{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@IBAction"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"didTapSegment"},{"kind":"text","text":"("},{"kind":"externalParam","text":"segment"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UISegmentedControl","preciseIdentifier":"c:objc(cs)UISegmentedControl"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/yababa\/discountscontainercontroller\/didtapsegment(segment:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/yababa\/discountscontainercontroller\/didtapsegment(segment:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/DiscountsContainerController\/didTapSegment(segment:)","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"didTapSegment"},{"kind":"text","text":"("},{"kind":"externalParam","text":"segment"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UISegmentedControl","preciseIdentifier":"c:objc(cs)UISegmentedControl"},{"kind":"text","text":")"}],"title":"didTapSegment(segment:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@M@Yababa@objc(cs)DiscountsContainerController(im)didTapSegmentWithSegment:","modules":[{"name":"Yababa"}],"navigatorTitle":[{"kind":"identifier","text":"didTapSegmentWithSegment:"}]},"hierarchy":{"paths":[["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/DiscountsContainerController"]]},"references":{"doc://com.yababaGmbH.yababa/documentation/Yababa/DiscountsContainerController/didTapSegment(segment:)":{"role":"symbol","title":"didTapSegment(segment:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"didTapSegment"},{"kind":"text","text":"("},{"kind":"externalParam","text":"segment"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UISegmentedControl","preciseIdentifier":"c:objc(cs)UISegmentedControl"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/DiscountsContainerController\/didTapSegment(segment:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"didTapSegmentWithSegment:"}],"url":"\/documentation\/yababa\/discountscontainercontroller\/didtapsegment(segment:)"},"doc://com.yababaGmbH.yababa/documentation/Yababa/DiscountsContainerController":{"role":"symbol","title":"DiscountsContainerController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DiscountsContainerController"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/DiscountsContainerController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DiscountsContainerController"}],"url":"\/documentation\/yababa\/discountscontainercontroller"},"doc://com.yababaGmbH.yababa/documentation/Yababa":{"role":"collection","title":"Yababa","abstract":[{"type":"text","text":"Getting Started"}],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa","kind":"symbol","type":"topic","url":"\/documentation\/yababa"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"didTapSegmentWithSegment:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"didTapSegmentWithSegment:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"didTapSegmentWithSegment:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UISegmentedControl","preciseIdentifier":"c:objc(cs)UISegmentedControl"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"segment"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1DiscountsContainerController~1didTapSegment(segment:)\/title","value":"didTapSegmentWithSegment:"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1DiscountsContainerController~1didTapSegment(segment:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"didTapSegmentWithSegment:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1DiscountsContainerController\/title","value":"DiscountsContainerController"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1DiscountsContainerController\/fragments","value":[{"kind":"identifier","text":"DiscountsContainerController"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}