{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@IBOutlet"},{"kind":"text","text":" "},{"kind":"keyword","text":"weak"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"segmentedControl"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UISegmentedControl","preciseIdentifier":"c:objc(cs)UISegmentedControl"},{"kind":"text","text":"!"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/yababa\/discountscontainercontroller\/segmentedcontrol"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/yababa\/discountscontainercontroller\/segmentedcontrol"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/DiscountsContainerController\/segmentedControl","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"segmentedControl"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UISegmentedControl","preciseIdentifier":"c:objc(cs)UISegmentedControl"},{"kind":"text","text":"!"}],"title":"segmentedControl","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:@M@Yababa@objc(cs)DiscountsContainerController(py)segmentedControl","modules":[{"name":"Yababa"}],"navigatorTitle":[{"kind":"identifier","text":"segmentedControl"}]},"hierarchy":{"paths":[["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/DiscountsContainerController"]]},"references":{"doc://com.yababaGmbH.yababa/documentation/Yababa":{"role":"collection","title":"Yababa","abstract":[{"type":"text","text":"Getting Started"}],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa","kind":"symbol","type":"topic","url":"\/documentation\/yababa"},"doc://com.yababaGmbH.yababa/documentation/Yababa/DiscountsContainerController":{"role":"symbol","title":"DiscountsContainerController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DiscountsContainerController"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/DiscountsContainerController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DiscountsContainerController"}],"url":"\/documentation\/yababa\/discountscontainercontroller"},"doc://com.yababaGmbH.yababa/documentation/Yababa/DiscountsContainerController/segmentedControl":{"role":"symbol","title":"segmentedControl","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"segmentedControl"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UISegmentedControl","preciseIdentifier":"c:objc(cs)UISegmentedControl"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/DiscountsContainerController\/segmentedControl","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"segmentedControl"}],"url":"\/documentation\/yababa\/discountscontainercontroller\/segmentedcontrol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"segmentedControl"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"segmentedControl"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"weak"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"UISegmentedControl","preciseIdentifier":"c:objc(cs)UISegmentedControl"},{"kind":"text","text":" * "},{"kind":"identifier","text":"segmentedControl"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1DiscountsContainerController\/title","value":"DiscountsContainerController"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1DiscountsContainerController\/fragments","value":[{"kind":"identifier","text":"DiscountsContainerController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1DiscountsContainerController~1segmentedControl\/title","value":"segmentedControl"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1DiscountsContainerController~1segmentedControl\/fragments","value":[{"kind":"identifier","text":"segmentedControl"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}