{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"discountsTabNeedsToBeViewed"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/yababa\/localuserstatemanager\/discountstabneedstobeviewed"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/yababa\/localuserstatemanager\/discountstabneedstobeviewed"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/LocalUserStateManager\/discountsTabNeedsToBeViewed","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"discountsTabNeedsToBeViewed"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"title":"discountsTabNeedsToBeViewed","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:@M@Yababa@objc(cs)LocalUserStateManager(py)discountsTabNeedsToBeViewed","modules":[{"name":"Yababa"}],"navigatorTitle":[{"kind":"identifier","text":"discountsTabNeedsToBeViewed"}]},"hierarchy":{"paths":[["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/LocalUserStateManager"]]},"references":{"doc://com.yababaGmbH.yababa/documentation/Yababa":{"role":"collection","title":"Yababa","abstract":[{"type":"text","text":"Getting Started"}],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa","kind":"symbol","type":"topic","url":"\/documentation\/yababa"},"doc://com.yababaGmbH.yababa/documentation/Yababa/LocalUserStateManager/discountsTabNeedsToBeViewed":{"role":"symbol","title":"discountsTabNeedsToBeViewed","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"discountsTabNeedsToBeViewed"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/LocalUserStateManager\/discountsTabNeedsToBeViewed","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"discountsTabNeedsToBeViewed"}],"url":"\/documentation\/yababa\/localuserstatemanager\/discountstabneedstobeviewed"},"doc://com.yababaGmbH.yababa/documentation/Yababa/LocalUserStateManager":{"role":"symbol","title":"LocalUserStateManager","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"LocalUserStateManager"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/LocalUserStateManager","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"LocalUserStateManager"}],"url":"\/documentation\/yababa\/localuserstatemanager"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"discountsTabNeedsToBeViewed"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"discountsTabNeedsToBeViewed"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"assign"},{"kind":"text","text":", "},{"kind":"keyword","text":"unsafe_unretained"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":" "},{"kind":"identifier","text":"discountsTabNeedsToBeViewed"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1LocalUserStateManager~1discountsTabNeedsToBeViewed\/title","value":"discountsTabNeedsToBeViewed"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1LocalUserStateManager~1discountsTabNeedsToBeViewed\/fragments","value":[{"kind":"identifier","text":"discountsTabNeedsToBeViewed"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1LocalUserStateManager\/title","value":"LocalUserStateManager"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1LocalUserStateManager\/fragments","value":[{"kind":"identifier","text":"LocalUserStateManager"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}