{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setSelectedPaymentCardID"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"creditCardID"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/yababa\/localuserstatemanager\/setselectedpaymentcardid(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/yababa\/localuserstatemanager\/setselectedpaymentcardid(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/LocalUserStateManager\/setSelectedPaymentCardID(_:)","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setSelectedPaymentCardID"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"title":"setSelectedPaymentCardID(_:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@M@Yababa@objc(cs)LocalUserStateManager(im)setSelectedPaymentCardID:","modules":[{"name":"Yababa"}],"navigatorTitle":[{"kind":"identifier","text":"setSelectedPaymentCardID:"}]},"hierarchy":{"paths":[["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/LocalUserStateManager"]]},"references":{"doc://com.yababaGmbH.yababa/documentation/Yababa":{"role":"collection","title":"Yababa","abstract":[{"type":"text","text":"Getting Started"}],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa","kind":"symbol","type":"topic","url":"\/documentation\/yababa"},"doc://com.yababaGmbH.yababa/documentation/Yababa/LocalUserStateManager":{"role":"symbol","title":"LocalUserStateManager","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"LocalUserStateManager"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/LocalUserStateManager","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"LocalUserStateManager"}],"url":"\/documentation\/yababa\/localuserstatemanager"},"doc://com.yababaGmbH.yababa/documentation/Yababa/LocalUserStateManager/setSelectedPaymentCardID(_:)":{"role":"symbol","title":"setSelectedPaymentCardID(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setSelectedPaymentCardID"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/LocalUserStateManager\/setSelectedPaymentCardID(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"setSelectedPaymentCardID:"}],"url":"\/documentation\/yababa\/localuserstatemanager\/setselectedpaymentcardid(_:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"setSelectedPaymentCardID:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setSelectedPaymentCardID:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"setSelectedPaymentCardID:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"},{"kind":"text","text":")"},{"kind":"internalParam","text":"creditCardID"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1LocalUserStateManager\/title","value":"LocalUserStateManager"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1LocalUserStateManager\/fragments","value":[{"kind":"identifier","text":"LocalUserStateManager"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1LocalUserStateManager~1setSelectedPaymentCardID(_:)\/title","value":"setSelectedPaymentCardID:"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1LocalUserStateManager~1setSelectedPaymentCardID(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setSelectedPaymentCardID:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}