{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"myProfile"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/Profile","preciseIdentifier":"c:@M@Yababa@objc(cs)Profile","text":"Profile"},{"kind":"text","text":"! { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/yababa\/userdata\/myprofile"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/yababa\/userdata\/myprofile"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/UserData\/myProfile","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"myProfile"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Profile","preciseIdentifier":"c:@M@Yababa@objc(cs)Profile"},{"kind":"text","text":"!"}],"title":"myProfile","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:objc(cs)UserData(py)myProfile","modules":[{"name":"Yababa"}],"navigatorTitle":[{"kind":"identifier","text":"myProfile"}]},"hierarchy":{"paths":[["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/UserData"]]},"references":{"doc://com.yababaGmbH.yababa/documentation/Yababa/UserData/myProfile":{"role":"symbol","title":"myProfile","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"myProfile"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Profile","preciseIdentifier":"c:@M@Yababa@objc(cs)Profile"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/UserData\/myProfile","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"myProfile"}],"url":"\/documentation\/yababa\/userdata\/myprofile"},"doc://com.yababaGmbH.yababa/documentation/Yababa":{"role":"collection","title":"Yababa","abstract":[{"type":"text","text":"Getting Started"}],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa","kind":"symbol","type":"topic","url":"\/documentation\/yababa"},"doc://com.yababaGmbH.yababa/documentation/Yababa/Profile":{"role":"symbol","title":"Profile","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Profile"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/Profile","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Profile"}],"url":"\/documentation\/yababa\/profile"},"doc://com.yababaGmbH.yababa/documentation/Yababa/UserData":{"role":"symbol","title":"UserData","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"UserData"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/UserData","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"UserData"}],"url":"\/documentation\/yababa\/userdata"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"myProfile"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"myProfile"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"retain"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"Profile","preciseIdentifier":"c:objc(cs)Profile"},{"kind":"text","text":" * "},{"kind":"identifier","text":"myProfile"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1UserData~1myProfile\/title","value":"myProfile"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1UserData~1myProfile\/fragments","value":[{"kind":"identifier","text":"myProfile"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1Profile\/title","value":"Profile"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1Profile\/fragments","value":[{"kind":"identifier","text":"Profile"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1UserData\/title","value":"UserData"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1UserData\/fragments","value":[{"kind":"identifier","text":"UserData"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}