{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onClearCart"},{"kind":"text","text":"()"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/yababa\/shoppingcartsceneviewcontroller\/onclearcart()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/yababa\/shoppingcartsceneviewcontroller\/onclearcart()"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ShoppingCartSceneViewController\/onClearCart()","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onClearCart"},{"kind":"text","text":"()"}],"title":"onClearCart()","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@M@Yababa@objc(cs)ShoppingCartSceneViewController(im)onClearCart","modules":[{"name":"Yababa"}],"navigatorTitle":[{"kind":"identifier","text":"onClearCart"}]},"hierarchy":{"paths":[["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ShoppingCartSceneViewController"]]},"references":{"doc://com.yababaGmbH.yababa/documentation/Yababa":{"role":"collection","title":"Yababa","abstract":[{"type":"text","text":"Getting Started"}],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa","kind":"symbol","type":"topic","url":"\/documentation\/yababa"},"doc://com.yababaGmbH.yababa/documentation/Yababa/ShoppingCartSceneViewController":{"role":"symbol","title":"ShoppingCartSceneViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ShoppingCartSceneViewController"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ShoppingCartSceneViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ShoppingCartSceneViewController"}],"url":"\/documentation\/yababa\/shoppingcartsceneviewcontroller"},"doc://com.yababaGmbH.yababa/documentation/Yababa/ShoppingCartSceneViewController/onClearCart()":{"role":"symbol","title":"onClearCart()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onClearCart"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ShoppingCartSceneViewController\/onClearCart()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"onClearCart"}],"url":"\/documentation\/yababa\/shoppingcartsceneviewcontroller\/onclearcart()"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"onClearCart"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onClearCart"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"onClearCart"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1ShoppingCartSceneViewController\/title","value":"ShoppingCartSceneViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1ShoppingCartSceneViewController\/fragments","value":[{"kind":"identifier","text":"ShoppingCartSceneViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1ShoppingCartSceneViewController~1onClearCart()\/title","value":"onClearCart"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1ShoppingCartSceneViewController~1onClearCart()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onClearCart"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}