{"primaryContentSections":[{"kind":"content","content":[{"anchor":"Overview","level":2,"type":"heading","text":"Overview"},{"type":"paragraph","inlineContent":[{"type":"text","text":"The Checkout and payment module is crucial component that allows customers to place orders, select a payment method, and complete the transaction. This document provides an overview of the functionality and flows of the checkout process."}]},{"anchor":"Checkout-Screen","level":3,"type":"heading","text":"Checkout Screen"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Checkout Screen provides user to review:"}]},{"type":"orderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Delviery Address"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Selected Time Slot for delivery"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Cost Summary (delivery fees, discounts, total price)"}]}]}]},{"anchor":"Checkout-Flow","level":2,"type":"heading","text":"Checkout Flow"},{"type":"paragraph","inlineContent":[{"type":"text","text":"The cart is maintained locally on the device. However, the cost is calculated in the backend to ensure accuracy and consistency in the pricing of items, delivery fee and total cost."}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"The checkout process takes the list of cart items from app to the backend. Once the app receives the calculated price, it calls the payment SDK to perform the actual payment."}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"The process is as follows:"}]},{"type":"orderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"App sends user’s address, selected time slot and the list of items to be purcahsed to the backend through PrepareCartCheckout "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CheckoutSceneInteractor\/prepareCartCheckout()"},{"type":"text","text":"."}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Server calculates the cost resturns the information in an encrypted response which we refer as secure checkout bean."}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"App decrypts the information into "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CheckoutBean"},{"type":"text","text":", which is used to display the neccessary information to the user."}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"User taps on confirm button and is presented with list of possible payment methods."}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"User selects a payment method."}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"User taps on Checkout. App calls Confirm Checkout "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CheckoutSceneInteractor\/confirmCheckout()"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"User is navigated to the payment gateway (e.g. paypal SDK)"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"User performs the actual payment in the payment gateway."}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The payment gateway returns back with status to the Checkout Interactor"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Payment gateway returns the status to the "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ShoppingCartPaymentFlowProcessor"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"ShoppingCartPaymentFlowProcessor posts the status to the Backend to confirm that the payment has either succceeded or failed."}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"User is taken to Order Details Screen after success."}]}]}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"Note:"}]},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"In case of saved credit card (through stripe), the Checkout Interactor posts the payment result status to the server."}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Confirm Checkout reserves the selected items (products) for 10 minutes. The API "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/OnlineBookingController\/onlineActivityBookingCancel(sessionId:completion:)"},{"type":"text","text":" releases them."}]}]}]},{"anchor":"References","level":4,"type":"heading","text":"References"},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Checkout"}]},{"type":"paragraph","inlineContent":[{"type":"reference","isActive":true,"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CheckoutSceneViewController"}]},{"type":"paragraph","inlineContent":[{"type":"reference","isActive":true,"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CheckoutSceneInteractor"}]},{"type":"paragraph","inlineContent":[{"type":"reference","isActive":true,"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CheckoutScenePresenter"}]},{"type":"paragraph","inlineContent":[{"type":"reference","isActive":true,"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CheckoutSceneRouter"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Prepare Cart Checkout"}]},{"type":"paragraph","inlineContent":[{"type":"reference","isActive":true,"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CheckoutSceneInteractor\/prepareCartCheckout()"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Confirm Checkout"}]},{"type":"paragraph","inlineContent":[{"type":"reference","isActive":true,"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CheckoutSceneInteractor\/confirmCheckout()"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Post Payment Success"}]},{"type":"paragraph","inlineContent":[{"type":"reference","isActive":true,"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ShoppingCartPaymentFlowProcessor\/onPaymentSuccess(sessionId:allowRetrial:)"}]}]}]},{"anchor":"Payment-Gateways","level":2,"type":"heading","text":"Payment Gateways"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Users can pay through following payment methods"}]},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Credit Card"}]},{"type":"paragraph","inlineContent":[{"type":"reference","isActive":true,"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/StripeCreditCardPay"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Apple Pay"}]},{"type":"paragraph","inlineContent":[{"type":"reference","isActive":true,"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/StripeApplePay"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Giro Pay"}]},{"type":"paragraph","inlineContent":[{"type":"reference","isActive":true,"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/StripeGiroPay"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"PayPal"}]},{"type":"paragraph","inlineContent":[{"type":"reference","isActive":true,"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/PaypalPaymentProcessManager"}]}]}]},{"type":"paragraph","inlineContent":[{"type":"image","identifier":"PaymentGateway.png"}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"Stripe and Paypal are the two payment SDKs integrated in the app. To standarize the gateways, both implement the "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/PaymentProcessManager"},{"type":"text","text":" protocol."}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"Default Credit card payment is made through Stripe. Apple pay and Giro pay are also based on Stripe’s SDK implementation. Thus they implement the Stripe  "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/PaymentSubMethod"},{"type":"text","text":" protocol."}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"Checkout Router holds a Flow Processor "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ShoppingCartPaymentFlowProcessor"},{"type":"text","text":", which is passed down to the "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/PaymentProcessManager"},{"type":"text","text":" (Stripe or PayPal). The ShoppingCartPaymentFlowProcessor acts like a delegate which posts the payment status to the server and lets it’s delegate (the checkout view controller) to show appropriate response in a view (success\/fail message box)."}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/yababa\/-checkoutoverview"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/yababa\/-checkoutoverview"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/-CheckoutOverview","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Checkout flow between the app, backend and payment gateway"}],"kind":"article","metadata":{"roleHeading":"Article","title":"Checkout","role":"article","modules":[{"name":"Yababa"}]},"hierarchy":{"paths":[["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa"]]},"references":{"doc://com.yababaGmbH.yababa/documentation/Yababa/CheckoutSceneInteractor/prepareCartCheckout()":{"role":"symbol","title":"prepareCartCheckout()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"prepareCartCheckout"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CheckoutSceneInteractor\/prepareCartCheckout()","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/checkoutsceneinteractor\/preparecartcheckout()"},"doc://com.yababaGmbH.yababa/documentation/Yababa/PaymentProcessManager":{"role":"symbol","title":"PaymentProcessManager","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"PaymentProcessManager"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/PaymentProcessManager","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PaymentProcessManager"}],"url":"\/documentation\/yababa\/paymentprocessmanager"},"PaymentGateway.png":{"alt":"Payment Gateways","type":"image","identifier":"PaymentGateway.png","variants":[{"url":"\/images\/PaymentGateway@2x.png","traits":["2x","light"]}]},"doc://com.yababaGmbH.yababa/documentation/Yababa/StripeCreditCardPay":{"role":"symbol","title":"StripeCreditCardPay","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"StripeCreditCardPay"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/StripeCreditCardPay","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"StripeCreditCardPay"}],"url":"\/documentation\/yababa\/stripecreditcardpay"},"doc://com.yababaGmbH.yababa/documentation/Yababa/StripeApplePay":{"role":"symbol","title":"StripeApplePay","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"StripeApplePay"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/StripeApplePay","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"StripeApplePay"}],"url":"\/documentation\/yababa\/stripeapplepay"},"doc://com.yababaGmbH.yababa/documentation/Yababa":{"role":"collection","title":"Yababa","abstract":[{"type":"text","text":"Getting Started"}],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa","kind":"symbol","type":"topic","url":"\/documentation\/yababa"},"doc://com.yababaGmbH.yababa/documentation/Yababa/OnlineBookingController/onlineActivityBookingCancel(sessionId:completion:)":{"role":"symbol","title":"onlineActivityBookingCancel(sessionId:completion:)","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onlineActivityBookingCancel"},{"kind":"text","text":"("},{"kind":"externalParam","text":"sessionId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": ("},{"kind":"typeIdentifier","text":"Result","preciseIdentifier":"s:s6ResultO"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"ResponsePayload","preciseIdentifier":"s:6Yababa15ResponsePayloadC"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":">) -> ())"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/OnlineBookingController\/onlineActivityBookingCancel(sessionId:completion:)","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/onlinebookingcontroller\/onlineactivitybookingcancel(sessionid:completion:)"},"doc://com.yababaGmbH.yababa/documentation/Yababa/PaymentSubMethod":{"role":"symbol","title":"PaymentSubMethod","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"PaymentSubMethod"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/PaymentSubMethod","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PaymentSubMethod"}],"url":"\/documentation\/yababa\/paymentsubmethod"},"doc://com.yababaGmbH.yababa/documentation/Yababa/StripeGiroPay":{"role":"symbol","title":"StripeGiroPay","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"StripeGiroPay"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/StripeGiroPay","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"StripeGiroPay"}],"url":"\/documentation\/yababa\/stripegiropay"},"doc://com.yababaGmbH.yababa/documentation/Yababa/CheckoutScenePresenter":{"role":"symbol","title":"CheckoutScenePresenter","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CheckoutScenePresenter"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CheckoutScenePresenter","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CheckoutScenePresenter"}],"url":"\/documentation\/yababa\/checkoutscenepresenter"},"doc://com.yababaGmbH.yababa/documentation/Yababa/CheckoutSceneViewController":{"role":"symbol","title":"CheckoutSceneViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CheckoutSceneViewController"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CheckoutSceneViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CheckoutSceneViewController"}],"url":"\/documentation\/yababa\/checkoutsceneviewcontroller"},"doc://com.yababaGmbH.yababa/documentation/Yababa/ShoppingCartPaymentFlowProcessor/onPaymentSuccess(sessionId:allowRetrial:)":{"role":"symbol","title":"onPaymentSuccess(sessionId:allowRetrial:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onPaymentSuccess"},{"kind":"text","text":"("},{"kind":"externalParam","text":"sessionId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"allowRetrial"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ShoppingCartPaymentFlowProcessor\/onPaymentSuccess(sessionId:allowRetrial:)","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/shoppingcartpaymentflowprocessor\/onpaymentsuccess(sessionid:allowretrial:)"},"doc://com.yababaGmbH.yababa/documentation/Yababa/ShoppingCartPaymentFlowProcessor":{"role":"symbol","title":"ShoppingCartPaymentFlowProcessor","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ShoppingCartPaymentFlowProcessor"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ShoppingCartPaymentFlowProcessor","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ShoppingCartPaymentFlowProcessor"}],"url":"\/documentation\/yababa\/shoppingcartpaymentflowprocessor"},"doc://com.yababaGmbH.yababa/documentation/Yababa/CheckoutSceneInteractor":{"role":"symbol","title":"CheckoutSceneInteractor","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CheckoutSceneInteractor"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CheckoutSceneInteractor","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CheckoutSceneInteractor"}],"url":"\/documentation\/yababa\/checkoutsceneinteractor"},"doc://com.yababaGmbH.yababa/documentation/Yababa/CheckoutSceneRouter":{"role":"symbol","title":"CheckoutSceneRouter","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CheckoutSceneRouter"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CheckoutSceneRouter","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CheckoutSceneRouter"}],"url":"\/documentation\/yababa\/checkoutscenerouter"},"doc://com.yababaGmbH.yababa/documentation/Yababa/PaypalPaymentProcessManager":{"role":"symbol","title":"PaypalPaymentProcessManager","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PaypalPaymentProcessManager"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/PaypalPaymentProcessManager","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PaypalPaymentProcessManager"}],"url":"\/documentation\/yababa\/paypalpaymentprocessmanager"},"doc://com.yababaGmbH.yababa/documentation/Yababa/CheckoutBean":{"role":"symbol","title":"CheckoutBean","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CheckoutBean"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CheckoutBean","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CheckoutBean"}],"url":"\/documentation\/yababa\/checkoutbean"},"doc://com.yababaGmbH.yababa/documentation/Yababa/CheckoutSceneInteractor/confirmCheckout()":{"role":"symbol","title":"confirmCheckout()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"confirmCheckout"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CheckoutSceneInteractor\/confirmCheckout()","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/checkoutsceneinteractor\/confirmcheckout()"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1StripeCreditCardPay\/title","value":"StripeCreditCardPay"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1StripeCreditCardPay\/fragments","value":[{"kind":"identifier","text":"StripeCreditCardPay"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1StripeApplePay\/title","value":"StripeApplePay"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1StripeApplePay\/fragments","value":[{"kind":"identifier","text":"StripeApplePay"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1StripeGiroPay\/title","value":"StripeGiroPay"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1StripeGiroPay\/fragments","value":[{"kind":"identifier","text":"StripeGiroPay"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1CheckoutSceneViewController\/title","value":"CheckoutSceneViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1CheckoutSceneViewController\/fragments","value":[{"kind":"identifier","text":"CheckoutSceneViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1ShoppingCartPaymentFlowProcessor\/title","value":"ShoppingCartPaymentFlowProcessor"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1ShoppingCartPaymentFlowProcessor\/fragments","value":[{"kind":"identifier","text":"ShoppingCartPaymentFlowProcessor"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1CheckoutSceneInteractor\/title","value":"CheckoutSceneInteractor"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1CheckoutSceneInteractor\/fragments","value":[{"kind":"identifier","text":"CheckoutSceneInteractor"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1CheckoutSceneRouter\/title","value":"CheckoutSceneRouter"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1CheckoutSceneRouter\/fragments","value":[{"kind":"identifier","text":"CheckoutSceneRouter"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1PaypalPaymentProcessManager\/title","value":"PaypalPaymentProcessManager"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1PaypalPaymentProcessManager\/fragments","value":[{"kind":"identifier","text":"PaypalPaymentProcessManager"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}