{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AddressManagerViewNavigator"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/yababa\/addressmanagerviewnavigator"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/yababa\/addressmanagerviewnavigator"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.yababaGmbH.yababa\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AddAddressDetailsDelegate","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AddressSelectionListDelegate","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AddressSelectionManager","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/DeliveryAreasSceneDelegate","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/InvalidAddressSelectionDelegate","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/LocationDelegate","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/MapsViewDelegate","doc:\/\/com.yababaGmbH.yababa\/objc(pl)NSObject","doc:\/\/com.yababaGmbH.yababa\/12SkeletonView17AssociatedObjectsP","doc:\/\/com.yababaGmbH.yababa\/s7CVarArgP","doc:\/\/com.yababaGmbH.yababa\/s28CustomDebugStringConvertibleP","doc:\/\/com.yababaGmbH.yababa\/s23CustomStringConvertibleP","doc:\/\/com.yababaGmbH.yababa\/SQ","doc:\/\/com.yababaGmbH.yababa\/SH","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/WeWillNotifyYouSceneDelegate"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AddressManagerViewNavigator","interfaceLanguage":"swift"},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AddressManagerViewNavigator\/init(parentViewController:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AddressManagerViewNavigator\/delegate","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AddressManagerViewNavigator\/parentViewController"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AddressManagerViewNavigator\/closeProcess()","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AddressManagerViewNavigator\/confirmIfAddressChangeWillResultInCartReset(address:completion:)","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AddressManagerViewNavigator\/onGetNotified()","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AddressManagerViewNavigator\/showAddAddressDetails(_:)","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AddressManagerViewNavigator\/showAddAddressFromMapView(withBackButton:)","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AddressManagerViewNavigator\/showAddressSelectionList(_:)","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AddressManagerViewNavigator\/showInvalidAddress(addressValidationResponse:)","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AddressManagerViewNavigator\/showSelectedAddress(_:addressHasDifferentWarehouseThanBefore:)","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AddressManagerViewNavigator\/showWeWillNotifyYouMessage()"]},{"title":"Default Implementations","identifiers":["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AddressManagerViewNavigator\/AddAddressDetailsDelegate-Implementations","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AddressManagerViewNavigator\/AddressSelectionListDelegate-Implementations","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AddressManagerViewNavigator\/DeliveryAreasSceneDelegate-Implementations","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AddressManagerViewNavigator\/InvalidAddressSelectionDelegate-Implementations","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AddressManagerViewNavigator\/LocationDelegate-Implementations","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AddressManagerViewNavigator\/MapsViewDelegate-Implementations","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AddressManagerViewNavigator\/WeWillNotifyYouSceneDelegate-Implementations"],"generated":true}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AddressManagerViewNavigator"}],"title":"AddressManagerViewNavigator","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@Yababa@objc(cs)AddressManagerViewNavigator","modules":[{"name":"Yababa"}],"navigatorTitle":[{"kind":"identifier","text":"AddressManagerViewNavigator"}]},"hierarchy":{"paths":[["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa"]]},"references":{"doc://com.yababaGmbH.yababa/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.yababaGmbH.yababa\/SQ"},"doc://com.yababaGmbH.yababa/documentation/Yababa/AddAddressDetailsDelegate":{"role":"symbol","title":"AddAddressDetailsDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"AddAddressDetailsDelegate"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AddAddressDetailsDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AddAddressDetailsDelegate"}],"url":"\/documentation\/yababa\/addaddressdetailsdelegate"},"doc://com.yababaGmbH.yababa/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.yababaGmbH.yababa\/s23CustomStringConvertibleP"},"doc://com.yababaGmbH.yababa/documentation/Yababa/AddressManagerViewNavigator/AddAddressDetailsDelegate-Implementations":{"role":"collectionGroup","title":"AddAddressDetailsDelegate Implementations","abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AddressManagerViewNavigator\/AddAddressDetailsDelegate-Implementations","kind":"article","type":"topic","url":"\/documentation\/yababa\/addressmanagerviewnavigator\/addaddressdetailsdelegate-implementations"},"doc://com.yababaGmbH.yababa/documentation/Yababa/AddressManagerViewNavigator/DeliveryAreasSceneDelegate-Implementations":{"role":"collectionGroup","title":"DeliveryAreasSceneDelegate Implementations","abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AddressManagerViewNavigator\/DeliveryAreasSceneDelegate-Implementations","kind":"article","type":"topic","url":"\/documentation\/yababa\/addressmanagerviewnavigator\/deliveryareasscenedelegate-implementations"},"doc://com.yababaGmbH.yababa/documentation/Yababa/AddressManagerViewNavigator/showWeWillNotifyYouMessage()":{"role":"symbol","title":"showWeWillNotifyYouMessage()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"showWeWillNotifyYouMessage"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AddressManagerViewNavigator\/showWeWillNotifyYouMessage()","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/addressmanagerviewnavigator\/showwewillnotifyyoumessage()"},"doc://com.yababaGmbH.yababa/documentation/Yababa/AddressManagerViewNavigator/InvalidAddressSelectionDelegate-Implementations":{"role":"collectionGroup","title":"InvalidAddressSelectionDelegate Implementations","abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AddressManagerViewNavigator\/InvalidAddressSelectionDelegate-Implementations","kind":"article","type":"topic","url":"\/documentation\/yababa\/addressmanagerviewnavigator\/invalidaddressselectiondelegate-implementations"},"doc://com.yababaGmbH.yababa/documentation/Yababa/AddressManagerViewNavigator/showAddAddressDetails(_:)":{"role":"symbol","title":"showAddAddressDetails(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"showAddAddressDetails"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Address","preciseIdentifier":"s:6Yababa7AddressC"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AddressManagerViewNavigator\/showAddAddressDetails(_:)","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/addressmanagerviewnavigator\/showaddaddressdetails(_:)"},"doc://com.yababaGmbH.yababa/documentation/Yababa/AddressManagerViewNavigator/showAddAddressFromMapView(withBackButton:)":{"role":"symbol","title":"showAddAddressFromMapView(withBackButton:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"showAddAddressFromMapView"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withBackButton"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AddressManagerViewNavigator\/showAddAddressFromMapView(withBackButton:)","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/addressmanagerviewnavigator\/showaddaddressfrommapview(withbackbutton:)"},"doc://com.yababaGmbH.yababa/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(cs)NSObject"},"doc://com.yababaGmbH.yababa/documentation/Yababa/AddressManagerViewNavigator/delegate":{"role":"symbol","title":"delegate","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"delegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AddressSelectionDelegate","preciseIdentifier":"s:6Yababa24AddressSelectionDelegateP"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AddressManagerViewNavigator\/delegate","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/addressmanagerviewnavigator\/delegate"},"doc://com.yababaGmbH.yababa/documentation/Yababa/AddressManagerViewNavigator":{"role":"symbol","title":"AddressManagerViewNavigator","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AddressManagerViewNavigator"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AddressManagerViewNavigator","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AddressManagerViewNavigator"}],"url":"\/documentation\/yababa\/addressmanagerviewnavigator"},"doc://com.yababaGmbH.yababa/documentation/Yababa/AddressSelectionListDelegate":{"role":"symbol","title":"AddressSelectionListDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"AddressSelectionListDelegate"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AddressSelectionListDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AddressSelectionListDelegate"}],"url":"\/documentation\/yababa\/addressselectionlistdelegate"},"doc://com.yababaGmbH.yababa/documentation/Yababa/AddressManagerViewNavigator/MapsViewDelegate-Implementations":{"role":"collectionGroup","title":"MapsViewDelegate Implementations","abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AddressManagerViewNavigator\/MapsViewDelegate-Implementations","kind":"article","type":"topic","url":"\/documentation\/yababa\/addressmanagerviewnavigator\/mapsviewdelegate-implementations"},"doc://com.yababaGmbH.yababa/documentation/Yababa":{"role":"collection","title":"Yababa","abstract":[{"type":"text","text":"Getting Started"}],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa","kind":"symbol","type":"topic","url":"\/documentation\/yababa"},"doc://com.yababaGmbH.yababa/documentation/Yababa/AddressManagerViewNavigator/LocationDelegate-Implementations":{"role":"collectionGroup","title":"LocationDelegate Implementations","abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AddressManagerViewNavigator\/LocationDelegate-Implementations","kind":"article","type":"topic","url":"\/documentation\/yababa\/addressmanagerviewnavigator\/locationdelegate-implementations"},"doc://com.yababaGmbH.yababa/documentation/Yababa/AddressManagerViewNavigator/showInvalidAddress(addressValidationResponse:)":{"role":"symbol","title":"showInvalidAddress(addressValidationResponse:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"showInvalidAddress"},{"kind":"text","text":"("},{"kind":"externalParam","text":"addressValidationResponse"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AddressValidationResponse","preciseIdentifier":"s:6Yababa25AddressValidationResponseC"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AddressManagerViewNavigator\/showInvalidAddress(addressValidationResponse:)","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/addressmanagerviewnavigator\/showinvalidaddress(addressvalidationresponse:)"},"doc://com.yababaGmbH.yababa/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.yababaGmbH.yababa\/SH"},"doc://com.yababaGmbH.yababa/documentation/Yababa/AddressManagerViewNavigator/WeWillNotifyYouSceneDelegate-Implementations":{"role":"collectionGroup","title":"WeWillNotifyYouSceneDelegate Implementations","abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AddressManagerViewNavigator\/WeWillNotifyYouSceneDelegate-Implementations","kind":"article","type":"topic","url":"\/documentation\/yababa\/addressmanagerviewnavigator\/wewillnotifyyouscenedelegate-implementations"},"doc://com.yababaGmbH.yababa/documentation/Yababa/AddressManagerViewNavigator/closeProcess()":{"role":"symbol","title":"closeProcess()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"closeProcess"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AddressManagerViewNavigator\/closeProcess()","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/addressmanagerviewnavigator\/closeprocess()"},"doc://com.yababaGmbH.yababa/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)NSObject"},"doc://com.yababaGmbH.yababa/documentation/Yababa/WeWillNotifyYouSceneDelegate":{"role":"symbol","title":"WeWillNotifyYouSceneDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"WeWillNotifyYouSceneDelegate"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/WeWillNotifyYouSceneDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"WeWillNotifyYouSceneDelegate"}],"url":"\/documentation\/yababa\/wewillnotifyyouscenedelegate"},"doc://com.yababaGmbH.yababa/documentation/Yababa/AddressManagerViewNavigator/parentViewController":{"role":"symbol","title":"parentViewController","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"parentViewController"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AddressManagerOwner","preciseIdentifier":"s:6Yababa19AddressManagerOwnerP"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AddressManagerViewNavigator\/parentViewController","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/addressmanagerviewnavigator\/parentviewcontroller"},"doc://com.yababaGmbH.yababa/documentation/Yababa/AddressManagerViewNavigator/init(parentViewController:)":{"role":"symbol","title":"init(parentViewController:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"parentViewController"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AddressManagerOwner","preciseIdentifier":"s:6Yababa19AddressManagerOwnerP"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AddressManagerViewNavigator\/init(parentViewController:)","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/addressmanagerviewnavigator\/init(parentviewcontroller:)"},"doc://com.yababaGmbH.yababa/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.yababaGmbH.yababa\/s7CVarArgP"},"doc://com.yababaGmbH.yababa/documentation/Yababa/LocationDelegate":{"role":"symbol","title":"LocationDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"LocationDelegate"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/LocationDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"LocationDelegate"}],"url":"\/documentation\/yababa\/locationdelegate"},"doc://com.yababaGmbH.yababa/documentation/Yababa/AddressManagerViewNavigator/showSelectedAddress(_:addressHasDifferentWarehouseThanBefore:)":{"role":"symbol","title":"showSelectedAddress(_:addressHasDifferentWarehouseThanBefore:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"showSelectedAddress"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Address","preciseIdentifier":"s:6Yababa7AddressC"},{"kind":"text","text":", "},{"kind":"externalParam","text":"addressHasDifferentWarehouseThanBefore"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AddressManagerViewNavigator\/showSelectedAddress(_:addressHasDifferentWarehouseThanBefore:)","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/addressmanagerviewnavigator\/showselectedaddress(_:addresshasdifferentwarehousethanbefore:)"},"doc://com.yababaGmbH.yababa/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.yababaGmbH.yababa\/s28CustomDebugStringConvertibleP"},"doc://com.yababaGmbH.yababa/documentation/Yababa/AddressManagerViewNavigator/onGetNotified()":{"role":"symbol","title":"onGetNotified()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onGetNotified"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AddressManagerViewNavigator\/onGetNotified()","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/addressmanagerviewnavigator\/ongetnotified()"},"doc://com.yababaGmbH.yababa/documentation/Yababa/MapsViewDelegate":{"role":"symbol","title":"MapsViewDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"MapsViewDelegate"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/MapsViewDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MapsViewDelegate"}],"url":"\/documentation\/yababa\/mapsviewdelegate"},"doc://com.yababaGmbH.yababa/documentation/Yababa/AddressManagerViewNavigator/showAddressSelectionList(_:)":{"role":"symbol","title":"showAddressSelectionList(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"showAddressSelectionList"},{"kind":"text","text":"(["},{"kind":"typeIdentifier","text":"Address","preciseIdentifier":"s:6Yababa7AddressC"},{"kind":"text","text":"])"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AddressManagerViewNavigator\/showAddressSelectionList(_:)","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/addressmanagerviewnavigator\/showaddressselectionlist(_:)"},"doc://com.yababaGmbH.yababa/documentation/Yababa/DeliveryAreasSceneDelegate":{"role":"symbol","title":"DeliveryAreasSceneDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"DeliveryAreasSceneDelegate"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/DeliveryAreasSceneDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DeliveryAreasSceneDelegate"}],"url":"\/documentation\/yababa\/deliveryareasscenedelegate"},"doc://com.yababaGmbH.yababa/documentation/Yababa/AddressManagerViewNavigator/AddressSelectionListDelegate-Implementations":{"role":"collectionGroup","title":"AddressSelectionListDelegate Implementations","abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AddressManagerViewNavigator\/AddressSelectionListDelegate-Implementations","kind":"article","type":"topic","url":"\/documentation\/yababa\/addressmanagerviewnavigator\/addressselectionlistdelegate-implementations"},"doc://com.yababaGmbH.yababa/12SkeletonView17AssociatedObjectsP":{"type":"unresolvable","title":"SkeletonView.AssociatedObjects","identifier":"doc:\/\/com.yababaGmbH.yababa\/12SkeletonView17AssociatedObjectsP"},"doc://com.yababaGmbH.yababa/documentation/Yababa/AddressManagerViewNavigator/confirmIfAddressChangeWillResultInCartReset(address:completion:)":{"role":"symbol","title":"confirmIfAddressChangeWillResultInCartReset(address:completion:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"confirmIfAddressChangeWillResultInCartReset"},{"kind":"text","text":"("},{"kind":"externalParam","text":"address"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Address","preciseIdentifier":"s:6Yababa7AddressC"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": ("},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":") -> ())"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AddressManagerViewNavigator\/confirmIfAddressChangeWillResultInCartReset(address:completion:)","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/addressmanagerviewnavigator\/confirmifaddresschangewillresultincartreset(address:completion:)"},"doc://com.yababaGmbH.yababa/documentation/Yababa/InvalidAddressSelectionDelegate":{"role":"symbol","title":"InvalidAddressSelectionDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"InvalidAddressSelectionDelegate"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/InvalidAddressSelectionDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"InvalidAddressSelectionDelegate"}],"url":"\/documentation\/yababa\/invalidaddressselectiondelegate"},"doc://com.yababaGmbH.yababa/documentation/Yababa/AddressSelectionManager":{"role":"symbol","title":"AddressSelectionManager","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"AddressSelectionManager"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AddressSelectionManager","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AddressSelectionManager"}],"url":"\/documentation\/yababa\/addressselectionmanager"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"AddressManagerViewNavigator"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AddressManagerViewNavigator"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"AddressManagerViewNavigator"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Default Implementations","identifiers":["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AddressManagerViewNavigator\/LocationDelegate-Implementations"],"generated":true}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.yababaGmbH.yababa\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"AddressManagerViewNavigator"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1AddressManagerViewNavigator\/title","value":"AddressManagerViewNavigator"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1AddressManagerViewNavigator\/fragments","value":[{"kind":"identifier","text":"AddressManagerViewNavigator"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1LocationDelegate\/title","value":"LocationDelegate"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1LocationDelegate\/fragments","value":[{"kind":"identifier","text":"LocationDelegate"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}