{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"AddressManagerOwner"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/yababa\/addressmanagerowner"],"traits":[{"interfaceLanguage":"swift"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.yababaGmbH.yababa\/objc(cs)UIViewController"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CheckoutSceneViewController","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/HomeScreen"],"kind":"relationships","title":"Conforming Types","type":"conformingTypes"}],"identifier":{"url":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AddressManagerOwner","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AddressManagerOwner\/addressManagerInteractor","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AddressManagerOwner\/addressSelectionManager","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AddressManagerOwner\/userAddressManager"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AddressManagerOwner\/closeAddressManager()-5tlf1","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AddressManagerOwner\/didSelectAddress(_:addressHasDifferentWarehouseThanBefore:)"]}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"AddressManagerOwner"}],"title":"AddressManagerOwner","roleHeading":"Protocol","role":"symbol","symbolKind":"protocol","externalID":"s:6Yababa19AddressManagerOwnerP","modules":[{"name":"Yababa"}],"navigatorTitle":[{"kind":"identifier","text":"AddressManagerOwner"}]},"hierarchy":{"paths":[["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa"]]},"references":{"doc://com.yababaGmbH.yababa/documentation/Yababa/AddressManagerOwner":{"role":"symbol","title":"AddressManagerOwner","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"AddressManagerOwner"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AddressManagerOwner","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AddressManagerOwner"}],"url":"\/documentation\/yababa\/addressmanagerowner"},"doc://com.yababaGmbH.yababa/documentation/Yababa/HomeScreen":{"role":"symbol","title":"HomeScreen","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HomeScreen"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/HomeScreen","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HomeScreen"}],"url":"\/documentation\/yababa\/homescreen"},"doc://com.yababaGmbH.yababa/documentation/Yababa":{"role":"collection","title":"Yababa","abstract":[{"type":"text","text":"Getting Started"}],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa","kind":"symbol","type":"topic","url":"\/documentation\/yababa"},"doc://com.yababaGmbH.yababa/documentation/Yababa/AddressManagerOwner/didSelectAddress(_:addressHasDifferentWarehouseThanBefore:)":{"role":"symbol","title":"didSelectAddress(_:addressHasDifferentWarehouseThanBefore:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"didSelectAddress"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Address","preciseIdentifier":"s:6Yababa7AddressC"},{"kind":"text","text":", "},{"kind":"externalParam","text":"addressHasDifferentWarehouseThanBefore"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AddressManagerOwner\/didSelectAddress(_:addressHasDifferentWarehouseThanBefore:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/yababa\/addressmanagerowner\/didselectaddress(_:addresshasdifferentwarehousethanbefore:)"},"doc://com.yababaGmbH.yababa/objc(cs)UIViewController":{"type":"unresolvable","title":"UIKit.UIViewController","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(cs)UIViewController"},"doc://com.yababaGmbH.yababa/documentation/Yababa/AddressManagerOwner/userAddressManager":{"role":"symbol","title":"userAddressManager","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"userAddressManager"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AddressManager","preciseIdentifier":"c:@M@Yababa@objc(cs)AddressManager"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AddressManagerOwner\/userAddressManager","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/yababa\/addressmanagerowner\/useraddressmanager"},"doc://com.yababaGmbH.yababa/documentation/Yababa/CheckoutSceneViewController":{"role":"symbol","title":"CheckoutSceneViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CheckoutSceneViewController"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CheckoutSceneViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CheckoutSceneViewController"}],"url":"\/documentation\/yababa\/checkoutsceneviewcontroller"},"doc://com.yababaGmbH.yababa/documentation/Yababa/AddressManagerOwner/addressManagerInteractor":{"role":"symbol","title":"addressManagerInteractor","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"addressManagerInteractor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AddressManagerInteractorProtocol","preciseIdentifier":"s:6Yababa32AddressManagerInteractorProtocolP"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AddressManagerOwner\/addressManagerInteractor","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/yababa\/addressmanagerowner\/addressmanagerinteractor"},"doc://com.yababaGmbH.yababa/documentation/Yababa/AddressManagerOwner/addressSelectionManager":{"role":"symbol","title":"addressSelectionManager","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"addressSelectionManager"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AddressSelectionManager","preciseIdentifier":"s:6Yababa23AddressSelectionManagerP"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AddressManagerOwner\/addressSelectionManager","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/yababa\/addressmanagerowner\/addressselectionmanager"},"doc://com.yababaGmbH.yababa/documentation/Yababa/AddressManagerOwner/closeAddressManager()-5tlf1":{"defaultImplementations":1,"role":"symbol","title":"closeAddressManager()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"closeAddressManager"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AddressManagerOwner\/closeAddressManager()-5tlf1","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/yababa\/addressmanagerowner\/closeaddressmanager()-5tlf1"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1HomeScreen\/title","value":"HomeScreen"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1HomeScreen\/fragments","value":[{"kind":"identifier","text":"HomeScreen"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1CheckoutSceneViewController\/title","value":"CheckoutSceneViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1CheckoutSceneViewController\/fragments","value":[{"kind":"identifier","text":"CheckoutSceneViewController"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}