{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AnalyticsTracker"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/yababa\/analyticstracker"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/yababa\/analyticstracker"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.yababaGmbH.yababa\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AnalyticsBaseTracker","doc:\/\/com.yababaGmbH.yababa\/objc(pl)NSObject","doc:\/\/com.yababaGmbH.yababa\/12SkeletonView17AssociatedObjectsP","doc:\/\/com.yababaGmbH.yababa\/s7CVarArgP","doc:\/\/com.yababaGmbH.yababa\/s28CustomDebugStringConvertibleP","doc:\/\/com.yababaGmbH.yababa\/s23CustomStringConvertibleP","doc:\/\/com.yababaGmbH.yababa\/SQ","doc:\/\/com.yababaGmbH.yababa\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AnalyticsTracker","interfaceLanguage":"swift"},"topicSections":[{"title":"Classes","identifiers":["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AnalyticsTracker\/AddressAnalyticEvents","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AnalyticsTracker\/AuthenticationAnalyticEvents","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AnalyticsTracker\/CheckoutAnalyticsEvents","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AnalyticsTracker\/CouponsAndVouchersAnalyticEvents","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AnalyticsTracker\/HomeAndBrowsingAnalyticEvents","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AnalyticsTracker\/LanguageAnalyticEvents","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AnalyticsTracker\/OrdersAnalyticEvents","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AnalyticsTracker\/PushNotificationsAnalyticEvents","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AnalyticsTracker\/ReferralsAnalyticEvents","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AnalyticsTracker\/SearchAnalyticEvents","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AnalyticsTracker\/ShoppingCartAnalyticEvents","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AnalyticsTracker\/TimeSlotAnalyticEvents","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AnalyticsTracker\/WalletAnalyticEvents"]},{"title":"Type Methods","identifiers":["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AnalyticsTracker\/CheckOutPriceDifferenceShown(cartItemsWithPriceChange:)","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AnalyticsTracker\/MobileNumberRequestLoaded()","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AnalyticsTracker\/SmsVerificationLoaded()","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AnalyticsTracker\/SmsVerificationSucceeded()","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AnalyticsTracker\/trackAccountRegistered()","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AnalyticsTracker\/trackAddAddress()","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AnalyticsTracker\/trackAddcouponClicked(eventOrigin:)","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AnalyticsTracker\/trackAddressOutOfDeliveryZone(postalCode:)","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AnalyticsTracker\/trackAppleSignIn()","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AnalyticsTracker\/trackBannerClicked(bannerCode:position:origin:)","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AnalyticsTracker\/trackBannerSeen(bannerCode:position:)","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AnalyticsTracker\/trackCartAdjusted(containedDeprecatedProducts:)","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AnalyticsTracker\/trackCashPaymentSelected()","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AnalyticsTracker\/trackCategorySelected(categoryName:categoryID:origin:)","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AnalyticsTracker\/trackCheckOutCompleted(orderId:cartValue:distinctProducts:productsQuantity:shopDiscount:shopDeliveryFee:totalVoucher:paymentMethod:pickDay:pickTime:couponCode:couponName:)","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AnalyticsTracker\/trackCheckOutConfirmed(cartValue:productsQuantity:shopDiscount:shopDeliveryFee:totalVoucher:paymentMethod:pickDay:pickTime:)","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AnalyticsTracker\/trackCheckOutLoaded(cartValue:productsQuantity:shopDiscount:shopDeliveryFee:totalVoucher:paymentMethod:pickDay:pickTime:)","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AnalyticsTracker\/trackCheckOutNewCreditCardPayButtonClicked()","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AnalyticsTracker\/trackCheckOutNewCreditCardPaymentInfoClicked()","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AnalyticsTracker\/trackCheckOutSelected(cartValue:productsQuantity:)","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AnalyticsTracker\/trackClearShoppingCart()","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AnalyticsTracker\/trackCustomEvent(eventName:)","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AnalyticsTracker\/trackEmailPassed()","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AnalyticsTracker\/trackEmailSignIn()","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AnalyticsTracker\/trackEmailSignup()","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AnalyticsTracker\/trackErrorCouponApplied(couponCode:errorText:)","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AnalyticsTracker\/trackFacebookSignIn()","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AnalyticsTracker\/trackForceUserToLogout()","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AnalyticsTracker\/trackGetStarted()","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AnalyticsTracker\/trackGoToCheckOutBtnClicked(cartValue:productsQuantity:)","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AnalyticsTracker\/trackGoogleSignup()","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AnalyticsTracker\/trackHomePageLoaded(hasWalletCollection:)","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AnalyticsTracker\/trackJustBrowse()","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AnalyticsTracker\/trackLanguageChangeApplied(locale:)","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AnalyticsTracker\/trackLanguageSelectionLoaded()","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AnalyticsTracker\/trackLiveTrackingLinkClicked()","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AnalyticsTracker\/trackNewAddressSuccessfullyAdded()","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AnalyticsTracker\/trackOrderTrackingClicked()","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AnalyticsTracker\/trackOrderTrackingLoaded()","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AnalyticsTracker\/trackPassPassed()","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AnalyticsTracker\/trackPaymentGateway(name:)","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AnalyticsTracker\/trackPaymentMethodPopupClicked(paymentMethod:paymentMethodAlreadyAdded:)","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AnalyticsTracker\/trackPaymentMethodPopupSeen()","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AnalyticsTracker\/trackPickTimeSlotClicked(eventOrigin:)","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AnalyticsTracker\/trackPickTimeSlotConfirmed(pickDay:pickTime:pickWeekday:pickDayPosition:pickTimePosition:availablePickTimes:unAvailablePickTimes:eventOrigin:)","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AnalyticsTracker\/trackPickTimeSlotData(firstAvailableDayIndex:firstAvailableTimeSlotIndex:timeSlotsDump:)","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AnalyticsTracker\/trackPickTimeSlotLoaded(pickDay:pickWeekday:availablePickDays:availablePickTimes:unAvailablePickTimes:)","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AnalyticsTracker\/trackProductDetailsSelected(productID:productName:productUnitPrice:productPosition:inStock:eventOrigin:)","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AnalyticsTracker\/trackPromotionPageClicked(bannerId:searchTags:)","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AnalyticsTracker\/trackPushNotificationHardOptInImpression()","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AnalyticsTracker\/trackPushNotificationOptInUpgraded()","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AnalyticsTracker\/trackPushNotificationSoftOptInResponse(status:)","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AnalyticsTracker\/trackReferralBannerClicked(eventOrigin:)","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AnalyticsTracker\/trackReferralBannerSeen(eventOrigin:)","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AnalyticsTracker\/trackReferralCouponShared(eventOrigin:)","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AnalyticsTracker\/trackReferralLinkClicked()","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AnalyticsTracker\/trackReferralLinkShared(eventOrigin:referralSharedMethod:)","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AnalyticsTracker\/trackReferralPopupLoaded(eventOrigin:)","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AnalyticsTracker\/trackReorderClicked()","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AnalyticsTracker\/trackSearchBarClicked(eventOrigin:)","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AnalyticsTracker\/trackSearchResultsClicked(searchedProductClicked:)","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AnalyticsTracker\/trackSearchResultsLoaded(searchTerm:searchResultsCount:)","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AnalyticsTracker\/trackSelectAlreadyAddedAddress(locationAddress:locationLon:locationLat:locationCity:locationCountry:)","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AnalyticsTracker\/trackSelectedVoucherChanged(from:code:)","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AnalyticsTracker\/trackShoppingCartLoaded(cartValue:productsQuantity:)","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AnalyticsTracker\/trackShoppingCartSelected()","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AnalyticsTracker\/trackSocialLoginError(provider:errorMessage:)","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AnalyticsTracker\/trackSplashLoaded(deviceID:deviceVersion:appVersion:)","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AnalyticsTracker\/trackSuccessCouponApplied(couponCode:)","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AnalyticsTracker\/trackUserAddedItemToCart(productID:productName:productUnitPrice:categoryName:eventLocation:swimLaneId:swimLaneItemIndex:bannerId:)","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AnalyticsTracker\/trackUserRemovedItemFromCart(productID:productName:productUnitPrice:eventLocation:)","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AnalyticsTracker\/trackVoucherAdded(code:eventOrigin:)","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AnalyticsTracker\/trackWalletDisplayed(code:origin:totalVouchers:)","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AnalyticsTracker\/trackWalletPromosClicked()","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AnalyticsTracker\/trackWelcomePage()"]}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AnalyticsTracker"}],"title":"AnalyticsTracker","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@Yababa@objc(cs)AnalyticsTracker","modules":[{"name":"Yababa"}],"navigatorTitle":[{"kind":"identifier","text":"AnalyticsTracker"}]},"hierarchy":{"paths":[["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa"]]},"references":{"doc://com.yababaGmbH.yababa/documentation/Yababa/AnalyticsTracker/init":{"role":"symbol","title":"init","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AnalyticsTracker\/init","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"init"}],"url":"\/documentation\/yababa\/analyticstracker\/init"},"doc://com.yababaGmbH.yababa/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.yababaGmbH.yababa\/s28CustomDebugStringConvertibleP"},"doc://com.yababaGmbH.yababa/documentation/Yababa/AnalyticsTracker/HomeAndBrowsingAnalyticEvents":{"role":"symbol","title":"AnalyticsTracker.HomeAndBrowsingAnalyticEvents","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HomeAndBrowsingAnalyticEvents"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AnalyticsTracker\/HomeAndBrowsingAnalyticEvents","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HomeAndBrowsingAnalyticEvents"}],"url":"\/documentation\/yababa\/analyticstracker\/homeandbrowsinganalyticevents"},"doc://com.yababaGmbH.yababa/documentation/Yababa/AnalyticsTracker/trackOrderTrackingClicked()":{"role":"symbol","title":"trackOrderTrackingClicked()","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"trackOrderTrackingClicked"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AnalyticsTracker\/trackOrderTrackingClicked()","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/analyticstracker\/trackordertrackingclicked()"},"doc://com.yababaGmbH.yababa/documentation/Yababa/AnalyticsTracker/trackReferralLinkClicked()":{"role":"symbol","title":"trackReferralLinkClicked()","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"trackReferralLinkClicked"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AnalyticsTracker\/trackReferralLinkClicked()","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/analyticstracker\/trackreferrallinkclicked()"},"doc://com.yababaGmbH.yababa/documentation/Yababa":{"role":"collection","title":"Yababa","abstract":[{"type":"text","text":"Getting Started"}],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa","kind":"symbol","type":"topic","url":"\/documentation\/yababa"},"doc://com.yababaGmbH.yababa/documentation/Yababa/AnalyticsTracker/trackCustomEvent(eventName:)":{"role":"symbol","title":"trackCustomEvent(eventName:)","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"trackCustomEvent"},{"kind":"text","text":"("},{"kind":"externalParam","text":"eventName"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Send event name directly in String format instead of TrackingEntity enum type"}],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AnalyticsTracker\/trackCustomEvent(eventName:)","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/analyticstracker\/trackcustomevent(eventname:)"},"doc://com.yababaGmbH.yababa/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)NSObject"},"doc://com.yababaGmbH.yababa/documentation/Yababa/AnalyticsTracker/trackLanguageSelectionLoaded()":{"role":"symbol","title":"trackLanguageSelectionLoaded()","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"trackLanguageSelectionLoaded"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AnalyticsTracker\/trackLanguageSelectionLoaded()","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/analyticstracker\/tracklanguageselectionloaded()"},"doc://com.yababaGmbH.yababa/documentation/Yababa/AnalyticsTracker/trackSocialLoginError(provider:errorMessage:)":{"role":"symbol","title":"trackSocialLoginError(provider:errorMessage:)","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"trackSocialLoginError"},{"kind":"text","text":"("},{"kind":"externalParam","text":"provider"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"errorMessage"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AnalyticsTracker\/trackSocialLoginError(provider:errorMessage:)","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/analyticstracker\/tracksocialloginerror(provider:errormessage:)"},"doc://com.yababaGmbH.yababa/documentation/Yababa/AnalyticsTracker/ReferralsAnalyticEvents":{"role":"symbol","title":"AnalyticsTracker.ReferralsAnalyticEvents","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ReferralsAnalyticEvents"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AnalyticsTracker\/ReferralsAnalyticEvents","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ReferralsAnalyticEvents"}],"url":"\/documentation\/yababa\/analyticstracker\/referralsanalyticevents"},"doc://com.yababaGmbH.yababa/documentation/Yababa/AnalyticsTracker/trackPushNotificationSoftOptInResponse(status:)":{"role":"symbol","title":"trackPushNotificationSoftOptInResponse(status:)","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"trackPushNotificationSoftOptInResponse"},{"kind":"text","text":"("},{"kind":"externalParam","text":"status"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AnalyticsTracker\/trackPushNotificationSoftOptInResponse(status:)","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/analyticstracker\/trackpushnotificationsoftoptinresponse(status:)"},"doc://com.yababaGmbH.yababa/documentation/Yababa/AnalyticsTracker/trackPickTimeSlotLoaded(pickDay:pickWeekday:availablePickDays:availablePickTimes:unAvailablePickTimes:)":{"role":"symbol","title":"trackPickTimeSlotLoaded(pickDay:pickWeekday:availablePickDays:availablePickTimes:unAvailablePickTimes:)","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"trackPickTimeSlotLoaded"},{"kind":"text","text":"("},{"kind":"externalParam","text":"pickDay"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"pickWeekday"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"availablePickDays"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"kind":"externalParam","text":"availablePickTimes"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"kind":"externalParam","text":"unAvailablePickTimes"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AnalyticsTracker\/trackPickTimeSlotLoaded(pickDay:pickWeekday:availablePickDays:availablePickTimes:unAvailablePickTimes:)","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/analyticstracker\/trackpicktimeslotloaded(pickday:pickweekday:availablepickdays:availablepicktimes:unavailablepicktimes:)"},"doc://com.yababaGmbH.yababa/documentation/Yababa/AnalyticsTracker/MobileNumberRequestLoaded()":{"role":"symbol","title":"MobileNumberRequestLoaded()","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"MobileNumberRequestLoaded"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AnalyticsTracker\/MobileNumberRequestLoaded()","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/analyticstracker\/mobilenumberrequestloaded()"},"doc://com.yababaGmbH.yababa/documentation/Yababa/AnalyticsTracker/trackPushNotificationHardOptInImpression()":{"role":"symbol","title":"trackPushNotificationHardOptInImpression()","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"trackPushNotificationHardOptInImpression"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AnalyticsTracker\/trackPushNotificationHardOptInImpression()","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/analyticstracker\/trackpushnotificationhardoptinimpression()"},"doc://com.yababaGmbH.yababa/documentation/Yababa/AnalyticsTracker/trackCheckOutSelected(cartValue:productsQuantity:)":{"role":"symbol","title":"trackCheckOutSelected(cartValue:productsQuantity:)","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"trackCheckOutSelected"},{"kind":"text","text":"("},{"kind":"externalParam","text":"cartValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"},{"kind":"text","text":", "},{"kind":"externalParam","text":"productsQuantity"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Checkout screen is loaded (DOES NOT mean Go to Checkout button (“Zum Checkout gehen”) is clicked)"}],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AnalyticsTracker\/trackCheckOutSelected(cartValue:productsQuantity:)","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/analyticstracker\/trackcheckoutselected(cartvalue:productsquantity:)"},"doc://com.yababaGmbH.yababa/documentation/Yababa/AnalyticsTracker/trackAddAddress()":{"role":"symbol","title":"trackAddAddress()","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"trackAddAddress"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AnalyticsTracker\/trackAddAddress()","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/analyticstracker\/trackaddaddress()"},"doc://com.yababaGmbH.yababa/documentation/Yababa/AnalyticsTracker/trackCheckOutConfirmed(cartValue:productsQuantity:shopDiscount:shopDeliveryFee:totalVoucher:paymentMethod:pickDay:pickTime:)":{"role":"symbol","title":"trackCheckOutConfirmed(cartValue:productsQuantity:shopDiscount:shopDeliveryFee:totalVoucher:paymentMethod:pickDay:pickTime:)","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"trackCheckOutConfirmed"},{"kind":"text","text":"("},{"kind":"externalParam","text":"cartValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"},{"kind":"text","text":", "},{"kind":"externalParam","text":"productsQuantity"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"kind":"externalParam","text":"shopDiscount"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"},{"kind":"text","text":", "},{"kind":"externalParam","text":"shopDeliveryFee"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"},{"kind":"text","text":", "},{"kind":"externalParam","text":"totalVoucher"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"},{"kind":"text","text":", "},{"kind":"externalParam","text":"paymentMethod"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"pickDay"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"pickTime"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AnalyticsTracker\/trackCheckOutConfirmed(cartValue:productsQuantity:shopDiscount:shopDeliveryFee:totalVoucher:paymentMethod:pickDay:pickTime:)","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/analyticstracker\/trackcheckoutconfirmed(cartvalue:productsquantity:shopdiscount:shopdeliveryfee:totalvoucher:paymentmethod:pickday:picktime:)"},"doc://com.yababaGmbH.yababa/documentation/Yababa/AnalyticsTracker":{"role":"symbol","title":"AnalyticsTracker","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AnalyticsTracker"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AnalyticsTracker","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AnalyticsTracker"}],"url":"\/documentation\/yababa\/analyticstracker"},"doc://com.yababaGmbH.yababa/documentation/Yababa/AnalyticsTracker/trackPushNotificationOptInUpgraded()":{"role":"symbol","title":"trackPushNotificationOptInUpgraded()","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"trackPushNotificationOptInUpgraded"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AnalyticsTracker\/trackPushNotificationOptInUpgraded()","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/analyticstracker\/trackpushnotificationoptinupgraded()"},"doc://com.yababaGmbH.yababa/documentation/Yababa/AnalyticsTracker/trackPaymentMethodPopupSeen()":{"role":"symbol","title":"trackPaymentMethodPopupSeen()","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"trackPaymentMethodPopupSeen"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AnalyticsTracker\/trackPaymentMethodPopupSeen()","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/analyticstracker\/trackpaymentmethodpopupseen()"},"doc://com.yababaGmbH.yababa/documentation/Yababa/AnalyticsTracker/trackEmailPassed()":{"role":"symbol","title":"trackEmailPassed()","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"trackEmailPassed"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AnalyticsTracker\/trackEmailPassed()","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/analyticstracker\/trackemailpassed()"},"doc://com.yababaGmbH.yababa/documentation/Yababa/AnalyticsTracker/trackPaymentMethodPopupClicked(paymentMethod:paymentMethodAlreadyAdded:)":{"role":"symbol","title":"trackPaymentMethodPopupClicked(paymentMethod:paymentMethodAlreadyAdded:)","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"trackPaymentMethodPopupClicked"},{"kind":"text","text":"("},{"kind":"externalParam","text":"paymentMethod"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"paymentMethodAlreadyAdded"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AnalyticsTracker\/trackPaymentMethodPopupClicked(paymentMethod:paymentMethodAlreadyAdded:)","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/analyticstracker\/trackpaymentmethodpopupclicked(paymentmethod:paymentmethodalreadyadded:)"},"doc://com.yababaGmbH.yababa/documentation/Yababa/AnalyticsTracker/trackSearchResultsClicked(searchedProductClicked:)":{"role":"symbol","title":"trackSearchResultsClicked(searchedProductClicked:)","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"trackSearchResultsClicked"},{"kind":"text","text":"("},{"kind":"externalParam","text":"searchedProductClicked"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AnalyticsTracker\/trackSearchResultsClicked(searchedProductClicked:)","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/analyticstracker\/tracksearchresultsclicked(searchedproductclicked:)"},"doc://com.yababaGmbH.yababa/documentation/Yababa/AnalyticsTracker/trackCheckOutLoaded(cartValue:productsQuantity:shopDiscount:shopDeliveryFee:totalVoucher:paymentMethod:pickDay:pickTime:)":{"role":"symbol","title":"trackCheckOutLoaded(cartValue:productsQuantity:shopDiscount:shopDeliveryFee:totalVoucher:paymentMethod:pickDay:pickTime:)","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"trackCheckOutLoaded"},{"kind":"text","text":"("},{"kind":"externalParam","text":"cartValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"},{"kind":"text","text":", "},{"kind":"externalParam","text":"productsQuantity"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"kind":"externalParam","text":"shopDiscount"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"shopDeliveryFee"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"totalVoucher"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"paymentMethod"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"pickDay"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"pickTime"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AnalyticsTracker\/trackCheckOutLoaded(cartValue:productsQuantity:shopDiscount:shopDeliveryFee:totalVoucher:paymentMethod:pickDay:pickTime:)","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/analyticstracker\/trackcheckoutloaded(cartvalue:productsquantity:shopdiscount:shopdeliveryfee:totalvoucher:paymentmethod:pickday:picktime:)"},"doc://com.yababaGmbH.yababa/documentation/Yababa/AnalyticsTracker/SmsVerificationLoaded()":{"role":"symbol","title":"SmsVerificationLoaded()","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"SmsVerificationLoaded"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AnalyticsTracker\/SmsVerificationLoaded()","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/analyticstracker\/smsverificationloaded()"},"doc://com.yababaGmbH.yababa/documentation/Yababa/AnalyticsTracker/trackCategorySelected(categoryName:categoryID:origin:)":{"role":"symbol","title":"trackCategorySelected(categoryName:categoryID:origin:)","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"trackCategorySelected"},{"kind":"text","text":"("},{"kind":"externalParam","text":"categoryName"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"categoryID"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"origin"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TrackingOrigin","preciseIdentifier":"s:6Yababa14TrackingOriginO"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AnalyticsTracker\/trackCategorySelected(categoryName:categoryID:origin:)","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/analyticstracker\/trackcategoryselected(categoryname:categoryid:origin:)"},"doc://com.yababaGmbH.yababa/documentation/Yababa/AnalyticsTracker/trackVoucherAdded(code:eventOrigin:)":{"role":"symbol","title":"trackVoucherAdded(code:eventOrigin:)","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"trackVoucherAdded"},{"kind":"text","text":"("},{"kind":"externalParam","text":"code"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"eventOrigin"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TrackingOrigin","preciseIdentifier":"s:6Yababa14TrackingOriginO"},{"kind":"text","text":"?)"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AnalyticsTracker\/trackVoucherAdded(code:eventOrigin:)","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/analyticstracker\/trackvoucheradded(code:eventorigin:)"},"doc://com.yababaGmbH.yababa/documentation/Yababa/AnalyticsTracker/WalletAnalyticEvents":{"role":"symbol","title":"AnalyticsTracker.WalletAnalyticEvents","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"WalletAnalyticEvents"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AnalyticsTracker\/WalletAnalyticEvents","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"WalletAnalyticEvents"}],"url":"\/documentation\/yababa\/analyticstracker\/walletanalyticevents"},"doc://com.yababaGmbH.yababa/documentation/Yababa/AnalyticsTracker/trackCashPaymentSelected()":{"role":"symbol","title":"trackCashPaymentSelected()","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"trackCashPaymentSelected"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AnalyticsTracker\/trackCashPaymentSelected()","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/analyticstracker\/trackcashpaymentselected()"},"doc://com.yababaGmbH.yababa/documentation/Yababa/AnalyticsTracker/trackCartAdjusted(containedDeprecatedProducts:)":{"role":"symbol","title":"trackCartAdjusted(containedDeprecatedProducts:)","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"trackCartAdjusted"},{"kind":"text","text":"("},{"kind":"externalParam","text":"containedDeprecatedProducts"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AnalyticsTracker\/trackCartAdjusted(containedDeprecatedProducts:)","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/analyticstracker\/trackcartadjusted(containeddeprecatedproducts:)"},"doc://com.yababaGmbH.yababa/documentation/Yababa/AnalyticsTracker/trackReferralBannerClicked(eventOrigin:)":{"role":"symbol","title":"trackReferralBannerClicked(eventOrigin:)","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"trackReferralBannerClicked"},{"kind":"text","text":"("},{"kind":"externalParam","text":"eventOrigin"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TrackingOrigin","preciseIdentifier":"s:6Yababa14TrackingOriginO"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AnalyticsTracker\/trackReferralBannerClicked(eventOrigin:)","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/analyticstracker\/trackreferralbannerclicked(eventorigin:)"},"doc://com.yababaGmbH.yababa/documentation/Yababa/AnalyticsTracker/trackSplashLoaded(deviceID:deviceVersion:appVersion:)":{"role":"symbol","title":"trackSplashLoaded(deviceID:deviceVersion:appVersion:)","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"trackSplashLoaded"},{"kind":"text","text":"("},{"kind":"externalParam","text":"deviceID"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"deviceVersion"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"appVersion"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AnalyticsTracker\/trackSplashLoaded(deviceID:deviceVersion:appVersion:)","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/analyticstracker\/tracksplashloaded(deviceid:deviceversion:appversion:)"},"doc://com.yababaGmbH.yababa/documentation/Yababa/AnalyticsTracker/SmsVerificationSucceeded()":{"role":"symbol","title":"SmsVerificationSucceeded()","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"SmsVerificationSucceeded"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AnalyticsTracker\/SmsVerificationSucceeded()","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/analyticstracker\/smsverificationsucceeded()"},"doc://com.yababaGmbH.yababa/12SkeletonView17AssociatedObjectsP":{"type":"unresolvable","title":"SkeletonView.AssociatedObjects","identifier":"doc:\/\/com.yababaGmbH.yababa\/12SkeletonView17AssociatedObjectsP"},"doc://com.yababaGmbH.yababa/documentation/Yababa/AnalyticsTracker/OrdersAnalyticEvents":{"role":"symbol","title":"AnalyticsTracker.OrdersAnalyticEvents","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"OrdersAnalyticEvents"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AnalyticsTracker\/OrdersAnalyticEvents","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"OrdersAnalyticEvents"}],"url":"\/documentation\/yababa\/analyticstracker\/ordersanalyticevents"},"doc://com.yababaGmbH.yababa/documentation/Yababa/AnalyticsTracker/trackGoToCheckOutBtnClicked(cartValue:productsQuantity:)":{"role":"symbol","title":"trackGoToCheckOutBtnClicked(cartValue:productsQuantity:)","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"trackGoToCheckOutBtnClicked"},{"kind":"text","text":"("},{"kind":"externalParam","text":"cartValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"},{"kind":"text","text":", "},{"kind":"externalParam","text":"productsQuantity"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AnalyticsTracker\/trackGoToCheckOutBtnClicked(cartValue:productsQuantity:)","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/analyticstracker\/trackgotocheckoutbtnclicked(cartvalue:productsquantity:)"},"doc://com.yababaGmbH.yababa/documentation/Yababa/AnalyticsTracker/trackCheckOutNewCreditCardPaymentInfoClicked()":{"role":"symbol","title":"trackCheckOutNewCreditCardPaymentInfoClicked()","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"trackCheckOutNewCreditCardPaymentInfoClicked"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AnalyticsTracker\/trackCheckOutNewCreditCardPaymentInfoClicked()","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/analyticstracker\/trackcheckoutnewcreditcardpaymentinfoclicked()"},"doc://com.yababaGmbH.yababa/documentation/Yababa/AnalyticsTracker/AddressAnalyticEvents":{"role":"symbol","title":"AnalyticsTracker.AddressAnalyticEvents","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AddressAnalyticEvents"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AnalyticsTracker\/AddressAnalyticEvents","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AddressAnalyticEvents"}],"url":"\/documentation\/yababa\/analyticstracker\/addressanalyticevents"},"doc://com.yababaGmbH.yababa/documentation/Yababa/AnalyticsTracker/trackShoppingCartLoaded(cartValue:productsQuantity:)":{"role":"symbol","title":"trackShoppingCartLoaded(cartValue:productsQuantity:)","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"trackShoppingCartLoaded"},{"kind":"text","text":"("},{"kind":"externalParam","text":"cartValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"},{"kind":"text","text":", "},{"kind":"externalParam","text":"productsQuantity"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AnalyticsTracker\/trackShoppingCartLoaded(cartValue:productsQuantity:)","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/analyticstracker\/trackshoppingcartloaded(cartvalue:productsquantity:)"},"doc://com.yababaGmbH.yababa/documentation/Yababa/AnalyticsTracker/PushNotificationsAnalyticEvents":{"role":"symbol","title":"AnalyticsTracker.PushNotificationsAnalyticEvents","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PushNotificationsAnalyticEvents"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AnalyticsTracker\/PushNotificationsAnalyticEvents","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PushNotificationsAnalyticEvents"}],"url":"\/documentation\/yababa\/analyticstracker\/pushnotificationsanalyticevents"},"doc://com.yababaGmbH.yababa/documentation/Yababa/AnalyticsTracker/trackReorderClicked()":{"role":"symbol","title":"trackReorderClicked()","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"trackReorderClicked"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AnalyticsTracker\/trackReorderClicked()","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/analyticstracker\/trackreorderclicked()"},"doc://com.yababaGmbH.yababa/documentation/Yababa/AnalyticsTracker/AuthenticationAnalyticEvents":{"role":"symbol","title":"AnalyticsTracker.AuthenticationAnalyticEvents","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AuthenticationAnalyticEvents"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AnalyticsTracker\/AuthenticationAnalyticEvents","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AuthenticationAnalyticEvents"}],"url":"\/documentation\/yababa\/analyticstracker\/authenticationanalyticevents"},"doc://com.yababaGmbH.yababa/documentation/Yababa/AnalyticsTracker/trackWelcomePage()":{"role":"symbol","title":"trackWelcomePage()","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"trackWelcomePage"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AnalyticsTracker\/trackWelcomePage()","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/analyticstracker\/trackwelcomepage()"},"doc://com.yababaGmbH.yababa/documentation/Yababa/AnalyticsTracker/trackClearShoppingCart()":{"role":"symbol","title":"trackClearShoppingCart()","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"trackClearShoppingCart"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AnalyticsTracker\/trackClearShoppingCart()","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/analyticstracker\/trackclearshoppingcart()"},"doc://com.yababaGmbH.yababa/documentation/Yababa/AnalyticsTracker/trackUserRemovedItemFromCart(productID:productName:productUnitPrice:eventLocation:)":{"role":"symbol","title":"trackUserRemovedItemFromCart(productID:productName:productUnitPrice:eventLocation:)","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"trackUserRemovedItemFromCart"},{"kind":"text","text":"("},{"kind":"externalParam","text":"productID"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"kind":"externalParam","text":"productName"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"productUnitPrice"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"},{"kind":"text","text":", "},{"kind":"externalParam","text":"eventLocation"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AnalyticsTracker\/trackUserRemovedItemFromCart(productID:productName:productUnitPrice:eventLocation:)","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/analyticstracker\/trackuserremoveditemfromcart(productid:productname:productunitprice:eventlocation:)"},"doc://com.yababaGmbH.yababa/documentation/Yababa/AnalyticsTracker/trackLiveTrackingLinkClicked()":{"role":"symbol","title":"trackLiveTrackingLinkClicked()","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"trackLiveTrackingLinkClicked"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AnalyticsTracker\/trackLiveTrackingLinkClicked()","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/analyticstracker\/tracklivetrackinglinkclicked()"},"doc://com.yababaGmbH.yababa/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.yababaGmbH.yababa\/SQ"},"doc://com.yababaGmbH.yababa/documentation/Yababa/AnalyticsTracker/trackReferralBannerSeen(eventOrigin:)":{"role":"symbol","title":"trackReferralBannerSeen(eventOrigin:)","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"trackReferralBannerSeen"},{"kind":"text","text":"("},{"kind":"externalParam","text":"eventOrigin"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TrackingOrigin","preciseIdentifier":"s:6Yababa14TrackingOriginO"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AnalyticsTracker\/trackReferralBannerSeen(eventOrigin:)","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/analyticstracker\/trackreferralbannerseen(eventorigin:)"},"doc://com.yababaGmbH.yababa/documentation/Yababa/AnalyticsTracker/trackReferralLinkShared(eventOrigin:referralSharedMethod:)":{"role":"symbol","title":"trackReferralLinkShared(eventOrigin:referralSharedMethod:)","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"trackReferralLinkShared"},{"kind":"text","text":"("},{"kind":"externalParam","text":"eventOrigin"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TrackingOrigin","preciseIdentifier":"s:6Yababa14TrackingOriginO"},{"kind":"text","text":", "},{"kind":"externalParam","text":"referralSharedMethod"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AnalyticsTracker\/trackReferralLinkShared(eventOrigin:referralSharedMethod:)","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/analyticstracker\/trackreferrallinkshared(eventorigin:referralsharedmethod:)"},"doc://com.yababaGmbH.yababa/documentation/Yababa/AnalyticsTracker/trackEmailSignup()":{"role":"symbol","title":"trackEmailSignup()","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"trackEmailSignup"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AnalyticsTracker\/trackEmailSignup()","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/analyticstracker\/trackemailsignup()"},"doc://com.yababaGmbH.yababa/documentation/Yababa/AnalyticsTracker/trackLanguageChangeApplied(locale:)":{"role":"symbol","title":"trackLanguageChangeApplied(locale:)","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"trackLanguageChangeApplied"},{"kind":"text","text":"("},{"kind":"externalParam","text":"locale"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AnalyticsTracker\/trackLanguageChangeApplied(locale:)","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/analyticstracker\/tracklanguagechangeapplied(locale:)"},"doc://com.yababaGmbH.yababa/documentation/Yababa/AnalyticsTracker/trackBannerClicked(bannerCode:position:origin:)":{"role":"symbol","title":"trackBannerClicked(bannerCode:position:origin:)","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"trackBannerClicked"},{"kind":"text","text":"("},{"kind":"externalParam","text":"bannerCode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"position"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"kind":"externalParam","text":"origin"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TrackingOrigin","preciseIdentifier":"s:6Yababa14TrackingOriginO"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AnalyticsTracker\/trackBannerClicked(bannerCode:position:origin:)","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/analyticstracker\/trackbannerclicked(bannercode:position:origin:)"},"doc://com.yababaGmbH.yababa/documentation/Yababa/AnalyticsTracker/trackGetStarted()":{"role":"symbol","title":"trackGetStarted()","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"trackGetStarted"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AnalyticsTracker\/trackGetStarted()","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/analyticstracker\/trackgetstarted()"},"doc://com.yababaGmbH.yababa/documentation/Yababa/AnalyticsTracker/ShoppingCartAnalyticEvents":{"role":"symbol","title":"AnalyticsTracker.ShoppingCartAnalyticEvents","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ShoppingCartAnalyticEvents"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AnalyticsTracker\/ShoppingCartAnalyticEvents","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ShoppingCartAnalyticEvents"}],"url":"\/documentation\/yababa\/analyticstracker\/shoppingcartanalyticevents"},"doc://com.yababaGmbH.yababa/documentation/Yababa/AnalyticsTracker/trackShoppingCartSelected()":{"role":"symbol","title":"trackShoppingCartSelected()","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"trackShoppingCartSelected"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AnalyticsTracker\/trackShoppingCartSelected()","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/analyticstracker\/trackshoppingcartselected()"},"doc://com.yababaGmbH.yababa/documentation/Yababa/AnalyticsTracker/CouponsAndVouchersAnalyticEvents":{"role":"symbol","title":"AnalyticsTracker.CouponsAndVouchersAnalyticEvents","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CouponsAndVouchersAnalyticEvents"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AnalyticsTracker\/CouponsAndVouchersAnalyticEvents","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CouponsAndVouchersAnalyticEvents"}],"url":"\/documentation\/yababa\/analyticstracker\/couponsandvouchersanalyticevents"},"doc://com.yababaGmbH.yababa/documentation/Yababa/AnalyticsTracker/trackUserAddedItemToCart(productID:productName:productUnitPrice:categoryName:eventLocation:swimLaneId:swimLaneItemIndex:bannerId:)":{"role":"symbol","title":"trackUserAddedItemToCart(productID:productName:productUnitPrice:categoryName:eventLocation:swimLaneId:swimLaneItemIndex:bannerId:)","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"trackUserAddedItemToCart"},{"kind":"text","text":"("},{"kind":"externalParam","text":"productID"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"kind":"externalParam","text":"productName"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"productUnitPrice"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"},{"kind":"text","text":", "},{"kind":"externalParam","text":"categoryName"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"eventLocation"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"swimLaneId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"swimLaneItemIndex"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"bannerId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?)"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AnalyticsTracker\/trackUserAddedItemToCart(productID:productName:productUnitPrice:categoryName:eventLocation:swimLaneId:swimLaneItemIndex:bannerId:)","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/analyticstracker\/trackuseraddeditemtocart(productid:productname:productunitprice:categoryname:eventlocation:swimlaneid:swimlaneitemindex:bannerid:)"},"doc://com.yababaGmbH.yababa/documentation/Yababa/AnalyticsTracker/trackSearchResultsLoaded(searchTerm:searchResultsCount:)":{"role":"symbol","title":"trackSearchResultsLoaded(searchTerm:searchResultsCount:)","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"trackSearchResultsLoaded"},{"kind":"text","text":"("},{"kind":"externalParam","text":"searchTerm"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"searchResultsCount"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AnalyticsTracker\/trackSearchResultsLoaded(searchTerm:searchResultsCount:)","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/analyticstracker\/tracksearchresultsloaded(searchterm:searchresultscount:)"},"doc://com.yababaGmbH.yababa/documentation/Yababa/AnalyticsTracker/trackAddcouponClicked(eventOrigin:)":{"role":"symbol","title":"trackAddcouponClicked(eventOrigin:)","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"trackAddcouponClicked"},{"kind":"text","text":"("},{"kind":"externalParam","text":"eventOrigin"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TrackingOrigin","preciseIdentifier":"s:6Yababa14TrackingOriginO"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AnalyticsTracker\/trackAddcouponClicked(eventOrigin:)","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/analyticstracker\/trackaddcouponclicked(eventorigin:)"},"doc://com.yababaGmbH.yababa/documentation/Yababa/AnalyticsTracker/LanguageAnalyticEvents":{"role":"symbol","title":"AnalyticsTracker.LanguageAnalyticEvents","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"LanguageAnalyticEvents"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AnalyticsTracker\/LanguageAnalyticEvents","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"LanguageAnalyticEvents"}],"url":"\/documentation\/yababa\/analyticstracker\/languageanalyticevents"},"doc://com.yababaGmbH.yababa/documentation/Yababa/AnalyticsTracker/trackFacebookSignIn()":{"role":"symbol","title":"trackFacebookSignIn()","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"trackFacebookSignIn"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AnalyticsTracker\/trackFacebookSignIn()","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/analyticstracker\/trackfacebooksignin()"},"doc://com.yababaGmbH.yababa/documentation/Yababa/AnalyticsTracker/trackPickTimeSlotData(firstAvailableDayIndex:firstAvailableTimeSlotIndex:timeSlotsDump:)":{"role":"symbol","title":"trackPickTimeSlotData(firstAvailableDayIndex:firstAvailableTimeSlotIndex:timeSlotsDump:)","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"trackPickTimeSlotData"},{"kind":"text","text":"("},{"kind":"externalParam","text":"firstAvailableDayIndex"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"kind":"externalParam","text":"firstAvailableTimeSlotIndex"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"kind":"externalParam","text":"timeSlotsDump"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"])"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AnalyticsTracker\/trackPickTimeSlotData(firstAvailableDayIndex:firstAvailableTimeSlotIndex:timeSlotsDump:)","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/analyticstracker\/trackpicktimeslotdata(firstavailabledayindex:firstavailabletimeslotindex:timeslotsdump:)"},"doc://com.yababaGmbH.yababa/documentation/Yababa/AnalyticsTracker/trackPickTimeSlotConfirmed(pickDay:pickTime:pickWeekday:pickDayPosition:pickTimePosition:availablePickTimes:unAvailablePickTimes:eventOrigin:)":{"role":"symbol","title":"trackPickTimeSlotConfirmed(pickDay:pickTime:pickWeekday:pickDayPosition:pickTimePosition:availablePickTimes:unAvailablePickTimes:eventOrigin:)","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"trackPickTimeSlotConfirmed"},{"kind":"text","text":"("},{"kind":"externalParam","text":"pickDay"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"pickTime"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"pickWeekday"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"pickDayPosition"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"kind":"externalParam","text":"pickTimePosition"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"kind":"externalParam","text":"availablePickTimes"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"kind":"externalParam","text":"unAvailablePickTimes"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"kind":"externalParam","text":"eventOrigin"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AnalyticsTracker\/trackPickTimeSlotConfirmed(pickDay:pickTime:pickWeekday:pickDayPosition:pickTimePosition:availablePickTimes:unAvailablePickTimes:eventOrigin:)","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/analyticstracker\/trackpicktimeslotconfirmed(pickday:picktime:pickweekday:pickdayposition:picktimeposition:availablepicktimes:unavailablepicktimes:eventorigin:)"},"doc://com.yababaGmbH.yababa/documentation/Yababa/AnalyticsTracker/trackReferralCouponShared(eventOrigin:)":{"role":"symbol","title":"trackReferralCouponShared(eventOrigin:)","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"trackReferralCouponShared"},{"kind":"text","text":"("},{"kind":"externalParam","text":"eventOrigin"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TrackingOrigin","preciseIdentifier":"s:6Yababa14TrackingOriginO"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AnalyticsTracker\/trackReferralCouponShared(eventOrigin:)","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/analyticstracker\/trackreferralcouponshared(eventorigin:)"},"doc://com.yababaGmbH.yababa/documentation/Yababa/AnalyticsTracker/trackErrorCouponApplied(couponCode:errorText:)":{"role":"symbol","title":"trackErrorCouponApplied(couponCode:errorText:)","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"trackErrorCouponApplied"},{"kind":"text","text":"("},{"kind":"externalParam","text":"couponCode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"errorText"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AnalyticsTracker\/trackErrorCouponApplied(couponCode:errorText:)","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/analyticstracker\/trackerrorcouponapplied(couponcode:errortext:)"},"doc://com.yababaGmbH.yababa/documentation/Yababa/AnalyticsTracker/trackSelectAlreadyAddedAddress(locationAddress:locationLon:locationLat:locationCity:locationCountry:)":{"role":"symbol","title":"trackSelectAlreadyAddedAddress(locationAddress:locationLon:locationLat:locationCity:locationCountry:)","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"trackSelectAlreadyAddedAddress"},{"kind":"text","text":"("},{"kind":"externalParam","text":"locationAddress"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"locationLon"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"},{"kind":"text","text":", "},{"kind":"externalParam","text":"locationLat"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"},{"kind":"text","text":", "},{"kind":"externalParam","text":"locationCity"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"locationCountry"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AnalyticsTracker\/trackSelectAlreadyAddedAddress(locationAddress:locationLon:locationLat:locationCity:locationCountry:)","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/analyticstracker\/trackselectalreadyaddedaddress(locationaddress:locationlon:locationlat:locationcity:locationcountry:)"},"doc://com.yababaGmbH.yababa/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.yababaGmbH.yababa\/SH"},"doc://com.yababaGmbH.yababa/documentation/Yababa/AnalyticsTracker/trackNewAddressSuccessfullyAdded()":{"role":"symbol","title":"trackNewAddressSuccessfullyAdded()","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"trackNewAddressSuccessfullyAdded"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AnalyticsTracker\/trackNewAddressSuccessfullyAdded()","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/analyticstracker\/tracknewaddresssuccessfullyadded()"},"doc://com.yababaGmbH.yababa/documentation/Yababa/AnalyticsTracker/CheckoutAnalyticsEvents":{"role":"symbol","title":"AnalyticsTracker.CheckoutAnalyticsEvents","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CheckoutAnalyticsEvents"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AnalyticsTracker\/CheckoutAnalyticsEvents","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CheckoutAnalyticsEvents"}],"url":"\/documentation\/yababa\/analyticstracker\/checkoutanalyticsevents"},"doc://com.yababaGmbH.yababa/documentation/Yababa/AnalyticsTracker/trackSearchBarClicked(eventOrigin:)":{"role":"symbol","title":"trackSearchBarClicked(eventOrigin:)","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"trackSearchBarClicked"},{"kind":"text","text":"("},{"kind":"externalParam","text":"eventOrigin"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AnalyticsTracker\/trackSearchBarClicked(eventOrigin:)","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/analyticstracker\/tracksearchbarclicked(eventorigin:)"},"doc://com.yababaGmbH.yababa/documentation/Yababa/AnalyticsTracker/trackJustBrowse()":{"role":"symbol","title":"trackJustBrowse()","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"trackJustBrowse"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AnalyticsTracker\/trackJustBrowse()","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/analyticstracker\/trackjustbrowse()"},"doc://com.yababaGmbH.yababa/documentation/Yababa/AnalyticsTracker/trackAppleSignIn()":{"role":"symbol","title":"trackAppleSignIn()","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"trackAppleSignIn"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AnalyticsTracker\/trackAppleSignIn()","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/analyticstracker\/trackapplesignin()"},"doc://com.yababaGmbH.yababa/documentation/Yababa/AnalyticsTracker/trackWalletDisplayed(code:origin:totalVouchers:)":{"role":"symbol","title":"trackWalletDisplayed(code:origin:totalVouchers:)","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"trackWalletDisplayed"},{"kind":"text","text":"("},{"kind":"externalParam","text":"code"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"origin"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TrackingOrigin","preciseIdentifier":"s:6Yababa14TrackingOriginO"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"totalVouchers"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AnalyticsTracker\/trackWalletDisplayed(code:origin:totalVouchers:)","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/analyticstracker\/trackwalletdisplayed(code:origin:totalvouchers:)"},"doc://com.yababaGmbH.yababa/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(cs)NSObject"},"doc://com.yababaGmbH.yababa/documentation/Yababa/AnalyticsTracker/CheckOutPriceDifferenceShown(cartItemsWithPriceChange:)":{"role":"symbol","title":"CheckOutPriceDifferenceShown(cartItemsWithPriceChange:)","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"CheckOutPriceDifferenceShown"},{"kind":"text","text":"("},{"kind":"externalParam","text":"cartItemsWithPriceChange"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":"])"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AnalyticsTracker\/CheckOutPriceDifferenceShown(cartItemsWithPriceChange:)","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/analyticstracker\/checkoutpricedifferenceshown(cartitemswithpricechange:)"},"doc://com.yababaGmbH.yababa/documentation/Yababa/AnalyticsTracker/trackProductDetailsSelected(productID:productName:productUnitPrice:productPosition:inStock:eventOrigin:)":{"role":"symbol","title":"trackProductDetailsSelected(productID:productName:productUnitPrice:productPosition:inStock:eventOrigin:)","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"trackProductDetailsSelected"},{"kind":"text","text":"("},{"kind":"externalParam","text":"productID"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"kind":"externalParam","text":"productName"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"productUnitPrice"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"},{"kind":"text","text":", "},{"kind":"externalParam","text":"productPosition"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"inStock"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"eventOrigin"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AnalyticsTracker\/trackProductDetailsSelected(productID:productName:productUnitPrice:productPosition:inStock:eventOrigin:)","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/analyticstracker\/trackproductdetailsselected(productid:productname:productunitprice:productposition:instock:eventorigin:)"},"doc://com.yababaGmbH.yababa/documentation/Yababa/AnalyticsTracker/trackOrderTrackingLoaded()":{"role":"symbol","title":"trackOrderTrackingLoaded()","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"trackOrderTrackingLoaded"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AnalyticsTracker\/trackOrderTrackingLoaded()","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/analyticstracker\/trackordertrackingloaded()"},"doc://com.yababaGmbH.yababa/documentation/Yababa/AnalyticsTracker/trackReferralPopupLoaded(eventOrigin:)":{"role":"symbol","title":"trackReferralPopupLoaded(eventOrigin:)","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"trackReferralPopupLoaded"},{"kind":"text","text":"("},{"kind":"externalParam","text":"eventOrigin"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TrackingOrigin","preciseIdentifier":"s:6Yababa14TrackingOriginO"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AnalyticsTracker\/trackReferralPopupLoaded(eventOrigin:)","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/analyticstracker\/trackreferralpopuploaded(eventorigin:)"},"doc://com.yababaGmbH.yababa/documentation/Yababa/AnalyticsTracker/trackAddressOutOfDeliveryZone(postalCode:)":{"role":"symbol","title":"trackAddressOutOfDeliveryZone(postalCode:)","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"trackAddressOutOfDeliveryZone"},{"kind":"text","text":"("},{"kind":"externalParam","text":"postalCode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AnalyticsTracker\/trackAddressOutOfDeliveryZone(postalCode:)","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/analyticstracker\/trackaddressoutofdeliveryzone(postalcode:)"},"doc://com.yababaGmbH.yababa/documentation/Yababa/AnalyticsTracker/trackWalletPromosClicked()":{"role":"symbol","title":"trackWalletPromosClicked()","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"trackWalletPromosClicked"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AnalyticsTracker\/trackWalletPromosClicked()","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/analyticstracker\/trackwalletpromosclicked()"},"doc://com.yababaGmbH.yababa/documentation/Yababa/AnalyticsTracker/trackSuccessCouponApplied(couponCode:)":{"role":"symbol","title":"trackSuccessCouponApplied(couponCode:)","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"trackSuccessCouponApplied"},{"kind":"text","text":"("},{"kind":"externalParam","text":"couponCode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AnalyticsTracker\/trackSuccessCouponApplied(couponCode:)","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/analyticstracker\/tracksuccesscouponapplied(couponcode:)"},"doc://com.yababaGmbH.yababa/documentation/Yababa/AnalyticsTracker/trackCheckOutNewCreditCardPayButtonClicked()":{"role":"symbol","title":"trackCheckOutNewCreditCardPayButtonClicked()","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"trackCheckOutNewCreditCardPayButtonClicked"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AnalyticsTracker\/trackCheckOutNewCreditCardPayButtonClicked()","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/analyticstracker\/trackcheckoutnewcreditcardpaybuttonclicked()"},"doc://com.yababaGmbH.yababa/documentation/Yababa/AnalyticsTracker/trackHomePageLoaded(hasWalletCollection:)":{"role":"symbol","title":"trackHomePageLoaded(hasWalletCollection:)","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"trackHomePageLoaded"},{"kind":"text","text":"("},{"kind":"externalParam","text":"hasWalletCollection"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":"?)"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AnalyticsTracker\/trackHomePageLoaded(hasWalletCollection:)","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/analyticstracker\/trackhomepageloaded(haswalletcollection:)"},"doc://com.yababaGmbH.yababa/documentation/Yababa/AnalyticsTracker/TimeSlotAnalyticEvents":{"role":"symbol","title":"AnalyticsTracker.TimeSlotAnalyticEvents","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TimeSlotAnalyticEvents"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AnalyticsTracker\/TimeSlotAnalyticEvents","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"TimeSlotAnalyticEvents"}],"url":"\/documentation\/yababa\/analyticstracker\/timeslotanalyticevents"},"doc://com.yababaGmbH.yababa/documentation/Yababa/AnalyticsTracker/trackPickTimeSlotClicked(eventOrigin:)":{"role":"symbol","title":"trackPickTimeSlotClicked(eventOrigin:)","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"trackPickTimeSlotClicked"},{"kind":"text","text":"("},{"kind":"externalParam","text":"eventOrigin"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AnalyticsTracker\/trackPickTimeSlotClicked(eventOrigin:)","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/analyticstracker\/trackpicktimeslotclicked(eventorigin:)"},"doc://com.yababaGmbH.yababa/documentation/Yababa/AnalyticsTracker/trackPaymentGateway(name:)":{"role":"symbol","title":"trackPaymentGateway(name:)","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"trackPaymentGateway"},{"kind":"text","text":"("},{"kind":"externalParam","text":"name"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AnalyticsTracker\/trackPaymentGateway(name:)","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/analyticstracker\/trackpaymentgateway(name:)"},"doc://com.yababaGmbH.yababa/documentation/Yababa/AnalyticsTracker/trackSelectedVoucherChanged(from:code:)":{"role":"symbol","title":"trackSelectedVoucherChanged(from:code:)","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"trackSelectedVoucherChanged"},{"kind":"text","text":"("},{"kind":"externalParam","text":"from"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TrackingOrigin","preciseIdentifier":"s:6Yababa14TrackingOriginO"},{"kind":"text","text":", "},{"kind":"externalParam","text":"code"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?)"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AnalyticsTracker\/trackSelectedVoucherChanged(from:code:)","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/analyticstracker\/trackselectedvoucherchanged(from:code:)"},"doc://com.yababaGmbH.yababa/documentation/Yababa/AnalyticsTracker/trackCheckOutCompleted(orderId:cartValue:distinctProducts:productsQuantity:shopDiscount:shopDeliveryFee:totalVoucher:paymentMethod:pickDay:pickTime:couponCode:couponName:)":{"role":"symbol","title":"trackCheckOutCompleted(orderId:cartValue:distinctProducts:productsQuantity:shopDiscount:shopDeliveryFee:totalVoucher:paymentMethod:pickDay:pickTime:couponCode:couponName:)","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"trackCheckOutCompleted"},{"kind":"text","text":"("},{"kind":"externalParam","text":"orderId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"cartValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"},{"kind":"text","text":", "},{"kind":"externalParam","text":"distinctProducts"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"ShoppingCartItem","preciseIdentifier":"s:6Yababa16ShoppingCartItemC"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"productsQuantity"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"kind":"externalParam","text":"shopDiscount"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"},{"kind":"text","text":", "},{"kind":"externalParam","text":"shopDeliveryFee"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"},{"kind":"text","text":", "},{"kind":"externalParam","text":"totalVoucher"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"},{"kind":"text","text":", "},{"kind":"externalParam","text":"paymentMethod"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"pickDay"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"pickTime"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"couponCode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"couponName"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?)"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AnalyticsTracker\/trackCheckOutCompleted(orderId:cartValue:distinctProducts:productsQuantity:shopDiscount:shopDeliveryFee:totalVoucher:paymentMethod:pickDay:pickTime:couponCode:couponName:)","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/analyticstracker\/trackcheckoutcompleted(orderid:cartvalue:distinctproducts:productsquantity:shopdiscount:shopdeliveryfee:totalvoucher:paymentmethod:pickday:picktime:couponcode:couponname:)"},"doc://com.yababaGmbH.yababa/documentation/Yababa/AnalyticsTracker/trackPromotionPageClicked(bannerId:searchTags:)":{"role":"symbol","title":"trackPromotionPageClicked(bannerId:searchTags:)","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"trackPromotionPageClicked"},{"kind":"text","text":"("},{"kind":"externalParam","text":"bannerId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"searchTags"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"]?)"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AnalyticsTracker\/trackPromotionPageClicked(bannerId:searchTags:)","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/analyticstracker\/trackpromotionpageclicked(bannerid:searchtags:)"},"doc://com.yababaGmbH.yababa/documentation/Yababa/AnalyticsTracker/trackPassPassed()":{"role":"symbol","title":"trackPassPassed()","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"trackPassPassed"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AnalyticsTracker\/trackPassPassed()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"trackPassPassed"}],"url":"\/documentation\/yababa\/analyticstracker\/trackpasspassed()"},"doc://com.yababaGmbH.yababa/documentation/Yababa/AnalyticsTracker/trackEmailSignIn()":{"role":"symbol","title":"trackEmailSignIn()","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"trackEmailSignIn"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AnalyticsTracker\/trackEmailSignIn()","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/analyticstracker\/trackemailsignin()"},"doc://com.yababaGmbH.yababa/documentation/Yababa/AnalyticsTracker/trackForceUserToLogout()":{"role":"symbol","title":"trackForceUserToLogout()","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"trackForceUserToLogout"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AnalyticsTracker\/trackForceUserToLogout()","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/analyticstracker\/trackforceusertologout()"},"doc://com.yababaGmbH.yababa/documentation/Yababa/AnalyticsTracker/SearchAnalyticEvents":{"role":"symbol","title":"AnalyticsTracker.SearchAnalyticEvents","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SearchAnalyticEvents"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AnalyticsTracker\/SearchAnalyticEvents","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SearchAnalyticEvents"}],"url":"\/documentation\/yababa\/analyticstracker\/searchanalyticevents"},"doc://com.yababaGmbH.yababa/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.yababaGmbH.yababa\/s7CVarArgP"},"doc://com.yababaGmbH.yababa/documentation/Yababa/AnalyticsTracker/trackAccountRegistered()":{"role":"symbol","title":"trackAccountRegistered()","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"trackAccountRegistered"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AnalyticsTracker\/trackAccountRegistered()","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/analyticstracker\/trackaccountregistered()"},"doc://com.yababaGmbH.yababa/documentation/Yababa/AnalyticsTracker/trackGoogleSignup()":{"role":"symbol","title":"trackGoogleSignup()","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"trackGoogleSignup"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AnalyticsTracker\/trackGoogleSignup()","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/analyticstracker\/trackgooglesignup()"},"doc://com.yababaGmbH.yababa/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.yababaGmbH.yababa\/s23CustomStringConvertibleP"},"doc://com.yababaGmbH.yababa/documentation/Yababa/AnalyticsTracker/trackBannerSeen(bannerCode:position:)":{"role":"symbol","title":"trackBannerSeen(bannerCode:position:)","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"trackBannerSeen"},{"kind":"text","text":"("},{"kind":"externalParam","text":"bannerCode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"position"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AnalyticsTracker\/trackBannerSeen(bannerCode:position:)","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/analyticstracker\/trackbannerseen(bannercode:position:)"},"doc://com.yababaGmbH.yababa/documentation/Yababa/AnalyticsBaseTracker":{"role":"symbol","title":"AnalyticsBaseTracker","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"AnalyticsBaseTracker"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AnalyticsBaseTracker","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AnalyticsBaseTracker"}],"url":"\/documentation\/yababa\/analyticsbasetracker"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"AnalyticsTracker"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AnalyticsTracker"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"AnalyticsTracker"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AnalyticsTracker\/init"]},{"title":"Type Methods","identifiers":["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AnalyticsTracker\/trackPassPassed()"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.yababaGmbH.yababa\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"AnalyticsTracker"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1AnalyticsTracker\/title","value":"AnalyticsTracker"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1AnalyticsTracker\/fragments","value":[{"kind":"identifier","text":"AnalyticsTracker"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1AnalyticsTracker~1trackPassPassed()\/title","value":"trackPassPassed"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1AnalyticsTracker~1trackPassPassed()\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"trackPassPassed"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}