{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objcMembers"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AppInfo"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/yababa\/appinfo"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/yababa\/appinfo"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.yababaGmbH.yababa\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.yababaGmbH.yababa\/objc(pl)NSObject","doc:\/\/com.yababaGmbH.yababa\/12SkeletonView17AssociatedObjectsP","doc:\/\/com.yababaGmbH.yababa\/s7CVarArgP","doc:\/\/com.yababaGmbH.yababa\/s28CustomDebugStringConvertibleP","doc:\/\/com.yababaGmbH.yababa\/s23CustomStringConvertibleP","doc:\/\/com.yababaGmbH.yababa\/SQ","doc:\/\/com.yababaGmbH.yababa\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AppInfo","interfaceLanguage":"swift"},"topicSections":[{"title":"Classes","identifiers":["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AppInfo\/Algolia","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AppInfo\/Braze","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AppInfo\/Castle","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AppInfo\/Languages","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AppInfo\/Mixpanel","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AppInfo\/Sentry","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AppInfo\/UXCam"]},{"title":"Type Properties","identifiers":["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AppInfo\/StripeApplePayMerchantId","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AppInfo\/apiVersion","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AppInfo\/appBuild","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AppInfo\/appVersion","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AppInfo\/appVersionAndBuildNumber","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AppInfo\/brandApiKey","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AppInfo\/contactUsEmail","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AppInfo\/isCurrentEnvironmentLive","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AppInfo\/isDevelopmentBuild","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AppInfo\/isTestFlightBuild","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AppInfo\/privacyPolicy","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AppInfo\/termsOfService"]}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AppInfo"}],"title":"AppInfo","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@Yababa@objc(cs)AppInfo","modules":[{"name":"Yababa"}],"navigatorTitle":[{"kind":"identifier","text":"AppInfo"}]},"hierarchy":{"paths":[["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa"]]},"references":{"doc://com.yababaGmbH.yababa/documentation/Yababa/AppInfo/Braze":{"role":"symbol","title":"AppInfo.Braze","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Braze"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AppInfo\/Braze","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Braze"}],"url":"\/documentation\/yababa\/appinfo\/braze"},"doc://com.yababaGmbH.yababa/documentation/Yababa/AppInfo/appVersion":{"role":"symbol","title":"appVersion","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"appVersion"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AppInfo\/appVersion","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"appVersion"}],"url":"\/documentation\/yababa\/appinfo\/appversion"},"doc://com.yababaGmbH.yababa/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.yababaGmbH.yababa\/s23CustomStringConvertibleP"},"doc://com.yababaGmbH.yababa/documentation/Yababa/AppInfo/init":{"role":"symbol","title":"init","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AppInfo\/init","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"init"}],"url":"\/documentation\/yababa\/appinfo\/init"},"doc://com.yababaGmbH.yababa/documentation/Yababa/AppInfo/isTestFlightBuild":{"role":"symbol","title":"isTestFlightBuild","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isTestFlightBuild"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AppInfo\/isTestFlightBuild","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"isTestFlightBuild"}],"url":"\/documentation\/yababa\/appinfo\/istestflightbuild"},"doc://com.yababaGmbH.yababa/documentation/Yababa/AppInfo/Mixpanel":{"role":"symbol","title":"AppInfo.Mixpanel","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Mixpanel"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AppInfo\/Mixpanel","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Mixpanel"}],"url":"\/documentation\/yababa\/appinfo\/mixpanel"},"doc://com.yababaGmbH.yababa/documentation/Yababa/AppInfo/Algolia":{"role":"symbol","title":"AppInfo.Algolia","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Algolia"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AppInfo\/Algolia","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Algolia"}],"url":"\/documentation\/yababa\/appinfo\/algolia"},"doc://com.yababaGmbH.yababa/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.yababaGmbH.yababa\/s28CustomDebugStringConvertibleP"},"doc://com.yababaGmbH.yababa/documentation/Yababa/AppInfo/Languages":{"role":"symbol","title":"AppInfo.Languages","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Languages"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AppInfo\/Languages","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Languages"}],"url":"\/documentation\/yababa\/appinfo\/languages"},"doc://com.yababaGmbH.yababa/documentation/Yababa/AppInfo/isDevelopmentBuild":{"role":"symbol","title":"isDevelopmentBuild","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isDevelopmentBuild"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AppInfo\/isDevelopmentBuild","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"isDevelopmentBuild"}],"url":"\/documentation\/yababa\/appinfo\/isdevelopmentbuild"},"doc://com.yababaGmbH.yababa/documentation/Yababa/AppInfo/UXCam":{"role":"symbol","title":"AppInfo.UXCam","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"UXCam"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AppInfo\/UXCam","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"UXCam"}],"url":"\/documentation\/yababa\/appinfo\/uxcam"},"doc://com.yababaGmbH.yababa/documentation/Yababa/AppInfo/appVersionAndBuildNumber":{"role":"symbol","title":"appVersionAndBuildNumber","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"appVersionAndBuildNumber"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AppInfo\/appVersionAndBuildNumber","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"appVersionAndBuildNumber"}],"url":"\/documentation\/yababa\/appinfo\/appversionandbuildnumber"},"doc://com.yababaGmbH.yababa/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.yababaGmbH.yababa\/SH"},"doc://com.yababaGmbH.yababa/documentation/Yababa/AppInfo/isCurrentEnvironmentLive":{"role":"symbol","title":"isCurrentEnvironmentLive","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isCurrentEnvironmentLive"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AppInfo\/isCurrentEnvironmentLive","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"isCurrentEnvironmentLive"}],"url":"\/documentation\/yababa\/appinfo\/iscurrentenvironmentlive"},"doc://com.yababaGmbH.yababa/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.yababaGmbH.yababa\/s7CVarArgP"},"doc://com.yababaGmbH.yababa/documentation/Yababa/AppInfo/contactUsEmail":{"role":"symbol","title":"contactUsEmail","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"contactUsEmail"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AppInfo\/contactUsEmail","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"contactUsEmail"}],"url":"\/documentation\/yababa\/appinfo\/contactusemail"},"doc://com.yababaGmbH.yababa/documentation/Yababa/AppInfo/Sentry":{"role":"symbol","title":"AppInfo.Sentry","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Sentry"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AppInfo\/Sentry","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Sentry"}],"url":"\/documentation\/yababa\/appinfo\/sentry"},"doc://com.yababaGmbH.yababa/12SkeletonView17AssociatedObjectsP":{"type":"unresolvable","title":"SkeletonView.AssociatedObjects","identifier":"doc:\/\/com.yababaGmbH.yababa\/12SkeletonView17AssociatedObjectsP"},"doc://com.yababaGmbH.yababa/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)NSObject"},"doc://com.yababaGmbH.yababa/documentation/Yababa/AppInfo/brandApiKey":{"role":"symbol","title":"brandApiKey","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"brandApiKey"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AppInfo\/brandApiKey","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"brandApiKey"}],"url":"\/documentation\/yababa\/appinfo\/brandapikey"},"doc://com.yababaGmbH.yababa/documentation/Yababa/AppInfo/StripeApplePayMerchantId":{"role":"symbol","title":"StripeApplePayMerchantId","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"StripeApplePayMerchantId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AppInfo\/StripeApplePayMerchantId","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"StripeApplePayMerchantId"}],"url":"\/documentation\/yababa\/appinfo\/stripeapplepaymerchantid"},"doc://com.yababaGmbH.yababa/documentation/Yababa/AppInfo/Castle":{"role":"symbol","title":"AppInfo.Castle","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Castle"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AppInfo\/Castle","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Castle"}],"url":"\/documentation\/yababa\/appinfo\/castle"},"doc://com.yababaGmbH.yababa/documentation/Yababa/AppInfo/termsOfService":{"role":"symbol","title":"termsOfService","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"termsOfService"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AppInfo\/termsOfService","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"termsOfService"}],"url":"\/documentation\/yababa\/appinfo\/termsofservice"},"doc://com.yababaGmbH.yababa/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(cs)NSObject"},"doc://com.yababaGmbH.yababa/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.yababaGmbH.yababa\/SQ"},"doc://com.yababaGmbH.yababa/documentation/Yababa":{"role":"collection","title":"Yababa","abstract":[{"type":"text","text":"Getting Started"}],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa","kind":"symbol","type":"topic","url":"\/documentation\/yababa"},"doc://com.yababaGmbH.yababa/documentation/Yababa/AppInfo/apiVersion":{"role":"symbol","title":"apiVersion","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"apiVersion"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AppInfo\/apiVersion","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"apiVersion"}],"url":"\/documentation\/yababa\/appinfo\/apiversion"},"doc://com.yababaGmbH.yababa/documentation/Yababa/AppInfo/appBuild":{"role":"symbol","title":"appBuild","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"appBuild"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AppInfo\/appBuild","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"appBuild"}],"url":"\/documentation\/yababa\/appinfo\/appbuild"},"doc://com.yababaGmbH.yababa/documentation/Yababa/AppInfo/privacyPolicy":{"role":"symbol","title":"privacyPolicy","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"privacyPolicy"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AppInfo\/privacyPolicy","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"privacyPolicy"}],"url":"\/documentation\/yababa\/appinfo\/privacypolicy"},"doc://com.yababaGmbH.yababa/documentation/Yababa/AppInfo":{"role":"symbol","title":"AppInfo","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AppInfo"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AppInfo","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AppInfo"}],"url":"\/documentation\/yababa\/appinfo"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"AppInfo"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AppInfo"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"AppInfo"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AppInfo\/init"]},{"title":"Type Properties","identifiers":["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AppInfo\/StripeApplePayMerchantId","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AppInfo\/apiVersion","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AppInfo\/appBuild","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AppInfo\/appVersion","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AppInfo\/appVersionAndBuildNumber","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AppInfo\/brandApiKey","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AppInfo\/contactUsEmail","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AppInfo\/isCurrentEnvironmentLive","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AppInfo\/isDevelopmentBuild","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AppInfo\/isTestFlightBuild","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AppInfo\/privacyPolicy","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AppInfo\/termsOfService"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.yababaGmbH.yababa\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"AppInfo"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1AppInfo~1appVersion\/title","value":"appVersion"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1AppInfo~1appVersion\/fragments","value":[{"kind":"identifier","text":"appVersion"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1AppInfo~1isTestFlightBuild\/title","value":"isTestFlightBuild"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1AppInfo~1isTestFlightBuild\/fragments","value":[{"kind":"identifier","text":"isTestFlightBuild"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1AppInfo~1isDevelopmentBuild\/title","value":"isDevelopmentBuild"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1AppInfo~1isDevelopmentBuild\/fragments","value":[{"kind":"identifier","text":"isDevelopmentBuild"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1AppInfo~1appVersionAndBuildNumber\/title","value":"appVersionAndBuildNumber"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1AppInfo~1appVersionAndBuildNumber\/fragments","value":[{"kind":"identifier","text":"appVersionAndBuildNumber"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1AppInfo~1isCurrentEnvironmentLive\/title","value":"isCurrentEnvironmentLive"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1AppInfo~1isCurrentEnvironmentLive\/fragments","value":[{"kind":"identifier","text":"isCurrentEnvironmentLive"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1AppInfo~1contactUsEmail\/title","value":"contactUsEmail"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1AppInfo~1contactUsEmail\/fragments","value":[{"kind":"identifier","text":"contactUsEmail"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1AppInfo~1brandApiKey\/title","value":"brandApiKey"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1AppInfo~1brandApiKey\/fragments","value":[{"kind":"identifier","text":"brandApiKey"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1AppInfo~1StripeApplePayMerchantId\/title","value":"StripeApplePayMerchantId"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1AppInfo~1StripeApplePayMerchantId\/fragments","value":[{"kind":"identifier","text":"StripeApplePayMerchantId"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1AppInfo~1termsOfService\/title","value":"termsOfService"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1AppInfo~1termsOfService\/fragments","value":[{"kind":"identifier","text":"termsOfService"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1AppInfo~1apiVersion\/title","value":"apiVersion"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1AppInfo~1apiVersion\/fragments","value":[{"kind":"identifier","text":"apiVersion"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1AppInfo~1appBuild\/title","value":"appBuild"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1AppInfo~1appBuild\/fragments","value":[{"kind":"identifier","text":"appBuild"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1AppInfo~1privacyPolicy\/title","value":"privacyPolicy"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1AppInfo~1privacyPolicy\/fragments","value":[{"kind":"identifier","text":"privacyPolicy"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1AppInfo\/title","value":"AppInfo"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1AppInfo\/fragments","value":[{"kind":"identifier","text":"AppInfo"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}