{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objcMembers"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AppManager"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/yababa\/appmanager"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/yababa\/appmanager"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.yababaGmbH.yababa\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.yababaGmbH.yababa\/objc(pl)NSObject","doc:\/\/com.yababaGmbH.yababa\/12SkeletonView17AssociatedObjectsP","doc:\/\/com.yababaGmbH.yababa\/s7CVarArgP","doc:\/\/com.yababaGmbH.yababa\/s28CustomDebugStringConvertibleP","doc:\/\/com.yababaGmbH.yababa\/s23CustomStringConvertibleP","doc:\/\/com.yababaGmbH.yababa\/SQ","doc:\/\/com.yababaGmbH.yababa\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AppManager","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AppManager\/analyticsTrackerService","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AppManager\/currentNavigationController","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AppManager\/currentTabBarController"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AppManager\/appHasBeenLoggedInStateAtleastOnce()","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AppManager\/changeAppLanguage(_:)","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AppManager\/configure()","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AppManager\/fetchStockItems()","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AppManager\/getAlertStyle()","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AppManager\/performLogout()","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AppManager\/performLogoutWithSessionExpireMessage()","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AppManager\/reloadWindow()","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AppManager\/setAppHasBeenLoggedInStateAtleastOnce()","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AppManager\/setupReachability()","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AppManager\/showAdjustedCartItems(_:)","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AppManager\/showMessage(_:)","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AppManager\/showServerMaintenanceMessage(message:)","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AppManager\/showWelcomeScreen()","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AppManager\/updateConnectionStatus(_:)"]},{"title":"Type Properties","identifiers":["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AppManager\/sharedInstance"]}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AppManager"}],"title":"AppManager","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@Yababa@objc(cs)AppManager","modules":[{"name":"Yababa"}],"navigatorTitle":[{"kind":"identifier","text":"AppManager"}]},"hierarchy":{"paths":[["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa"]]},"references":{"doc://com.yababaGmbH.yababa/documentation/Yababa/AppManager/performLogoutWithSessionExpireMessage()":{"role":"symbol","title":"performLogoutWithSessionExpireMessage()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"performLogoutWithSessionExpireMessage"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AppManager\/performLogoutWithSessionExpireMessage()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"performLogoutWithSessionExpireMessage"}],"url":"\/documentation\/yababa\/appmanager\/performlogoutwithsessionexpiremessage()"},"doc://com.yababaGmbH.yababa/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.yababaGmbH.yababa\/s23CustomStringConvertibleP"},"doc://com.yababaGmbH.yababa/documentation/Yababa/AppManager/showServerMaintenanceMessage(message:)":{"role":"symbol","title":"showServerMaintenanceMessage(message:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"showServerMaintenanceMessage"},{"kind":"text","text":"("},{"kind":"externalParam","text":"message"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AppManager\/showServerMaintenanceMessage(message:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"showServerMaintenanceMessageWithMessage:"}],"url":"\/documentation\/yababa\/appmanager\/showservermaintenancemessage(message:)"},"doc://com.yababaGmbH.yababa/documentation/Yababa/AppManager/configure()":{"role":"symbol","title":"configure()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"configure"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AppManager\/configure()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"configure"}],"url":"\/documentation\/yababa\/appmanager\/configure()"},"doc://com.yababaGmbH.yababa/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(cs)NSObject"},"doc://com.yababaGmbH.yababa/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)NSObject"},"doc://com.yababaGmbH.yababa/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.yababaGmbH.yababa\/s7CVarArgP"},"doc://com.yababaGmbH.yababa/documentation/Yababa/AppManager/currentNavigationController":{"role":"symbol","title":"currentNavigationController","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"currentNavigationController"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UINavigationController","preciseIdentifier":"c:objc(cs)UINavigationController"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AppManager\/currentNavigationController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"currentNavigationController"}],"url":"\/documentation\/yababa\/appmanager\/currentnavigationcontroller"},"doc://com.yababaGmbH.yababa/documentation/Yababa/AppManager/currentTabBarController":{"role":"symbol","title":"currentTabBarController","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"currentTabBarController"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TabBarController","preciseIdentifier":"c:@M@Yababa@objc(cs)TabBarController"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AppManager\/currentTabBarController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"currentTabBarController"}],"url":"\/documentation\/yababa\/appmanager\/currenttabbarcontroller"},"doc://com.yababaGmbH.yababa/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.yababaGmbH.yababa\/s28CustomDebugStringConvertibleP"},"doc://com.yababaGmbH.yababa/documentation/Yababa/AppManager/sharedInstance":{"role":"symbol","title":"sharedInstance","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"sharedInstance"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AppManager","preciseIdentifier":"c:@M@Yababa@objc(cs)AppManager"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AppManager\/sharedInstance","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"sharedInstance"}],"url":"\/documentation\/yababa\/appmanager\/sharedinstance"},"doc://com.yababaGmbH.yababa/documentation/Yababa/AppManager/performLogout()":{"role":"symbol","title":"performLogout()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"performLogout"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AppManager\/performLogout()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"performLogout"}],"url":"\/documentation\/yababa\/appmanager\/performlogout()"},"doc://com.yababaGmbH.yababa/documentation/Yababa/AppManager/fetchStockItems()":{"role":"symbol","title":"fetchStockItems()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"fetchStockItems"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AppManager\/fetchStockItems()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"fetchStockItems"}],"url":"\/documentation\/yababa\/appmanager\/fetchstockitems()"},"doc://com.yababaGmbH.yababa/documentation/Yababa/AppManager":{"role":"symbol","title":"AppManager","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AppManager"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AppManager","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AppManager"}],"url":"\/documentation\/yababa\/appmanager"},"doc://com.yababaGmbH.yababa/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.yababaGmbH.yababa\/SQ"},"doc://com.yababaGmbH.yababa/documentation/Yababa/AppManager/setAppHasBeenLoggedInStateAtleastOnce()":{"role":"symbol","title":"setAppHasBeenLoggedInStateAtleastOnce()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setAppHasBeenLoggedInStateAtleastOnce"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AppManager\/setAppHasBeenLoggedInStateAtleastOnce()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"setAppHasBeenLoggedInStateAtleastOnce"}],"url":"\/documentation\/yababa\/appmanager\/setapphasbeenloggedinstateatleastonce()"},"doc://com.yababaGmbH.yababa/documentation/Yababa/AppManager/showMessage(_:)":{"role":"symbol","title":"showMessage(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"showMessage"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AppManager\/showMessage(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"showMessage:"}],"url":"\/documentation\/yababa\/appmanager\/showmessage(_:)"},"doc://com.yababaGmbH.yababa/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.yababaGmbH.yababa\/SH"},"doc://com.yababaGmbH.yababa/documentation/Yababa/AppManager/analyticsTrackerService":{"role":"symbol","title":"analyticsTrackerService","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"analyticsTrackerService"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AnalyticsTrackerService","preciseIdentifier":"s:6Yababa23AnalyticsTrackerServiceP"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AppManager\/analyticsTrackerService","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/appmanager\/analyticstrackerservice"},"doc://com.yababaGmbH.yababa/documentation/Yababa/AppManager/getAlertStyle()":{"role":"symbol","title":"getAlertStyle()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getAlertStyle"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"UIAlertController","preciseIdentifier":"c:objc(cs)UIAlertController"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"Style","preciseIdentifier":"c:@E@UIAlertControllerStyle"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AppManager\/getAlertStyle()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"getAlertStyle"}],"url":"\/documentation\/yababa\/appmanager\/getalertstyle()"},"doc://com.yababaGmbH.yababa/documentation/Yababa/AppManager/updateConnectionStatus(_:)":{"role":"symbol","title":"updateConnectionStatus(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"updateConnectionStatus"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Connectivity","preciseIdentifier":"s:12ConnectivityAAC"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"Status","preciseIdentifier":"s:12ConnectivityAAC6Statusa"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AppManager\/updateConnectionStatus(_:)","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/appmanager\/updateconnectionstatus(_:)"},"doc://com.yababaGmbH.yababa/documentation/Yababa/AppManager/showWelcomeScreen()":{"role":"symbol","title":"showWelcomeScreen()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"showWelcomeScreen"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AppManager\/showWelcomeScreen()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"showWelcomeScreen"}],"url":"\/documentation\/yababa\/appmanager\/showwelcomescreen()"},"doc://com.yababaGmbH.yababa/documentation/Yababa/AppManager/init":{"role":"symbol","title":"init","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AppManager\/init","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"init"}],"url":"\/documentation\/yababa\/appmanager\/init"},"doc://com.yababaGmbH.yababa/documentation/Yababa/AppManager/changeAppLanguage(_:)":{"role":"symbol","title":"changeAppLanguage(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"changeAppLanguage"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AppManager\/changeAppLanguage(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"changeAppLanguage:"}],"url":"\/documentation\/yababa\/appmanager\/changeapplanguage(_:)"},"doc://com.yababaGmbH.yababa/documentation/Yababa/AppManager/appHasBeenLoggedInStateAtleastOnce()":{"role":"symbol","title":"appHasBeenLoggedInStateAtleastOnce()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"appHasBeenLoggedInStateAtleastOnce"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AppManager\/appHasBeenLoggedInStateAtleastOnce()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"appHasBeenLoggedInStateAtleastOnce"}],"url":"\/documentation\/yababa\/appmanager\/apphasbeenloggedinstateatleastonce()"},"doc://com.yababaGmbH.yababa/documentation/Yababa/AppManager/setupReachability()":{"role":"symbol","title":"setupReachability()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setupReachability"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AppManager\/setupReachability()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"setupReachability"}],"url":"\/documentation\/yababa\/appmanager\/setupreachability()"},"doc://com.yababaGmbH.yababa/12SkeletonView17AssociatedObjectsP":{"type":"unresolvable","title":"SkeletonView.AssociatedObjects","identifier":"doc:\/\/com.yababaGmbH.yababa\/12SkeletonView17AssociatedObjectsP"},"doc://com.yababaGmbH.yababa/documentation/Yababa":{"role":"collection","title":"Yababa","abstract":[{"type":"text","text":"Getting Started"}],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa","kind":"symbol","type":"topic","url":"\/documentation\/yababa"},"doc://com.yababaGmbH.yababa/documentation/Yababa/AppManager/showAdjustedCartItems(_:)":{"role":"symbol","title":"showAdjustedCartItems(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"showAdjustedCartItems"},{"kind":"text","text":"(["},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"ShoppingCartItem","preciseIdentifier":"s:6Yababa16ShoppingCartItemC"},{"kind":"text","text":"])"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AppManager\/showAdjustedCartItems(_:)","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/appmanager\/showadjustedcartitems(_:)"},"doc://com.yababaGmbH.yababa/documentation/Yababa/AppManager/reloadWindow()":{"role":"symbol","title":"reloadWindow()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"reloadWindow"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AppManager\/reloadWindow()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"reloadWindow"}],"url":"\/documentation\/yababa\/appmanager\/reloadwindow()"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"AppManager"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AppManager"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"AppManager"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AppManager\/currentNavigationController","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AppManager\/currentTabBarController"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AppManager\/appHasBeenLoggedInStateAtleastOnce()","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AppManager\/changeAppLanguage(_:)","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AppManager\/configure()","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AppManager\/fetchStockItems()","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AppManager\/getAlertStyle()","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AppManager\/init","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AppManager\/performLogout()","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AppManager\/performLogoutWithSessionExpireMessage()","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AppManager\/reloadWindow()","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AppManager\/setAppHasBeenLoggedInStateAtleastOnce()","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AppManager\/setupReachability()","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AppManager\/showMessage(_:)","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AppManager\/showServerMaintenanceMessage(message:)","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AppManager\/showWelcomeScreen()"]},{"title":"Type Properties","identifiers":["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AppManager\/sharedInstance"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.yababaGmbH.yababa\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"AppManager"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1AppManager~1performLogoutWithSessionExpireMessage()\/title","value":"performLogoutWithSessionExpireMessage"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1AppManager~1performLogoutWithSessionExpireMessage()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"performLogoutWithSessionExpireMessage"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1AppManager~1showServerMaintenanceMessage(message:)\/title","value":"showServerMaintenanceMessageWithMessage:"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1AppManager~1showServerMaintenanceMessage(message:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"showServerMaintenanceMessageWithMessage:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1AppManager~1configure()\/title","value":"configure"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1AppManager~1configure()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"configure"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1AppManager~1currentNavigationController\/title","value":"currentNavigationController"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1AppManager~1currentNavigationController\/fragments","value":[{"kind":"identifier","text":"currentNavigationController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1AppManager~1currentTabBarController\/title","value":"currentTabBarController"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1AppManager~1currentTabBarController\/fragments","value":[{"kind":"identifier","text":"currentTabBarController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1AppManager~1sharedInstance\/title","value":"sharedInstance"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1AppManager~1sharedInstance\/fragments","value":[{"kind":"identifier","text":"sharedInstance"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1AppManager~1performLogout()\/title","value":"performLogout"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1AppManager~1performLogout()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"performLogout"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1AppManager~1fetchStockItems()\/title","value":"fetchStockItems"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1AppManager~1fetchStockItems()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"fetchStockItems"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1AppManager\/title","value":"AppManager"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1AppManager\/fragments","value":[{"kind":"identifier","text":"AppManager"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1AppManager~1setAppHasBeenLoggedInStateAtleastOnce()\/title","value":"setAppHasBeenLoggedInStateAtleastOnce"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1AppManager~1setAppHasBeenLoggedInStateAtleastOnce()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setAppHasBeenLoggedInStateAtleastOnce"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1AppManager~1showMessage(_:)\/title","value":"showMessage:"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1AppManager~1showMessage(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"showMessage:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1AppManager~1getAlertStyle()\/title","value":"getAlertStyle"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1AppManager~1getAlertStyle()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"getAlertStyle"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1AppManager~1showWelcomeScreen()\/title","value":"showWelcomeScreen"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1AppManager~1showWelcomeScreen()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"showWelcomeScreen"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1AppManager~1changeAppLanguage(_:)\/title","value":"changeAppLanguage:"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1AppManager~1changeAppLanguage(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"changeAppLanguage:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1AppManager~1appHasBeenLoggedInStateAtleastOnce()\/title","value":"appHasBeenLoggedInStateAtleastOnce"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1AppManager~1appHasBeenLoggedInStateAtleastOnce()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"appHasBeenLoggedInStateAtleastOnce"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1AppManager~1setupReachability()\/title","value":"setupReachability"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1AppManager~1setupReachability()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setupReachability"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1AppManager~1reloadWindow()\/title","value":"reloadWindow"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1AppManager~1reloadWindow()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"reloadWindow"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}