{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AppsFlyerManager"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/yababa\/appsflyermanager"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/yababa\/appsflyermanager"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.yababaGmbH.yababa\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.yababaGmbH.yababa\/objc(pl)AppsFlyerLibDelegate","doc:\/\/com.yababaGmbH.yababa\/objc(pl)AppsFlyerDeepLinkDelegate","doc:\/\/com.yababaGmbH.yababa\/objc(pl)NSObject","doc:\/\/com.yababaGmbH.yababa\/12SkeletonView17AssociatedObjectsP","doc:\/\/com.yababaGmbH.yababa\/s7CVarArgP","doc:\/\/com.yababaGmbH.yababa\/s28CustomDebugStringConvertibleP","doc:\/\/com.yababaGmbH.yababa\/s23CustomStringConvertibleP","doc:\/\/com.yababaGmbH.yababa\/SQ","doc:\/\/com.yababaGmbH.yababa\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AppsFlyerManager","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AppsFlyerManager\/afAttributionDate","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AppsFlyerManager\/afAttributionType","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AppsFlyerManager\/afCampaign","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AppsFlyerManager\/afMediaSource","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AppsFlyerManager\/afSource","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AppsFlyerManager\/defaults"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AppsFlyerManager\/didResolveDeepLink(_:)","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AppsFlyerManager\/handleDeepLinkReceived(referralCode:referralValue:)","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AppsFlyerManager\/onConversionDataFail(_:)","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AppsFlyerManager\/onConversionDataSuccess(_:)","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AppsFlyerManager\/start()"]},{"title":"Type Properties","identifiers":["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AppsFlyerManager\/defaultInstance"]}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AppsFlyerManager"}],"title":"AppsFlyerManager","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@Yababa@objc(cs)AppsFlyerManager","modules":[{"name":"Yababa"}],"navigatorTitle":[{"kind":"identifier","text":"AppsFlyerManager"}]},"hierarchy":{"paths":[["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa"]]},"references":{"doc://com.yababaGmbH.yababa/documentation/Yababa/AppsFlyerManager/onConversionDataFail(_:)":{"role":"symbol","title":"onConversionDataFail(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onConversionDataFail"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AppsFlyerManager\/onConversionDataFail(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"onConversionDataFail:"}],"url":"\/documentation\/yababa\/appsflyermanager\/onconversiondatafail(_:)"},"doc://com.yababaGmbH.yababa/documentation/Yababa/AppsFlyerManager/onConversionDataSuccess(_:)":{"role":"symbol","title":"onConversionDataSuccess(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onConversionDataSuccess"},{"kind":"text","text":"(["},{"kind":"typeIdentifier","text":"AnyHashable","preciseIdentifier":"s:s11AnyHashableV"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"])"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AppsFlyerManager\/onConversionDataSuccess(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"onConversionDataSuccess:"}],"url":"\/documentation\/yababa\/appsflyermanager\/onconversiondatasuccess(_:)"},"doc://com.yababaGmbH.yababa/documentation/Yababa/AppsFlyerManager/afAttributionType":{"role":"symbol","title":"afAttributionType","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"afAttributionType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AppsFlyerManager\/afAttributionType","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/appsflyermanager\/afattributiontype"},"doc://com.yababaGmbH.yababa/documentation/Yababa/AppsFlyerManager/handleDeepLinkReceived(referralCode:referralValue:)":{"role":"symbol","title":"handleDeepLinkReceived(referralCode:referralValue:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"handleDeepLinkReceived"},{"kind":"text","text":"("},{"kind":"externalParam","text":"referralCode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"referralValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AppsFlyerManager\/handleDeepLinkReceived(referralCode:referralValue:)","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/appsflyermanager\/handledeeplinkreceived(referralcode:referralvalue:)"},"doc://com.yababaGmbH.yababa/documentation/Yababa/AppsFlyerManager/defaultInstance":{"role":"symbol","title":"defaultInstance","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"defaultInstance"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AppsFlyerManager","preciseIdentifier":"c:@M@Yababa@objc(cs)AppsFlyerManager"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AppsFlyerManager\/defaultInstance","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/appsflyermanager\/defaultinstance"},"doc://com.yababaGmbH.yababa/documentation/Yababa/AppsFlyerManager/defaults":{"role":"symbol","title":"defaults","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"defaults"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UserDefaults","preciseIdentifier":"c:objc(cs)NSUserDefaults"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AppsFlyerManager\/defaults","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/appsflyermanager\/defaults"},"doc://com.yababaGmbH.yababa/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(cs)NSObject"},"doc://com.yababaGmbH.yababa/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.yababaGmbH.yababa\/SH"},"doc://com.yababaGmbH.yababa/documentation/Yababa/AppsFlyerManager/start()":{"role":"symbol","title":"start()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"start"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AppsFlyerManager\/start()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"start"}],"url":"\/documentation\/yababa\/appsflyermanager\/start()"},"doc://com.yababaGmbH.yababa/documentation/Yababa/AppsFlyerManager/afAttributionDate":{"role":"symbol","title":"afAttributionDate","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"afAttributionDate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AppsFlyerManager\/afAttributionDate","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/appsflyermanager\/afattributiondate"},"doc://com.yababaGmbH.yababa/documentation/Yababa/AppsFlyerManager/afCampaign":{"role":"symbol","title":"afCampaign","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"afCampaign"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AppsFlyerManager\/afCampaign","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/appsflyermanager\/afcampaign"},"doc://com.yababaGmbH.yababa/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.yababaGmbH.yababa\/s28CustomDebugStringConvertibleP"},"doc://com.yababaGmbH.yababa/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.yababaGmbH.yababa\/SQ"},"doc://com.yababaGmbH.yababa/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.yababaGmbH.yababa\/s7CVarArgP"},"doc://com.yababaGmbH.yababa/documentation/Yababa/AppsFlyerManager/afMediaSource":{"role":"symbol","title":"afMediaSource","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"afMediaSource"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AppsFlyerManager\/afMediaSource","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/appsflyermanager\/afmediasource"},"doc://com.yababaGmbH.yababa/documentation/Yababa/AppsFlyerManager":{"role":"symbol","title":"AppsFlyerManager","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AppsFlyerManager"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AppsFlyerManager","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AppsFlyerManager"}],"url":"\/documentation\/yababa\/appsflyermanager"},"doc://com.yababaGmbH.yababa/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)NSObject"},"doc://com.yababaGmbH.yababa/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.yababaGmbH.yababa\/s23CustomStringConvertibleP"},"doc://com.yababaGmbH.yababa/objc(pl)AppsFlyerLibDelegate":{"type":"unresolvable","title":"AppsFlyerLibDelegate","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)AppsFlyerLibDelegate"},"doc://com.yababaGmbH.yababa/documentation/Yababa/AppsFlyerManager/didResolveDeepLink(_:)":{"role":"symbol","title":"didResolveDeepLink(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"didResolveDeepLink"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"DeepLinkResult","preciseIdentifier":"c:objc(cs)AppsFlyerDeepLinkResult"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AppsFlyerManager\/didResolveDeepLink(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"didResolveDeepLink:"}],"url":"\/documentation\/yababa\/appsflyermanager\/didresolvedeeplink(_:)"},"doc://com.yababaGmbH.yababa/documentation/Yababa":{"role":"collection","title":"Yababa","abstract":[{"type":"text","text":"Getting Started"}],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa","kind":"symbol","type":"topic","url":"\/documentation\/yababa"},"doc://com.yababaGmbH.yababa/objc(pl)AppsFlyerDeepLinkDelegate":{"type":"unresolvable","title":"AppsFlyerDeepLinkDelegate","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)AppsFlyerDeepLinkDelegate"},"doc://com.yababaGmbH.yababa/12SkeletonView17AssociatedObjectsP":{"type":"unresolvable","title":"SkeletonView.AssociatedObjects","identifier":"doc:\/\/com.yababaGmbH.yababa\/12SkeletonView17AssociatedObjectsP"},"doc://com.yababaGmbH.yababa/documentation/Yababa/AppsFlyerManager/afSource":{"role":"symbol","title":"afSource","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"afSource"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AppsFlyerManager\/afSource","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/appsflyermanager\/afsource"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"AppsFlyerManager"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AppsFlyerManager"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"AppsFlyerManager"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AppsFlyerManager\/didResolveDeepLink(_:)","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AppsFlyerManager\/onConversionDataFail(_:)","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AppsFlyerManager\/onConversionDataSuccess(_:)","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AppsFlyerManager\/start()"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.yababaGmbH.yababa\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.yababaGmbH.yababa\/objc(pl)AppsFlyerDeepLinkDelegate","doc:\/\/com.yababaGmbH.yababa\/objc(pl)AppsFlyerLibDelegate"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"AppsFlyerManager"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1AppsFlyerManager~1onConversionDataFail(_:)\/title","value":"onConversionDataFail:"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1AppsFlyerManager~1onConversionDataFail(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onConversionDataFail:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1AppsFlyerManager~1onConversionDataSuccess(_:)\/title","value":"onConversionDataSuccess:"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1AppsFlyerManager~1onConversionDataSuccess(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onConversionDataSuccess:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1AppsFlyerManager~1start()\/title","value":"start"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1AppsFlyerManager~1start()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"start"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1AppsFlyerManager\/title","value":"AppsFlyerManager"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1AppsFlyerManager\/fragments","value":[{"kind":"identifier","text":"AppsFlyerManager"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1AppsFlyerManager~1didResolveDeepLink(_:)\/title","value":"didResolveDeepLink:"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1AppsFlyerManager~1didResolveDeepLink(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"didResolveDeepLink:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}