{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CardSelectionController"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/yababa\/cardselectioncontroller"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/yababa\/cardselectioncontroller"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/FragmentDrawerViewController"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CardSelectionInteractorProtocol","doc:\/\/com.yababaGmbH.yababa\/objc(pl)NSCoding","doc:\/\/com.yababaGmbH.yababa\/objc(pl)NSExtensionRequestHandling","doc:\/\/com.yababaGmbH.yababa\/objc(pl)NSObject","doc:\/\/com.yababaGmbH.yababa\/12SkeletonView17AssociatedObjectsP","doc:\/\/com.yababaGmbH.yababa\/s7CVarArgP","doc:\/\/com.yababaGmbH.yababa\/s28CustomDebugStringConvertibleP","doc:\/\/com.yababaGmbH.yababa\/s23CustomStringConvertibleP","doc:\/\/com.yababaGmbH.yababa\/SQ","doc:\/\/com.yababaGmbH.yababa\/SH","doc:\/\/com.yababaGmbH.yababa\/s8SendableP","doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIActivityItemsConfigurationProviding","doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIAppearanceContainer","doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIContentContainer","doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIFocusEnvironment","doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIPasteConfigurationSupporting","doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIResponderStandardEditActions","doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIStateRestoring","doc:\/\/com.yababaGmbH.yababa\/objc(pl)UITraitEnvironment","doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIUserActivityRestoring"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CardSelectionController","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CardSelectionController\/changePayModeButton","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CardSelectionController\/delegate","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CardSelectionController\/errorMessageLabel","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CardSelectionController\/newPaymentOptions","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CardSelectionController\/otherPaymentMethodCards","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CardSelectionController\/parentStackView","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CardSelectionController\/payButton","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CardSelectionController\/paymentControlStackView","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CardSelectionController\/paymentOptionsTableView","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CardSelectionController\/previousSavedCreditCards","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CardSelectionController\/screenTitle","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CardSelectionController\/selectedCard","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CardSelectionController\/selectedCardExpirationLabelView","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CardSelectionController\/selectedCardIcon","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CardSelectionController\/selectedCardNumberLabelView","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CardSelectionController\/tableViewHeightConstraint"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CardSelectionController\/changePaymentMethodAction(_:)","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CardSelectionController\/hidePayButtonAndShowPaymentOptions()","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CardSelectionController\/onBack()","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CardSelectionController\/onPayAction(_:)","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CardSelectionController\/proceedWithPayment(card:)","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CardSelectionController\/refreshLayout()","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CardSelectionController\/setIdentifiers()","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CardSelectionController\/setSelectedPaymentOptionLayout()","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CardSelectionController\/setupLocalizedStrings()","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CardSelectionController\/setupPaymentsTableView()","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CardSelectionController\/showErrorMessage(_:)","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CardSelectionController\/showPayButtonAndHidePaymentOptions()","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CardSelectionController\/viewDidLoad()"]},{"title":"Default Implementations","identifiers":["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CardSelectionController\/CardSelectionInteractorProtocol-Implementations"],"generated":true}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CardSelectionController"}],"title":"CardSelectionController","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@Yababa@objc(cs)CardSelectionController","modules":[{"name":"Yababa"}],"navigatorTitle":[{"kind":"identifier","text":"CardSelectionController"}]},"hierarchy":{"paths":[["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa"]]},"references":{"doc://com.yababaGmbH.yababa/documentation/Yababa/CardSelectionController/showPayButtonAndHidePaymentOptions()":{"role":"symbol","title":"showPayButtonAndHidePaymentOptions()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"showPayButtonAndHidePaymentOptions"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CardSelectionController\/showPayButtonAndHidePaymentOptions()","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/cardselectioncontroller\/showpaybuttonandhidepaymentoptions()"},"doc://com.yababaGmbH.yababa/documentation/Yababa/CardSelectionController/changePaymentMethodAction(_:)":{"role":"symbol","title":"changePaymentMethodAction(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"changePaymentMethodAction"},{"kind":"text","text":"("},{"kind":"keyword","text":"Any"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CardSelectionController\/changePaymentMethodAction(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"changePaymentMethodAction:"}],"url":"\/documentation\/yababa\/cardselectioncontroller\/changepaymentmethodaction(_:)"},"doc://com.yababaGmbH.yababa/documentation/Yababa/CardSelectionController/errorMessageLabel":{"role":"symbol","title":"errorMessageLabel","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"errorMessageLabel"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UILabel","preciseIdentifier":"c:objc(cs)UILabel"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CardSelectionController\/errorMessageLabel","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"errorMessageLabel"}],"url":"\/documentation\/yababa\/cardselectioncontroller\/errormessagelabel"},"doc://com.yababaGmbH.yababa/documentation/Yababa":{"role":"collection","title":"Yababa","abstract":[{"type":"text","text":"Getting Started"}],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa","kind":"symbol","type":"topic","url":"\/documentation\/yababa"},"doc://com.yababaGmbH.yababa/objc(pl)UIUserActivityRestoring":{"type":"unresolvable","title":"UIKit.UIUserActivityRestoring","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIUserActivityRestoring"},"doc://com.yababaGmbH.yababa/documentation/Yababa/CardSelectionController/initWithCoder:":{"role":"symbol","title":"initWithCoder:","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithCoder:"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CardSelectionController\/initWithCoder:","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithCoder:"}],"url":"\/documentation\/yababa\/cardselectioncontroller\/initwithcoder:"},"doc://com.yababaGmbH.yababa/documentation/Yababa/CardSelectionController/selectedCardNumberLabelView":{"role":"symbol","title":"selectedCardNumberLabelView","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"selectedCardNumberLabelView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UILabel","preciseIdentifier":"c:objc(cs)UILabel"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CardSelectionController\/selectedCardNumberLabelView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"selectedCardNumberLabelView"}],"url":"\/documentation\/yababa\/cardselectioncontroller\/selectedcardnumberlabelview"},"doc://com.yababaGmbH.yababa/documentation/Yababa/CardSelectionController/CardSelectionInteractorProtocol-Implementations":{"role":"collectionGroup","title":"CardSelectionInteractorProtocol Implementations","abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CardSelectionController\/CardSelectionInteractorProtocol-Implementations","kind":"article","type":"topic","url":"\/documentation\/yababa\/cardselectioncontroller\/cardselectioninteractorprotocol-implementations"},"doc://com.yababaGmbH.yababa/documentation/Yababa/CardSelectionController/setSelectedPaymentOptionLayout()":{"role":"symbol","title":"setSelectedPaymentOptionLayout()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setSelectedPaymentOptionLayout"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CardSelectionController\/setSelectedPaymentOptionLayout()","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/cardselectioncontroller\/setselectedpaymentoptionlayout()"},"doc://com.yababaGmbH.yababa/objc(pl)UIAppearanceContainer":{"type":"unresolvable","title":"UIKit.UIAppearanceContainer","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIAppearanceContainer"},"doc://com.yababaGmbH.yababa/documentation/Yababa/CardSelectionController/changePayModeButton":{"role":"symbol","title":"changePayModeButton","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"changePayModeButton"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIButton","preciseIdentifier":"c:objc(cs)UIButton"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CardSelectionController\/changePayModeButton","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"changePayModeButton"}],"url":"\/documentation\/yababa\/cardselectioncontroller\/changepaymodebutton"},"doc://com.yababaGmbH.yababa/documentation/Yababa/CardSelectionController/setupLocalizedStrings()":{"role":"symbol","title":"setupLocalizedStrings()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setupLocalizedStrings"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CardSelectionController\/setupLocalizedStrings()","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/cardselectioncontroller\/setuplocalizedstrings()"},"doc://com.yababaGmbH.yababa/documentation/Yababa/CardSelectionController/otherPaymentMethodCards":{"role":"symbol","title":"otherPaymentMethodCards","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"otherPaymentMethodCards"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"CreditCard","preciseIdentifier":"s:6Yababa10CreditCardC"},{"kind":"text","text":"]?"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CardSelectionController\/otherPaymentMethodCards","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/cardselectioncontroller\/otherpaymentmethodcards"},"doc://com.yababaGmbH.yababa/documentation/Yababa/CardSelectionController/delegate":{"role":"symbol","title":"delegate","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"delegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CardSelectionDelegate","preciseIdentifier":"s:6Yababa21CardSelectionDelegateP"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CardSelectionController\/delegate","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/cardselectioncontroller\/delegate"},"doc://com.yababaGmbH.yababa/documentation/Yababa/CardSelectionController/proceedWithPayment(card:)":{"role":"symbol","title":"proceedWithPayment(card:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"proceedWithPayment"},{"kind":"text","text":"("},{"kind":"externalParam","text":"card"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CreditCard","preciseIdentifier":"s:6Yababa10CreditCardC"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CardSelectionController\/proceedWithPayment(card:)","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/cardselectioncontroller\/proceedwithpayment(card:)"},"doc://com.yababaGmbH.yababa/documentation/Yababa/CardSelectionController/previousSavedCreditCards":{"role":"symbol","title":"previousSavedCreditCards","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"previousSavedCreditCards"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"CreditCard","preciseIdentifier":"s:6Yababa10CreditCardC"},{"kind":"text","text":"]?"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CardSelectionController\/previousSavedCreditCards","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/cardselectioncontroller\/previoussavedcreditcards"},"doc://com.yababaGmbH.yababa/objc(pl)UIFocusEnvironment":{"type":"unresolvable","title":"UIKit.UIFocusEnvironment","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIFocusEnvironment"},"doc://com.yababaGmbH.yababa/documentation/Yababa/CardSelectionController/newPaymentOptions":{"role":"symbol","title":"newPaymentOptions","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"newPaymentOptions"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"CreditCard","preciseIdentifier":"s:6Yababa10CreditCardC"},{"kind":"text","text":"]?"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CardSelectionController\/newPaymentOptions","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/cardselectioncontroller\/newpaymentoptions"},"doc://com.yababaGmbH.yababa/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.yababaGmbH.yababa\/SH"},"doc://com.yababaGmbH.yababa/documentation/Yababa/CardSelectionController/initWithNibName:bundle:":{"role":"symbol","title":"initWithNibName:bundle:","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithNibName:bundle:"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CardSelectionController\/initWithNibName:bundle:","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithNibName:bundle:"}],"url":"\/documentation\/yababa\/cardselectioncontroller\/initwithnibname:bundle:"},"doc://com.yababaGmbH.yababa/documentation/Yababa/CardSelectionController/parentStackView":{"role":"symbol","title":"parentStackView","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"parentStackView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIStackView","preciseIdentifier":"c:objc(cs)UIStackView"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CardSelectionController\/parentStackView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"parentStackView"}],"url":"\/documentation\/yababa\/cardselectioncontroller\/parentstackview"},"doc://com.yababaGmbH.yababa/objc(pl)UIContentContainer":{"type":"unresolvable","title":"UIKit.UIContentContainer","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIContentContainer"},"doc://com.yababaGmbH.yababa/documentation/Yababa/CardSelectionController/paymentOptionsTableView":{"role":"symbol","title":"paymentOptionsTableView","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"paymentOptionsTableView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UITableView","preciseIdentifier":"c:objc(cs)UITableView"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CardSelectionController\/paymentOptionsTableView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"paymentOptionsTableView"}],"url":"\/documentation\/yababa\/cardselectioncontroller\/paymentoptionstableview"},"doc://com.yababaGmbH.yababa/documentation/Yababa/FragmentDrawerViewController":{"role":"symbol","title":"FragmentDrawerViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FragmentDrawerViewController"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/FragmentDrawerViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FragmentDrawerViewController"}],"url":"\/documentation\/yababa\/fragmentdrawerviewcontroller"},"doc://com.yababaGmbH.yababa/documentation/Yababa/CardSelectionController":{"role":"symbol","title":"CardSelectionController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CardSelectionController"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CardSelectionController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CardSelectionController"}],"url":"\/documentation\/yababa\/cardselectioncontroller"},"doc://com.yababaGmbH.yababa/documentation/Yababa/CardSelectionController/onPayAction(_:)":{"role":"symbol","title":"onPayAction(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onPayAction"},{"kind":"text","text":"("},{"kind":"keyword","text":"Any"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CardSelectionController\/onPayAction(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"onPayAction:"}],"url":"\/documentation\/yababa\/cardselectioncontroller\/onpayaction(_:)"},"doc://com.yababaGmbH.yababa/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.yababaGmbH.yababa\/s23CustomStringConvertibleP"},"doc://com.yababaGmbH.yababa/documentation/Yababa/CardSelectionController/showErrorMessage(_:)":{"role":"symbol","title":"showErrorMessage(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"showErrorMessage"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CardSelectionController\/showErrorMessage(_:)","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/cardselectioncontroller\/showerrormessage(_:)"},"doc://com.yababaGmbH.yababa/documentation/Yababa/CardSelectionController/viewDidLoad()":{"role":"symbol","title":"viewDidLoad()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"viewDidLoad"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CardSelectionController\/viewDidLoad()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"viewDidLoad"}],"url":"\/documentation\/yababa\/cardselectioncontroller\/viewdidload()"},"doc://com.yababaGmbH.yababa/objc(pl)UIActivityItemsConfigurationProviding":{"type":"unresolvable","title":"UIKit.UIActivityItemsConfigurationProviding","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIActivityItemsConfigurationProviding"},"doc://com.yababaGmbH.yababa/documentation/Yababa/CardSelectionController/setIdentifiers()":{"role":"symbol","title":"setIdentifiers()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setIdentifiers"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CardSelectionController\/setIdentifiers()","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/cardselectioncontroller\/setidentifiers()"},"doc://com.yababaGmbH.yababa/documentation/Yababa/CardSelectionController/tableViewHeightConstraint":{"role":"symbol","title":"tableViewHeightConstraint","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"tableViewHeightConstraint"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSLayoutConstraint","preciseIdentifier":"c:objc(cs)NSLayoutConstraint"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CardSelectionController\/tableViewHeightConstraint","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"tableViewHeightConstraint"}],"url":"\/documentation\/yababa\/cardselectioncontroller\/tableviewheightconstraint"},"doc://com.yababaGmbH.yababa/documentation/Yababa/CardSelectionController/onBack()":{"role":"symbol","title":"onBack()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onBack"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CardSelectionController\/onBack()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"onBack"}],"url":"\/documentation\/yababa\/cardselectioncontroller\/onback()"},"doc://com.yababaGmbH.yababa/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.yababaGmbH.yababa\/SQ"},"doc://com.yababaGmbH.yababa/objc(pl)UIStateRestoring":{"type":"unresolvable","title":"UIKit.UIStateRestoring","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIStateRestoring"},"doc://com.yababaGmbH.yababa/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.yababaGmbH.yababa\/s28CustomDebugStringConvertibleP"},"doc://com.yababaGmbH.yababa/objc(pl)NSCoding":{"type":"unresolvable","title":"Foundation.NSCoding","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)NSCoding"},"doc://com.yababaGmbH.yababa/documentation/Yababa/CardSelectionInteractorProtocol":{"role":"symbol","title":"CardSelectionInteractorProtocol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"CardSelectionInteractorProtocol"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CardSelectionInteractorProtocol","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CardSelectionInteractorProtocol"}],"url":"\/documentation\/yababa\/cardselectioninteractorprotocol"},"doc://com.yababaGmbH.yababa/documentation/Yababa/CardSelectionController/selectedCardIcon":{"role":"symbol","title":"selectedCardIcon","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"selectedCardIcon"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIImageView","preciseIdentifier":"c:objc(cs)UIImageView"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CardSelectionController\/selectedCardIcon","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"selectedCardIcon"}],"url":"\/documentation\/yababa\/cardselectioncontroller\/selectedcardicon"},"doc://com.yababaGmbH.yababa/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/com.yababaGmbH.yababa\/s8SendableP"},"doc://com.yababaGmbH.yababa/documentation/Yababa/CardSelectionController/setupPaymentsTableView()":{"role":"symbol","title":"setupPaymentsTableView()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setupPaymentsTableView"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CardSelectionController\/setupPaymentsTableView()","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/cardselectioncontroller\/setuppaymentstableview()"},"doc://com.yababaGmbH.yababa/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.yababaGmbH.yababa\/s7CVarArgP"},"doc://com.yababaGmbH.yababa/12SkeletonView17AssociatedObjectsP":{"type":"unresolvable","title":"SkeletonView.AssociatedObjects","identifier":"doc:\/\/com.yababaGmbH.yababa\/12SkeletonView17AssociatedObjectsP"},"doc://com.yababaGmbH.yababa/objc(pl)UIPasteConfigurationSupporting":{"type":"unresolvable","title":"UIKit.UIPasteConfigurationSupporting","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIPasteConfigurationSupporting"},"doc://com.yababaGmbH.yababa/objc(pl)UITraitEnvironment":{"type":"unresolvable","title":"UIKit.UITraitEnvironment","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)UITraitEnvironment"},"doc://com.yababaGmbH.yababa/documentation/Yababa/CardSelectionController/hidePayButtonAndShowPaymentOptions()":{"role":"symbol","title":"hidePayButtonAndShowPaymentOptions()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"hidePayButtonAndShowPaymentOptions"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CardSelectionController\/hidePayButtonAndShowPaymentOptions()","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/cardselectioncontroller\/hidepaybuttonandshowpaymentoptions()"},"doc://com.yababaGmbH.yababa/documentation/Yababa/CardSelectionController/paymentControlStackView":{"role":"symbol","title":"paymentControlStackView","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"paymentControlStackView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIStackView","preciseIdentifier":"c:objc(cs)UIStackView"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CardSelectionController\/paymentControlStackView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"paymentControlStackView"}],"url":"\/documentation\/yababa\/cardselectioncontroller\/paymentcontrolstackview"},"doc://com.yababaGmbH.yababa/documentation/Yababa/CardSelectionController/selectedCard":{"role":"symbol","title":"selectedCard","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"selectedCard"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CreditCard","preciseIdentifier":"s:6Yababa10CreditCardC"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CardSelectionController\/selectedCard","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/cardselectioncontroller\/selectedcard"},"doc://com.yababaGmbH.yababa/documentation/Yababa/CardSelectionController/selectedCardExpirationLabelView":{"role":"symbol","title":"selectedCardExpirationLabelView","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"selectedCardExpirationLabelView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UILabel","preciseIdentifier":"c:objc(cs)UILabel"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CardSelectionController\/selectedCardExpirationLabelView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"selectedCardExpirationLabelView"}],"url":"\/documentation\/yababa\/cardselectioncontroller\/selectedcardexpirationlabelview"},"doc://com.yababaGmbH.yababa/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)NSObject"},"doc://com.yababaGmbH.yababa/documentation/Yababa/CardSelectionController/payButton":{"role":"symbol","title":"payButton","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"payButton"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIButton","preciseIdentifier":"c:objc(cs)UIButton"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CardSelectionController\/payButton","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"payButton"}],"url":"\/documentation\/yababa\/cardselectioncontroller\/paybutton"},"doc://com.yababaGmbH.yababa/documentation/Yababa/CardSelectionController/refreshLayout()":{"role":"symbol","title":"refreshLayout()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"refreshLayout"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CardSelectionController\/refreshLayout()","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/cardselectioncontroller\/refreshlayout()"},"doc://com.yababaGmbH.yababa/objc(pl)NSExtensionRequestHandling":{"type":"unresolvable","title":"Foundation.NSExtensionRequestHandling","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)NSExtensionRequestHandling"},"doc://com.yababaGmbH.yababa/objc(pl)UIResponderStandardEditActions":{"type":"unresolvable","title":"UIKit.UIResponderStandardEditActions","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIResponderStandardEditActions"},"doc://com.yababaGmbH.yababa/documentation/Yababa/CardSelectionController/screenTitle":{"role":"symbol","title":"screenTitle","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"screenTitle"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CardSelectionController\/screenTitle","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/cardselectioncontroller\/screentitle"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"CardSelectionController"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"CardSelectionController"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"CardSelectionController"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CardSelectionController\/changePayModeButton","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CardSelectionController\/errorMessageLabel","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CardSelectionController\/parentStackView","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CardSelectionController\/payButton","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CardSelectionController\/paymentControlStackView","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CardSelectionController\/paymentOptionsTableView","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CardSelectionController\/selectedCardExpirationLabelView","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CardSelectionController\/selectedCardIcon","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CardSelectionController\/selectedCardNumberLabelView","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CardSelectionController\/tableViewHeightConstraint"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CardSelectionController\/changePaymentMethodAction(_:)","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CardSelectionController\/initWithCoder:","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CardSelectionController\/initWithNibName:bundle:","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CardSelectionController\/onBack()","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CardSelectionController\/onPayAction(_:)","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CardSelectionController\/viewDidLoad()"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/FragmentDrawerViewController"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"CardSelectionController"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/FragmentDrawerViewController","preciseIdentifier":"c:@M@Yababa@objc(cs)FragmentDrawerViewController","text":"FragmentDrawerViewController"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1CardSelectionController~1changePaymentMethodAction(_:)\/title","value":"changePaymentMethodAction:"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1CardSelectionController~1changePaymentMethodAction(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"changePaymentMethodAction:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1CardSelectionController~1errorMessageLabel\/title","value":"errorMessageLabel"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1CardSelectionController~1errorMessageLabel\/fragments","value":[{"kind":"identifier","text":"errorMessageLabel"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1CardSelectionController~1selectedCardNumberLabelView\/title","value":"selectedCardNumberLabelView"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1CardSelectionController~1selectedCardNumberLabelView\/fragments","value":[{"kind":"identifier","text":"selectedCardNumberLabelView"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1CardSelectionController~1changePayModeButton\/title","value":"changePayModeButton"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1CardSelectionController~1changePayModeButton\/fragments","value":[{"kind":"identifier","text":"changePayModeButton"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1CardSelectionController~1parentStackView\/title","value":"parentStackView"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1CardSelectionController~1parentStackView\/fragments","value":[{"kind":"identifier","text":"parentStackView"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1CardSelectionController~1paymentOptionsTableView\/title","value":"paymentOptionsTableView"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1CardSelectionController~1paymentOptionsTableView\/fragments","value":[{"kind":"identifier","text":"paymentOptionsTableView"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1FragmentDrawerViewController\/title","value":"FragmentDrawerViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1FragmentDrawerViewController\/fragments","value":[{"kind":"identifier","text":"FragmentDrawerViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1CardSelectionController\/title","value":"CardSelectionController"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1CardSelectionController\/fragments","value":[{"kind":"identifier","text":"CardSelectionController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1CardSelectionController~1onPayAction(_:)\/title","value":"onPayAction:"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1CardSelectionController~1onPayAction(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onPayAction:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1CardSelectionController~1viewDidLoad()\/title","value":"viewDidLoad"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1CardSelectionController~1viewDidLoad()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"viewDidLoad"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1CardSelectionController~1tableViewHeightConstraint\/title","value":"tableViewHeightConstraint"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1CardSelectionController~1tableViewHeightConstraint\/fragments","value":[{"kind":"identifier","text":"tableViewHeightConstraint"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1CardSelectionController~1onBack()\/title","value":"onBack"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1CardSelectionController~1onBack()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onBack"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1CardSelectionController~1selectedCardIcon\/title","value":"selectedCardIcon"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1CardSelectionController~1selectedCardIcon\/fragments","value":[{"kind":"identifier","text":"selectedCardIcon"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1CardSelectionController~1paymentControlStackView\/title","value":"paymentControlStackView"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1CardSelectionController~1paymentControlStackView\/fragments","value":[{"kind":"identifier","text":"paymentControlStackView"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1CardSelectionController~1selectedCardExpirationLabelView\/title","value":"selectedCardExpirationLabelView"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1CardSelectionController~1selectedCardExpirationLabelView\/fragments","value":[{"kind":"identifier","text":"selectedCardExpirationLabelView"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1CardSelectionController~1payButton\/title","value":"payButton"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1CardSelectionController~1payButton\/fragments","value":[{"kind":"identifier","text":"payButton"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}