{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CatalogueViewController"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/yababa\/catalogueviewcontroller"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/yababa\/catalogueviewcontroller"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.yababaGmbH.yababa\/@M@XLPagerTabStrip@objc(cs)ButtonBarPagerTabStripViewController"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.yababaGmbH.yababa\/objc(pl)NSCoding","doc:\/\/com.yababaGmbH.yababa\/objc(pl)NSExtensionRequestHandling","doc:\/\/com.yababaGmbH.yababa\/objc(pl)NSObject","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ShoppingCartObserver","doc:\/\/com.yababaGmbH.yababa\/12SkeletonView17AssociatedObjectsP","doc:\/\/com.yababaGmbH.yababa\/s7CVarArgP","doc:\/\/com.yababaGmbH.yababa\/s28CustomDebugStringConvertibleP","doc:\/\/com.yababaGmbH.yababa\/s23CustomStringConvertibleP","doc:\/\/com.yababaGmbH.yababa\/SQ","doc:\/\/com.yababaGmbH.yababa\/SH","doc:\/\/com.yababaGmbH.yababa\/s8SendableP","doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIActivityItemsConfigurationProviding","doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIAppearanceContainer","doc:\/\/com.yababaGmbH.yababa\/objc(pl)UICollectionViewDataSource","doc:\/\/com.yababaGmbH.yababa\/objc(pl)UICollectionViewDelegate","doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIContentContainer","doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIFocusEnvironment","doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIPasteConfigurationSupporting","doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIResponderStandardEditActions","doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIScrollViewDelegate","doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIStateRestoring","doc:\/\/com.yababaGmbH.yababa\/objc(pl)UITraitEnvironment","doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIUserActivityRestoring","doc:\/\/com.yababaGmbH.yababa\/15XLPagerTabStrip05PagerbC10DataSourceP","doc:\/\/com.yababaGmbH.yababa\/15XLPagerTabStrip05PagerbC8DelegateP","doc:\/\/com.yababaGmbH.yababa\/15XLPagerTabStrip05PagerbC21IsProgressiveDelegateP"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CatalogueViewController","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CatalogueViewController\/categoryAndProductsViews","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CatalogueViewController\/interactor","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CatalogueViewController\/mainStackView","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CatalogueViewController\/origin","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CatalogueViewController\/router","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CatalogueViewController\/searchBar","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CatalogueViewController\/searchBarContainer"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CatalogueViewController\/dealloc()","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CatalogueViewController\/onBack()","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CatalogueViewController\/onSearch()","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CatalogueViewController\/populateCategoryAndProductsViews()","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CatalogueViewController\/refreshAndMoveToSelectedCategoryId()","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CatalogueViewController\/viewControllers(for:)","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CatalogueViewController\/viewDidAppear(_:)","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CatalogueViewController\/viewDidLoad()","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CatalogueViewController\/viewWillAppear(_:)"]},{"title":"Default Implementations","identifiers":["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CatalogueViewController\/ShoppingCartObserver-Implementations"],"generated":true}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CatalogueViewController"}],"title":"CatalogueViewController","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@Yababa@objc(cs)CatalogueViewController","modules":[{"name":"Yababa"}],"navigatorTitle":[{"kind":"identifier","text":"CatalogueViewController"}]},"hierarchy":{"paths":[["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa"]]},"references":{"doc://com.yababaGmbH.yababa/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.yababaGmbH.yababa\/s7CVarArgP"},"doc://com.yababaGmbH.yababa/objc(pl)UICollectionViewDataSource":{"type":"unresolvable","title":"UIKit.UICollectionViewDataSource","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)UICollectionViewDataSource"},"doc://com.yababaGmbH.yababa/documentation/Yababa/CatalogueViewController/viewControllers(for:)":{"role":"symbol","title":"viewControllers(for:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"viewControllers"},{"kind":"text","text":"("},{"kind":"externalParam","text":"for"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"PagerTabStripViewController","preciseIdentifier":"c:@M@XLPagerTabStrip@objc(cs)PagerTabStripViewController"},{"kind":"text","text":") -> ["},{"kind":"typeIdentifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"},{"kind":"text","text":"]"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CatalogueViewController\/viewControllers(for:)","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/catalogueviewcontroller\/viewcontrollers(for:)"},"doc://com.yababaGmbH.yababa/documentation/Yababa/CatalogueViewController/interactor":{"role":"symbol","title":"interactor","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"interactor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ViewControllerToInteractorCatalogueProtocol","preciseIdentifier":"s:6Yababa43ViewControllerToInteractorCatalogueProtocolP"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CatalogueViewController\/interactor","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/catalogueviewcontroller\/interactor"},"doc://com.yababaGmbH.yababa/documentation/Yababa/CatalogueViewController/initWithCoder:":{"role":"symbol","title":"initWithCoder:","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithCoder:"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CatalogueViewController\/initWithCoder:","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithCoder:"}],"url":"\/documentation\/yababa\/catalogueviewcontroller\/initwithcoder:"},"doc://com.yababaGmbH.yababa/objc(pl)UIPasteConfigurationSupporting":{"type":"unresolvable","title":"UIKit.UIPasteConfigurationSupporting","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIPasteConfigurationSupporting"},"doc://com.yababaGmbH.yababa/15XLPagerTabStrip05PagerbC21IsProgressiveDelegateP":{"type":"unresolvable","title":"XLPagerTabStrip.PagerTabStripIsProgressiveDelegate","identifier":"doc:\/\/com.yababaGmbH.yababa\/15XLPagerTabStrip05PagerbC21IsProgressiveDelegateP"},"doc://com.yababaGmbH.yababa/objc(pl)UIAppearanceContainer":{"type":"unresolvable","title":"UIKit.UIAppearanceContainer","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIAppearanceContainer"},"doc://com.yababaGmbH.yababa/documentation/Yababa/CatalogueViewController/initWithNibName:bundle:":{"role":"symbol","title":"initWithNibName:bundle:","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithNibName:bundle:"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CatalogueViewController\/initWithNibName:bundle:","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithNibName:bundle:"}],"url":"\/documentation\/yababa\/catalogueviewcontroller\/initwithnibname:bundle:"},"doc://com.yababaGmbH.yababa/15XLPagerTabStrip05PagerbC10DataSourceP":{"type":"unresolvable","title":"XLPagerTabStrip.PagerTabStripDataSource","identifier":"doc:\/\/com.yababaGmbH.yababa\/15XLPagerTabStrip05PagerbC10DataSourceP"},"doc://com.yababaGmbH.yababa/objc(pl)NSExtensionRequestHandling":{"type":"unresolvable","title":"Foundation.NSExtensionRequestHandling","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)NSExtensionRequestHandling"},"doc://com.yababaGmbH.yababa/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)NSObject"},"doc://com.yababaGmbH.yababa/objc(pl)UIFocusEnvironment":{"type":"unresolvable","title":"UIKit.UIFocusEnvironment","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIFocusEnvironment"},"doc://com.yababaGmbH.yababa/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.yababaGmbH.yababa\/SH"},"doc://com.yababaGmbH.yababa/documentation/Yababa/CatalogueViewController/viewDidLoad()":{"role":"symbol","title":"viewDidLoad()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"viewDidLoad"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CatalogueViewController\/viewDidLoad()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"viewDidLoad"}],"url":"\/documentation\/yababa\/catalogueviewcontroller\/viewdidload()"},"doc://com.yababaGmbH.yababa/documentation/Yababa/ShoppingCartObserver":{"role":"symbol","title":"ShoppingCartObserver","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"ShoppingCartObserver"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ShoppingCartObserver","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ShoppingCartObserver"}],"url":"\/documentation\/yababa\/shoppingcartobserver"},"doc://com.yababaGmbH.yababa/documentation/Yababa/CatalogueViewController/searchBar":{"role":"symbol","title":"searchBar","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"searchBar"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UISearchBar","preciseIdentifier":"c:objc(cs)UISearchBar"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CatalogueViewController\/searchBar","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"searchBar"}],"url":"\/documentation\/yababa\/catalogueviewcontroller\/searchbar"},"doc://com.yababaGmbH.yababa/objc(pl)UITraitEnvironment":{"type":"unresolvable","title":"UIKit.UITraitEnvironment","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)UITraitEnvironment"},"doc://com.yababaGmbH.yababa/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.yababaGmbH.yababa\/SQ"},"doc://com.yababaGmbH.yababa/documentation/Yababa/CatalogueViewController/viewDidAppear(_:)":{"role":"symbol","title":"viewDidAppear(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"viewDidAppear"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CatalogueViewController\/viewDidAppear(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"viewDidAppear:"}],"url":"\/documentation\/yababa\/catalogueviewcontroller\/viewdidappear(_:)"},"doc://com.yababaGmbH.yababa/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.yababaGmbH.yababa\/s23CustomStringConvertibleP"},"doc://com.yababaGmbH.yababa/objc(pl)UIResponderStandardEditActions":{"type":"unresolvable","title":"UIKit.UIResponderStandardEditActions","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIResponderStandardEditActions"},"doc://com.yababaGmbH.yababa/documentation/Yababa/CatalogueViewController/router":{"role":"symbol","title":"router","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"router"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ViewControllerToRouterCatalogueProtocol","preciseIdentifier":"s:6Yababa39ViewControllerToRouterCatalogueProtocolP"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CatalogueViewController\/router","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/catalogueviewcontroller\/router"},"doc://com.yababaGmbH.yababa/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.yababaGmbH.yababa\/s28CustomDebugStringConvertibleP"},"doc://com.yababaGmbH.yababa/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/com.yababaGmbH.yababa\/s8SendableP"},"doc://com.yababaGmbH.yababa/documentation/Yababa/CatalogueViewController/ShoppingCartObserver-Implementations":{"role":"collectionGroup","title":"ShoppingCartObserver Implementations","abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CatalogueViewController\/ShoppingCartObserver-Implementations","kind":"article","type":"topic","url":"\/documentation\/yababa\/catalogueviewcontroller\/shoppingcartobserver-implementations"},"doc://com.yababaGmbH.yababa/@M@XLPagerTabStrip@objc(cs)ButtonBarPagerTabStripViewController":{"type":"unresolvable","title":"_TtC15XLPagerTabStrip36ButtonBarPagerTabStripViewController","identifier":"doc:\/\/com.yababaGmbH.yababa\/@M@XLPagerTabStrip@objc(cs)ButtonBarPagerTabStripViewController"},"doc://com.yababaGmbH.yababa/objc(pl)UICollectionViewDelegate":{"type":"unresolvable","title":"UIKit.UICollectionViewDelegate","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)UICollectionViewDelegate"},"doc://com.yababaGmbH.yababa/objc(pl)UIContentContainer":{"type":"unresolvable","title":"UIKit.UIContentContainer","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIContentContainer"},"doc://com.yababaGmbH.yababa/documentation/Yababa/CatalogueViewController/viewWillAppear(_:)":{"role":"symbol","title":"viewWillAppear(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"viewWillAppear"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CatalogueViewController\/viewWillAppear(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"viewWillAppear:"}],"url":"\/documentation\/yababa\/catalogueviewcontroller\/viewwillappear(_:)"},"doc://com.yababaGmbH.yababa/documentation/Yababa/CatalogueViewController/origin":{"role":"symbol","title":"origin","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"origin"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TrackingOrigin","preciseIdentifier":"s:6Yababa14TrackingOriginO"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CatalogueViewController\/origin","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/catalogueviewcontroller\/origin"},"doc://com.yababaGmbH.yababa/objc(pl)UIScrollViewDelegate":{"type":"unresolvable","title":"UIKit.UIScrollViewDelegate","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIScrollViewDelegate"},"doc://com.yababaGmbH.yababa/documentation/Yababa/CatalogueViewController/searchBarContainer":{"role":"symbol","title":"searchBarContainer","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"searchBarContainer"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CatalogueViewController\/searchBarContainer","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"searchBarContainer"}],"url":"\/documentation\/yababa\/catalogueviewcontroller\/searchbarcontainer"},"doc://com.yababaGmbH.yababa/documentation/Yababa/CatalogueViewController/onBack()":{"role":"symbol","title":"onBack()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onBack"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CatalogueViewController\/onBack()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"onBack"}],"url":"\/documentation\/yababa\/catalogueviewcontroller\/onback()"},"doc://com.yababaGmbH.yababa/documentation/Yababa/CatalogueViewController/dealloc()":{"role":"symbol","title":"dealloc()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"dealloc"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CatalogueViewController\/dealloc()","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/catalogueviewcontroller\/dealloc()"},"doc://com.yababaGmbH.yababa/documentation/Yababa/CatalogueViewController":{"role":"symbol","title":"CatalogueViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CatalogueViewController"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CatalogueViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CatalogueViewController"}],"url":"\/documentation\/yababa\/catalogueviewcontroller"},"doc://com.yababaGmbH.yababa/documentation/Yababa/CatalogueViewController/populateCategoryAndProductsViews()":{"role":"symbol","title":"populateCategoryAndProductsViews()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"populateCategoryAndProductsViews"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CatalogueViewController\/populateCategoryAndProductsViews()","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/catalogueviewcontroller\/populatecategoryandproductsviews()"},"doc://com.yababaGmbH.yababa/12SkeletonView17AssociatedObjectsP":{"type":"unresolvable","title":"SkeletonView.AssociatedObjects","identifier":"doc:\/\/com.yababaGmbH.yababa\/12SkeletonView17AssociatedObjectsP"},"doc://com.yababaGmbH.yababa/documentation/Yababa/CatalogueViewController/refreshAndMoveToSelectedCategoryId()":{"role":"symbol","title":"refreshAndMoveToSelectedCategoryId()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"refreshAndMoveToSelectedCategoryId"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CatalogueViewController\/refreshAndMoveToSelectedCategoryId()","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/catalogueviewcontroller\/refreshandmovetoselectedcategoryid()"},"doc://com.yababaGmbH.yababa/objc(pl)UIActivityItemsConfigurationProviding":{"type":"unresolvable","title":"UIKit.UIActivityItemsConfigurationProviding","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIActivityItemsConfigurationProviding"},"doc://com.yababaGmbH.yababa/15XLPagerTabStrip05PagerbC8DelegateP":{"type":"unresolvable","title":"XLPagerTabStrip.PagerTabStripDelegate","identifier":"doc:\/\/com.yababaGmbH.yababa\/15XLPagerTabStrip05PagerbC8DelegateP"},"doc://com.yababaGmbH.yababa/documentation/Yababa/CatalogueViewController/onSearch()":{"role":"symbol","title":"onSearch()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onSearch"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CatalogueViewController\/onSearch()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"onSearch"}],"url":"\/documentation\/yababa\/catalogueviewcontroller\/onsearch()"},"doc://com.yababaGmbH.yababa/documentation/Yababa/CatalogueViewController/categoryAndProductsViews":{"role":"symbol","title":"categoryAndProductsViews","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"categoryAndProductsViews"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"CategoryAndProductsViewController","preciseIdentifier":"c:@M@Yababa@objc(cs)CategoryAndProductsViewController"},{"kind":"text","text":"]"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CatalogueViewController\/categoryAndProductsViews","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/catalogueviewcontroller\/categoryandproductsviews"},"doc://com.yababaGmbH.yababa/objc(pl)UIUserActivityRestoring":{"type":"unresolvable","title":"UIKit.UIUserActivityRestoring","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIUserActivityRestoring"},"doc://com.yababaGmbH.yababa/objc(pl)UIStateRestoring":{"type":"unresolvable","title":"UIKit.UIStateRestoring","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIStateRestoring"},"doc://com.yababaGmbH.yababa/objc(pl)NSCoding":{"type":"unresolvable","title":"Foundation.NSCoding","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)NSCoding"},"doc://com.yababaGmbH.yababa/documentation/Yababa":{"role":"collection","title":"Yababa","abstract":[{"type":"text","text":"Getting Started"}],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa","kind":"symbol","type":"topic","url":"\/documentation\/yababa"},"doc://com.yababaGmbH.yababa/documentation/Yababa/CatalogueViewController/mainStackView":{"role":"symbol","title":"mainStackView","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"mainStackView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIStackView","preciseIdentifier":"c:objc(cs)UIStackView"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CatalogueViewController\/mainStackView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"mainStackView"}],"url":"\/documentation\/yababa\/catalogueviewcontroller\/mainstackview"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"CatalogueViewController"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"CatalogueViewController"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"CatalogueViewController"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CatalogueViewController\/mainStackView","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CatalogueViewController\/searchBar","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CatalogueViewController\/searchBarContainer"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CatalogueViewController\/initWithCoder:","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CatalogueViewController\/initWithNibName:bundle:","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CatalogueViewController\/onBack()","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CatalogueViewController\/onSearch()","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CatalogueViewController\/viewDidAppear(_:)","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CatalogueViewController\/viewDidLoad()","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CatalogueViewController\/viewWillAppear(_:)"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.yababaGmbH.yababa\/@M@XLPagerTabStrip@objc(cs)ButtonBarPagerTabStripViewController"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"CatalogueViewController"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"ButtonBarPagerTabStripViewController","preciseIdentifier":"c:@M@XLPagerTabStrip@objc(cs)ButtonBarPagerTabStripViewController"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1CatalogueViewController~1viewDidLoad()\/title","value":"viewDidLoad"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1CatalogueViewController~1viewDidLoad()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"viewDidLoad"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1CatalogueViewController~1searchBar\/title","value":"searchBar"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1CatalogueViewController~1searchBar\/fragments","value":[{"kind":"identifier","text":"searchBar"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1CatalogueViewController~1viewDidAppear(_:)\/title","value":"viewDidAppear:"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1CatalogueViewController~1viewDidAppear(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"viewDidAppear:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1CatalogueViewController~1viewWillAppear(_:)\/title","value":"viewWillAppear:"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1CatalogueViewController~1viewWillAppear(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"viewWillAppear:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1CatalogueViewController~1searchBarContainer\/title","value":"searchBarContainer"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1CatalogueViewController~1searchBarContainer\/fragments","value":[{"kind":"identifier","text":"searchBarContainer"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1CatalogueViewController~1onBack()\/title","value":"onBack"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1CatalogueViewController~1onBack()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onBack"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1CatalogueViewController\/title","value":"CatalogueViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1CatalogueViewController\/fragments","value":[{"kind":"identifier","text":"CatalogueViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1CatalogueViewController~1onSearch()\/title","value":"onSearch"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1CatalogueViewController~1onSearch()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onSearch"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1CatalogueViewController~1mainStackView\/title","value":"mainStackView"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1CatalogueViewController~1mainStackView\/fragments","value":[{"kind":"identifier","text":"mainStackView"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}