{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CheckoutSceneViewController"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/yababa\/checkoutsceneviewcontroller"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/yababa\/checkoutsceneviewcontroller"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/MasterViewController"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AddressManagerOwner","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CheckoutSceneViewControllerProtocol","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/FlowProcessorDelegate","doc:\/\/com.yababaGmbH.yababa\/objc(pl)NSCoding","doc:\/\/com.yababaGmbH.yababa\/objc(pl)NSExtensionRequestHandling","doc:\/\/com.yababaGmbH.yababa\/6Nantes0A13LabelDelegateP","doc:\/\/com.yababaGmbH.yababa\/objc(pl)NSObject","doc:\/\/com.yababaGmbH.yababa\/12SkeletonView17AssociatedObjectsP","doc:\/\/com.yababaGmbH.yababa\/@M@Stripe@objc(pl)STPAuthenticationContext","doc:\/\/com.yababaGmbH.yababa\/s7CVarArgP","doc:\/\/com.yababaGmbH.yababa\/s28CustomDebugStringConvertibleP","doc:\/\/com.yababaGmbH.yababa\/s23CustomStringConvertibleP","doc:\/\/com.yababaGmbH.yababa\/SQ","doc:\/\/com.yababaGmbH.yababa\/SH","doc:\/\/com.yababaGmbH.yababa\/s8SendableP","doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIActivityItemsConfigurationProviding","doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIAppearanceContainer","doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIContentContainer","doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIFocusEnvironment","doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIPasteConfigurationSupporting","doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIResponderStandardEditActions","doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIStateRestoring","doc:\/\/com.yababaGmbH.yababa\/objc(pl)UITraitEnvironment","doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIUserActivityRestoring","doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIViewControllerTransitioningDelegate"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CheckoutSceneViewController","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CheckoutSceneViewController\/addressAdditionalInfoLabel","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CheckoutSceneViewController\/addressLabel","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CheckoutSceneViewController\/addressManagerInteractor","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CheckoutSceneViewController\/addressSelectionManager","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CheckoutSceneViewController\/cardCoverImageView","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CheckoutSceneViewController\/cardIconImageContainer","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CheckoutSceneViewController\/cardInfoSubTitleLabel","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CheckoutSceneViewController\/cardInfoTitleLabel","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CheckoutSceneViewController\/cardInfoView","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CheckoutSceneViewController\/cardView","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CheckoutSceneViewController\/deliveryAddressButton","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CheckoutSceneViewController\/deliveryAddressLabel","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CheckoutSceneViewController\/deliveryFeeTextLabel","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CheckoutSceneViewController\/deliveryFeesLabel","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CheckoutSceneViewController\/deliveryTimeAddressContainer","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CheckoutSceneViewController\/deliveryTimeButton","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CheckoutSceneViewController\/deliveryTimeLabel","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CheckoutSceneViewController\/deliveryTimeTextLabel","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CheckoutSceneViewController\/discountContainerView","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CheckoutSceneViewController\/discountLabel","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CheckoutSceneViewController\/discountTextLabel","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CheckoutSceneViewController\/freeDeliveryFeesLabel","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CheckoutSceneViewController\/freeDeliveryFeesView","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CheckoutSceneViewController\/gatewayFeesLabel","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CheckoutSceneViewController\/interactor","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CheckoutSceneViewController\/orderSummaryLabel","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CheckoutSceneViewController\/paymentMethodLabel","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CheckoutSceneViewController\/placeOrderBtn","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CheckoutSceneViewController\/placeOrderBtnContainer","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CheckoutSceneViewController\/promoDiscountTextLabel","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CheckoutSceneViewController\/promosDiscounContainer","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CheckoutSceneViewController\/promosDiscountValueLabel","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CheckoutSceneViewController\/router","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CheckoutSceneViewController\/serverMessageContainer","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CheckoutSceneViewController\/serverMessageLabel","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CheckoutSceneViewController\/smallSpinner","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CheckoutSceneViewController\/subTotalLabel","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CheckoutSceneViewController\/subTotalTextLabel","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CheckoutSceneViewController\/summaryView","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CheckoutSceneViewController\/totalLabel","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CheckoutSceneViewController\/totalSavingsContainerView","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CheckoutSceneViewController\/totalSavingsTitleLabel","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CheckoutSceneViewController\/totalSavingsValueLabel","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CheckoutSceneViewController\/totalTextLabel","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CheckoutSceneViewController\/userAddressManager","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CheckoutSceneViewController\/vouchersCollectionView","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CheckoutSceneViewController\/yababaTermsLabel"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CheckoutSceneViewController\/hideLoadingOverview()","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CheckoutSceneViewController\/hideSpinner()","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CheckoutSceneViewController\/onAddVoucher()","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CheckoutSceneViewController\/onCardSelection()","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CheckoutSceneViewController\/onDeliveryAddress()","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CheckoutSceneViewController\/onDeliveryTime()","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CheckoutSceneViewController\/onPlaceOrder()","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CheckoutSceneViewController\/prepareCartCheckout()","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CheckoutSceneViewController\/setIdentifiers()","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CheckoutSceneViewController\/showLoadingOverview()","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CheckoutSceneViewController\/showSpinner()","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CheckoutSceneViewController\/userEnteredCoupon()","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CheckoutSceneViewController\/viewDidDisappear(_:)","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CheckoutSceneViewController\/viewDidLoad()","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CheckoutSceneViewController\/viewWillAppear(_:)"]},{"title":"Default Implementations","identifiers":["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CheckoutSceneViewController\/AddressManagerOwner-Implementations","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CheckoutSceneViewController\/CheckoutSceneViewControllerProtocol-Implementations","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CheckoutSceneViewController\/FlowProcessorDelegate-Implementations","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CheckoutSceneViewController\/NantesLabelDelegate-Implementations","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CheckoutSceneViewController\/STPAuthenticationContext-Implementations","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CheckoutSceneViewController\/UIViewControllerTransitioningDelegate-Implementations"],"generated":true}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CheckoutSceneViewController"}],"title":"CheckoutSceneViewController","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@Yababa@objc(cs)CheckoutSceneViewController","modules":[{"name":"Yababa"}],"navigatorTitle":[{"kind":"identifier","text":"CheckoutSceneViewController"}]},"hierarchy":{"paths":[["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa"]]},"references":{"doc://com.yababaGmbH.yababa/documentation/Yababa/CheckoutSceneViewController/subTotalTextLabel":{"role":"symbol","title":"subTotalTextLabel","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"subTotalTextLabel"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UILabel","preciseIdentifier":"c:objc(cs)UILabel"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CheckoutSceneViewController\/subTotalTextLabel","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"subTotalTextLabel"}],"url":"\/documentation\/yababa\/checkoutsceneviewcontroller\/subtotaltextlabel"},"doc://com.yababaGmbH.yababa/documentation/Yababa/CheckoutSceneViewController/deliveryAddressButton":{"role":"symbol","title":"deliveryAddressButton","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"deliveryAddressButton"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIButton","preciseIdentifier":"c:objc(cs)UIButton"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CheckoutSceneViewController\/deliveryAddressButton","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"deliveryAddressButton"}],"url":"\/documentation\/yababa\/checkoutsceneviewcontroller\/deliveryaddressbutton"},"doc://com.yababaGmbH.yababa/6Nantes0A13LabelDelegateP":{"type":"unresolvable","title":"Nantes.NantesLabelDelegate","identifier":"doc:\/\/com.yababaGmbH.yababa\/6Nantes0A13LabelDelegateP"},"doc://com.yababaGmbH.yababa/documentation/Yababa/CheckoutSceneViewController/deliveryTimeTextLabel":{"role":"symbol","title":"deliveryTimeTextLabel","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"deliveryTimeTextLabel"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UILabel","preciseIdentifier":"c:objc(cs)UILabel"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CheckoutSceneViewController\/deliveryTimeTextLabel","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"deliveryTimeTextLabel"}],"url":"\/documentation\/yababa\/checkoutsceneviewcontroller\/deliverytimetextlabel"},"doc://com.yababaGmbH.yababa/objc(pl)UITraitEnvironment":{"type":"unresolvable","title":"UIKit.UITraitEnvironment","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)UITraitEnvironment"},"doc://com.yababaGmbH.yababa/documentation/Yababa/CheckoutSceneViewController/userAddressManager":{"role":"symbol","title":"userAddressManager","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"userAddressManager"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AddressManager","preciseIdentifier":"c:@M@Yababa@objc(cs)AddressManager"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CheckoutSceneViewController\/userAddressManager","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/checkoutsceneviewcontroller\/useraddressmanager"},"doc://com.yababaGmbH.yababa/documentation/Yababa/CheckoutSceneViewController/deliveryAddressLabel":{"role":"symbol","title":"deliveryAddressLabel","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"deliveryAddressLabel"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UILabel","preciseIdentifier":"c:objc(cs)UILabel"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CheckoutSceneViewController\/deliveryAddressLabel","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"deliveryAddressLabel"}],"url":"\/documentation\/yababa\/checkoutsceneviewcontroller\/deliveryaddresslabel"},"doc://com.yababaGmbH.yababa/documentation/Yababa/CheckoutSceneViewController/hideSpinner()":{"role":"symbol","title":"hideSpinner()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"hideSpinner"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CheckoutSceneViewController\/hideSpinner()","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/checkoutsceneviewcontroller\/hidespinner()"},"doc://com.yababaGmbH.yababa/documentation/Yababa/AddressManagerOwner":{"role":"symbol","title":"AddressManagerOwner","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"AddressManagerOwner"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AddressManagerOwner","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AddressManagerOwner"}],"url":"\/documentation\/yababa\/addressmanagerowner"},"doc://com.yababaGmbH.yababa/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.yababaGmbH.yababa\/SH"},"doc://com.yababaGmbH.yababa/documentation/Yababa/CheckoutSceneViewController":{"role":"symbol","title":"CheckoutSceneViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CheckoutSceneViewController"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CheckoutSceneViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CheckoutSceneViewController"}],"url":"\/documentation\/yababa\/checkoutsceneviewcontroller"},"doc://com.yababaGmbH.yababa/documentation/Yababa/CheckoutSceneViewController/totalSavingsContainerView":{"role":"symbol","title":"totalSavingsContainerView","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"totalSavingsContainerView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CheckoutSceneViewController\/totalSavingsContainerView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"totalSavingsContainerView"}],"url":"\/documentation\/yababa\/checkoutsceneviewcontroller\/totalsavingscontainerview"},"doc://com.yababaGmbH.yababa/documentation/Yababa/CheckoutSceneViewController/subTotalLabel":{"role":"symbol","title":"subTotalLabel","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"subTotalLabel"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UILabel","preciseIdentifier":"c:objc(cs)UILabel"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CheckoutSceneViewController\/subTotalLabel","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"subTotalLabel"}],"url":"\/documentation\/yababa\/checkoutsceneviewcontroller\/subtotallabel"},"doc://com.yababaGmbH.yababa/objc(pl)UIResponderStandardEditActions":{"type":"unresolvable","title":"UIKit.UIResponderStandardEditActions","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIResponderStandardEditActions"},"doc://com.yababaGmbH.yababa/documentation/Yababa/FlowProcessorDelegate":{"role":"symbol","title":"FlowProcessorDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"FlowProcessorDelegate"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/FlowProcessorDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FlowProcessorDelegate"}],"url":"\/documentation\/yababa\/flowprocessordelegate"},"doc://com.yababaGmbH.yababa/documentation/Yababa/CheckoutSceneViewController/discountLabel":{"role":"symbol","title":"discountLabel","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"discountLabel"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UILabel","preciseIdentifier":"c:objc(cs)UILabel"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CheckoutSceneViewController\/discountLabel","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"discountLabel"}],"url":"\/documentation\/yababa\/checkoutsceneviewcontroller\/discountlabel"},"doc://com.yababaGmbH.yababa/documentation/Yababa/CheckoutSceneViewController/cardInfoTitleLabel":{"role":"symbol","title":"cardInfoTitleLabel","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"cardInfoTitleLabel"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UILabel","preciseIdentifier":"c:objc(cs)UILabel"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CheckoutSceneViewController\/cardInfoTitleLabel","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"cardInfoTitleLabel"}],"url":"\/documentation\/yababa\/checkoutsceneviewcontroller\/cardinfotitlelabel"},"doc://com.yababaGmbH.yababa/documentation/Yababa/CheckoutSceneViewController/cardInfoSubTitleLabel":{"role":"symbol","title":"cardInfoSubTitleLabel","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"cardInfoSubTitleLabel"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UILabel","preciseIdentifier":"c:objc(cs)UILabel"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CheckoutSceneViewController\/cardInfoSubTitleLabel","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"cardInfoSubTitleLabel"}],"url":"\/documentation\/yababa\/checkoutsceneviewcontroller\/cardinfosubtitlelabel"},"doc://com.yababaGmbH.yababa/objc(pl)UIActivityItemsConfigurationProviding":{"type":"unresolvable","title":"UIKit.UIActivityItemsConfigurationProviding","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIActivityItemsConfigurationProviding"},"doc://com.yababaGmbH.yababa/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.yababaGmbH.yababa\/s7CVarArgP"},"doc://com.yababaGmbH.yababa/documentation/Yababa/CheckoutSceneViewController/totalSavingsValueLabel":{"role":"symbol","title":"totalSavingsValueLabel","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"totalSavingsValueLabel"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UILabel","preciseIdentifier":"c:objc(cs)UILabel"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CheckoutSceneViewController\/totalSavingsValueLabel","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"totalSavingsValueLabel"}],"url":"\/documentation\/yababa\/checkoutsceneviewcontroller\/totalsavingsvaluelabel"},"doc://com.yababaGmbH.yababa/documentation/Yababa/CheckoutSceneViewController/promoDiscountTextLabel":{"role":"symbol","title":"promoDiscountTextLabel","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"promoDiscountTextLabel"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UILabel","preciseIdentifier":"c:objc(cs)UILabel"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CheckoutSceneViewController\/promoDiscountTextLabel","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"promoDiscountTextLabel"}],"url":"\/documentation\/yababa\/checkoutsceneviewcontroller\/promodiscounttextlabel"},"doc://com.yababaGmbH.yababa/objc(pl)UIFocusEnvironment":{"type":"unresolvable","title":"UIKit.UIFocusEnvironment","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIFocusEnvironment"},"doc://com.yababaGmbH.yababa/documentation/Yababa/CheckoutSceneViewController/addressLabel":{"role":"symbol","title":"addressLabel","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"addressLabel"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UILabel","preciseIdentifier":"c:objc(cs)UILabel"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CheckoutSceneViewController\/addressLabel","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"addressLabel"}],"url":"\/documentation\/yababa\/checkoutsceneviewcontroller\/addresslabel"},"doc://com.yababaGmbH.yababa/documentation/Yababa/CheckoutSceneViewController/userEnteredCoupon()":{"role":"symbol","title":"userEnteredCoupon()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"userEnteredCoupon"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CheckoutSceneViewController\/userEnteredCoupon()","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/checkoutsceneviewcontroller\/userenteredcoupon()"},"doc://com.yababaGmbH.yababa/documentation/Yababa/CheckoutSceneViewController/onCardSelection()":{"role":"symbol","title":"onCardSelection()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onCardSelection"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CheckoutSceneViewController\/onCardSelection()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"onCardSelection"}],"url":"\/documentation\/yababa\/checkoutsceneviewcontroller\/oncardselection()"},"doc://com.yababaGmbH.yababa/documentation/Yababa/CheckoutSceneViewController/initWithNibName:bundle:":{"role":"symbol","title":"initWithNibName:bundle:","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithNibName:bundle:"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CheckoutSceneViewController\/initWithNibName:bundle:","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithNibName:bundle:"}],"url":"\/documentation\/yababa\/checkoutsceneviewcontroller\/initwithnibname:bundle:"},"doc://com.yababaGmbH.yababa/documentation/Yababa/CheckoutSceneViewController/UIViewControllerTransitioningDelegate-Implementations":{"role":"collectionGroup","title":"UIViewControllerTransitioningDelegate Implementations","abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CheckoutSceneViewController\/UIViewControllerTransitioningDelegate-Implementations","kind":"article","type":"topic","url":"\/documentation\/yababa\/checkoutsceneviewcontroller\/uiviewcontrollertransitioningdelegate-implementations"},"doc://com.yababaGmbH.yababa/documentation/Yababa/CheckoutSceneViewController/cardIconImageContainer":{"role":"symbol","title":"cardIconImageContainer","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"cardIconImageContainer"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CheckoutSceneViewController\/cardIconImageContainer","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"cardIconImageContainer"}],"url":"\/documentation\/yababa\/checkoutsceneviewcontroller\/cardiconimagecontainer"},"doc://com.yababaGmbH.yababa/documentation/Yababa/CheckoutSceneViewController/cardView":{"role":"symbol","title":"cardView","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"cardView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CheckoutSceneViewController\/cardView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"cardView"}],"url":"\/documentation\/yababa\/checkoutsceneviewcontroller\/cardview"},"doc://com.yababaGmbH.yababa/documentation/Yababa/CheckoutSceneViewController/onAddVoucher()":{"role":"symbol","title":"onAddVoucher()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onAddVoucher"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CheckoutSceneViewController\/onAddVoucher()","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/checkoutsceneviewcontroller\/onaddvoucher()"},"doc://com.yababaGmbH.yababa/objc(pl)UIContentContainer":{"type":"unresolvable","title":"UIKit.UIContentContainer","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIContentContainer"},"doc://com.yababaGmbH.yababa/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.yababaGmbH.yababa\/s23CustomStringConvertibleP"},"doc://com.yababaGmbH.yababa/documentation/Yababa/CheckoutSceneViewController/CheckoutSceneViewControllerProtocol-Implementations":{"role":"collectionGroup","title":"CheckoutSceneViewControllerProtocol Implementations","abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CheckoutSceneViewController\/CheckoutSceneViewControllerProtocol-Implementations","kind":"article","type":"topic","url":"\/documentation\/yababa\/checkoutsceneviewcontroller\/checkoutsceneviewcontrollerprotocol-implementations"},"doc://com.yababaGmbH.yababa/documentation/Yababa/CheckoutSceneViewController/totalLabel":{"role":"symbol","title":"totalLabel","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"totalLabel"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UILabel","preciseIdentifier":"c:objc(cs)UILabel"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CheckoutSceneViewController\/totalLabel","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"totalLabel"}],"url":"\/documentation\/yababa\/checkoutsceneviewcontroller\/totallabel"},"doc://com.yababaGmbH.yababa/documentation/Yababa/CheckoutSceneViewController/yababaTermsLabel":{"role":"symbol","title":"yababaTermsLabel","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"yababaTermsLabel"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NantesLabel","preciseIdentifier":"c:@M@Nantes@objc(cs)NantesLabel"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CheckoutSceneViewController\/yababaTermsLabel","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"yababaTermsLabel"}],"url":"\/documentation\/yababa\/checkoutsceneviewcontroller\/yababatermslabel"},"doc://com.yababaGmbH.yababa/documentation/Yababa/CheckoutSceneViewController/onDeliveryAddress()":{"role":"symbol","title":"onDeliveryAddress()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onDeliveryAddress"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CheckoutSceneViewController\/onDeliveryAddress()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"onDeliveryAddress"}],"url":"\/documentation\/yababa\/checkoutsceneviewcontroller\/ondeliveryaddress()"},"doc://com.yababaGmbH.yababa/objc(pl)UIUserActivityRestoring":{"type":"unresolvable","title":"UIKit.UIUserActivityRestoring","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIUserActivityRestoring"},"doc://com.yababaGmbH.yababa/documentation/Yababa/CheckoutSceneViewController/interactor":{"role":"symbol","title":"interactor","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"interactor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CheckoutSceneInteractorProtocol","preciseIdentifier":"s:6Yababa31CheckoutSceneInteractorProtocolP"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CheckoutSceneViewController\/interactor","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/checkoutsceneviewcontroller\/interactor"},"doc://com.yababaGmbH.yababa/documentation/Yababa/CheckoutSceneViewController/deliveryTimeAddressContainer":{"role":"symbol","title":"deliveryTimeAddressContainer","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"deliveryTimeAddressContainer"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CheckoutSceneViewController\/deliveryTimeAddressContainer","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"deliveryTimeAddressContainer"}],"url":"\/documentation\/yababa\/checkoutsceneviewcontroller\/deliverytimeaddresscontainer"},"doc://com.yababaGmbH.yababa/documentation/Yababa/CheckoutSceneViewController/viewWillAppear(_:)":{"role":"symbol","title":"viewWillAppear(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"viewWillAppear"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CheckoutSceneViewController\/viewWillAppear(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"viewWillAppear:"}],"url":"\/documentation\/yababa\/checkoutsceneviewcontroller\/viewwillappear(_:)"},"doc://com.yababaGmbH.yababa/objc(pl)NSExtensionRequestHandling":{"type":"unresolvable","title":"Foundation.NSExtensionRequestHandling","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)NSExtensionRequestHandling"},"doc://com.yababaGmbH.yababa/documentation/Yababa/CheckoutSceneViewController/vouchersCollectionView":{"role":"symbol","title":"vouchersCollectionView","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"vouchersCollectionView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DiscountsCollectionView","preciseIdentifier":"c:@M@Yababa@objc(cs)DiscountsCollectionView"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CheckoutSceneViewController\/vouchersCollectionView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"vouchersCollectionView"}],"url":"\/documentation\/yababa\/checkoutsceneviewcontroller\/voucherscollectionview"},"doc://com.yababaGmbH.yababa/documentation/Yababa/CheckoutSceneViewController/AddressManagerOwner-Implementations":{"role":"collectionGroup","title":"AddressManagerOwner Implementations","abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CheckoutSceneViewController\/AddressManagerOwner-Implementations","kind":"article","type":"topic","url":"\/documentation\/yababa\/checkoutsceneviewcontroller\/addressmanagerowner-implementations"},"doc://com.yababaGmbH.yababa/documentation/Yababa/CheckoutSceneViewController/onDeliveryTime()":{"role":"symbol","title":"onDeliveryTime()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onDeliveryTime"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CheckoutSceneViewController\/onDeliveryTime()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"onDeliveryTime"}],"url":"\/documentation\/yababa\/checkoutsceneviewcontroller\/ondeliverytime()"},"doc://com.yababaGmbH.yababa/documentation/Yababa/CheckoutSceneViewController/addressSelectionManager":{"role":"symbol","title":"addressSelectionManager","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"addressSelectionManager"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AddressSelectionManager","preciseIdentifier":"s:6Yababa23AddressSelectionManagerP"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CheckoutSceneViewController\/addressSelectionManager","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/checkoutsceneviewcontroller\/addressselectionmanager"},"doc://com.yababaGmbH.yababa/documentation/Yababa/MasterViewController":{"role":"symbol","title":"MasterViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MasterViewController"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/MasterViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MasterViewController"}],"url":"\/documentation\/yababa\/masterviewcontroller"},"doc://com.yababaGmbH.yababa/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)NSObject"},"doc://com.yababaGmbH.yababa/documentation/Yababa/CheckoutSceneViewControllerProtocol":{"role":"symbol","title":"CheckoutSceneViewControllerProtocol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"CheckoutSceneViewControllerProtocol"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CheckoutSceneViewControllerProtocol","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CheckoutSceneViewControllerProtocol"}],"url":"\/documentation\/yababa\/checkoutsceneviewcontrollerprotocol"},"doc://com.yababaGmbH.yababa/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.yababaGmbH.yababa\/SQ"},"doc://com.yababaGmbH.yababa/documentation/Yababa/CheckoutSceneViewController/promosDiscountValueLabel":{"role":"symbol","title":"promosDiscountValueLabel","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"promosDiscountValueLabel"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UILabel","preciseIdentifier":"c:objc(cs)UILabel"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CheckoutSceneViewController\/promosDiscountValueLabel","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"promosDiscountValueLabel"}],"url":"\/documentation\/yababa\/checkoutsceneviewcontroller\/promosdiscountvaluelabel"},"doc://com.yababaGmbH.yababa/documentation/Yababa/CheckoutSceneViewController/addressManagerInteractor":{"role":"symbol","title":"addressManagerInteractor","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"addressManagerInteractor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AddressManagerInteractorProtocol","preciseIdentifier":"s:6Yababa32AddressManagerInteractorProtocolP"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CheckoutSceneViewController\/addressManagerInteractor","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/checkoutsceneviewcontroller\/addressmanagerinteractor"},"doc://com.yababaGmbH.yababa/documentation/Yababa/CheckoutSceneViewController/discountTextLabel":{"role":"symbol","title":"discountTextLabel","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"discountTextLabel"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UILabel","preciseIdentifier":"c:objc(cs)UILabel"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CheckoutSceneViewController\/discountTextLabel","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"discountTextLabel"}],"url":"\/documentation\/yababa\/checkoutsceneviewcontroller\/discounttextlabel"},"doc://com.yababaGmbH.yababa/documentation/Yababa/CheckoutSceneViewController/showSpinner()":{"role":"symbol","title":"showSpinner()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"showSpinner"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CheckoutSceneViewController\/showSpinner()","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/checkoutsceneviewcontroller\/showspinner()"},"doc://com.yababaGmbH.yababa/documentation/Yababa/CheckoutSceneViewController/viewDidDisappear(_:)":{"role":"symbol","title":"viewDidDisappear(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"viewDidDisappear"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CheckoutSceneViewController\/viewDidDisappear(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"viewDidDisappear:"}],"url":"\/documentation\/yababa\/checkoutsceneviewcontroller\/viewdiddisappear(_:)"},"doc://com.yababaGmbH.yababa/documentation/Yababa/CheckoutSceneViewController/showLoadingOverview()":{"role":"symbol","title":"showLoadingOverview()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"showLoadingOverview"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CheckoutSceneViewController\/showLoadingOverview()","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/checkoutsceneviewcontroller\/showloadingoverview()"},"doc://com.yababaGmbH.yababa/documentation/Yababa/CheckoutSceneViewController/STPAuthenticationContext-Implementations":{"role":"collectionGroup","title":"STPAuthenticationContext Implementations","abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CheckoutSceneViewController\/STPAuthenticationContext-Implementations","kind":"article","type":"topic","url":"\/documentation\/yababa\/checkoutsceneviewcontroller\/stpauthenticationcontext-implementations"},"doc://com.yababaGmbH.yababa/documentation/Yababa/CheckoutSceneViewController/FlowProcessorDelegate-Implementations":{"role":"collectionGroup","title":"FlowProcessorDelegate Implementations","abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CheckoutSceneViewController\/FlowProcessorDelegate-Implementations","kind":"article","type":"topic","url":"\/documentation\/yababa\/checkoutsceneviewcontroller\/flowprocessordelegate-implementations"},"doc://com.yababaGmbH.yababa/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.yababaGmbH.yababa\/s28CustomDebugStringConvertibleP"},"doc://com.yababaGmbH.yababa/documentation/Yababa/CheckoutSceneViewController/deliveryFeeTextLabel":{"role":"symbol","title":"deliveryFeeTextLabel","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"deliveryFeeTextLabel"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UILabel","preciseIdentifier":"c:objc(cs)UILabel"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CheckoutSceneViewController\/deliveryFeeTextLabel","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"deliveryFeeTextLabel"}],"url":"\/documentation\/yababa\/checkoutsceneviewcontroller\/deliveryfeetextlabel"},"doc://com.yababaGmbH.yababa/documentation/Yababa/CheckoutSceneViewController/deliveryFeesLabel":{"role":"symbol","title":"deliveryFeesLabel","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"deliveryFeesLabel"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UILabel","preciseIdentifier":"c:objc(cs)UILabel"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CheckoutSceneViewController\/deliveryFeesLabel","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"deliveryFeesLabel"}],"url":"\/documentation\/yababa\/checkoutsceneviewcontroller\/deliveryfeeslabel"},"doc://com.yababaGmbH.yababa/documentation/Yababa/CheckoutSceneViewController/setIdentifiers()":{"role":"symbol","title":"setIdentifiers()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setIdentifiers"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CheckoutSceneViewController\/setIdentifiers()","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/checkoutsceneviewcontroller\/setidentifiers()"},"doc://com.yababaGmbH.yababa/documentation/Yababa":{"role":"collection","title":"Yababa","abstract":[{"type":"text","text":"Getting Started"}],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa","kind":"symbol","type":"topic","url":"\/documentation\/yababa"},"doc://com.yababaGmbH.yababa/objc(pl)UIPasteConfigurationSupporting":{"type":"unresolvable","title":"UIKit.UIPasteConfigurationSupporting","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIPasteConfigurationSupporting"},"doc://com.yababaGmbH.yababa/documentation/Yababa/CheckoutSceneViewController/discountContainerView":{"role":"symbol","title":"discountContainerView","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"discountContainerView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CheckoutSceneViewController\/discountContainerView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"discountContainerView"}],"url":"\/documentation\/yababa\/checkoutsceneviewcontroller\/discountcontainerview"},"doc://com.yababaGmbH.yababa/documentation/Yababa/CheckoutSceneViewController/gatewayFeesLabel":{"role":"symbol","title":"gatewayFeesLabel","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"gatewayFeesLabel"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UILabel","preciseIdentifier":"c:objc(cs)UILabel"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CheckoutSceneViewController\/gatewayFeesLabel","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"gatewayFeesLabel"}],"url":"\/documentation\/yababa\/checkoutsceneviewcontroller\/gatewayfeeslabel"},"doc://com.yababaGmbH.yababa/documentation/Yababa/CheckoutSceneViewController/cardInfoView":{"role":"symbol","title":"cardInfoView","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"cardInfoView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CheckoutSceneViewController\/cardInfoView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"cardInfoView"}],"url":"\/documentation\/yababa\/checkoutsceneviewcontroller\/cardinfoview"},"doc://com.yababaGmbH.yababa/documentation/Yababa/CheckoutSceneViewController/placeOrderBtnContainer":{"role":"symbol","title":"placeOrderBtnContainer","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"placeOrderBtnContainer"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CheckoutSceneViewController\/placeOrderBtnContainer","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"placeOrderBtnContainer"}],"url":"\/documentation\/yababa\/checkoutsceneviewcontroller\/placeorderbtncontainer"},"doc://com.yababaGmbH.yababa/documentation/Yababa/CheckoutSceneViewController/summaryView":{"role":"symbol","title":"summaryView","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"summaryView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CheckoutSceneViewController\/summaryView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"summaryView"}],"url":"\/documentation\/yababa\/checkoutsceneviewcontroller\/summaryview"},"doc://com.yababaGmbH.yababa/documentation/Yababa/CheckoutSceneViewController/cardCoverImageView":{"role":"symbol","title":"cardCoverImageView","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"cardCoverImageView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIImageView","preciseIdentifier":"c:objc(cs)UIImageView"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CheckoutSceneViewController\/cardCoverImageView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"cardCoverImageView"}],"url":"\/documentation\/yababa\/checkoutsceneviewcontroller\/cardcoverimageview"},"doc://com.yababaGmbH.yababa/documentation/Yababa/CheckoutSceneViewController/smallSpinner":{"role":"symbol","title":"smallSpinner","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"smallSpinner"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIActivityIndicatorView","preciseIdentifier":"c:objc(cs)UIActivityIndicatorView"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CheckoutSceneViewController\/smallSpinner","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"smallSpinner"}],"url":"\/documentation\/yababa\/checkoutsceneviewcontroller\/smallspinner"},"doc://com.yababaGmbH.yababa/documentation/Yababa/CheckoutSceneViewController/totalTextLabel":{"role":"symbol","title":"totalTextLabel","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"totalTextLabel"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UILabel","preciseIdentifier":"c:objc(cs)UILabel"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CheckoutSceneViewController\/totalTextLabel","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"totalTextLabel"}],"url":"\/documentation\/yababa\/checkoutsceneviewcontroller\/totaltextlabel"},"doc://com.yababaGmbH.yababa/documentation/Yababa/CheckoutSceneViewController/addressAdditionalInfoLabel":{"role":"symbol","title":"addressAdditionalInfoLabel","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"addressAdditionalInfoLabel"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UILabel","preciseIdentifier":"c:objc(cs)UILabel"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CheckoutSceneViewController\/addressAdditionalInfoLabel","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"addressAdditionalInfoLabel"}],"url":"\/documentation\/yababa\/checkoutsceneviewcontroller\/addressadditionalinfolabel"},"doc://com.yababaGmbH.yababa/documentation/Yababa/CheckoutSceneViewController/deliveryTimeButton":{"role":"symbol","title":"deliveryTimeButton","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"deliveryTimeButton"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIButton","preciseIdentifier":"c:objc(cs)UIButton"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CheckoutSceneViewController\/deliveryTimeButton","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"deliveryTimeButton"}],"url":"\/documentation\/yababa\/checkoutsceneviewcontroller\/deliverytimebutton"},"doc://com.yababaGmbH.yababa/objc(pl)UIStateRestoring":{"type":"unresolvable","title":"UIKit.UIStateRestoring","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIStateRestoring"},"doc://com.yababaGmbH.yababa/documentation/Yababa/CheckoutSceneViewController/placeOrderBtn":{"role":"symbol","title":"placeOrderBtn","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"placeOrderBtn"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIButton","preciseIdentifier":"c:objc(cs)UIButton"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CheckoutSceneViewController\/placeOrderBtn","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"placeOrderBtn"}],"url":"\/documentation\/yababa\/checkoutsceneviewcontroller\/placeorderbtn"},"doc://com.yababaGmbH.yababa/documentation/Yababa/CheckoutSceneViewController/serverMessageLabel":{"role":"symbol","title":"serverMessageLabel","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"serverMessageLabel"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UILabel","preciseIdentifier":"c:objc(cs)UILabel"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CheckoutSceneViewController\/serverMessageLabel","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"serverMessageLabel"}],"url":"\/documentation\/yababa\/checkoutsceneviewcontroller\/servermessagelabel"},"doc://com.yababaGmbH.yababa/objc(pl)NSCoding":{"type":"unresolvable","title":"Foundation.NSCoding","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)NSCoding"},"doc://com.yababaGmbH.yababa/documentation/Yababa/CheckoutSceneViewController/deliveryTimeLabel":{"role":"symbol","title":"deliveryTimeLabel","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"deliveryTimeLabel"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UILabel","preciseIdentifier":"c:objc(cs)UILabel"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CheckoutSceneViewController\/deliveryTimeLabel","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"deliveryTimeLabel"}],"url":"\/documentation\/yababa\/checkoutsceneviewcontroller\/deliverytimelabel"},"doc://com.yababaGmbH.yababa/documentation/Yababa/CheckoutSceneViewController/serverMessageContainer":{"role":"symbol","title":"serverMessageContainer","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"serverMessageContainer"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CheckoutSceneViewController\/serverMessageContainer","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"serverMessageContainer"}],"url":"\/documentation\/yababa\/checkoutsceneviewcontroller\/servermessagecontainer"},"doc://com.yababaGmbH.yababa/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/com.yababaGmbH.yababa\/s8SendableP"},"doc://com.yababaGmbH.yababa/documentation/Yababa/CheckoutSceneViewController/viewDidLoad()":{"role":"symbol","title":"viewDidLoad()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"viewDidLoad"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CheckoutSceneViewController\/viewDidLoad()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"viewDidLoad"}],"url":"\/documentation\/yababa\/checkoutsceneviewcontroller\/viewdidload()"},"doc://com.yababaGmbH.yababa/objc(pl)UIViewControllerTransitioningDelegate":{"type":"unresolvable","title":"UIKit.UIViewControllerTransitioningDelegate","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIViewControllerTransitioningDelegate"},"doc://com.yababaGmbH.yababa/documentation/Yababa/CheckoutSceneViewController/initWithCoder:":{"role":"symbol","title":"initWithCoder:","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithCoder:"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CheckoutSceneViewController\/initWithCoder:","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithCoder:"}],"url":"\/documentation\/yababa\/checkoutsceneviewcontroller\/initwithcoder:"},"doc://com.yababaGmbH.yababa/documentation/Yababa/CheckoutSceneViewController/hideLoadingOverview()":{"role":"symbol","title":"hideLoadingOverview()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"hideLoadingOverview"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CheckoutSceneViewController\/hideLoadingOverview()","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/checkoutsceneviewcontroller\/hideloadingoverview()"},"doc://com.yababaGmbH.yababa/documentation/Yababa/CheckoutSceneViewController/freeDeliveryFeesView":{"role":"symbol","title":"freeDeliveryFeesView","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"freeDeliveryFeesView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CheckoutSceneViewController\/freeDeliveryFeesView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"freeDeliveryFeesView"}],"url":"\/documentation\/yababa\/checkoutsceneviewcontroller\/freedeliveryfeesview"},"doc://com.yababaGmbH.yababa/12SkeletonView17AssociatedObjectsP":{"type":"unresolvable","title":"SkeletonView.AssociatedObjects","identifier":"doc:\/\/com.yababaGmbH.yababa\/12SkeletonView17AssociatedObjectsP"},"doc://com.yababaGmbH.yababa/@M@Stripe@objc(pl)STPAuthenticationContext":{"type":"unresolvable","title":"Stripe.STPAuthenticationContext","identifier":"doc:\/\/com.yababaGmbH.yababa\/@M@Stripe@objc(pl)STPAuthenticationContext"},"doc://com.yababaGmbH.yababa/documentation/Yababa/CheckoutSceneViewController/totalSavingsTitleLabel":{"role":"symbol","title":"totalSavingsTitleLabel","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"totalSavingsTitleLabel"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UILabel","preciseIdentifier":"c:objc(cs)UILabel"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CheckoutSceneViewController\/totalSavingsTitleLabel","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"totalSavingsTitleLabel"}],"url":"\/documentation\/yababa\/checkoutsceneviewcontroller\/totalsavingstitlelabel"},"doc://com.yababaGmbH.yababa/documentation/Yababa/CheckoutSceneViewController/onPlaceOrder()":{"role":"symbol","title":"onPlaceOrder()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onPlaceOrder"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CheckoutSceneViewController\/onPlaceOrder()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"onPlaceOrder"}],"url":"\/documentation\/yababa\/checkoutsceneviewcontroller\/onplaceorder()"},"doc://com.yababaGmbH.yababa/objc(pl)UIAppearanceContainer":{"type":"unresolvable","title":"UIKit.UIAppearanceContainer","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIAppearanceContainer"},"doc://com.yababaGmbH.yababa/documentation/Yababa/CheckoutSceneViewController/NantesLabelDelegate-Implementations":{"role":"collectionGroup","title":"NantesLabelDelegate Implementations","abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CheckoutSceneViewController\/NantesLabelDelegate-Implementations","kind":"article","type":"topic","url":"\/documentation\/yababa\/checkoutsceneviewcontroller\/nanteslabeldelegate-implementations"},"doc://com.yababaGmbH.yababa/documentation/Yababa/CheckoutSceneViewController/router":{"role":"symbol","title":"router","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"router"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CheckoutSceneRouterProtocol","preciseIdentifier":"s:6Yababa27CheckoutSceneRouterProtocolP"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CheckoutSceneViewController\/router","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/checkoutsceneviewcontroller\/router"},"doc://com.yababaGmbH.yababa/documentation/Yababa/CheckoutSceneViewController/prepareCartCheckout()":{"role":"symbol","title":"prepareCartCheckout()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"prepareCartCheckout"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CheckoutSceneViewController\/prepareCartCheckout()","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/checkoutsceneviewcontroller\/preparecartcheckout()"},"doc://com.yababaGmbH.yababa/documentation/Yababa/CheckoutSceneViewController/promosDiscounContainer":{"role":"symbol","title":"promosDiscounContainer","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"promosDiscounContainer"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CheckoutSceneViewController\/promosDiscounContainer","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"promosDiscounContainer"}],"url":"\/documentation\/yababa\/checkoutsceneviewcontroller\/promosdiscouncontainer"},"doc://com.yababaGmbH.yababa/documentation/Yababa/CheckoutSceneViewController/paymentMethodLabel":{"role":"symbol","title":"paymentMethodLabel","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"paymentMethodLabel"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UILabel","preciseIdentifier":"c:objc(cs)UILabel"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CheckoutSceneViewController\/paymentMethodLabel","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"paymentMethodLabel"}],"url":"\/documentation\/yababa\/checkoutsceneviewcontroller\/paymentmethodlabel"},"doc://com.yababaGmbH.yababa/documentation/Yababa/CheckoutSceneViewController/orderSummaryLabel":{"role":"symbol","title":"orderSummaryLabel","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"orderSummaryLabel"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UILabel","preciseIdentifier":"c:objc(cs)UILabel"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CheckoutSceneViewController\/orderSummaryLabel","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"orderSummaryLabel"}],"url":"\/documentation\/yababa\/checkoutsceneviewcontroller\/ordersummarylabel"},"doc://com.yababaGmbH.yababa/documentation/Yababa/CheckoutSceneViewController/freeDeliveryFeesLabel":{"role":"symbol","title":"freeDeliveryFeesLabel","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"freeDeliveryFeesLabel"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"InsetLabel","preciseIdentifier":"c:@M@Yababa@objc(cs)InsetLabel"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CheckoutSceneViewController\/freeDeliveryFeesLabel","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"freeDeliveryFeesLabel"}],"url":"\/documentation\/yababa\/checkoutsceneviewcontroller\/freedeliveryfeeslabel"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"CheckoutSceneViewController"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"CheckoutSceneViewController"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"CheckoutSceneViewController"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CheckoutSceneViewController\/addressAdditionalInfoLabel","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CheckoutSceneViewController\/addressLabel","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CheckoutSceneViewController\/cardCoverImageView","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CheckoutSceneViewController\/cardIconImageContainer","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CheckoutSceneViewController\/cardInfoSubTitleLabel","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CheckoutSceneViewController\/cardInfoTitleLabel","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CheckoutSceneViewController\/cardInfoView","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CheckoutSceneViewController\/cardView","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CheckoutSceneViewController\/deliveryAddressButton","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CheckoutSceneViewController\/deliveryAddressLabel","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CheckoutSceneViewController\/deliveryFeeTextLabel","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CheckoutSceneViewController\/deliveryFeesLabel","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CheckoutSceneViewController\/deliveryTimeAddressContainer","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CheckoutSceneViewController\/deliveryTimeButton","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CheckoutSceneViewController\/deliveryTimeLabel","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CheckoutSceneViewController\/deliveryTimeTextLabel","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CheckoutSceneViewController\/discountContainerView","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CheckoutSceneViewController\/discountLabel","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CheckoutSceneViewController\/discountTextLabel","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CheckoutSceneViewController\/freeDeliveryFeesLabel","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CheckoutSceneViewController\/freeDeliveryFeesView","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CheckoutSceneViewController\/gatewayFeesLabel","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CheckoutSceneViewController\/orderSummaryLabel","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CheckoutSceneViewController\/paymentMethodLabel","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CheckoutSceneViewController\/placeOrderBtn","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CheckoutSceneViewController\/placeOrderBtnContainer","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CheckoutSceneViewController\/promoDiscountTextLabel","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CheckoutSceneViewController\/promosDiscounContainer","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CheckoutSceneViewController\/promosDiscountValueLabel","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CheckoutSceneViewController\/serverMessageContainer","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CheckoutSceneViewController\/serverMessageLabel","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CheckoutSceneViewController\/smallSpinner","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CheckoutSceneViewController\/subTotalLabel","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CheckoutSceneViewController\/subTotalTextLabel","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CheckoutSceneViewController\/summaryView","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CheckoutSceneViewController\/totalLabel","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CheckoutSceneViewController\/totalSavingsContainerView","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CheckoutSceneViewController\/totalSavingsTitleLabel","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CheckoutSceneViewController\/totalSavingsValueLabel","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CheckoutSceneViewController\/totalTextLabel","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CheckoutSceneViewController\/vouchersCollectionView","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CheckoutSceneViewController\/yababaTermsLabel"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CheckoutSceneViewController\/initWithCoder:","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CheckoutSceneViewController\/initWithNibName:bundle:","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CheckoutSceneViewController\/onCardSelection()","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CheckoutSceneViewController\/onDeliveryAddress()","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CheckoutSceneViewController\/onDeliveryTime()","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CheckoutSceneViewController\/onPlaceOrder()","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CheckoutSceneViewController\/viewDidDisappear(_:)","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CheckoutSceneViewController\/viewDidLoad()","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CheckoutSceneViewController\/viewWillAppear(_:)"]},{"title":"Default Implementations","identifiers":["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CheckoutSceneViewController\/STPAuthenticationContext-Implementations","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CheckoutSceneViewController\/UIViewControllerTransitioningDelegate-Implementations"],"generated":true}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/MasterViewController"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"CheckoutSceneViewController"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/MasterViewController","preciseIdentifier":"c:@M@Yababa@objc(cs)MasterViewController","text":"MasterViewController"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1CheckoutSceneViewController~1subTotalTextLabel\/title","value":"subTotalTextLabel"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1CheckoutSceneViewController~1subTotalTextLabel\/fragments","value":[{"kind":"identifier","text":"subTotalTextLabel"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1CheckoutSceneViewController~1deliveryAddressButton\/title","value":"deliveryAddressButton"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1CheckoutSceneViewController~1deliveryAddressButton\/fragments","value":[{"kind":"identifier","text":"deliveryAddressButton"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1CheckoutSceneViewController~1deliveryTimeTextLabel\/title","value":"deliveryTimeTextLabel"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1CheckoutSceneViewController~1deliveryTimeTextLabel\/fragments","value":[{"kind":"identifier","text":"deliveryTimeTextLabel"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1CheckoutSceneViewController~1deliveryAddressLabel\/title","value":"deliveryAddressLabel"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1CheckoutSceneViewController~1deliveryAddressLabel\/fragments","value":[{"kind":"identifier","text":"deliveryAddressLabel"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1CheckoutSceneViewController\/title","value":"CheckoutSceneViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1CheckoutSceneViewController\/fragments","value":[{"kind":"identifier","text":"CheckoutSceneViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1CheckoutSceneViewController~1totalSavingsContainerView\/title","value":"totalSavingsContainerView"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1CheckoutSceneViewController~1totalSavingsContainerView\/fragments","value":[{"kind":"identifier","text":"totalSavingsContainerView"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1CheckoutSceneViewController~1subTotalLabel\/title","value":"subTotalLabel"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1CheckoutSceneViewController~1subTotalLabel\/fragments","value":[{"kind":"identifier","text":"subTotalLabel"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1CheckoutSceneViewController~1discountLabel\/title","value":"discountLabel"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1CheckoutSceneViewController~1discountLabel\/fragments","value":[{"kind":"identifier","text":"discountLabel"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1CheckoutSceneViewController~1cardInfoTitleLabel\/title","value":"cardInfoTitleLabel"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1CheckoutSceneViewController~1cardInfoTitleLabel\/fragments","value":[{"kind":"identifier","text":"cardInfoTitleLabel"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1CheckoutSceneViewController~1cardInfoSubTitleLabel\/title","value":"cardInfoSubTitleLabel"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1CheckoutSceneViewController~1cardInfoSubTitleLabel\/fragments","value":[{"kind":"identifier","text":"cardInfoSubTitleLabel"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1CheckoutSceneViewController~1totalSavingsValueLabel\/title","value":"totalSavingsValueLabel"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1CheckoutSceneViewController~1totalSavingsValueLabel\/fragments","value":[{"kind":"identifier","text":"totalSavingsValueLabel"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1CheckoutSceneViewController~1promoDiscountTextLabel\/title","value":"promoDiscountTextLabel"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1CheckoutSceneViewController~1promoDiscountTextLabel\/fragments","value":[{"kind":"identifier","text":"promoDiscountTextLabel"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1CheckoutSceneViewController~1addressLabel\/title","value":"addressLabel"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1CheckoutSceneViewController~1addressLabel\/fragments","value":[{"kind":"identifier","text":"addressLabel"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1CheckoutSceneViewController~1onCardSelection()\/title","value":"onCardSelection"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1CheckoutSceneViewController~1onCardSelection()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onCardSelection"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1CheckoutSceneViewController~1cardIconImageContainer\/title","value":"cardIconImageContainer"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1CheckoutSceneViewController~1cardIconImageContainer\/fragments","value":[{"kind":"identifier","text":"cardIconImageContainer"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1CheckoutSceneViewController~1cardView\/title","value":"cardView"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1CheckoutSceneViewController~1cardView\/fragments","value":[{"kind":"identifier","text":"cardView"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1CheckoutSceneViewController~1totalLabel\/title","value":"totalLabel"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1CheckoutSceneViewController~1totalLabel\/fragments","value":[{"kind":"identifier","text":"totalLabel"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1CheckoutSceneViewController~1yababaTermsLabel\/title","value":"yababaTermsLabel"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1CheckoutSceneViewController~1yababaTermsLabel\/fragments","value":[{"kind":"identifier","text":"yababaTermsLabel"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1CheckoutSceneViewController~1onDeliveryAddress()\/title","value":"onDeliveryAddress"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1CheckoutSceneViewController~1onDeliveryAddress()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onDeliveryAddress"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1CheckoutSceneViewController~1deliveryTimeAddressContainer\/title","value":"deliveryTimeAddressContainer"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1CheckoutSceneViewController~1deliveryTimeAddressContainer\/fragments","value":[{"kind":"identifier","text":"deliveryTimeAddressContainer"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1CheckoutSceneViewController~1viewWillAppear(_:)\/title","value":"viewWillAppear:"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1CheckoutSceneViewController~1viewWillAppear(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"viewWillAppear:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1CheckoutSceneViewController~1vouchersCollectionView\/title","value":"vouchersCollectionView"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1CheckoutSceneViewController~1vouchersCollectionView\/fragments","value":[{"kind":"identifier","text":"vouchersCollectionView"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1CheckoutSceneViewController~1onDeliveryTime()\/title","value":"onDeliveryTime"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1CheckoutSceneViewController~1onDeliveryTime()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onDeliveryTime"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1MasterViewController\/title","value":"MasterViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1MasterViewController\/fragments","value":[{"kind":"identifier","text":"MasterViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1CheckoutSceneViewController~1promosDiscountValueLabel\/title","value":"promosDiscountValueLabel"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1CheckoutSceneViewController~1promosDiscountValueLabel\/fragments","value":[{"kind":"identifier","text":"promosDiscountValueLabel"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1CheckoutSceneViewController~1discountTextLabel\/title","value":"discountTextLabel"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1CheckoutSceneViewController~1discountTextLabel\/fragments","value":[{"kind":"identifier","text":"discountTextLabel"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1CheckoutSceneViewController~1viewDidDisappear(_:)\/title","value":"viewDidDisappear:"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1CheckoutSceneViewController~1viewDidDisappear(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"viewDidDisappear:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1CheckoutSceneViewController~1deliveryFeeTextLabel\/title","value":"deliveryFeeTextLabel"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1CheckoutSceneViewController~1deliveryFeeTextLabel\/fragments","value":[{"kind":"identifier","text":"deliveryFeeTextLabel"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1CheckoutSceneViewController~1deliveryFeesLabel\/title","value":"deliveryFeesLabel"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1CheckoutSceneViewController~1deliveryFeesLabel\/fragments","value":[{"kind":"identifier","text":"deliveryFeesLabel"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1CheckoutSceneViewController~1discountContainerView\/title","value":"discountContainerView"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1CheckoutSceneViewController~1discountContainerView\/fragments","value":[{"kind":"identifier","text":"discountContainerView"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1CheckoutSceneViewController~1gatewayFeesLabel\/title","value":"gatewayFeesLabel"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1CheckoutSceneViewController~1gatewayFeesLabel\/fragments","value":[{"kind":"identifier","text":"gatewayFeesLabel"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1CheckoutSceneViewController~1cardInfoView\/title","value":"cardInfoView"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1CheckoutSceneViewController~1cardInfoView\/fragments","value":[{"kind":"identifier","text":"cardInfoView"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1CheckoutSceneViewController~1placeOrderBtnContainer\/title","value":"placeOrderBtnContainer"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1CheckoutSceneViewController~1placeOrderBtnContainer\/fragments","value":[{"kind":"identifier","text":"placeOrderBtnContainer"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1CheckoutSceneViewController~1summaryView\/title","value":"summaryView"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1CheckoutSceneViewController~1summaryView\/fragments","value":[{"kind":"identifier","text":"summaryView"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1CheckoutSceneViewController~1cardCoverImageView\/title","value":"cardCoverImageView"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1CheckoutSceneViewController~1cardCoverImageView\/fragments","value":[{"kind":"identifier","text":"cardCoverImageView"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1CheckoutSceneViewController~1smallSpinner\/title","value":"smallSpinner"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1CheckoutSceneViewController~1smallSpinner\/fragments","value":[{"kind":"identifier","text":"smallSpinner"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1CheckoutSceneViewController~1totalTextLabel\/title","value":"totalTextLabel"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1CheckoutSceneViewController~1totalTextLabel\/fragments","value":[{"kind":"identifier","text":"totalTextLabel"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1CheckoutSceneViewController~1addressAdditionalInfoLabel\/title","value":"addressAdditionalInfoLabel"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1CheckoutSceneViewController~1addressAdditionalInfoLabel\/fragments","value":[{"kind":"identifier","text":"addressAdditionalInfoLabel"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1CheckoutSceneViewController~1deliveryTimeButton\/title","value":"deliveryTimeButton"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1CheckoutSceneViewController~1deliveryTimeButton\/fragments","value":[{"kind":"identifier","text":"deliveryTimeButton"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1CheckoutSceneViewController~1placeOrderBtn\/title","value":"placeOrderBtn"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1CheckoutSceneViewController~1placeOrderBtn\/fragments","value":[{"kind":"identifier","text":"placeOrderBtn"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1CheckoutSceneViewController~1serverMessageLabel\/title","value":"serverMessageLabel"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1CheckoutSceneViewController~1serverMessageLabel\/fragments","value":[{"kind":"identifier","text":"serverMessageLabel"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1CheckoutSceneViewController~1deliveryTimeLabel\/title","value":"deliveryTimeLabel"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1CheckoutSceneViewController~1deliveryTimeLabel\/fragments","value":[{"kind":"identifier","text":"deliveryTimeLabel"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1CheckoutSceneViewController~1serverMessageContainer\/title","value":"serverMessageContainer"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1CheckoutSceneViewController~1serverMessageContainer\/fragments","value":[{"kind":"identifier","text":"serverMessageContainer"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1CheckoutSceneViewController~1viewDidLoad()\/title","value":"viewDidLoad"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1CheckoutSceneViewController~1viewDidLoad()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"viewDidLoad"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1CheckoutSceneViewController~1freeDeliveryFeesView\/title","value":"freeDeliveryFeesView"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1CheckoutSceneViewController~1freeDeliveryFeesView\/fragments","value":[{"kind":"identifier","text":"freeDeliveryFeesView"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1CheckoutSceneViewController~1totalSavingsTitleLabel\/title","value":"totalSavingsTitleLabel"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1CheckoutSceneViewController~1totalSavingsTitleLabel\/fragments","value":[{"kind":"identifier","text":"totalSavingsTitleLabel"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1CheckoutSceneViewController~1onPlaceOrder()\/title","value":"onPlaceOrder"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1CheckoutSceneViewController~1onPlaceOrder()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onPlaceOrder"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1CheckoutSceneViewController~1promosDiscounContainer\/title","value":"promosDiscounContainer"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1CheckoutSceneViewController~1promosDiscounContainer\/fragments","value":[{"kind":"identifier","text":"promosDiscounContainer"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1CheckoutSceneViewController~1paymentMethodLabel\/title","value":"paymentMethodLabel"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1CheckoutSceneViewController~1paymentMethodLabel\/fragments","value":[{"kind":"identifier","text":"paymentMethodLabel"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1CheckoutSceneViewController~1orderSummaryLabel\/title","value":"orderSummaryLabel"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1CheckoutSceneViewController~1orderSummaryLabel\/fragments","value":[{"kind":"identifier","text":"orderSummaryLabel"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1CheckoutSceneViewController~1freeDeliveryFeesLabel\/title","value":"freeDeliveryFeesLabel"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1CheckoutSceneViewController~1freeDeliveryFeesLabel\/fragments","value":[{"kind":"identifier","text":"freeDeliveryFeesLabel"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}