{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CheckoutSceneRouter"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/yababa\/checkoutscenerouter"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/yababa\/checkoutscenerouter"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.yababaGmbH.yababa\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AddCouponPopupRoutable","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CheckoutSceneRouterProtocol","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/DeliveryTimeSlotPickerDelegate","doc:\/\/com.yababaGmbH.yababa\/objc(pl)NSObject","doc:\/\/com.yababaGmbH.yababa\/12SkeletonView17AssociatedObjectsP","doc:\/\/com.yababaGmbH.yababa\/s7CVarArgP","doc:\/\/com.yababaGmbH.yababa\/s28CustomDebugStringConvertibleP","doc:\/\/com.yababaGmbH.yababa\/s23CustomStringConvertibleP","doc:\/\/com.yababaGmbH.yababa\/SQ","doc:\/\/com.yababaGmbH.yababa\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CheckoutSceneRouter","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CheckoutSceneRouter\/viewController"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CheckoutSceneRouter\/deallocate()","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CheckoutSceneRouter\/navigateToCardSelection(creditCards:otherPaymentMethodCards:)","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CheckoutSceneRouter\/navigateToPaymentProcessor(_:subGateway:)","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CheckoutSceneRouter\/navigateToReceiptView(orderId:)","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CheckoutSceneRouter\/navigateToTimeSlotSelection()"]},{"title":"Default Implementations","identifiers":["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CheckoutSceneRouter\/DeliveryTimeSlotPickerDelegate-Implementations"],"generated":true}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CheckoutSceneRouter"}],"title":"CheckoutSceneRouter","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@Yababa@objc(cs)CheckoutSceneRouter","modules":[{"name":"Yababa"}],"navigatorTitle":[{"kind":"identifier","text":"CheckoutSceneRouter"}]},"hierarchy":{"paths":[["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa"]]},"references":{"doc://com.yababaGmbH.yababa/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.yababaGmbH.yababa\/s23CustomStringConvertibleP"},"doc://com.yababaGmbH.yababa/documentation/Yababa/DeliveryTimeSlotPickerDelegate":{"role":"symbol","title":"DeliveryTimeSlotPickerDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"DeliveryTimeSlotPickerDelegate"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/DeliveryTimeSlotPickerDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DeliveryTimeSlotPickerDelegate"}],"url":"\/documentation\/yababa\/deliverytimeslotpickerdelegate"},"doc://com.yababaGmbH.yababa/documentation/Yababa/CheckoutSceneRouter/DeliveryTimeSlotPickerDelegate-Implementations":{"role":"collectionGroup","title":"DeliveryTimeSlotPickerDelegate Implementations","abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CheckoutSceneRouter\/DeliveryTimeSlotPickerDelegate-Implementations","kind":"article","type":"topic","url":"\/documentation\/yababa\/checkoutscenerouter\/deliverytimeslotpickerdelegate-implementations"},"doc://com.yababaGmbH.yababa/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.yababaGmbH.yababa\/s28CustomDebugStringConvertibleP"},"doc://com.yababaGmbH.yababa/documentation/Yababa/CheckoutSceneRouter/viewController":{"role":"symbol","title":"viewController","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"viewController"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CheckoutSceneViewController","preciseIdentifier":"c:@M@Yababa@objc(cs)CheckoutSceneViewController"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CheckoutSceneRouter\/viewController","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/checkoutscenerouter\/viewcontroller"},"doc://com.yababaGmbH.yababa/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.yababaGmbH.yababa\/s7CVarArgP"},"doc://com.yababaGmbH.yababa/documentation/Yababa/CheckoutSceneRouter/navigateToTimeSlotSelection()":{"role":"symbol","title":"navigateToTimeSlotSelection()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"navigateToTimeSlotSelection"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CheckoutSceneRouter\/navigateToTimeSlotSelection()","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/checkoutscenerouter\/navigatetotimeslotselection()"},"doc://com.yababaGmbH.yababa/documentation/Yababa":{"role":"collection","title":"Yababa","abstract":[{"type":"text","text":"Getting Started"}],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa","kind":"symbol","type":"topic","url":"\/documentation\/yababa"},"doc://com.yababaGmbH.yababa/documentation/Yababa/CheckoutSceneRouter/deallocate()":{"role":"symbol","title":"deallocate()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"deallocate"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CheckoutSceneRouter\/deallocate()","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/checkoutscenerouter\/deallocate()"},"doc://com.yababaGmbH.yababa/documentation/Yababa/CheckoutSceneRouterProtocol":{"role":"symbol","title":"CheckoutSceneRouterProtocol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"CheckoutSceneRouterProtocol"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CheckoutSceneRouterProtocol","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CheckoutSceneRouterProtocol"}],"url":"\/documentation\/yababa\/checkoutscenerouterprotocol"},"doc://com.yababaGmbH.yababa/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)NSObject"},"doc://com.yababaGmbH.yababa/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.yababaGmbH.yababa\/SQ"},"doc://com.yababaGmbH.yababa/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.yababaGmbH.yababa\/SH"},"doc://com.yababaGmbH.yababa/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(cs)NSObject"},"doc://com.yababaGmbH.yababa/documentation/Yababa/CheckoutSceneRouter/navigateToPaymentProcessor(_:subGateway:)":{"role":"symbol","title":"navigateToPaymentProcessor(_:subGateway:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"navigateToPaymentProcessor"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"CheckoutInformation","preciseIdentifier":"s:6Yababa19CheckoutInformationa"},{"kind":"text","text":", "},{"kind":"externalParam","text":"subGateway"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SubGatewayType","preciseIdentifier":"s:6Yababa14SubGatewayTypeO"},{"kind":"text","text":"?)"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CheckoutSceneRouter\/navigateToPaymentProcessor(_:subGateway:)","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/checkoutscenerouter\/navigatetopaymentprocessor(_:subgateway:)"},"doc://com.yababaGmbH.yababa/documentation/Yababa/AddCouponPopupRoutable":{"role":"symbol","title":"AddCouponPopupRoutable","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"AddCouponPopupRoutable"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AddCouponPopupRoutable","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AddCouponPopupRoutable"}],"url":"\/documentation\/yababa\/addcouponpopuproutable"},"doc://com.yababaGmbH.yababa/documentation/Yababa/CheckoutSceneRouter/navigateToCardSelection(creditCards:otherPaymentMethodCards:)":{"role":"symbol","title":"navigateToCardSelection(creditCards:otherPaymentMethodCards:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"navigateToCardSelection"},{"kind":"text","text":"("},{"kind":"externalParam","text":"creditCards"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"CreditCard","preciseIdentifier":"s:6Yababa10CreditCardC"},{"kind":"text","text":"]?, "},{"kind":"externalParam","text":"otherPaymentMethodCards"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"CreditCard","preciseIdentifier":"s:6Yababa10CreditCardC"},{"kind":"text","text":"]?)"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CheckoutSceneRouter\/navigateToCardSelection(creditCards:otherPaymentMethodCards:)","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/checkoutscenerouter\/navigatetocardselection(creditcards:otherpaymentmethodcards:)"},"doc://com.yababaGmbH.yababa/documentation/Yababa/CheckoutSceneRouter":{"role":"symbol","title":"CheckoutSceneRouter","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CheckoutSceneRouter"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CheckoutSceneRouter","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CheckoutSceneRouter"}],"url":"\/documentation\/yababa\/checkoutscenerouter"},"doc://com.yababaGmbH.yababa/documentation/Yababa/CheckoutSceneRouter/navigateToReceiptView(orderId:)":{"role":"symbol","title":"navigateToReceiptView(orderId:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"navigateToReceiptView"},{"kind":"text","text":"("},{"kind":"externalParam","text":"orderId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":"?)"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CheckoutSceneRouter\/navigateToReceiptView(orderId:)","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/checkoutscenerouter\/navigatetoreceiptview(orderid:)"},"doc://com.yababaGmbH.yababa/documentation/Yababa/CheckoutSceneRouter/init":{"role":"symbol","title":"init","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CheckoutSceneRouter\/init","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"init"}],"url":"\/documentation\/yababa\/checkoutscenerouter\/init"},"doc://com.yababaGmbH.yababa/12SkeletonView17AssociatedObjectsP":{"type":"unresolvable","title":"SkeletonView.AssociatedObjects","identifier":"doc:\/\/com.yababaGmbH.yababa\/12SkeletonView17AssociatedObjectsP"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"CheckoutSceneRouter"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"CheckoutSceneRouter"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"CheckoutSceneRouter"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CheckoutSceneRouter\/init"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.yababaGmbH.yababa\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"CheckoutSceneRouter"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1CheckoutSceneRouter\/title","value":"CheckoutSceneRouter"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1CheckoutSceneRouter\/fragments","value":[{"kind":"identifier","text":"CheckoutSceneRouter"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}