{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CollectionViewItemCell"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/yababa\/collectionviewitemcell"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/yababa\/collectionviewitemcell"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.yababaGmbH.yababa\/objc(cs)UICollectionViewCell"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/BannerCollectionViewCell","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/BlockCollectionViewCell","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/BlocksSliderCollectionViewCell","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CatalogueCategoryCollectionViewCell","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/DropdownCollectionCell","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/InfoTextCollectionViewCell","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/OrderInProgressCell","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ProductCollectionCell","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ReferralCollectionViewCell","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/StaticBlocksCollectionViewCell","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/VoucherCollectionViewCell"],"kind":"relationships","title":"Inherited By","type":"inheritedBy"},{"identifiers":["doc:\/\/com.yababaGmbH.yababa\/objc(pl)NSCoding","doc:\/\/com.yababaGmbH.yababa\/objc(pl)NSObject","doc:\/\/com.yababaGmbH.yababa\/objc(pl)CALayerDelegate","doc:\/\/com.yababaGmbH.yababa\/12SkeletonView17AssociatedObjectsP","doc:\/\/com.yababaGmbH.yababa\/12SkeletonView15IterableElementP","doc:\/\/com.yababaGmbH.yababa\/12SkeletonView11RecoverableP","doc:\/\/com.yababaGmbH.yababa\/12SkeletonView0A12ReusableCellP","doc:\/\/com.yababaGmbH.yababa\/6Stripe19SafeAreaLayoutGuideP","doc:\/\/com.yababaGmbH.yababa\/s7CVarArgP","doc:\/\/com.yababaGmbH.yababa\/s28CustomDebugStringConvertibleP","doc:\/\/com.yababaGmbH.yababa\/s23CustomStringConvertibleP","doc:\/\/com.yababaGmbH.yababa\/SQ","doc:\/\/com.yababaGmbH.yababa\/SH","doc:\/\/com.yababaGmbH.yababa\/s8SendableP","doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIAccessibilityIdentification","doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIActivityItemsConfigurationProviding","doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIAppearance","doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIAppearanceContainer","doc:\/\/com.yababaGmbH.yababa\/objc(pl)UICoordinateSpace","doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIDynamicItem","doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIFocusEnvironment","doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIFocusItem","doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIFocusItemContainer","doc:\/\/com.yababaGmbH.yababa\/objc(pl)UILargeContentViewerItem","doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIPasteConfigurationSupporting","doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIPopoverPresentationControllerSourceItem","doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIResponderStandardEditActions","doc:\/\/com.yababaGmbH.yababa\/objc(pl)UITraitEnvironment","doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIUserActivityRestoring","doc:\/\/com.yababaGmbH.yababa\/22ZendeskSDKUIComponents28UICollectionReusableViewTypeP"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CollectionViewItemCell","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CollectionViewItemCell\/containerView","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CollectionViewItemCell\/coverImage","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CollectionViewItemCell\/gradientImage","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CollectionViewItemCell\/infoLabel","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CollectionViewItemCell\/miniTitleLabel","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CollectionViewItemCell\/subtitleLabel","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CollectionViewItemCell\/titleLabel"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CollectionViewItemCell\/markAsSeen(containerContentOffset:)","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CollectionViewItemCell\/onSubAction()","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CollectionViewItemCell\/setIdentifiers(_:)","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CollectionViewItemCell\/setImage(imageURL:)","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CollectionViewItemCell\/setInfoTitle(_:)","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CollectionViewItemCell\/setItem(_:)","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CollectionViewItemCell\/setMiniTitle(_:)","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CollectionViewItemCell\/setSubtitle(_:)","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CollectionViewItemCell\/setTitle(_:)"]}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CollectionViewItemCell"}],"title":"CollectionViewItemCell","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@Yababa@objc(cs)CollectionViewItemCell","modules":[{"name":"Yababa"}],"navigatorTitle":[{"kind":"identifier","text":"CollectionViewItemCell"}]},"hierarchy":{"paths":[["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa"]]},"references":{"doc://com.yababaGmbH.yababa/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.yababaGmbH.yababa\/s7CVarArgP"},"doc://com.yababaGmbH.yababa/12SkeletonView11RecoverableP":{"type":"unresolvable","title":"SkeletonView.Recoverable","identifier":"doc:\/\/com.yababaGmbH.yababa\/12SkeletonView11RecoverableP"},"doc://com.yababaGmbH.yababa/documentation/Yababa/CollectionViewItemCell":{"role":"symbol","title":"CollectionViewItemCell","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CollectionViewItemCell"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CollectionViewItemCell","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CollectionViewItemCell"}],"url":"\/documentation\/yababa\/collectionviewitemcell"},"doc://com.yababaGmbH.yababa/documentation/Yababa/CollectionViewItemCell/setTitle(_:)":{"role":"symbol","title":"setTitle(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setTitle"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?)"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CollectionViewItemCell\/setTitle(_:)","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/collectionviewitemcell\/settitle(_:)"},"doc://com.yababaGmbH.yababa/objc(pl)NSCoding":{"type":"unresolvable","title":"Foundation.NSCoding","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)NSCoding"},"doc://com.yababaGmbH.yababa/objc(pl)UIUserActivityRestoring":{"type":"unresolvable","title":"UIKit.UIUserActivityRestoring","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIUserActivityRestoring"},"doc://com.yababaGmbH.yababa/documentation/Yababa/CollectionViewItemCell/titleLabel":{"role":"symbol","title":"titleLabel","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"titleLabel"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UILabel","preciseIdentifier":"c:objc(cs)UILabel"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CollectionViewItemCell\/titleLabel","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"titleLabel"}],"url":"\/documentation\/yababa\/collectionviewitemcell\/titlelabel"},"doc://com.yababaGmbH.yababa/objc(pl)UICoordinateSpace":{"type":"unresolvable","title":"UIKit.UICoordinateSpace","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)UICoordinateSpace"},"doc://com.yababaGmbH.yababa/objc(pl)UIActivityItemsConfigurationProviding":{"type":"unresolvable","title":"UIKit.UIActivityItemsConfigurationProviding","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIActivityItemsConfigurationProviding"},"doc://com.yababaGmbH.yababa/documentation/Yababa/ReferralCollectionViewCell":{"role":"symbol","title":"ReferralCollectionViewCell","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ReferralCollectionViewCell"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ReferralCollectionViewCell","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ReferralCollectionViewCell"}],"url":"\/documentation\/yababa\/referralcollectionviewcell"},"doc://com.yababaGmbH.yababa/documentation/Yababa/CollectionViewItemCell/infoLabel":{"role":"symbol","title":"infoLabel","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"infoLabel"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UILabel","preciseIdentifier":"c:objc(cs)UILabel"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CollectionViewItemCell\/infoLabel","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"infoLabel"}],"url":"\/documentation\/yababa\/collectionviewitemcell\/infolabel"},"doc://com.yababaGmbH.yababa/documentation/Yababa/CollectionViewItemCell/setImage(imageURL:)":{"role":"symbol","title":"setImage(imageURL:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setImage"},{"kind":"text","text":"("},{"kind":"externalParam","text":"imageURL"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"URL","preciseIdentifier":"s:10Foundation3URLV"},{"kind":"text","text":"?)"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CollectionViewItemCell\/setImage(imageURL:)","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/collectionviewitemcell\/setimage(imageurl:)"},"doc://com.yababaGmbH.yababa/documentation/Yababa/StaticBlocksCollectionViewCell":{"role":"symbol","title":"StaticBlocksCollectionViewCell","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"StaticBlocksCollectionViewCell"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/StaticBlocksCollectionViewCell","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"StaticBlocksCollectionViewCell"}],"url":"\/documentation\/yababa\/staticblockscollectionviewcell"},"doc://com.yababaGmbH.yababa/documentation/Yababa/OrderInProgressCell":{"role":"symbol","title":"OrderInProgressCell","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"OrderInProgressCell"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/OrderInProgressCell","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"OrderInProgressCell"}],"url":"\/documentation\/yababa\/orderinprogresscell"},"doc://com.yababaGmbH.yababa/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)NSObject"},"doc://com.yababaGmbH.yababa/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.yababaGmbH.yababa\/s23CustomStringConvertibleP"},"doc://com.yababaGmbH.yababa/objc(pl)UIDynamicItem":{"type":"unresolvable","title":"UIKit.UIDynamicItem","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIDynamicItem"},"doc://com.yababaGmbH.yababa/documentation/Yababa/CollectionViewItemCell/gradientImage":{"role":"symbol","title":"gradientImage","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"gradientImage"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIImageView","preciseIdentifier":"c:objc(cs)UIImageView"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CollectionViewItemCell\/gradientImage","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"gradientImage"}],"url":"\/documentation\/yababa\/collectionviewitemcell\/gradientimage"},"doc://com.yababaGmbH.yababa/documentation/Yababa/CollectionViewItemCell/subtitleLabel":{"role":"symbol","title":"subtitleLabel","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"subtitleLabel"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UILabel","preciseIdentifier":"c:objc(cs)UILabel"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CollectionViewItemCell\/subtitleLabel","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"subtitleLabel"}],"url":"\/documentation\/yababa\/collectionviewitemcell\/subtitlelabel"},"doc://com.yababaGmbH.yababa/documentation/Yababa/BlocksSliderCollectionViewCell":{"role":"symbol","title":"BlocksSliderCollectionViewCell","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"BlocksSliderCollectionViewCell"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/BlocksSliderCollectionViewCell","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"BlocksSliderCollectionViewCell"}],"url":"\/documentation\/yababa\/blocksslidercollectionviewcell"},"doc://com.yababaGmbH.yababa/documentation/Yababa/ProductCollectionCell":{"role":"symbol","title":"ProductCollectionCell","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ProductCollectionCell"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ProductCollectionCell","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ProductCollectionCell"}],"url":"\/documentation\/yababa\/productcollectioncell"},"doc://com.yababaGmbH.yababa/objc(cs)UICollectionViewCell":{"type":"unresolvable","title":"UICollectionViewCell","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(cs)UICollectionViewCell"},"doc://com.yababaGmbH.yababa/objc(pl)UILargeContentViewerItem":{"type":"unresolvable","title":"UIKit.UILargeContentViewerItem","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)UILargeContentViewerItem"},"doc://com.yababaGmbH.yababa/objc(pl)UIAppearanceContainer":{"type":"unresolvable","title":"UIKit.UIAppearanceContainer","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIAppearanceContainer"},"doc://com.yababaGmbH.yababa/documentation/Yababa/CollectionViewItemCell/setInfoTitle(_:)":{"role":"symbol","title":"setInfoTitle(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setInfoTitle"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?)"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CollectionViewItemCell\/setInfoTitle(_:)","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/collectionviewitemcell\/setinfotitle(_:)"},"doc://com.yababaGmbH.yababa/documentation/Yababa/CollectionViewItemCell/containerView":{"role":"symbol","title":"containerView","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"containerView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CollectionViewItemCell\/containerView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"containerView"}],"url":"\/documentation\/yababa\/collectionviewitemcell\/containerview"},"doc://com.yababaGmbH.yababa/documentation/Yababa/CollectionViewItemCell/coverImage":{"role":"symbol","title":"coverImage","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"coverImage"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIImageView","preciseIdentifier":"c:objc(cs)UIImageView"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CollectionViewItemCell\/coverImage","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"coverImage"}],"url":"\/documentation\/yababa\/collectionviewitemcell\/coverimage"},"doc://com.yababaGmbH.yababa/objc(pl)UIAccessibilityIdentification":{"type":"unresolvable","title":"UIKit.UIAccessibilityIdentification","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIAccessibilityIdentification"},"doc://com.yababaGmbH.yababa/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.yababaGmbH.yababa\/SQ"},"doc://com.yababaGmbH.yababa/documentation/Yababa/VoucherCollectionViewCell":{"role":"symbol","title":"VoucherCollectionViewCell","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"VoucherCollectionViewCell"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/VoucherCollectionViewCell","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"VoucherCollectionViewCell"}],"url":"\/documentation\/yababa\/vouchercollectionviewcell"},"doc://com.yababaGmbH.yababa/documentation/Yababa/CollectionViewItemCell/onSubAction()":{"role":"symbol","title":"onSubAction()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onSubAction"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CollectionViewItemCell\/onSubAction()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"onSubAction"}],"url":"\/documentation\/yababa\/collectionviewitemcell\/onsubaction()"},"doc://com.yababaGmbH.yababa/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.yababaGmbH.yababa\/SH"},"doc://com.yababaGmbH.yababa/objc(pl)UIFocusItem":{"type":"unresolvable","title":"UIKit.UIFocusItem","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIFocusItem"},"doc://com.yababaGmbH.yababa/documentation/Yababa/CollectionViewItemCell/setIdentifiers(_:)":{"role":"symbol","title":"setIdentifiers(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setIdentifiers"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"ScreenItem","preciseIdentifier":"s:6Yababa10ScreenItemC"},{"kind":"text","text":"?)"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CollectionViewItemCell\/setIdentifiers(_:)","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/collectionviewitemcell\/setidentifiers(_:)"},"doc://com.yababaGmbH.yababa/documentation/Yababa":{"role":"collection","title":"Yababa","abstract":[{"type":"text","text":"Getting Started"}],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa","kind":"symbol","type":"topic","url":"\/documentation\/yababa"},"doc://com.yababaGmbH.yababa/documentation/Yababa/CollectionViewItemCell/setMiniTitle(_:)":{"role":"symbol","title":"setMiniTitle(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setMiniTitle"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?)"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CollectionViewItemCell\/setMiniTitle(_:)","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/collectionviewitemcell\/setminititle(_:)"},"doc://com.yababaGmbH.yababa/objc(pl)UIPasteConfigurationSupporting":{"type":"unresolvable","title":"UIKit.UIPasteConfigurationSupporting","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIPasteConfigurationSupporting"},"doc://com.yababaGmbH.yababa/objc(pl)UIResponderStandardEditActions":{"type":"unresolvable","title":"UIKit.UIResponderStandardEditActions","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIResponderStandardEditActions"},"doc://com.yababaGmbH.yababa/documentation/Yababa/CollectionViewItemCell/markAsSeen(containerContentOffset:)":{"role":"symbol","title":"markAsSeen(containerContentOffset:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"markAsSeen"},{"kind":"text","text":"("},{"kind":"externalParam","text":"containerContentOffset"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGPoint","preciseIdentifier":"c:@S@CGPoint"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CollectionViewItemCell\/markAsSeen(containerContentOffset:)","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/collectionviewitemcell\/markasseen(containercontentoffset:)"},"doc://com.yababaGmbH.yababa/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.yababaGmbH.yababa\/s28CustomDebugStringConvertibleP"},"doc://com.yababaGmbH.yababa/documentation/Yababa/BannerCollectionViewCell":{"role":"symbol","title":"BannerCollectionViewCell","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"BannerCollectionViewCell"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/BannerCollectionViewCell","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"BannerCollectionViewCell"}],"url":"\/documentation\/yababa\/bannercollectionviewcell"},"doc://com.yababaGmbH.yababa/documentation/Yababa/CollectionViewItemCell/setSubtitle(_:)":{"role":"symbol","title":"setSubtitle(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setSubtitle"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?)"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CollectionViewItemCell\/setSubtitle(_:)","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/collectionviewitemcell\/setsubtitle(_:)"},"doc://com.yababaGmbH.yababa/documentation/Yababa/CollectionViewItemCell/miniTitleLabel":{"role":"symbol","title":"miniTitleLabel","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"miniTitleLabel"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UILabel","preciseIdentifier":"c:objc(cs)UILabel"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CollectionViewItemCell\/miniTitleLabel","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"miniTitleLabel"}],"url":"\/documentation\/yababa\/collectionviewitemcell\/minititlelabel"},"doc://com.yababaGmbH.yababa/documentation/Yababa/InfoTextCollectionViewCell":{"role":"symbol","title":"InfoTextCollectionViewCell","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"InfoTextCollectionViewCell"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/InfoTextCollectionViewCell","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"InfoTextCollectionViewCell"}],"url":"\/documentation\/yababa\/infotextcollectionviewcell"},"doc://com.yababaGmbH.yababa/12SkeletonView15IterableElementP":{"type":"unresolvable","title":"SkeletonView.IterableElement","identifier":"doc:\/\/com.yababaGmbH.yababa\/12SkeletonView15IterableElementP"},"doc://com.yababaGmbH.yababa/documentation/Yababa/CollectionViewItemCell/setItem(_:)":{"role":"symbol","title":"setItem(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setItem"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"ScreenItem","preciseIdentifier":"s:6Yababa10ScreenItemC"},{"kind":"text","text":"?)"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CollectionViewItemCell\/setItem(_:)","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/collectionviewitemcell\/setitem(_:)"},"doc://com.yababaGmbH.yababa/objc(pl)CALayerDelegate":{"type":"unresolvable","title":"QuartzCore.CALayerDelegate","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)CALayerDelegate"},"doc://com.yababaGmbH.yababa/documentation/Yababa/CollectionViewItemCell/initWithCoder:":{"role":"symbol","title":"initWithCoder:","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithCoder:"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CollectionViewItemCell\/initWithCoder:","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithCoder:"}],"url":"\/documentation\/yababa\/collectionviewitemcell\/initwithcoder:"},"doc://com.yababaGmbH.yababa/objc(pl)UIPopoverPresentationControllerSourceItem":{"type":"unresolvable","title":"UIKit.UIPopoverPresentationControllerSourceItem","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIPopoverPresentationControllerSourceItem"},"doc://com.yababaGmbH.yababa/12SkeletonView0A12ReusableCellP":{"type":"unresolvable","title":"SkeletonView.SkeletonReusableCell","identifier":"doc:\/\/com.yababaGmbH.yababa\/12SkeletonView0A12ReusableCellP"},"doc://com.yababaGmbH.yababa/12SkeletonView17AssociatedObjectsP":{"type":"unresolvable","title":"SkeletonView.AssociatedObjects","identifier":"doc:\/\/com.yababaGmbH.yababa\/12SkeletonView17AssociatedObjectsP"},"doc://com.yababaGmbH.yababa/objc(pl)UIFocusItemContainer":{"type":"unresolvable","title":"UIKit.UIFocusItemContainer","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIFocusItemContainer"},"doc://com.yababaGmbH.yababa/objc(pl)UIFocusEnvironment":{"type":"unresolvable","title":"UIKit.UIFocusEnvironment","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIFocusEnvironment"},"doc://com.yababaGmbH.yababa/documentation/Yababa/CatalogueCategoryCollectionViewCell":{"role":"symbol","title":"CatalogueCategoryCollectionViewCell","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CatalogueCategoryCollectionViewCell"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CatalogueCategoryCollectionViewCell","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CatalogueCategoryCollectionViewCell"}],"url":"\/documentation\/yababa\/cataloguecategorycollectionviewcell"},"doc://com.yababaGmbH.yababa/objc(pl)UIAppearance":{"type":"unresolvable","title":"UIKit.UIAppearance","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIAppearance"},"doc://com.yababaGmbH.yababa/documentation/Yababa/DropdownCollectionCell":{"role":"symbol","title":"DropdownCollectionCell","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DropdownCollectionCell"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/DropdownCollectionCell","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DropdownCollectionCell"}],"url":"\/documentation\/yababa\/dropdowncollectioncell"},"doc://com.yababaGmbH.yababa/objc(pl)UITraitEnvironment":{"type":"unresolvable","title":"UIKit.UITraitEnvironment","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)UITraitEnvironment"},"doc://com.yababaGmbH.yababa/documentation/Yababa/BlockCollectionViewCell":{"role":"symbol","title":"BlockCollectionViewCell","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"BlockCollectionViewCell"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/BlockCollectionViewCell","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"BlockCollectionViewCell"}],"url":"\/documentation\/yababa\/blockcollectionviewcell"},"doc://com.yababaGmbH.yababa/6Stripe19SafeAreaLayoutGuideP":{"type":"unresolvable","title":"Stripe.SafeAreaLayoutGuide","identifier":"doc:\/\/com.yababaGmbH.yababa\/6Stripe19SafeAreaLayoutGuideP"},"doc://com.yababaGmbH.yababa/22ZendeskSDKUIComponents28UICollectionReusableViewTypeP":{"type":"unresolvable","title":"ZendeskSDKUIComponents.UICollectionReusableViewType","identifier":"doc:\/\/com.yababaGmbH.yababa\/22ZendeskSDKUIComponents28UICollectionReusableViewTypeP"},"doc://com.yababaGmbH.yababa/documentation/Yababa/CollectionViewItemCell/initWithFrame:":{"role":"symbol","title":"initWithFrame:","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithFrame:"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CollectionViewItemCell\/initWithFrame:","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithFrame:"}],"url":"\/documentation\/yababa\/collectionviewitemcell\/initwithframe:"},"doc://com.yababaGmbH.yababa/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/com.yababaGmbH.yababa\/s8SendableP"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"CollectionViewItemCell"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"CollectionViewItemCell"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"CollectionViewItemCell"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CollectionViewItemCell\/containerView","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CollectionViewItemCell\/coverImage","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CollectionViewItemCell\/gradientImage","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CollectionViewItemCell\/infoLabel","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CollectionViewItemCell\/miniTitleLabel","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CollectionViewItemCell\/subtitleLabel","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CollectionViewItemCell\/titleLabel"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CollectionViewItemCell\/initWithCoder:","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CollectionViewItemCell\/initWithFrame:","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CollectionViewItemCell\/onSubAction()"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.yababaGmbH.yababa\/objc(cs)UICollectionViewCell"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/BannerCollectionViewCell","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/BlockCollectionViewCell","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/BlocksSliderCollectionViewCell","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CatalogueCategoryCollectionViewCell","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/DropdownCollectionCell","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/InfoTextCollectionViewCell","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/OrderInProgressCell","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ProductCollectionCell","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ReferralCollectionViewCell","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/StaticBlocksCollectionViewCell","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/VoucherCollectionViewCell"],"kind":"relationships","title":"Inherited By","type":"inheritedBy"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"CollectionViewItemCell"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"UICollectionViewCell","preciseIdentifier":"c:objc(cs)UICollectionViewCell"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1CollectionViewItemCell\/title","value":"CollectionViewItemCell"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1CollectionViewItemCell\/fragments","value":[{"kind":"identifier","text":"CollectionViewItemCell"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1CollectionViewItemCell~1titleLabel\/title","value":"titleLabel"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1CollectionViewItemCell~1titleLabel\/fragments","value":[{"kind":"identifier","text":"titleLabel"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1ReferralCollectionViewCell\/title","value":"ReferralCollectionViewCell"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1ReferralCollectionViewCell\/fragments","value":[{"kind":"identifier","text":"ReferralCollectionViewCell"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1CollectionViewItemCell~1infoLabel\/title","value":"infoLabel"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1CollectionViewItemCell~1infoLabel\/fragments","value":[{"kind":"identifier","text":"infoLabel"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1StaticBlocksCollectionViewCell\/title","value":"StaticBlocksCollectionViewCell"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1StaticBlocksCollectionViewCell\/fragments","value":[{"kind":"identifier","text":"StaticBlocksCollectionViewCell"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1OrderInProgressCell\/title","value":"OrderInProgressCell"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1OrderInProgressCell\/fragments","value":[{"kind":"identifier","text":"OrderInProgressCell"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1CollectionViewItemCell~1gradientImage\/title","value":"gradientImage"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1CollectionViewItemCell~1gradientImage\/fragments","value":[{"kind":"identifier","text":"gradientImage"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1CollectionViewItemCell~1subtitleLabel\/title","value":"subtitleLabel"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1CollectionViewItemCell~1subtitleLabel\/fragments","value":[{"kind":"identifier","text":"subtitleLabel"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1BlocksSliderCollectionViewCell\/title","value":"BlocksSliderCollectionViewCell"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1BlocksSliderCollectionViewCell\/fragments","value":[{"kind":"identifier","text":"BlocksSliderCollectionViewCell"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1ProductCollectionCell\/title","value":"ProductCollectionCell"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1ProductCollectionCell\/fragments","value":[{"kind":"identifier","text":"ProductCollectionCell"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1CollectionViewItemCell~1containerView\/title","value":"containerView"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1CollectionViewItemCell~1containerView\/fragments","value":[{"kind":"identifier","text":"containerView"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1CollectionViewItemCell~1coverImage\/title","value":"coverImage"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1CollectionViewItemCell~1coverImage\/fragments","value":[{"kind":"identifier","text":"coverImage"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1VoucherCollectionViewCell\/title","value":"VoucherCollectionViewCell"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1VoucherCollectionViewCell\/fragments","value":[{"kind":"identifier","text":"VoucherCollectionViewCell"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1CollectionViewItemCell~1onSubAction()\/title","value":"onSubAction"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1CollectionViewItemCell~1onSubAction()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onSubAction"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1BannerCollectionViewCell\/title","value":"BannerCollectionViewCell"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1BannerCollectionViewCell\/fragments","value":[{"kind":"identifier","text":"BannerCollectionViewCell"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1CollectionViewItemCell~1miniTitleLabel\/title","value":"miniTitleLabel"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1CollectionViewItemCell~1miniTitleLabel\/fragments","value":[{"kind":"identifier","text":"miniTitleLabel"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1InfoTextCollectionViewCell\/title","value":"InfoTextCollectionViewCell"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1InfoTextCollectionViewCell\/fragments","value":[{"kind":"identifier","text":"InfoTextCollectionViewCell"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1CatalogueCategoryCollectionViewCell\/title","value":"CatalogueCategoryCollectionViewCell"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1CatalogueCategoryCollectionViewCell\/fragments","value":[{"kind":"identifier","text":"CatalogueCategoryCollectionViewCell"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1DropdownCollectionCell\/title","value":"DropdownCollectionCell"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1DropdownCollectionCell\/fragments","value":[{"kind":"identifier","text":"DropdownCollectionCell"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1BlockCollectionViewCell\/title","value":"BlockCollectionViewCell"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1BlockCollectionViewCell\/fragments","value":[{"kind":"identifier","text":"BlockCollectionViewCell"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}