{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CompleteProfileSceneViewController"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/yababa\/completeprofilesceneviewcontroller"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/yababa\/completeprofilesceneviewcontroller"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/MasterViewController"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CompleteProfileSceneViewControllerProtocol","doc:\/\/com.yababaGmbH.yababa\/objc(pl)NSCoding","doc:\/\/com.yababaGmbH.yababa\/objc(pl)NSExtensionRequestHandling","doc:\/\/com.yababaGmbH.yababa\/objc(pl)NSObject","doc:\/\/com.yababaGmbH.yababa\/12SkeletonView17AssociatedObjectsP","doc:\/\/com.yababaGmbH.yababa\/s7CVarArgP","doc:\/\/com.yababaGmbH.yababa\/s28CustomDebugStringConvertibleP","doc:\/\/com.yababaGmbH.yababa\/s23CustomStringConvertibleP","doc:\/\/com.yababaGmbH.yababa\/SQ","doc:\/\/com.yababaGmbH.yababa\/SH","doc:\/\/com.yababaGmbH.yababa\/s8SendableP","doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIActivityItemsConfigurationProviding","doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIAppearanceContainer","doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIContentContainer","doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIFocusEnvironment","doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIPasteConfigurationSupporting","doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIResponderStandardEditActions","doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIStateRestoring","doc:\/\/com.yababaGmbH.yababa\/objc(pl)UITraitEnvironment","doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIUserActivityRestoring"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CompleteProfileSceneViewController","interfaceLanguage":"swift"},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CompleteProfileSceneViewController\/init(coder:)","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CompleteProfileSceneViewController\/init(delegate:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CompleteProfileSceneViewController\/firstNameTextField","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CompleteProfileSceneViewController\/interactor","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CompleteProfileSceneViewController\/lastNameTextField","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CompleteProfileSceneViewController\/nameStackView","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CompleteProfileSceneViewController\/nextBtn","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CompleteProfileSceneViewController\/phoneStackView","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CompleteProfileSceneViewController\/phoneTextField","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CompleteProfileSceneViewController\/router","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CompleteProfileSceneViewController\/smallSpinner","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CompleteProfileSceneViewController\/subTitleLabel"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CompleteProfileSceneViewController\/getFormattedPhoneNumber()","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CompleteProfileSceneViewController\/onDonePhoneTextfield()","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CompleteProfileSceneViewController\/onNext()","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CompleteProfileSceneViewController\/viewDidLoad()"]},{"title":"Default Implementations","identifiers":["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CompleteProfileSceneViewController\/CompleteProfileSceneViewControllerProtocol-Implementations"],"generated":true}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CompleteProfileSceneViewController"}],"title":"CompleteProfileSceneViewController","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@Yababa@objc(cs)CompleteProfileSceneViewController","modules":[{"name":"Yababa"}],"navigatorTitle":[{"kind":"identifier","text":"CompleteProfileSceneViewController"}]},"hierarchy":{"paths":[["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa"]]},"references":{"doc://com.yababaGmbH.yababa/documentation/Yababa/CompleteProfileSceneViewController/router":{"role":"symbol","title":"router","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"router"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CompleteProfileSceneRouterProtocol","preciseIdentifier":"s:6Yababa34CompleteProfileSceneRouterProtocolP"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CompleteProfileSceneViewController\/router","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/completeprofilesceneviewcontroller\/router"},"doc://com.yababaGmbH.yababa/objc(pl)UIUserActivityRestoring":{"type":"unresolvable","title":"UIKit.UIUserActivityRestoring","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIUserActivityRestoring"},"doc://com.yababaGmbH.yababa/documentation/Yababa/CompleteProfileSceneViewController/onDonePhoneTextfield()":{"role":"symbol","title":"onDonePhoneTextfield()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onDonePhoneTextfield"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CompleteProfileSceneViewController\/onDonePhoneTextfield()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"onDonePhoneTextfield"}],"url":"\/documentation\/yababa\/completeprofilesceneviewcontroller\/ondonephonetextfield()"},"doc://com.yababaGmbH.yababa/documentation/Yababa/CompleteProfileSceneViewController/viewDidLoad()":{"role":"symbol","title":"viewDidLoad()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"viewDidLoad"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CompleteProfileSceneViewController\/viewDidLoad()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"viewDidLoad"}],"url":"\/documentation\/yababa\/completeprofilesceneviewcontroller\/viewdidload()"},"doc://com.yababaGmbH.yababa/documentation/Yababa/CompleteProfileSceneViewController/interactor":{"role":"symbol","title":"interactor","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"interactor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CompleteProfileSceneInteractorProtocol","preciseIdentifier":"s:6Yababa38CompleteProfileSceneInteractorProtocolP"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CompleteProfileSceneViewController\/interactor","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/completeprofilesceneviewcontroller\/interactor"},"doc://com.yababaGmbH.yababa/documentation/Yababa/CompleteProfileSceneViewController/getFormattedPhoneNumber()":{"role":"symbol","title":"getFormattedPhoneNumber()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getFormattedPhoneNumber"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CompleteProfileSceneViewController\/getFormattedPhoneNumber()","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/completeprofilesceneviewcontroller\/getformattedphonenumber()"},"doc://com.yababaGmbH.yababa/objc(pl)UIFocusEnvironment":{"type":"unresolvable","title":"UIKit.UIFocusEnvironment","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIFocusEnvironment"},"doc://com.yababaGmbH.yababa/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)NSObject"},"doc://com.yababaGmbH.yababa/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.yababaGmbH.yababa\/s23CustomStringConvertibleP"},"doc://com.yababaGmbH.yababa/objc(pl)UIAppearanceContainer":{"type":"unresolvable","title":"UIKit.UIAppearanceContainer","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIAppearanceContainer"},"doc://com.yababaGmbH.yababa/objc(pl)UIPasteConfigurationSupporting":{"type":"unresolvable","title":"UIKit.UIPasteConfigurationSupporting","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIPasteConfigurationSupporting"},"doc://com.yababaGmbH.yababa/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.yababaGmbH.yababa\/s28CustomDebugStringConvertibleP"},"doc://com.yababaGmbH.yababa/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/com.yababaGmbH.yababa\/s8SendableP"},"doc://com.yababaGmbH.yababa/documentation/Yababa":{"role":"collection","title":"Yababa","abstract":[{"type":"text","text":"Getting Started"}],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa","kind":"symbol","type":"topic","url":"\/documentation\/yababa"},"doc://com.yababaGmbH.yababa/documentation/Yababa/CompleteProfileSceneViewController/phoneStackView":{"role":"symbol","title":"phoneStackView","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"phoneStackView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CompleteProfileSceneViewController\/phoneStackView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"phoneStackView"}],"url":"\/documentation\/yababa\/completeprofilesceneviewcontroller\/phonestackview"},"doc://com.yababaGmbH.yababa/objc(pl)NSExtensionRequestHandling":{"type":"unresolvable","title":"Foundation.NSExtensionRequestHandling","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)NSExtensionRequestHandling"},"doc://com.yababaGmbH.yababa/objc(pl)UIResponderStandardEditActions":{"type":"unresolvable","title":"UIKit.UIResponderStandardEditActions","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIResponderStandardEditActions"},"doc://com.yababaGmbH.yababa/documentation/Yababa/CompleteProfileSceneViewController/onNext()":{"role":"symbol","title":"onNext()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onNext"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CompleteProfileSceneViewController\/onNext()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"onNext"}],"url":"\/documentation\/yababa\/completeprofilesceneviewcontroller\/onnext()"},"doc://com.yababaGmbH.yababa/documentation/Yababa/MasterViewController":{"role":"symbol","title":"MasterViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MasterViewController"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/MasterViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MasterViewController"}],"url":"\/documentation\/yababa\/masterviewcontroller"},"doc://com.yababaGmbH.yababa/documentation/Yababa/CompleteProfileSceneViewController/smallSpinner":{"role":"symbol","title":"smallSpinner","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"smallSpinner"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIActivityIndicatorView","preciseIdentifier":"c:objc(cs)UIActivityIndicatorView"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CompleteProfileSceneViewController\/smallSpinner","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"smallSpinner"}],"url":"\/documentation\/yababa\/completeprofilesceneviewcontroller\/smallspinner"},"doc://com.yababaGmbH.yababa/documentation/Yababa/CompleteProfileSceneViewController/subTitleLabel":{"role":"symbol","title":"subTitleLabel","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"subTitleLabel"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UILabel","preciseIdentifier":"c:objc(cs)UILabel"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CompleteProfileSceneViewController\/subTitleLabel","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"subTitleLabel"}],"url":"\/documentation\/yababa\/completeprofilesceneviewcontroller\/subtitlelabel"},"doc://com.yababaGmbH.yababa/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.yababaGmbH.yababa\/s7CVarArgP"},"doc://com.yababaGmbH.yababa/objc(pl)UIStateRestoring":{"type":"unresolvable","title":"UIKit.UIStateRestoring","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIStateRestoring"},"doc://com.yababaGmbH.yababa/objc(pl)UITraitEnvironment":{"type":"unresolvable","title":"UIKit.UITraitEnvironment","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)UITraitEnvironment"},"doc://com.yababaGmbH.yababa/documentation/Yababa/CompleteProfileSceneViewController/init(delegate:)":{"role":"symbol","title":"init(delegate:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"delegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CompleteProfileVCDelegate","preciseIdentifier":"s:6Yababa25CompleteProfileVCDelegateP"},{"kind":"text","text":"?)"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CompleteProfileSceneViewController\/init(delegate:)","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/completeprofilesceneviewcontroller\/init(delegate:)"},"doc://com.yababaGmbH.yababa/documentation/Yababa/CompleteProfileSceneViewController/firstNameTextField":{"role":"symbol","title":"firstNameTextField","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"firstNameTextField"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UITextField","preciseIdentifier":"c:objc(cs)UITextField"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CompleteProfileSceneViewController\/firstNameTextField","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"firstNameTextField"}],"url":"\/documentation\/yababa\/completeprofilesceneviewcontroller\/firstnametextfield"},"doc://com.yababaGmbH.yababa/documentation/Yababa/CompleteProfileSceneViewController":{"role":"symbol","title":"CompleteProfileSceneViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CompleteProfileSceneViewController"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CompleteProfileSceneViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CompleteProfileSceneViewController"}],"url":"\/documentation\/yababa\/completeprofilesceneviewcontroller"},"doc://com.yababaGmbH.yababa/documentation/Yababa/CompleteProfileSceneViewController/init(coder:)":{"role":"symbol","title":"init(coder:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"coder"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSCoder","preciseIdentifier":"c:objc(cs)NSCoder"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CompleteProfileSceneViewController\/init(coder:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithCoder:"}],"url":"\/documentation\/yababa\/completeprofilesceneviewcontroller\/init(coder:)"},"doc://com.yababaGmbH.yababa/objc(pl)NSCoding":{"type":"unresolvable","title":"Foundation.NSCoding","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)NSCoding"},"doc://com.yababaGmbH.yababa/documentation/Yababa/CompleteProfileSceneViewController/lastNameTextField":{"role":"symbol","title":"lastNameTextField","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"lastNameTextField"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UITextField","preciseIdentifier":"c:objc(cs)UITextField"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CompleteProfileSceneViewController\/lastNameTextField","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"lastNameTextField"}],"url":"\/documentation\/yababa\/completeprofilesceneviewcontroller\/lastnametextfield"},"doc://com.yababaGmbH.yababa/documentation/Yababa/CompleteProfileSceneViewController/nextBtn":{"role":"symbol","title":"nextBtn","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"nextBtn"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIButton","preciseIdentifier":"c:objc(cs)UIButton"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CompleteProfileSceneViewController\/nextBtn","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"nextBtn"}],"url":"\/documentation\/yababa\/completeprofilesceneviewcontroller\/nextbtn"},"doc://com.yababaGmbH.yababa/documentation/Yababa/CompleteProfileSceneViewController/nameStackView":{"role":"symbol","title":"nameStackView","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"nameStackView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIStackView","preciseIdentifier":"c:objc(cs)UIStackView"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CompleteProfileSceneViewController\/nameStackView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"nameStackView"}],"url":"\/documentation\/yababa\/completeprofilesceneviewcontroller\/namestackview"},"doc://com.yababaGmbH.yababa/documentation/Yababa/CompleteProfileSceneViewController/CompleteProfileSceneViewControllerProtocol-Implementations":{"role":"collectionGroup","title":"CompleteProfileSceneViewControllerProtocol Implementations","abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CompleteProfileSceneViewController\/CompleteProfileSceneViewControllerProtocol-Implementations","kind":"article","type":"topic","url":"\/documentation\/yababa\/completeprofilesceneviewcontroller\/completeprofilesceneviewcontrollerprotocol-implementations"},"doc://com.yababaGmbH.yababa/12SkeletonView17AssociatedObjectsP":{"type":"unresolvable","title":"SkeletonView.AssociatedObjects","identifier":"doc:\/\/com.yababaGmbH.yababa\/12SkeletonView17AssociatedObjectsP"},"doc://com.yababaGmbH.yababa/documentation/Yababa/CompleteProfileSceneViewController/phoneTextField":{"role":"symbol","title":"phoneTextField","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"phoneTextField"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MyPhoneNumberTextField","preciseIdentifier":"c:@M@Yababa@objc(cs)MyPhoneNumberTextField"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CompleteProfileSceneViewController\/phoneTextField","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"phoneTextField"}],"url":"\/documentation\/yababa\/completeprofilesceneviewcontroller\/phonetextfield"},"doc://com.yababaGmbH.yababa/objc(pl)UIContentContainer":{"type":"unresolvable","title":"UIKit.UIContentContainer","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIContentContainer"},"doc://com.yababaGmbH.yababa/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.yababaGmbH.yababa\/SQ"},"doc://com.yababaGmbH.yababa/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.yababaGmbH.yababa\/SH"},"doc://com.yababaGmbH.yababa/documentation/Yababa/CompleteProfileSceneViewControllerProtocol":{"role":"symbol","title":"CompleteProfileSceneViewControllerProtocol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"CompleteProfileSceneViewControllerProtocol"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CompleteProfileSceneViewControllerProtocol","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CompleteProfileSceneViewControllerProtocol"}],"url":"\/documentation\/yababa\/completeprofilesceneviewcontrollerprotocol"},"doc://com.yababaGmbH.yababa/objc(pl)UIActivityItemsConfigurationProviding":{"type":"unresolvable","title":"UIKit.UIActivityItemsConfigurationProviding","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIActivityItemsConfigurationProviding"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"CompleteProfileSceneViewController"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"CompleteProfileSceneViewController"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"CompleteProfileSceneViewController"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CompleteProfileSceneViewController\/firstNameTextField","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CompleteProfileSceneViewController\/lastNameTextField","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CompleteProfileSceneViewController\/nameStackView","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CompleteProfileSceneViewController\/nextBtn","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CompleteProfileSceneViewController\/phoneStackView","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CompleteProfileSceneViewController\/phoneTextField","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CompleteProfileSceneViewController\/smallSpinner","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CompleteProfileSceneViewController\/subTitleLabel"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CompleteProfileSceneViewController\/init(coder:)","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CompleteProfileSceneViewController\/onDonePhoneTextfield()","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CompleteProfileSceneViewController\/onNext()","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CompleteProfileSceneViewController\/viewDidLoad()"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/MasterViewController"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"CompleteProfileSceneViewController"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/MasterViewController","preciseIdentifier":"c:@M@Yababa@objc(cs)MasterViewController","text":"MasterViewController"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1CompleteProfileSceneViewController~1onDonePhoneTextfield()\/title","value":"onDonePhoneTextfield"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1CompleteProfileSceneViewController~1onDonePhoneTextfield()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onDonePhoneTextfield"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1CompleteProfileSceneViewController~1viewDidLoad()\/title","value":"viewDidLoad"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1CompleteProfileSceneViewController~1viewDidLoad()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"viewDidLoad"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1CompleteProfileSceneViewController~1phoneStackView\/title","value":"phoneStackView"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1CompleteProfileSceneViewController~1phoneStackView\/fragments","value":[{"kind":"identifier","text":"phoneStackView"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1CompleteProfileSceneViewController~1onNext()\/title","value":"onNext"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1CompleteProfileSceneViewController~1onNext()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onNext"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1MasterViewController\/title","value":"MasterViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1MasterViewController\/fragments","value":[{"kind":"identifier","text":"MasterViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1CompleteProfileSceneViewController~1smallSpinner\/title","value":"smallSpinner"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1CompleteProfileSceneViewController~1smallSpinner\/fragments","value":[{"kind":"identifier","text":"smallSpinner"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1CompleteProfileSceneViewController~1subTitleLabel\/title","value":"subTitleLabel"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1CompleteProfileSceneViewController~1subTitleLabel\/fragments","value":[{"kind":"identifier","text":"subTitleLabel"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1CompleteProfileSceneViewController~1firstNameTextField\/title","value":"firstNameTextField"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1CompleteProfileSceneViewController~1firstNameTextField\/fragments","value":[{"kind":"identifier","text":"firstNameTextField"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1CompleteProfileSceneViewController\/title","value":"CompleteProfileSceneViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1CompleteProfileSceneViewController\/fragments","value":[{"kind":"identifier","text":"CompleteProfileSceneViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1CompleteProfileSceneViewController~1init(coder:)\/title","value":"initWithCoder:"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1CompleteProfileSceneViewController~1init(coder:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithCoder:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1CompleteProfileSceneViewController~1lastNameTextField\/title","value":"lastNameTextField"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1CompleteProfileSceneViewController~1lastNameTextField\/fragments","value":[{"kind":"identifier","text":"lastNameTextField"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1CompleteProfileSceneViewController~1nextBtn\/title","value":"nextBtn"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1CompleteProfileSceneViewController~1nextBtn\/fragments","value":[{"kind":"identifier","text":"nextBtn"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1CompleteProfileSceneViewController~1nameStackView\/title","value":"nameStackView"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1CompleteProfileSceneViewController~1nameStackView\/fragments","value":[{"kind":"identifier","text":"nameStackView"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1CompleteProfileSceneViewController~1phoneTextField\/title","value":"phoneTextField"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1CompleteProfileSceneViewController~1phoneTextField\/fragments","value":[{"kind":"identifier","text":"phoneTextField"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}