{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CreditCardListDataSource"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/yababa\/creditcardlistdatasource"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/yababa\/creditcardlistdatasource"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.yababaGmbH.yababa\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.yababaGmbH.yababa\/objc(pl)NSObject","doc:\/\/com.yababaGmbH.yababa\/12SkeletonView17AssociatedObjectsP","doc:\/\/com.yababaGmbH.yababa\/s7CVarArgP","doc:\/\/com.yababaGmbH.yababa\/s28CustomDebugStringConvertibleP","doc:\/\/com.yababaGmbH.yababa\/s23CustomStringConvertibleP","doc:\/\/com.yababaGmbH.yababa\/SQ","doc:\/\/com.yababaGmbH.yababa\/SH","doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIScrollViewDelegate","doc:\/\/com.yababaGmbH.yababa\/objc(pl)UITableViewDataSource","doc:\/\/com.yababaGmbH.yababa\/objc(pl)UITableViewDelegate"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CreditCardListDataSource","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CreditCardListDataSource\/cardSelectionInteractorProtocol","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CreditCardListDataSource\/creditCardsSections","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CreditCardListDataSource\/rowHeight"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CreditCardListDataSource\/getTableRequiredHeight()","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CreditCardListDataSource\/numberOfElementsToShow()","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CreditCardListDataSource\/numberOfSections(in:)","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CreditCardListDataSource\/setCreditCardSectionsList(_:)","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CreditCardListDataSource\/setcardSelectionInteractorProtocol(_:)","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CreditCardListDataSource\/tableView(_:cellForRowAt:)","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CreditCardListDataSource\/tableView(_:didSelectRowAt:)","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CreditCardListDataSource\/tableView(_:heightForHeaderInSection:)","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CreditCardListDataSource\/tableView(_:numberOfRowsInSection:)","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CreditCardListDataSource\/tableView(_:titleForHeaderInSection:)","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CreditCardListDataSource\/tableView(_:willDisplayHeaderView:forSection:)"]}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CreditCardListDataSource"}],"title":"CreditCardListDataSource","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@Yababa@objc(cs)CreditCardListDataSource","modules":[{"name":"Yababa"}],"navigatorTitle":[{"kind":"identifier","text":"CreditCardListDataSource"}]},"hierarchy":{"paths":[["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa"]]},"references":{"doc://com.yababaGmbH.yababa/documentation/Yababa/CreditCardListDataSource/setcardSelectionInteractorProtocol(_:)":{"role":"symbol","title":"setcardSelectionInteractorProtocol(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setcardSelectionInteractorProtocol"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"CardSelectionInteractorProtocol","preciseIdentifier":"s:6Yababa31CardSelectionInteractorProtocolP"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CreditCardListDataSource\/setcardSelectionInteractorProtocol(_:)","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/creditcardlistdatasource\/setcardselectioninteractorprotocol(_:)"},"doc://com.yababaGmbH.yababa/documentation/Yababa/CreditCardListDataSource/getTableRequiredHeight()":{"role":"symbol","title":"getTableRequiredHeight()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getTableRequiredHeight"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CreditCardListDataSource\/getTableRequiredHeight()","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/creditcardlistdatasource\/gettablerequiredheight()"},"doc://com.yababaGmbH.yababa/documentation/Yababa/CreditCardListDataSource/numberOfElementsToShow()":{"role":"symbol","title":"numberOfElementsToShow()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"numberOfElementsToShow"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CreditCardListDataSource\/numberOfElementsToShow()","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/creditcardlistdatasource\/numberofelementstoshow()"},"doc://com.yababaGmbH.yababa/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.yababaGmbH.yababa\/s7CVarArgP"},"doc://com.yababaGmbH.yababa/documentation/Yababa/CreditCardListDataSource/cardSelectionInteractorProtocol":{"role":"symbol","title":"cardSelectionInteractorProtocol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"cardSelectionInteractorProtocol"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CardSelectionInteractorProtocol","preciseIdentifier":"s:6Yababa31CardSelectionInteractorProtocolP"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CreditCardListDataSource\/cardSelectionInteractorProtocol","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/creditcardlistdatasource\/cardselectioninteractorprotocol"},"doc://com.yababaGmbH.yababa/objc(pl)UIScrollViewDelegate":{"type":"unresolvable","title":"UIKit.UIScrollViewDelegate","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIScrollViewDelegate"},"doc://com.yababaGmbH.yababa/documentation/Yababa/CreditCardListDataSource":{"role":"symbol","title":"CreditCardListDataSource","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CreditCardListDataSource"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CreditCardListDataSource","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CreditCardListDataSource"}],"url":"\/documentation\/yababa\/creditcardlistdatasource"},"doc://com.yababaGmbH.yababa/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.yababaGmbH.yababa\/SH"},"doc://com.yababaGmbH.yababa/documentation/Yababa":{"role":"collection","title":"Yababa","abstract":[{"type":"text","text":"Getting Started"}],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa","kind":"symbol","type":"topic","url":"\/documentation\/yababa"},"doc://com.yababaGmbH.yababa/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(cs)NSObject"},"doc://com.yababaGmbH.yababa/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.yababaGmbH.yababa\/SQ"},"doc://com.yababaGmbH.yababa/documentation/Yababa/CreditCardListDataSource/init":{"role":"symbol","title":"init","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CreditCardListDataSource\/init","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"init"}],"url":"\/documentation\/yababa\/creditcardlistdatasource\/init"},"doc://com.yababaGmbH.yababa/objc(pl)UITableViewDelegate":{"type":"unresolvable","title":"UITableViewDelegate","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)UITableViewDelegate"},"doc://com.yababaGmbH.yababa/documentation/Yababa/CreditCardListDataSource/rowHeight":{"role":"symbol","title":"rowHeight","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"rowHeight"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CreditCardListDataSource\/rowHeight","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/creditcardlistdatasource\/rowheight"},"doc://com.yababaGmbH.yababa/documentation/Yababa/CreditCardListDataSource/tableView(_:numberOfRowsInSection:)":{"role":"symbol","title":"tableView(_:numberOfRowsInSection:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"tableView"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UITableView","preciseIdentifier":"c:objc(cs)UITableView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"numberOfRowsInSection"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CreditCardListDataSource\/tableView(_:numberOfRowsInSection:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"tableView:numberOfRowsInSection:"}],"url":"\/documentation\/yababa\/creditcardlistdatasource\/tableview(_:numberofrowsinsection:)"},"doc://com.yababaGmbH.yababa/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.yababaGmbH.yababa\/s28CustomDebugStringConvertibleP"},"doc://com.yababaGmbH.yababa/documentation/Yababa/CreditCardListDataSource/tableView(_:titleForHeaderInSection:)":{"role":"symbol","title":"tableView(_:titleForHeaderInSection:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"tableView"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UITableView","preciseIdentifier":"c:objc(cs)UITableView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"titleForHeaderInSection"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CreditCardListDataSource\/tableView(_:titleForHeaderInSection:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"tableView:titleForHeaderInSection:"}],"url":"\/documentation\/yababa\/creditcardlistdatasource\/tableview(_:titleforheaderinsection:)"},"doc://com.yababaGmbH.yababa/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)NSObject"},"doc://com.yababaGmbH.yababa/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.yababaGmbH.yababa\/s23CustomStringConvertibleP"},"doc://com.yababaGmbH.yababa/documentation/Yababa/CreditCardListDataSource/tableView(_:willDisplayHeaderView:forSection:)":{"role":"symbol","title":"tableView(_:willDisplayHeaderView:forSection:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"tableView"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UITableView","preciseIdentifier":"c:objc(cs)UITableView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"willDisplayHeaderView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"forSection"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CreditCardListDataSource\/tableView(_:willDisplayHeaderView:forSection:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"tableView:willDisplayHeaderView:forSection:"}],"url":"\/documentation\/yababa\/creditcardlistdatasource\/tableview(_:willdisplayheaderview:forsection:)"},"doc://com.yababaGmbH.yababa/objc(pl)UITableViewDataSource":{"type":"unresolvable","title":"UITableViewDataSource","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)UITableViewDataSource"},"doc://com.yababaGmbH.yababa/documentation/Yababa/CreditCardListDataSource/tableView(_:heightForHeaderInSection:)":{"role":"symbol","title":"tableView(_:heightForHeaderInSection:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"tableView"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UITableView","preciseIdentifier":"c:objc(cs)UITableView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"heightForHeaderInSection"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CreditCardListDataSource\/tableView(_:heightForHeaderInSection:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"tableView:heightForHeaderInSection:"}],"url":"\/documentation\/yababa\/creditcardlistdatasource\/tableview(_:heightforheaderinsection:)"},"doc://com.yababaGmbH.yababa/documentation/Yababa/CreditCardListDataSource/creditCardsSections":{"role":"symbol","title":"creditCardsSections","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"creditCardsSections"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"CreditCardListSection","preciseIdentifier":"s:6Yababa21CreditCardListSectionV"},{"kind":"text","text":"]"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CreditCardListDataSource\/creditCardsSections","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/creditcardlistdatasource\/creditcardssections"},"doc://com.yababaGmbH.yababa/documentation/Yababa/CreditCardListDataSource/tableView(_:cellForRowAt:)":{"role":"symbol","title":"tableView(_:cellForRowAt:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"tableView"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UITableView","preciseIdentifier":"c:objc(cs)UITableView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"cellForRowAt"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"IndexPath","preciseIdentifier":"s:10Foundation9IndexPathV"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"UITableViewCell","preciseIdentifier":"c:objc(cs)UITableViewCell"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CreditCardListDataSource\/tableView(_:cellForRowAt:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"tableView:cellForRowAtIndexPath:"}],"url":"\/documentation\/yababa\/creditcardlistdatasource\/tableview(_:cellforrowat:)"},"doc://com.yababaGmbH.yababa/documentation/Yababa/CreditCardListDataSource/numberOfSections(in:)":{"role":"symbol","title":"numberOfSections(in:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"numberOfSections"},{"kind":"text","text":"("},{"kind":"externalParam","text":"in"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UITableView","preciseIdentifier":"c:objc(cs)UITableView"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CreditCardListDataSource\/numberOfSections(in:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"numberOfSectionsInTableView:"}],"url":"\/documentation\/yababa\/creditcardlistdatasource\/numberofsections(in:)"},"doc://com.yababaGmbH.yababa/12SkeletonView17AssociatedObjectsP":{"type":"unresolvable","title":"SkeletonView.AssociatedObjects","identifier":"doc:\/\/com.yababaGmbH.yababa\/12SkeletonView17AssociatedObjectsP"},"doc://com.yababaGmbH.yababa/documentation/Yababa/CreditCardListDataSource/tableView(_:didSelectRowAt:)":{"role":"symbol","title":"tableView(_:didSelectRowAt:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"tableView"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UITableView","preciseIdentifier":"c:objc(cs)UITableView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didSelectRowAt"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"IndexPath","preciseIdentifier":"s:10Foundation9IndexPathV"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CreditCardListDataSource\/tableView(_:didSelectRowAt:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"tableView:didSelectRowAtIndexPath:"}],"url":"\/documentation\/yababa\/creditcardlistdatasource\/tableview(_:didselectrowat:)"},"doc://com.yababaGmbH.yababa/documentation/Yababa/CreditCardListDataSource/setCreditCardSectionsList(_:)":{"role":"symbol","title":"setCreditCardSectionsList(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setCreditCardSectionsList"},{"kind":"text","text":"(["},{"kind":"typeIdentifier","text":"CreditCardListSection","preciseIdentifier":"s:6Yababa21CreditCardListSectionV"},{"kind":"text","text":"])"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CreditCardListDataSource\/setCreditCardSectionsList(_:)","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/creditcardlistdatasource\/setcreditcardsectionslist(_:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"CreditCardListDataSource"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"CreditCardListDataSource"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"CreditCardListDataSource"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CreditCardListDataSource\/init","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CreditCardListDataSource\/numberOfSections(in:)","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CreditCardListDataSource\/tableView(_:cellForRowAt:)","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CreditCardListDataSource\/tableView(_:didSelectRowAt:)","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CreditCardListDataSource\/tableView(_:heightForHeaderInSection:)","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CreditCardListDataSource\/tableView(_:numberOfRowsInSection:)","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CreditCardListDataSource\/tableView(_:titleForHeaderInSection:)","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CreditCardListDataSource\/tableView(_:willDisplayHeaderView:forSection:)"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.yababaGmbH.yababa\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.yababaGmbH.yababa\/objc(pl)UITableViewDataSource","doc:\/\/com.yababaGmbH.yababa\/objc(pl)UITableViewDelegate"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"CreditCardListDataSource"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1CreditCardListDataSource\/title","value":"CreditCardListDataSource"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1CreditCardListDataSource\/fragments","value":[{"kind":"identifier","text":"CreditCardListDataSource"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1CreditCardListDataSource~1tableView(_:numberOfRowsInSection:)\/title","value":"tableView:numberOfRowsInSection:"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1CreditCardListDataSource~1tableView(_:numberOfRowsInSection:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"tableView:numberOfRowsInSection:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1CreditCardListDataSource~1tableView(_:titleForHeaderInSection:)\/title","value":"tableView:titleForHeaderInSection:"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1CreditCardListDataSource~1tableView(_:titleForHeaderInSection:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"tableView:titleForHeaderInSection:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1CreditCardListDataSource~1tableView(_:willDisplayHeaderView:forSection:)\/title","value":"tableView:willDisplayHeaderView:forSection:"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1CreditCardListDataSource~1tableView(_:willDisplayHeaderView:forSection:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"tableView:willDisplayHeaderView:forSection:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1CreditCardListDataSource~1tableView(_:heightForHeaderInSection:)\/title","value":"tableView:heightForHeaderInSection:"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1CreditCardListDataSource~1tableView(_:heightForHeaderInSection:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"tableView:heightForHeaderInSection:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1CreditCardListDataSource~1tableView(_:cellForRowAt:)\/title","value":"tableView:cellForRowAtIndexPath:"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1CreditCardListDataSource~1tableView(_:cellForRowAt:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"tableView:cellForRowAtIndexPath:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1CreditCardListDataSource~1numberOfSections(in:)\/title","value":"numberOfSectionsInTableView:"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1CreditCardListDataSource~1numberOfSections(in:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"numberOfSectionsInTableView:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1CreditCardListDataSource~1tableView(_:didSelectRowAt:)\/title","value":"tableView:didSelectRowAtIndexPath:"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1CreditCardListDataSource~1tableView(_:didSelectRowAt:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"tableView:didSelectRowAtIndexPath:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}