{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DeliveryTimeSlotPickerViewController"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/yababa\/deliverytimeslotpickerviewcontroller"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/yababa\/deliverytimeslotpickerviewcontroller"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.yababaGmbH.yababa\/objc(cs)UIViewController"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/DeliveryTimeSlotPickerViewControllerProtocol","doc:\/\/com.yababaGmbH.yababa\/objc(pl)NSCoding","doc:\/\/com.yababaGmbH.yababa\/objc(pl)NSExtensionRequestHandling","doc:\/\/com.yababaGmbH.yababa\/objc(pl)NSObject","doc:\/\/com.yababaGmbH.yababa\/12SkeletonView17AssociatedObjectsP","doc:\/\/com.yababaGmbH.yababa\/s7CVarArgP","doc:\/\/com.yababaGmbH.yababa\/s28CustomDebugStringConvertibleP","doc:\/\/com.yababaGmbH.yababa\/s23CustomStringConvertibleP","doc:\/\/com.yababaGmbH.yababa\/SQ","doc:\/\/com.yababaGmbH.yababa\/SH","doc:\/\/com.yababaGmbH.yababa\/s8SendableP","doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIActivityItemsConfigurationProviding","doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIAppearanceContainer","doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIContentContainer","doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIFocusEnvironment","doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIPasteConfigurationSupporting","doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIResponderStandardEditActions","doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIStateRestoring","doc:\/\/com.yababaGmbH.yababa\/objc(pl)UITraitEnvironment","doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIUserActivityRestoring"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/DeliveryTimeSlotPickerViewController","interfaceLanguage":"swift"},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/DeliveryTimeSlotPickerViewController\/init(coder:)","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/DeliveryTimeSlotPickerViewController\/init(eventOrigin:withTimeExpiredError:withCustomBackButton:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/DeliveryTimeSlotPickerViewController\/availabilityDaySlots","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/DeliveryTimeSlotPickerViewController\/availableTimeSlotsLabel","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/DeliveryTimeSlotPickerViewController\/bottomContainerMessageLabel","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/DeliveryTimeSlotPickerViewController\/bottomMessageContainer","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/DeliveryTimeSlotPickerViewController\/collectionViewsStackViewContainer","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/DeliveryTimeSlotPickerViewController\/confirmTimeBtn","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/DeliveryTimeSlotPickerViewController\/customNavBar","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/DeliveryTimeSlotPickerViewController\/dayCollectionContainerView","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/DeliveryTimeSlotPickerViewController\/dayCollectionView","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/DeliveryTimeSlotPickerViewController\/dayCollectionViewHeightConstraint","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/DeliveryTimeSlotPickerViewController\/delegate","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/DeliveryTimeSlotPickerViewController\/interactor","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/DeliveryTimeSlotPickerViewController\/is3PLDelivery","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/DeliveryTimeSlotPickerViewController\/pickTimeLabel","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/DeliveryTimeSlotPickerViewController\/router","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/DeliveryTimeSlotPickerViewController\/selectedSlot","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/DeliveryTimeSlotPickerViewController\/timeCollectionContainerView","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/DeliveryTimeSlotPickerViewController\/timeCollectionView"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/DeliveryTimeSlotPickerViewController\/fetchTimeSlots(date:)","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/DeliveryTimeSlotPickerViewController\/getCorrespondingDaySlotIndexToSelect(_:)","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/DeliveryTimeSlotPickerViewController\/hideLoading()","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/DeliveryTimeSlotPickerViewController\/layout3PLViewMode()","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/DeliveryTimeSlotPickerViewController\/layoutStandardSlotsMode()","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/DeliveryTimeSlotPickerViewController\/onBack()","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/DeliveryTimeSlotPickerViewController\/onConfirm()","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/DeliveryTimeSlotPickerViewController\/onTimeSlotSelection(_:reloadTableView:)","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/DeliveryTimeSlotPickerViewController\/postLoadAnalytics()","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/DeliveryTimeSlotPickerViewController\/setIdentifiers()","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/DeliveryTimeSlotPickerViewController\/setupUI()","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/DeliveryTimeSlotPickerViewController\/showLoading()","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/DeliveryTimeSlotPickerViewController\/viewDidLoad()"]},{"title":"Default Implementations","identifiers":["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/DeliveryTimeSlotPickerViewController\/DayCollectionViewDataSourceDelegate-Implementations","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/DeliveryTimeSlotPickerViewController\/DeliveryTimeSlotPickerViewControllerProtocol-Implementations","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/DeliveryTimeSlotPickerViewController\/TimeCollectionViewDataSourceDelegate-Implementations"],"generated":true}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DeliveryTimeSlotPickerViewController"}],"title":"DeliveryTimeSlotPickerViewController","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@Yababa@objc(cs)DeliveryTimeSlotPickerViewController","modules":[{"name":"Yababa"}],"navigatorTitle":[{"kind":"identifier","text":"DeliveryTimeSlotPickerViewController"}]},"hierarchy":{"paths":[["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa"]]},"references":{"doc://com.yababaGmbH.yababa/objc(pl)NSExtensionRequestHandling":{"type":"unresolvable","title":"Foundation.NSExtensionRequestHandling","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)NSExtensionRequestHandling"},"doc://com.yababaGmbH.yababa/documentation/Yababa/DeliveryTimeSlotPickerViewController/customNavBar":{"role":"symbol","title":"customNavBar","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"customNavBar"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/DeliveryTimeSlotPickerViewController\/customNavBar","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"customNavBar"}],"url":"\/documentation\/yababa\/deliverytimeslotpickerviewcontroller\/customnavbar"},"doc://com.yababaGmbH.yababa/documentation/Yababa/DeliveryTimeSlotPickerViewController/onConfirm()":{"role":"symbol","title":"onConfirm()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onConfirm"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/DeliveryTimeSlotPickerViewController\/onConfirm()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"onConfirm"}],"url":"\/documentation\/yababa\/deliverytimeslotpickerviewcontroller\/onconfirm()"},"doc://com.yababaGmbH.yababa/documentation/Yababa/DeliveryTimeSlotPickerViewController/bottomMessageContainer":{"role":"symbol","title":"bottomMessageContainer","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"bottomMessageContainer"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/DeliveryTimeSlotPickerViewController\/bottomMessageContainer","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"bottomMessageContainer"}],"url":"\/documentation\/yababa\/deliverytimeslotpickerviewcontroller\/bottommessagecontainer"},"doc://com.yababaGmbH.yababa/objc(pl)UIResponderStandardEditActions":{"type":"unresolvable","title":"UIKit.UIResponderStandardEditActions","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIResponderStandardEditActions"},"doc://com.yababaGmbH.yababa/objc(pl)NSCoding":{"type":"unresolvable","title":"Foundation.NSCoding","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)NSCoding"},"doc://com.yababaGmbH.yababa/documentation/Yababa/DeliveryTimeSlotPickerViewController/collectionViewsStackViewContainer":{"role":"symbol","title":"collectionViewsStackViewContainer","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"collectionViewsStackViewContainer"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIStackView","preciseIdentifier":"c:objc(cs)UIStackView"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/DeliveryTimeSlotPickerViewController\/collectionViewsStackViewContainer","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"collectionViewsStackViewContainer"}],"url":"\/documentation\/yababa\/deliverytimeslotpickerviewcontroller\/collectionviewsstackviewcontainer"},"doc://com.yababaGmbH.yababa/documentation/Yababa/DeliveryTimeSlotPickerViewController/hideLoading()":{"role":"symbol","title":"hideLoading()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"hideLoading"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/DeliveryTimeSlotPickerViewController\/hideLoading()","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/deliverytimeslotpickerviewcontroller\/hideloading()"},"doc://com.yababaGmbH.yababa/documentation/Yababa/DeliveryTimeSlotPickerViewController/fetchTimeSlots(date:)":{"role":"symbol","title":"fetchTimeSlots(date:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"fetchTimeSlots"},{"kind":"text","text":"("},{"kind":"externalParam","text":"date"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Date","preciseIdentifier":"s:10Foundation4DateV"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/DeliveryTimeSlotPickerViewController\/fetchTimeSlots(date:)","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/deliverytimeslotpickerviewcontroller\/fetchtimeslots(date:)"},"doc://com.yababaGmbH.yababa/documentation/Yababa/DeliveryTimeSlotPickerViewController/router":{"role":"symbol","title":"router","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"router"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DeliveryTimeSlotPickerRouterProtocol","preciseIdentifier":"s:6Yababa36DeliveryTimeSlotPickerRouterProtocolP"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/DeliveryTimeSlotPickerViewController\/router","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/deliverytimeslotpickerviewcontroller\/router"},"doc://com.yababaGmbH.yababa/documentation/Yababa/DeliveryTimeSlotPickerViewController/delegate":{"role":"symbol","title":"delegate","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"delegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DeliveryTimeSlotPickerDelegate","preciseIdentifier":"s:6Yababa30DeliveryTimeSlotPickerDelegateP"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/DeliveryTimeSlotPickerViewController\/delegate","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/deliverytimeslotpickerviewcontroller\/delegate"},"doc://com.yababaGmbH.yababa/documentation/Yababa/DeliveryTimeSlotPickerViewController/confirmTimeBtn":{"role":"symbol","title":"confirmTimeBtn","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"confirmTimeBtn"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIButton","preciseIdentifier":"c:objc(cs)UIButton"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/DeliveryTimeSlotPickerViewController\/confirmTimeBtn","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"confirmTimeBtn"}],"url":"\/documentation\/yababa\/deliverytimeslotpickerviewcontroller\/confirmtimebtn"},"doc://com.yababaGmbH.yababa/documentation/Yababa/DeliveryTimeSlotPickerViewController/init(coder:)":{"role":"symbol","title":"init(coder:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"coder"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSCoder","preciseIdentifier":"c:objc(cs)NSCoder"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/DeliveryTimeSlotPickerViewController\/init(coder:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithCoder:"}],"url":"\/documentation\/yababa\/deliverytimeslotpickerviewcontroller\/init(coder:)"},"doc://com.yababaGmbH.yababa/documentation/Yababa/DeliveryTimeSlotPickerViewController/availabilityDaySlots":{"role":"symbol","title":"availabilityDaySlots","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"availabilityDaySlots"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"AvailabilityDaySlot","preciseIdentifier":"s:6Yababa19AvailabilityDaySlotC"},{"kind":"text","text":"]"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/DeliveryTimeSlotPickerViewController\/availabilityDaySlots","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/deliverytimeslotpickerviewcontroller\/availabilitydayslots"},"doc://com.yababaGmbH.yababa/documentation/Yababa/DeliveryTimeSlotPickerViewController/setIdentifiers()":{"role":"symbol","title":"setIdentifiers()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setIdentifiers"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/DeliveryTimeSlotPickerViewController\/setIdentifiers()","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/deliverytimeslotpickerviewcontroller\/setidentifiers()"},"doc://com.yababaGmbH.yababa/12SkeletonView17AssociatedObjectsP":{"type":"unresolvable","title":"SkeletonView.AssociatedObjects","identifier":"doc:\/\/com.yababaGmbH.yababa\/12SkeletonView17AssociatedObjectsP"},"doc://com.yababaGmbH.yababa/documentation/Yababa/DeliveryTimeSlotPickerViewController/setupUI()":{"role":"symbol","title":"setupUI()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setupUI"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/DeliveryTimeSlotPickerViewController\/setupUI()","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/deliverytimeslotpickerviewcontroller\/setupui()"},"doc://com.yababaGmbH.yababa/documentation/Yababa/DeliveryTimeSlotPickerViewController/timeCollectionContainerView":{"role":"symbol","title":"timeCollectionContainerView","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"timeCollectionContainerView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/DeliveryTimeSlotPickerViewController\/timeCollectionContainerView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"timeCollectionContainerView"}],"url":"\/documentation\/yababa\/deliverytimeslotpickerviewcontroller\/timecollectioncontainerview"},"doc://com.yababaGmbH.yababa/documentation/Yababa/DeliveryTimeSlotPickerViewController/getCorrespondingDaySlotIndexToSelect(_:)":{"role":"symbol","title":"getCorrespondingDaySlotIndexToSelect(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getCorrespondingDaySlotIndexToSelect"},{"kind":"text","text":"(["},{"kind":"typeIdentifier","text":"AvailabilityDaySlot","preciseIdentifier":"s:6Yababa19AvailabilityDaySlotC"},{"kind":"text","text":"]) -> "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/DeliveryTimeSlotPickerViewController\/getCorrespondingDaySlotIndexToSelect(_:)","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/deliverytimeslotpickerviewcontroller\/getcorrespondingdayslotindextoselect(_:)"},"doc://com.yababaGmbH.yababa/documentation/Yababa/DeliveryTimeSlotPickerViewController/selectedSlot":{"role":"symbol","title":"selectedSlot","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"selectedSlot"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AvailabilityTimeSlot","preciseIdentifier":"s:6Yababa20AvailabilityTimeSlotC"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/DeliveryTimeSlotPickerViewController\/selectedSlot","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/deliverytimeslotpickerviewcontroller\/selectedslot"},"doc://com.yababaGmbH.yababa/documentation/Yababa/DeliveryTimeSlotPickerViewController/postLoadAnalytics()":{"role":"symbol","title":"postLoadAnalytics()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"postLoadAnalytics"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/DeliveryTimeSlotPickerViewController\/postLoadAnalytics()","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/deliverytimeslotpickerviewcontroller\/postloadanalytics()"},"doc://com.yababaGmbH.yababa/objc(cs)UIViewController":{"type":"unresolvable","title":"UIViewController","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(cs)UIViewController"},"doc://com.yababaGmbH.yababa/documentation/Yababa/DeliveryTimeSlotPickerViewController/availableTimeSlotsLabel":{"role":"symbol","title":"availableTimeSlotsLabel","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"availableTimeSlotsLabel"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UILabel","preciseIdentifier":"c:objc(cs)UILabel"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/DeliveryTimeSlotPickerViewController\/availableTimeSlotsLabel","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"availableTimeSlotsLabel"}],"url":"\/documentation\/yababa\/deliverytimeslotpickerviewcontroller\/availabletimeslotslabel"},"doc://com.yababaGmbH.yababa/documentation/Yababa/DeliveryTimeSlotPickerViewController/layout3PLViewMode()":{"role":"symbol","title":"layout3PLViewMode()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"layout3PLViewMode"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/DeliveryTimeSlotPickerViewController\/layout3PLViewMode()","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/deliverytimeslotpickerviewcontroller\/layout3plviewmode()"},"doc://com.yababaGmbH.yababa/documentation/Yababa/DeliveryTimeSlotPickerViewController/DeliveryTimeSlotPickerViewControllerProtocol-Implementations":{"role":"collectionGroup","title":"DeliveryTimeSlotPickerViewControllerProtocol Implementations","abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/DeliveryTimeSlotPickerViewController\/DeliveryTimeSlotPickerViewControllerProtocol-Implementations","kind":"article","type":"topic","url":"\/documentation\/yababa\/deliverytimeslotpickerviewcontroller\/deliverytimeslotpickerviewcontrollerprotocol-implementations"},"doc://com.yababaGmbH.yababa/documentation/Yababa/DeliveryTimeSlotPickerViewController/timeCollectionView":{"role":"symbol","title":"timeCollectionView","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"timeCollectionView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UICollectionView","preciseIdentifier":"c:objc(cs)UICollectionView"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/DeliveryTimeSlotPickerViewController\/timeCollectionView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"timeCollectionView"}],"url":"\/documentation\/yababa\/deliverytimeslotpickerviewcontroller\/timecollectionview"},"doc://com.yababaGmbH.yababa/objc(pl)UIPasteConfigurationSupporting":{"type":"unresolvable","title":"UIKit.UIPasteConfigurationSupporting","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIPasteConfigurationSupporting"},"doc://com.yababaGmbH.yababa/documentation/Yababa/DeliveryTimeSlotPickerViewController/onTimeSlotSelection(_:reloadTableView:)":{"role":"symbol","title":"onTimeSlotSelection(_:reloadTableView:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onTimeSlotSelection"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AvailabilityTimeSlot","preciseIdentifier":"s:6Yababa20AvailabilityTimeSlotC"},{"kind":"text","text":", "},{"kind":"externalParam","text":"reloadTableView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/DeliveryTimeSlotPickerViewController\/onTimeSlotSelection(_:reloadTableView:)","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/deliverytimeslotpickerviewcontroller\/ontimeslotselection(_:reloadtableview:)"},"doc://com.yababaGmbH.yababa/documentation/Yababa/DeliveryTimeSlotPickerViewController":{"role":"symbol","title":"DeliveryTimeSlotPickerViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DeliveryTimeSlotPickerViewController"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/DeliveryTimeSlotPickerViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DeliveryTimeSlotPickerViewController"}],"url":"\/documentation\/yababa\/deliverytimeslotpickerviewcontroller"},"doc://com.yababaGmbH.yababa/documentation/Yababa/DeliveryTimeSlotPickerViewController/viewDidLoad()":{"role":"symbol","title":"viewDidLoad()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"viewDidLoad"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/DeliveryTimeSlotPickerViewController\/viewDidLoad()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"viewDidLoad"}],"url":"\/documentation\/yababa\/deliverytimeslotpickerviewcontroller\/viewdidload()"},"doc://com.yababaGmbH.yababa/objc(pl)UITraitEnvironment":{"type":"unresolvable","title":"UIKit.UITraitEnvironment","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)UITraitEnvironment"},"doc://com.yababaGmbH.yababa/documentation/Yababa/DeliveryTimeSlotPickerViewControllerProtocol":{"role":"symbol","title":"DeliveryTimeSlotPickerViewControllerProtocol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"DeliveryTimeSlotPickerViewControllerProtocol"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/DeliveryTimeSlotPickerViewControllerProtocol","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DeliveryTimeSlotPickerViewControllerProtocol"}],"url":"\/documentation\/yababa\/deliverytimeslotpickerviewcontrollerprotocol"},"doc://com.yababaGmbH.yababa/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)NSObject"},"doc://com.yababaGmbH.yababa/documentation/Yababa/DeliveryTimeSlotPickerViewController/bottomContainerMessageLabel":{"role":"symbol","title":"bottomContainerMessageLabel","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"bottomContainerMessageLabel"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UILabel","preciseIdentifier":"c:objc(cs)UILabel"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/DeliveryTimeSlotPickerViewController\/bottomContainerMessageLabel","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"bottomContainerMessageLabel"}],"url":"\/documentation\/yababa\/deliverytimeslotpickerviewcontroller\/bottomcontainermessagelabel"},"doc://com.yababaGmbH.yababa/documentation/Yababa/DeliveryTimeSlotPickerViewController/onBack()":{"role":"symbol","title":"onBack()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onBack"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/DeliveryTimeSlotPickerViewController\/onBack()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"onBack"}],"url":"\/documentation\/yababa\/deliverytimeslotpickerviewcontroller\/onback()"},"doc://com.yababaGmbH.yababa/documentation/Yababa/DeliveryTimeSlotPickerViewController/dayCollectionView":{"role":"symbol","title":"dayCollectionView","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"dayCollectionView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UICollectionView","preciseIdentifier":"c:objc(cs)UICollectionView"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/DeliveryTimeSlotPickerViewController\/dayCollectionView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"dayCollectionView"}],"url":"\/documentation\/yababa\/deliverytimeslotpickerviewcontroller\/daycollectionview"},"doc://com.yababaGmbH.yababa/documentation/Yababa/DeliveryTimeSlotPickerViewController/TimeCollectionViewDataSourceDelegate-Implementations":{"role":"collectionGroup","title":"TimeCollectionViewDataSourceDelegate Implementations","abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/DeliveryTimeSlotPickerViewController\/TimeCollectionViewDataSourceDelegate-Implementations","kind":"article","type":"topic","url":"\/documentation\/yababa\/deliverytimeslotpickerviewcontroller\/timecollectionviewdatasourcedelegate-implementations"},"doc://com.yababaGmbH.yababa/objc(pl)UIContentContainer":{"type":"unresolvable","title":"UIKit.UIContentContainer","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIContentContainer"},"doc://com.yababaGmbH.yababa/objc(pl)UIStateRestoring":{"type":"unresolvable","title":"UIKit.UIStateRestoring","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIStateRestoring"},"doc://com.yababaGmbH.yababa/documentation/Yababa/DeliveryTimeSlotPickerViewController/init(eventOrigin:withTimeExpiredError:withCustomBackButton:)":{"role":"symbol","title":"init(eventOrigin:withTimeExpiredError:withCustomBackButton:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"eventOrigin"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"withTimeExpiredError"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"withCustomBackButton"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/DeliveryTimeSlotPickerViewController\/init(eventOrigin:withTimeExpiredError:withCustomBackButton:)","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/deliverytimeslotpickerviewcontroller\/init(eventorigin:withtimeexpirederror:withcustombackbutton:)"},"doc://com.yababaGmbH.yababa/objc(pl)UIUserActivityRestoring":{"type":"unresolvable","title":"UIKit.UIUserActivityRestoring","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIUserActivityRestoring"},"doc://com.yababaGmbH.yababa/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.yababaGmbH.yababa\/s23CustomStringConvertibleP"},"doc://com.yababaGmbH.yababa/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.yababaGmbH.yababa\/SQ"},"doc://com.yababaGmbH.yababa/documentation/Yababa":{"role":"collection","title":"Yababa","abstract":[{"type":"text","text":"Getting Started"}],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa","kind":"symbol","type":"topic","url":"\/documentation\/yababa"},"doc://com.yababaGmbH.yababa/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.yababaGmbH.yababa\/s28CustomDebugStringConvertibleP"},"doc://com.yababaGmbH.yababa/documentation/Yababa/DeliveryTimeSlotPickerViewController/interactor":{"role":"symbol","title":"interactor","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"interactor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DeliveryTimeSlotPickerInteractorProtocol","preciseIdentifier":"s:6Yababa40DeliveryTimeSlotPickerInteractorProtocolP"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/DeliveryTimeSlotPickerViewController\/interactor","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/deliverytimeslotpickerviewcontroller\/interactor"},"doc://com.yababaGmbH.yababa/documentation/Yababa/DeliveryTimeSlotPickerViewController/layoutStandardSlotsMode()":{"role":"symbol","title":"layoutStandardSlotsMode()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"layoutStandardSlotsMode"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/DeliveryTimeSlotPickerViewController\/layoutStandardSlotsMode()","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/deliverytimeslotpickerviewcontroller\/layoutstandardslotsmode()"},"doc://com.yababaGmbH.yababa/objc(pl)UIAppearanceContainer":{"type":"unresolvable","title":"UIKit.UIAppearanceContainer","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIAppearanceContainer"},"doc://com.yababaGmbH.yababa/documentation/Yababa/DeliveryTimeSlotPickerViewController/dayCollectionViewHeightConstraint":{"role":"symbol","title":"dayCollectionViewHeightConstraint","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"dayCollectionViewHeightConstraint"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSLayoutConstraint","preciseIdentifier":"c:objc(cs)NSLayoutConstraint"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/DeliveryTimeSlotPickerViewController\/dayCollectionViewHeightConstraint","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"dayCollectionViewHeightConstraint"}],"url":"\/documentation\/yababa\/deliverytimeslotpickerviewcontroller\/daycollectionviewheightconstraint"},"doc://com.yababaGmbH.yababa/documentation/Yababa/DeliveryTimeSlotPickerViewController/DayCollectionViewDataSourceDelegate-Implementations":{"role":"collectionGroup","title":"DayCollectionViewDataSourceDelegate Implementations","abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/DeliveryTimeSlotPickerViewController\/DayCollectionViewDataSourceDelegate-Implementations","kind":"article","type":"topic","url":"\/documentation\/yababa\/deliverytimeslotpickerviewcontroller\/daycollectionviewdatasourcedelegate-implementations"},"doc://com.yababaGmbH.yababa/documentation/Yababa/DeliveryTimeSlotPickerViewController/is3PLDelivery":{"role":"symbol","title":"is3PLDelivery","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"is3PLDelivery"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/DeliveryTimeSlotPickerViewController\/is3PLDelivery","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/deliverytimeslotpickerviewcontroller\/is3pldelivery"},"doc://com.yababaGmbH.yababa/documentation/Yababa/DeliveryTimeSlotPickerViewController/pickTimeLabel":{"role":"symbol","title":"pickTimeLabel","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"pickTimeLabel"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UILabel","preciseIdentifier":"c:objc(cs)UILabel"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/DeliveryTimeSlotPickerViewController\/pickTimeLabel","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"pickTimeLabel"}],"url":"\/documentation\/yababa\/deliverytimeslotpickerviewcontroller\/picktimelabel"},"doc://com.yababaGmbH.yababa/documentation/Yababa/DeliveryTimeSlotPickerViewController/dayCollectionContainerView":{"role":"symbol","title":"dayCollectionContainerView","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"dayCollectionContainerView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/DeliveryTimeSlotPickerViewController\/dayCollectionContainerView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"dayCollectionContainerView"}],"url":"\/documentation\/yababa\/deliverytimeslotpickerviewcontroller\/daycollectioncontainerview"},"doc://com.yababaGmbH.yababa/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.yababaGmbH.yababa\/s7CVarArgP"},"doc://com.yababaGmbH.yababa/objc(pl)UIFocusEnvironment":{"type":"unresolvable","title":"UIKit.UIFocusEnvironment","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIFocusEnvironment"},"doc://com.yababaGmbH.yababa/documentation/Yababa/DeliveryTimeSlotPickerViewController/showLoading()":{"role":"symbol","title":"showLoading()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"showLoading"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/DeliveryTimeSlotPickerViewController\/showLoading()","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/deliverytimeslotpickerviewcontroller\/showloading()"},"doc://com.yababaGmbH.yababa/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.yababaGmbH.yababa\/SH"},"doc://com.yababaGmbH.yababa/objc(pl)UIActivityItemsConfigurationProviding":{"type":"unresolvable","title":"UIKit.UIActivityItemsConfigurationProviding","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIActivityItemsConfigurationProviding"},"doc://com.yababaGmbH.yababa/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/com.yababaGmbH.yababa\/s8SendableP"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"DeliveryTimeSlotPickerViewController"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"DeliveryTimeSlotPickerViewController"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"DeliveryTimeSlotPickerViewController"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/DeliveryTimeSlotPickerViewController\/availableTimeSlotsLabel","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/DeliveryTimeSlotPickerViewController\/bottomContainerMessageLabel","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/DeliveryTimeSlotPickerViewController\/bottomMessageContainer","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/DeliveryTimeSlotPickerViewController\/collectionViewsStackViewContainer","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/DeliveryTimeSlotPickerViewController\/confirmTimeBtn","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/DeliveryTimeSlotPickerViewController\/customNavBar","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/DeliveryTimeSlotPickerViewController\/dayCollectionContainerView","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/DeliveryTimeSlotPickerViewController\/dayCollectionView","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/DeliveryTimeSlotPickerViewController\/dayCollectionViewHeightConstraint","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/DeliveryTimeSlotPickerViewController\/pickTimeLabel","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/DeliveryTimeSlotPickerViewController\/timeCollectionContainerView","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/DeliveryTimeSlotPickerViewController\/timeCollectionView"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/DeliveryTimeSlotPickerViewController\/init(coder:)","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/DeliveryTimeSlotPickerViewController\/onBack()","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/DeliveryTimeSlotPickerViewController\/onConfirm()","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/DeliveryTimeSlotPickerViewController\/viewDidLoad()"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.yababaGmbH.yababa\/objc(cs)UIViewController"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"DeliveryTimeSlotPickerViewController"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1DeliveryTimeSlotPickerViewController~1customNavBar\/title","value":"customNavBar"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1DeliveryTimeSlotPickerViewController~1customNavBar\/fragments","value":[{"kind":"identifier","text":"customNavBar"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1DeliveryTimeSlotPickerViewController~1onConfirm()\/title","value":"onConfirm"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1DeliveryTimeSlotPickerViewController~1onConfirm()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onConfirm"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1DeliveryTimeSlotPickerViewController~1bottomMessageContainer\/title","value":"bottomMessageContainer"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1DeliveryTimeSlotPickerViewController~1bottomMessageContainer\/fragments","value":[{"kind":"identifier","text":"bottomMessageContainer"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1DeliveryTimeSlotPickerViewController~1collectionViewsStackViewContainer\/title","value":"collectionViewsStackViewContainer"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1DeliveryTimeSlotPickerViewController~1collectionViewsStackViewContainer\/fragments","value":[{"kind":"identifier","text":"collectionViewsStackViewContainer"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1DeliveryTimeSlotPickerViewController~1confirmTimeBtn\/title","value":"confirmTimeBtn"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1DeliveryTimeSlotPickerViewController~1confirmTimeBtn\/fragments","value":[{"kind":"identifier","text":"confirmTimeBtn"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1DeliveryTimeSlotPickerViewController~1init(coder:)\/title","value":"initWithCoder:"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1DeliveryTimeSlotPickerViewController~1init(coder:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithCoder:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1DeliveryTimeSlotPickerViewController~1timeCollectionContainerView\/title","value":"timeCollectionContainerView"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1DeliveryTimeSlotPickerViewController~1timeCollectionContainerView\/fragments","value":[{"kind":"identifier","text":"timeCollectionContainerView"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1DeliveryTimeSlotPickerViewController~1availableTimeSlotsLabel\/title","value":"availableTimeSlotsLabel"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1DeliveryTimeSlotPickerViewController~1availableTimeSlotsLabel\/fragments","value":[{"kind":"identifier","text":"availableTimeSlotsLabel"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1DeliveryTimeSlotPickerViewController~1timeCollectionView\/title","value":"timeCollectionView"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1DeliveryTimeSlotPickerViewController~1timeCollectionView\/fragments","value":[{"kind":"identifier","text":"timeCollectionView"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1DeliveryTimeSlotPickerViewController\/title","value":"DeliveryTimeSlotPickerViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1DeliveryTimeSlotPickerViewController\/fragments","value":[{"kind":"identifier","text":"DeliveryTimeSlotPickerViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1DeliveryTimeSlotPickerViewController~1viewDidLoad()\/title","value":"viewDidLoad"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1DeliveryTimeSlotPickerViewController~1viewDidLoad()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"viewDidLoad"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1DeliveryTimeSlotPickerViewController~1bottomContainerMessageLabel\/title","value":"bottomContainerMessageLabel"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1DeliveryTimeSlotPickerViewController~1bottomContainerMessageLabel\/fragments","value":[{"kind":"identifier","text":"bottomContainerMessageLabel"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1DeliveryTimeSlotPickerViewController~1onBack()\/title","value":"onBack"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1DeliveryTimeSlotPickerViewController~1onBack()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onBack"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1DeliveryTimeSlotPickerViewController~1dayCollectionView\/title","value":"dayCollectionView"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1DeliveryTimeSlotPickerViewController~1dayCollectionView\/fragments","value":[{"kind":"identifier","text":"dayCollectionView"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1DeliveryTimeSlotPickerViewController~1dayCollectionViewHeightConstraint\/title","value":"dayCollectionViewHeightConstraint"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1DeliveryTimeSlotPickerViewController~1dayCollectionViewHeightConstraint\/fragments","value":[{"kind":"identifier","text":"dayCollectionViewHeightConstraint"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1DeliveryTimeSlotPickerViewController~1pickTimeLabel\/title","value":"pickTimeLabel"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1DeliveryTimeSlotPickerViewController~1pickTimeLabel\/fragments","value":[{"kind":"identifier","text":"pickTimeLabel"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1DeliveryTimeSlotPickerViewController~1dayCollectionContainerView\/title","value":"dayCollectionContainerView"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1DeliveryTimeSlotPickerViewController~1dayCollectionContainerView\/fragments","value":[{"kind":"identifier","text":"dayCollectionContainerView"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}