{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"DeliveryTimeSlotPickerDelegate"},{"kind":"text","text":" : AnyObject"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/yababa\/deliverytimeslotpickerdelegate"],"traits":[{"interfaceLanguage":"swift"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CheckoutSceneRouter","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/HomeScreen","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ShoppingCartSceneRouter"],"kind":"relationships","title":"Conforming Types","type":"conformingTypes"}],"identifier":{"url":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/DeliveryTimeSlotPickerDelegate","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/DeliveryTimeSlotPickerDelegate\/didNotSelectTimeSlot()","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/DeliveryTimeSlotPickerDelegate\/didSelectDayTimeSlot(_:)"]}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"DeliveryTimeSlotPickerDelegate"}],"title":"DeliveryTimeSlotPickerDelegate","roleHeading":"Protocol","role":"symbol","symbolKind":"protocol","externalID":"s:6Yababa30DeliveryTimeSlotPickerDelegateP","modules":[{"name":"Yababa"}],"navigatorTitle":[{"kind":"identifier","text":"DeliveryTimeSlotPickerDelegate"}]},"hierarchy":{"paths":[["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa"]]},"references":{"doc://com.yababaGmbH.yababa/documentation/Yababa/CheckoutSceneRouter":{"role":"symbol","title":"CheckoutSceneRouter","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CheckoutSceneRouter"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CheckoutSceneRouter","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CheckoutSceneRouter"}],"url":"\/documentation\/yababa\/checkoutscenerouter"},"doc://com.yababaGmbH.yababa/documentation/Yababa/ShoppingCartSceneRouter":{"role":"symbol","title":"ShoppingCartSceneRouter","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ShoppingCartSceneRouter"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ShoppingCartSceneRouter","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ShoppingCartSceneRouter"}],"url":"\/documentation\/yababa\/shoppingcartscenerouter"},"doc://com.yababaGmbH.yababa/documentation/Yababa":{"role":"collection","title":"Yababa","abstract":[{"type":"text","text":"Getting Started"}],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa","kind":"symbol","type":"topic","url":"\/documentation\/yababa"},"doc://com.yababaGmbH.yababa/documentation/Yababa/DeliveryTimeSlotPickerDelegate":{"role":"symbol","title":"DeliveryTimeSlotPickerDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"DeliveryTimeSlotPickerDelegate"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/DeliveryTimeSlotPickerDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DeliveryTimeSlotPickerDelegate"}],"url":"\/documentation\/yababa\/deliverytimeslotpickerdelegate"},"doc://com.yababaGmbH.yababa/documentation/Yababa/DeliveryTimeSlotPickerDelegate/didSelectDayTimeSlot(_:)":{"role":"symbol","title":"didSelectDayTimeSlot(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"didSelectDayTimeSlot"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AvailabilityTimeSlot","preciseIdentifier":"s:6Yababa20AvailabilityTimeSlotC"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/DeliveryTimeSlotPickerDelegate\/didSelectDayTimeSlot(_:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/yababa\/deliverytimeslotpickerdelegate\/didselectdaytimeslot(_:)"},"doc://com.yababaGmbH.yababa/documentation/Yababa/HomeScreen":{"role":"symbol","title":"HomeScreen","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HomeScreen"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/HomeScreen","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HomeScreen"}],"url":"\/documentation\/yababa\/homescreen"},"doc://com.yababaGmbH.yababa/documentation/Yababa/DeliveryTimeSlotPickerDelegate/didNotSelectTimeSlot()":{"role":"symbol","title":"didNotSelectTimeSlot()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"didNotSelectTimeSlot"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/DeliveryTimeSlotPickerDelegate\/didNotSelectTimeSlot()","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/yababa\/deliverytimeslotpickerdelegate\/didnotselecttimeslot()"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1CheckoutSceneRouter\/title","value":"CheckoutSceneRouter"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1CheckoutSceneRouter\/fragments","value":[{"kind":"identifier","text":"CheckoutSceneRouter"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1HomeScreen\/title","value":"HomeScreen"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1HomeScreen\/fragments","value":[{"kind":"identifier","text":"HomeScreen"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}