{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HomeScreen"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/yababa\/homescreen"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/yababa\/homescreen"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/DynamicLayoutScreen"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AddressManagerOwner","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/DeliveryTimeSlotPickerDelegate","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/DynamicLayoutItemSelectionDelegate","doc:\/\/com.yababaGmbH.yababa\/objc(pl)NSCoding","doc:\/\/com.yababaGmbH.yababa\/objc(pl)NSExtensionRequestHandling","doc:\/\/com.yababaGmbH.yababa\/objc(pl)NSObject","doc:\/\/com.yababaGmbH.yababa\/12SkeletonView17AssociatedObjectsP","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/SocialLoginResponseDelegate","doc:\/\/com.yababaGmbH.yababa\/s7CVarArgP","doc:\/\/com.yababaGmbH.yababa\/s28CustomDebugStringConvertibleP","doc:\/\/com.yababaGmbH.yababa\/s23CustomStringConvertibleP","doc:\/\/com.yababaGmbH.yababa\/SQ","doc:\/\/com.yababaGmbH.yababa\/SH","doc:\/\/com.yababaGmbH.yababa\/s8SendableP","doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIActivityItemsConfigurationProviding","doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIAppearanceContainer","doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIContentContainer","doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIFocusEnvironment","doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIPasteConfigurationSupporting","doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIResponderStandardEditActions","doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIScrollViewDelegate","doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIStateRestoring","doc:\/\/com.yababaGmbH.yababa\/objc(pl)UITableViewDataSource","doc:\/\/com.yababaGmbH.yababa\/objc(pl)UITableViewDelegate","doc:\/\/com.yababaGmbH.yababa\/objc(pl)UITraitEnvironment","doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIUserActivityRestoring"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/HomeScreen","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/HomeScreen\/addressManagerInteractor","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/HomeScreen\/addressSelectionManager","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/HomeScreen\/appleButton","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/HomeScreen\/browsingModeLabel","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/HomeScreen\/browsingModeLoginLabel","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/HomeScreen\/browsingModeView","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/HomeScreen\/clockIcon","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/HomeScreen\/facebookButton","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/HomeScreen\/featureFlagsButton","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/HomeScreen\/googleButton","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/HomeScreen\/headerLocationAndTimeContainer","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/HomeScreen\/homeSpinner","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/HomeScreen\/locationBtn","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/HomeScreen\/loginBenefitsViewContainer","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/HomeScreen\/mailButton","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/HomeScreen\/refreshBtn","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/HomeScreen\/searchBtn","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/HomeScreen\/timeSlotLabel","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/HomeScreen\/userAddressManager"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/HomeScreen\/checkValidityOfTimeSlot()","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/HomeScreen\/fetchHomeScreenItems()","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/HomeScreen\/getInteractor()","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/HomeScreen\/initializeAddressManager()","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/HomeScreen\/onAppleSignIn(_:)","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/HomeScreen\/onFacebookSignIn(_:)","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/HomeScreen\/onGoogleSignIn(_:)","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/HomeScreen\/onHeaderTap()","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/HomeScreen\/onMailSignIn(_:)","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/HomeScreen\/onShowMapsView()","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/HomeScreen\/refreshData()","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/HomeScreen\/scrollViewDidScroll(_:)","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/HomeScreen\/setIdentifiers()","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/HomeScreen\/setupUI()","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/HomeScreen\/showFeatureFlags(_:)","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/HomeScreen\/showSearch()","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/HomeScreen\/showTimeSlotPicker()","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/HomeScreen\/trackHomePageLoaded()","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/HomeScreen\/viewDidAppear(_:)","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/HomeScreen\/viewDidLoad()","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/HomeScreen\/viewWillAppear(_:)"]},{"title":"Default Implementations","identifiers":["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/HomeScreen\/AddressManagerOwner-Implementations","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/HomeScreen\/DeliveryTimeSlotPickerDelegate-Implementations","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/HomeScreen\/SocialLoginResponseDelegate-Implementations"],"generated":true}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HomeScreen"}],"title":"HomeScreen","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@Yababa@objc(cs)HomeScreen","modules":[{"name":"Yababa"}],"navigatorTitle":[{"kind":"identifier","text":"HomeScreen"}]},"hierarchy":{"paths":[["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa"]]},"references":{"doc://com.yababaGmbH.yababa/documentation/Yababa/HomeScreen/locationBtn":{"role":"symbol","title":"locationBtn","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"locationBtn"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIButton","preciseIdentifier":"c:objc(cs)UIButton"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/HomeScreen\/locationBtn","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"locationBtn"}],"url":"\/documentation\/yababa\/homescreen\/locationbtn"},"doc://com.yababaGmbH.yababa/documentation/Yababa/HomeScreen/showTimeSlotPicker()":{"role":"symbol","title":"showTimeSlotPicker()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"showTimeSlotPicker"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/HomeScreen\/showTimeSlotPicker()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"showTimeSlotPicker"}],"url":"\/documentation\/yababa\/homescreen\/showtimeslotpicker()"},"doc://com.yababaGmbH.yababa/objc(pl)UITraitEnvironment":{"type":"unresolvable","title":"UIKit.UITraitEnvironment","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)UITraitEnvironment"},"doc://com.yababaGmbH.yababa/objc(pl)UIActivityItemsConfigurationProviding":{"type":"unresolvable","title":"UIKit.UIActivityItemsConfigurationProviding","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIActivityItemsConfigurationProviding"},"doc://com.yababaGmbH.yababa/documentation/Yababa/HomeScreen/scrollViewDidScroll(_:)":{"role":"symbol","title":"scrollViewDidScroll(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"scrollViewDidScroll"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UIScrollView","preciseIdentifier":"c:objc(cs)UIScrollView"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/HomeScreen\/scrollViewDidScroll(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"scrollViewDidScroll:"}],"url":"\/documentation\/yababa\/homescreen\/scrollviewdidscroll(_:)"},"doc://com.yababaGmbH.yababa/objc(pl)UIResponderStandardEditActions":{"type":"unresolvable","title":"UIKit.UIResponderStandardEditActions","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIResponderStandardEditActions"},"doc://com.yababaGmbH.yababa/documentation/Yababa/HomeScreen/browsingModeLabel":{"role":"symbol","title":"browsingModeLabel","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"browsingModeLabel"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UILabel","preciseIdentifier":"c:objc(cs)UILabel"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/HomeScreen\/browsingModeLabel","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"browsingModeLabel"}],"url":"\/documentation\/yababa\/homescreen\/browsingmodelabel"},"doc://com.yababaGmbH.yababa/documentation/Yababa/HomeScreen/setupUI()":{"role":"symbol","title":"setupUI()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setupUI"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/HomeScreen\/setupUI()","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/homescreen\/setupui()"},"doc://com.yababaGmbH.yababa/objc(pl)NSCoding":{"type":"unresolvable","title":"Foundation.NSCoding","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)NSCoding"},"doc://com.yababaGmbH.yababa/documentation/Yababa/HomeScreen/googleButton":{"role":"symbol","title":"googleButton","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"googleButton"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIButton","preciseIdentifier":"c:objc(cs)UIButton"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/HomeScreen\/googleButton","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"googleButton"}],"url":"\/documentation\/yababa\/homescreen\/googlebutton"},"doc://com.yababaGmbH.yababa/documentation/Yababa/HomeScreen/initializeAddressManager()":{"role":"symbol","title":"initializeAddressManager()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"initializeAddressManager"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/HomeScreen\/initializeAddressManager()","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/homescreen\/initializeaddressmanager()"},"doc://com.yababaGmbH.yababa/documentation/Yababa/HomeScreen/mailButton":{"role":"symbol","title":"mailButton","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"mailButton"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIButton","preciseIdentifier":"c:objc(cs)UIButton"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/HomeScreen\/mailButton","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"mailButton"}],"url":"\/documentation\/yababa\/homescreen\/mailbutton"},"doc://com.yababaGmbH.yababa/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.yababaGmbH.yababa\/s23CustomStringConvertibleP"},"doc://com.yababaGmbH.yababa/documentation/Yababa/HomeScreen/onGoogleSignIn(_:)":{"role":"symbol","title":"onGoogleSignIn(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onGoogleSignIn"},{"kind":"text","text":"("},{"kind":"keyword","text":"Any"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/HomeScreen\/onGoogleSignIn(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"onGoogleSignIn:"}],"url":"\/documentation\/yababa\/homescreen\/ongooglesignin(_:)"},"doc://com.yababaGmbH.yababa/documentation/Yababa/HomeScreen/SocialLoginResponseDelegate-Implementations":{"role":"collectionGroup","title":"SocialLoginResponseDelegate Implementations","abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/HomeScreen\/SocialLoginResponseDelegate-Implementations","kind":"article","type":"topic","url":"\/documentation\/yababa\/homescreen\/socialloginresponsedelegate-implementations"},"doc://com.yababaGmbH.yababa/objc(pl)UIAppearanceContainer":{"type":"unresolvable","title":"UIKit.UIAppearanceContainer","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIAppearanceContainer"},"doc://com.yababaGmbH.yababa/documentation/Yababa/DeliveryTimeSlotPickerDelegate":{"role":"symbol","title":"DeliveryTimeSlotPickerDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"DeliveryTimeSlotPickerDelegate"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/DeliveryTimeSlotPickerDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DeliveryTimeSlotPickerDelegate"}],"url":"\/documentation\/yababa\/deliverytimeslotpickerdelegate"},"doc://com.yababaGmbH.yababa/objc(pl)NSExtensionRequestHandling":{"type":"unresolvable","title":"Foundation.NSExtensionRequestHandling","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)NSExtensionRequestHandling"},"doc://com.yababaGmbH.yababa/objc(pl)UIScrollViewDelegate":{"type":"unresolvable","title":"UIKit.UIScrollViewDelegate","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIScrollViewDelegate"},"doc://com.yababaGmbH.yababa/documentation/Yababa":{"role":"collection","title":"Yababa","abstract":[{"type":"text","text":"Getting Started"}],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa","kind":"symbol","type":"topic","url":"\/documentation\/yababa"},"doc://com.yababaGmbH.yababa/objc(pl)UIContentContainer":{"type":"unresolvable","title":"UIKit.UIContentContainer","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIContentContainer"},"doc://com.yababaGmbH.yababa/objc(pl)UIPasteConfigurationSupporting":{"type":"unresolvable","title":"UIKit.UIPasteConfigurationSupporting","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIPasteConfigurationSupporting"},"doc://com.yababaGmbH.yababa/documentation/Yababa/HomeScreen/initWithNibName:bundle:":{"role":"symbol","title":"initWithNibName:bundle:","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithNibName:bundle:"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/HomeScreen\/initWithNibName:bundle:","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithNibName:bundle:"}],"url":"\/documentation\/yababa\/homescreen\/initwithnibname:bundle:"},"doc://com.yababaGmbH.yababa/documentation/Yababa/HomeScreen/timeSlotLabel":{"role":"symbol","title":"timeSlotLabel","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"timeSlotLabel"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UILabel","preciseIdentifier":"c:objc(cs)UILabel"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/HomeScreen\/timeSlotLabel","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"timeSlotLabel"}],"url":"\/documentation\/yababa\/homescreen\/timeslotlabel"},"doc://com.yababaGmbH.yababa/documentation/Yababa/HomeScreen/initWithCoder:":{"role":"symbol","title":"initWithCoder:","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithCoder:"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/HomeScreen\/initWithCoder:","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithCoder:"}],"url":"\/documentation\/yababa\/homescreen\/initwithcoder:"},"doc://com.yababaGmbH.yababa/documentation/Yababa/HomeScreen/addressManagerInteractor":{"role":"symbol","title":"addressManagerInteractor","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"addressManagerInteractor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AddressManagerInteractorProtocol","preciseIdentifier":"s:6Yababa32AddressManagerInteractorProtocolP"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/HomeScreen\/addressManagerInteractor","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/homescreen\/addressmanagerinteractor"},"doc://com.yababaGmbH.yababa/documentation/Yababa/HomeScreen/browsingModeLoginLabel":{"role":"symbol","title":"browsingModeLoginLabel","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"browsingModeLoginLabel"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UILabel","preciseIdentifier":"c:objc(cs)UILabel"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/HomeScreen\/browsingModeLoginLabel","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"browsingModeLoginLabel"}],"url":"\/documentation\/yababa\/homescreen\/browsingmodeloginlabel"},"doc://com.yababaGmbH.yababa/documentation/Yababa/HomeScreen/facebookButton":{"role":"symbol","title":"facebookButton","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"facebookButton"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIButton","preciseIdentifier":"c:objc(cs)UIButton"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/HomeScreen\/facebookButton","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"facebookButton"}],"url":"\/documentation\/yababa\/homescreen\/facebookbutton"},"doc://com.yababaGmbH.yababa/documentation/Yababa/HomeScreen/userAddressManager":{"role":"symbol","title":"userAddressManager","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"userAddressManager"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AddressManager","preciseIdentifier":"c:@M@Yababa@objc(cs)AddressManager"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/HomeScreen\/userAddressManager","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/homescreen\/useraddressmanager"},"doc://com.yababaGmbH.yababa/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/com.yababaGmbH.yababa\/s8SendableP"},"doc://com.yababaGmbH.yababa/documentation/Yababa/HomeScreen/browsingModeView":{"role":"symbol","title":"browsingModeView","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"browsingModeView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/HomeScreen\/browsingModeView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"browsingModeView"}],"url":"\/documentation\/yababa\/homescreen\/browsingmodeview"},"doc://com.yababaGmbH.yababa/objc(pl)UIUserActivityRestoring":{"type":"unresolvable","title":"UIKit.UIUserActivityRestoring","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIUserActivityRestoring"},"doc://com.yababaGmbH.yababa/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.yababaGmbH.yababa\/SQ"},"doc://com.yababaGmbH.yababa/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.yababaGmbH.yababa\/s28CustomDebugStringConvertibleP"},"doc://com.yababaGmbH.yababa/documentation/Yababa/HomeScreen/onMailSignIn(_:)":{"role":"symbol","title":"onMailSignIn(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onMailSignIn"},{"kind":"text","text":"("},{"kind":"keyword","text":"Any"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/HomeScreen\/onMailSignIn(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"onMailSignIn:"}],"url":"\/documentation\/yababa\/homescreen\/onmailsignin(_:)"},"doc://com.yababaGmbH.yababa/documentation/Yababa/HomeScreen/viewWillAppear(_:)":{"role":"symbol","title":"viewWillAppear(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"viewWillAppear"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/HomeScreen\/viewWillAppear(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"viewWillAppear:"}],"url":"\/documentation\/yababa\/homescreen\/viewwillappear(_:)"},"doc://com.yababaGmbH.yababa/documentation/Yababa/HomeScreen/setIdentifiers()":{"role":"symbol","title":"setIdentifiers()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setIdentifiers"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/HomeScreen\/setIdentifiers()","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/homescreen\/setidentifiers()"},"doc://com.yababaGmbH.yababa/documentation/Yababa/HomeScreen/viewDidAppear(_:)":{"role":"symbol","title":"viewDidAppear(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"viewDidAppear"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/HomeScreen\/viewDidAppear(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"viewDidAppear:"}],"url":"\/documentation\/yababa\/homescreen\/viewdidappear(_:)"},"doc://com.yababaGmbH.yababa/documentation/Yababa/HomeScreen/onHeaderTap()":{"role":"symbol","title":"onHeaderTap()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onHeaderTap"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/HomeScreen\/onHeaderTap()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"onHeaderTap"}],"url":"\/documentation\/yababa\/homescreen\/onheadertap()"},"doc://com.yababaGmbH.yababa/documentation/Yababa/HomeScreen/getInteractor()":{"role":"symbol","title":"getInteractor()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getInteractor"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"HomeScreenInteractorProtocol","preciseIdentifier":"s:6Yababa28HomeScreenInteractorProtocolP"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/HomeScreen\/getInteractor()","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/homescreen\/getinteractor()"},"doc://com.yababaGmbH.yababa/objc(pl)UITableViewDelegate":{"type":"unresolvable","title":"UIKit.UITableViewDelegate","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)UITableViewDelegate"},"doc://com.yababaGmbH.yababa/documentation/Yababa/AddressManagerOwner":{"role":"symbol","title":"AddressManagerOwner","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"AddressManagerOwner"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AddressManagerOwner","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AddressManagerOwner"}],"url":"\/documentation\/yababa\/addressmanagerowner"},"doc://com.yababaGmbH.yababa/documentation/Yababa/HomeScreen/clockIcon":{"role":"symbol","title":"clockIcon","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"clockIcon"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIImageView","preciseIdentifier":"c:objc(cs)UIImageView"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/HomeScreen\/clockIcon","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"clockIcon"}],"url":"\/documentation\/yababa\/homescreen\/clockicon"},"doc://com.yababaGmbH.yababa/documentation/Yababa/HomeScreen/onAppleSignIn(_:)":{"role":"symbol","title":"onAppleSignIn(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onAppleSignIn"},{"kind":"text","text":"("},{"kind":"keyword","text":"Any"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/HomeScreen\/onAppleSignIn(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"onAppleSignIn:"}],"url":"\/documentation\/yababa\/homescreen\/onapplesignin(_:)"},"doc://com.yababaGmbH.yababa/documentation/Yababa/HomeScreen/DeliveryTimeSlotPickerDelegate-Implementations":{"role":"collectionGroup","title":"DeliveryTimeSlotPickerDelegate Implementations","abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/HomeScreen\/DeliveryTimeSlotPickerDelegate-Implementations","kind":"article","type":"topic","url":"\/documentation\/yababa\/homescreen\/deliverytimeslotpickerdelegate-implementations"},"doc://com.yababaGmbH.yababa/documentation/Yababa/HomeScreen/trackHomePageLoaded()":{"role":"symbol","title":"trackHomePageLoaded()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"trackHomePageLoaded"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/HomeScreen\/trackHomePageLoaded()","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/homescreen\/trackhomepageloaded()"},"doc://com.yababaGmbH.yababa/objc(pl)UIStateRestoring":{"type":"unresolvable","title":"UIKit.UIStateRestoring","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIStateRestoring"},"doc://com.yababaGmbH.yababa/documentation/Yababa/HomeScreen/onFacebookSignIn(_:)":{"role":"symbol","title":"onFacebookSignIn(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onFacebookSignIn"},{"kind":"text","text":"("},{"kind":"keyword","text":"Any"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/HomeScreen\/onFacebookSignIn(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"onFacebookSignIn:"}],"url":"\/documentation\/yababa\/homescreen\/onfacebooksignin(_:)"},"doc://com.yababaGmbH.yababa/documentation/Yababa/HomeScreen/AddressManagerOwner-Implementations":{"role":"collectionGroup","title":"AddressManagerOwner Implementations","abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/HomeScreen\/AddressManagerOwner-Implementations","kind":"article","type":"topic","url":"\/documentation\/yababa\/homescreen\/addressmanagerowner-implementations"},"doc://com.yababaGmbH.yababa/documentation/Yababa/HomeScreen/featureFlagsButton":{"role":"symbol","title":"featureFlagsButton","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"featureFlagsButton"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIButton","preciseIdentifier":"c:objc(cs)UIButton"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/HomeScreen\/featureFlagsButton","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"featureFlagsButton"}],"url":"\/documentation\/yababa\/homescreen\/featureflagsbutton"},"doc://com.yababaGmbH.yababa/documentation/Yababa/HomeScreen/appleButton":{"role":"symbol","title":"appleButton","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"appleButton"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIButton","preciseIdentifier":"c:objc(cs)UIButton"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/HomeScreen\/appleButton","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"appleButton"}],"url":"\/documentation\/yababa\/homescreen\/applebutton"},"doc://com.yababaGmbH.yababa/documentation/Yababa/HomeScreen/searchBtn":{"role":"symbol","title":"searchBtn","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"searchBtn"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIButton","preciseIdentifier":"c:objc(cs)UIButton"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/HomeScreen\/searchBtn","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"searchBtn"}],"url":"\/documentation\/yababa\/homescreen\/searchbtn"},"doc://com.yababaGmbH.yababa/objc(pl)UITableViewDataSource":{"type":"unresolvable","title":"UIKit.UITableViewDataSource","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)UITableViewDataSource"},"doc://com.yababaGmbH.yababa/12SkeletonView17AssociatedObjectsP":{"type":"unresolvable","title":"SkeletonView.AssociatedObjects","identifier":"doc:\/\/com.yababaGmbH.yababa\/12SkeletonView17AssociatedObjectsP"},"doc://com.yababaGmbH.yababa/documentation/Yababa/HomeScreen/fetchHomeScreenItems()":{"role":"symbol","title":"fetchHomeScreenItems()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"fetchHomeScreenItems"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/HomeScreen\/fetchHomeScreenItems()","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/homescreen\/fetchhomescreenitems()"},"doc://com.yababaGmbH.yababa/documentation/Yababa/HomeScreen/viewDidLoad()":{"role":"symbol","title":"viewDidLoad()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"viewDidLoad"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/HomeScreen\/viewDidLoad()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"viewDidLoad"}],"url":"\/documentation\/yababa\/homescreen\/viewdidload()"},"doc://com.yababaGmbH.yababa/documentation/Yababa/DynamicLayoutScreen":{"role":"symbol","title":"DynamicLayoutScreen","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DynamicLayoutScreen"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/DynamicLayoutScreen","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DynamicLayoutScreen"}],"url":"\/documentation\/yababa\/dynamiclayoutscreen"},"doc://com.yababaGmbH.yababa/documentation/Yababa/HomeScreen/showSearch()":{"role":"symbol","title":"showSearch()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"showSearch"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/HomeScreen\/showSearch()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"showSearch"}],"url":"\/documentation\/yababa\/homescreen\/showsearch()"},"doc://com.yababaGmbH.yababa/documentation/Yababa/HomeScreen/homeSpinner":{"role":"symbol","title":"homeSpinner","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"homeSpinner"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIActivityIndicatorView","preciseIdentifier":"c:objc(cs)UIActivityIndicatorView"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/HomeScreen\/homeSpinner","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"homeSpinner"}],"url":"\/documentation\/yababa\/homescreen\/homespinner"},"doc://com.yababaGmbH.yababa/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.yababaGmbH.yababa\/s7CVarArgP"},"doc://com.yababaGmbH.yababa/documentation/Yababa/HomeScreen/refreshBtn":{"role":"symbol","title":"refreshBtn","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"refreshBtn"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIButton","preciseIdentifier":"c:objc(cs)UIButton"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/HomeScreen\/refreshBtn","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"refreshBtn"}],"url":"\/documentation\/yababa\/homescreen\/refreshbtn"},"doc://com.yababaGmbH.yababa/documentation/Yababa/HomeScreen/showFeatureFlags(_:)":{"role":"symbol","title":"showFeatureFlags(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"showFeatureFlags"},{"kind":"text","text":"("},{"kind":"keyword","text":"Any"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/HomeScreen\/showFeatureFlags(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"showFeatureFlags:"}],"url":"\/documentation\/yababa\/homescreen\/showfeatureflags(_:)"},"doc://com.yababaGmbH.yababa/objc(pl)UIFocusEnvironment":{"type":"unresolvable","title":"UIKit.UIFocusEnvironment","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIFocusEnvironment"},"doc://com.yababaGmbH.yababa/documentation/Yababa/HomeScreen/loginBenefitsViewContainer":{"role":"symbol","title":"loginBenefitsViewContainer","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"loginBenefitsViewContainer"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIStackView","preciseIdentifier":"c:objc(cs)UIStackView"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/HomeScreen\/loginBenefitsViewContainer","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"loginBenefitsViewContainer"}],"url":"\/documentation\/yababa\/homescreen\/loginbenefitsviewcontainer"},"doc://com.yababaGmbH.yababa/documentation/Yababa/HomeScreen/checkValidityOfTimeSlot()":{"role":"symbol","title":"checkValidityOfTimeSlot()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"checkValidityOfTimeSlot"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/HomeScreen\/checkValidityOfTimeSlot()","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/homescreen\/checkvalidityoftimeslot()"},"doc://com.yababaGmbH.yababa/documentation/Yababa/SocialLoginResponseDelegate":{"role":"symbol","title":"SocialLoginResponseDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SocialLoginResponseDelegate"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/SocialLoginResponseDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SocialLoginResponseDelegate"}],"url":"\/documentation\/yababa\/socialloginresponsedelegate"},"doc://com.yababaGmbH.yababa/documentation/Yababa/DynamicLayoutItemSelectionDelegate":{"role":"symbol","title":"DynamicLayoutItemSelectionDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"DynamicLayoutItemSelectionDelegate"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/DynamicLayoutItemSelectionDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DynamicLayoutItemSelectionDelegate"}],"url":"\/documentation\/yababa\/dynamiclayoutitemselectiondelegate"},"doc://com.yababaGmbH.yababa/documentation/Yababa/HomeScreen/refreshData()":{"role":"symbol","title":"refreshData()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"refreshData"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/HomeScreen\/refreshData()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"refreshData"}],"url":"\/documentation\/yababa\/homescreen\/refreshdata()"},"doc://com.yababaGmbH.yababa/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)NSObject"},"doc://com.yababaGmbH.yababa/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.yababaGmbH.yababa\/SH"},"doc://com.yababaGmbH.yababa/documentation/Yababa/HomeScreen/addressSelectionManager":{"role":"symbol","title":"addressSelectionManager","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"addressSelectionManager"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AddressSelectionManager","preciseIdentifier":"s:6Yababa23AddressSelectionManagerP"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/HomeScreen\/addressSelectionManager","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/homescreen\/addressselectionmanager"},"doc://com.yababaGmbH.yababa/documentation/Yababa/HomeScreen":{"role":"symbol","title":"HomeScreen","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HomeScreen"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/HomeScreen","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HomeScreen"}],"url":"\/documentation\/yababa\/homescreen"},"doc://com.yababaGmbH.yababa/documentation/Yababa/HomeScreen/onShowMapsView()":{"role":"symbol","title":"onShowMapsView()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onShowMapsView"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/HomeScreen\/onShowMapsView()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"onShowMapsView"}],"url":"\/documentation\/yababa\/homescreen\/onshowmapsview()"},"doc://com.yababaGmbH.yababa/documentation/Yababa/HomeScreen/headerLocationAndTimeContainer":{"role":"symbol","title":"headerLocationAndTimeContainer","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"headerLocationAndTimeContainer"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/HomeScreen\/headerLocationAndTimeContainer","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"headerLocationAndTimeContainer"}],"url":"\/documentation\/yababa\/homescreen\/headerlocationandtimecontainer"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"HomeScreen"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"HomeScreen"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"HomeScreen"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/HomeScreen\/appleButton","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/HomeScreen\/browsingModeLabel","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/HomeScreen\/browsingModeLoginLabel","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/HomeScreen\/browsingModeView","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/HomeScreen\/clockIcon","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/HomeScreen\/facebookButton","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/HomeScreen\/featureFlagsButton","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/HomeScreen\/googleButton","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/HomeScreen\/headerLocationAndTimeContainer","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/HomeScreen\/homeSpinner","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/HomeScreen\/locationBtn","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/HomeScreen\/loginBenefitsViewContainer","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/HomeScreen\/mailButton","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/HomeScreen\/refreshBtn","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/HomeScreen\/searchBtn","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/HomeScreen\/timeSlotLabel"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/HomeScreen\/initWithCoder:","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/HomeScreen\/initWithNibName:bundle:","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/HomeScreen\/onAppleSignIn(_:)","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/HomeScreen\/onFacebookSignIn(_:)","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/HomeScreen\/onGoogleSignIn(_:)","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/HomeScreen\/onHeaderTap()","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/HomeScreen\/onMailSignIn(_:)","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/HomeScreen\/onShowMapsView()","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/HomeScreen\/refreshData()","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/HomeScreen\/scrollViewDidScroll(_:)","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/HomeScreen\/showFeatureFlags(_:)","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/HomeScreen\/showSearch()","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/HomeScreen\/showTimeSlotPicker()","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/HomeScreen\/viewDidAppear(_:)","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/HomeScreen\/viewDidLoad()","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/HomeScreen\/viewWillAppear(_:)"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/DynamicLayoutScreen"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"HomeScreen"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/DynamicLayoutScreen","preciseIdentifier":"c:@M@Yababa@objc(cs)DynamicLayoutScreen","text":"DynamicLayoutScreen"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1HomeScreen~1locationBtn\/title","value":"locationBtn"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1HomeScreen~1locationBtn\/fragments","value":[{"kind":"identifier","text":"locationBtn"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1HomeScreen~1showTimeSlotPicker()\/title","value":"showTimeSlotPicker"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1HomeScreen~1showTimeSlotPicker()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"showTimeSlotPicker"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1HomeScreen~1scrollViewDidScroll(_:)\/title","value":"scrollViewDidScroll:"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1HomeScreen~1scrollViewDidScroll(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"scrollViewDidScroll:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1HomeScreen~1browsingModeLabel\/title","value":"browsingModeLabel"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1HomeScreen~1browsingModeLabel\/fragments","value":[{"kind":"identifier","text":"browsingModeLabel"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1HomeScreen~1googleButton\/title","value":"googleButton"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1HomeScreen~1googleButton\/fragments","value":[{"kind":"identifier","text":"googleButton"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1HomeScreen~1mailButton\/title","value":"mailButton"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1HomeScreen~1mailButton\/fragments","value":[{"kind":"identifier","text":"mailButton"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1HomeScreen~1onGoogleSignIn(_:)\/title","value":"onGoogleSignIn:"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1HomeScreen~1onGoogleSignIn(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onGoogleSignIn:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1HomeScreen~1timeSlotLabel\/title","value":"timeSlotLabel"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1HomeScreen~1timeSlotLabel\/fragments","value":[{"kind":"identifier","text":"timeSlotLabel"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1HomeScreen~1browsingModeLoginLabel\/title","value":"browsingModeLoginLabel"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1HomeScreen~1browsingModeLoginLabel\/fragments","value":[{"kind":"identifier","text":"browsingModeLoginLabel"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1HomeScreen~1facebookButton\/title","value":"facebookButton"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1HomeScreen~1facebookButton\/fragments","value":[{"kind":"identifier","text":"facebookButton"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1HomeScreen~1browsingModeView\/title","value":"browsingModeView"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1HomeScreen~1browsingModeView\/fragments","value":[{"kind":"identifier","text":"browsingModeView"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1HomeScreen~1onMailSignIn(_:)\/title","value":"onMailSignIn:"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1HomeScreen~1onMailSignIn(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onMailSignIn:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1HomeScreen~1viewWillAppear(_:)\/title","value":"viewWillAppear:"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1HomeScreen~1viewWillAppear(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"viewWillAppear:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1HomeScreen~1viewDidAppear(_:)\/title","value":"viewDidAppear:"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1HomeScreen~1viewDidAppear(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"viewDidAppear:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1HomeScreen~1onHeaderTap()\/title","value":"onHeaderTap"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1HomeScreen~1onHeaderTap()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onHeaderTap"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1HomeScreen~1clockIcon\/title","value":"clockIcon"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1HomeScreen~1clockIcon\/fragments","value":[{"kind":"identifier","text":"clockIcon"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1HomeScreen~1onAppleSignIn(_:)\/title","value":"onAppleSignIn:"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1HomeScreen~1onAppleSignIn(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onAppleSignIn:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1HomeScreen~1onFacebookSignIn(_:)\/title","value":"onFacebookSignIn:"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1HomeScreen~1onFacebookSignIn(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onFacebookSignIn:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1HomeScreen~1featureFlagsButton\/title","value":"featureFlagsButton"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1HomeScreen~1featureFlagsButton\/fragments","value":[{"kind":"identifier","text":"featureFlagsButton"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1HomeScreen~1appleButton\/title","value":"appleButton"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1HomeScreen~1appleButton\/fragments","value":[{"kind":"identifier","text":"appleButton"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1HomeScreen~1searchBtn\/title","value":"searchBtn"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1HomeScreen~1searchBtn\/fragments","value":[{"kind":"identifier","text":"searchBtn"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1HomeScreen~1viewDidLoad()\/title","value":"viewDidLoad"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1HomeScreen~1viewDidLoad()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"viewDidLoad"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1DynamicLayoutScreen\/title","value":"DynamicLayoutScreen"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1DynamicLayoutScreen\/fragments","value":[{"kind":"identifier","text":"DynamicLayoutScreen"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1HomeScreen~1showSearch()\/title","value":"showSearch"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1HomeScreen~1showSearch()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"showSearch"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1HomeScreen~1homeSpinner\/title","value":"homeSpinner"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1HomeScreen~1homeSpinner\/fragments","value":[{"kind":"identifier","text":"homeSpinner"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1HomeScreen~1refreshBtn\/title","value":"refreshBtn"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1HomeScreen~1refreshBtn\/fragments","value":[{"kind":"identifier","text":"refreshBtn"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1HomeScreen~1showFeatureFlags(_:)\/title","value":"showFeatureFlags:"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1HomeScreen~1showFeatureFlags(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"showFeatureFlags:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1HomeScreen~1loginBenefitsViewContainer\/title","value":"loginBenefitsViewContainer"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1HomeScreen~1loginBenefitsViewContainer\/fragments","value":[{"kind":"identifier","text":"loginBenefitsViewContainer"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1HomeScreen~1refreshData()\/title","value":"refreshData"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1HomeScreen~1refreshData()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"refreshData"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1HomeScreen\/title","value":"HomeScreen"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1HomeScreen\/fragments","value":[{"kind":"identifier","text":"HomeScreen"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1HomeScreen~1onShowMapsView()\/title","value":"onShowMapsView"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1HomeScreen~1onShowMapsView()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onShowMapsView"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1HomeScreen~1headerLocationAndTimeContainer\/title","value":"headerLocationAndTimeContainer"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1HomeScreen~1headerLocationAndTimeContainer\/fragments","value":[{"kind":"identifier","text":"headerLocationAndTimeContainer"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}