{"primaryContentSections":[{"kind":"content","content":[{"anchor":"Overview","level":2,"type":"heading","text":"Overview"},{"type":"paragraph","inlineContent":[{"type":"text","text":"In-App Messages are a type of pop-up message that appear within the app (while it’s active). These messages can be confgirued though third party tools and are typically used to provide users with information, promotions, or prompts for taking specific actions. In-App Messages can be targeted to specific user groups based on user behavior, demographics, or other criteria."}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"For Yababa, these messages are managed and triggered by Braze."}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"Braze helps in creating and managing different campaings. A campaign helps to target specific user groups based on user behavior, demographics, or other criteria. Braze also provides an interface which helps to customize the in-app message with texts, images, and buttons to prompt specific actions."}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"For handling button actions, Braze allows to send deep link urls. Yababa app processes these deeplinks through "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/DeepLinkRouter"},{"type":"text","text":" class."}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"Yababa also uses In-App Messages to prompt Soft opt in for Push notifications. The message which can be customized via Braze allows us to describe the beniefits of enabling push notifications. If user responds with a yes, app requests to allow receiving push notifications (Hard opt in). This is discussed in detail in "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/PushNotificationsDocumentation"}]},{"anchor":"References","level":3,"type":"heading","text":"References"},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"reference","isActive":true,"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/BrazeManager"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"reference","isActive":true,"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/DeepLinkRouter"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"reference","isActive":true,"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/PushNotificationsManager"}]}]}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/yababa\/inappmessages"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/yababa\/inappmessages"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/InAppMessages","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Pop-up messages that appear within the app to provide users with information, promotions, and other relevant content."}],"kind":"article","metadata":{"roleHeading":"Article","title":"InApp Messages","role":"article","modules":[{"name":"Yababa"}]},"hierarchy":{"paths":[["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa"]]},"seeAlsoSections":[{"title":"Others","identifiers":["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/NetworkLayer","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AnalyticsDocumentation"],"generated":true}],"references":{"doc://com.yababaGmbH.yababa/documentation/Yababa/PushNotificationsDocumentation":{"role":"collectionGroup","title":"Push Notifications Manager","abstract":[{"type":"text","text":"Requesting permission for Push Notifications and receiving them"}],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/PushNotificationsDocumentation","kind":"article","type":"topic","url":"\/documentation\/yababa\/pushnotificationsdocumentation"},"doc://com.yababaGmbH.yababa/documentation/Yababa/DeepLinkRouter":{"role":"symbol","title":"DeepLinkRouter","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DeepLinkRouter"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/DeepLinkRouter","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DeepLinkRouter"}],"url":"\/documentation\/yababa\/deeplinkrouter"},"doc://com.yababaGmbH.yababa/documentation/Yababa/AnalyticsDocumentation":{"role":"article","title":"Analytics Manager","abstract":[{"type":"text","text":"Responsible for collecting events about user behavior and forwarding to third party analytics platforms."}],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AnalyticsDocumentation","kind":"article","type":"topic","url":"\/documentation\/yababa\/analyticsdocumentation"},"doc://com.yababaGmbH.yababa/documentation/Yababa":{"role":"collection","title":"Yababa","abstract":[{"type":"text","text":"Getting Started"}],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa","kind":"symbol","type":"topic","url":"\/documentation\/yababa"},"doc://com.yababaGmbH.yababa/documentation/Yababa/BrazeManager":{"role":"symbol","title":"BrazeManager","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"BrazeManager"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/BrazeManager","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"BrazeManager"}],"url":"\/documentation\/yababa\/brazemanager"},"doc://com.yababaGmbH.yababa/documentation/Yababa/NetworkLayer":{"role":"article","title":"Network Layer","abstract":[{"type":"text","text":"Responsible for managing the communication between the app and backend server"}],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/NetworkLayer","kind":"article","type":"topic","url":"\/documentation\/yababa\/networklayer"},"doc://com.yababaGmbH.yababa/documentation/Yababa/PushNotificationsManager":{"role":"symbol","title":"PushNotificationsManager","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PushNotificationsManager"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/PushNotificationsManager","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PushNotificationsManager"}],"url":"\/documentation\/yababa\/pushnotificationsmanager"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/topicSections","value":null},{"op":"replace","path":"\/seeAlsoSections","value":[{"title":"Others","identifiers":["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/NetworkLayer","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AnalyticsDocumentation"],"generated":true}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1DeepLinkRouter\/title","value":"DeepLinkRouter"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1DeepLinkRouter\/fragments","value":[{"kind":"identifier","text":"DeepLinkRouter"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1BrazeManager\/title","value":"BrazeManager"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1BrazeManager\/fragments","value":[{"kind":"identifier","text":"BrazeManager"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1PushNotificationsManager\/title","value":"PushNotificationsManager"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1PushNotificationsManager\/fragments","value":[{"kind":"identifier","text":"PushNotificationsManager"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}