{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"InDelegate"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObjectProtocol","preciseIdentifier":"c:objc(pl)NSObject"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/yababa\/indelegate"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/yababa\/indelegate"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.yababaGmbH.yababa\/objc(pl)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}],"identifier":{"url":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/InDelegate","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/InDelegate\/response(forChangeEmail:)","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/InDelegate\/response(forChangePassword:)","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/InDelegate\/response(forContactUs:)","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/InDelegate\/response(forCountryCoordinatesLat:lng:)","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/InDelegate\/response(forRequestTimezone:)","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/InDelegate\/response(forSignin:)","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/InDelegate\/response(forUpdateUserName:)","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/InDelegate\/response(forUpdateUserProfile:)","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/InDelegate\/responseGenericEntity(_:)"]}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"InDelegate"}],"title":"InDelegate","roleHeading":"Protocol","role":"symbol","symbolKind":"protocol","externalID":"c:objc(pl)InDelegate","modules":[{"name":"Yababa"}],"navigatorTitle":[{"kind":"identifier","text":"InDelegate"}]},"hierarchy":{"paths":[["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa"]]},"references":{"doc://com.yababaGmbH.yababa/documentation/Yababa/InDelegate/response(forChangeEmail:)":{"role":"symbol","title":"response(forChangeEmail:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"response"},{"kind":"text","text":"("},{"kind":"externalParam","text":"forChangeEmail"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ResponseClass","preciseIdentifier":"c:objc(cs)ResponseClass"},{"kind":"text","text":"!)"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/InDelegate\/response(forChangeEmail:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ResponseForChangeEmail:"}],"url":"\/documentation\/yababa\/indelegate\/response(forchangeemail:)"},"doc://com.yababaGmbH.yababa/documentation/Yababa/AppDelegate":{"role":"symbol","title":"AppDelegate","fragments":[{"kind":"identifier","text":"AppDelegate"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AppDelegate","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/appdelegate"},"doc://com.yababaGmbH.yababa/documentation/Yababa/InDelegate/response(forSignin:)":{"navigatorTitle":[{"kind":"identifier","text":"ResponseForSignin:"}],"role":"symbol","title":"response(forSignin:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"response"},{"kind":"text","text":"("},{"kind":"externalParam","text":"forSignin"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"LoginResponseClass","preciseIdentifier":"c:objc(cs)LoginResponseClass"},{"kind":"text","text":"!)"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/InDelegate\/response(forSignin:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/yababa\/indelegate\/response(forsignin:)"},"doc://com.yababaGmbH.yababa/documentation/Yababa/InDelegate/response(forUpdateUserName:)":{"role":"symbol","title":"response(forUpdateUserName:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"response"},{"kind":"text","text":"("},{"kind":"externalParam","text":"forUpdateUserName"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ResponseClass","preciseIdentifier":"c:objc(cs)ResponseClass"},{"kind":"text","text":"!)"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/InDelegate\/response(forUpdateUserName:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ResponseForUpdateUserName:"}],"url":"\/documentation\/yababa\/indelegate\/response(forupdateusername:)"},"doc://com.yababaGmbH.yababa/documentation/Yababa/InDelegate/response(forCountryCoordinatesLat:lng:)":{"navigatorTitle":[{"kind":"identifier","text":"ResponseForCountryCoordinatesLat:lng:"}],"role":"symbol","title":"response(forCountryCoordinatesLat:lng:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"response"},{"kind":"text","text":"("},{"kind":"externalParam","text":"forCountryCoordinatesLat"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"},{"kind":"text","text":", "},{"kind":"externalParam","text":"lng"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/InDelegate\/response(forCountryCoordinatesLat:lng:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/yababa\/indelegate\/response(forcountrycoordinateslat:lng:)"},"doc://com.yababaGmbH.yababa/documentation/Yababa/InDelegate/responseGenericEntity(_:)":{"navigatorTitle":[{"kind":"identifier","text":"ResponseGenericEntity:"}],"role":"symbol","title":"responseGenericEntity(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"responseGenericEntity"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"ResponseClass","preciseIdentifier":"c:objc(cs)ResponseClass"},{"kind":"text","text":"!)"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/InDelegate\/responseGenericEntity(_:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/yababa\/indelegate\/responsegenericentity(_:)"},"doc://com.yababaGmbH.yababa/documentation/Yababa/InDelegate/response(forContactUs:)":{"role":"symbol","title":"response(forContactUs:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"response"},{"kind":"text","text":"("},{"kind":"externalParam","text":"forContactUs"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ResponseClass","preciseIdentifier":"c:objc(cs)ResponseClass"},{"kind":"text","text":"!)"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/InDelegate\/response(forContactUs:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ResponseForContactUs:"}],"url":"\/documentation\/yababa\/indelegate\/response(forcontactus:)"},"doc://com.yababaGmbH.yababa/objc(pl)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)NSObject"},"doc://com.yababaGmbH.yababa/documentation/Yababa/InDelegate":{"role":"symbol","title":"InDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"InDelegate"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/InDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"InDelegate"}],"url":"\/documentation\/yababa\/indelegate"},"doc://com.yababaGmbH.yababa/documentation/Yababa/InDelegate/response(forUpdateUserProfile:)":{"navigatorTitle":[{"kind":"identifier","text":"ResponseForUpdateUserProfile:"}],"role":"symbol","title":"response(forUpdateUserProfile:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"response"},{"kind":"text","text":"("},{"kind":"externalParam","text":"forUpdateUserProfile"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ResponseClass","preciseIdentifier":"c:objc(cs)ResponseClass"},{"kind":"text","text":"!)"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/InDelegate\/response(forUpdateUserProfile:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/yababa\/indelegate\/response(forupdateuserprofile:)"},"doc://com.yababaGmbH.yababa/documentation/Yababa":{"role":"collection","title":"Yababa","abstract":[{"type":"text","text":"Getting Started"}],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa","kind":"symbol","type":"topic","url":"\/documentation\/yababa"},"doc://com.yababaGmbH.yababa/documentation/Yababa/InDelegate/response(forChangePassword:)":{"navigatorTitle":[{"kind":"identifier","text":"ResponseForChangePassword:"}],"role":"symbol","title":"response(forChangePassword:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"response"},{"kind":"text","text":"("},{"kind":"externalParam","text":"forChangePassword"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ResponseClass","preciseIdentifier":"c:objc(cs)ResponseClass"},{"kind":"text","text":"!)"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/InDelegate\/response(forChangePassword:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/yababa\/indelegate\/response(forchangepassword:)"},"doc://com.yababaGmbH.yababa/documentation/Yababa/InDelegate/response(forRequestTimezone:)":{"navigatorTitle":[{"kind":"identifier","text":"ResponseForRequestTimezone:"}],"role":"symbol","title":"response(forRequestTimezone:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"response"},{"kind":"text","text":"("},{"kind":"externalParam","text":"forRequestTimezone"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"!)"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/InDelegate\/response(forRequestTimezone:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/yababa\/indelegate\/response(forrequesttimezone:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Protocol"},{"op":"replace","path":"\/metadata\/title","value":"InDelegate"},{"op":"replace","path":"\/metadata\/symbolKind","value":"protocol"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"InDelegate"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"InDelegate"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/InDelegate\/response(forChangeEmail:)","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/InDelegate\/response(forChangePassword:)","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/InDelegate\/response(forContactUs:)","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/InDelegate\/response(forCountryCoordinatesLat:lng:)","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/InDelegate\/response(forRequestTimezone:)","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/InDelegate\/response(forSignin:)","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/InDelegate\/response(forUpdateUserName:)","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/InDelegate\/response(forUpdateUserProfile:)","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/InDelegate\/responseGenericEntity(_:)"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.yababaGmbH.yababa\/objc(pl)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AppDelegate"],"kind":"relationships","title":"Conforming Types","type":"conformingTypes"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"InDelegate"},{"kind":"text","text":"<"},{"kind":"keyword","text":"NSObject"},{"kind":"text","text":">"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1InDelegate~1response(forChangeEmail:)\/title","value":"ResponseForChangeEmail:"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1InDelegate~1response(forChangeEmail:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"ResponseForChangeEmail:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1InDelegate~1response(forSignin:)\/title","value":"ResponseForSignin:"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1InDelegate~1response(forSignin:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"ResponseForSignin:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1InDelegate~1response(forUpdateUserName:)\/title","value":"ResponseForUpdateUserName:"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1InDelegate~1response(forUpdateUserName:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"ResponseForUpdateUserName:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1InDelegate~1response(forCountryCoordinatesLat:lng:)\/title","value":"ResponseForCountryCoordinatesLat:lng:"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1InDelegate~1response(forCountryCoordinatesLat:lng:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"ResponseForCountryCoordinatesLat:lng:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1InDelegate~1responseGenericEntity(_:)\/title","value":"ResponseGenericEntity:"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1InDelegate~1responseGenericEntity(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"ResponseGenericEntity:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1InDelegate~1response(forContactUs:)\/title","value":"ResponseForContactUs:"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1InDelegate~1response(forContactUs:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"ResponseForContactUs:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1InDelegate\/title","value":"InDelegate"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1InDelegate\/fragments","value":[{"kind":"identifier","text":"InDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1InDelegate~1response(forUpdateUserProfile:)\/title","value":"ResponseForUpdateUserProfile:"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1InDelegate~1response(forUpdateUserProfile:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"ResponseForUpdateUserProfile:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1InDelegate~1response(forChangePassword:)\/title","value":"ResponseForChangePassword:"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1InDelegate~1response(forChangePassword:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"ResponseForChangePassword:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1InDelegate~1response(forRequestTimezone:)\/title","value":"ResponseForRequestTimezone:"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1InDelegate~1response(forRequestTimezone:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"ResponseForRequestTimezone:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}