{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"InRepository"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/yababa\/inrepository"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/yababa\/inrepository"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.yababaGmbH.yababa\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.yababaGmbH.yababa\/objc(pl)NSObject","doc:\/\/com.yababaGmbH.yababa\/12SkeletonView17AssociatedObjectsP","doc:\/\/com.yababaGmbH.yababa\/s7CVarArgP","doc:\/\/com.yababaGmbH.yababa\/s28CustomDebugStringConvertibleP","doc:\/\/com.yababaGmbH.yababa\/s23CustomStringConvertibleP","doc:\/\/com.yababaGmbH.yababa\/SQ","doc:\/\/com.yababaGmbH.yababa\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/InRepository","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/InRepository\/delegate"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/InRepository\/changeEmail(_:newEmail:password:)","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/InRepository\/changePassword(_:andOldPassword:andNewPassword:)","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/InRepository\/decodeJsonLoginResponse(_:)","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/InRepository\/decodeProfile(_:)","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/InRepository\/deserializeJsonRespone(_:)","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/InRepository\/getLocationForCountry(_:)","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/InRepository\/requestForTimeZone(withLong:andLat:)","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/InRepository\/sendContactUs(withToken:name:email:message:)","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/InRepository\/signIn(byEmail:password:idDevice:pushToken:referralCode:)","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/InRepository\/updateUserName(withToken:username:)","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/InRepository\/updateUserProfile(withToken:name:username:phoneNumber:)"]}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"InRepository"}],"title":"InRepository","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:objc(cs)InRepository","modules":[{"name":"Yababa"}],"navigatorTitle":[{"kind":"identifier","text":"InRepository"}]},"hierarchy":{"paths":[["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa"]]},"references":{"doc://com.yababaGmbH.yababa/documentation/Yababa/InRepository/Manager":{"role":"symbol","title":"Manager","fragments":[{"kind":"identifier","text":"Manager"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/InRepository\/Manager","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/inrepository\/manager"},"doc://com.yababaGmbH.yababa/documentation/Yababa/InRepository/changePassword(_:andOldPassword:andNewPassword:)":{"role":"symbol","title":"changePassword(_:andOldPassword:andNewPassword:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"changePassword"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"!, "},{"kind":"externalParam","text":"andOldPassword"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"!, "},{"kind":"externalParam","text":"andNewPassword"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"!)"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/InRepository\/changePassword(_:andOldPassword:andNewPassword:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ChangePassword:AndOldPassword:AndNewPassword:"}],"url":"\/documentation\/yababa\/inrepository\/changepassword(_:andoldpassword:andnewpassword:)"},"doc://com.yababaGmbH.yababa/documentation/Yababa/InRepository/requestForTimeZone(withLong:andLat:)":{"role":"symbol","title":"requestForTimeZone(withLong:andLat:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"requestForTimeZone"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withLong"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"},{"kind":"text","text":", "},{"kind":"externalParam","text":"andLat"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/InRepository\/requestForTimeZone(withLong:andLat:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"RequestForTimeZoneWithLong:andLat:"}],"url":"\/documentation\/yababa\/inrepository\/requestfortimezone(withlong:andlat:)"},"doc://com.yababaGmbH.yababa/documentation/Yababa/InRepository/changeEmail(_:newEmail:password:)":{"role":"symbol","title":"changeEmail(_:newEmail:password:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"changeEmail"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"!, "},{"kind":"externalParam","text":"newEmail"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"!, "},{"kind":"externalParam","text":"password"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"!)"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/InRepository\/changeEmail(_:newEmail:password:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ChangeEmail:newEmail:password:"}],"url":"\/documentation\/yababa\/inrepository\/changeemail(_:newemail:password:)"},"doc://com.yababaGmbH.yababa/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.yababaGmbH.yababa\/SQ"},"doc://com.yababaGmbH.yababa/documentation/Yababa/InRepository/signIn(byEmail:password:idDevice:pushToken:referralCode:)":{"role":"symbol","title":"signIn(byEmail:password:idDevice:pushToken:referralCode:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"signIn"},{"kind":"text","text":"("},{"kind":"externalParam","text":"byEmail"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"!, "},{"kind":"externalParam","text":"password"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"!, "},{"kind":"externalParam","text":"idDevice"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"!, "},{"kind":"externalParam","text":"pushToken"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"!, "},{"kind":"externalParam","text":"referralCode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?)"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/InRepository\/signIn(byEmail:password:idDevice:pushToken:referralCode:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SignInByEmail:Password:idDevice:pushToken:referralCode:"}],"url":"\/documentation\/yababa\/inrepository\/signin(byemail:password:iddevice:pushtoken:referralcode:)"},"doc://com.yababaGmbH.yababa/documentation/Yababa/InRepository/deserializeJsonRespone(_:)":{"role":"symbol","title":"deserializeJsonRespone(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"deserializeJsonRespone"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Data","preciseIdentifier":"s:10Foundation4DataV"},{"kind":"text","text":"!) -> ["},{"kind":"typeIdentifier","text":"AnyHashable","preciseIdentifier":"s:s11AnyHashableV"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]!"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/InRepository\/deserializeJsonRespone(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DeserializeJsonRespone:"}],"url":"\/documentation\/yababa\/inrepository\/deserializejsonrespone(_:)"},"doc://com.yababaGmbH.yababa/12SkeletonView17AssociatedObjectsP":{"type":"unresolvable","title":"SkeletonView.AssociatedObjects","identifier":"doc:\/\/com.yababaGmbH.yababa\/12SkeletonView17AssociatedObjectsP"},"doc://com.yababaGmbH.yababa/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)NSObject"},"doc://com.yababaGmbH.yababa/documentation/Yababa/InRepository":{"role":"symbol","title":"InRepository","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"InRepository"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/InRepository","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"InRepository"}],"url":"\/documentation\/yababa\/inrepository"},"doc://com.yababaGmbH.yababa/documentation/Yababa/InRepository/delegate":{"role":"symbol","title":"delegate","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"delegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"InDelegate","preciseIdentifier":"c:objc(pl)InDelegate"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/InRepository\/delegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"delegate"}],"url":"\/documentation\/yababa\/inrepository\/delegate"},"doc://com.yababaGmbH.yababa/documentation/Yababa/InRepository/sendContactUs(withToken:name:email:message:)":{"role":"symbol","title":"sendContactUs(withToken:name:email:message:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"sendContactUs"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withToken"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"!, "},{"kind":"externalParam","text":"name"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"!, "},{"kind":"externalParam","text":"email"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"!, "},{"kind":"externalParam","text":"message"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"!)"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/InRepository\/sendContactUs(withToken:name:email:message:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SendContactUsWithToken:Name:Email:Message:"}],"url":"\/documentation\/yababa\/inrepository\/sendcontactus(withtoken:name:email:message:)"},"doc://com.yababaGmbH.yababa/documentation/Yababa/InRepository/decodeJsonLoginResponse(_:)":{"role":"symbol","title":"decodeJsonLoginResponse(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"decodeJsonLoginResponse"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Data","preciseIdentifier":"s:10Foundation4DataV"},{"kind":"text","text":"!) -> "},{"kind":"typeIdentifier","text":"LoginResponseClass","preciseIdentifier":"c:objc(cs)LoginResponseClass"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/InRepository\/decodeJsonLoginResponse(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"decodeJsonLoginResponse:"}],"url":"\/documentation\/yababa\/inrepository\/decodejsonloginresponse(_:)"},"doc://com.yababaGmbH.yababa/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.yababaGmbH.yababa\/SH"},"doc://com.yababaGmbH.yababa/documentation/Yababa/InRepository/decodeProfile(_:)":{"role":"symbol","title":"decodeProfile(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"decodeProfile"},{"kind":"text","text":"(["},{"kind":"typeIdentifier","text":"AnyHashable","preciseIdentifier":"s:s11AnyHashableV"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]!) -> "},{"kind":"typeIdentifier","text":"ProfileClass","preciseIdentifier":"c:objc(cs)ProfileClass"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/InRepository\/decodeProfile(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"decodeProfile:"}],"url":"\/documentation\/yababa\/inrepository\/decodeprofile(_:)"},"doc://com.yababaGmbH.yababa/documentation/Yababa":{"role":"collection","title":"Yababa","abstract":[{"type":"text","text":"Getting Started"}],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa","kind":"symbol","type":"topic","url":"\/documentation\/yababa"},"doc://com.yababaGmbH.yababa/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.yababaGmbH.yababa\/s28CustomDebugStringConvertibleP"},"doc://com.yababaGmbH.yababa/documentation/Yababa/InRepository/getLocationForCountry(_:)":{"role":"symbol","title":"getLocationForCountry(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getLocationForCountry"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"!)"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/InRepository\/getLocationForCountry(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"getLocationForCountry:"}],"url":"\/documentation\/yababa\/inrepository\/getlocationforcountry(_:)"},"doc://com.yababaGmbH.yababa/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.yababaGmbH.yababa\/s7CVarArgP"},"doc://com.yababaGmbH.yababa/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.yababaGmbH.yababa\/s23CustomStringConvertibleP"},"doc://com.yababaGmbH.yababa/documentation/Yababa/InRepository/updateUserProfile(withToken:name:username:phoneNumber:)":{"role":"symbol","title":"updateUserProfile(withToken:name:username:phoneNumber:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"updateUserProfile"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withToken"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"!, "},{"kind":"externalParam","text":"name"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"!, "},{"kind":"externalParam","text":"username"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"!, "},{"kind":"externalParam","text":"phoneNumber"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"!)"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/InRepository\/updateUserProfile(withToken:name:username:phoneNumber:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"updateUserProfileWithToken:name:username:phoneNumber:"}],"url":"\/documentation\/yababa\/inrepository\/updateuserprofile(withtoken:name:username:phonenumber:)"},"doc://com.yababaGmbH.yababa/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(cs)NSObject"},"doc://com.yababaGmbH.yababa/documentation/Yababa/InRepository/updateUserName(withToken:username:)":{"role":"symbol","title":"updateUserName(withToken:username:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"updateUserName"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withToken"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"!, "},{"kind":"externalParam","text":"username"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"!)"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/InRepository\/updateUserName(withToken:username:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"UpdateUserNameWithToken:username:"}],"url":"\/documentation\/yababa\/inrepository\/updateusername(withtoken:username:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"InRepository"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"InRepository"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"InRepository"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Variables","identifiers":["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/InRepository\/Manager"]},{"title":"Instance Properties","identifiers":["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/InRepository\/delegate"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/InRepository\/changeEmail(_:newEmail:password:)","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/InRepository\/changePassword(_:andOldPassword:andNewPassword:)","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/InRepository\/decodeJsonLoginResponse(_:)","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/InRepository\/decodeProfile(_:)","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/InRepository\/deserializeJsonRespone(_:)","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/InRepository\/getLocationForCountry(_:)","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/InRepository\/requestForTimeZone(withLong:andLat:)","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/InRepository\/sendContactUs(withToken:name:email:message:)","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/InRepository\/signIn(byEmail:password:idDevice:pushToken:referralCode:)","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/InRepository\/updateUserName(withToken:username:)","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/InRepository\/updateUserProfile(withToken:name:username:phoneNumber:)"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.yababaGmbH.yababa\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"InRepository"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1InRepository~1changePassword(_:andOldPassword:andNewPassword:)\/title","value":"ChangePassword:AndOldPassword:AndNewPassword:"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1InRepository~1changePassword(_:andOldPassword:andNewPassword:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"ChangePassword:AndOldPassword:AndNewPassword:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1InRepository~1requestForTimeZone(withLong:andLat:)\/title","value":"RequestForTimeZoneWithLong:andLat:"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1InRepository~1requestForTimeZone(withLong:andLat:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"RequestForTimeZoneWithLong:andLat:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1InRepository~1changeEmail(_:newEmail:password:)\/title","value":"ChangeEmail:newEmail:password:"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1InRepository~1changeEmail(_:newEmail:password:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"ChangeEmail:newEmail:password:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1InRepository~1signIn(byEmail:password:idDevice:pushToken:referralCode:)\/title","value":"SignInByEmail:Password:idDevice:pushToken:referralCode:"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1InRepository~1signIn(byEmail:password:idDevice:pushToken:referralCode:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"SignInByEmail:Password:idDevice:pushToken:referralCode:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1InRepository~1deserializeJsonRespone(_:)\/title","value":"DeserializeJsonRespone:"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1InRepository~1deserializeJsonRespone(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"DeserializeJsonRespone:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1InRepository\/title","value":"InRepository"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1InRepository\/fragments","value":[{"kind":"identifier","text":"InRepository"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1InRepository~1delegate\/title","value":"delegate"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1InRepository~1delegate\/fragments","value":[{"kind":"identifier","text":"delegate"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1InRepository~1sendContactUs(withToken:name:email:message:)\/title","value":"SendContactUsWithToken:Name:Email:Message:"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1InRepository~1sendContactUs(withToken:name:email:message:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"SendContactUsWithToken:Name:Email:Message:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1InRepository~1decodeJsonLoginResponse(_:)\/title","value":"decodeJsonLoginResponse:"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1InRepository~1decodeJsonLoginResponse(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"decodeJsonLoginResponse:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1InRepository~1decodeProfile(_:)\/title","value":"decodeProfile:"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1InRepository~1decodeProfile(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"decodeProfile:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1InRepository~1getLocationForCountry(_:)\/title","value":"getLocationForCountry:"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1InRepository~1getLocationForCountry(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"getLocationForCountry:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1InRepository~1updateUserProfile(withToken:name:username:phoneNumber:)\/title","value":"updateUserProfileWithToken:name:username:phoneNumber:"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1InRepository~1updateUserProfile(withToken:name:username:phoneNumber:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"updateUserProfileWithToken:name:username:phoneNumber:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1InRepository~1updateUserName(withToken:username:)\/title","value":"UpdateUserNameWithToken:username:"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1InRepository~1updateUserName(withToken:username:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"UpdateUserNameWithToken:username:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}