{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"JoinSceneViewController"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/yababa\/joinsceneviewcontroller"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/yababa\/joinsceneviewcontroller"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/MasterViewController"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.yababaGmbH.yababa\/objc(pl)NSCoding","doc:\/\/com.yababaGmbH.yababa\/objc(pl)NSExtensionRequestHandling","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/JoinSceneViewControllerProtocol","doc:\/\/com.yababaGmbH.yababa\/objc(pl)NSObject","doc:\/\/com.yababaGmbH.yababa\/12SkeletonView17AssociatedObjectsP","doc:\/\/com.yababaGmbH.yababa\/s7CVarArgP","doc:\/\/com.yababaGmbH.yababa\/s28CustomDebugStringConvertibleP","doc:\/\/com.yababaGmbH.yababa\/s23CustomStringConvertibleP","doc:\/\/com.yababaGmbH.yababa\/SQ","doc:\/\/com.yababaGmbH.yababa\/SH","doc:\/\/com.yababaGmbH.yababa\/s8SendableP","doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIActivityItemsConfigurationProviding","doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIAppearanceContainer","doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIContentContainer","doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIFocusEnvironment","doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIPasteConfigurationSupporting","doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIResponderStandardEditActions","doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIStateRestoring","doc:\/\/com.yababaGmbH.yababa\/objc(pl)UITextFieldDelegate","doc:\/\/com.yababaGmbH.yababa\/objc(pl)UITraitEnvironment","doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIUserActivityRestoring"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/JoinSceneViewController","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/JoinSceneViewController\/emailSuggestionBtn","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/JoinSceneViewController\/emailTextField","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/JoinSceneViewController\/helloLabel","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/JoinSceneViewController\/interactor","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/JoinSceneViewController\/nextBtn","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/JoinSceneViewController\/pleaseEnterYourEmailAddressLabel","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/JoinSceneViewController\/sloganLabel","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/JoinSceneViewController\/smallSpinner"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/JoinSceneViewController\/automateContinueWithEmailAddress(_:)","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/JoinSceneViewController\/dellocate()","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/JoinSceneViewController\/hideSpinner()","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/JoinSceneViewController\/onNext()","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/JoinSceneViewController\/showSpinner()","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/JoinSceneViewController\/textFieldDidChange(_:)","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/JoinSceneViewController\/updateNextButton(isEnabled:)","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/JoinSceneViewController\/viewDidAppear(_:)","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/JoinSceneViewController\/viewDidDisappear(_:)","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/JoinSceneViewController\/viewDidLoad()","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/JoinSceneViewController\/viewWillAppear(_:)"]},{"title":"Default Implementations","identifiers":["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/JoinSceneViewController\/JoinSceneViewControllerProtocol-Implementations","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/JoinSceneViewController\/UITextFieldDelegate-Implementations"],"generated":true}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"JoinSceneViewController"}],"title":"JoinSceneViewController","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@Yababa@objc(cs)JoinSceneViewController","modules":[{"name":"Yababa"}],"navigatorTitle":[{"kind":"identifier","text":"JoinSceneViewController"}]},"hierarchy":{"paths":[["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa"]]},"references":{"doc://com.yababaGmbH.yababa/objc(pl)UIActivityItemsConfigurationProviding":{"type":"unresolvable","title":"UIKit.UIActivityItemsConfigurationProviding","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIActivityItemsConfigurationProviding"},"doc://com.yababaGmbH.yababa/objc(pl)UIStateRestoring":{"type":"unresolvable","title":"UIKit.UIStateRestoring","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIStateRestoring"},"doc://com.yababaGmbH.yababa/objc(pl)UIFocusEnvironment":{"type":"unresolvable","title":"UIKit.UIFocusEnvironment","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIFocusEnvironment"},"doc://com.yababaGmbH.yababa/documentation/Yababa/JoinSceneViewController/nextBtn":{"role":"symbol","title":"nextBtn","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"nextBtn"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIButton","preciseIdentifier":"c:objc(cs)UIButton"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/JoinSceneViewController\/nextBtn","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"nextBtn"}],"url":"\/documentation\/yababa\/joinsceneviewcontroller\/nextbtn"},"doc://com.yababaGmbH.yababa/documentation/Yababa/JoinSceneViewController/initWithCoder:":{"role":"symbol","title":"initWithCoder:","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithCoder:"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/JoinSceneViewController\/initWithCoder:","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithCoder:"}],"url":"\/documentation\/yababa\/joinsceneviewcontroller\/initwithcoder:"},"doc://com.yababaGmbH.yababa/documentation/Yababa/JoinSceneViewController/UITextFieldDelegate-Implementations":{"role":"collectionGroup","title":"UITextFieldDelegate Implementations","abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/JoinSceneViewController\/UITextFieldDelegate-Implementations","kind":"article","type":"topic","url":"\/documentation\/yababa\/joinsceneviewcontroller\/uitextfielddelegate-implementations"},"doc://com.yababaGmbH.yababa/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/com.yababaGmbH.yababa\/s8SendableP"},"doc://com.yababaGmbH.yababa/objc(pl)UIContentContainer":{"type":"unresolvable","title":"UIKit.UIContentContainer","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIContentContainer"},"doc://com.yababaGmbH.yababa/objc(pl)NSExtensionRequestHandling":{"type":"unresolvable","title":"Foundation.NSExtensionRequestHandling","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)NSExtensionRequestHandling"},"doc://com.yababaGmbH.yababa/documentation/Yababa/JoinSceneViewController/automateContinueWithEmailAddress(_:)":{"role":"symbol","title":"automateContinueWithEmailAddress(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"automateContinueWithEmailAddress"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/JoinSceneViewController\/automateContinueWithEmailAddress(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"automateContinueWithEmailAddress:"}],"url":"\/documentation\/yababa\/joinsceneviewcontroller\/automatecontinuewithemailaddress(_:)"},"doc://com.yababaGmbH.yababa/objc(pl)UITraitEnvironment":{"type":"unresolvable","title":"UIKit.UITraitEnvironment","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)UITraitEnvironment"},"doc://com.yababaGmbH.yababa/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.yababaGmbH.yababa\/s23CustomStringConvertibleP"},"doc://com.yababaGmbH.yababa/objc(pl)UIAppearanceContainer":{"type":"unresolvable","title":"UIKit.UIAppearanceContainer","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIAppearanceContainer"},"doc://com.yababaGmbH.yababa/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)NSObject"},"doc://com.yababaGmbH.yababa/documentation/Yababa/JoinSceneViewController/initWithNibName:bundle:":{"role":"symbol","title":"initWithNibName:bundle:","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithNibName:bundle:"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/JoinSceneViewController\/initWithNibName:bundle:","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithNibName:bundle:"}],"url":"\/documentation\/yababa\/joinsceneviewcontroller\/initwithnibname:bundle:"},"doc://com.yababaGmbH.yababa/documentation/Yababa/JoinSceneViewController/sloganLabel":{"role":"symbol","title":"sloganLabel","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"sloganLabel"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UILabel","preciseIdentifier":"c:objc(cs)UILabel"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/JoinSceneViewController\/sloganLabel","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"sloganLabel"}],"url":"\/documentation\/yababa\/joinsceneviewcontroller\/sloganlabel"},"doc://com.yababaGmbH.yababa/documentation/Yababa/JoinSceneViewController/hideSpinner()":{"role":"symbol","title":"hideSpinner()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"hideSpinner"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/JoinSceneViewController\/hideSpinner()","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/joinsceneviewcontroller\/hidespinner()"},"doc://com.yababaGmbH.yababa/documentation/Yababa/JoinSceneViewController/updateNextButton(isEnabled:)":{"role":"symbol","title":"updateNextButton(isEnabled:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"updateNextButton"},{"kind":"text","text":"("},{"kind":"externalParam","text":"isEnabled"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/JoinSceneViewController\/updateNextButton(isEnabled:)","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/joinsceneviewcontroller\/updatenextbutton(isenabled:)"},"doc://com.yababaGmbH.yababa/documentation/Yababa/JoinSceneViewController/textFieldDidChange(_:)":{"role":"symbol","title":"textFieldDidChange(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"textFieldDidChange"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UITextField","preciseIdentifier":"c:objc(cs)UITextField"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/JoinSceneViewController\/textFieldDidChange(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"textFieldDidChange:"}],"url":"\/documentation\/yababa\/joinsceneviewcontroller\/textfielddidchange(_:)"},"doc://com.yababaGmbH.yababa/objc(pl)UIResponderStandardEditActions":{"type":"unresolvable","title":"UIKit.UIResponderStandardEditActions","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIResponderStandardEditActions"},"doc://com.yababaGmbH.yababa/objc(pl)UIUserActivityRestoring":{"type":"unresolvable","title":"UIKit.UIUserActivityRestoring","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIUserActivityRestoring"},"doc://com.yababaGmbH.yababa/objc(pl)UIPasteConfigurationSupporting":{"type":"unresolvable","title":"UIKit.UIPasteConfigurationSupporting","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIPasteConfigurationSupporting"},"doc://com.yababaGmbH.yababa/documentation/Yababa/JoinSceneViewController/onNext()":{"role":"symbol","title":"onNext()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onNext"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/JoinSceneViewController\/onNext()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"onNext"}],"url":"\/documentation\/yababa\/joinsceneviewcontroller\/onnext()"},"doc://com.yababaGmbH.yababa/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.yababaGmbH.yababa\/SQ"},"doc://com.yababaGmbH.yababa/documentation/Yababa/JoinSceneViewController/emailTextField":{"role":"symbol","title":"emailTextField","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"emailTextField"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UITextField","preciseIdentifier":"c:objc(cs)UITextField"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/JoinSceneViewController\/emailTextField","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"emailTextField"}],"url":"\/documentation\/yababa\/joinsceneviewcontroller\/emailtextfield"},"doc://com.yababaGmbH.yababa/documentation/Yababa/JoinSceneViewController/interactor":{"role":"symbol","title":"interactor","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"interactor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"JoinSceneInteractorProtocol","preciseIdentifier":"s:6Yababa27JoinSceneInteractorProtocolP"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/JoinSceneViewController\/interactor","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/joinsceneviewcontroller\/interactor"},"doc://com.yababaGmbH.yababa/documentation/Yababa/JoinSceneViewController/dellocate()":{"role":"symbol","title":"dellocate()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"dellocate"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/JoinSceneViewController\/dellocate()","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/joinsceneviewcontroller\/dellocate()"},"doc://com.yababaGmbH.yababa/documentation/Yababa/MasterViewController":{"role":"symbol","title":"MasterViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MasterViewController"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/MasterViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MasterViewController"}],"url":"\/documentation\/yababa\/masterviewcontroller"},"doc://com.yababaGmbH.yababa/documentation/Yababa/JoinSceneViewController/smallSpinner":{"role":"symbol","title":"smallSpinner","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"smallSpinner"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIActivityIndicatorView","preciseIdentifier":"c:objc(cs)UIActivityIndicatorView"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/JoinSceneViewController\/smallSpinner","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"smallSpinner"}],"url":"\/documentation\/yababa\/joinsceneviewcontroller\/smallspinner"},"doc://com.yababaGmbH.yababa/documentation/Yababa/JoinSceneViewController/helloLabel":{"role":"symbol","title":"helloLabel","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"helloLabel"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UILabel","preciseIdentifier":"c:objc(cs)UILabel"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/JoinSceneViewController\/helloLabel","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"helloLabel"}],"url":"\/documentation\/yababa\/joinsceneviewcontroller\/hellolabel"},"doc://com.yababaGmbH.yababa/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.yababaGmbH.yababa\/s28CustomDebugStringConvertibleP"},"doc://com.yababaGmbH.yababa/documentation/Yababa/JoinSceneViewController":{"role":"symbol","title":"JoinSceneViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"JoinSceneViewController"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/JoinSceneViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"JoinSceneViewController"}],"url":"\/documentation\/yababa\/joinsceneviewcontroller"},"doc://com.yababaGmbH.yababa/documentation/Yababa/JoinSceneViewController/viewDidLoad()":{"role":"symbol","title":"viewDidLoad()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"viewDidLoad"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/JoinSceneViewController\/viewDidLoad()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"viewDidLoad"}],"url":"\/documentation\/yababa\/joinsceneviewcontroller\/viewdidload()"},"doc://com.yababaGmbH.yababa/documentation/Yababa/JoinSceneViewController/viewDidDisappear(_:)":{"role":"symbol","title":"viewDidDisappear(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"viewDidDisappear"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/JoinSceneViewController\/viewDidDisappear(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"viewDidDisappear:"}],"url":"\/documentation\/yababa\/joinsceneviewcontroller\/viewdiddisappear(_:)"},"doc://com.yababaGmbH.yababa/documentation/Yababa/JoinSceneViewController/emailSuggestionBtn":{"role":"symbol","title":"emailSuggestionBtn","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"emailSuggestionBtn"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIBarButtonItem","preciseIdentifier":"c:objc(cs)UIBarButtonItem"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/JoinSceneViewController\/emailSuggestionBtn","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/joinsceneviewcontroller\/emailsuggestionbtn"},"doc://com.yababaGmbH.yababa/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.yababaGmbH.yababa\/SH"},"doc://com.yababaGmbH.yababa/documentation/Yababa/JoinSceneViewController/JoinSceneViewControllerProtocol-Implementations":{"role":"collectionGroup","title":"JoinSceneViewControllerProtocol Implementations","abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/JoinSceneViewController\/JoinSceneViewControllerProtocol-Implementations","kind":"article","type":"topic","url":"\/documentation\/yababa\/joinsceneviewcontroller\/joinsceneviewcontrollerprotocol-implementations"},"doc://com.yababaGmbH.yababa/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.yababaGmbH.yababa\/s7CVarArgP"},"doc://com.yababaGmbH.yababa/documentation/Yababa/JoinSceneViewController/pleaseEnterYourEmailAddressLabel":{"role":"symbol","title":"pleaseEnterYourEmailAddressLabel","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"pleaseEnterYourEmailAddressLabel"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UILabel","preciseIdentifier":"c:objc(cs)UILabel"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/JoinSceneViewController\/pleaseEnterYourEmailAddressLabel","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"pleaseEnterYourEmailAddressLabel"}],"url":"\/documentation\/yababa\/joinsceneviewcontroller\/pleaseenteryouremailaddresslabel"},"doc://com.yababaGmbH.yababa/objc(pl)UITextFieldDelegate":{"type":"unresolvable","title":"UIKit.UITextFieldDelegate","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)UITextFieldDelegate"},"doc://com.yababaGmbH.yababa/documentation/Yababa/JoinSceneViewController/viewDidAppear(_:)":{"role":"symbol","title":"viewDidAppear(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"viewDidAppear"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/JoinSceneViewController\/viewDidAppear(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"viewDidAppear:"}],"url":"\/documentation\/yababa\/joinsceneviewcontroller\/viewdidappear(_:)"},"doc://com.yababaGmbH.yababa/documentation/Yababa":{"role":"collection","title":"Yababa","abstract":[{"type":"text","text":"Getting Started"}],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa","kind":"symbol","type":"topic","url":"\/documentation\/yababa"},"doc://com.yababaGmbH.yababa/12SkeletonView17AssociatedObjectsP":{"type":"unresolvable","title":"SkeletonView.AssociatedObjects","identifier":"doc:\/\/com.yababaGmbH.yababa\/12SkeletonView17AssociatedObjectsP"},"doc://com.yababaGmbH.yababa/documentation/Yababa/JoinSceneViewController/showSpinner()":{"role":"symbol","title":"showSpinner()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"showSpinner"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/JoinSceneViewController\/showSpinner()","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/joinsceneviewcontroller\/showspinner()"},"doc://com.yababaGmbH.yababa/objc(pl)NSCoding":{"type":"unresolvable","title":"Foundation.NSCoding","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)NSCoding"},"doc://com.yababaGmbH.yababa/documentation/Yababa/JoinSceneViewController/viewWillAppear(_:)":{"role":"symbol","title":"viewWillAppear(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"viewWillAppear"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/JoinSceneViewController\/viewWillAppear(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"viewWillAppear:"}],"url":"\/documentation\/yababa\/joinsceneviewcontroller\/viewwillappear(_:)"},"doc://com.yababaGmbH.yababa/documentation/Yababa/JoinSceneViewControllerProtocol":{"role":"symbol","title":"JoinSceneViewControllerProtocol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"JoinSceneViewControllerProtocol"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/JoinSceneViewControllerProtocol","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"JoinSceneViewControllerProtocol"}],"url":"\/documentation\/yababa\/joinsceneviewcontrollerprotocol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"JoinSceneViewController"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"JoinSceneViewController"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"JoinSceneViewController"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/JoinSceneViewController\/emailTextField","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/JoinSceneViewController\/helloLabel","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/JoinSceneViewController\/nextBtn","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/JoinSceneViewController\/pleaseEnterYourEmailAddressLabel","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/JoinSceneViewController\/sloganLabel","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/JoinSceneViewController\/smallSpinner"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/JoinSceneViewController\/automateContinueWithEmailAddress(_:)","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/JoinSceneViewController\/initWithCoder:","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/JoinSceneViewController\/initWithNibName:bundle:","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/JoinSceneViewController\/onNext()","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/JoinSceneViewController\/textFieldDidChange(_:)","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/JoinSceneViewController\/viewDidAppear(_:)","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/JoinSceneViewController\/viewDidDisappear(_:)","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/JoinSceneViewController\/viewDidLoad()","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/JoinSceneViewController\/viewWillAppear(_:)"]},{"title":"Default Implementations","identifiers":["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/JoinSceneViewController\/UITextFieldDelegate-Implementations"],"generated":true}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/MasterViewController"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"JoinSceneViewController"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/MasterViewController","preciseIdentifier":"c:@M@Yababa@objc(cs)MasterViewController","text":"MasterViewController"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1JoinSceneViewController~1nextBtn\/title","value":"nextBtn"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1JoinSceneViewController~1nextBtn\/fragments","value":[{"kind":"identifier","text":"nextBtn"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1JoinSceneViewController~1automateContinueWithEmailAddress(_:)\/title","value":"automateContinueWithEmailAddress:"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1JoinSceneViewController~1automateContinueWithEmailAddress(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"automateContinueWithEmailAddress:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1JoinSceneViewController~1sloganLabel\/title","value":"sloganLabel"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1JoinSceneViewController~1sloganLabel\/fragments","value":[{"kind":"identifier","text":"sloganLabel"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1JoinSceneViewController~1textFieldDidChange(_:)\/title","value":"textFieldDidChange:"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1JoinSceneViewController~1textFieldDidChange(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"textFieldDidChange:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1JoinSceneViewController~1onNext()\/title","value":"onNext"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1JoinSceneViewController~1onNext()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onNext"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1JoinSceneViewController~1emailTextField\/title","value":"emailTextField"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1JoinSceneViewController~1emailTextField\/fragments","value":[{"kind":"identifier","text":"emailTextField"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1MasterViewController\/title","value":"MasterViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1MasterViewController\/fragments","value":[{"kind":"identifier","text":"MasterViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1JoinSceneViewController~1smallSpinner\/title","value":"smallSpinner"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1JoinSceneViewController~1smallSpinner\/fragments","value":[{"kind":"identifier","text":"smallSpinner"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1JoinSceneViewController~1helloLabel\/title","value":"helloLabel"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1JoinSceneViewController~1helloLabel\/fragments","value":[{"kind":"identifier","text":"helloLabel"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1JoinSceneViewController\/title","value":"JoinSceneViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1JoinSceneViewController\/fragments","value":[{"kind":"identifier","text":"JoinSceneViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1JoinSceneViewController~1viewDidLoad()\/title","value":"viewDidLoad"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1JoinSceneViewController~1viewDidLoad()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"viewDidLoad"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1JoinSceneViewController~1viewDidDisappear(_:)\/title","value":"viewDidDisappear:"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1JoinSceneViewController~1viewDidDisappear(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"viewDidDisappear:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1JoinSceneViewController~1pleaseEnterYourEmailAddressLabel\/title","value":"pleaseEnterYourEmailAddressLabel"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1JoinSceneViewController~1pleaseEnterYourEmailAddressLabel\/fragments","value":[{"kind":"identifier","text":"pleaseEnterYourEmailAddressLabel"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1JoinSceneViewController~1viewDidAppear(_:)\/title","value":"viewDidAppear:"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1JoinSceneViewController~1viewDidAppear(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"viewDidAppear:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1JoinSceneViewController~1viewWillAppear(_:)\/title","value":"viewWillAppear:"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1JoinSceneViewController~1viewWillAppear(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"viewWillAppear:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}