{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objcMembers"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"LocalUserStateManager"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/yababa\/localuserstatemanager"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/yababa\/localuserstatemanager"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.yababaGmbH.yababa\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.yababaGmbH.yababa\/objc(pl)NSObject","doc:\/\/com.yababaGmbH.yababa\/12SkeletonView17AssociatedObjectsP","doc:\/\/com.yababaGmbH.yababa\/s7CVarArgP","doc:\/\/com.yababaGmbH.yababa\/s28CustomDebugStringConvertibleP","doc:\/\/com.yababaGmbH.yababa\/s23CustomStringConvertibleP","doc:\/\/com.yababaGmbH.yababa\/SQ","doc:\/\/com.yababaGmbH.yababa\/SH","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/UserStateManagerProtocol"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/LocalUserStateManager","interfaceLanguage":"swift"},"topicSections":[{"title":"Structures","identifiers":["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/LocalUserStateManager\/StateKeys"]},{"title":"Instance Properties","identifiers":["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/LocalUserStateManager\/discountsTabNeedsToBeViewed","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/LocalUserStateManager\/isDefaultBackendVoucherApplied","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/LocalUserStateManager\/onSelectedVoucherIdChanged","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/LocalUserStateManager\/selectedVoucher"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/LocalUserStateManager\/clearState()","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/LocalUserStateManager\/getAddress()","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/LocalUserStateManager\/getAppVersionWhichForcedCatalogeRefresh()","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/LocalUserStateManager\/getCurrentUser()","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/LocalUserStateManager\/getDeliveryTimeSlot()","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/LocalUserStateManager\/getDeliveryTimeSlotWithVerification(completion:)","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/LocalUserStateManager\/getPushToken()","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/LocalUserStateManager\/getReferralCode()","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/LocalUserStateManager\/getSelectedLanguage()","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/LocalUserStateManager\/getSelectedPaymentCardID()","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/LocalUserStateManager\/getUserAnsweredSoftIn()","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/LocalUserStateManager\/getUserFirstAndLastName()","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/LocalUserStateManager\/getUserHasReadBannerInfo()","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/LocalUserStateManager\/getUserLastestReferralCode()","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/LocalUserStateManager\/getUserProfile()","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/LocalUserStateManager\/getUserPushSubscriptionStatus()","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/LocalUserStateManager\/getUserUnreadFreshChatMessage()","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/LocalUserStateManager\/hasAnAddress()","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/LocalUserStateManager\/isLoggedInUserAppleUser()","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/LocalUserStateManager\/isLoggedInUserFacebookUser()","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/LocalUserStateManager\/isLoggedInUserGoogleUser()","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/LocalUserStateManager\/isUserInBrowsingMode()","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/LocalUserStateManager\/loadState()","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/LocalUserStateManager\/setAddress(_:)","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/LocalUserStateManager\/setAppCurrentVersionWhichForcedCatalogeRefresh()","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/LocalUserStateManager\/setDeliveryTimeSlot(_:)","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/LocalUserStateManager\/setHasAnAddress(_:)","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/LocalUserStateManager\/setSelectedLanguage(_:)","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/LocalUserStateManager\/setSelectedPaymentCardID(_:)","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/LocalUserStateManager\/setUserAnsweredSoftIn(_:)","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/LocalUserStateManager\/setUserEmailSubscriptionStatus(_:)","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/LocalUserStateManager\/setUserHasReadBannerInfo(_:)","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/LocalUserStateManager\/setUserLatestReferralCode(_:)","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/LocalUserStateManager\/setUserPushSubscriptionStatus(_:)","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/LocalUserStateManager\/setUserUnreadFreshChatMessage(_:)","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/LocalUserStateManager\/syncBrazeUserSubscriptionStatusToDevice(completion:)","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/LocalUserStateManager\/syncUserProfile()","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/LocalUserStateManager\/userNeedsToCompleteProfile(rightBeforeBooking:)"]},{"title":"Type Properties","identifiers":["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/LocalUserStateManager\/defaultInstance"]}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"LocalUserStateManager"}],"title":"LocalUserStateManager","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@Yababa@objc(cs)LocalUserStateManager","modules":[{"name":"Yababa"}],"navigatorTitle":[{"kind":"identifier","text":"LocalUserStateManager"}]},"hierarchy":{"paths":[["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa"]]},"references":{"doc://com.yababaGmbH.yababa/documentation/Yababa/LocalUserStateManager/getAppVersionWhichForcedCatalogeRefresh()":{"role":"symbol","title":"getAppVersionWhichForcedCatalogeRefresh()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getAppVersionWhichForcedCatalogeRefresh"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/LocalUserStateManager\/getAppVersionWhichForcedCatalogeRefresh()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"getAppVersionWhichForcedCatalogeRefresh"}],"url":"\/documentation\/yababa\/localuserstatemanager\/getappversionwhichforcedcatalogerefresh()"},"doc://com.yababaGmbH.yababa/documentation/Yababa/LocalUserStateManager/syncUserProfile()":{"role":"symbol","title":"syncUserProfile()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"syncUserProfile"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/LocalUserStateManager\/syncUserProfile()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"syncUserProfile"}],"url":"\/documentation\/yababa\/localuserstatemanager\/syncuserprofile()"},"doc://com.yababaGmbH.yababa/documentation/Yababa/LocalUserStateManager/setSelectedPaymentCardID(_:)":{"role":"symbol","title":"setSelectedPaymentCardID(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setSelectedPaymentCardID"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/LocalUserStateManager\/setSelectedPaymentCardID(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"setSelectedPaymentCardID:"}],"url":"\/documentation\/yababa\/localuserstatemanager\/setselectedpaymentcardid(_:)"},"doc://com.yababaGmbH.yababa/documentation/Yababa/LocalUserStateManager/getUserPushSubscriptionStatus()":{"role":"symbol","title":"getUserPushSubscriptionStatus()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getUserPushSubscriptionStatus"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"SubscriptionStatus","preciseIdentifier":"c:@M@Yababa@E@SubscriptionStatus"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/LocalUserStateManager\/getUserPushSubscriptionStatus()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"getUserPushSubscriptionStatus"}],"url":"\/documentation\/yababa\/localuserstatemanager\/getuserpushsubscriptionstatus()"},"doc://com.yababaGmbH.yababa/documentation/Yababa/LocalUserStateManager/isUserInBrowsingMode()":{"role":"symbol","title":"isUserInBrowsingMode()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"isUserInBrowsingMode"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/LocalUserStateManager\/isUserInBrowsingMode()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"isUserInBrowsingMode"}],"url":"\/documentation\/yababa\/localuserstatemanager\/isuserinbrowsingmode()"},"doc://com.yababaGmbH.yababa/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.yababaGmbH.yababa\/SH"},"doc://com.yababaGmbH.yababa/documentation/Yababa/LocalUserStateManager/setUserHasReadBannerInfo(_:)":{"role":"symbol","title":"setUserHasReadBannerInfo(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setUserHasReadBannerInfo"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/LocalUserStateManager\/setUserHasReadBannerInfo(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"setUserHasReadBannerInfo:"}],"url":"\/documentation\/yababa\/localuserstatemanager\/setuserhasreadbannerinfo(_:)"},"doc://com.yababaGmbH.yababa/documentation/Yababa/LocalUserStateManager/isLoggedInUserGoogleUser()":{"role":"symbol","title":"isLoggedInUserGoogleUser()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"isLoggedInUserGoogleUser"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/LocalUserStateManager\/isLoggedInUserGoogleUser()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"isLoggedInUserGoogleUser"}],"url":"\/documentation\/yababa\/localuserstatemanager\/isloggedinusergoogleuser()"},"doc://com.yababaGmbH.yababa/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(cs)NSObject"},"doc://com.yababaGmbH.yababa/documentation/Yababa/LocalUserStateManager/getAddress()":{"role":"symbol","title":"getAddress()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getAddress"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"Address","preciseIdentifier":"s:6Yababa7AddressC"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/LocalUserStateManager\/getAddress()","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/localuserstatemanager\/getaddress()"},"doc://com.yababaGmbH.yababa/documentation/Yababa/LocalUserStateManager/discountsTabNeedsToBeViewed":{"role":"symbol","title":"discountsTabNeedsToBeViewed","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"discountsTabNeedsToBeViewed"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/LocalUserStateManager\/discountsTabNeedsToBeViewed","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"discountsTabNeedsToBeViewed"}],"url":"\/documentation\/yababa\/localuserstatemanager\/discountstabneedstobeviewed"},"doc://com.yababaGmbH.yababa/documentation/Yababa/LocalUserStateManager/setAppCurrentVersionWhichForcedCatalogeRefresh()":{"role":"symbol","title":"setAppCurrentVersionWhichForcedCatalogeRefresh()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setAppCurrentVersionWhichForcedCatalogeRefresh"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/LocalUserStateManager\/setAppCurrentVersionWhichForcedCatalogeRefresh()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"setAppCurrentVersionWhichForcedCatalogeRefresh"}],"url":"\/documentation\/yababa\/localuserstatemanager\/setappcurrentversionwhichforcedcatalogerefresh()"},"doc://com.yababaGmbH.yababa/documentation/Yababa/LocalUserStateManager/getReferralCode()":{"role":"symbol","title":"getReferralCode()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getReferralCode"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/LocalUserStateManager\/getReferralCode()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"getReferralCode"}],"url":"\/documentation\/yababa\/localuserstatemanager\/getreferralcode()"},"doc://com.yababaGmbH.yababa/documentation/Yababa/LocalUserStateManager/setUserUnreadFreshChatMessage(_:)":{"role":"symbol","title":"setUserUnreadFreshChatMessage(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setUserUnreadFreshChatMessage"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/LocalUserStateManager\/setUserUnreadFreshChatMessage(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"setUserUnreadFreshChatMessage:"}],"url":"\/documentation\/yababa\/localuserstatemanager\/setuserunreadfreshchatmessage(_:)"},"doc://com.yababaGmbH.yababa/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)NSObject"},"doc://com.yababaGmbH.yababa/documentation/Yababa/LocalUserStateManager/getDeliveryTimeSlot()":{"role":"symbol","title":"getDeliveryTimeSlot()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getDeliveryTimeSlot"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"AvailabilityTimeSlot","preciseIdentifier":"s:6Yababa20AvailabilityTimeSlotC"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/LocalUserStateManager\/getDeliveryTimeSlot()","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/localuserstatemanager\/getdeliverytimeslot()"},"doc://com.yababaGmbH.yababa/documentation/Yababa/LocalUserStateManager/onSelectedVoucherIdChanged":{"role":"symbol","title":"onSelectedVoucherIdChanged","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"onSelectedVoucherIdChanged"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Notification","preciseIdentifier":"s:10Foundation12NotificationV"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"Name","preciseIdentifier":"s:10Foundation12NotificationV4Namea"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/LocalUserStateManager\/onSelectedVoucherIdChanged","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"onSelectedVoucherIdChanged"}],"url":"\/documentation\/yababa\/localuserstatemanager\/onselectedvoucheridchanged"},"doc://com.yababaGmbH.yababa/documentation/Yababa/LocalUserStateManager/setUserAnsweredSoftIn(_:)":{"role":"symbol","title":"setUserAnsweredSoftIn(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setUserAnsweredSoftIn"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/LocalUserStateManager\/setUserAnsweredSoftIn(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"setUserAnsweredSoftIn:"}],"url":"\/documentation\/yababa\/localuserstatemanager\/setuseransweredsoftin(_:)"},"doc://com.yababaGmbH.yababa/documentation/Yababa/LocalUserStateManager/hasAnAddress()":{"role":"symbol","title":"hasAnAddress()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"hasAnAddress"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/LocalUserStateManager\/hasAnAddress()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"hasAnAddress"}],"url":"\/documentation\/yababa\/localuserstatemanager\/hasanaddress()"},"doc://com.yababaGmbH.yababa/documentation/Yababa/LocalUserStateManager/setDeliveryTimeSlot(_:)":{"role":"symbol","title":"setDeliveryTimeSlot(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setDeliveryTimeSlot"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AvailabilityTimeSlot","preciseIdentifier":"s:6Yababa20AvailabilityTimeSlotC"},{"kind":"text","text":"?)"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/LocalUserStateManager\/setDeliveryTimeSlot(_:)","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/localuserstatemanager\/setdeliverytimeslot(_:)"},"doc://com.yababaGmbH.yababa/documentation/Yababa/LocalUserStateManager/getDeliveryTimeSlotWithVerification(completion:)":{"role":"symbol","title":"getDeliveryTimeSlotWithVerification(completion:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getDeliveryTimeSlotWithVerification"},{"kind":"text","text":"("},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": ("},{"kind":"typeIdentifier","text":"AvailabilityTimeSlot","preciseIdentifier":"s:6Yababa20AvailabilityTimeSlotC"},{"kind":"text","text":"?) -> ())"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/LocalUserStateManager\/getDeliveryTimeSlotWithVerification(completion:)","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/localuserstatemanager\/getdeliverytimeslotwithverification(completion:)"},"doc://com.yababaGmbH.yababa/documentation/Yababa/LocalUserStateManager/getSelectedPaymentCardID()":{"role":"symbol","title":"getSelectedPaymentCardID()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getSelectedPaymentCardID"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/LocalUserStateManager\/getSelectedPaymentCardID()","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/localuserstatemanager\/getselectedpaymentcardid()"},"doc://com.yababaGmbH.yababa/documentation/Yababa":{"role":"collection","title":"Yababa","abstract":[{"type":"text","text":"Getting Started"}],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa","kind":"symbol","type":"topic","url":"\/documentation\/yababa"},"doc://com.yababaGmbH.yababa/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.yababaGmbH.yababa\/s28CustomDebugStringConvertibleP"},"doc://com.yababaGmbH.yababa/documentation/Yababa/LocalUserStateManager/getUserProfile()":{"role":"symbol","title":"getUserProfile()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getUserProfile"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"Profile","preciseIdentifier":"c:@M@Yababa@objc(cs)Profile"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/LocalUserStateManager\/getUserProfile()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"getUserProfile"}],"url":"\/documentation\/yababa\/localuserstatemanager\/getuserprofile()"},"doc://com.yababaGmbH.yababa/documentation/Yababa/LocalUserStateManager/getUserHasReadBannerInfo()":{"role":"symbol","title":"getUserHasReadBannerInfo()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getUserHasReadBannerInfo"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/LocalUserStateManager\/getUserHasReadBannerInfo()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"getUserHasReadBannerInfo"}],"url":"\/documentation\/yababa\/localuserstatemanager\/getuserhasreadbannerinfo()"},"doc://com.yababaGmbH.yababa/documentation/Yababa/LocalUserStateManager/setSelectedLanguage(_:)":{"role":"symbol","title":"setSelectedLanguage(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setSelectedLanguage"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?)"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/LocalUserStateManager\/setSelectedLanguage(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"setSelectedLanguage:"}],"url":"\/documentation\/yababa\/localuserstatemanager\/setselectedlanguage(_:)"},"doc://com.yababaGmbH.yababa/documentation/Yababa/LocalUserStateManager/loadState()":{"role":"symbol","title":"loadState()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"loadState"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/LocalUserStateManager\/loadState()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"loadState"}],"url":"\/documentation\/yababa\/localuserstatemanager\/loadstate()"},"doc://com.yababaGmbH.yababa/12SkeletonView17AssociatedObjectsP":{"type":"unresolvable","title":"SkeletonView.AssociatedObjects","identifier":"doc:\/\/com.yababaGmbH.yababa\/12SkeletonView17AssociatedObjectsP"},"doc://com.yababaGmbH.yababa/documentation/Yababa/LocalUserStateManager/getUserLastestReferralCode()":{"role":"symbol","title":"getUserLastestReferralCode()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getUserLastestReferralCode"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/LocalUserStateManager\/getUserLastestReferralCode()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"getUserLastestReferralCode"}],"url":"\/documentation\/yababa\/localuserstatemanager\/getuserlastestreferralcode()"},"doc://com.yababaGmbH.yababa/documentation/Yababa/LocalUserStateManager/getUserAnsweredSoftIn()":{"role":"symbol","title":"getUserAnsweredSoftIn()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getUserAnsweredSoftIn"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/LocalUserStateManager\/getUserAnsweredSoftIn()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"getUserAnsweredSoftIn"}],"url":"\/documentation\/yababa\/localuserstatemanager\/getuseransweredsoftin()"},"doc://com.yababaGmbH.yababa/documentation/Yababa/LocalUserStateManager/defaultInstance":{"role":"symbol","title":"defaultInstance","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"defaultInstance"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"LocalUserStateManager","preciseIdentifier":"c:@M@Yababa@objc(cs)LocalUserStateManager"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/LocalUserStateManager\/defaultInstance","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"defaultInstance"}],"url":"\/documentation\/yababa\/localuserstatemanager\/defaultinstance"},"doc://com.yababaGmbH.yababa/documentation/Yababa/UserStateManagerProtocol":{"role":"symbol","title":"UserStateManagerProtocol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"UserStateManagerProtocol"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/UserStateManagerProtocol","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"UserStateManagerProtocol"}],"url":"\/documentation\/yababa\/userstatemanagerprotocol"},"doc://com.yababaGmbH.yababa/documentation/Yababa/LocalUserStateManager/selectedVoucher":{"role":"symbol","title":"selectedVoucher","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"selectedVoucher"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UserCoupon","preciseIdentifier":"s:6Yababa10UserCouponC"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/LocalUserStateManager\/selectedVoucher","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/localuserstatemanager\/selectedvoucher"},"doc://com.yababaGmbH.yababa/documentation/Yababa/LocalUserStateManager/syncBrazeUserSubscriptionStatusToDevice(completion:)":{"role":"symbol","title":"syncBrazeUserSubscriptionStatusToDevice(completion:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"syncBrazeUserSubscriptionStatusToDevice"},{"kind":"text","text":"("},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": () -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/LocalUserStateManager\/syncBrazeUserSubscriptionStatusToDevice(completion:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"syncBrazeUserSubscriptionStatusToDeviceWithCompletion:"}],"url":"\/documentation\/yababa\/localuserstatemanager\/syncbrazeusersubscriptionstatustodevice(completion:)"},"doc://com.yababaGmbH.yababa/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.yababaGmbH.yababa\/s7CVarArgP"},"doc://com.yababaGmbH.yababa/documentation/Yababa/LocalUserStateManager/setHasAnAddress(_:)":{"role":"symbol","title":"setHasAnAddress(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setHasAnAddress"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/LocalUserStateManager\/setHasAnAddress(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"setHasAnAddress:"}],"url":"\/documentation\/yababa\/localuserstatemanager\/sethasanaddress(_:)"},"doc://com.yababaGmbH.yababa/documentation/Yababa/LocalUserStateManager/isLoggedInUserFacebookUser()":{"role":"symbol","title":"isLoggedInUserFacebookUser()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"isLoggedInUserFacebookUser"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/LocalUserStateManager\/isLoggedInUserFacebookUser()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"isLoggedInUserFacebookUser"}],"url":"\/documentation\/yababa\/localuserstatemanager\/isloggedinuserfacebookuser()"},"doc://com.yababaGmbH.yababa/documentation/Yababa/LocalUserStateManager/getPushToken()":{"role":"symbol","title":"getPushToken()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getPushToken"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/LocalUserStateManager\/getPushToken()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"getPushToken"}],"url":"\/documentation\/yababa\/localuserstatemanager\/getpushtoken()"},"doc://com.yababaGmbH.yababa/documentation/Yababa/LocalUserStateManager/setUserLatestReferralCode(_:)":{"role":"symbol","title":"setUserLatestReferralCode(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setUserLatestReferralCode"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/LocalUserStateManager\/setUserLatestReferralCode(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"setUserLatestReferralCode:"}],"url":"\/documentation\/yababa\/localuserstatemanager\/setuserlatestreferralcode(_:)"},"doc://com.yababaGmbH.yababa/documentation/Yababa/LocalUserStateManager":{"role":"symbol","title":"LocalUserStateManager","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"LocalUserStateManager"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/LocalUserStateManager","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"LocalUserStateManager"}],"url":"\/documentation\/yababa\/localuserstatemanager"},"doc://com.yababaGmbH.yababa/documentation/Yababa/LocalUserStateManager/setUserPushSubscriptionStatus(_:)":{"role":"symbol","title":"setUserPushSubscriptionStatus(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setUserPushSubscriptionStatus"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"SubscriptionStatus","preciseIdentifier":"c:@M@Yababa@E@SubscriptionStatus"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/LocalUserStateManager\/setUserPushSubscriptionStatus(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"setUserPushSubscriptionStatus:"}],"url":"\/documentation\/yababa\/localuserstatemanager\/setuserpushsubscriptionstatus(_:)"},"doc://com.yababaGmbH.yababa/documentation/Yababa/LocalUserStateManager/getSelectedLanguage()":{"role":"symbol","title":"getSelectedLanguage()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getSelectedLanguage"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/LocalUserStateManager\/getSelectedLanguage()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"getSelectedLanguage"}],"url":"\/documentation\/yababa\/localuserstatemanager\/getselectedlanguage()"},"doc://com.yababaGmbH.yababa/documentation/Yababa/LocalUserStateManager/getUserUnreadFreshChatMessage()":{"role":"symbol","title":"getUserUnreadFreshChatMessage()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getUserUnreadFreshChatMessage"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/LocalUserStateManager\/getUserUnreadFreshChatMessage()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"getUserUnreadFreshChatMessage"}],"url":"\/documentation\/yababa\/localuserstatemanager\/getuserunreadfreshchatmessage()"},"doc://com.yababaGmbH.yababa/documentation/Yababa/LocalUserStateManager/isDefaultBackendVoucherApplied":{"role":"symbol","title":"isDefaultBackendVoucherApplied","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isDefaultBackendVoucherApplied"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/LocalUserStateManager\/isDefaultBackendVoucherApplied","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"isDefaultBackendVoucherApplied"}],"url":"\/documentation\/yababa\/localuserstatemanager\/isdefaultbackendvoucherapplied"},"doc://com.yababaGmbH.yababa/documentation/Yababa/LocalUserStateManager/clearState()":{"role":"symbol","title":"clearState()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"clearState"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/LocalUserStateManager\/clearState()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"clearState"}],"url":"\/documentation\/yababa\/localuserstatemanager\/clearstate()"},"doc://com.yababaGmbH.yababa/documentation/Yababa/LocalUserStateManager/setAddress(_:)":{"role":"symbol","title":"setAddress(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setAddress"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Address","preciseIdentifier":"s:6Yababa7AddressC"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/LocalUserStateManager\/setAddress(_:)","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/localuserstatemanager\/setaddress(_:)"},"doc://com.yababaGmbH.yababa/documentation/Yababa/LocalUserStateManager/getUserFirstAndLastName()":{"role":"symbol","title":"getUserFirstAndLastName()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getUserFirstAndLastName"},{"kind":"text","text":"() -> (firstName"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, lastName"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?)"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/LocalUserStateManager\/getUserFirstAndLastName()","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/localuserstatemanager\/getuserfirstandlastname()"},"doc://com.yababaGmbH.yababa/documentation/Yababa/LocalUserStateManager/setUserEmailSubscriptionStatus(_:)":{"role":"symbol","title":"setUserEmailSubscriptionStatus(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setUserEmailSubscriptionStatus"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"SubscriptionStatus","preciseIdentifier":"c:@M@Yababa@E@SubscriptionStatus"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/LocalUserStateManager\/setUserEmailSubscriptionStatus(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"setUserEmailSubscriptionStatus:"}],"url":"\/documentation\/yababa\/localuserstatemanager\/setuseremailsubscriptionstatus(_:)"},"doc://com.yababaGmbH.yababa/documentation/Yababa/LocalUserStateManager/isLoggedInUserAppleUser()":{"role":"symbol","title":"isLoggedInUserAppleUser()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"isLoggedInUserAppleUser"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/LocalUserStateManager\/isLoggedInUserAppleUser()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"isLoggedInUserAppleUser"}],"url":"\/documentation\/yababa\/localuserstatemanager\/isloggedinuserappleuser()"},"doc://com.yababaGmbH.yababa/documentation/Yababa/LocalUserStateManager/userNeedsToCompleteProfile(rightBeforeBooking:)":{"role":"symbol","title":"userNeedsToCompleteProfile(rightBeforeBooking:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"userNeedsToCompleteProfile"},{"kind":"text","text":"("},{"kind":"externalParam","text":"rightBeforeBooking"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/LocalUserStateManager\/userNeedsToCompleteProfile(rightBeforeBooking:)","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/localuserstatemanager\/userneedstocompleteprofile(rightbeforebooking:)"},"doc://com.yababaGmbH.yababa/documentation/Yababa/LocalUserStateManager/StateKeys":{"role":"symbol","title":"LocalUserStateManager.StateKeys","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"StateKeys"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/LocalUserStateManager\/StateKeys","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"StateKeys"}],"url":"\/documentation\/yababa\/localuserstatemanager\/statekeys"},"doc://com.yababaGmbH.yababa/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.yababaGmbH.yababa\/SQ"},"doc://com.yababaGmbH.yababa/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.yababaGmbH.yababa\/s23CustomStringConvertibleP"},"doc://com.yababaGmbH.yababa/documentation/Yababa/LocalUserStateManager/getCurrentUser()":{"role":"symbol","title":"getCurrentUser()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getCurrentUser"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"UserData","preciseIdentifier":"c:objc(cs)UserData"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/LocalUserStateManager\/getCurrentUser()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"getCurrentUser"}],"url":"\/documentation\/yababa\/localuserstatemanager\/getcurrentuser()"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"LocalUserStateManager"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"LocalUserStateManager"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"LocalUserStateManager"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/LocalUserStateManager\/discountsTabNeedsToBeViewed","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/LocalUserStateManager\/isDefaultBackendVoucherApplied","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/LocalUserStateManager\/onSelectedVoucherIdChanged"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/LocalUserStateManager\/clearState()","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/LocalUserStateManager\/getAppVersionWhichForcedCatalogeRefresh()","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/LocalUserStateManager\/getCurrentUser()","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/LocalUserStateManager\/getPushToken()","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/LocalUserStateManager\/getReferralCode()","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/LocalUserStateManager\/getSelectedLanguage()","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/LocalUserStateManager\/getUserAnsweredSoftIn()","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/LocalUserStateManager\/getUserHasReadBannerInfo()","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/LocalUserStateManager\/getUserLastestReferralCode()","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/LocalUserStateManager\/getUserProfile()","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/LocalUserStateManager\/getUserPushSubscriptionStatus()","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/LocalUserStateManager\/getUserUnreadFreshChatMessage()","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/LocalUserStateManager\/hasAnAddress()","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/LocalUserStateManager\/isLoggedInUserAppleUser()","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/LocalUserStateManager\/isLoggedInUserFacebookUser()","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/LocalUserStateManager\/isLoggedInUserGoogleUser()","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/LocalUserStateManager\/isUserInBrowsingMode()","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/LocalUserStateManager\/loadState()","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/LocalUserStateManager\/setAppCurrentVersionWhichForcedCatalogeRefresh()","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/LocalUserStateManager\/setHasAnAddress(_:)","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/LocalUserStateManager\/setSelectedLanguage(_:)","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/LocalUserStateManager\/setSelectedPaymentCardID(_:)","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/LocalUserStateManager\/setUserAnsweredSoftIn(_:)","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/LocalUserStateManager\/setUserEmailSubscriptionStatus(_:)","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/LocalUserStateManager\/setUserHasReadBannerInfo(_:)","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/LocalUserStateManager\/setUserLatestReferralCode(_:)","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/LocalUserStateManager\/setUserPushSubscriptionStatus(_:)","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/LocalUserStateManager\/setUserUnreadFreshChatMessage(_:)","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/LocalUserStateManager\/syncBrazeUserSubscriptionStatusToDevice(completion:)","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/LocalUserStateManager\/syncUserProfile()"]},{"title":"Type Properties","identifiers":["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/LocalUserStateManager\/defaultInstance"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.yababaGmbH.yababa\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"LocalUserStateManager"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1LocalUserStateManager~1getAppVersionWhichForcedCatalogeRefresh()\/title","value":"getAppVersionWhichForcedCatalogeRefresh"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1LocalUserStateManager~1getAppVersionWhichForcedCatalogeRefresh()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"getAppVersionWhichForcedCatalogeRefresh"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1LocalUserStateManager~1syncUserProfile()\/title","value":"syncUserProfile"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1LocalUserStateManager~1syncUserProfile()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"syncUserProfile"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1LocalUserStateManager~1setSelectedPaymentCardID(_:)\/title","value":"setSelectedPaymentCardID:"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1LocalUserStateManager~1setSelectedPaymentCardID(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setSelectedPaymentCardID:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1LocalUserStateManager~1getUserPushSubscriptionStatus()\/title","value":"getUserPushSubscriptionStatus"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1LocalUserStateManager~1getUserPushSubscriptionStatus()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"getUserPushSubscriptionStatus"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1LocalUserStateManager~1isUserInBrowsingMode()\/title","value":"isUserInBrowsingMode"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1LocalUserStateManager~1isUserInBrowsingMode()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"isUserInBrowsingMode"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1LocalUserStateManager~1setUserHasReadBannerInfo(_:)\/title","value":"setUserHasReadBannerInfo:"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1LocalUserStateManager~1setUserHasReadBannerInfo(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setUserHasReadBannerInfo:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1LocalUserStateManager~1isLoggedInUserGoogleUser()\/title","value":"isLoggedInUserGoogleUser"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1LocalUserStateManager~1isLoggedInUserGoogleUser()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"isLoggedInUserGoogleUser"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1LocalUserStateManager~1discountsTabNeedsToBeViewed\/title","value":"discountsTabNeedsToBeViewed"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1LocalUserStateManager~1discountsTabNeedsToBeViewed\/fragments","value":[{"kind":"identifier","text":"discountsTabNeedsToBeViewed"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1LocalUserStateManager~1setAppCurrentVersionWhichForcedCatalogeRefresh()\/title","value":"setAppCurrentVersionWhichForcedCatalogeRefresh"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1LocalUserStateManager~1setAppCurrentVersionWhichForcedCatalogeRefresh()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setAppCurrentVersionWhichForcedCatalogeRefresh"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1LocalUserStateManager~1getReferralCode()\/title","value":"getReferralCode"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1LocalUserStateManager~1getReferralCode()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"getReferralCode"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1LocalUserStateManager~1setUserUnreadFreshChatMessage(_:)\/title","value":"setUserUnreadFreshChatMessage:"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1LocalUserStateManager~1setUserUnreadFreshChatMessage(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setUserUnreadFreshChatMessage:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1LocalUserStateManager~1onSelectedVoucherIdChanged\/title","value":"onSelectedVoucherIdChanged"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1LocalUserStateManager~1onSelectedVoucherIdChanged\/fragments","value":[{"kind":"identifier","text":"onSelectedVoucherIdChanged"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1LocalUserStateManager~1setUserAnsweredSoftIn(_:)\/title","value":"setUserAnsweredSoftIn:"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1LocalUserStateManager~1setUserAnsweredSoftIn(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setUserAnsweredSoftIn:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1LocalUserStateManager~1hasAnAddress()\/title","value":"hasAnAddress"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1LocalUserStateManager~1hasAnAddress()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"hasAnAddress"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1LocalUserStateManager~1getUserProfile()\/title","value":"getUserProfile"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1LocalUserStateManager~1getUserProfile()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"getUserProfile"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1LocalUserStateManager~1getUserHasReadBannerInfo()\/title","value":"getUserHasReadBannerInfo"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1LocalUserStateManager~1getUserHasReadBannerInfo()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"getUserHasReadBannerInfo"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1LocalUserStateManager~1setSelectedLanguage(_:)\/title","value":"setSelectedLanguage:"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1LocalUserStateManager~1setSelectedLanguage(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setSelectedLanguage:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1LocalUserStateManager~1loadState()\/title","value":"loadState"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1LocalUserStateManager~1loadState()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"loadState"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1LocalUserStateManager~1getUserLastestReferralCode()\/title","value":"getUserLastestReferralCode"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1LocalUserStateManager~1getUserLastestReferralCode()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"getUserLastestReferralCode"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1LocalUserStateManager~1getUserAnsweredSoftIn()\/title","value":"getUserAnsweredSoftIn"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1LocalUserStateManager~1getUserAnsweredSoftIn()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"getUserAnsweredSoftIn"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1LocalUserStateManager~1defaultInstance\/title","value":"defaultInstance"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1LocalUserStateManager~1defaultInstance\/fragments","value":[{"kind":"identifier","text":"defaultInstance"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1LocalUserStateManager~1syncBrazeUserSubscriptionStatusToDevice(completion:)\/title","value":"syncBrazeUserSubscriptionStatusToDeviceWithCompletion:"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1LocalUserStateManager~1syncBrazeUserSubscriptionStatusToDevice(completion:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"syncBrazeUserSubscriptionStatusToDeviceWithCompletion:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1LocalUserStateManager~1setHasAnAddress(_:)\/title","value":"setHasAnAddress:"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1LocalUserStateManager~1setHasAnAddress(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setHasAnAddress:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1LocalUserStateManager~1isLoggedInUserFacebookUser()\/title","value":"isLoggedInUserFacebookUser"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1LocalUserStateManager~1isLoggedInUserFacebookUser()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"isLoggedInUserFacebookUser"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1LocalUserStateManager~1getPushToken()\/title","value":"getPushToken"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1LocalUserStateManager~1getPushToken()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"getPushToken"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1LocalUserStateManager~1setUserLatestReferralCode(_:)\/title","value":"setUserLatestReferralCode:"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1LocalUserStateManager~1setUserLatestReferralCode(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setUserLatestReferralCode:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1LocalUserStateManager\/title","value":"LocalUserStateManager"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1LocalUserStateManager\/fragments","value":[{"kind":"identifier","text":"LocalUserStateManager"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1LocalUserStateManager~1setUserPushSubscriptionStatus(_:)\/title","value":"setUserPushSubscriptionStatus:"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1LocalUserStateManager~1setUserPushSubscriptionStatus(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setUserPushSubscriptionStatus:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1LocalUserStateManager~1getSelectedLanguage()\/title","value":"getSelectedLanguage"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1LocalUserStateManager~1getSelectedLanguage()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"getSelectedLanguage"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1LocalUserStateManager~1getUserUnreadFreshChatMessage()\/title","value":"getUserUnreadFreshChatMessage"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1LocalUserStateManager~1getUserUnreadFreshChatMessage()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"getUserUnreadFreshChatMessage"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1LocalUserStateManager~1isDefaultBackendVoucherApplied\/title","value":"isDefaultBackendVoucherApplied"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1LocalUserStateManager~1isDefaultBackendVoucherApplied\/fragments","value":[{"kind":"identifier","text":"isDefaultBackendVoucherApplied"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1LocalUserStateManager~1clearState()\/title","value":"clearState"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1LocalUserStateManager~1clearState()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"clearState"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1LocalUserStateManager~1setUserEmailSubscriptionStatus(_:)\/title","value":"setUserEmailSubscriptionStatus:"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1LocalUserStateManager~1setUserEmailSubscriptionStatus(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setUserEmailSubscriptionStatus:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1LocalUserStateManager~1isLoggedInUserAppleUser()\/title","value":"isLoggedInUserAppleUser"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1LocalUserStateManager~1isLoggedInUserAppleUser()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"isLoggedInUserAppleUser"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1LocalUserStateManager~1getCurrentUser()\/title","value":"getCurrentUser"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1LocalUserStateManager~1getCurrentUser()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"getCurrentUser"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}