{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"LocationDelegate"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObjectProtocol","preciseIdentifier":"c:objc(pl)NSObject"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/yababa\/locationdelegate"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/yababa\/locationdelegate"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.yababaGmbH.yababa\/objc(pl)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AddressManagerViewNavigator","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/MapsViewController"],"kind":"relationships","title":"Conforming Types","type":"conformingTypes"}],"identifier":{"url":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/LocationDelegate","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/LocationDelegate\/response(forCountryCoordinatesLat:lng:)","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/LocationDelegate\/response(forRequestLocation:postalCode:city:country:countryCode:lat:lng:)","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/LocationDelegate\/response(forRequestTimezone:)"]}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"LocationDelegate"}],"title":"LocationDelegate","roleHeading":"Protocol","role":"symbol","symbolKind":"protocol","externalID":"c:objc(pl)LocationDelegate","modules":[{"name":"Yababa"}],"navigatorTitle":[{"kind":"identifier","text":"LocationDelegate"}]},"hierarchy":{"paths":[["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa"]]},"references":{"doc://com.yababaGmbH.yababa/objc(pl)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)NSObject"},"doc://com.yababaGmbH.yababa/documentation/Yababa/LocationDelegate/response(forCountryCoordinatesLat:lng:)":{"role":"symbol","title":"response(forCountryCoordinatesLat:lng:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"response"},{"kind":"text","text":"("},{"kind":"externalParam","text":"forCountryCoordinatesLat"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"},{"kind":"text","text":", "},{"kind":"externalParam","text":"lng"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/LocationDelegate\/response(forCountryCoordinatesLat:lng:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ResponseForCountryCoordinatesLat:lng:"}],"url":"\/documentation\/yababa\/locationdelegate\/response(forcountrycoordinateslat:lng:)"},"doc://com.yababaGmbH.yababa/documentation/Yababa/LocationDelegate/response(forRequestTimezone:)":{"navigatorTitle":[{"kind":"identifier","text":"ResponseForRequestTimezone:"}],"role":"symbol","title":"response(forRequestTimezone:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"response"},{"kind":"text","text":"("},{"kind":"externalParam","text":"forRequestTimezone"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/LocationDelegate\/response(forRequestTimezone:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/yababa\/locationdelegate\/response(forrequesttimezone:)"},"doc://com.yababaGmbH.yababa/documentation/Yababa/LocationDelegate":{"role":"symbol","title":"LocationDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"LocationDelegate"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/LocationDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"LocationDelegate"}],"url":"\/documentation\/yababa\/locationdelegate"},"doc://com.yababaGmbH.yababa/documentation/Yababa/LocationDelegate/response(forRequestLocation:postalCode:city:country:countryCode:lat:lng:)":{"navigatorTitle":[{"kind":"identifier","text":"ResponseForRequestLocation:postalCode:city:country:countryCode:Lat:Lng:"}],"role":"symbol","title":"response(forRequestLocation:postalCode:city:country:countryCode:lat:lng:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"response"},{"kind":"text","text":"("},{"kind":"externalParam","text":"forRequestLocation"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"postalCode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"city"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"country"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"countryCode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"lat"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"},{"kind":"text","text":", "},{"kind":"externalParam","text":"lng"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/LocationDelegate\/response(forRequestLocation:postalCode:city:country:countryCode:lat:lng:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/yababa\/locationdelegate\/response(forrequestlocation:postalcode:city:country:countrycode:lat:lng:)"},"doc://com.yababaGmbH.yababa/documentation/Yababa/AddressManagerViewNavigator":{"role":"symbol","title":"AddressManagerViewNavigator","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AddressManagerViewNavigator"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AddressManagerViewNavigator","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AddressManagerViewNavigator"}],"url":"\/documentation\/yababa\/addressmanagerviewnavigator"},"doc://com.yababaGmbH.yababa/documentation/Yababa/MapsViewController":{"role":"symbol","title":"MapsViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MapsViewController"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/MapsViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MapsViewController"}],"url":"\/documentation\/yababa\/mapsviewcontroller"},"doc://com.yababaGmbH.yababa/documentation/Yababa":{"role":"collection","title":"Yababa","abstract":[{"type":"text","text":"Getting Started"}],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa","kind":"symbol","type":"topic","url":"\/documentation\/yababa"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Protocol"},{"op":"replace","path":"\/metadata\/title","value":"LocationDelegate"},{"op":"replace","path":"\/metadata\/symbolKind","value":"protocol"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"LocationDelegate"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"LocationDelegate"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/LocationDelegate\/response(forCountryCoordinatesLat:lng:)","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/LocationDelegate\/response(forRequestLocation:postalCode:city:country:countryCode:lat:lng:)","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/LocationDelegate\/response(forRequestTimezone:)"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.yababaGmbH.yababa\/objc(pl)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"LocationDelegate"},{"kind":"text","text":"<"},{"kind":"keyword","text":"NSObject"},{"kind":"text","text":">"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1LocationDelegate~1response(forCountryCoordinatesLat:lng:)\/title","value":"ResponseForCountryCoordinatesLat:lng:"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1LocationDelegate~1response(forCountryCoordinatesLat:lng:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"ResponseForCountryCoordinatesLat:lng:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1LocationDelegate~1response(forRequestTimezone:)\/title","value":"ResponseForRequestTimezone:"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1LocationDelegate~1response(forRequestTimezone:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"ResponseForRequestTimezone:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1LocationDelegate\/title","value":"LocationDelegate"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1LocationDelegate\/fragments","value":[{"kind":"identifier","text":"LocationDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1LocationDelegate~1response(forRequestLocation:postalCode:city:country:countryCode:lat:lng:)\/title","value":"ResponseForRequestLocation:postalCode:city:country:countryCode:Lat:Lng:"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1LocationDelegate~1response(forRequestLocation:postalCode:city:country:countryCode:lat:lng:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"ResponseForRequestLocation:postalCode:city:country:countryCode:Lat:Lng:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1AddressManagerViewNavigator\/title","value":"AddressManagerViewNavigator"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1AddressManagerViewNavigator\/fragments","value":[{"kind":"identifier","text":"AddressManagerViewNavigator"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1MapsViewController\/title","value":"MapsViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1MapsViewController\/fragments","value":[{"kind":"identifier","text":"MapsViewController"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}