{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MapsViewController"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/yababa\/mapsviewcontroller"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/yababa\/mapsviewcontroller"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/MasterViewController"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.yababaGmbH.yababa\/objc(pl)CLLocationManagerDelegate","doc:\/\/com.yababaGmbH.yababa\/objc(pl)NSCoding","doc:\/\/com.yababaGmbH.yababa\/objc(pl)NSExtensionRequestHandling","doc:\/\/com.yababaGmbH.yababa\/objc(pl)GMSMapViewDelegate","doc:\/\/com.yababaGmbH.yababa\/objc(pl)GMSAutocompleteViewControllerDelegate","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/LocationDelegate","doc:\/\/com.yababaGmbH.yababa\/objc(pl)NSObject","doc:\/\/com.yababaGmbH.yababa\/12SkeletonView17AssociatedObjectsP","doc:\/\/com.yababaGmbH.yababa\/s7CVarArgP","doc:\/\/com.yababaGmbH.yababa\/s28CustomDebugStringConvertibleP","doc:\/\/com.yababaGmbH.yababa\/s23CustomStringConvertibleP","doc:\/\/com.yababaGmbH.yababa\/SQ","doc:\/\/com.yababaGmbH.yababa\/SH","doc:\/\/com.yababaGmbH.yababa\/s8SendableP","doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIActivityItemsConfigurationProviding","doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIAppearanceContainer","doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIContentContainer","doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIFocusEnvironment","doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIPasteConfigurationSupporting","doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIResponderStandardEditActions","doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIStateRestoring","doc:\/\/com.yababaGmbH.yababa\/objc(pl)UITraitEnvironment","doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIUserActivityRestoring"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/MapsViewController","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/MapsViewController\/backBtn","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/MapsViewController\/customBlackPin","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/MapsViewController\/delegate","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/MapsViewController\/mapsView","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/MapsViewController\/searchBtn","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/MapsViewController\/searchLabel","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/MapsViewController\/selectBtn","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/MapsViewController\/selectedCoordinate","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/MapsViewController\/showBackBtn","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/MapsViewController\/zoomLevel"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/MapsViewController\/getLocationForCoordinates(_:)","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/MapsViewController\/navigateToBerlin()","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/MapsViewController\/navigateToUserLocation()","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/MapsViewController\/onSearch(_:)","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/MapsViewController\/onSelection(_:)","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/MapsViewController\/setIdentifiers()","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/MapsViewController\/setupUI()","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/MapsViewController\/viewDidLoad()"]},{"title":"Default Implementations","identifiers":["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/MapsViewController\/CLLocationManagerDelegate-Implementations","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/MapsViewController\/GMSAutocompleteViewControllerDelegate-Implementations","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/MapsViewController\/GMSMapViewDelegate-Implementations","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/MapsViewController\/LocationDelegate-Implementations"],"generated":true}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MapsViewController"}],"title":"MapsViewController","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@Yababa@objc(cs)MapsViewController","modules":[{"name":"Yababa"}],"navigatorTitle":[{"kind":"identifier","text":"MapsViewController"}]},"hierarchy":{"paths":[["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa"]]},"references":{"doc://com.yababaGmbH.yababa/documentation/Yababa/MapsViewController/searchBtn":{"role":"symbol","title":"searchBtn","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"searchBtn"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIButton","preciseIdentifier":"c:objc(cs)UIButton"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/MapsViewController\/searchBtn","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"searchBtn"}],"url":"\/documentation\/yababa\/mapsviewcontroller\/searchbtn"},"doc://com.yababaGmbH.yababa/documentation/Yababa/MapsViewController/CLLocationManagerDelegate-Implementations":{"role":"collectionGroup","title":"CLLocationManagerDelegate Implementations","abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/MapsViewController\/CLLocationManagerDelegate-Implementations","kind":"article","type":"topic","url":"\/documentation\/yababa\/mapsviewcontroller\/cllocationmanagerdelegate-implementations"},"doc://com.yababaGmbH.yababa/documentation/Yababa/MapsViewController/initWithCoder:":{"role":"symbol","title":"initWithCoder:","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithCoder:"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/MapsViewController\/initWithCoder:","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithCoder:"}],"url":"\/documentation\/yababa\/mapsviewcontroller\/initwithcoder:"},"doc://com.yababaGmbH.yababa/objc(pl)CLLocationManagerDelegate":{"type":"unresolvable","title":"CoreLocation.CLLocationManagerDelegate","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)CLLocationManagerDelegate"},"doc://com.yababaGmbH.yababa/documentation/Yababa/MapsViewController/navigateToUserLocation()":{"role":"symbol","title":"navigateToUserLocation()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"navigateToUserLocation"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/MapsViewController\/navigateToUserLocation()","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/mapsviewcontroller\/navigatetouserlocation()"},"doc://com.yababaGmbH.yababa/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/com.yababaGmbH.yababa\/s8SendableP"},"doc://com.yababaGmbH.yababa/objc(pl)UIContentContainer":{"type":"unresolvable","title":"UIKit.UIContentContainer","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIContentContainer"},"doc://com.yababaGmbH.yababa/objc(pl)UIPasteConfigurationSupporting":{"type":"unresolvable","title":"UIKit.UIPasteConfigurationSupporting","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIPasteConfigurationSupporting"},"doc://com.yababaGmbH.yababa/objc(pl)UIFocusEnvironment":{"type":"unresolvable","title":"UIKit.UIFocusEnvironment","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIFocusEnvironment"},"doc://com.yababaGmbH.yababa/documentation/Yababa/MapsViewController/GMSAutocompleteViewControllerDelegate-Implementations":{"role":"collectionGroup","title":"GMSAutocompleteViewControllerDelegate Implementations","abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/MapsViewController\/GMSAutocompleteViewControllerDelegate-Implementations","kind":"article","type":"topic","url":"\/documentation\/yababa\/mapsviewcontroller\/gmsautocompleteviewcontrollerdelegate-implementations"},"doc://com.yababaGmbH.yababa/documentation/Yababa/MapsViewController/setupUI()":{"role":"symbol","title":"setupUI()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setupUI"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/MapsViewController\/setupUI()","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/mapsviewcontroller\/setupui()"},"doc://com.yababaGmbH.yababa/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.yababaGmbH.yababa\/SH"},"doc://com.yababaGmbH.yababa/objc(pl)UIStateRestoring":{"type":"unresolvable","title":"UIKit.UIStateRestoring","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIStateRestoring"},"doc://com.yababaGmbH.yababa/objc(pl)UIAppearanceContainer":{"type":"unresolvable","title":"UIKit.UIAppearanceContainer","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIAppearanceContainer"},"doc://com.yababaGmbH.yababa/documentation/Yababa/MapsViewController/onSearch(_:)":{"role":"symbol","title":"onSearch(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onSearch"},{"kind":"text","text":"("},{"kind":"keyword","text":"Any"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/MapsViewController\/onSearch(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"onSearch:"}],"url":"\/documentation\/yababa\/mapsviewcontroller\/onsearch(_:)"},"doc://com.yababaGmbH.yababa/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)NSObject"},"doc://com.yababaGmbH.yababa/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.yababaGmbH.yababa\/s23CustomStringConvertibleP"},"doc://com.yababaGmbH.yababa/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.yababaGmbH.yababa\/SQ"},"doc://com.yababaGmbH.yababa/objc(pl)GMSMapViewDelegate":{"type":"unresolvable","title":"GoogleMaps.GMSMapViewDelegate","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)GMSMapViewDelegate"},"doc://com.yababaGmbH.yababa/documentation/Yababa/MapsViewController/setIdentifiers()":{"role":"symbol","title":"setIdentifiers()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setIdentifiers"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/MapsViewController\/setIdentifiers()","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/mapsviewcontroller\/setidentifiers()"},"doc://com.yababaGmbH.yababa/documentation/Yababa/MapsViewController/GMSMapViewDelegate-Implementations":{"role":"collectionGroup","title":"GMSMapViewDelegate Implementations","abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/MapsViewController\/GMSMapViewDelegate-Implementations","kind":"article","type":"topic","url":"\/documentation\/yababa\/mapsviewcontroller\/gmsmapviewdelegate-implementations"},"doc://com.yababaGmbH.yababa/documentation/Yababa/MapsViewController/customBlackPin":{"role":"symbol","title":"customBlackPin","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"customBlackPin"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIImageView","preciseIdentifier":"c:objc(cs)UIImageView"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/MapsViewController\/customBlackPin","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"customBlackPin"}],"url":"\/documentation\/yababa\/mapsviewcontroller\/customblackpin"},"doc://com.yababaGmbH.yababa/12SkeletonView17AssociatedObjectsP":{"type":"unresolvable","title":"SkeletonView.AssociatedObjects","identifier":"doc:\/\/com.yababaGmbH.yababa\/12SkeletonView17AssociatedObjectsP"},"doc://com.yababaGmbH.yababa/documentation/Yababa":{"role":"collection","title":"Yababa","abstract":[{"type":"text","text":"Getting Started"}],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa","kind":"symbol","type":"topic","url":"\/documentation\/yababa"},"doc://com.yababaGmbH.yababa/documentation/Yababa/MapsViewController/LocationDelegate-Implementations":{"role":"collectionGroup","title":"LocationDelegate Implementations","abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/MapsViewController\/LocationDelegate-Implementations","kind":"article","type":"topic","url":"\/documentation\/yababa\/mapsviewcontroller\/locationdelegate-implementations"},"doc://com.yababaGmbH.yababa/objc(pl)UIResponderStandardEditActions":{"type":"unresolvable","title":"UIKit.UIResponderStandardEditActions","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIResponderStandardEditActions"},"doc://com.yababaGmbH.yababa/documentation/Yababa/MapsViewController/selectBtn":{"role":"symbol","title":"selectBtn","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"selectBtn"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIButton","preciseIdentifier":"c:objc(cs)UIButton"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/MapsViewController\/selectBtn","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"selectBtn"}],"url":"\/documentation\/yababa\/mapsviewcontroller\/selectbtn"},"doc://com.yababaGmbH.yababa/objc(pl)NSExtensionRequestHandling":{"type":"unresolvable","title":"Foundation.NSExtensionRequestHandling","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)NSExtensionRequestHandling"},"doc://com.yababaGmbH.yababa/documentation/Yababa/MapsViewController/navigateToBerlin()":{"role":"symbol","title":"navigateToBerlin()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"navigateToBerlin"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/MapsViewController\/navigateToBerlin()","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/mapsviewcontroller\/navigatetoberlin()"},"doc://com.yababaGmbH.yababa/documentation/Yababa/MapsViewController/mapsView":{"role":"symbol","title":"mapsView","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"mapsView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GMSMapView","preciseIdentifier":"c:objc(cs)GMSMapView"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/MapsViewController\/mapsView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"mapsView"}],"url":"\/documentation\/yababa\/mapsviewcontroller\/mapsview"},"doc://com.yababaGmbH.yababa/documentation/Yababa/MapsViewController/delegate":{"role":"symbol","title":"delegate","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"delegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MapsViewDelegate","preciseIdentifier":"s:6Yababa16MapsViewDelegateP"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/MapsViewController\/delegate","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/mapsviewcontroller\/delegate"},"doc://com.yababaGmbH.yababa/documentation/Yababa/MapsViewController/backBtn":{"role":"symbol","title":"backBtn","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"backBtn"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIButton","preciseIdentifier":"c:objc(cs)UIButton"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/MapsViewController\/backBtn","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"backBtn"}],"url":"\/documentation\/yababa\/mapsviewcontroller\/backbtn"},"doc://com.yababaGmbH.yababa/documentation/Yababa/LocationDelegate":{"role":"symbol","title":"LocationDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"LocationDelegate"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/LocationDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"LocationDelegate"}],"url":"\/documentation\/yababa\/locationdelegate"},"doc://com.yababaGmbH.yababa/objc(pl)UIUserActivityRestoring":{"type":"unresolvable","title":"UIKit.UIUserActivityRestoring","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIUserActivityRestoring"},"doc://com.yababaGmbH.yababa/objc(pl)UITraitEnvironment":{"type":"unresolvable","title":"UIKit.UITraitEnvironment","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)UITraitEnvironment"},"doc://com.yababaGmbH.yababa/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.yababaGmbH.yababa\/s28CustomDebugStringConvertibleP"},"doc://com.yababaGmbH.yababa/documentation/Yababa/MapsViewController/viewDidLoad()":{"role":"symbol","title":"viewDidLoad()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"viewDidLoad"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/MapsViewController\/viewDidLoad()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"viewDidLoad"}],"url":"\/documentation\/yababa\/mapsviewcontroller\/viewdidload()"},"doc://com.yababaGmbH.yababa/documentation/Yababa/MapsViewController/zoomLevel":{"role":"symbol","title":"zoomLevel","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"zoomLevel"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Float","preciseIdentifier":"s:Sf"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/MapsViewController\/zoomLevel","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/mapsviewcontroller\/zoomlevel"},"doc://com.yababaGmbH.yababa/documentation/Yababa/MapsViewController/showBackBtn":{"role":"symbol","title":"showBackBtn","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"showBackBtn"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/MapsViewController\/showBackBtn","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/mapsviewcontroller\/showbackbtn"},"doc://com.yababaGmbH.yababa/documentation/Yababa/MapsViewController/initWithNibName:bundle:":{"role":"symbol","title":"initWithNibName:bundle:","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithNibName:bundle:"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/MapsViewController\/initWithNibName:bundle:","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithNibName:bundle:"}],"url":"\/documentation\/yababa\/mapsviewcontroller\/initwithnibname:bundle:"},"doc://com.yababaGmbH.yababa/documentation/Yababa/MapsViewController/onSelection(_:)":{"role":"symbol","title":"onSelection(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onSelection"},{"kind":"text","text":"("},{"kind":"keyword","text":"Any"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/MapsViewController\/onSelection(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"onSelection:"}],"url":"\/documentation\/yababa\/mapsviewcontroller\/onselection(_:)"},"doc://com.yababaGmbH.yababa/objc(pl)UIActivityItemsConfigurationProviding":{"type":"unresolvable","title":"UIKit.UIActivityItemsConfigurationProviding","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIActivityItemsConfigurationProviding"},"doc://com.yababaGmbH.yababa/objc(pl)NSCoding":{"type":"unresolvable","title":"Foundation.NSCoding","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)NSCoding"},"doc://com.yababaGmbH.yababa/objc(pl)GMSAutocompleteViewControllerDelegate":{"type":"unresolvable","title":"GooglePlaces.GMSAutocompleteViewControllerDelegate","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)GMSAutocompleteViewControllerDelegate"},"doc://com.yababaGmbH.yababa/documentation/Yababa/MasterViewController":{"role":"symbol","title":"MasterViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MasterViewController"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/MasterViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MasterViewController"}],"url":"\/documentation\/yababa\/masterviewcontroller"},"doc://com.yababaGmbH.yababa/documentation/Yababa/MapsViewController/selectedCoordinate":{"role":"symbol","title":"selectedCoordinate","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"selectedCoordinate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CLLocationCoordinate2D","preciseIdentifier":"c:@S@CLLocationCoordinate2D"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/MapsViewController\/selectedCoordinate","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/mapsviewcontroller\/selectedcoordinate"},"doc://com.yababaGmbH.yababa/documentation/Yababa/MapsViewController/searchLabel":{"role":"symbol","title":"searchLabel","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"searchLabel"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UILabel","preciseIdentifier":"c:objc(cs)UILabel"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/MapsViewController\/searchLabel","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"searchLabel"}],"url":"\/documentation\/yababa\/mapsviewcontroller\/searchlabel"},"doc://com.yababaGmbH.yababa/documentation/Yababa/MapsViewController":{"role":"symbol","title":"MapsViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MapsViewController"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/MapsViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MapsViewController"}],"url":"\/documentation\/yababa\/mapsviewcontroller"},"doc://com.yababaGmbH.yababa/documentation/Yababa/MapsViewController/getLocationForCoordinates(_:)":{"role":"symbol","title":"getLocationForCoordinates(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getLocationForCoordinates"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"CLLocationCoordinate2D","preciseIdentifier":"c:@S@CLLocationCoordinate2D"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/MapsViewController\/getLocationForCoordinates(_:)","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/mapsviewcontroller\/getlocationforcoordinates(_:)"},"doc://com.yababaGmbH.yababa/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.yababaGmbH.yababa\/s7CVarArgP"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"MapsViewController"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"MapsViewController"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"MapsViewController"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/MapsViewController\/backBtn","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/MapsViewController\/customBlackPin","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/MapsViewController\/mapsView","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/MapsViewController\/searchBtn","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/MapsViewController\/searchLabel","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/MapsViewController\/selectBtn"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/MapsViewController\/initWithCoder:","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/MapsViewController\/initWithNibName:bundle:","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/MapsViewController\/onSearch(_:)","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/MapsViewController\/onSelection(_:)","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/MapsViewController\/viewDidLoad()"]},{"title":"Default Implementations","identifiers":["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/MapsViewController\/CLLocationManagerDelegate-Implementations","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/MapsViewController\/GMSAutocompleteViewControllerDelegate-Implementations","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/MapsViewController\/GMSMapViewDelegate-Implementations","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/MapsViewController\/LocationDelegate-Implementations"],"generated":true}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/MasterViewController"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"MapsViewController"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/MasterViewController","preciseIdentifier":"c:@M@Yababa@objc(cs)MasterViewController","text":"MasterViewController"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1MapsViewController~1searchBtn\/title","value":"searchBtn"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1MapsViewController~1searchBtn\/fragments","value":[{"kind":"identifier","text":"searchBtn"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1MapsViewController~1onSearch(_:)\/title","value":"onSearch:"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1MapsViewController~1onSearch(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onSearch:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1MapsViewController~1customBlackPin\/title","value":"customBlackPin"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1MapsViewController~1customBlackPin\/fragments","value":[{"kind":"identifier","text":"customBlackPin"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1MapsViewController~1selectBtn\/title","value":"selectBtn"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1MapsViewController~1selectBtn\/fragments","value":[{"kind":"identifier","text":"selectBtn"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1MapsViewController~1mapsView\/title","value":"mapsView"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1MapsViewController~1mapsView\/fragments","value":[{"kind":"identifier","text":"mapsView"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1MapsViewController~1backBtn\/title","value":"backBtn"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1MapsViewController~1backBtn\/fragments","value":[{"kind":"identifier","text":"backBtn"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1LocationDelegate\/title","value":"LocationDelegate"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1LocationDelegate\/fragments","value":[{"kind":"identifier","text":"LocationDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1MapsViewController~1viewDidLoad()\/title","value":"viewDidLoad"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1MapsViewController~1viewDidLoad()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"viewDidLoad"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1MapsViewController~1onSelection(_:)\/title","value":"onSelection:"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1MapsViewController~1onSelection(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onSelection:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1MasterViewController\/title","value":"MasterViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1MasterViewController\/fragments","value":[{"kind":"identifier","text":"MasterViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1MapsViewController~1searchLabel\/title","value":"searchLabel"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1MapsViewController~1searchLabel\/fragments","value":[{"kind":"identifier","text":"searchLabel"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1MapsViewController\/title","value":"MapsViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1MapsViewController\/fragments","value":[{"kind":"identifier","text":"MapsViewController"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}