{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MasterViewController"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/yababa\/masterviewcontroller"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/yababa\/masterviewcontroller"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.yababaGmbH.yababa\/objc(cs)UIViewController"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AddressSelectionListSceneViewController","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CheckoutSceneViewController","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CompleteProfileSceneViewController","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/DeliveryAreasViewController","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/DiscountsViewController","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/DynamicLayoutScreen","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/FragmentDrawerViewController","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/JoinSceneViewController","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/LanguageSelectionViewController","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/MapsViewController","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/MyOrdersSceneViewController","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/MyProfileViewController","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/OrderDetailsSceneViewController","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/PhoneNumberVerificationSceneViewController","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ProductDetailsSceneViewController","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ReceiptViewController","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ShoppingCartSceneViewController","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/SignupSceneViewController","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/StripeGatewayViewController","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/WelcomeSceneViewController"],"kind":"relationships","title":"Inherited By","type":"inheritedBy"},{"identifiers":["doc:\/\/com.yababaGmbH.yababa\/objc(pl)NSCoding","doc:\/\/com.yababaGmbH.yababa\/objc(pl)NSExtensionRequestHandling","doc:\/\/com.yababaGmbH.yababa\/objc(pl)NSObject","doc:\/\/com.yababaGmbH.yababa\/12SkeletonView17AssociatedObjectsP","doc:\/\/com.yababaGmbH.yababa\/s7CVarArgP","doc:\/\/com.yababaGmbH.yababa\/s28CustomDebugStringConvertibleP","doc:\/\/com.yababaGmbH.yababa\/s23CustomStringConvertibleP","doc:\/\/com.yababaGmbH.yababa\/SQ","doc:\/\/com.yababaGmbH.yababa\/SH","doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIActivityItemsConfigurationProviding","doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIAppearanceContainer","doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIContentContainer","doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIFocusEnvironment","doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIPasteConfigurationSupporting","doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIResponderStandardEditActions","doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIStateRestoring","doc:\/\/com.yababaGmbH.yababa\/objc(pl)UITraitEnvironment","doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIUserActivityRestoring"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/MasterViewController","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/MasterViewController\/hidesBottomBarWhenPushed","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/MasterViewController\/infoView","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/MasterViewController\/infoViewSubTitleLabel","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/MasterViewController\/infoViewTitleLabel","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/MasterViewController\/navBarTheme"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/MasterViewController\/makeCustomBackBtn(isDark:)","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/MasterViewController\/onBack()","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/MasterViewController\/onDismiss()","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/MasterViewController\/setNavigationBarTheme(_:)","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/MasterViewController\/setTitle(_:)","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/MasterViewController\/setupNavigationBar()","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/MasterViewController\/showPopupMessage(withTitle:_:)","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/MasterViewController\/viewDidAppear(_:)","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/MasterViewController\/viewDidLoad()","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/MasterViewController\/viewWillAppear(_:)"]}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MasterViewController"}],"title":"MasterViewController","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@Yababa@objc(cs)MasterViewController","modules":[{"name":"Yababa"}],"navigatorTitle":[{"kind":"identifier","text":"MasterViewController"}]},"hierarchy":{"paths":[["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa"]]},"references":{"doc://com.yababaGmbH.yababa/documentation/Yababa/MasterViewController/initWithCoder:":{"role":"symbol","title":"initWithCoder:","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithCoder:"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/MasterViewController\/initWithCoder:","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithCoder:"}],"url":"\/documentation\/yababa\/masterviewcontroller\/initwithcoder:"},"doc://com.yababaGmbH.yababa/12SkeletonView17AssociatedObjectsP":{"type":"unresolvable","title":"SkeletonView.AssociatedObjects","identifier":"doc:\/\/com.yababaGmbH.yababa\/12SkeletonView17AssociatedObjectsP"},"doc://com.yababaGmbH.yababa/documentation/Yababa/JoinSceneViewController":{"role":"symbol","title":"JoinSceneViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"JoinSceneViewController"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/JoinSceneViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"JoinSceneViewController"}],"url":"\/documentation\/yababa\/joinsceneviewcontroller"},"doc://com.yababaGmbH.yababa/documentation/Yababa/DynamicLayoutScreen":{"role":"symbol","title":"DynamicLayoutScreen","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DynamicLayoutScreen"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/DynamicLayoutScreen","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DynamicLayoutScreen"}],"url":"\/documentation\/yababa\/dynamiclayoutscreen"},"doc://com.yababaGmbH.yababa/documentation/Yababa/MasterViewController/infoViewSubTitleLabel":{"role":"symbol","title":"infoViewSubTitleLabel","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"infoViewSubTitleLabel"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UILabel","preciseIdentifier":"c:objc(cs)UILabel"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/MasterViewController\/infoViewSubTitleLabel","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"infoViewSubTitleLabel"}],"url":"\/documentation\/yababa\/masterviewcontroller\/infoviewsubtitlelabel"},"doc://com.yababaGmbH.yababa/documentation/Yababa/ReceiptViewController":{"role":"symbol","title":"ReceiptViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ReceiptViewController"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ReceiptViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ReceiptViewController"}],"url":"\/documentation\/yababa\/receiptviewcontroller"},"doc://com.yababaGmbH.yababa/documentation/Yababa/MasterViewController/setNavigationBarTheme(_:)":{"role":"symbol","title":"setNavigationBarTheme(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setNavigationBarTheme"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NavBarTheme","preciseIdentifier":"s:6Yababa11NavBarThemea"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/MasterViewController\/setNavigationBarTheme(_:)","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/masterviewcontroller\/setnavigationbartheme(_:)"},"doc://com.yababaGmbH.yababa/documentation/Yababa/MapsViewController":{"role":"symbol","title":"MapsViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MapsViewController"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/MapsViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MapsViewController"}],"url":"\/documentation\/yababa\/mapsviewcontroller"},"doc://com.yababaGmbH.yababa/objc(pl)UIPasteConfigurationSupporting":{"type":"unresolvable","title":"UIKit.UIPasteConfigurationSupporting","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIPasteConfigurationSupporting"},"doc://com.yababaGmbH.yababa/documentation/Yababa/DeliveryAreasViewController":{"role":"symbol","title":"DeliveryAreasViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DeliveryAreasViewController"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/DeliveryAreasViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DeliveryAreasViewController"}],"url":"\/documentation\/yababa\/deliveryareasviewcontroller"},"doc://com.yababaGmbH.yababa/objc(pl)UIActivityItemsConfigurationProviding":{"type":"unresolvable","title":"UIKit.UIActivityItemsConfigurationProviding","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIActivityItemsConfigurationProviding"},"doc://com.yababaGmbH.yababa/documentation/Yababa/MasterViewController/viewWillAppear(_:)":{"role":"symbol","title":"viewWillAppear(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"viewWillAppear"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/MasterViewController\/viewWillAppear(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"viewWillAppear:"}],"url":"\/documentation\/yababa\/masterviewcontroller\/viewwillappear(_:)"},"doc://com.yababaGmbH.yababa/documentation/Yababa/MasterViewController/viewDidLoad()":{"role":"symbol","title":"viewDidLoad()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"viewDidLoad"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/MasterViewController\/viewDidLoad()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"viewDidLoad"}],"url":"\/documentation\/yababa\/masterviewcontroller\/viewdidload()"},"doc://com.yababaGmbH.yababa/objc(pl)UITraitEnvironment":{"type":"unresolvable","title":"UIKit.UITraitEnvironment","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)UITraitEnvironment"},"doc://com.yababaGmbH.yababa/documentation/Yababa/LanguageSelectionViewController":{"role":"symbol","title":"LanguageSelectionViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"LanguageSelectionViewController"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/LanguageSelectionViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"LanguageSelectionViewController"}],"url":"\/documentation\/yababa\/languageselectionviewcontroller"},"doc://com.yababaGmbH.yababa/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.yababaGmbH.yababa\/s7CVarArgP"},"doc://com.yababaGmbH.yababa/documentation/Yababa/MasterViewController/infoViewTitleLabel":{"role":"symbol","title":"infoViewTitleLabel","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"infoViewTitleLabel"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UILabel","preciseIdentifier":"c:objc(cs)UILabel"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/MasterViewController\/infoViewTitleLabel","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"infoViewTitleLabel"}],"url":"\/documentation\/yababa\/masterviewcontroller\/infoviewtitlelabel"},"doc://com.yababaGmbH.yababa/documentation/Yababa/MasterViewController/onBack()":{"role":"symbol","title":"onBack()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onBack"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/MasterViewController\/onBack()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"onBack"}],"url":"\/documentation\/yababa\/masterviewcontroller\/onback()"},"doc://com.yababaGmbH.yababa/documentation/Yababa/PhoneNumberVerificationSceneViewController":{"role":"symbol","title":"PhoneNumberVerificationSceneViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PhoneNumberVerificationSceneViewController"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/PhoneNumberVerificationSceneViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PhoneNumberVerificationSceneViewController"}],"url":"\/documentation\/yababa\/phonenumberverificationsceneviewcontroller"},"doc://com.yababaGmbH.yababa/objc(pl)UIContentContainer":{"type":"unresolvable","title":"UIKit.UIContentContainer","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIContentContainer"},"doc://com.yababaGmbH.yababa/documentation/Yababa/WelcomeSceneViewController":{"role":"symbol","title":"WelcomeSceneViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"WelcomeSceneViewController"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/WelcomeSceneViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"WelcomeSceneViewController"}],"url":"\/documentation\/yababa\/welcomesceneviewcontroller"},"doc://com.yababaGmbH.yababa/documentation/Yababa/MasterViewController/setupNavigationBar()":{"role":"symbol","title":"setupNavigationBar()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setupNavigationBar"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/MasterViewController\/setupNavigationBar()","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/masterviewcontroller\/setupnavigationbar()"},"doc://com.yababaGmbH.yababa/objc(pl)UIFocusEnvironment":{"type":"unresolvable","title":"UIKit.UIFocusEnvironment","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIFocusEnvironment"},"doc://com.yababaGmbH.yababa/documentation/Yababa/OrderDetailsSceneViewController":{"role":"symbol","title":"OrderDetailsSceneViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"OrderDetailsSceneViewController"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/OrderDetailsSceneViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"OrderDetailsSceneViewController"}],"url":"\/documentation\/yababa\/orderdetailssceneviewcontroller"},"doc://com.yababaGmbH.yababa/documentation/Yababa/AddressSelectionListSceneViewController":{"role":"symbol","title":"AddressSelectionListSceneViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AddressSelectionListSceneViewController"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AddressSelectionListSceneViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AddressSelectionListSceneViewController"}],"url":"\/documentation\/yababa\/addressselectionlistsceneviewcontroller"},"doc://com.yababaGmbH.yababa/documentation/Yababa/MasterViewController/makeCustomBackBtn(isDark:)":{"role":"symbol","title":"makeCustomBackBtn(isDark:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"makeCustomBackBtn"},{"kind":"text","text":"("},{"kind":"externalParam","text":"isDark"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"UIBarButtonItem","preciseIdentifier":"c:objc(cs)UIBarButtonItem"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/MasterViewController\/makeCustomBackBtn(isDark:)","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/masterviewcontroller\/makecustombackbtn(isdark:)"},"doc://com.yababaGmbH.yababa/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.yababaGmbH.yababa\/SQ"},"doc://com.yababaGmbH.yababa/documentation/Yababa/MyOrdersSceneViewController":{"role":"symbol","title":"MyOrdersSceneViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MyOrdersSceneViewController"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/MyOrdersSceneViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MyOrdersSceneViewController"}],"url":"\/documentation\/yababa\/myorderssceneviewcontroller"},"doc://com.yababaGmbH.yababa/documentation/Yababa/CompleteProfileSceneViewController":{"role":"symbol","title":"CompleteProfileSceneViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CompleteProfileSceneViewController"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CompleteProfileSceneViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CompleteProfileSceneViewController"}],"url":"\/documentation\/yababa\/completeprofilesceneviewcontroller"},"doc://com.yababaGmbH.yababa/documentation/Yababa/ShoppingCartSceneViewController":{"role":"symbol","title":"ShoppingCartSceneViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ShoppingCartSceneViewController"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ShoppingCartSceneViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ShoppingCartSceneViewController"}],"url":"\/documentation\/yababa\/shoppingcartsceneviewcontroller"},"doc://com.yababaGmbH.yababa/documentation/Yababa/MasterViewController/showPopupMessage(withTitle:_:)":{"role":"symbol","title":"showPopupMessage(withTitle:_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"showPopupMessage"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withTitle"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/MasterViewController\/showPopupMessage(withTitle:_:)","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/masterviewcontroller\/showpopupmessage(withtitle:_:)"},"doc://com.yababaGmbH.yababa/objc(pl)UIAppearanceContainer":{"type":"unresolvable","title":"UIKit.UIAppearanceContainer","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIAppearanceContainer"},"doc://com.yababaGmbH.yababa/documentation/Yababa/MasterViewController/viewDidAppear(_:)":{"role":"symbol","title":"viewDidAppear(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"viewDidAppear"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/MasterViewController\/viewDidAppear(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"viewDidAppear:"}],"url":"\/documentation\/yababa\/masterviewcontroller\/viewdidappear(_:)"},"doc://com.yababaGmbH.yababa/documentation/Yababa/FragmentDrawerViewController":{"role":"symbol","title":"FragmentDrawerViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FragmentDrawerViewController"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/FragmentDrawerViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FragmentDrawerViewController"}],"url":"\/documentation\/yababa\/fragmentdrawerviewcontroller"},"doc://com.yababaGmbH.yababa/objc(pl)UIStateRestoring":{"type":"unresolvable","title":"UIKit.UIStateRestoring","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIStateRestoring"},"doc://com.yababaGmbH.yababa/documentation/Yababa/CheckoutSceneViewController":{"role":"symbol","title":"CheckoutSceneViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CheckoutSceneViewController"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CheckoutSceneViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CheckoutSceneViewController"}],"url":"\/documentation\/yababa\/checkoutsceneviewcontroller"},"doc://com.yababaGmbH.yababa/documentation/Yababa/StripeGatewayViewController":{"role":"symbol","title":"StripeGatewayViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"StripeGatewayViewController"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/StripeGatewayViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"StripeGatewayViewController"}],"url":"\/documentation\/yababa\/stripegatewayviewcontroller"},"doc://com.yababaGmbH.yababa/documentation/Yababa/MasterViewController":{"role":"symbol","title":"MasterViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MasterViewController"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/MasterViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MasterViewController"}],"url":"\/documentation\/yababa\/masterviewcontroller"},"doc://com.yababaGmbH.yababa/objc(pl)UIUserActivityRestoring":{"type":"unresolvable","title":"UIKit.UIUserActivityRestoring","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIUserActivityRestoring"},"doc://com.yababaGmbH.yababa/documentation/Yababa":{"role":"collection","title":"Yababa","abstract":[{"type":"text","text":"Getting Started"}],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa","kind":"symbol","type":"topic","url":"\/documentation\/yababa"},"doc://com.yababaGmbH.yababa/documentation/Yababa/MyProfileViewController":{"role":"symbol","title":"MyProfileViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MyProfileViewController"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/MyProfileViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MyProfileViewController"}],"url":"\/documentation\/yababa\/myprofileviewcontroller"},"doc://com.yababaGmbH.yababa/documentation/Yababa/SignupSceneViewController":{"role":"symbol","title":"SignupSceneViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SignupSceneViewController"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/SignupSceneViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SignupSceneViewController"}],"url":"\/documentation\/yababa\/signupsceneviewcontroller"},"doc://com.yababaGmbH.yababa/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.yababaGmbH.yababa\/s23CustomStringConvertibleP"},"doc://com.yababaGmbH.yababa/documentation/Yababa/MasterViewController/setTitle(_:)":{"role":"symbol","title":"setTitle(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setTitle"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/MasterViewController\/setTitle(_:)","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/masterviewcontroller\/settitle(_:)"},"doc://com.yababaGmbH.yababa/objc(cs)UIViewController":{"type":"unresolvable","title":"UIViewController","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(cs)UIViewController"},"doc://com.yababaGmbH.yababa/documentation/Yababa/MasterViewController/initWithNibName:bundle:":{"role":"symbol","title":"initWithNibName:bundle:","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithNibName:bundle:"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/MasterViewController\/initWithNibName:bundle:","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithNibName:bundle:"}],"url":"\/documentation\/yababa\/masterviewcontroller\/initwithnibname:bundle:"},"doc://com.yababaGmbH.yababa/documentation/Yababa/MasterViewController/hidesBottomBarWhenPushed":{"role":"symbol","title":"hidesBottomBarWhenPushed","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"hidesBottomBarWhenPushed"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/MasterViewController\/hidesBottomBarWhenPushed","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"hidesBottomBarWhenPushed"}],"url":"\/documentation\/yababa\/masterviewcontroller\/hidesbottombarwhenpushed"},"doc://com.yababaGmbH.yababa/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.yababaGmbH.yababa\/s28CustomDebugStringConvertibleP"},"doc://com.yababaGmbH.yababa/objc(pl)NSExtensionRequestHandling":{"type":"unresolvable","title":"Foundation.NSExtensionRequestHandling","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)NSExtensionRequestHandling"},"doc://com.yababaGmbH.yababa/objc(pl)NSCoding":{"type":"unresolvable","title":"Foundation.NSCoding","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)NSCoding"},"doc://com.yababaGmbH.yababa/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)NSObject"},"doc://com.yababaGmbH.yababa/documentation/Yababa/MasterViewController/onDismiss()":{"role":"symbol","title":"onDismiss()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onDismiss"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/MasterViewController\/onDismiss()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"onDismiss"}],"url":"\/documentation\/yababa\/masterviewcontroller\/ondismiss()"},"doc://com.yababaGmbH.yababa/documentation/Yababa/MasterViewController/infoView":{"role":"symbol","title":"infoView","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"infoView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/MasterViewController\/infoView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"infoView"}],"url":"\/documentation\/yababa\/masterviewcontroller\/infoview"},"doc://com.yababaGmbH.yababa/documentation/Yababa/MasterViewController/navBarTheme":{"role":"symbol","title":"navBarTheme","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"navBarTheme"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NavBarTheme","preciseIdentifier":"s:6Yababa11NavBarThemea"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/MasterViewController\/navBarTheme","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/masterviewcontroller\/navbartheme"},"doc://com.yababaGmbH.yababa/documentation/Yababa/DiscountsViewController":{"role":"symbol","title":"DiscountsViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DiscountsViewController"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/DiscountsViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DiscountsViewController"}],"url":"\/documentation\/yababa\/discountsviewcontroller"},"doc://com.yababaGmbH.yababa/documentation/Yababa/ProductDetailsSceneViewController":{"role":"symbol","title":"ProductDetailsSceneViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ProductDetailsSceneViewController"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ProductDetailsSceneViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ProductDetailsSceneViewController"}],"url":"\/documentation\/yababa\/productdetailssceneviewcontroller"},"doc://com.yababaGmbH.yababa/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.yababaGmbH.yababa\/SH"},"doc://com.yababaGmbH.yababa/objc(pl)UIResponderStandardEditActions":{"type":"unresolvable","title":"UIKit.UIResponderStandardEditActions","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIResponderStandardEditActions"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"MasterViewController"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"MasterViewController"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"MasterViewController"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/MasterViewController\/hidesBottomBarWhenPushed","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/MasterViewController\/infoView","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/MasterViewController\/infoViewSubTitleLabel","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/MasterViewController\/infoViewTitleLabel"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/MasterViewController\/initWithCoder:","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/MasterViewController\/initWithNibName:bundle:","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/MasterViewController\/onBack()","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/MasterViewController\/onDismiss()","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/MasterViewController\/viewDidAppear(_:)","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/MasterViewController\/viewDidLoad()","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/MasterViewController\/viewWillAppear(_:)"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.yababaGmbH.yababa\/objc(cs)UIViewController"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AddressSelectionListSceneViewController","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CheckoutSceneViewController","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CompleteProfileSceneViewController","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/DeliveryAreasViewController","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/DiscountsViewController","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/DynamicLayoutScreen","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/FragmentDrawerViewController","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/JoinSceneViewController","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/LanguageSelectionViewController","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/MapsViewController","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/MyOrdersSceneViewController","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/MyProfileViewController","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/OrderDetailsSceneViewController","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/PhoneNumberVerificationSceneViewController","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ProductDetailsSceneViewController","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ReceiptViewController","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ShoppingCartSceneViewController","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/SignupSceneViewController","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/StripeGatewayViewController","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/WelcomeSceneViewController"],"kind":"relationships","title":"Inherited By","type":"inheritedBy"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"MasterViewController"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1JoinSceneViewController\/title","value":"JoinSceneViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1JoinSceneViewController\/fragments","value":[{"kind":"identifier","text":"JoinSceneViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1DynamicLayoutScreen\/title","value":"DynamicLayoutScreen"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1DynamicLayoutScreen\/fragments","value":[{"kind":"identifier","text":"DynamicLayoutScreen"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1MasterViewController~1infoViewSubTitleLabel\/title","value":"infoViewSubTitleLabel"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1MasterViewController~1infoViewSubTitleLabel\/fragments","value":[{"kind":"identifier","text":"infoViewSubTitleLabel"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1ReceiptViewController\/title","value":"ReceiptViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1ReceiptViewController\/fragments","value":[{"kind":"identifier","text":"ReceiptViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1MapsViewController\/title","value":"MapsViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1MapsViewController\/fragments","value":[{"kind":"identifier","text":"MapsViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1DeliveryAreasViewController\/title","value":"DeliveryAreasViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1DeliveryAreasViewController\/fragments","value":[{"kind":"identifier","text":"DeliveryAreasViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1MasterViewController~1viewWillAppear(_:)\/title","value":"viewWillAppear:"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1MasterViewController~1viewWillAppear(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"viewWillAppear:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1MasterViewController~1viewDidLoad()\/title","value":"viewDidLoad"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1MasterViewController~1viewDidLoad()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"viewDidLoad"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1LanguageSelectionViewController\/title","value":"LanguageSelectionViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1LanguageSelectionViewController\/fragments","value":[{"kind":"identifier","text":"LanguageSelectionViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1MasterViewController~1infoViewTitleLabel\/title","value":"infoViewTitleLabel"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1MasterViewController~1infoViewTitleLabel\/fragments","value":[{"kind":"identifier","text":"infoViewTitleLabel"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1MasterViewController~1onBack()\/title","value":"onBack"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1MasterViewController~1onBack()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onBack"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1PhoneNumberVerificationSceneViewController\/title","value":"PhoneNumberVerificationSceneViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1PhoneNumberVerificationSceneViewController\/fragments","value":[{"kind":"identifier","text":"PhoneNumberVerificationSceneViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1WelcomeSceneViewController\/title","value":"WelcomeSceneViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1WelcomeSceneViewController\/fragments","value":[{"kind":"identifier","text":"WelcomeSceneViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1OrderDetailsSceneViewController\/title","value":"OrderDetailsSceneViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1OrderDetailsSceneViewController\/fragments","value":[{"kind":"identifier","text":"OrderDetailsSceneViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1AddressSelectionListSceneViewController\/title","value":"AddressSelectionListSceneViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1AddressSelectionListSceneViewController\/fragments","value":[{"kind":"identifier","text":"AddressSelectionListSceneViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1MyOrdersSceneViewController\/title","value":"MyOrdersSceneViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1MyOrdersSceneViewController\/fragments","value":[{"kind":"identifier","text":"MyOrdersSceneViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1CompleteProfileSceneViewController\/title","value":"CompleteProfileSceneViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1CompleteProfileSceneViewController\/fragments","value":[{"kind":"identifier","text":"CompleteProfileSceneViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1ShoppingCartSceneViewController\/title","value":"ShoppingCartSceneViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1ShoppingCartSceneViewController\/fragments","value":[{"kind":"identifier","text":"ShoppingCartSceneViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1MasterViewController~1viewDidAppear(_:)\/title","value":"viewDidAppear:"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1MasterViewController~1viewDidAppear(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"viewDidAppear:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1FragmentDrawerViewController\/title","value":"FragmentDrawerViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1FragmentDrawerViewController\/fragments","value":[{"kind":"identifier","text":"FragmentDrawerViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1CheckoutSceneViewController\/title","value":"CheckoutSceneViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1CheckoutSceneViewController\/fragments","value":[{"kind":"identifier","text":"CheckoutSceneViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1StripeGatewayViewController\/title","value":"StripeGatewayViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1StripeGatewayViewController\/fragments","value":[{"kind":"identifier","text":"StripeGatewayViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1MasterViewController\/title","value":"MasterViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1MasterViewController\/fragments","value":[{"kind":"identifier","text":"MasterViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1MyProfileViewController\/title","value":"MyProfileViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1MyProfileViewController\/fragments","value":[{"kind":"identifier","text":"MyProfileViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1SignupSceneViewController\/title","value":"SignupSceneViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1SignupSceneViewController\/fragments","value":[{"kind":"identifier","text":"SignupSceneViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1MasterViewController~1hidesBottomBarWhenPushed\/title","value":"hidesBottomBarWhenPushed"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1MasterViewController~1hidesBottomBarWhenPushed\/fragments","value":[{"kind":"identifier","text":"hidesBottomBarWhenPushed"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1MasterViewController~1onDismiss()\/title","value":"onDismiss"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1MasterViewController~1onDismiss()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onDismiss"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1MasterViewController~1infoView\/title","value":"infoView"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1MasterViewController~1infoView\/fragments","value":[{"kind":"identifier","text":"infoView"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1DiscountsViewController\/title","value":"DiscountsViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1DiscountsViewController\/fragments","value":[{"kind":"identifier","text":"DiscountsViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1ProductDetailsSceneViewController\/title","value":"ProductDetailsSceneViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1ProductDetailsSceneViewController\/fragments","value":[{"kind":"identifier","text":"ProductDetailsSceneViewController"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}