{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MyPhoneNumberTextField"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/yababa\/myphonenumbertextfield"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/yababa\/myphonenumbertextfield"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.yababaGmbH.yababa\/@M@PhoneNumberKit@objc(cs)PhoneNumberTextField"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.yababaGmbH.yababa\/objc(pl)NSCoding","doc:\/\/com.yababaGmbH.yababa\/objc(pl)NSObject","doc:\/\/com.yababaGmbH.yababa\/14PhoneNumberKit25CountryCodePickerDelegateP","doc:\/\/com.yababaGmbH.yababa\/objc(pl)CALayerDelegate","doc:\/\/com.yababaGmbH.yababa\/12SkeletonView17AssociatedObjectsP","doc:\/\/com.yababaGmbH.yababa\/12SkeletonView15IterableElementP","doc:\/\/com.yababaGmbH.yababa\/12SkeletonView11RecoverableP","doc:\/\/com.yababaGmbH.yababa\/6Stripe19SafeAreaLayoutGuideP","doc:\/\/com.yababaGmbH.yababa\/s7CVarArgP","doc:\/\/com.yababaGmbH.yababa\/s28CustomDebugStringConvertibleP","doc:\/\/com.yababaGmbH.yababa\/s23CustomStringConvertibleP","doc:\/\/com.yababaGmbH.yababa\/SQ","doc:\/\/com.yababaGmbH.yababa\/SH","doc:\/\/com.yababaGmbH.yababa\/s8SendableP","doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIAccessibilityIdentification","doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIActivityItemsConfigurationProviding","doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIAppearance","doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIAppearanceContainer","doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIContentSizeCategoryAdjusting","doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIContextMenuInteractionDelegate","doc:\/\/com.yababaGmbH.yababa\/objc(pl)UICoordinateSpace","doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIDynamicItem","doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIFocusEnvironment","doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIFocusItem","doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIFocusItemContainer","doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIKeyInput","doc:\/\/com.yababaGmbH.yababa\/objc(pl)UILargeContentViewerItem","doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIPasteConfigurationSupporting","doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIPopoverPresentationControllerSourceItem","doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIResponderStandardEditActions","doc:\/\/com.yababaGmbH.yababa\/objc(pl)UITextDraggable","doc:\/\/com.yababaGmbH.yababa\/objc(pl)UITextDroppable","doc:\/\/com.yababaGmbH.yababa\/objc(pl)UITextFieldDelegate","doc:\/\/com.yababaGmbH.yababa\/objc(pl)UITextInput","doc:\/\/com.yababaGmbH.yababa\/objc(pl)UITextInputTraits","doc:\/\/com.yababaGmbH.yababa\/objc(pl)UITextPasteConfigurationSupporting","doc:\/\/com.yababaGmbH.yababa\/objc(pl)UITraitEnvironment","doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIUserActivityRestoring"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/MyPhoneNumberTextField","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/MyPhoneNumberTextField\/getFormattedPhoneNumber()","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/MyPhoneNumberTextField\/isPhoneNumberValid()","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/MyPhoneNumberTextField\/refresh()","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/MyPhoneNumberTextField\/setupUI()"]}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MyPhoneNumberTextField"}],"title":"MyPhoneNumberTextField","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@Yababa@objc(cs)MyPhoneNumberTextField","modules":[{"name":"Yababa"}],"navigatorTitle":[{"kind":"identifier","text":"MyPhoneNumberTextField"}]},"hierarchy":{"paths":[["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa"]]},"references":{"doc://com.yababaGmbH.yababa/objc(pl)UIContextMenuInteractionDelegate":{"type":"unresolvable","title":"UIKit.UIContextMenuInteractionDelegate","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIContextMenuInteractionDelegate"},"doc://com.yababaGmbH.yababa/documentation/Yababa":{"role":"collection","title":"Yababa","abstract":[{"type":"text","text":"Getting Started"}],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa","kind":"symbol","type":"topic","url":"\/documentation\/yababa"},"doc://com.yababaGmbH.yababa/objc(pl)UITextInput":{"type":"unresolvable","title":"UIKit.UITextInput","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)UITextInput"},"doc://com.yababaGmbH.yababa/objc(pl)UIPopoverPresentationControllerSourceItem":{"type":"unresolvable","title":"UIKit.UIPopoverPresentationControllerSourceItem","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIPopoverPresentationControllerSourceItem"},"doc://com.yababaGmbH.yababa/objc(pl)UILargeContentViewerItem":{"type":"unresolvable","title":"UIKit.UILargeContentViewerItem","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)UILargeContentViewerItem"},"doc://com.yababaGmbH.yababa/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)NSObject"},"doc://com.yababaGmbH.yababa/objc(pl)UIAppearance":{"type":"unresolvable","title":"UIKit.UIAppearance","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIAppearance"},"doc://com.yababaGmbH.yababa/objc(pl)CALayerDelegate":{"type":"unresolvable","title":"QuartzCore.CALayerDelegate","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)CALayerDelegate"},"doc://com.yababaGmbH.yababa/objc(pl)UIFocusItemContainer":{"type":"unresolvable","title":"UIKit.UIFocusItemContainer","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIFocusItemContainer"},"doc://com.yababaGmbH.yababa/objc(pl)UICoordinateSpace":{"type":"unresolvable","title":"UIKit.UICoordinateSpace","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)UICoordinateSpace"},"doc://com.yababaGmbH.yababa/objc(pl)UITextDroppable":{"type":"unresolvable","title":"UIKit.UITextDroppable","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)UITextDroppable"},"doc://com.yababaGmbH.yababa/objc(pl)UIFocusItem":{"type":"unresolvable","title":"UIKit.UIFocusItem","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIFocusItem"},"doc://com.yababaGmbH.yababa/documentation/Yababa/MyPhoneNumberTextField/setupUI()":{"role":"symbol","title":"setupUI()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setupUI"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/MyPhoneNumberTextField\/setupUI()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"setupUI"}],"url":"\/documentation\/yababa\/myphonenumbertextfield\/setupui()"},"doc://com.yababaGmbH.yababa/objc(pl)UIPasteConfigurationSupporting":{"type":"unresolvable","title":"UIKit.UIPasteConfigurationSupporting","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIPasteConfigurationSupporting"},"doc://com.yababaGmbH.yababa/14PhoneNumberKit25CountryCodePickerDelegateP":{"type":"unresolvable","title":"PhoneNumberKit.CountryCodePickerDelegate","identifier":"doc:\/\/com.yababaGmbH.yababa\/14PhoneNumberKit25CountryCodePickerDelegateP"},"doc://com.yababaGmbH.yababa/objc(pl)UITextDraggable":{"type":"unresolvable","title":"UIKit.UITextDraggable","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)UITextDraggable"},"doc://com.yababaGmbH.yababa/12SkeletonView11RecoverableP":{"type":"unresolvable","title":"SkeletonView.Recoverable","identifier":"doc:\/\/com.yababaGmbH.yababa\/12SkeletonView11RecoverableP"},"doc://com.yababaGmbH.yababa/documentation/Yababa/MyPhoneNumberTextField/getFormattedPhoneNumber()":{"role":"symbol","title":"getFormattedPhoneNumber()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getFormattedPhoneNumber"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/MyPhoneNumberTextField\/getFormattedPhoneNumber()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"getFormattedPhoneNumber"}],"url":"\/documentation\/yababa\/myphonenumbertextfield\/getformattedphonenumber()"},"doc://com.yababaGmbH.yababa/documentation/Yababa/MyPhoneNumberTextField/refresh()":{"role":"symbol","title":"refresh()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"refresh"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/MyPhoneNumberTextField\/refresh()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"refresh"}],"url":"\/documentation\/yababa\/myphonenumbertextfield\/refresh()"},"doc://com.yababaGmbH.yababa/documentation/Yababa/MyPhoneNumberTextField/initWithCoder:":{"role":"symbol","title":"initWithCoder:","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithCoder:"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/MyPhoneNumberTextField\/initWithCoder:","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithCoder:"}],"url":"\/documentation\/yababa\/myphonenumbertextfield\/initwithcoder:"},"doc://com.yababaGmbH.yababa/objc(pl)UIAppearanceContainer":{"type":"unresolvable","title":"UIKit.UIAppearanceContainer","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIAppearanceContainer"},"doc://com.yababaGmbH.yababa/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.yababaGmbH.yababa\/s28CustomDebugStringConvertibleP"},"doc://com.yababaGmbH.yababa/documentation/Yababa/MyPhoneNumberTextField/initWithFrame:":{"role":"symbol","title":"initWithFrame:","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithFrame:"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/MyPhoneNumberTextField\/initWithFrame:","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithFrame:"}],"url":"\/documentation\/yababa\/myphonenumbertextfield\/initwithframe:"},"doc://com.yababaGmbH.yababa/objc(pl)UITextInputTraits":{"type":"unresolvable","title":"UIKit.UITextInputTraits","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)UITextInputTraits"},"doc://com.yababaGmbH.yababa/objc(pl)UITextPasteConfigurationSupporting":{"type":"unresolvable","title":"UIKit.UITextPasteConfigurationSupporting","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)UITextPasteConfigurationSupporting"},"doc://com.yababaGmbH.yababa/6Stripe19SafeAreaLayoutGuideP":{"type":"unresolvable","title":"Stripe.SafeAreaLayoutGuide","identifier":"doc:\/\/com.yababaGmbH.yababa\/6Stripe19SafeAreaLayoutGuideP"},"doc://com.yababaGmbH.yababa/@M@PhoneNumberKit@objc(cs)PhoneNumberTextField":{"type":"unresolvable","title":"_TtC14PhoneNumberKit20PhoneNumberTextField","identifier":"doc:\/\/com.yababaGmbH.yababa\/@M@PhoneNumberKit@objc(cs)PhoneNumberTextField"},"doc://com.yababaGmbH.yababa/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/com.yababaGmbH.yababa\/s8SendableP"},"doc://com.yababaGmbH.yababa/documentation/Yababa/MyPhoneNumberTextField/isPhoneNumberValid()":{"role":"symbol","title":"isPhoneNumberValid()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"isPhoneNumberValid"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/MyPhoneNumberTextField\/isPhoneNumberValid()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"isPhoneNumberValid"}],"url":"\/documentation\/yababa\/myphonenumbertextfield\/isphonenumbervalid()"},"doc://com.yababaGmbH.yababa/documentation/Yababa/MyPhoneNumberTextField":{"role":"symbol","title":"MyPhoneNumberTextField","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MyPhoneNumberTextField"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/MyPhoneNumberTextField","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MyPhoneNumberTextField"}],"url":"\/documentation\/yababa\/myphonenumbertextfield"},"doc://com.yababaGmbH.yababa/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.yababaGmbH.yababa\/s23CustomStringConvertibleP"},"doc://com.yababaGmbH.yababa/12SkeletonView15IterableElementP":{"type":"unresolvable","title":"SkeletonView.IterableElement","identifier":"doc:\/\/com.yababaGmbH.yababa\/12SkeletonView15IterableElementP"},"doc://com.yababaGmbH.yababa/objc(pl)UIFocusEnvironment":{"type":"unresolvable","title":"UIKit.UIFocusEnvironment","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIFocusEnvironment"},"doc://com.yababaGmbH.yababa/objc(pl)UIDynamicItem":{"type":"unresolvable","title":"UIKit.UIDynamicItem","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIDynamicItem"},"doc://com.yababaGmbH.yababa/objc(pl)UIAccessibilityIdentification":{"type":"unresolvable","title":"UIKit.UIAccessibilityIdentification","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIAccessibilityIdentification"},"doc://com.yababaGmbH.yababa/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.yababaGmbH.yababa\/SH"},"doc://com.yababaGmbH.yababa/objc(pl)UIKeyInput":{"type":"unresolvable","title":"UIKit.UIKeyInput","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIKeyInput"},"doc://com.yababaGmbH.yababa/objc(pl)UIContentSizeCategoryAdjusting":{"type":"unresolvable","title":"UIKit.UIContentSizeCategoryAdjusting","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIContentSizeCategoryAdjusting"},"doc://com.yababaGmbH.yababa/objc(pl)UIResponderStandardEditActions":{"type":"unresolvable","title":"UIKit.UIResponderStandardEditActions","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIResponderStandardEditActions"},"doc://com.yababaGmbH.yababa/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.yababaGmbH.yababa\/s7CVarArgP"},"doc://com.yababaGmbH.yababa/12SkeletonView17AssociatedObjectsP":{"type":"unresolvable","title":"SkeletonView.AssociatedObjects","identifier":"doc:\/\/com.yababaGmbH.yababa\/12SkeletonView17AssociatedObjectsP"},"doc://com.yababaGmbH.yababa/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.yababaGmbH.yababa\/SQ"},"doc://com.yababaGmbH.yababa/objc(pl)UITraitEnvironment":{"type":"unresolvable","title":"UIKit.UITraitEnvironment","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)UITraitEnvironment"},"doc://com.yababaGmbH.yababa/objc(pl)NSCoding":{"type":"unresolvable","title":"Foundation.NSCoding","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)NSCoding"},"doc://com.yababaGmbH.yababa/objc(pl)UITextFieldDelegate":{"type":"unresolvable","title":"UIKit.UITextFieldDelegate","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)UITextFieldDelegate"},"doc://com.yababaGmbH.yababa/objc(pl)UIUserActivityRestoring":{"type":"unresolvable","title":"UIKit.UIUserActivityRestoring","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIUserActivityRestoring"},"doc://com.yababaGmbH.yababa/objc(pl)UIActivityItemsConfigurationProviding":{"type":"unresolvable","title":"UIKit.UIActivityItemsConfigurationProviding","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIActivityItemsConfigurationProviding"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"MyPhoneNumberTextField"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"MyPhoneNumberTextField"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"MyPhoneNumberTextField"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/MyPhoneNumberTextField\/getFormattedPhoneNumber()","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/MyPhoneNumberTextField\/initWithCoder:","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/MyPhoneNumberTextField\/initWithFrame:","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/MyPhoneNumberTextField\/isPhoneNumberValid()","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/MyPhoneNumberTextField\/refresh()","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/MyPhoneNumberTextField\/setupUI()"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.yababaGmbH.yababa\/@M@PhoneNumberKit@objc(cs)PhoneNumberTextField"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"MyPhoneNumberTextField"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"PhoneNumberTextField","preciseIdentifier":"c:@M@PhoneNumberKit@objc(cs)PhoneNumberTextField"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1MyPhoneNumberTextField~1setupUI()\/title","value":"setupUI"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1MyPhoneNumberTextField~1setupUI()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setupUI"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1MyPhoneNumberTextField~1getFormattedPhoneNumber()\/title","value":"getFormattedPhoneNumber"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1MyPhoneNumberTextField~1getFormattedPhoneNumber()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"getFormattedPhoneNumber"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1MyPhoneNumberTextField~1refresh()\/title","value":"refresh"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1MyPhoneNumberTextField~1refresh()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"refresh"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1MyPhoneNumberTextField~1isPhoneNumberValid()\/title","value":"isPhoneNumberValid"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1MyPhoneNumberTextField~1isPhoneNumberValid()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"isPhoneNumberValid"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1MyPhoneNumberTextField\/title","value":"MyPhoneNumberTextField"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1MyPhoneNumberTextField\/fragments","value":[{"kind":"identifier","text":"MyPhoneNumberTextField"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}