{"primaryContentSections":[{"kind":"content","content":[{"anchor":"Overview","level":2,"type":"heading","text":"Overview"},{"type":"paragraph","inlineContent":[{"type":"text","text":"The Network layer of the iOS app  is divided in multiple files such that it tries to mirror the Backend endpoint controllers. Each class contains a route (sub path) that is appended to the base url, followed by the api endpoint (baseurl\/route\/endpoint)."}]},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"reference","isActive":true,"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/PublicController"}]}]}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"Contains endpoints associated with user login and signup requests"}]},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"reference","isActive":true,"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ApiController"}]}]}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"Contains general endpoints that user will request"}]},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"reference","isActive":true,"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CatalogueStockController"}]}]}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"Contains endpoints primary related to Catalogue and their stock quantities"}]},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"reference","isActive":true,"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/OnlineBookingController"}]}]}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"Contains endpoints primary related to checkout and payment. Also contains some endpoints related to user addresses."}]},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"reference","isActive":true,"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/BannersAPIController"}]}]}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"Contains endpoints related to Banners"}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"The core implementation of network API requests is in "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ServiceController"},{"type":"text","text":". It’s a protocol with extensions (default implementations) that the above listed controller classes conform to i.e. Composition. It uses Alamofire to make the request and Object Mapper to map the response."}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"A helper entity "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/NetworkRequestPrinter"},{"type":"text","text":" can be used to log the request and response of a given endpoint call. This can be done easily by passing an optional parameter ‘printLog’ when calling the request method of ServiceController."}]},{"type":"paragraph","inlineContent":[{"type":"image","identifier":"NetworkLayer.png"}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/yababa\/networklayer"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/yababa\/networklayer"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/NetworkLayer","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Responsible for managing the communication between the app and backend server"}],"kind":"article","metadata":{"roleHeading":"Article","title":"Network Layer","role":"article","modules":[{"name":"Yababa"}]},"hierarchy":{"paths":[["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa"]]},"seeAlsoSections":[{"title":"Others","identifiers":["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AnalyticsDocumentation","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/InAppMessages"],"generated":true}],"references":{"doc://com.yababaGmbH.yababa/documentation/Yababa/BannersAPIController":{"role":"symbol","title":"BannersAPIController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"BannersAPIController"}],"abstract":[{"type":"text","text":"Contains endpoints related to Banners"}],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/BannersAPIController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"BannersAPIController"}],"url":"\/documentation\/yababa\/bannersapicontroller"},"doc://com.yababaGmbH.yababa/documentation/Yababa/CatalogueStockController":{"role":"symbol","title":"CatalogueStockController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CatalogueStockController"}],"abstract":[{"type":"text","text":"Contains endpoints primary related to Catalogue and their stock quantities"}],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CatalogueStockController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CatalogueStockController"}],"url":"\/documentation\/yababa\/cataloguestockcontroller"},"doc://com.yababaGmbH.yababa/documentation/Yababa/NetworkRequestPrinter":{"role":"symbol","title":"NetworkRequestPrinter","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"NetworkRequestPrinter"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/NetworkRequestPrinter","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"NetworkRequestPrinter"}],"url":"\/documentation\/yababa\/networkrequestprinter"},"doc://com.yababaGmbH.yababa/documentation/Yababa/OnlineBookingController":{"role":"symbol","title":"OnlineBookingController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"OnlineBookingController"}],"abstract":[{"type":"text","text":"Contains endpoints primary related to checkout and payment. Also contains some endpoints related to user addresses."}],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/OnlineBookingController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"OnlineBookingController"}],"url":"\/documentation\/yababa\/onlinebookingcontroller"},"doc://com.yababaGmbH.yababa/documentation/Yababa/ServiceController":{"role":"symbol","title":"ServiceController","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"ServiceController"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ServiceController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ServiceController"}],"url":"\/documentation\/yababa\/servicecontroller"},"doc://com.yababaGmbH.yababa/documentation/Yababa/PublicController":{"role":"symbol","title":"PublicController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PublicController"}],"abstract":[{"type":"text","text":"Contains endpoints associated with user login and signup requests."}],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/PublicController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PublicController"}],"url":"\/documentation\/yababa\/publiccontroller"},"doc://com.yababaGmbH.yababa/documentation/Yababa":{"role":"collection","title":"Yababa","abstract":[{"type":"text","text":"Getting Started"}],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa","kind":"symbol","type":"topic","url":"\/documentation\/yababa"},"doc://com.yababaGmbH.yababa/documentation/Yababa/ApiController":{"role":"symbol","title":"ApiController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ApiController"}],"abstract":[{"type":"text","text":"Contains general endpoints that user will request"}],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ApiController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ApiController"}],"url":"\/documentation\/yababa\/apicontroller"},"doc://com.yababaGmbH.yababa/documentation/Yababa/InAppMessages":{"role":"article","title":"InApp Messages","abstract":[{"type":"text","text":"Pop-up messages that appear within the app to provide users with information, promotions, and other relevant content."}],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/InAppMessages","kind":"article","type":"topic","url":"\/documentation\/yababa\/inappmessages"},"doc://com.yababaGmbH.yababa/documentation/Yababa/AnalyticsDocumentation":{"role":"article","title":"Analytics Manager","abstract":[{"type":"text","text":"Responsible for collecting events about user behavior and forwarding to third party analytics platforms."}],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AnalyticsDocumentation","kind":"article","type":"topic","url":"\/documentation\/yababa\/analyticsdocumentation"},"NetworkLayer.png":{"alt":"Network layer overview","type":"image","identifier":"NetworkLayer.png","variants":[{"url":"\/images\/NetworkLayer@2x.png","traits":["2x","light"]}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/topicSections","value":null},{"op":"replace","path":"\/seeAlsoSections","value":[{"title":"Others","identifiers":["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AnalyticsDocumentation","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/InAppMessages"],"generated":true}]}],"traits":[{"interfaceLanguage":"occ"}]}]}