{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PhoneNumberVerificationSceneViewController"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/yababa\/phonenumberverificationsceneviewcontroller"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/yababa\/phonenumberverificationsceneviewcontroller"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/MasterViewController"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.yababaGmbH.yababa\/objc(pl)NSCoding","doc:\/\/com.yababaGmbH.yababa\/objc(pl)NSExtensionRequestHandling","doc:\/\/com.yababaGmbH.yababa\/objc(pl)NSObject","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/PhoneNumberVerificationSceneViewControllerProtocol","doc:\/\/com.yababaGmbH.yababa\/12SkeletonView17AssociatedObjectsP","doc:\/\/com.yababaGmbH.yababa\/s7CVarArgP","doc:\/\/com.yababaGmbH.yababa\/s28CustomDebugStringConvertibleP","doc:\/\/com.yababaGmbH.yababa\/s23CustomStringConvertibleP","doc:\/\/com.yababaGmbH.yababa\/SQ","doc:\/\/com.yababaGmbH.yababa\/SH","doc:\/\/com.yababaGmbH.yababa\/s8SendableP","doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIActivityItemsConfigurationProviding","doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIAppearanceContainer","doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIContentContainer","doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIFocusEnvironment","doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIPasteConfigurationSupporting","doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIResponderStandardEditActions","doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIStateRestoring","doc:\/\/com.yababaGmbH.yababa\/objc(pl)UITraitEnvironment","doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIUserActivityRestoring"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/PhoneNumberVerificationSceneViewController","interfaceLanguage":"swift"},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/PhoneNumberVerificationSceneViewController\/init(coder:)","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/PhoneNumberVerificationSceneViewController\/init(phoneNumber:delegate:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/PhoneNumberVerificationSceneViewController\/codeLabel","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/PhoneNumberVerificationSceneViewController\/enterYourFourDigitCodeLabel","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/PhoneNumberVerificationSceneViewController\/interactor","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/PhoneNumberVerificationSceneViewController\/nextBtn","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/PhoneNumberVerificationSceneViewController\/otpField","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/PhoneNumberVerificationSceneViewController\/phoneNumberLabel","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/PhoneNumberVerificationSceneViewController\/resendBtn","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/PhoneNumberVerificationSceneViewController\/router","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/PhoneNumberVerificationSceneViewController\/smallSpinner"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/PhoneNumberVerificationSceneViewController\/continueAhead(withSuccess:)","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/PhoneNumberVerificationSceneViewController\/disableNextButton()","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/PhoneNumberVerificationSceneViewController\/enableNextButton()","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/PhoneNumberVerificationSceneViewController\/onNext()","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/PhoneNumberVerificationSceneViewController\/onResend()","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/PhoneNumberVerificationSceneViewController\/onTimerFires()","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/PhoneNumberVerificationSceneViewController\/stopTimer()","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/PhoneNumberVerificationSceneViewController\/viewDidLoad()"]},{"title":"Default Implementations","identifiers":["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/PhoneNumberVerificationSceneViewController\/PhoneNumberVerificationSceneViewControllerProtocol-Implementations"],"generated":true}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PhoneNumberVerificationSceneViewController"}],"title":"PhoneNumberVerificationSceneViewController","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@Yababa@objc(cs)PhoneNumberVerificationSceneViewController","modules":[{"name":"Yababa"}],"navigatorTitle":[{"kind":"identifier","text":"PhoneNumberVerificationSceneViewController"}]},"hierarchy":{"paths":[["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa"]]},"references":{"doc://com.yababaGmbH.yababa/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.yababaGmbH.yababa\/s28CustomDebugStringConvertibleP"},"doc://com.yababaGmbH.yababa/objc(pl)UIFocusEnvironment":{"type":"unresolvable","title":"UIKit.UIFocusEnvironment","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIFocusEnvironment"},"doc://com.yababaGmbH.yababa/objc(pl)UIPasteConfigurationSupporting":{"type":"unresolvable","title":"UIKit.UIPasteConfigurationSupporting","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIPasteConfigurationSupporting"},"doc://com.yababaGmbH.yababa/documentation/Yababa/PhoneNumberVerificationSceneViewController/otpField":{"role":"symbol","title":"otpField","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"otpField"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UITextField","preciseIdentifier":"c:objc(cs)UITextField"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/PhoneNumberVerificationSceneViewController\/otpField","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"otpField"}],"url":"\/documentation\/yababa\/phonenumberverificationsceneviewcontroller\/otpfield"},"doc://com.yababaGmbH.yababa/documentation/Yababa/PhoneNumberVerificationSceneViewController/PhoneNumberVerificationSceneViewControllerProtocol-Implementations":{"role":"collectionGroup","title":"PhoneNumberVerificationSceneViewControllerProtocol Implementations","abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/PhoneNumberVerificationSceneViewController\/PhoneNumberVerificationSceneViewControllerProtocol-Implementations","kind":"article","type":"topic","url":"\/documentation\/yababa\/phonenumberverificationsceneviewcontroller\/phonenumberverificationsceneviewcontrollerprotocol-implementations"},"doc://com.yababaGmbH.yababa/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.yababaGmbH.yababa\/SQ"},"doc://com.yababaGmbH.yababa/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/com.yababaGmbH.yababa\/s8SendableP"},"doc://com.yababaGmbH.yababa/documentation/Yababa/PhoneNumberVerificationSceneViewController/disableNextButton()":{"role":"symbol","title":"disableNextButton()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"disableNextButton"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/PhoneNumberVerificationSceneViewController\/disableNextButton()","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/phonenumberverificationsceneviewcontroller\/disablenextbutton()"},"doc://com.yababaGmbH.yababa/documentation/Yababa/PhoneNumberVerificationSceneViewController/enableNextButton()":{"role":"symbol","title":"enableNextButton()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"enableNextButton"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/PhoneNumberVerificationSceneViewController\/enableNextButton()","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/phonenumberverificationsceneviewcontroller\/enablenextbutton()"},"doc://com.yababaGmbH.yababa/documentation/Yababa/PhoneNumberVerificationSceneViewController/enterYourFourDigitCodeLabel":{"role":"symbol","title":"enterYourFourDigitCodeLabel","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"enterYourFourDigitCodeLabel"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UILabel","preciseIdentifier":"c:objc(cs)UILabel"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/PhoneNumberVerificationSceneViewController\/enterYourFourDigitCodeLabel","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"enterYourFourDigitCodeLabel"}],"url":"\/documentation\/yababa\/phonenumberverificationsceneviewcontroller\/enteryourfourdigitcodelabel"},"doc://com.yababaGmbH.yababa/12SkeletonView17AssociatedObjectsP":{"type":"unresolvable","title":"SkeletonView.AssociatedObjects","identifier":"doc:\/\/com.yababaGmbH.yababa\/12SkeletonView17AssociatedObjectsP"},"doc://com.yababaGmbH.yababa/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)NSObject"},"doc://com.yababaGmbH.yababa/objc(pl)UIActivityItemsConfigurationProviding":{"type":"unresolvable","title":"UIKit.UIActivityItemsConfigurationProviding","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIActivityItemsConfigurationProviding"},"doc://com.yababaGmbH.yababa/objc(pl)UIAppearanceContainer":{"type":"unresolvable","title":"UIKit.UIAppearanceContainer","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIAppearanceContainer"},"doc://com.yababaGmbH.yababa/documentation/Yababa/PhoneNumberVerificationSceneViewController/interactor":{"role":"symbol","title":"interactor","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"interactor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"PhoneNumberVerificationSceneInteractorProtocol","preciseIdentifier":"s:6Yababa46PhoneNumberVerificationSceneInteractorProtocolP"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/PhoneNumberVerificationSceneViewController\/interactor","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/phonenumberverificationsceneviewcontroller\/interactor"},"doc://com.yababaGmbH.yababa/objc(pl)NSCoding":{"type":"unresolvable","title":"Foundation.NSCoding","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)NSCoding"},"doc://com.yababaGmbH.yababa/objc(pl)UIUserActivityRestoring":{"type":"unresolvable","title":"UIKit.UIUserActivityRestoring","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIUserActivityRestoring"},"doc://com.yababaGmbH.yababa/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.yababaGmbH.yababa\/s7CVarArgP"},"doc://com.yababaGmbH.yababa/documentation/Yababa/PhoneNumberVerificationSceneViewController":{"role":"symbol","title":"PhoneNumberVerificationSceneViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PhoneNumberVerificationSceneViewController"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/PhoneNumberVerificationSceneViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PhoneNumberVerificationSceneViewController"}],"url":"\/documentation\/yababa\/phonenumberverificationsceneviewcontroller"},"doc://com.yababaGmbH.yababa/documentation/Yababa":{"role":"collection","title":"Yababa","abstract":[{"type":"text","text":"Getting Started"}],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa","kind":"symbol","type":"topic","url":"\/documentation\/yababa"},"doc://com.yababaGmbH.yababa/documentation/Yababa/PhoneNumberVerificationSceneViewController/smallSpinner":{"role":"symbol","title":"smallSpinner","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"smallSpinner"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIActivityIndicatorView","preciseIdentifier":"c:objc(cs)UIActivityIndicatorView"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/PhoneNumberVerificationSceneViewController\/smallSpinner","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"smallSpinner"}],"url":"\/documentation\/yababa\/phonenumberverificationsceneviewcontroller\/smallspinner"},"doc://com.yababaGmbH.yababa/documentation/Yababa/PhoneNumberVerificationSceneViewController/resendBtn":{"role":"symbol","title":"resendBtn","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"resendBtn"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIButton","preciseIdentifier":"c:objc(cs)UIButton"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/PhoneNumberVerificationSceneViewController\/resendBtn","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"resendBtn"}],"url":"\/documentation\/yababa\/phonenumberverificationsceneviewcontroller\/resendbtn"},"doc://com.yababaGmbH.yababa/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.yababaGmbH.yababa\/SH"},"doc://com.yababaGmbH.yababa/objc(pl)NSExtensionRequestHandling":{"type":"unresolvable","title":"Foundation.NSExtensionRequestHandling","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)NSExtensionRequestHandling"},"doc://com.yababaGmbH.yababa/documentation/Yababa/PhoneNumberVerificationSceneViewController/onNext()":{"role":"symbol","title":"onNext()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onNext"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/PhoneNumberVerificationSceneViewController\/onNext()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"onNext"}],"url":"\/documentation\/yababa\/phonenumberverificationsceneviewcontroller\/onnext()"},"doc://com.yababaGmbH.yababa/documentation/Yababa/PhoneNumberVerificationSceneViewController/onResend()":{"role":"symbol","title":"onResend()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onResend"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/PhoneNumberVerificationSceneViewController\/onResend()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"onResend"}],"url":"\/documentation\/yababa\/phonenumberverificationsceneviewcontroller\/onresend()"},"doc://com.yababaGmbH.yababa/documentation/Yababa/PhoneNumberVerificationSceneViewController/init(coder:)":{"role":"symbol","title":"init(coder:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"coder"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSCoder","preciseIdentifier":"c:objc(cs)NSCoder"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/PhoneNumberVerificationSceneViewController\/init(coder:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithCoder:"}],"url":"\/documentation\/yababa\/phonenumberverificationsceneviewcontroller\/init(coder:)"},"doc://com.yababaGmbH.yababa/documentation/Yababa/PhoneNumberVerificationSceneViewController/continueAhead(withSuccess:)":{"role":"symbol","title":"continueAhead(withSuccess:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"continueAhead"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withSuccess"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/PhoneNumberVerificationSceneViewController\/continueAhead(withSuccess:)","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/phonenumberverificationsceneviewcontroller\/continueahead(withsuccess:)"},"doc://com.yababaGmbH.yababa/documentation/Yababa/PhoneNumberVerificationSceneViewControllerProtocol":{"role":"symbol","title":"PhoneNumberVerificationSceneViewControllerProtocol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"PhoneNumberVerificationSceneViewControllerProtocol"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/PhoneNumberVerificationSceneViewControllerProtocol","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PhoneNumberVerificationSceneViewControllerProtocol"}],"url":"\/documentation\/yababa\/phonenumberverificationsceneviewcontrollerprotocol"},"doc://com.yababaGmbH.yababa/documentation/Yababa/PhoneNumberVerificationSceneViewController/viewDidLoad()":{"role":"symbol","title":"viewDidLoad()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"viewDidLoad"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/PhoneNumberVerificationSceneViewController\/viewDidLoad()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"viewDidLoad"}],"url":"\/documentation\/yababa\/phonenumberverificationsceneviewcontroller\/viewdidload()"},"doc://com.yababaGmbH.yababa/documentation/Yababa/PhoneNumberVerificationSceneViewController/router":{"role":"symbol","title":"router","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"router"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"PhoneNumberVerificationSceneRouterProtocol","preciseIdentifier":"s:6Yababa42PhoneNumberVerificationSceneRouterProtocolP"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/PhoneNumberVerificationSceneViewController\/router","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/phonenumberverificationsceneviewcontroller\/router"},"doc://com.yababaGmbH.yababa/documentation/Yababa/PhoneNumberVerificationSceneViewController/codeLabel":{"role":"symbol","title":"codeLabel","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"codeLabel"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UILabel","preciseIdentifier":"c:objc(cs)UILabel"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/PhoneNumberVerificationSceneViewController\/codeLabel","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"codeLabel"}],"url":"\/documentation\/yababa\/phonenumberverificationsceneviewcontroller\/codelabel"},"doc://com.yababaGmbH.yababa/documentation/Yababa/PhoneNumberVerificationSceneViewController/onTimerFires()":{"role":"symbol","title":"onTimerFires()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onTimerFires"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/PhoneNumberVerificationSceneViewController\/onTimerFires()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"onTimerFires"}],"url":"\/documentation\/yababa\/phonenumberverificationsceneviewcontroller\/ontimerfires()"},"doc://com.yababaGmbH.yababa/objc(pl)UIStateRestoring":{"type":"unresolvable","title":"UIKit.UIStateRestoring","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIStateRestoring"},"doc://com.yababaGmbH.yababa/objc(pl)UIResponderStandardEditActions":{"type":"unresolvable","title":"UIKit.UIResponderStandardEditActions","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIResponderStandardEditActions"},"doc://com.yababaGmbH.yababa/documentation/Yababa/MasterViewController":{"role":"symbol","title":"MasterViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MasterViewController"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/MasterViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MasterViewController"}],"url":"\/documentation\/yababa\/masterviewcontroller"},"doc://com.yababaGmbH.yababa/documentation/Yababa/PhoneNumberVerificationSceneViewController/stopTimer()":{"role":"symbol","title":"stopTimer()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"stopTimer"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/PhoneNumberVerificationSceneViewController\/stopTimer()","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/phonenumberverificationsceneviewcontroller\/stoptimer()"},"doc://com.yababaGmbH.yababa/objc(pl)UITraitEnvironment":{"type":"unresolvable","title":"UIKit.UITraitEnvironment","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)UITraitEnvironment"},"doc://com.yababaGmbH.yababa/objc(pl)UIContentContainer":{"type":"unresolvable","title":"UIKit.UIContentContainer","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIContentContainer"},"doc://com.yababaGmbH.yababa/documentation/Yababa/PhoneNumberVerificationSceneViewController/phoneNumberLabel":{"role":"symbol","title":"phoneNumberLabel","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"phoneNumberLabel"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UILabel","preciseIdentifier":"c:objc(cs)UILabel"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/PhoneNumberVerificationSceneViewController\/phoneNumberLabel","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"phoneNumberLabel"}],"url":"\/documentation\/yababa\/phonenumberverificationsceneviewcontroller\/phonenumberlabel"},"doc://com.yababaGmbH.yababa/documentation/Yababa/PhoneNumberVerificationSceneViewController/init(phoneNumber:delegate:)":{"role":"symbol","title":"init(phoneNumber:delegate:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"phoneNumber"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"delegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CompleteProfileVCDelegate","preciseIdentifier":"s:6Yababa25CompleteProfileVCDelegateP"},{"kind":"text","text":"?)"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/PhoneNumberVerificationSceneViewController\/init(phoneNumber:delegate:)","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/phonenumberverificationsceneviewcontroller\/init(phonenumber:delegate:)"},"doc://com.yababaGmbH.yababa/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.yababaGmbH.yababa\/s23CustomStringConvertibleP"},"doc://com.yababaGmbH.yababa/documentation/Yababa/PhoneNumberVerificationSceneViewController/nextBtn":{"role":"symbol","title":"nextBtn","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"nextBtn"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIButton","preciseIdentifier":"c:objc(cs)UIButton"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/PhoneNumberVerificationSceneViewController\/nextBtn","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"nextBtn"}],"url":"\/documentation\/yababa\/phonenumberverificationsceneviewcontroller\/nextbtn"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"PhoneNumberVerificationSceneViewController"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"PhoneNumberVerificationSceneViewController"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"PhoneNumberVerificationSceneViewController"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/PhoneNumberVerificationSceneViewController\/codeLabel","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/PhoneNumberVerificationSceneViewController\/enterYourFourDigitCodeLabel","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/PhoneNumberVerificationSceneViewController\/nextBtn","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/PhoneNumberVerificationSceneViewController\/otpField","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/PhoneNumberVerificationSceneViewController\/phoneNumberLabel","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/PhoneNumberVerificationSceneViewController\/resendBtn","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/PhoneNumberVerificationSceneViewController\/smallSpinner"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/PhoneNumberVerificationSceneViewController\/init(coder:)","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/PhoneNumberVerificationSceneViewController\/onNext()","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/PhoneNumberVerificationSceneViewController\/onResend()","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/PhoneNumberVerificationSceneViewController\/onTimerFires()","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/PhoneNumberVerificationSceneViewController\/viewDidLoad()"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/MasterViewController"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"PhoneNumberVerificationSceneViewController"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/MasterViewController","preciseIdentifier":"c:@M@Yababa@objc(cs)MasterViewController","text":"MasterViewController"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1PhoneNumberVerificationSceneViewController~1otpField\/title","value":"otpField"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1PhoneNumberVerificationSceneViewController~1otpField\/fragments","value":[{"kind":"identifier","text":"otpField"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1PhoneNumberVerificationSceneViewController~1enterYourFourDigitCodeLabel\/title","value":"enterYourFourDigitCodeLabel"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1PhoneNumberVerificationSceneViewController~1enterYourFourDigitCodeLabel\/fragments","value":[{"kind":"identifier","text":"enterYourFourDigitCodeLabel"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1PhoneNumberVerificationSceneViewController\/title","value":"PhoneNumberVerificationSceneViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1PhoneNumberVerificationSceneViewController\/fragments","value":[{"kind":"identifier","text":"PhoneNumberVerificationSceneViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1PhoneNumberVerificationSceneViewController~1smallSpinner\/title","value":"smallSpinner"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1PhoneNumberVerificationSceneViewController~1smallSpinner\/fragments","value":[{"kind":"identifier","text":"smallSpinner"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1PhoneNumberVerificationSceneViewController~1resendBtn\/title","value":"resendBtn"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1PhoneNumberVerificationSceneViewController~1resendBtn\/fragments","value":[{"kind":"identifier","text":"resendBtn"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1PhoneNumberVerificationSceneViewController~1onNext()\/title","value":"onNext"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1PhoneNumberVerificationSceneViewController~1onNext()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onNext"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1PhoneNumberVerificationSceneViewController~1onResend()\/title","value":"onResend"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1PhoneNumberVerificationSceneViewController~1onResend()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onResend"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1PhoneNumberVerificationSceneViewController~1init(coder:)\/title","value":"initWithCoder:"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1PhoneNumberVerificationSceneViewController~1init(coder:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithCoder:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1PhoneNumberVerificationSceneViewController~1viewDidLoad()\/title","value":"viewDidLoad"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1PhoneNumberVerificationSceneViewController~1viewDidLoad()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"viewDidLoad"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1PhoneNumberVerificationSceneViewController~1codeLabel\/title","value":"codeLabel"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1PhoneNumberVerificationSceneViewController~1codeLabel\/fragments","value":[{"kind":"identifier","text":"codeLabel"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1PhoneNumberVerificationSceneViewController~1onTimerFires()\/title","value":"onTimerFires"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1PhoneNumberVerificationSceneViewController~1onTimerFires()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onTimerFires"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1MasterViewController\/title","value":"MasterViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1MasterViewController\/fragments","value":[{"kind":"identifier","text":"MasterViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1PhoneNumberVerificationSceneViewController~1phoneNumberLabel\/title","value":"phoneNumberLabel"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1PhoneNumberVerificationSceneViewController~1phoneNumberLabel\/fragments","value":[{"kind":"identifier","text":"phoneNumberLabel"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1PhoneNumberVerificationSceneViewController~1nextBtn\/title","value":"nextBtn"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1PhoneNumberVerificationSceneViewController~1nextBtn\/fragments","value":[{"kind":"identifier","text":"nextBtn"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}