{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ProductDetailsSceneViewController"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/yababa\/productdetailssceneviewcontroller"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/yababa\/productdetailssceneviewcontroller"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/MasterViewController"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.yababaGmbH.yababa\/objc(pl)NSCoding","doc:\/\/com.yababaGmbH.yababa\/objc(pl)NSExtensionRequestHandling","doc:\/\/com.yababaGmbH.yababa\/objc(pl)NSObject","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ProductDetailsSceneViewControllerProtocol","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ProductsSimpleListingDelegate","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/QuantityInCartDelegate","doc:\/\/com.yababaGmbH.yababa\/12SkeletonView17AssociatedObjectsP","doc:\/\/com.yababaGmbH.yababa\/s7CVarArgP","doc:\/\/com.yababaGmbH.yababa\/s28CustomDebugStringConvertibleP","doc:\/\/com.yababaGmbH.yababa\/s23CustomStringConvertibleP","doc:\/\/com.yababaGmbH.yababa\/SQ","doc:\/\/com.yababaGmbH.yababa\/SH","doc:\/\/com.yababaGmbH.yababa\/s8SendableP","doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIActivityItemsConfigurationProviding","doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIAppearanceContainer","doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIContentContainer","doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIFocusEnvironment","doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIPasteConfigurationSupporting","doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIResponderStandardEditActions","doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIStateRestoring","doc:\/\/com.yababaGmbH.yababa\/objc(pl)UITraitEnvironment","doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIUserActivityRestoring"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ProductDetailsSceneViewController","interfaceLanguage":"swift"},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ProductDetailsSceneViewController\/init(coder:)","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ProductDetailsSceneViewController\/init(product:withCustomBackButton:positionInSender:alreadyBoughtAtPrice:delegate:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ProductDetailsSceneViewController\/addItemBtn","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ProductDetailsSceneViewController\/collectionView","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ProductDetailsSceneViewController\/descriptionLabel","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ProductDetailsSceneViewController\/discountLabel","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ProductDetailsSceneViewController\/discountLabelContainer","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ProductDetailsSceneViewController\/discountLabelContainerTopConstraint","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ProductDetailsSceneViewController\/imagesViewer","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ProductDetailsSceneViewController\/interactor","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ProductDetailsSceneViewController\/isDepositView","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ProductDetailsSceneViewController\/item1Label","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ProductDetailsSceneViewController\/item2Label","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ProductDetailsSceneViewController\/item3Label","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ProductDetailsSceneViewController\/pageIndicator","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ProductDetailsSceneViewController\/pricePerUnitLabel","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ProductDetailsSceneViewController\/productDetailLabel","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ProductDetailsSceneViewController\/productDetailStackView","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ProductDetailsSceneViewController\/productVATLabel","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ProductDetailsSceneViewController\/quantityInCartViewContainer","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ProductDetailsSceneViewController\/router","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ProductDetailsSceneViewController\/scrollView","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ProductDetailsSceneViewController\/strikeThroughPriceLabel","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ProductDetailsSceneViewController\/youMightAlsoLike"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ProductDetailsSceneViewController\/changeQuantityInCartBackground()","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ProductDetailsSceneViewController\/checkIfItIsADepositProduct()","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ProductDetailsSceneViewController\/onAddItem(_:)","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ProductDetailsSceneViewController\/onBack()","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ProductDetailsSceneViewController\/onUserTappedAdd()","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ProductDetailsSceneViewController\/onUserTappedRemove()","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ProductDetailsSceneViewController\/setIdentifiers()","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ProductDetailsSceneViewController\/viewDidLoad()"]}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ProductDetailsSceneViewController"}],"title":"ProductDetailsSceneViewController","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@Yababa@objc(cs)ProductDetailsSceneViewController","modules":[{"name":"Yababa"}],"navigatorTitle":[{"kind":"identifier","text":"ProductDetailsSceneViewController"}]},"hierarchy":{"paths":[["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa"]]},"references":{"doc://com.yababaGmbH.yababa/documentation/Yababa/ProductDetailsSceneViewController/youMightAlsoLike":{"role":"symbol","title":"youMightAlsoLike","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"youMightAlsoLike"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UILabel","preciseIdentifier":"c:objc(cs)UILabel"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ProductDetailsSceneViewController\/youMightAlsoLike","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"youMightAlsoLike"}],"url":"\/documentation\/yababa\/productdetailssceneviewcontroller\/youmightalsolike"},"doc://com.yababaGmbH.yababa/12SkeletonView17AssociatedObjectsP":{"type":"unresolvable","title":"SkeletonView.AssociatedObjects","identifier":"doc:\/\/com.yababaGmbH.yababa\/12SkeletonView17AssociatedObjectsP"},"doc://com.yababaGmbH.yababa/documentation/Yababa/ProductDetailsSceneViewController/item3Label":{"role":"symbol","title":"item3Label","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"item3Label"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UILabel","preciseIdentifier":"c:objc(cs)UILabel"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ProductDetailsSceneViewController\/item3Label","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"item3Label"}],"url":"\/documentation\/yababa\/productdetailssceneviewcontroller\/item3label"},"doc://com.yababaGmbH.yababa/documentation/Yababa/ProductDetailsSceneViewController/quantityInCartViewContainer":{"role":"symbol","title":"quantityInCartViewContainer","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"quantityInCartViewContainer"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ProductDetailsSceneViewController\/quantityInCartViewContainer","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"quantityInCartViewContainer"}],"url":"\/documentation\/yababa\/productdetailssceneviewcontroller\/quantityincartviewcontainer"},"doc://com.yababaGmbH.yababa/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/com.yababaGmbH.yababa\/s8SendableP"},"doc://com.yababaGmbH.yababa/documentation/Yababa/ProductDetailsSceneViewController/discountLabelContainerTopConstraint":{"role":"symbol","title":"discountLabelContainerTopConstraint","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"discountLabelContainerTopConstraint"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSLayoutConstraint","preciseIdentifier":"c:objc(cs)NSLayoutConstraint"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ProductDetailsSceneViewController\/discountLabelContainerTopConstraint","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"discountLabelContainerTopConstraint"}],"url":"\/documentation\/yababa\/productdetailssceneviewcontroller\/discountlabelcontainertopconstraint"},"doc://com.yababaGmbH.yababa/documentation/Yababa/ProductDetailsSceneViewController/pricePerUnitLabel":{"role":"symbol","title":"pricePerUnitLabel","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"pricePerUnitLabel"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UILabel","preciseIdentifier":"c:objc(cs)UILabel"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ProductDetailsSceneViewController\/pricePerUnitLabel","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"pricePerUnitLabel"}],"url":"\/documentation\/yababa\/productdetailssceneviewcontroller\/priceperunitlabel"},"doc://com.yababaGmbH.yababa/objc(pl)UIResponderStandardEditActions":{"type":"unresolvable","title":"UIKit.UIResponderStandardEditActions","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIResponderStandardEditActions"},"doc://com.yababaGmbH.yababa/documentation/Yababa/ProductDetailsSceneViewController/init(product:withCustomBackButton:positionInSender:alreadyBoughtAtPrice:delegate:)":{"role":"symbol","title":"init(product:withCustomBackButton:positionInSender:alreadyBoughtAtPrice:delegate:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"product"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Product","preciseIdentifier":"s:6Yababa7ProductC"},{"kind":"text","text":", "},{"kind":"externalParam","text":"withCustomBackButton"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"positionInSender"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"alreadyBoughtAtPrice"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"delegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ProductViewSenderDelegate","preciseIdentifier":"s:6Yababa25ProductViewSenderDelegateP"},{"kind":"text","text":"?)"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ProductDetailsSceneViewController\/init(product:withCustomBackButton:positionInSender:alreadyBoughtAtPrice:delegate:)","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/productdetailssceneviewcontroller\/init(product:withcustombackbutton:positioninsender:alreadyboughtatprice:delegate:)"},"doc://com.yababaGmbH.yababa/documentation/Yababa/ProductDetailsSceneViewController/interactor":{"role":"symbol","title":"interactor","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"interactor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ProductDetailsSceneInteractorProtocol","preciseIdentifier":"s:6Yababa37ProductDetailsSceneInteractorProtocolP"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ProductDetailsSceneViewController\/interactor","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/productdetailssceneviewcontroller\/interactor"},"doc://com.yababaGmbH.yababa/documentation/Yababa/ProductDetailsSceneViewController/router":{"role":"symbol","title":"router","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"router"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ProductDetailsSceneRouterProtocol","preciseIdentifier":"s:6Yababa33ProductDetailsSceneRouterProtocolP"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ProductDetailsSceneViewController\/router","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/productdetailssceneviewcontroller\/router"},"doc://com.yababaGmbH.yababa/objc(pl)UIContentContainer":{"type":"unresolvable","title":"UIKit.UIContentContainer","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIContentContainer"},"doc://com.yababaGmbH.yababa/documentation/Yababa/ProductDetailsSceneViewController/productDetailStackView":{"role":"symbol","title":"productDetailStackView","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"productDetailStackView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIStackView","preciseIdentifier":"c:objc(cs)UIStackView"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ProductDetailsSceneViewController\/productDetailStackView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"productDetailStackView"}],"url":"\/documentation\/yababa\/productdetailssceneviewcontroller\/productdetailstackview"},"doc://com.yababaGmbH.yababa/objc(pl)NSCoding":{"type":"unresolvable","title":"Foundation.NSCoding","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)NSCoding"},"doc://com.yababaGmbH.yababa/documentation/Yababa/ProductDetailsSceneViewController/collectionView":{"role":"symbol","title":"collectionView","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"collectionView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UICollectionView","preciseIdentifier":"c:objc(cs)UICollectionView"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ProductDetailsSceneViewController\/collectionView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"collectionView"}],"url":"\/documentation\/yababa\/productdetailssceneviewcontroller\/collectionview"},"doc://com.yababaGmbH.yababa/documentation/Yababa/ProductDetailsSceneViewController/isDepositView":{"role":"symbol","title":"isDepositView","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isDepositView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ProductDetailsSceneViewController\/isDepositView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"isDepositView"}],"url":"\/documentation\/yababa\/productdetailssceneviewcontroller\/isdepositview"},"doc://com.yababaGmbH.yababa/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.yababaGmbH.yababa\/SH"},"doc://com.yababaGmbH.yababa/documentation/Yababa/ProductDetailsSceneViewController/onBack()":{"role":"symbol","title":"onBack()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onBack"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ProductDetailsSceneViewController\/onBack()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"onBack"}],"url":"\/documentation\/yababa\/productdetailssceneviewcontroller\/onback()"},"doc://com.yababaGmbH.yababa/documentation/Yababa/ProductDetailsSceneViewController/item2Label":{"role":"symbol","title":"item2Label","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"item2Label"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UILabel","preciseIdentifier":"c:objc(cs)UILabel"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ProductDetailsSceneViewController\/item2Label","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"item2Label"}],"url":"\/documentation\/yababa\/productdetailssceneviewcontroller\/item2label"},"doc://com.yababaGmbH.yababa/documentation/Yababa/ProductDetailsSceneViewController/pageIndicator":{"role":"symbol","title":"pageIndicator","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"pageIndicator"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIPageControl","preciseIdentifier":"c:objc(cs)UIPageControl"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ProductDetailsSceneViewController\/pageIndicator","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"pageIndicator"}],"url":"\/documentation\/yababa\/productdetailssceneviewcontroller\/pageindicator"},"doc://com.yababaGmbH.yababa/documentation/Yababa/ProductDetailsSceneViewController/setIdentifiers()":{"role":"symbol","title":"setIdentifiers()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setIdentifiers"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ProductDetailsSceneViewController\/setIdentifiers()","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/productdetailssceneviewcontroller\/setidentifiers()"},"doc://com.yababaGmbH.yababa/documentation/Yababa/ProductDetailsSceneViewController/strikeThroughPriceLabel":{"role":"symbol","title":"strikeThroughPriceLabel","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"strikeThroughPriceLabel"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UILabel","preciseIdentifier":"c:objc(cs)UILabel"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ProductDetailsSceneViewController\/strikeThroughPriceLabel","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"strikeThroughPriceLabel"}],"url":"\/documentation\/yababa\/productdetailssceneviewcontroller\/strikethroughpricelabel"},"doc://com.yababaGmbH.yababa/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)NSObject"},"doc://com.yababaGmbH.yababa/documentation/Yababa/ProductDetailsSceneViewController/item1Label":{"role":"symbol","title":"item1Label","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"item1Label"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UILabel","preciseIdentifier":"c:objc(cs)UILabel"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ProductDetailsSceneViewController\/item1Label","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"item1Label"}],"url":"\/documentation\/yababa\/productdetailssceneviewcontroller\/item1label"},"doc://com.yababaGmbH.yababa/documentation/Yababa/ProductDetailsSceneViewController/discountLabelContainer":{"role":"symbol","title":"discountLabelContainer","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"discountLabelContainer"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ProductDetailsSceneViewController\/discountLabelContainer","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"discountLabelContainer"}],"url":"\/documentation\/yababa\/productdetailssceneviewcontroller\/discountlabelcontainer"},"doc://com.yababaGmbH.yababa/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.yababaGmbH.yababa\/s23CustomStringConvertibleP"},"doc://com.yababaGmbH.yababa/documentation/Yababa/ProductDetailsSceneViewController/productVATLabel":{"role":"symbol","title":"productVATLabel","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"productVATLabel"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UILabel","preciseIdentifier":"c:objc(cs)UILabel"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ProductDetailsSceneViewController\/productVATLabel","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"productVATLabel"}],"url":"\/documentation\/yababa\/productdetailssceneviewcontroller\/productvatlabel"},"doc://com.yababaGmbH.yababa/objc(pl)UIPasteConfigurationSupporting":{"type":"unresolvable","title":"UIKit.UIPasteConfigurationSupporting","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIPasteConfigurationSupporting"},"doc://com.yababaGmbH.yababa/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.yababaGmbH.yababa\/s28CustomDebugStringConvertibleP"},"doc://com.yababaGmbH.yababa/documentation/Yababa":{"role":"collection","title":"Yababa","abstract":[{"type":"text","text":"Getting Started"}],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa","kind":"symbol","type":"topic","url":"\/documentation\/yababa"},"doc://com.yababaGmbH.yababa/objc(pl)UIUserActivityRestoring":{"type":"unresolvable","title":"UIKit.UIUserActivityRestoring","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIUserActivityRestoring"},"doc://com.yababaGmbH.yababa/documentation/Yababa/ProductDetailsSceneViewController/checkIfItIsADepositProduct()":{"role":"symbol","title":"checkIfItIsADepositProduct()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"checkIfItIsADepositProduct"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ProductDetailsSceneViewController\/checkIfItIsADepositProduct()","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/productdetailssceneviewcontroller\/checkifitisadepositproduct()"},"doc://com.yababaGmbH.yababa/objc(pl)UIStateRestoring":{"type":"unresolvable","title":"UIKit.UIStateRestoring","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIStateRestoring"},"doc://com.yababaGmbH.yababa/documentation/Yababa/ProductDetailsSceneViewController/discountLabel":{"role":"symbol","title":"discountLabel","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"discountLabel"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UILabel","preciseIdentifier":"c:objc(cs)UILabel"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ProductDetailsSceneViewController\/discountLabel","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"discountLabel"}],"url":"\/documentation\/yababa\/productdetailssceneviewcontroller\/discountlabel"},"doc://com.yababaGmbH.yababa/documentation/Yababa/ProductDetailsSceneViewController/addItemBtn":{"role":"symbol","title":"addItemBtn","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"addItemBtn"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIButton","preciseIdentifier":"c:objc(cs)UIButton"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ProductDetailsSceneViewController\/addItemBtn","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"addItemBtn"}],"url":"\/documentation\/yababa\/productdetailssceneviewcontroller\/additembtn"},"doc://com.yababaGmbH.yababa/objc(pl)UITraitEnvironment":{"type":"unresolvable","title":"UIKit.UITraitEnvironment","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)UITraitEnvironment"},"doc://com.yababaGmbH.yababa/documentation/Yababa/ProductDetailsSceneViewController/onAddItem(_:)":{"role":"symbol","title":"onAddItem(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onAddItem"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UIButton","preciseIdentifier":"c:objc(cs)UIButton"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ProductDetailsSceneViewController\/onAddItem(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"onAddItem:"}],"url":"\/documentation\/yababa\/productdetailssceneviewcontroller\/onadditem(_:)"},"doc://com.yababaGmbH.yababa/documentation/Yababa/ProductsSimpleListingDelegate":{"role":"symbol","title":"ProductsSimpleListingDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"ProductsSimpleListingDelegate"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ProductsSimpleListingDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ProductsSimpleListingDelegate"}],"url":"\/documentation\/yababa\/productssimplelistingdelegate"},"doc://com.yababaGmbH.yababa/documentation/Yababa/ProductDetailsSceneViewController/viewDidLoad()":{"role":"symbol","title":"viewDidLoad()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"viewDidLoad"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ProductDetailsSceneViewController\/viewDidLoad()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"viewDidLoad"}],"url":"\/documentation\/yababa\/productdetailssceneviewcontroller\/viewdidload()"},"doc://com.yababaGmbH.yababa/documentation/Yababa/ProductDetailsSceneViewController/productDetailLabel":{"role":"symbol","title":"productDetailLabel","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"productDetailLabel"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UILabel","preciseIdentifier":"c:objc(cs)UILabel"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ProductDetailsSceneViewController\/productDetailLabel","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"productDetailLabel"}],"url":"\/documentation\/yababa\/productdetailssceneviewcontroller\/productdetaillabel"},"doc://com.yababaGmbH.yababa/documentation/Yababa/ProductDetailsSceneViewController/descriptionLabel":{"role":"symbol","title":"descriptionLabel","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"descriptionLabel"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UILabel","preciseIdentifier":"c:objc(cs)UILabel"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ProductDetailsSceneViewController\/descriptionLabel","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"descriptionLabel"}],"url":"\/documentation\/yababa\/productdetailssceneviewcontroller\/descriptionlabel"},"doc://com.yababaGmbH.yababa/documentation/Yababa/ProductDetailsSceneViewController/changeQuantityInCartBackground()":{"role":"symbol","title":"changeQuantityInCartBackground()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"changeQuantityInCartBackground"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ProductDetailsSceneViewController\/changeQuantityInCartBackground()","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/productdetailssceneviewcontroller\/changequantityincartbackground()"},"doc://com.yababaGmbH.yababa/documentation/Yababa/ProductDetailsSceneViewControllerProtocol":{"role":"symbol","title":"ProductDetailsSceneViewControllerProtocol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"ProductDetailsSceneViewControllerProtocol"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ProductDetailsSceneViewControllerProtocol","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ProductDetailsSceneViewControllerProtocol"}],"url":"\/documentation\/yababa\/productdetailssceneviewcontrollerprotocol"},"doc://com.yababaGmbH.yababa/documentation/Yababa/QuantityInCartDelegate":{"role":"symbol","title":"QuantityInCartDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"QuantityInCartDelegate"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/QuantityInCartDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"QuantityInCartDelegate"}],"url":"\/documentation\/yababa\/quantityincartdelegate"},"doc://com.yababaGmbH.yababa/documentation/Yababa/ProductDetailsSceneViewController/scrollView":{"role":"symbol","title":"scrollView","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"scrollView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIScrollView","preciseIdentifier":"c:objc(cs)UIScrollView"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ProductDetailsSceneViewController\/scrollView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"scrollView"}],"url":"\/documentation\/yababa\/productdetailssceneviewcontroller\/scrollview"},"doc://com.yababaGmbH.yababa/objc(pl)UIFocusEnvironment":{"type":"unresolvable","title":"UIKit.UIFocusEnvironment","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIFocusEnvironment"},"doc://com.yababaGmbH.yababa/documentation/Yababa/ProductDetailsSceneViewController/onUserTappedAdd()":{"role":"symbol","title":"onUserTappedAdd()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onUserTappedAdd"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ProductDetailsSceneViewController\/onUserTappedAdd()","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/productdetailssceneviewcontroller\/onusertappedadd()"},"doc://com.yababaGmbH.yababa/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.yababaGmbH.yababa\/SQ"},"doc://com.yababaGmbH.yababa/documentation/Yababa/ProductDetailsSceneViewController/onUserTappedRemove()":{"role":"symbol","title":"onUserTappedRemove()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onUserTappedRemove"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ProductDetailsSceneViewController\/onUserTappedRemove()","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/productdetailssceneviewcontroller\/onusertappedremove()"},"doc://com.yababaGmbH.yababa/documentation/Yababa/MasterViewController":{"role":"symbol","title":"MasterViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MasterViewController"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/MasterViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MasterViewController"}],"url":"\/documentation\/yababa\/masterviewcontroller"},"doc://com.yababaGmbH.yababa/documentation/Yababa/ProductDetailsSceneViewController":{"role":"symbol","title":"ProductDetailsSceneViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ProductDetailsSceneViewController"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ProductDetailsSceneViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ProductDetailsSceneViewController"}],"url":"\/documentation\/yababa\/productdetailssceneviewcontroller"},"doc://com.yababaGmbH.yababa/objc(pl)UIActivityItemsConfigurationProviding":{"type":"unresolvable","title":"UIKit.UIActivityItemsConfigurationProviding","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIActivityItemsConfigurationProviding"},"doc://com.yababaGmbH.yababa/documentation/Yababa/ProductDetailsSceneViewController/init(coder:)":{"role":"symbol","title":"init(coder:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"coder"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSCoder","preciseIdentifier":"c:objc(cs)NSCoder"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ProductDetailsSceneViewController\/init(coder:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithCoder:"}],"url":"\/documentation\/yababa\/productdetailssceneviewcontroller\/init(coder:)"},"doc://com.yababaGmbH.yababa/objc(pl)NSExtensionRequestHandling":{"type":"unresolvable","title":"Foundation.NSExtensionRequestHandling","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)NSExtensionRequestHandling"},"doc://com.yababaGmbH.yababa/documentation/Yababa/ProductDetailsSceneViewController/imagesViewer":{"role":"symbol","title":"imagesViewer","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"imagesViewer"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ImageSlideshow","preciseIdentifier":"c:@M@ImageSlideshow@objc(cs)ImageSlideshow"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ProductDetailsSceneViewController\/imagesViewer","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"imagesViewer"}],"url":"\/documentation\/yababa\/productdetailssceneviewcontroller\/imagesviewer"},"doc://com.yababaGmbH.yababa/objc(pl)UIAppearanceContainer":{"type":"unresolvable","title":"UIKit.UIAppearanceContainer","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIAppearanceContainer"},"doc://com.yababaGmbH.yababa/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.yababaGmbH.yababa\/s7CVarArgP"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"ProductDetailsSceneViewController"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"ProductDetailsSceneViewController"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"ProductDetailsSceneViewController"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ProductDetailsSceneViewController\/addItemBtn","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ProductDetailsSceneViewController\/collectionView","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ProductDetailsSceneViewController\/descriptionLabel","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ProductDetailsSceneViewController\/discountLabel","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ProductDetailsSceneViewController\/discountLabelContainer","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ProductDetailsSceneViewController\/discountLabelContainerTopConstraint","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ProductDetailsSceneViewController\/imagesViewer","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ProductDetailsSceneViewController\/isDepositView","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ProductDetailsSceneViewController\/item1Label","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ProductDetailsSceneViewController\/item2Label","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ProductDetailsSceneViewController\/item3Label","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ProductDetailsSceneViewController\/pageIndicator","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ProductDetailsSceneViewController\/pricePerUnitLabel","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ProductDetailsSceneViewController\/productDetailLabel","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ProductDetailsSceneViewController\/productDetailStackView","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ProductDetailsSceneViewController\/productVATLabel","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ProductDetailsSceneViewController\/quantityInCartViewContainer","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ProductDetailsSceneViewController\/scrollView","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ProductDetailsSceneViewController\/strikeThroughPriceLabel","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ProductDetailsSceneViewController\/youMightAlsoLike"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ProductDetailsSceneViewController\/init(coder:)","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ProductDetailsSceneViewController\/onAddItem(_:)","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ProductDetailsSceneViewController\/onBack()","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ProductDetailsSceneViewController\/viewDidLoad()"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/MasterViewController"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"ProductDetailsSceneViewController"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/MasterViewController","preciseIdentifier":"c:@M@Yababa@objc(cs)MasterViewController","text":"MasterViewController"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1ProductDetailsSceneViewController~1youMightAlsoLike\/title","value":"youMightAlsoLike"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1ProductDetailsSceneViewController~1youMightAlsoLike\/fragments","value":[{"kind":"identifier","text":"youMightAlsoLike"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1ProductDetailsSceneViewController~1item3Label\/title","value":"item3Label"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1ProductDetailsSceneViewController~1item3Label\/fragments","value":[{"kind":"identifier","text":"item3Label"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1ProductDetailsSceneViewController~1quantityInCartViewContainer\/title","value":"quantityInCartViewContainer"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1ProductDetailsSceneViewController~1quantityInCartViewContainer\/fragments","value":[{"kind":"identifier","text":"quantityInCartViewContainer"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1ProductDetailsSceneViewController~1discountLabelContainerTopConstraint\/title","value":"discountLabelContainerTopConstraint"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1ProductDetailsSceneViewController~1discountLabelContainerTopConstraint\/fragments","value":[{"kind":"identifier","text":"discountLabelContainerTopConstraint"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1ProductDetailsSceneViewController~1pricePerUnitLabel\/title","value":"pricePerUnitLabel"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1ProductDetailsSceneViewController~1pricePerUnitLabel\/fragments","value":[{"kind":"identifier","text":"pricePerUnitLabel"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1ProductDetailsSceneViewController~1productDetailStackView\/title","value":"productDetailStackView"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1ProductDetailsSceneViewController~1productDetailStackView\/fragments","value":[{"kind":"identifier","text":"productDetailStackView"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1ProductDetailsSceneViewController~1collectionView\/title","value":"collectionView"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1ProductDetailsSceneViewController~1collectionView\/fragments","value":[{"kind":"identifier","text":"collectionView"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1ProductDetailsSceneViewController~1isDepositView\/title","value":"isDepositView"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1ProductDetailsSceneViewController~1isDepositView\/fragments","value":[{"kind":"identifier","text":"isDepositView"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1ProductDetailsSceneViewController~1onBack()\/title","value":"onBack"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1ProductDetailsSceneViewController~1onBack()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onBack"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1ProductDetailsSceneViewController~1item2Label\/title","value":"item2Label"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1ProductDetailsSceneViewController~1item2Label\/fragments","value":[{"kind":"identifier","text":"item2Label"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1ProductDetailsSceneViewController~1pageIndicator\/title","value":"pageIndicator"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1ProductDetailsSceneViewController~1pageIndicator\/fragments","value":[{"kind":"identifier","text":"pageIndicator"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1ProductDetailsSceneViewController~1strikeThroughPriceLabel\/title","value":"strikeThroughPriceLabel"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1ProductDetailsSceneViewController~1strikeThroughPriceLabel\/fragments","value":[{"kind":"identifier","text":"strikeThroughPriceLabel"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1ProductDetailsSceneViewController~1item1Label\/title","value":"item1Label"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1ProductDetailsSceneViewController~1item1Label\/fragments","value":[{"kind":"identifier","text":"item1Label"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1ProductDetailsSceneViewController~1discountLabelContainer\/title","value":"discountLabelContainer"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1ProductDetailsSceneViewController~1discountLabelContainer\/fragments","value":[{"kind":"identifier","text":"discountLabelContainer"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1ProductDetailsSceneViewController~1productVATLabel\/title","value":"productVATLabel"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1ProductDetailsSceneViewController~1productVATLabel\/fragments","value":[{"kind":"identifier","text":"productVATLabel"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1ProductDetailsSceneViewController~1discountLabel\/title","value":"discountLabel"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1ProductDetailsSceneViewController~1discountLabel\/fragments","value":[{"kind":"identifier","text":"discountLabel"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1ProductDetailsSceneViewController~1addItemBtn\/title","value":"addItemBtn"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1ProductDetailsSceneViewController~1addItemBtn\/fragments","value":[{"kind":"identifier","text":"addItemBtn"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1ProductDetailsSceneViewController~1onAddItem(_:)\/title","value":"onAddItem:"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1ProductDetailsSceneViewController~1onAddItem(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onAddItem:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1ProductDetailsSceneViewController~1viewDidLoad()\/title","value":"viewDidLoad"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1ProductDetailsSceneViewController~1viewDidLoad()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"viewDidLoad"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1ProductDetailsSceneViewController~1productDetailLabel\/title","value":"productDetailLabel"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1ProductDetailsSceneViewController~1productDetailLabel\/fragments","value":[{"kind":"identifier","text":"productDetailLabel"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1ProductDetailsSceneViewController~1descriptionLabel\/title","value":"descriptionLabel"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1ProductDetailsSceneViewController~1descriptionLabel\/fragments","value":[{"kind":"identifier","text":"descriptionLabel"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1ProductDetailsSceneViewController~1scrollView\/title","value":"scrollView"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1ProductDetailsSceneViewController~1scrollView\/fragments","value":[{"kind":"identifier","text":"scrollView"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1MasterViewController\/title","value":"MasterViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1MasterViewController\/fragments","value":[{"kind":"identifier","text":"MasterViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1ProductDetailsSceneViewController\/title","value":"ProductDetailsSceneViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1ProductDetailsSceneViewController\/fragments","value":[{"kind":"identifier","text":"ProductDetailsSceneViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1ProductDetailsSceneViewController~1init(coder:)\/title","value":"initWithCoder:"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1ProductDetailsSceneViewController~1init(coder:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithCoder:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1ProductDetailsSceneViewController~1imagesViewer\/title","value":"imagesViewer"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1ProductDetailsSceneViewController~1imagesViewer\/fragments","value":[{"kind":"identifier","text":"imagesViewer"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}