{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ProductsListingDatasourceManager"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/yababa\/productslistingdatasourcemanager"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/yababa\/productslistingdatasourcemanager"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.yababaGmbH.yababa\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ActionButtonDelegate","doc:\/\/com.yababaGmbH.yababa\/objc(pl)NSObject","doc:\/\/com.yababaGmbH.yababa\/12SkeletonView17AssociatedObjectsP","doc:\/\/com.yababaGmbH.yababa\/s7CVarArgP","doc:\/\/com.yababaGmbH.yababa\/s28CustomDebugStringConvertibleP","doc:\/\/com.yababaGmbH.yababa\/s23CustomStringConvertibleP","doc:\/\/com.yababaGmbH.yababa\/SQ","doc:\/\/com.yababaGmbH.yababa\/SH","doc:\/\/com.yababaGmbH.yababa\/objc(pl)UICollectionViewDataSource","doc:\/\/com.yababaGmbH.yababa\/objc(pl)UICollectionViewDelegate","doc:\/\/com.yababaGmbH.yababa\/objc(pl)UICollectionViewDelegateFlowLayout","doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIScrollViewDelegate"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ProductsListingDatasourceManager","interfaceLanguage":"swift"},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ProductsListingDatasourceManager\/init(collectionView:category:delegate:origin:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ProductsListingDatasourceManager\/viewingSection"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ProductsListingDatasourceManager\/collectionView(_:cellForItemAt:)","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ProductsListingDatasourceManager\/collectionView(_:didSelectItemAt:)","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ProductsListingDatasourceManager\/collectionView(_:layout:referenceSizeForFooterInSection:)","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ProductsListingDatasourceManager\/collectionView(_:numberOfItemsInSection:)","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ProductsListingDatasourceManager\/collectionView(_:viewForSupplementaryElementOfKind:at:)","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ProductsListingDatasourceManager\/numberOfSections(in:)","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ProductsListingDatasourceManager\/updateCategory(_:)"]},{"title":"Default Implementations","identifiers":["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ProductsListingDatasourceManager\/ActionButtonDelegate-Implementations"],"generated":true}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ProductsListingDatasourceManager"}],"title":"ProductsListingDatasourceManager","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@Yababa@objc(cs)ProductsListingDatasourceManager","modules":[{"name":"Yababa"}],"navigatorTitle":[{"kind":"identifier","text":"ProductsListingDatasourceManager"}]},"hierarchy":{"paths":[["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa"]]},"references":{"doc://com.yababaGmbH.yababa/documentation/Yababa/ProductsListingDatasourceManager/init(collectionView:category:delegate:origin:)":{"role":"symbol","title":"init(collectionView:category:delegate:origin:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"collectionView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UICollectionView","preciseIdentifier":"c:objc(cs)UICollectionView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"category"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CollectionCategory","preciseIdentifier":"s:6Yababa18CollectionCategoryC"},{"kind":"text","text":", "},{"kind":"externalParam","text":"delegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ProductsListingDelegate","preciseIdentifier":"s:6Yababa23ProductsListingDelegateP"},{"kind":"text","text":", "},{"kind":"externalParam","text":"origin"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TrackingOrigin","preciseIdentifier":"s:6Yababa14TrackingOriginO"},{"kind":"text","text":"?)"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ProductsListingDatasourceManager\/init(collectionView:category:delegate:origin:)","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/productslistingdatasourcemanager\/init(collectionview:category:delegate:origin:)"},"doc://com.yababaGmbH.yababa/documentation/Yababa/ProductsListingDatasourceManager/collectionView(_:cellForItemAt:)":{"role":"symbol","title":"collectionView(_:cellForItemAt:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"collectionView"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UICollectionView","preciseIdentifier":"c:objc(cs)UICollectionView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"cellForItemAt"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"IndexPath","preciseIdentifier":"s:10Foundation9IndexPathV"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"UICollectionViewCell","preciseIdentifier":"c:objc(cs)UICollectionViewCell"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ProductsListingDatasourceManager\/collectionView(_:cellForItemAt:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"collectionView:cellForItemAtIndexPath:"}],"url":"\/documentation\/yababa\/productslistingdatasourcemanager\/collectionview(_:cellforitemat:)"},"doc://com.yababaGmbH.yababa/objc(pl)UICollectionViewDataSource":{"type":"unresolvable","title":"UICollectionViewDataSource","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)UICollectionViewDataSource"},"doc://com.yababaGmbH.yababa/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.yababaGmbH.yababa\/s23CustomStringConvertibleP"},"doc://com.yababaGmbH.yababa/documentation/Yababa/ProductsListingDatasourceManager/updateCategory(_:)":{"role":"symbol","title":"updateCategory(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"updateCategory"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"CollectionCategory","preciseIdentifier":"s:6Yababa18CollectionCategoryC"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ProductsListingDatasourceManager\/updateCategory(_:)","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/productslistingdatasourcemanager\/updatecategory(_:)"},"doc://com.yababaGmbH.yababa/documentation/Yababa/ProductsListingDatasourceManager/collectionView(_:didSelectItemAt:)":{"role":"symbol","title":"collectionView(_:didSelectItemAt:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"collectionView"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UICollectionView","preciseIdentifier":"c:objc(cs)UICollectionView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didSelectItemAt"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"IndexPath","preciseIdentifier":"s:10Foundation9IndexPathV"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ProductsListingDatasourceManager\/collectionView(_:didSelectItemAt:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"collectionView:didSelectItemAtIndexPath:"}],"url":"\/documentation\/yababa\/productslistingdatasourcemanager\/collectionview(_:didselectitemat:)"},"doc://com.yababaGmbH.yababa/documentation/Yababa/ProductsListingDatasourceManager/numberOfSections(in:)":{"role":"symbol","title":"numberOfSections(in:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"numberOfSections"},{"kind":"text","text":"("},{"kind":"externalParam","text":"in"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UICollectionView","preciseIdentifier":"c:objc(cs)UICollectionView"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ProductsListingDatasourceManager\/numberOfSections(in:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"numberOfSectionsInCollectionView:"}],"url":"\/documentation\/yababa\/productslistingdatasourcemanager\/numberofsections(in:)"},"doc://com.yababaGmbH.yababa/documentation/Yababa":{"role":"collection","title":"Yababa","abstract":[{"type":"text","text":"Getting Started"}],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa","kind":"symbol","type":"topic","url":"\/documentation\/yababa"},"doc://com.yababaGmbH.yababa/documentation/Yababa/ActionButtonDelegate":{"role":"symbol","title":"ActionButtonDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"ActionButtonDelegate"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ActionButtonDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ActionButtonDelegate"}],"url":"\/documentation\/yababa\/actionbuttondelegate"},"doc://com.yababaGmbH.yababa/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(cs)NSObject"},"doc://com.yababaGmbH.yababa/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.yababaGmbH.yababa\/SQ"},"doc://com.yababaGmbH.yababa/documentation/Yababa/ProductsListingDatasourceManager/collectionView(_:layout:referenceSizeForFooterInSection:)":{"role":"symbol","title":"collectionView(_:layout:referenceSizeForFooterInSection:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"collectionView"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UICollectionView","preciseIdentifier":"c:objc(cs)UICollectionView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"layout"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UICollectionViewLayout","preciseIdentifier":"c:objc(cs)UICollectionViewLayout"},{"kind":"text","text":", "},{"kind":"externalParam","text":"referenceSizeForFooterInSection"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"CGSize","preciseIdentifier":"c:@S@CGSize"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ProductsListingDatasourceManager\/collectionView(_:layout:referenceSizeForFooterInSection:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"collectionView:layout:referenceSizeForFooterInSection:"}],"url":"\/documentation\/yababa\/productslistingdatasourcemanager\/collectionview(_:layout:referencesizeforfooterinsection:)"},"doc://com.yababaGmbH.yababa/documentation/Yababa/ProductsListingDatasourceManager/collectionView(_:viewForSupplementaryElementOfKind:at:)":{"role":"symbol","title":"collectionView(_:viewForSupplementaryElementOfKind:at:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"collectionView"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UICollectionView","preciseIdentifier":"c:objc(cs)UICollectionView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"viewForSupplementaryElementOfKind"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"at"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"IndexPath","preciseIdentifier":"s:10Foundation9IndexPathV"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"UICollectionReusableView","preciseIdentifier":"c:objc(cs)UICollectionReusableView"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ProductsListingDatasourceManager\/collectionView(_:viewForSupplementaryElementOfKind:at:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"collectionView:viewForSupplementaryElementOfKind:atIndexPath:"}],"url":"\/documentation\/yababa\/productslistingdatasourcemanager\/collectionview(_:viewforsupplementaryelementofkind:at:)"},"doc://com.yababaGmbH.yababa/12SkeletonView17AssociatedObjectsP":{"type":"unresolvable","title":"SkeletonView.AssociatedObjects","identifier":"doc:\/\/com.yababaGmbH.yababa\/12SkeletonView17AssociatedObjectsP"},"doc://com.yababaGmbH.yababa/documentation/Yababa/ProductsListingDatasourceManager/viewingSection":{"role":"symbol","title":"viewingSection","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"viewingSection"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Box","preciseIdentifier":"s:6Yababa3BoxC"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":">"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ProductsListingDatasourceManager\/viewingSection","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/productslistingdatasourcemanager\/viewingsection"},"doc://com.yababaGmbH.yababa/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.yababaGmbH.yababa\/s28CustomDebugStringConvertibleP"},"doc://com.yababaGmbH.yababa/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.yababaGmbH.yababa\/s7CVarArgP"},"doc://com.yababaGmbH.yababa/objc(pl)UIScrollViewDelegate":{"type":"unresolvable","title":"UIKit.UIScrollViewDelegate","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIScrollViewDelegate"},"doc://com.yababaGmbH.yababa/documentation/Yababa/ProductsListingDatasourceManager/ActionButtonDelegate-Implementations":{"role":"collectionGroup","title":"ActionButtonDelegate Implementations","abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ProductsListingDatasourceManager\/ActionButtonDelegate-Implementations","kind":"article","type":"topic","url":"\/documentation\/yababa\/productslistingdatasourcemanager\/actionbuttondelegate-implementations"},"doc://com.yababaGmbH.yababa/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)NSObject"},"doc://com.yababaGmbH.yababa/documentation/Yababa/ProductsListingDatasourceManager":{"role":"symbol","title":"ProductsListingDatasourceManager","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ProductsListingDatasourceManager"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ProductsListingDatasourceManager","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ProductsListingDatasourceManager"}],"url":"\/documentation\/yababa\/productslistingdatasourcemanager"},"doc://com.yababaGmbH.yababa/objc(pl)UICollectionViewDelegate":{"type":"unresolvable","title":"UIKit.UICollectionViewDelegate","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)UICollectionViewDelegate"},"doc://com.yababaGmbH.yababa/documentation/Yababa/ProductsListingDatasourceManager/collectionView(_:numberOfItemsInSection:)":{"role":"symbol","title":"collectionView(_:numberOfItemsInSection:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"collectionView"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UICollectionView","preciseIdentifier":"c:objc(cs)UICollectionView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"numberOfItemsInSection"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ProductsListingDatasourceManager\/collectionView(_:numberOfItemsInSection:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"collectionView:numberOfItemsInSection:"}],"url":"\/documentation\/yababa\/productslistingdatasourcemanager\/collectionview(_:numberofitemsinsection:)"},"doc://com.yababaGmbH.yababa/objc(pl)UICollectionViewDelegateFlowLayout":{"type":"unresolvable","title":"UICollectionViewDelegateFlowLayout","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)UICollectionViewDelegateFlowLayout"},"doc://com.yababaGmbH.yababa/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.yababaGmbH.yababa\/SH"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"ProductsListingDatasourceManager"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"ProductsListingDatasourceManager"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"ProductsListingDatasourceManager"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ProductsListingDatasourceManager\/collectionView(_:cellForItemAt:)","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ProductsListingDatasourceManager\/collectionView(_:didSelectItemAt:)","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ProductsListingDatasourceManager\/collectionView(_:layout:referenceSizeForFooterInSection:)","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ProductsListingDatasourceManager\/collectionView(_:numberOfItemsInSection:)","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ProductsListingDatasourceManager\/collectionView(_:viewForSupplementaryElementOfKind:at:)","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ProductsListingDatasourceManager\/numberOfSections(in:)"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.yababaGmbH.yababa\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.yababaGmbH.yababa\/objc(pl)UICollectionViewDataSource","doc:\/\/com.yababaGmbH.yababa\/objc(pl)UICollectionViewDelegateFlowLayout"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"ProductsListingDatasourceManager"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1ProductsListingDatasourceManager~1collectionView(_:cellForItemAt:)\/title","value":"collectionView:cellForItemAtIndexPath:"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1ProductsListingDatasourceManager~1collectionView(_:cellForItemAt:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"collectionView:cellForItemAtIndexPath:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1ProductsListingDatasourceManager~1collectionView(_:didSelectItemAt:)\/title","value":"collectionView:didSelectItemAtIndexPath:"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1ProductsListingDatasourceManager~1collectionView(_:didSelectItemAt:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"collectionView:didSelectItemAtIndexPath:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1ProductsListingDatasourceManager~1numberOfSections(in:)\/title","value":"numberOfSectionsInCollectionView:"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1ProductsListingDatasourceManager~1numberOfSections(in:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"numberOfSectionsInCollectionView:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1ProductsListingDatasourceManager~1collectionView(_:layout:referenceSizeForFooterInSection:)\/title","value":"collectionView:layout:referenceSizeForFooterInSection:"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1ProductsListingDatasourceManager~1collectionView(_:layout:referenceSizeForFooterInSection:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"collectionView:layout:referenceSizeForFooterInSection:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1ProductsListingDatasourceManager~1collectionView(_:viewForSupplementaryElementOfKind:at:)\/title","value":"collectionView:viewForSupplementaryElementOfKind:atIndexPath:"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1ProductsListingDatasourceManager~1collectionView(_:viewForSupplementaryElementOfKind:at:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"collectionView:viewForSupplementaryElementOfKind:atIndexPath:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1ProductsListingDatasourceManager\/title","value":"ProductsListingDatasourceManager"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1ProductsListingDatasourceManager\/fragments","value":[{"kind":"identifier","text":"ProductsListingDatasourceManager"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1ProductsListingDatasourceManager~1collectionView(_:numberOfItemsInSection:)\/title","value":"collectionView:numberOfItemsInSection:"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1ProductsListingDatasourceManager~1collectionView(_:numberOfItemsInSection:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"collectionView:numberOfItemsInSection:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}