{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ProfileClass"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/yababa\/profileclass"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/yababa\/profileclass"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.yababaGmbH.yababa\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/Profile"],"kind":"relationships","title":"Inherited By","type":"inheritedBy"},{"identifiers":["doc:\/\/com.yababaGmbH.yababa\/objc(pl)NSCoding","doc:\/\/com.yababaGmbH.yababa\/objc(pl)NSObject","doc:\/\/com.yababaGmbH.yababa\/12SkeletonView17AssociatedObjectsP","doc:\/\/com.yababaGmbH.yababa\/s7CVarArgP","doc:\/\/com.yababaGmbH.yababa\/s28CustomDebugStringConvertibleP","doc:\/\/com.yababaGmbH.yababa\/s23CustomStringConvertibleP","doc:\/\/com.yababaGmbH.yababa\/SQ","doc:\/\/com.yababaGmbH.yababa\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ProfileClass","interfaceLanguage":"swift"},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ProfileClass\/init()","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ProfileClass\/init(coder:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ProfileClass\/email","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ProfileClass\/emailSubscribed","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ProfileClass\/facebookUserID","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ProfileClass\/name","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ProfileClass\/phoneNumber","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ProfileClass\/phoneNumberVerified","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ProfileClass\/picUrl","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ProfileClass\/pushSubscribed","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ProfileClass\/userKey","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ProfileClass\/username"]}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ProfileClass"}],"title":"ProfileClass","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:objc(cs)ProfileClass","modules":[{"name":"Yababa"}],"navigatorTitle":[{"kind":"identifier","text":"ProfileClass"}]},"hierarchy":{"paths":[["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa"]]},"references":{"doc://com.yababaGmbH.yababa/documentation/Yababa/ProfileClass/emailSubscribed":{"role":"symbol","title":"emailSubscribed","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"emailSubscribed"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ProfileClass\/emailSubscribed","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"emailSubscribed"}],"url":"\/documentation\/yababa\/profileclass\/emailsubscribed"},"doc://com.yababaGmbH.yababa/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.yababaGmbH.yababa\/SQ"},"doc://com.yababaGmbH.yababa/documentation/Yababa/ProfileClass/facebookUserID":{"role":"symbol","title":"facebookUserID","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"facebookUserID"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ProfileClass\/facebookUserID","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"facebookUserID"}],"url":"\/documentation\/yababa\/profileclass\/facebookuserid"},"doc://com.yababaGmbH.yababa/documentation/Yababa/ProfileClass/phoneNumber":{"role":"symbol","title":"phoneNumber","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"phoneNumber"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ProfileClass\/phoneNumber","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"phoneNumber"}],"url":"\/documentation\/yababa\/profileclass\/phonenumber"},"doc://com.yababaGmbH.yababa/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)NSObject"},"doc://com.yababaGmbH.yababa/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.yababaGmbH.yababa\/SH"},"doc://com.yababaGmbH.yababa/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.yababaGmbH.yababa\/s28CustomDebugStringConvertibleP"},"doc://com.yababaGmbH.yababa/documentation/Yababa/ProfileClass/username":{"role":"symbol","title":"username","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"username"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ProfileClass\/username","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"username"}],"url":"\/documentation\/yababa\/profileclass\/username"},"doc://com.yababaGmbH.yababa/documentation/Yababa/ProfileClass/name":{"role":"symbol","title":"name","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"name"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ProfileClass\/name","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"name"}],"url":"\/documentation\/yababa\/profileclass\/name"},"doc://com.yababaGmbH.yababa/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(cs)NSObject"},"doc://com.yababaGmbH.yababa/documentation/Yababa/ProfileClass/init(coder:)":{"role":"symbol","title":"init(coder:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"coder"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSCoder","preciseIdentifier":"c:objc(cs)NSCoder"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ProfileClass\/init(coder:)","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/profileclass\/init(coder:)"},"doc://com.yababaGmbH.yababa/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.yababaGmbH.yababa\/s7CVarArgP"},"doc://com.yababaGmbH.yababa/documentation/Yababa/ProfileClass/init()":{"role":"symbol","title":"init()","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"!()"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ProfileClass\/init()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"init"}],"url":"\/documentation\/yababa\/profileclass\/init()"},"doc://com.yababaGmbH.yababa/documentation/Yababa":{"role":"collection","title":"Yababa","abstract":[{"type":"text","text":"Getting Started"}],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa","kind":"symbol","type":"topic","url":"\/documentation\/yababa"},"doc://com.yababaGmbH.yababa/documentation/Yababa/ProfileClass/userKey":{"role":"symbol","title":"userKey","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"userKey"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ProfileClass\/userKey","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"userKey"}],"url":"\/documentation\/yababa\/profileclass\/userkey"},"doc://com.yababaGmbH.yababa/documentation/Yababa/ProfileClass/picUrl":{"role":"symbol","title":"picUrl","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"picUrl"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ProfileClass\/picUrl","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"picUrl"}],"url":"\/documentation\/yababa\/profileclass\/picurl"},"doc://com.yababaGmbH.yababa/documentation/Yababa/ProfileClass/pushSubscribed":{"role":"symbol","title":"pushSubscribed","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"pushSubscribed"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ProfileClass\/pushSubscribed","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"pushSubscribed"}],"url":"\/documentation\/yababa\/profileclass\/pushsubscribed"},"doc://com.yababaGmbH.yababa/documentation/Yababa/ProfileClass/email":{"role":"symbol","title":"email","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"email"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ProfileClass\/email","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"email"}],"url":"\/documentation\/yababa\/profileclass\/email"},"doc://com.yababaGmbH.yababa/documentation/Yababa/Profile":{"role":"symbol","title":"Profile","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Profile"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/Profile","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Profile"}],"url":"\/documentation\/yababa\/profile"},"doc://com.yababaGmbH.yababa/documentation/Yababa/ProfileClass/phoneNumberVerified":{"role":"symbol","title":"phoneNumberVerified","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"phoneNumberVerified"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ProfileClass\/phoneNumberVerified","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"phoneNumberVerified"}],"url":"\/documentation\/yababa\/profileclass\/phonenumberverified"},"doc://com.yababaGmbH.yababa/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.yababaGmbH.yababa\/s23CustomStringConvertibleP"},"doc://com.yababaGmbH.yababa/objc(pl)NSCoding":{"type":"unresolvable","title":"NSCoding","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)NSCoding"},"doc://com.yababaGmbH.yababa/12SkeletonView17AssociatedObjectsP":{"type":"unresolvable","title":"SkeletonView.AssociatedObjects","identifier":"doc:\/\/com.yababaGmbH.yababa\/12SkeletonView17AssociatedObjectsP"},"doc://com.yababaGmbH.yababa/documentation/Yababa/ProfileClass":{"role":"symbol","title":"ProfileClass","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ProfileClass"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ProfileClass","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ProfileClass"}],"url":"\/documentation\/yababa\/profileclass"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"ProfileClass"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"ProfileClass"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"ProfileClass"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ProfileClass\/email","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ProfileClass\/emailSubscribed","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ProfileClass\/facebookUserID","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ProfileClass\/name","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ProfileClass\/phoneNumber","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ProfileClass\/phoneNumberVerified","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ProfileClass\/picUrl","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ProfileClass\/pushSubscribed","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ProfileClass\/userKey","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ProfileClass\/username"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ProfileClass\/init()"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.yababaGmbH.yababa\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/Profile"],"kind":"relationships","title":"Inherited By","type":"inheritedBy"},{"identifiers":["doc:\/\/com.yababaGmbH.yababa\/objc(pl)NSCoding"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"ProfileClass"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1ProfileClass~1emailSubscribed\/title","value":"emailSubscribed"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1ProfileClass~1emailSubscribed\/fragments","value":[{"kind":"identifier","text":"emailSubscribed"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1ProfileClass~1facebookUserID\/title","value":"facebookUserID"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1ProfileClass~1facebookUserID\/fragments","value":[{"kind":"identifier","text":"facebookUserID"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1ProfileClass~1phoneNumber\/title","value":"phoneNumber"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1ProfileClass~1phoneNumber\/fragments","value":[{"kind":"identifier","text":"phoneNumber"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1ProfileClass~1username\/title","value":"username"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1ProfileClass~1username\/fragments","value":[{"kind":"identifier","text":"username"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1ProfileClass~1name\/title","value":"name"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1ProfileClass~1name\/fragments","value":[{"kind":"identifier","text":"name"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1ProfileClass~1init()\/title","value":"init"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1ProfileClass~1init()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1ProfileClass~1userKey\/title","value":"userKey"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1ProfileClass~1userKey\/fragments","value":[{"kind":"identifier","text":"userKey"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1ProfileClass~1picUrl\/title","value":"picUrl"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1ProfileClass~1picUrl\/fragments","value":[{"kind":"identifier","text":"picUrl"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1ProfileClass~1pushSubscribed\/title","value":"pushSubscribed"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1ProfileClass~1pushSubscribed\/fragments","value":[{"kind":"identifier","text":"pushSubscribed"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1ProfileClass~1email\/title","value":"email"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1ProfileClass~1email\/fragments","value":[{"kind":"identifier","text":"email"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1Profile\/title","value":"Profile"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1Profile\/fragments","value":[{"kind":"identifier","text":"Profile"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1ProfileClass~1phoneNumberVerified\/title","value":"phoneNumberVerified"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1ProfileClass~1phoneNumberVerified\/fragments","value":[{"kind":"identifier","text":"phoneNumberVerified"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1ProfileClass\/title","value":"ProfileClass"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1ProfileClass\/fragments","value":[{"kind":"identifier","text":"ProfileClass"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}