{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PushNotificationsManager"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/yababa\/pushnotificationsmanager"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/yababa\/pushnotificationsmanager"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.yababaGmbH.yababa\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.yababaGmbH.yababa\/objc(pl)NSObject","doc:\/\/com.yababaGmbH.yababa\/12SkeletonView17AssociatedObjectsP","doc:\/\/com.yababaGmbH.yababa\/s7CVarArgP","doc:\/\/com.yababaGmbH.yababa\/s28CustomDebugStringConvertibleP","doc:\/\/com.yababaGmbH.yababa\/s23CustomStringConvertibleP","doc:\/\/com.yababaGmbH.yababa\/SQ","doc:\/\/com.yababaGmbH.yababa\/SH","doc:\/\/com.yababaGmbH.yababa\/objc(pl)UNUserNotificationCenterDelegate"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/PushNotificationsManager","interfaceLanguage":"swift"},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/PushNotificationsManager\/init()"]},{"title":"Instance Properties","identifiers":["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/PushNotificationsManager\/prompterViewController"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/PushNotificationsManager\/application(_:didReceiveRemoteNotification:fetchCompletionHandler:)","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/PushNotificationsManager\/configure(pushNotificationManagerInteractor:pushNotificationMarketingManager:)","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/PushNotificationsManager\/deviceHasAuthorizedPushNotifications(completion:)","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/PushNotificationsManager\/didRegisterForRemoteNotifications(deviceToken:)","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/PushNotificationsManager\/getDevicePushNotificationAuthStatus(completion:)","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/PushNotificationsManager\/getUserPushSubscriptionStatus()","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/PushNotificationsManager\/navigateToDeviceSettings()","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/PushNotificationsManager\/prepareHardOptIn()","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/PushNotificationsManager\/prepareHardOptIn(deniedExtraAction:)","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/PushNotificationsManager\/promptEnablePushNotificationFromSettings()","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/PushNotificationsManager\/userRespondedToHardOptIn(_:)","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/PushNotificationsManager\/userRespondedToSoftOptIn(_:)"]},{"title":"Type Properties","identifiers":["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/PushNotificationsManager\/sharedInstance"]},{"title":"Default Implementations","identifiers":["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/PushNotificationsManager\/UNUserNotificationCenterDelegate-Implementations"],"generated":true}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PushNotificationsManager"}],"title":"PushNotificationsManager","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@Yababa@objc(cs)PushNotificationsManager","modules":[{"name":"Yababa"}],"navigatorTitle":[{"kind":"identifier","text":"PushNotificationsManager"}]},"hierarchy":{"paths":[["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa"]]},"references":{"doc://com.yababaGmbH.yababa/documentation/Yababa/PushNotificationsManager/prompterViewController":{"role":"symbol","title":"prompterViewController","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"prompterViewController"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/PushNotificationsManager\/prompterViewController","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/pushnotificationsmanager\/prompterviewcontroller"},"doc://com.yababaGmbH.yababa/documentation/Yababa/PushNotificationsManager/application(_:didReceiveRemoteNotification:fetchCompletionHandler:)":{"role":"symbol","title":"application(_:didReceiveRemoteNotification:fetchCompletionHandler:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"application"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UIApplication","preciseIdentifier":"c:objc(cs)UIApplication"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didReceiveRemoteNotification"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"AnyHashable","preciseIdentifier":"s:s11AnyHashableV"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"fetchCompletionHandler"},{"kind":"text","text":": ("},{"kind":"typeIdentifier","text":"UIBackgroundFetchResult","preciseIdentifier":"c:@E@UIBackgroundFetchResult"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/PushNotificationsManager\/application(_:didReceiveRemoteNotification:fetchCompletionHandler:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"application:didReceiveRemoteNotification:fetchCompletionHandler:"}],"url":"\/documentation\/yababa\/pushnotificationsmanager\/application(_:didreceiveremotenotification:fetchcompletionhandler:)"},"doc://com.yababaGmbH.yababa/documentation/Yababa/PushNotificationsManager/sharedInstance":{"role":"symbol","title":"sharedInstance","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"sharedInstance"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"PushNotificationsManager","preciseIdentifier":"c:@M@Yababa@objc(cs)PushNotificationsManager"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/PushNotificationsManager\/sharedInstance","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"sharedInstance"}],"url":"\/documentation\/yababa\/pushnotificationsmanager\/sharedinstance"},"doc://com.yababaGmbH.yababa/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(cs)NSObject"},"doc://com.yababaGmbH.yababa/documentation/Yababa":{"role":"collection","title":"Yababa","abstract":[{"type":"text","text":"Getting Started"}],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa","kind":"symbol","type":"topic","url":"\/documentation\/yababa"},"doc://com.yababaGmbH.yababa/documentation/Yababa/PushNotificationsManager/didRegisterForRemoteNotifications(deviceToken:)":{"role":"symbol","title":"didRegisterForRemoteNotifications(deviceToken:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"didRegisterForRemoteNotifications"},{"kind":"text","text":"("},{"kind":"externalParam","text":"deviceToken"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Data","preciseIdentifier":"s:10Foundation4DataV"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/PushNotificationsManager\/didRegisterForRemoteNotifications(deviceToken:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"didRegisterForRemoteNotificationsWithDeviceToken:"}],"url":"\/documentation\/yababa\/pushnotificationsmanager\/didregisterforremotenotifications(devicetoken:)"},"doc://com.yababaGmbH.yababa/documentation/Yababa/PushNotificationsManager/navigateToDeviceSettings()":{"role":"symbol","title":"navigateToDeviceSettings()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"navigateToDeviceSettings"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/PushNotificationsManager\/navigateToDeviceSettings()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"navigateToDeviceSettings"}],"url":"\/documentation\/yababa\/pushnotificationsmanager\/navigatetodevicesettings()"},"doc://com.yababaGmbH.yababa/documentation/Yababa/PushNotificationsManager/configure(pushNotificationManagerInteractor:pushNotificationMarketingManager:)":{"role":"symbol","title":"configure(pushNotificationManagerInteractor:pushNotificationMarketingManager:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"configure"},{"kind":"text","text":"("},{"kind":"externalParam","text":"pushNotificationManagerInteractor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"PushNotificationInteractorProtocol","preciseIdentifier":"c:@M@Yababa@objc(pl)PushNotificationInteractorProtocol"},{"kind":"text","text":", "},{"kind":"externalParam","text":"pushNotificationMarketingManager"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"PushNotificationMarketingManager","preciseIdentifier":"s:6Yababa32PushNotificationMarketingManagerP"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/PushNotificationsManager\/configure(pushNotificationManagerInteractor:pushNotificationMarketingManager:)","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/pushnotificationsmanager\/configure(pushnotificationmanagerinteractor:pushnotificationmarketingmanager:)"},"doc://com.yababaGmbH.yababa/documentation/Yababa/PushNotificationsManager/init()":{"role":"symbol","title":"init()","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/PushNotificationsManager\/init()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"init"}],"url":"\/documentation\/yababa\/pushnotificationsmanager\/init()"},"doc://com.yababaGmbH.yababa/12SkeletonView17AssociatedObjectsP":{"type":"unresolvable","title":"SkeletonView.AssociatedObjects","identifier":"doc:\/\/com.yababaGmbH.yababa\/12SkeletonView17AssociatedObjectsP"},"doc://com.yababaGmbH.yababa/documentation/Yababa/PushNotificationsManager/promptEnablePushNotificationFromSettings()":{"role":"symbol","title":"promptEnablePushNotificationFromSettings()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"promptEnablePushNotificationFromSettings"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/PushNotificationsManager\/promptEnablePushNotificationFromSettings()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"promptEnablePushNotificationFromSettings"}],"url":"\/documentation\/yababa\/pushnotificationsmanager\/promptenablepushnotificationfromsettings()"},"doc://com.yababaGmbH.yababa/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)NSObject"},"doc://com.yababaGmbH.yababa/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.yababaGmbH.yababa\/SH"},"doc://com.yababaGmbH.yababa/documentation/Yababa/PushNotificationsManager/prepareHardOptIn(deniedExtraAction:)":{"role":"symbol","title":"prepareHardOptIn(deniedExtraAction:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"prepareHardOptIn"},{"kind":"text","text":"("},{"kind":"externalParam","text":"deniedExtraAction"},{"kind":"text","text":": (() -> ())?)"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/PushNotificationsManager\/prepareHardOptIn(deniedExtraAction:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"prepareHardOptInDeniedExtraAction:"}],"url":"\/documentation\/yababa\/pushnotificationsmanager\/preparehardoptin(deniedextraaction:)"},"doc://com.yababaGmbH.yababa/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.yababaGmbH.yababa\/s23CustomStringConvertibleP"},"doc://com.yababaGmbH.yababa/documentation/Yababa/PushNotificationsManager/UNUserNotificationCenterDelegate-Implementations":{"role":"collectionGroup","title":"UNUserNotificationCenterDelegate Implementations","abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/PushNotificationsManager\/UNUserNotificationCenterDelegate-Implementations","kind":"article","type":"topic","url":"\/documentation\/yababa\/pushnotificationsmanager\/unusernotificationcenterdelegate-implementations"},"doc://com.yababaGmbH.yababa/documentation/Yababa/PushNotificationsManager/prepareHardOptIn()":{"role":"symbol","title":"prepareHardOptIn()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"prepareHardOptIn"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/PushNotificationsManager\/prepareHardOptIn()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"prepareHardOptIn"}],"url":"\/documentation\/yababa\/pushnotificationsmanager\/preparehardoptin()"},"doc://com.yababaGmbH.yababa/documentation/Yababa/PushNotificationsManager/getUserPushSubscriptionStatus()":{"role":"symbol","title":"getUserPushSubscriptionStatus()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getUserPushSubscriptionStatus"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"SubscriptionStatus","preciseIdentifier":"c:@M@Yababa@E@SubscriptionStatus"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/PushNotificationsManager\/getUserPushSubscriptionStatus()","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/pushnotificationsmanager\/getuserpushsubscriptionstatus()"},"doc://com.yababaGmbH.yababa/documentation/Yababa/PushNotificationsManager":{"role":"symbol","title":"PushNotificationsManager","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PushNotificationsManager"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/PushNotificationsManager","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PushNotificationsManager"}],"url":"\/documentation\/yababa\/pushnotificationsmanager"},"doc://com.yababaGmbH.yababa/documentation/Yababa/PushNotificationsManager/userRespondedToHardOptIn(_:)":{"role":"symbol","title":"userRespondedToHardOptIn(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"userRespondedToHardOptIn"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/PushNotificationsManager\/userRespondedToHardOptIn(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"userRespondedToHardOptIn:"}],"url":"\/documentation\/yababa\/pushnotificationsmanager\/userrespondedtohardoptin(_:)"},"doc://com.yababaGmbH.yababa/documentation/Yababa/PushNotificationsManager/getDevicePushNotificationAuthStatus(completion:)":{"role":"symbol","title":"getDevicePushNotificationAuthStatus(completion:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getDevicePushNotificationAuthStatus"},{"kind":"text","text":"("},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": ("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"permissionStatus"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UNAuthorizationStatus","preciseIdentifier":"c:@E@UNAuthorizationStatus"},{"kind":"text","text":") -> ())"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/PushNotificationsManager\/getDevicePushNotificationAuthStatus(completion:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"getDevicePushNotificationAuthStatusWithCompletion:"}],"url":"\/documentation\/yababa\/pushnotificationsmanager\/getdevicepushnotificationauthstatus(completion:)"},"doc://com.yababaGmbH.yababa/documentation/Yababa/PushNotificationsManager/userRespondedToSoftOptIn(_:)":{"role":"symbol","title":"userRespondedToSoftOptIn(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"userRespondedToSoftOptIn"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/PushNotificationsManager\/userRespondedToSoftOptIn(_:)","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/pushnotificationsmanager\/userrespondedtosoftoptin(_:)"},"doc://com.yababaGmbH.yababa/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.yababaGmbH.yababa\/s7CVarArgP"},"doc://com.yababaGmbH.yababa/documentation/Yababa/PushNotificationsManager/deviceHasAuthorizedPushNotifications(completion:)":{"role":"symbol","title":"deviceHasAuthorizedPushNotifications(completion:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"deviceHasAuthorizedPushNotifications"},{"kind":"text","text":"("},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": ("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"granted"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":") -> ())"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/PushNotificationsManager\/deviceHasAuthorizedPushNotifications(completion:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"deviceHasAuthorizedPushNotificationsWithCompletion:"}],"url":"\/documentation\/yababa\/pushnotificationsmanager\/devicehasauthorizedpushnotifications(completion:)"},"doc://com.yababaGmbH.yababa/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.yababaGmbH.yababa\/s28CustomDebugStringConvertibleP"},"doc://com.yababaGmbH.yababa/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.yababaGmbH.yababa\/SQ"},"doc://com.yababaGmbH.yababa/objc(pl)UNUserNotificationCenterDelegate":{"type":"unresolvable","title":"UserNotifications.UNUserNotificationCenterDelegate","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)UNUserNotificationCenterDelegate"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"PushNotificationsManager"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"PushNotificationsManager"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"PushNotificationsManager"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/PushNotificationsManager\/application(_:didReceiveRemoteNotification:fetchCompletionHandler:)","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/PushNotificationsManager\/deviceHasAuthorizedPushNotifications(completion:)","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/PushNotificationsManager\/didRegisterForRemoteNotifications(deviceToken:)","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/PushNotificationsManager\/getDevicePushNotificationAuthStatus(completion:)","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/PushNotificationsManager\/init()","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/PushNotificationsManager\/navigateToDeviceSettings()","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/PushNotificationsManager\/prepareHardOptIn()","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/PushNotificationsManager\/prepareHardOptIn(deniedExtraAction:)","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/PushNotificationsManager\/promptEnablePushNotificationFromSettings()","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/PushNotificationsManager\/userRespondedToHardOptIn(_:)"]},{"title":"Type Properties","identifiers":["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/PushNotificationsManager\/sharedInstance"]},{"title":"Default Implementations","identifiers":["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/PushNotificationsManager\/UNUserNotificationCenterDelegate-Implementations"],"generated":true}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.yababaGmbH.yababa\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"PushNotificationsManager"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1PushNotificationsManager~1application(_:didReceiveRemoteNotification:fetchCompletionHandler:)\/title","value":"application:didReceiveRemoteNotification:fetchCompletionHandler:"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1PushNotificationsManager~1application(_:didReceiveRemoteNotification:fetchCompletionHandler:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"application:didReceiveRemoteNotification:fetchCompletionHandler:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1PushNotificationsManager~1sharedInstance\/title","value":"sharedInstance"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1PushNotificationsManager~1sharedInstance\/fragments","value":[{"kind":"identifier","text":"sharedInstance"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1PushNotificationsManager~1didRegisterForRemoteNotifications(deviceToken:)\/title","value":"didRegisterForRemoteNotificationsWithDeviceToken:"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1PushNotificationsManager~1didRegisterForRemoteNotifications(deviceToken:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"didRegisterForRemoteNotificationsWithDeviceToken:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1PushNotificationsManager~1navigateToDeviceSettings()\/title","value":"navigateToDeviceSettings"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1PushNotificationsManager~1navigateToDeviceSettings()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"navigateToDeviceSettings"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1PushNotificationsManager~1init()\/title","value":"init"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1PushNotificationsManager~1init()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1PushNotificationsManager~1promptEnablePushNotificationFromSettings()\/title","value":"promptEnablePushNotificationFromSettings"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1PushNotificationsManager~1promptEnablePushNotificationFromSettings()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"promptEnablePushNotificationFromSettings"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1PushNotificationsManager~1prepareHardOptIn(deniedExtraAction:)\/title","value":"prepareHardOptInDeniedExtraAction:"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1PushNotificationsManager~1prepareHardOptIn(deniedExtraAction:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"prepareHardOptInDeniedExtraAction:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1PushNotificationsManager~1prepareHardOptIn()\/title","value":"prepareHardOptIn"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1PushNotificationsManager~1prepareHardOptIn()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"prepareHardOptIn"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1PushNotificationsManager\/title","value":"PushNotificationsManager"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1PushNotificationsManager\/fragments","value":[{"kind":"identifier","text":"PushNotificationsManager"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1PushNotificationsManager~1userRespondedToHardOptIn(_:)\/title","value":"userRespondedToHardOptIn:"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1PushNotificationsManager~1userRespondedToHardOptIn(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"userRespondedToHardOptIn:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1PushNotificationsManager~1getDevicePushNotificationAuthStatus(completion:)\/title","value":"getDevicePushNotificationAuthStatusWithCompletion:"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1PushNotificationsManager~1getDevicePushNotificationAuthStatus(completion:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"getDevicePushNotificationAuthStatusWithCompletion:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1PushNotificationsManager~1deviceHasAuthorizedPushNotifications(completion:)\/title","value":"deviceHasAuthorizedPushNotificationsWithCompletion:"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1PushNotificationsManager~1deviceHasAuthorizedPushNotifications(completion:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"deviceHasAuthorizedPushNotificationsWithCompletion:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}