{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"PushNotificationInteractorProtocol"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/yababa\/pushnotificationinteractorprotocol"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/yababa\/pushnotificationinteractorprotocol"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/PushNotificationInteractor"],"kind":"relationships","title":"Conforming Types","type":"conformingTypes"}],"identifier":{"url":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/PushNotificationInteractorProtocol","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/PushNotificationInteractorProtocol\/getDevicePushNotificationAuthStatus(completion:)","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/PushNotificationInteractorProtocol\/getUserPushSubscriptionStatus()","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/PushNotificationInteractorProtocol\/navigateToDeviceSettings()","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/PushNotificationInteractorProtocol\/promptEnablePushNotificationFromSettings()","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/PushNotificationInteractorProtocol\/promptHardOptIn()"]}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"PushNotificationInteractorProtocol"}],"title":"PushNotificationInteractorProtocol","roleHeading":"Protocol","role":"symbol","symbolKind":"protocol","externalID":"c:@M@Yababa@objc(pl)PushNotificationInteractorProtocol","modules":[{"name":"Yababa"}],"navigatorTitle":[{"kind":"identifier","text":"PushNotificationInteractorProtocol"}]},"hierarchy":{"paths":[["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa"]]},"references":{"doc://com.yababaGmbH.yababa/documentation/Yababa":{"role":"collection","title":"Yababa","abstract":[{"type":"text","text":"Getting Started"}],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa","kind":"symbol","type":"topic","url":"\/documentation\/yababa"},"doc://com.yababaGmbH.yababa/documentation/Yababa/PushNotificationInteractor":{"role":"symbol","title":"PushNotificationInteractor","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PushNotificationInteractor"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/PushNotificationInteractor","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PushNotificationInteractor"}],"url":"\/documentation\/yababa\/pushnotificationinteractor"},"doc://com.yababaGmbH.yababa/documentation/Yababa/PushNotificationInteractorProtocol/getDevicePushNotificationAuthStatus(completion:)":{"navigatorTitle":[{"kind":"identifier","text":"getDevicePushNotificationAuthStatusWithCompletion:"}],"role":"symbol","title":"getDevicePushNotificationAuthStatus(completion:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getDevicePushNotificationAuthStatus"},{"kind":"text","text":"("},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": ("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"permissionStatus"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UNAuthorizationStatus","preciseIdentifier":"c:@E@UNAuthorizationStatus"},{"kind":"text","text":") -> ())"}],"abstract":[{"type":"text","text":"Gets the status of app push notifications from the device settings for it"}],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/PushNotificationInteractorProtocol\/getDevicePushNotificationAuthStatus(completion:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/yababa\/pushnotificationinteractorprotocol\/getdevicepushnotificationauthstatus(completion:)"},"doc://com.yababaGmbH.yababa/documentation/Yababa/PushNotificationInteractorProtocol/promptHardOptIn()":{"navigatorTitle":[{"kind":"identifier","text":"promptHardOptIn"}],"role":"symbol","title":"promptHardOptIn()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"promptHardOptIn"},{"kind":"text","text":"()"}],"abstract":[{"type":"text","text":"Apple native push notification permission prompt"}],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/PushNotificationInteractorProtocol\/promptHardOptIn()","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/yababa\/pushnotificationinteractorprotocol\/prompthardoptin()"},"doc://com.yababaGmbH.yababa/documentation/Yababa/PushNotificationInteractorProtocol":{"role":"symbol","title":"PushNotificationInteractorProtocol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"PushNotificationInteractorProtocol"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/PushNotificationInteractorProtocol","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PushNotificationInteractorProtocol"}],"url":"\/documentation\/yababa\/pushnotificationinteractorprotocol"},"doc://com.yababaGmbH.yababa/documentation/Yababa/PushNotificationInteractorProtocol/getUserPushSubscriptionStatus()":{"navigatorTitle":[{"kind":"identifier","text":"getUserPushSubscriptionStatus"}],"role":"symbol","title":"getUserPushSubscriptionStatus()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getUserPushSubscriptionStatus"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"SubscriptionStatus","preciseIdentifier":"c:@M@Yababa@E@SubscriptionStatus"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/PushNotificationInteractorProtocol\/getUserPushSubscriptionStatus()","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/yababa\/pushnotificationinteractorprotocol\/getuserpushsubscriptionstatus()"},"doc://com.yababaGmbH.yababa/documentation/Yababa/PushNotificationInteractorProtocol/promptEnablePushNotificationFromSettings()":{"navigatorTitle":[{"kind":"identifier","text":"promptEnablePushNotificationFromSettings"}],"role":"symbol","title":"promptEnablePushNotificationFromSettings()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"promptEnablePushNotificationFromSettings"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/PushNotificationInteractorProtocol\/promptEnablePushNotificationFromSettings()","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/yababa\/pushnotificationinteractorprotocol\/promptenablepushnotificationfromsettings()"},"doc://com.yababaGmbH.yababa/documentation/Yababa/PushNotificationInteractorProtocol/navigateToDeviceSettings()":{"navigatorTitle":[{"kind":"identifier","text":"navigateToDeviceSettings"}],"role":"symbol","title":"navigateToDeviceSettings()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"navigateToDeviceSettings"},{"kind":"text","text":"()"}],"abstract":[{"type":"text","text":"Open App in device settings for user to enable push notifications for Yababa"}],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/PushNotificationInteractorProtocol\/navigateToDeviceSettings()","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/yababa\/pushnotificationinteractorprotocol\/navigatetodevicesettings()"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Protocol"},{"op":"replace","path":"\/metadata\/title","value":"PushNotificationInteractorProtocol"},{"op":"replace","path":"\/metadata\/symbolKind","value":"protocol"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"PushNotificationInteractorProtocol"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"PushNotificationInteractorProtocol"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/PushNotificationInteractorProtocol\/getDevicePushNotificationAuthStatus(completion:)","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/PushNotificationInteractorProtocol\/getUserPushSubscriptionStatus()","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/PushNotificationInteractorProtocol\/navigateToDeviceSettings()","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/PushNotificationInteractorProtocol\/promptEnablePushNotificationFromSettings()","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/PushNotificationInteractorProtocol\/promptHardOptIn()"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/PushNotificationInteractor"],"kind":"relationships","title":"Conforming Types","type":"conformingTypes"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"PushNotificationInteractorProtocol"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1PushNotificationInteractor\/title","value":"PushNotificationInteractor"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1PushNotificationInteractor\/fragments","value":[{"kind":"identifier","text":"PushNotificationInteractor"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1PushNotificationInteractorProtocol~1getDevicePushNotificationAuthStatus(completion:)\/title","value":"getDevicePushNotificationAuthStatusWithCompletion:"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1PushNotificationInteractorProtocol~1getDevicePushNotificationAuthStatus(completion:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"getDevicePushNotificationAuthStatusWithCompletion:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1PushNotificationInteractorProtocol~1promptHardOptIn()\/title","value":"promptHardOptIn"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1PushNotificationInteractorProtocol~1promptHardOptIn()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"promptHardOptIn"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1PushNotificationInteractorProtocol\/title","value":"PushNotificationInteractorProtocol"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1PushNotificationInteractorProtocol\/fragments","value":[{"kind":"identifier","text":"PushNotificationInteractorProtocol"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1PushNotificationInteractorProtocol~1getUserPushSubscriptionStatus()\/title","value":"getUserPushSubscriptionStatus"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1PushNotificationInteractorProtocol~1getUserPushSubscriptionStatus()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"getUserPushSubscriptionStatus"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1PushNotificationInteractorProtocol~1promptEnablePushNotificationFromSettings()\/title","value":"promptEnablePushNotificationFromSettings"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1PushNotificationInteractorProtocol~1promptEnablePushNotificationFromSettings()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"promptEnablePushNotificationFromSettings"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1PushNotificationInteractorProtocol~1navigateToDeviceSettings()\/title","value":"navigateToDeviceSettings"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1PushNotificationInteractorProtocol~1navigateToDeviceSettings()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"navigateToDeviceSettings"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}