{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PushNotificationInteractor"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/yababa\/pushnotificationinteractor"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/yababa\/pushnotificationinteractor"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.yababaGmbH.yababa\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.yababaGmbH.yababa\/objc(pl)NSObject","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/PushNotificationInteractorProtocol","doc:\/\/com.yababaGmbH.yababa\/12SkeletonView17AssociatedObjectsP","doc:\/\/com.yababaGmbH.yababa\/s7CVarArgP","doc:\/\/com.yababaGmbH.yababa\/s28CustomDebugStringConvertibleP","doc:\/\/com.yababaGmbH.yababa\/s23CustomStringConvertibleP","doc:\/\/com.yababaGmbH.yababa\/SQ","doc:\/\/com.yababaGmbH.yababa\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/PushNotificationInteractor","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/PushNotificationInteractor\/getDevicePushNotificationAuthStatus(completion:)","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/PushNotificationInteractor\/getUserPushSubscriptionStatus()","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/PushNotificationInteractor\/navigateToDeviceSettings()","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/PushNotificationInteractor\/promptEnablePushNotificationFromSettings()","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/PushNotificationInteractor\/promptHardOptIn()"]}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PushNotificationInteractor"}],"title":"PushNotificationInteractor","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@Yababa@objc(cs)PushNotificationInteractor","modules":[{"name":"Yababa"}],"navigatorTitle":[{"kind":"identifier","text":"PushNotificationInteractor"}]},"hierarchy":{"paths":[["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa"]]},"references":{"doc://com.yababaGmbH.yababa/documentation/Yababa/PushNotificationInteractor/init":{"role":"symbol","title":"init","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/PushNotificationInteractor\/init","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"init"}],"url":"\/documentation\/yababa\/pushnotificationinteractor\/init"},"doc://com.yababaGmbH.yababa/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(cs)NSObject"},"doc://com.yababaGmbH.yababa/documentation/Yababa/PushNotificationInteractor/getUserPushSubscriptionStatus()":{"role":"symbol","title":"getUserPushSubscriptionStatus()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getUserPushSubscriptionStatus"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"SubscriptionStatus","preciseIdentifier":"c:@M@Yababa@E@SubscriptionStatus"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/PushNotificationInteractor\/getUserPushSubscriptionStatus()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"getUserPushSubscriptionStatus"}],"url":"\/documentation\/yababa\/pushnotificationinteractor\/getuserpushsubscriptionstatus()"},"doc://com.yababaGmbH.yababa/documentation/Yababa/PushNotificationInteractor/navigateToDeviceSettings()":{"role":"symbol","title":"navigateToDeviceSettings()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"navigateToDeviceSettings"},{"kind":"text","text":"()"}],"abstract":[{"type":"text","text":"Open App in device settings for user to enable push notifications for Yababa"}],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/PushNotificationInteractor\/navigateToDeviceSettings()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"navigateToDeviceSettings"}],"url":"\/documentation\/yababa\/pushnotificationinteractor\/navigatetodevicesettings()"},"doc://com.yababaGmbH.yababa/documentation/Yababa/PushNotificationInteractor/promptHardOptIn()":{"role":"symbol","title":"promptHardOptIn()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"promptHardOptIn"},{"kind":"text","text":"()"}],"abstract":[{"type":"text","text":"Apple native push notification permission prompt"}],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/PushNotificationInteractor\/promptHardOptIn()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"promptHardOptIn"}],"url":"\/documentation\/yababa\/pushnotificationinteractor\/prompthardoptin()"},"doc://com.yababaGmbH.yababa/documentation/Yababa/PushNotificationInteractor/promptEnablePushNotificationFromSettings()":{"role":"symbol","title":"promptEnablePushNotificationFromSettings()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"promptEnablePushNotificationFromSettings"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/PushNotificationInteractor\/promptEnablePushNotificationFromSettings()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"promptEnablePushNotificationFromSettings"}],"url":"\/documentation\/yababa\/pushnotificationinteractor\/promptenablepushnotificationfromsettings()"},"doc://com.yababaGmbH.yababa/12SkeletonView17AssociatedObjectsP":{"type":"unresolvable","title":"SkeletonView.AssociatedObjects","identifier":"doc:\/\/com.yababaGmbH.yababa\/12SkeletonView17AssociatedObjectsP"},"doc://com.yababaGmbH.yababa/documentation/Yababa/PushNotificationInteractorProtocol":{"role":"symbol","title":"PushNotificationInteractorProtocol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"PushNotificationInteractorProtocol"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/PushNotificationInteractorProtocol","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PushNotificationInteractorProtocol"}],"url":"\/documentation\/yababa\/pushnotificationinteractorprotocol"},"doc://com.yababaGmbH.yababa/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.yababaGmbH.yababa\/s28CustomDebugStringConvertibleP"},"doc://com.yababaGmbH.yababa/documentation/Yababa":{"role":"collection","title":"Yababa","abstract":[{"type":"text","text":"Getting Started"}],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa","kind":"symbol","type":"topic","url":"\/documentation\/yababa"},"doc://com.yababaGmbH.yababa/documentation/Yababa/PushNotificationInteractor/getDevicePushNotificationAuthStatus(completion:)":{"role":"symbol","title":"getDevicePushNotificationAuthStatus(completion:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getDevicePushNotificationAuthStatus"},{"kind":"text","text":"("},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": ("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"permissionStatus"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UNAuthorizationStatus","preciseIdentifier":"c:@E@UNAuthorizationStatus"},{"kind":"text","text":") -> ())"}],"abstract":[{"type":"text","text":"Gets the status of app push notifications from the device settings for it"}],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/PushNotificationInteractor\/getDevicePushNotificationAuthStatus(completion:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"getDevicePushNotificationAuthStatusWithCompletion:"}],"url":"\/documentation\/yababa\/pushnotificationinteractor\/getdevicepushnotificationauthstatus(completion:)"},"doc://com.yababaGmbH.yababa/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.yababaGmbH.yababa\/s23CustomStringConvertibleP"},"doc://com.yababaGmbH.yababa/documentation/Yababa/PushNotificationInteractor":{"role":"symbol","title":"PushNotificationInteractor","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PushNotificationInteractor"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/PushNotificationInteractor","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PushNotificationInteractor"}],"url":"\/documentation\/yababa\/pushnotificationinteractor"},"doc://com.yababaGmbH.yababa/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.yababaGmbH.yababa\/SH"},"doc://com.yababaGmbH.yababa/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.yababaGmbH.yababa\/SQ"},"doc://com.yababaGmbH.yababa/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.yababaGmbH.yababa\/s7CVarArgP"},"doc://com.yababaGmbH.yababa/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)NSObject"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"PushNotificationInteractor"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"PushNotificationInteractor"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"PushNotificationInteractor"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/PushNotificationInteractor\/getDevicePushNotificationAuthStatus(completion:)","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/PushNotificationInteractor\/getUserPushSubscriptionStatus()","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/PushNotificationInteractor\/init","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/PushNotificationInteractor\/navigateToDeviceSettings()","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/PushNotificationInteractor\/promptEnablePushNotificationFromSettings()","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/PushNotificationInteractor\/promptHardOptIn()"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.yababaGmbH.yababa\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/PushNotificationInteractorProtocol"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"PushNotificationInteractor"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1PushNotificationInteractor~1getUserPushSubscriptionStatus()\/title","value":"getUserPushSubscriptionStatus"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1PushNotificationInteractor~1getUserPushSubscriptionStatus()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"getUserPushSubscriptionStatus"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1PushNotificationInteractor~1navigateToDeviceSettings()\/title","value":"navigateToDeviceSettings"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1PushNotificationInteractor~1navigateToDeviceSettings()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"navigateToDeviceSettings"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1PushNotificationInteractor~1promptHardOptIn()\/title","value":"promptHardOptIn"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1PushNotificationInteractor~1promptHardOptIn()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"promptHardOptIn"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1PushNotificationInteractor~1promptEnablePushNotificationFromSettings()\/title","value":"promptEnablePushNotificationFromSettings"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1PushNotificationInteractor~1promptEnablePushNotificationFromSettings()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"promptEnablePushNotificationFromSettings"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1PushNotificationInteractorProtocol\/title","value":"PushNotificationInteractorProtocol"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1PushNotificationInteractorProtocol\/fragments","value":[{"kind":"identifier","text":"PushNotificationInteractorProtocol"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1PushNotificationInteractor~1getDevicePushNotificationAuthStatus(completion:)\/title","value":"getDevicePushNotificationAuthStatusWithCompletion:"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1PushNotificationInteractor~1getDevicePushNotificationAuthStatus(completion:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"getDevicePushNotificationAuthStatusWithCompletion:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1PushNotificationInteractor\/title","value":"PushNotificationInteractor"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1PushNotificationInteractor\/fragments","value":[{"kind":"identifier","text":"PushNotificationInteractor"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}