{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"QuantityInCartDelegate"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/yababa\/quantityincartdelegate"],"traits":[{"interfaceLanguage":"swift"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.yababaGmbH.yababa\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ProductCollectionCell","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ProductDetailsSceneViewController","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ProductTableCell"],"kind":"relationships","title":"Conforming Types","type":"conformingTypes"}],"identifier":{"url":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/QuantityInCartDelegate","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/QuantityInCartDelegate\/onUserTappedAdd()","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/QuantityInCartDelegate\/onUserTappedRemove()"]}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"QuantityInCartDelegate"}],"title":"QuantityInCartDelegate","roleHeading":"Protocol","role":"symbol","symbolKind":"protocol","externalID":"s:6Yababa22QuantityInCartDelegateP","modules":[{"name":"Yababa"}],"navigatorTitle":[{"kind":"identifier","text":"QuantityInCartDelegate"}]},"hierarchy":{"paths":[["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa"]]},"references":{"doc://com.yababaGmbH.yababa/documentation/Yababa":{"role":"collection","title":"Yababa","abstract":[{"type":"text","text":"Getting Started"}],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa","kind":"symbol","type":"topic","url":"\/documentation\/yababa"},"doc://com.yababaGmbH.yababa/documentation/Yababa/ProductDetailsSceneViewController":{"role":"symbol","title":"ProductDetailsSceneViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ProductDetailsSceneViewController"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ProductDetailsSceneViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ProductDetailsSceneViewController"}],"url":"\/documentation\/yababa\/productdetailssceneviewcontroller"},"doc://com.yababaGmbH.yababa/documentation/Yababa/QuantityInCartDelegate":{"role":"symbol","title":"QuantityInCartDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"QuantityInCartDelegate"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/QuantityInCartDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"QuantityInCartDelegate"}],"url":"\/documentation\/yababa\/quantityincartdelegate"},"doc://com.yababaGmbH.yababa/documentation/Yababa/QuantityInCartDelegate/onUserTappedRemove()":{"role":"symbol","title":"onUserTappedRemove()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onUserTappedRemove"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/QuantityInCartDelegate\/onUserTappedRemove()","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/yababa\/quantityincartdelegate\/onusertappedremove()"},"doc://com.yababaGmbH.yababa/documentation/Yababa/QuantityInCartDelegate/onUserTappedAdd()":{"role":"symbol","title":"onUserTappedAdd()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onUserTappedAdd"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/QuantityInCartDelegate\/onUserTappedAdd()","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/yababa\/quantityincartdelegate\/onusertappedadd()"},"doc://com.yababaGmbH.yababa/objc(cs)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObject","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(cs)NSObject"},"doc://com.yababaGmbH.yababa/documentation/Yababa/ProductCollectionCell":{"role":"symbol","title":"ProductCollectionCell","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ProductCollectionCell"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ProductCollectionCell","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ProductCollectionCell"}],"url":"\/documentation\/yababa\/productcollectioncell"},"doc://com.yababaGmbH.yababa/documentation/Yababa/ProductTableCell":{"role":"symbol","title":"ProductTableCell","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ProductTableCell"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ProductTableCell","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ProductTableCell"}],"url":"\/documentation\/yababa\/producttablecell"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1ProductDetailsSceneViewController\/title","value":"ProductDetailsSceneViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1ProductDetailsSceneViewController\/fragments","value":[{"kind":"identifier","text":"ProductDetailsSceneViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1ProductCollectionCell\/title","value":"ProductCollectionCell"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1ProductCollectionCell\/fragments","value":[{"kind":"identifier","text":"ProductCollectionCell"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1ProductTableCell\/title","value":"ProductTableCell"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1ProductTableCell\/fragments","value":[{"kind":"identifier","text":"ProductTableCell"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}