{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ReferToFriendController"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/yababa\/refertofriendcontroller"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/yababa\/refertofriendcontroller"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.yababaGmbH.yababa\/objc(cs)UIViewController"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.yababaGmbH.yababa\/objc(pl)NSCoding","doc:\/\/com.yababaGmbH.yababa\/objc(pl)NSExtensionRequestHandling","doc:\/\/com.yababaGmbH.yababa\/objc(pl)NSObject","doc:\/\/com.yababaGmbH.yababa\/12SkeletonView17AssociatedObjectsP","doc:\/\/com.yababaGmbH.yababa\/s7CVarArgP","doc:\/\/com.yababaGmbH.yababa\/s28CustomDebugStringConvertibleP","doc:\/\/com.yababaGmbH.yababa\/s23CustomStringConvertibleP","doc:\/\/com.yababaGmbH.yababa\/SQ","doc:\/\/com.yababaGmbH.yababa\/SH","doc:\/\/com.yababaGmbH.yababa\/s8SendableP","doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIActivityItemsConfigurationProviding","doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIAppearanceContainer","doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIContentContainer","doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIFocusEnvironment","doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIPasteConfigurationSupporting","doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIResponderStandardEditActions","doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIStateRestoring","doc:\/\/com.yababaGmbH.yababa\/objc(pl)UITraitEnvironment","doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIUserActivityRestoring"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ReferToFriendController","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ReferToFriendController\/copyCodeButton","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ReferToFriendController\/referToFriendCodeContainer","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ReferToFriendController\/referToFriendCodeLabel","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ReferToFriendController\/referToFriendDetailsLabel","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ReferToFriendController\/referToFriendHeaderLabel","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ReferToFriendController\/referToFriendShareButton","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ReferToFriendController\/screenItem","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ReferToFriendController\/shareButton","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ReferToFriendController\/termsAndConditionsButton"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ReferToFriendController\/fetchReferralCode()","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ReferToFriendController\/fetchReferralLink()","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ReferToFriendController\/formatReferralMessage(refLink:)","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ReferToFriendController\/hideLoadingForCode()","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ReferToFriendController\/onBack()","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ReferToFriendController\/onCopyCodeAction(_:)","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ReferToFriendController\/onTermsnConditionsAction(_:)","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ReferToFriendController\/postLoadAnalytics()","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ReferToFriendController\/prepareShareAction(_:)","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ReferToFriendController\/setData()","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ReferToFriendController\/setupLocalizedStrings()","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ReferToFriendController\/setupUI()","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ReferToFriendController\/showLoadingForCode()","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ReferToFriendController\/showReferralCode(_:)","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ReferToFriendController\/showShareSheet(message:)","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ReferToFriendController\/viewDidLoad()","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ReferToFriendController\/viewWillAppear(_:)"]}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ReferToFriendController"}],"title":"ReferToFriendController","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@Yababa@objc(cs)ReferToFriendController","modules":[{"name":"Yababa"}],"navigatorTitle":[{"kind":"identifier","text":"ReferToFriendController"}]},"hierarchy":{"paths":[["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa"]]},"references":{"doc://com.yababaGmbH.yababa/objc(pl)UIPasteConfigurationSupporting":{"type":"unresolvable","title":"UIKit.UIPasteConfigurationSupporting","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIPasteConfigurationSupporting"},"doc://com.yababaGmbH.yababa/documentation/Yababa/ReferToFriendController/postLoadAnalytics()":{"role":"symbol","title":"postLoadAnalytics()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"postLoadAnalytics"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ReferToFriendController\/postLoadAnalytics()","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/refertofriendcontroller\/postloadanalytics()"},"doc://com.yababaGmbH.yababa/documentation/Yababa/ReferToFriendController/formatReferralMessage(refLink:)":{"role":"symbol","title":"formatReferralMessage(refLink:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"formatReferralMessage"},{"kind":"text","text":"("},{"kind":"externalParam","text":"refLink"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ReferToFriendController\/formatReferralMessage(refLink:)","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/refertofriendcontroller\/formatreferralmessage(reflink:)"},"doc://com.yababaGmbH.yababa/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.yababaGmbH.yababa\/s7CVarArgP"},"doc://com.yababaGmbH.yababa/objc(cs)UIViewController":{"type":"unresolvable","title":"UIViewController","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(cs)UIViewController"},"doc://com.yababaGmbH.yababa/objc(pl)NSCoding":{"type":"unresolvable","title":"Foundation.NSCoding","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)NSCoding"},"doc://com.yababaGmbH.yababa/documentation/Yababa/ReferToFriendController/showLoadingForCode()":{"role":"symbol","title":"showLoadingForCode()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"showLoadingForCode"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ReferToFriendController\/showLoadingForCode()","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/refertofriendcontroller\/showloadingforcode()"},"doc://com.yababaGmbH.yababa/documentation/Yababa/ReferToFriendController/termsAndConditionsButton":{"role":"symbol","title":"termsAndConditionsButton","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"termsAndConditionsButton"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIButton","preciseIdentifier":"c:objc(cs)UIButton"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ReferToFriendController\/termsAndConditionsButton","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"termsAndConditionsButton"}],"url":"\/documentation\/yababa\/refertofriendcontroller\/termsandconditionsbutton"},"doc://com.yababaGmbH.yababa/documentation/Yababa/ReferToFriendController/onCopyCodeAction(_:)":{"role":"symbol","title":"onCopyCodeAction(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onCopyCodeAction"},{"kind":"text","text":"("},{"kind":"keyword","text":"Any"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ReferToFriendController\/onCopyCodeAction(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"onCopyCodeAction:"}],"url":"\/documentation\/yababa\/refertofriendcontroller\/oncopycodeaction(_:)"},"doc://com.yababaGmbH.yababa/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.yababaGmbH.yababa\/SH"},"doc://com.yababaGmbH.yababa/objc(pl)UIStateRestoring":{"type":"unresolvable","title":"UIKit.UIStateRestoring","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIStateRestoring"},"doc://com.yababaGmbH.yababa/objc(pl)UIFocusEnvironment":{"type":"unresolvable","title":"UIKit.UIFocusEnvironment","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIFocusEnvironment"},"doc://com.yababaGmbH.yababa/documentation/Yababa/ReferToFriendController/setupUI()":{"role":"symbol","title":"setupUI()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setupUI"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ReferToFriendController\/setupUI()","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/refertofriendcontroller\/setupui()"},"doc://com.yababaGmbH.yababa/documentation/Yababa/ReferToFriendController/onTermsnConditionsAction(_:)":{"role":"symbol","title":"onTermsnConditionsAction(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onTermsnConditionsAction"},{"kind":"text","text":"("},{"kind":"keyword","text":"Any"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ReferToFriendController\/onTermsnConditionsAction(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"onTermsnConditionsAction:"}],"url":"\/documentation\/yababa\/refertofriendcontroller\/ontermsnconditionsaction(_:)"},"doc://com.yababaGmbH.yababa/documentation/Yababa":{"role":"collection","title":"Yababa","abstract":[{"type":"text","text":"Getting Started"}],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa","kind":"symbol","type":"topic","url":"\/documentation\/yababa"},"doc://com.yababaGmbH.yababa/documentation/Yababa/ReferToFriendController/fetchReferralLink()":{"role":"symbol","title":"fetchReferralLink()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"fetchReferralLink"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ReferToFriendController\/fetchReferralLink()","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/refertofriendcontroller\/fetchreferrallink()"},"doc://com.yababaGmbH.yababa/documentation/Yababa/ReferToFriendController/showReferralCode(_:)":{"role":"symbol","title":"showReferralCode(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"showReferralCode"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ReferToFriendController\/showReferralCode(_:)","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/refertofriendcontroller\/showreferralcode(_:)"},"doc://com.yababaGmbH.yababa/objc(pl)UIResponderStandardEditActions":{"type":"unresolvable","title":"UIKit.UIResponderStandardEditActions","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIResponderStandardEditActions"},"doc://com.yababaGmbH.yababa/documentation/Yababa/ReferToFriendController/prepareShareAction(_:)":{"role":"symbol","title":"prepareShareAction(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"prepareShareAction"},{"kind":"text","text":"("},{"kind":"keyword","text":"Any"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ReferToFriendController\/prepareShareAction(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"prepareShareAction:"}],"url":"\/documentation\/yababa\/refertofriendcontroller\/prepareshareaction(_:)"},"doc://com.yababaGmbH.yababa/documentation/Yababa/ReferToFriendController/fetchReferralCode()":{"role":"symbol","title":"fetchReferralCode()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"fetchReferralCode"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ReferToFriendController\/fetchReferralCode()","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/refertofriendcontroller\/fetchreferralcode()"},"doc://com.yababaGmbH.yababa/documentation/Yababa/ReferToFriendController/viewDidLoad()":{"role":"symbol","title":"viewDidLoad()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"viewDidLoad"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ReferToFriendController\/viewDidLoad()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"viewDidLoad"}],"url":"\/documentation\/yababa\/refertofriendcontroller\/viewdidload()"},"doc://com.yababaGmbH.yababa/objc(pl)UIContentContainer":{"type":"unresolvable","title":"UIKit.UIContentContainer","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIContentContainer"},"doc://com.yababaGmbH.yababa/documentation/Yababa/ReferToFriendController/shareButton":{"role":"symbol","title":"shareButton","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"shareButton"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIButton","preciseIdentifier":"c:objc(cs)UIButton"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ReferToFriendController\/shareButton","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"shareButton"}],"url":"\/documentation\/yababa\/refertofriendcontroller\/sharebutton"},"doc://com.yababaGmbH.yababa/documentation/Yababa/ReferToFriendController/hideLoadingForCode()":{"role":"symbol","title":"hideLoadingForCode()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"hideLoadingForCode"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ReferToFriendController\/hideLoadingForCode()","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/refertofriendcontroller\/hideloadingforcode()"},"doc://com.yababaGmbH.yababa/documentation/Yababa/ReferToFriendController/screenItem":{"role":"symbol","title":"screenItem","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"screenItem"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ScreenItem","preciseIdentifier":"s:6Yababa10ScreenItemC"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ReferToFriendController\/screenItem","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/refertofriendcontroller\/screenitem"},"doc://com.yababaGmbH.yababa/documentation/Yababa/ReferToFriendController/referToFriendDetailsLabel":{"role":"symbol","title":"referToFriendDetailsLabel","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"referToFriendDetailsLabel"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UILabel","preciseIdentifier":"c:objc(cs)UILabel"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ReferToFriendController\/referToFriendDetailsLabel","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"referToFriendDetailsLabel"}],"url":"\/documentation\/yababa\/refertofriendcontroller\/refertofrienddetailslabel"},"doc://com.yababaGmbH.yababa/objc(pl)UITraitEnvironment":{"type":"unresolvable","title":"UIKit.UITraitEnvironment","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)UITraitEnvironment"},"doc://com.yababaGmbH.yababa/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)NSObject"},"doc://com.yababaGmbH.yababa/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.yababaGmbH.yababa\/s28CustomDebugStringConvertibleP"},"doc://com.yababaGmbH.yababa/documentation/Yababa/ReferToFriendController/initWithCoder:":{"role":"symbol","title":"initWithCoder:","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithCoder:"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ReferToFriendController\/initWithCoder:","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithCoder:"}],"url":"\/documentation\/yababa\/refertofriendcontroller\/initwithcoder:"},"doc://com.yababaGmbH.yababa/documentation/Yababa/ReferToFriendController/initWithNibName:bundle:":{"role":"symbol","title":"initWithNibName:bundle:","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithNibName:bundle:"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ReferToFriendController\/initWithNibName:bundle:","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithNibName:bundle:"}],"url":"\/documentation\/yababa\/refertofriendcontroller\/initwithnibname:bundle:"},"doc://com.yababaGmbH.yababa/objc(pl)UIAppearanceContainer":{"type":"unresolvable","title":"UIKit.UIAppearanceContainer","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIAppearanceContainer"},"doc://com.yababaGmbH.yababa/documentation/Yababa/ReferToFriendController/setupLocalizedStrings()":{"role":"symbol","title":"setupLocalizedStrings()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setupLocalizedStrings"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ReferToFriendController\/setupLocalizedStrings()","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/refertofriendcontroller\/setuplocalizedstrings()"},"doc://com.yababaGmbH.yababa/objc(pl)NSExtensionRequestHandling":{"type":"unresolvable","title":"Foundation.NSExtensionRequestHandling","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)NSExtensionRequestHandling"},"doc://com.yababaGmbH.yababa/documentation/Yababa/ReferToFriendController/referToFriendShareButton":{"role":"symbol","title":"referToFriendShareButton","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"referToFriendShareButton"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIButton","preciseIdentifier":"c:objc(cs)UIButton"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ReferToFriendController\/referToFriendShareButton","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"referToFriendShareButton"}],"url":"\/documentation\/yababa\/refertofriendcontroller\/refertofriendsharebutton"},"doc://com.yababaGmbH.yababa/documentation/Yababa/ReferToFriendController/onBack()":{"role":"symbol","title":"onBack()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onBack"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ReferToFriendController\/onBack()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"onBack"}],"url":"\/documentation\/yababa\/refertofriendcontroller\/onback()"},"doc://com.yababaGmbH.yababa/documentation/Yababa/ReferToFriendController/copyCodeButton":{"role":"symbol","title":"copyCodeButton","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"copyCodeButton"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIButton","preciseIdentifier":"c:objc(cs)UIButton"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ReferToFriendController\/copyCodeButton","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"copyCodeButton"}],"url":"\/documentation\/yababa\/refertofriendcontroller\/copycodebutton"},"doc://com.yababaGmbH.yababa/documentation/Yababa/ReferToFriendController/referToFriendHeaderLabel":{"role":"symbol","title":"referToFriendHeaderLabel","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"referToFriendHeaderLabel"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UILabel","preciseIdentifier":"c:objc(cs)UILabel"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ReferToFriendController\/referToFriendHeaderLabel","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"referToFriendHeaderLabel"}],"url":"\/documentation\/yababa\/refertofriendcontroller\/refertofriendheaderlabel"},"doc://com.yababaGmbH.yababa/documentation/Yababa/ReferToFriendController/referToFriendCodeContainer":{"role":"symbol","title":"referToFriendCodeContainer","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"referToFriendCodeContainer"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ReferToFriendController\/referToFriendCodeContainer","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"referToFriendCodeContainer"}],"url":"\/documentation\/yababa\/refertofriendcontroller\/refertofriendcodecontainer"},"doc://com.yababaGmbH.yababa/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.yababaGmbH.yababa\/s23CustomStringConvertibleP"},"doc://com.yababaGmbH.yababa/documentation/Yababa/ReferToFriendController/setData()":{"role":"symbol","title":"setData()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setData"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ReferToFriendController\/setData()","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/refertofriendcontroller\/setdata()"},"doc://com.yababaGmbH.yababa/documentation/Yababa/ReferToFriendController/viewWillAppear(_:)":{"role":"symbol","title":"viewWillAppear(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"viewWillAppear"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ReferToFriendController\/viewWillAppear(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"viewWillAppear:"}],"url":"\/documentation\/yababa\/refertofriendcontroller\/viewwillappear(_:)"},"doc://com.yababaGmbH.yababa/documentation/Yababa/ReferToFriendController/referToFriendCodeLabel":{"role":"symbol","title":"referToFriendCodeLabel","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"referToFriendCodeLabel"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UILabel","preciseIdentifier":"c:objc(cs)UILabel"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ReferToFriendController\/referToFriendCodeLabel","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"referToFriendCodeLabel"}],"url":"\/documentation\/yababa\/refertofriendcontroller\/refertofriendcodelabel"},"doc://com.yababaGmbH.yababa/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.yababaGmbH.yababa\/SQ"},"doc://com.yababaGmbH.yababa/objc(pl)UIUserActivityRestoring":{"type":"unresolvable","title":"UIKit.UIUserActivityRestoring","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIUserActivityRestoring"},"doc://com.yababaGmbH.yababa/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/com.yababaGmbH.yababa\/s8SendableP"},"doc://com.yababaGmbH.yababa/documentation/Yababa/ReferToFriendController":{"role":"symbol","title":"ReferToFriendController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ReferToFriendController"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ReferToFriendController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ReferToFriendController"}],"url":"\/documentation\/yababa\/refertofriendcontroller"},"doc://com.yababaGmbH.yababa/documentation/Yababa/ReferToFriendController/showShareSheet(message:)":{"role":"symbol","title":"showShareSheet(message:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"showShareSheet"},{"kind":"text","text":"("},{"kind":"externalParam","text":"message"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ReferToFriendController\/showShareSheet(message:)","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/refertofriendcontroller\/showsharesheet(message:)"},"doc://com.yababaGmbH.yababa/12SkeletonView17AssociatedObjectsP":{"type":"unresolvable","title":"SkeletonView.AssociatedObjects","identifier":"doc:\/\/com.yababaGmbH.yababa\/12SkeletonView17AssociatedObjectsP"},"doc://com.yababaGmbH.yababa/objc(pl)UIActivityItemsConfigurationProviding":{"type":"unresolvable","title":"UIKit.UIActivityItemsConfigurationProviding","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIActivityItemsConfigurationProviding"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"ReferToFriendController"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"ReferToFriendController"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"ReferToFriendController"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ReferToFriendController\/copyCodeButton","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ReferToFriendController\/referToFriendCodeContainer","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ReferToFriendController\/referToFriendCodeLabel","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ReferToFriendController\/referToFriendDetailsLabel","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ReferToFriendController\/referToFriendHeaderLabel","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ReferToFriendController\/referToFriendShareButton","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ReferToFriendController\/shareButton","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ReferToFriendController\/termsAndConditionsButton"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ReferToFriendController\/initWithCoder:","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ReferToFriendController\/initWithNibName:bundle:","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ReferToFriendController\/onBack()","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ReferToFriendController\/onCopyCodeAction(_:)","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ReferToFriendController\/onTermsnConditionsAction(_:)","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ReferToFriendController\/prepareShareAction(_:)","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ReferToFriendController\/viewDidLoad()","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ReferToFriendController\/viewWillAppear(_:)"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.yababaGmbH.yababa\/objc(cs)UIViewController"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"ReferToFriendController"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1ReferToFriendController~1termsAndConditionsButton\/title","value":"termsAndConditionsButton"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1ReferToFriendController~1termsAndConditionsButton\/fragments","value":[{"kind":"identifier","text":"termsAndConditionsButton"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1ReferToFriendController~1onCopyCodeAction(_:)\/title","value":"onCopyCodeAction:"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1ReferToFriendController~1onCopyCodeAction(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onCopyCodeAction:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1ReferToFriendController~1onTermsnConditionsAction(_:)\/title","value":"onTermsnConditionsAction:"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1ReferToFriendController~1onTermsnConditionsAction(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onTermsnConditionsAction:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1ReferToFriendController~1prepareShareAction(_:)\/title","value":"prepareShareAction:"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1ReferToFriendController~1prepareShareAction(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"prepareShareAction:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1ReferToFriendController~1viewDidLoad()\/title","value":"viewDidLoad"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1ReferToFriendController~1viewDidLoad()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"viewDidLoad"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1ReferToFriendController~1shareButton\/title","value":"shareButton"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1ReferToFriendController~1shareButton\/fragments","value":[{"kind":"identifier","text":"shareButton"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1ReferToFriendController~1referToFriendDetailsLabel\/title","value":"referToFriendDetailsLabel"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1ReferToFriendController~1referToFriendDetailsLabel\/fragments","value":[{"kind":"identifier","text":"referToFriendDetailsLabel"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1ReferToFriendController~1referToFriendShareButton\/title","value":"referToFriendShareButton"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1ReferToFriendController~1referToFriendShareButton\/fragments","value":[{"kind":"identifier","text":"referToFriendShareButton"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1ReferToFriendController~1onBack()\/title","value":"onBack"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1ReferToFriendController~1onBack()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onBack"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1ReferToFriendController~1copyCodeButton\/title","value":"copyCodeButton"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1ReferToFriendController~1copyCodeButton\/fragments","value":[{"kind":"identifier","text":"copyCodeButton"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1ReferToFriendController~1referToFriendHeaderLabel\/title","value":"referToFriendHeaderLabel"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1ReferToFriendController~1referToFriendHeaderLabel\/fragments","value":[{"kind":"identifier","text":"referToFriendHeaderLabel"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1ReferToFriendController~1referToFriendCodeContainer\/title","value":"referToFriendCodeContainer"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1ReferToFriendController~1referToFriendCodeContainer\/fragments","value":[{"kind":"identifier","text":"referToFriendCodeContainer"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1ReferToFriendController~1viewWillAppear(_:)\/title","value":"viewWillAppear:"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1ReferToFriendController~1viewWillAppear(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"viewWillAppear:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1ReferToFriendController~1referToFriendCodeLabel\/title","value":"referToFriendCodeLabel"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1ReferToFriendController~1referToFriendCodeLabel\/fragments","value":[{"kind":"identifier","text":"referToFriendCodeLabel"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1ReferToFriendController\/title","value":"ReferToFriendController"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1ReferToFriendController\/fragments","value":[{"kind":"identifier","text":"ReferToFriendController"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}