{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"Renderable"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/yababa\/renderable"],"traits":[{"interfaceLanguage":"swift"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CartProgressView","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/TileProduct","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/YButton"],"kind":"relationships","title":"Conforming Types","type":"conformingTypes"}],"identifier":{"url":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/Renderable","interfaceLanguage":"swift"},"topicSections":[{"title":"Associated Types","identifiers":["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/Renderable\/ViewModel"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/Renderable\/render(vm:)"]}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"Renderable"}],"title":"Renderable","roleHeading":"Protocol","role":"symbol","symbolKind":"protocol","externalID":"s:6Yababa10RenderableP","modules":[{"name":"Yababa"}],"navigatorTitle":[{"kind":"identifier","text":"Renderable"}]},"hierarchy":{"paths":[["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa"]]},"references":{"doc://com.yababaGmbH.yababa/documentation/Yababa/Renderable/render(vm:)":{"role":"symbol","title":"render(vm:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"render"},{"kind":"text","text":"("},{"kind":"externalParam","text":"vm"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ViewModel","preciseIdentifier":"s:6Yababa10RenderableP9ViewModelQa"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/Renderable\/render(vm:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/yababa\/renderable\/render(vm:)"},"doc://com.yababaGmbH.yababa/documentation/Yababa":{"role":"collection","title":"Yababa","abstract":[{"type":"text","text":"Getting Started"}],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa","kind":"symbol","type":"topic","url":"\/documentation\/yababa"},"doc://com.yababaGmbH.yababa/documentation/Yababa/CartProgressView":{"role":"symbol","title":"CartProgressView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CartProgressView"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CartProgressView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CartProgressView"}],"url":"\/documentation\/yababa\/cartprogressview"},"doc://com.yababaGmbH.yababa/documentation/Yababa/Renderable/ViewModel":{"role":"symbol","title":"ViewModel","fragments":[{"kind":"keyword","text":"associatedtype"},{"kind":"text","text":" "},{"kind":"identifier","text":"ViewModel"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/Renderable\/ViewModel","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/yababa\/renderable\/viewmodel"},"doc://com.yababaGmbH.yababa/documentation/Yababa/TileProduct":{"role":"symbol","title":"TileProduct","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TileProduct"}],"abstract":[{"type":"text","text":"WARNING: Not finished. Example implementation for component with Renderable"}],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/TileProduct","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"TileProduct"}],"url":"\/documentation\/yababa\/tileproduct"},"doc://com.yababaGmbH.yababa/documentation/Yababa/Renderable":{"role":"symbol","title":"Renderable","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"Renderable"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/Renderable","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Renderable"}],"url":"\/documentation\/yababa\/renderable"},"doc://com.yababaGmbH.yababa/documentation/Yababa/YButton":{"role":"symbol","title":"YButton","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"YButton"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/YButton","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"YButton"}],"url":"\/documentation\/yababa\/ybutton"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1CartProgressView\/title","value":"CartProgressView"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1CartProgressView\/fragments","value":[{"kind":"identifier","text":"CartProgressView"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1TileProduct\/title","value":"TileProduct"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1TileProduct\/fragments","value":[{"kind":"identifier","text":"TileProduct"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1YButton\/title","value":"YButton"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1YButton\/fragments","value":[{"kind":"identifier","text":"YButton"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}