{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SharedData"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/yababa\/shareddata"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/yababa\/shareddata"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.yababaGmbH.yababa\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.yababaGmbH.yababa\/objc(pl)CLLocationManagerDelegate","doc:\/\/com.yababaGmbH.yababa\/objc(pl)NSObject","doc:\/\/com.yababaGmbH.yababa\/12SkeletonView17AssociatedObjectsP","doc:\/\/com.yababaGmbH.yababa\/s7CVarArgP","doc:\/\/com.yababaGmbH.yababa\/s28CustomDebugStringConvertibleP","doc:\/\/com.yababaGmbH.yababa\/s23CustomStringConvertibleP","doc:\/\/com.yababaGmbH.yababa\/SQ","doc:\/\/com.yababaGmbH.yababa\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/SharedData","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/SharedData\/apiVersion","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/SharedData\/appRequiresUpdate","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/SharedData\/currentUser","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/SharedData\/currentViewController","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/SharedData\/dateFormat","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/SharedData\/emailKey","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/SharedData\/internetView","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/SharedData\/isIPhone","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/SharedData\/isLocationUpdated","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/SharedData\/isProfileUpdated","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/SharedData\/locationManager","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/SharedData\/lostInternetConnection","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/SharedData\/navigationBarHeight","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/SharedData\/screenSize","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/SharedData\/selectedIndex","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/SharedData\/serverUrl","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/SharedData\/statusBar","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/SharedData\/statusBarHeight","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/SharedData\/userInfo","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/SharedData\/waitingView"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/SharedData\/archiveIn()","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/SharedData\/deleteChache()","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/SharedData\/getCountryCode()","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/SharedData\/hideWaitingView()","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/SharedData\/internetIsReachable()","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/SharedData\/nsStringIsValidEmail(_:)","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/SharedData\/showWaitingView()","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/SharedData\/unarchiveIn()"]},{"title":"Type Methods","identifiers":["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/SharedData\/getInstance()"]}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SharedData"}],"title":"SharedData","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:objc(cs)SharedData","modules":[{"name":"Yababa"}],"navigatorTitle":[{"kind":"identifier","text":"SharedData"}]},"hierarchy":{"paths":[["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa"]]},"references":{"doc://com.yababaGmbH.yababa/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.yababaGmbH.yababa\/s28CustomDebugStringConvertibleP"},"doc://com.yababaGmbH.yababa/documentation/Yababa/SharedData/emailKey":{"role":"symbol","title":"emailKey","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"emailKey"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/SharedData\/emailKey","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"emailKey"}],"url":"\/documentation\/yababa\/shareddata\/emailkey"},"doc://com.yababaGmbH.yababa/documentation/Yababa/SharedData/internetIsReachable()":{"role":"symbol","title":"internetIsReachable()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"internetIsReachable"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/SharedData\/internetIsReachable()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"internetIsReachable"}],"url":"\/documentation\/yababa\/shareddata\/internetisreachable()"},"doc://com.yababaGmbH.yababa/documentation/Yababa/SharedData/navigationBarHeight":{"role":"symbol","title":"navigationBarHeight","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"navigationBarHeight"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Float","preciseIdentifier":"s:Sf"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/SharedData\/navigationBarHeight","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"NavigationBarHeight"}],"url":"\/documentation\/yababa\/shareddata\/navigationbarheight"},"doc://com.yababaGmbH.yababa/documentation/Yababa/SharedData/waitingView":{"role":"symbol","title":"waitingView","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"waitingView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"WaitingView","preciseIdentifier":"c:objc(cs)WaitingView"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/SharedData\/waitingView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"waitingView"}],"url":"\/documentation\/yababa\/shareddata\/waitingview"},"doc://com.yababaGmbH.yababa/documentation/Yababa/SharedData/serverUrl":{"role":"symbol","title":"serverUrl","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"serverUrl"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/SharedData\/serverUrl","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"serverUrl"}],"url":"\/documentation\/yababa\/shareddata\/serverurl"},"doc://com.yababaGmbH.yababa/documentation/Yababa/SharedData/showWaitingView()":{"role":"symbol","title":"showWaitingView()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"showWaitingView"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/SharedData\/showWaitingView()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ShowWaitingView"}],"url":"\/documentation\/yababa\/shareddata\/showwaitingview()"},"doc://com.yababaGmbH.yababa/documentation/Yababa/SharedData":{"role":"symbol","title":"SharedData","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SharedData"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/SharedData","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SharedData"}],"url":"\/documentation\/yababa\/shareddata"},"doc://com.yababaGmbH.yababa/documentation/Yababa/SharedData/isProfileUpdated":{"role":"symbol","title":"isProfileUpdated","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isProfileUpdated"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/SharedData\/isProfileUpdated","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"isProfileUpdated"}],"url":"\/documentation\/yababa\/shareddata\/isprofileupdated"},"doc://com.yababaGmbH.yababa/documentation/Yababa/SharedData/currentUser":{"role":"symbol","title":"currentUser","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"currentUser"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UserData","preciseIdentifier":"c:objc(cs)UserData"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/SharedData\/currentUser","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"currentUser"}],"url":"\/documentation\/yababa\/shareddata\/currentuser"},"doc://com.yababaGmbH.yababa/documentation/Yababa/SharedData/screenSize":{"role":"symbol","title":"screenSize","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"screenSize"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGSize","preciseIdentifier":"c:@S@CGSize"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/SharedData\/screenSize","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ScreenSize"}],"url":"\/documentation\/yababa\/shareddata\/screensize"},"doc://com.yababaGmbH.yababa/documentation/Yababa/SharedData/hideWaitingView()":{"role":"symbol","title":"hideWaitingView()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"hideWaitingView"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/SharedData\/hideWaitingView()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HideWaitingView"}],"url":"\/documentation\/yababa\/shareddata\/hidewaitingview()"},"doc://com.yababaGmbH.yababa/documentation/Yababa/SharedData/internetView":{"role":"symbol","title":"internetView","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"internetView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"InternetAlertView","preciseIdentifier":"c:objc(cs)InternetAlertView"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/SharedData\/internetView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"internetView"}],"url":"\/documentation\/yababa\/shareddata\/internetview"},"doc://com.yababaGmbH.yababa/12SkeletonView17AssociatedObjectsP":{"type":"unresolvable","title":"SkeletonView.AssociatedObjects","identifier":"doc:\/\/com.yababaGmbH.yababa\/12SkeletonView17AssociatedObjectsP"},"doc://com.yababaGmbH.yababa/objc(pl)CLLocationManagerDelegate":{"type":"unresolvable","title":"CLLocationManagerDelegate","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)CLLocationManagerDelegate"},"doc://com.yababaGmbH.yababa/documentation/Yababa/SharedData/deleteChache()":{"role":"symbol","title":"deleteChache()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"deleteChache"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/SharedData\/deleteChache()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"deleteChache"}],"url":"\/documentation\/yababa\/shareddata\/deletechache()"},"doc://com.yababaGmbH.yababa/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.yababaGmbH.yababa\/s7CVarArgP"},"doc://com.yababaGmbH.yababa/documentation/Yababa/SharedData/appRequiresUpdate":{"role":"symbol","title":"appRequiresUpdate","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"appRequiresUpdate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/SharedData\/appRequiresUpdate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"appRequiresUpdate"}],"url":"\/documentation\/yababa\/shareddata\/apprequiresupdate"},"doc://com.yababaGmbH.yababa/documentation/Yababa/SharedData/statusBar":{"role":"symbol","title":"statusBar","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"statusBar"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/SharedData\/statusBar","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"statusBar"}],"url":"\/documentation\/yababa\/shareddata\/statusbar"},"doc://com.yababaGmbH.yababa/documentation/Yababa/SharedData/currentViewController":{"role":"symbol","title":"currentViewController","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"currentViewController"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/SharedData\/currentViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"currentViewController"}],"url":"\/documentation\/yababa\/shareddata\/currentviewcontroller"},"doc://com.yababaGmbH.yababa/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)NSObject"},"doc://com.yababaGmbH.yababa/documentation/Yababa/SharedData/getCountryCode()":{"role":"symbol","title":"getCountryCode()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getCountryCode"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/SharedData\/getCountryCode()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"getCountryCode"}],"url":"\/documentation\/yababa\/shareddata\/getcountrycode()"},"doc://com.yababaGmbH.yababa/documentation/Yababa":{"role":"collection","title":"Yababa","abstract":[{"type":"text","text":"Getting Started"}],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa","kind":"symbol","type":"topic","url":"\/documentation\/yababa"},"doc://com.yababaGmbH.yababa/documentation/Yababa/SharedData/lostInternetConnection":{"role":"symbol","title":"lostInternetConnection","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"lostInternetConnection"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/SharedData\/lostInternetConnection","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"lostInternetConnection"}],"url":"\/documentation\/yababa\/shareddata\/lostinternetconnection"},"doc://com.yababaGmbH.yababa/documentation/Yababa/SharedData/statusBarHeight":{"role":"symbol","title":"statusBarHeight","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"statusBarHeight"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Float","preciseIdentifier":"s:Sf"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/SharedData\/statusBarHeight","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"StatusBarHeight"}],"url":"\/documentation\/yababa\/shareddata\/statusbarheight"},"doc://com.yababaGmbH.yababa/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.yababaGmbH.yababa\/SQ"},"doc://com.yababaGmbH.yababa/documentation/Yababa/SharedData/apiVersion":{"role":"symbol","title":"apiVersion","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"apiVersion"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/SharedData\/apiVersion","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"apiVersion"}],"url":"\/documentation\/yababa\/shareddata\/apiversion"},"doc://com.yababaGmbH.yababa/documentation/Yababa/SharedData/dateFormat":{"role":"symbol","title":"dateFormat","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"dateFormat"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/SharedData\/dateFormat","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"dateFormat"}],"url":"\/documentation\/yababa\/shareddata\/dateformat"},"doc://com.yababaGmbH.yababa/documentation/Yababa/SharedData/nsStringIsValidEmail(_:)":{"role":"symbol","title":"nsStringIsValidEmail(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"nsStringIsValidEmail"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"!) -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/SharedData\/nsStringIsValidEmail(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"NSStringIsValidEmail:"}],"url":"\/documentation\/yababa\/shareddata\/nsstringisvalidemail(_:)"},"doc://com.yababaGmbH.yababa/documentation/Yababa/SharedData/unarchiveIn()":{"role":"symbol","title":"unarchiveIn()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"unarchiveIn"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/SharedData\/unarchiveIn()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"unarchiveIn"}],"url":"\/documentation\/yababa\/shareddata\/unarchivein()"},"doc://com.yababaGmbH.yababa/documentation/Yababa/SharedData/locationManager":{"role":"symbol","title":"locationManager","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"locationManager"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CLLocationManager","preciseIdentifier":"c:objc(cs)CLLocationManager"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/SharedData\/locationManager","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"LocationManager"}],"url":"\/documentation\/yababa\/shareddata\/locationmanager"},"doc://com.yababaGmbH.yababa/documentation/Yababa/SharedData/getInstance()":{"role":"symbol","title":"getInstance()","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getInstance"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"SharedData","preciseIdentifier":"c:objc(cs)SharedData"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/SharedData\/getInstance()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"getInstance"}],"url":"\/documentation\/yababa\/shareddata\/getinstance()"},"doc://com.yababaGmbH.yababa/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(cs)NSObject"},"doc://com.yababaGmbH.yababa/documentation/Yababa/SharedData/selectedIndex":{"role":"symbol","title":"selectedIndex","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"selectedIndex"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/SharedData\/selectedIndex","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"selectedIndex"}],"url":"\/documentation\/yababa\/shareddata\/selectedindex"},"doc://com.yababaGmbH.yababa/documentation/Yababa/SharedData/archiveIn()":{"role":"symbol","title":"archiveIn()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"archiveIn"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/SharedData\/archiveIn()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"archiveIn"}],"url":"\/documentation\/yababa\/shareddata\/archivein()"},"doc://com.yababaGmbH.yababa/documentation/Yababa/SharedData/isLocationUpdated":{"role":"symbol","title":"isLocationUpdated","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isLocationUpdated"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/SharedData\/isLocationUpdated","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"isLocationUpdated"}],"url":"\/documentation\/yababa\/shareddata\/islocationupdated"},"doc://com.yababaGmbH.yababa/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.yababaGmbH.yababa\/SH"},"doc://com.yababaGmbH.yababa/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.yababaGmbH.yababa\/s23CustomStringConvertibleP"},"doc://com.yababaGmbH.yababa/documentation/Yababa/SharedData/isIPhone":{"role":"symbol","title":"isIPhone","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isIPhone"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/SharedData\/isIPhone","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"isIPhone"}],"url":"\/documentation\/yababa\/shareddata\/isiphone"},"doc://com.yababaGmbH.yababa/documentation/Yababa/SharedData/userInfo":{"role":"symbol","title":"userInfo","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"userInfo"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"AnyHashable","preciseIdentifier":"s:s11AnyHashableV"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]!"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/SharedData\/userInfo","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"userInfo"}],"url":"\/documentation\/yababa\/shareddata\/userinfo"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"SharedData"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SharedData"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"SharedData"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/SharedData\/apiVersion","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/SharedData\/appRequiresUpdate","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/SharedData\/currentUser","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/SharedData\/currentViewController","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/SharedData\/dateFormat","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/SharedData\/emailKey","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/SharedData\/internetView","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/SharedData\/isIPhone","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/SharedData\/isLocationUpdated","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/SharedData\/isProfileUpdated","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/SharedData\/locationManager","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/SharedData\/lostInternetConnection","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/SharedData\/navigationBarHeight","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/SharedData\/screenSize","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/SharedData\/selectedIndex","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/SharedData\/serverUrl","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/SharedData\/statusBar","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/SharedData\/statusBarHeight","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/SharedData\/userInfo","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/SharedData\/waitingView"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/SharedData\/archiveIn()","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/SharedData\/deleteChache()","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/SharedData\/getCountryCode()","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/SharedData\/hideWaitingView()","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/SharedData\/internetIsReachable()","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/SharedData\/nsStringIsValidEmail(_:)","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/SharedData\/showWaitingView()","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/SharedData\/unarchiveIn()"]},{"title":"Type Methods","identifiers":["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/SharedData\/getInstance()"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.yababaGmbH.yababa\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.yababaGmbH.yababa\/objc(pl)CLLocationManagerDelegate"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"SharedData"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1SharedData~1emailKey\/title","value":"emailKey"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1SharedData~1emailKey\/fragments","value":[{"kind":"identifier","text":"emailKey"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1SharedData~1internetIsReachable()\/title","value":"internetIsReachable"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1SharedData~1internetIsReachable()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"internetIsReachable"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1SharedData~1navigationBarHeight\/title","value":"NavigationBarHeight"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1SharedData~1navigationBarHeight\/fragments","value":[{"kind":"identifier","text":"NavigationBarHeight"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1SharedData~1waitingView\/title","value":"waitingView"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1SharedData~1waitingView\/fragments","value":[{"kind":"identifier","text":"waitingView"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1SharedData~1serverUrl\/title","value":"serverUrl"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1SharedData~1serverUrl\/fragments","value":[{"kind":"identifier","text":"serverUrl"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1SharedData~1showWaitingView()\/title","value":"ShowWaitingView"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1SharedData~1showWaitingView()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"ShowWaitingView"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1SharedData\/title","value":"SharedData"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1SharedData\/fragments","value":[{"kind":"identifier","text":"SharedData"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1SharedData~1isProfileUpdated\/title","value":"isProfileUpdated"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1SharedData~1isProfileUpdated\/fragments","value":[{"kind":"identifier","text":"isProfileUpdated"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1SharedData~1currentUser\/title","value":"currentUser"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1SharedData~1currentUser\/fragments","value":[{"kind":"identifier","text":"currentUser"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1SharedData~1screenSize\/title","value":"ScreenSize"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1SharedData~1screenSize\/fragments","value":[{"kind":"identifier","text":"ScreenSize"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1SharedData~1hideWaitingView()\/title","value":"HideWaitingView"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1SharedData~1hideWaitingView()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"HideWaitingView"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1SharedData~1internetView\/title","value":"internetView"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1SharedData~1internetView\/fragments","value":[{"kind":"identifier","text":"internetView"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1SharedData~1deleteChache()\/title","value":"deleteChache"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1SharedData~1deleteChache()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"deleteChache"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1SharedData~1appRequiresUpdate\/title","value":"appRequiresUpdate"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1SharedData~1appRequiresUpdate\/fragments","value":[{"kind":"identifier","text":"appRequiresUpdate"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1SharedData~1statusBar\/title","value":"statusBar"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1SharedData~1statusBar\/fragments","value":[{"kind":"identifier","text":"statusBar"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1SharedData~1currentViewController\/title","value":"currentViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1SharedData~1currentViewController\/fragments","value":[{"kind":"identifier","text":"currentViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1SharedData~1getCountryCode()\/title","value":"getCountryCode"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1SharedData~1getCountryCode()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"getCountryCode"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1SharedData~1lostInternetConnection\/title","value":"lostInternetConnection"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1SharedData~1lostInternetConnection\/fragments","value":[{"kind":"identifier","text":"lostInternetConnection"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1SharedData~1statusBarHeight\/title","value":"StatusBarHeight"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1SharedData~1statusBarHeight\/fragments","value":[{"kind":"identifier","text":"StatusBarHeight"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1SharedData~1apiVersion\/title","value":"apiVersion"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1SharedData~1apiVersion\/fragments","value":[{"kind":"identifier","text":"apiVersion"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1SharedData~1dateFormat\/title","value":"dateFormat"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1SharedData~1dateFormat\/fragments","value":[{"kind":"identifier","text":"dateFormat"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1SharedData~1nsStringIsValidEmail(_:)\/title","value":"NSStringIsValidEmail:"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1SharedData~1nsStringIsValidEmail(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"NSStringIsValidEmail:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1SharedData~1unarchiveIn()\/title","value":"unarchiveIn"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1SharedData~1unarchiveIn()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"unarchiveIn"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1SharedData~1locationManager\/title","value":"LocationManager"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1SharedData~1locationManager\/fragments","value":[{"kind":"identifier","text":"LocationManager"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1SharedData~1getInstance()\/title","value":"getInstance"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1SharedData~1getInstance()\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"getInstance"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1SharedData~1selectedIndex\/title","value":"selectedIndex"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1SharedData~1selectedIndex\/fragments","value":[{"kind":"identifier","text":"selectedIndex"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1SharedData~1archiveIn()\/title","value":"archiveIn"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1SharedData~1archiveIn()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"archiveIn"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1SharedData~1isLocationUpdated\/title","value":"isLocationUpdated"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1SharedData~1isLocationUpdated\/fragments","value":[{"kind":"identifier","text":"isLocationUpdated"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1SharedData~1isIPhone\/title","value":"isIPhone"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1SharedData~1isIPhone\/fragments","value":[{"kind":"identifier","text":"isIPhone"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1SharedData~1userInfo\/title","value":"userInfo"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1SharedData~1userInfo\/fragments","value":[{"kind":"identifier","text":"userInfo"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}