{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ShoppingCartPaymentFlowProcessor"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/yababa\/shoppingcartpaymentflowprocessor"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/yababa\/shoppingcartpaymentflowprocessor"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.yababaGmbH.yababa\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/FlowProcessor","doc:\/\/com.yababaGmbH.yababa\/objc(pl)NSObject","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ReceiptViewDelegate","doc:\/\/com.yababaGmbH.yababa\/12SkeletonView17AssociatedObjectsP","doc:\/\/com.yababaGmbH.yababa\/s7CVarArgP","doc:\/\/com.yababaGmbH.yababa\/s28CustomDebugStringConvertibleP","doc:\/\/com.yababaGmbH.yababa\/s23CustomStringConvertibleP","doc:\/\/com.yababaGmbH.yababa\/SQ","doc:\/\/com.yababaGmbH.yababa\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ShoppingCartPaymentFlowProcessor","interfaceLanguage":"swift"},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ShoppingCartPaymentFlowProcessor\/init(delegate:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ShoppingCartPaymentFlowProcessor\/delegate","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ShoppingCartPaymentFlowProcessor\/orderIdAfterSuccess"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ShoppingCartPaymentFlowProcessor\/onPaymentCancel(sessionId:)","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ShoppingCartPaymentFlowProcessor\/onPaymentFail(message:sessionId:)","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ShoppingCartPaymentFlowProcessor\/onPaymentSuccess(sessionId:allowRetrial:)","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ShoppingCartPaymentFlowProcessor\/onReceiptClose()","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ShoppingCartPaymentFlowProcessor\/showReceipt()"]}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ShoppingCartPaymentFlowProcessor"}],"title":"ShoppingCartPaymentFlowProcessor","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@Yababa@objc(cs)ShoppingCartPaymentFlowProcessor","modules":[{"name":"Yababa"}],"navigatorTitle":[{"kind":"identifier","text":"ShoppingCartPaymentFlowProcessor"}]},"hierarchy":{"paths":[["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa"]]},"references":{"doc://com.yababaGmbH.yababa/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.yababaGmbH.yababa\/SH"},"doc://com.yababaGmbH.yababa/documentation/Yababa/FlowProcessor":{"role":"symbol","title":"FlowProcessor","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"FlowProcessor"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/FlowProcessor","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FlowProcessor"}],"url":"\/documentation\/yababa\/flowprocessor"},"doc://com.yababaGmbH.yababa/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.yababaGmbH.yababa\/SQ"},"doc://com.yababaGmbH.yababa/12SkeletonView17AssociatedObjectsP":{"type":"unresolvable","title":"SkeletonView.AssociatedObjects","identifier":"doc:\/\/com.yababaGmbH.yababa\/12SkeletonView17AssociatedObjectsP"},"doc://com.yababaGmbH.yababa/documentation/Yababa/ShoppingCartPaymentFlowProcessor/onPaymentSuccess(sessionId:allowRetrial:)":{"role":"symbol","title":"onPaymentSuccess(sessionId:allowRetrial:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onPaymentSuccess"},{"kind":"text","text":"("},{"kind":"externalParam","text":"sessionId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"allowRetrial"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ShoppingCartPaymentFlowProcessor\/onPaymentSuccess(sessionId:allowRetrial:)","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/shoppingcartpaymentflowprocessor\/onpaymentsuccess(sessionid:allowretrial:)"},"doc://com.yababaGmbH.yababa/documentation/Yababa/ShoppingCartPaymentFlowProcessor/init(delegate:)":{"role":"symbol","title":"init(delegate:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"delegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"FlowProcessorDelegate","preciseIdentifier":"s:6Yababa21FlowProcessorDelegateP"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ShoppingCartPaymentFlowProcessor\/init(delegate:)","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/shoppingcartpaymentflowprocessor\/init(delegate:)"},"doc://com.yababaGmbH.yababa/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)NSObject"},"doc://com.yababaGmbH.yababa/documentation/Yababa/ShoppingCartPaymentFlowProcessor/onPaymentFail(message:sessionId:)":{"role":"symbol","title":"onPaymentFail(message:sessionId:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onPaymentFail"},{"kind":"text","text":"("},{"kind":"externalParam","text":"message"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"sessionId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ShoppingCartPaymentFlowProcessor\/onPaymentFail(message:sessionId:)","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/shoppingcartpaymentflowprocessor\/onpaymentfail(message:sessionid:)"},"doc://com.yababaGmbH.yababa/documentation/Yababa/ShoppingCartPaymentFlowProcessor/onPaymentCancel(sessionId:)":{"role":"symbol","title":"onPaymentCancel(sessionId:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onPaymentCancel"},{"kind":"text","text":"("},{"kind":"externalParam","text":"sessionId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ShoppingCartPaymentFlowProcessor\/onPaymentCancel(sessionId:)","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/shoppingcartpaymentflowprocessor\/onpaymentcancel(sessionid:)"},"doc://com.yababaGmbH.yababa/documentation/Yababa":{"role":"collection","title":"Yababa","abstract":[{"type":"text","text":"Getting Started"}],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa","kind":"symbol","type":"topic","url":"\/documentation\/yababa"},"doc://com.yababaGmbH.yababa/documentation/Yababa/ShoppingCartPaymentFlowProcessor/onReceiptClose()":{"role":"symbol","title":"onReceiptClose()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onReceiptClose"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ShoppingCartPaymentFlowProcessor\/onReceiptClose()","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/shoppingcartpaymentflowprocessor\/onreceiptclose()"},"doc://com.yababaGmbH.yababa/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(cs)NSObject"},"doc://com.yababaGmbH.yababa/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.yababaGmbH.yababa\/s23CustomStringConvertibleP"},"doc://com.yababaGmbH.yababa/documentation/Yababa/ShoppingCartPaymentFlowProcessor/orderIdAfterSuccess":{"role":"symbol","title":"orderIdAfterSuccess","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"orderIdAfterSuccess"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ShoppingCartPaymentFlowProcessor\/orderIdAfterSuccess","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/shoppingcartpaymentflowprocessor\/orderidaftersuccess"},"doc://com.yababaGmbH.yababa/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.yababaGmbH.yababa\/s7CVarArgP"},"doc://com.yababaGmbH.yababa/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.yababaGmbH.yababa\/s28CustomDebugStringConvertibleP"},"doc://com.yababaGmbH.yababa/documentation/Yababa/ReceiptViewDelegate":{"role":"symbol","title":"ReceiptViewDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"ReceiptViewDelegate"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ReceiptViewDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ReceiptViewDelegate"}],"url":"\/documentation\/yababa\/receiptviewdelegate"},"doc://com.yababaGmbH.yababa/documentation/Yababa/ShoppingCartPaymentFlowProcessor":{"role":"symbol","title":"ShoppingCartPaymentFlowProcessor","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ShoppingCartPaymentFlowProcessor"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ShoppingCartPaymentFlowProcessor","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ShoppingCartPaymentFlowProcessor"}],"url":"\/documentation\/yababa\/shoppingcartpaymentflowprocessor"},"doc://com.yababaGmbH.yababa/documentation/Yababa/ShoppingCartPaymentFlowProcessor/showReceipt()":{"role":"symbol","title":"showReceipt()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"showReceipt"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ShoppingCartPaymentFlowProcessor\/showReceipt()","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/shoppingcartpaymentflowprocessor\/showreceipt()"},"doc://com.yababaGmbH.yababa/documentation/Yababa/ShoppingCartPaymentFlowProcessor/delegate":{"role":"symbol","title":"delegate","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"delegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"FlowProcessorDelegate","preciseIdentifier":"s:6Yababa21FlowProcessorDelegateP"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ShoppingCartPaymentFlowProcessor\/delegate","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/shoppingcartpaymentflowprocessor\/delegate"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"ShoppingCartPaymentFlowProcessor"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"ShoppingCartPaymentFlowProcessor"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"ShoppingCartPaymentFlowProcessor"}]},{"op":"replace","path":"\/topicSections","value":null},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.yababaGmbH.yababa\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"ShoppingCartPaymentFlowProcessor"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1ShoppingCartPaymentFlowProcessor\/title","value":"ShoppingCartPaymentFlowProcessor"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1ShoppingCartPaymentFlowProcessor\/fragments","value":[{"kind":"identifier","text":"ShoppingCartPaymentFlowProcessor"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}