{"primaryContentSections":[{"kind":"content","content":[{"anchor":"Overview","level":2,"type":"heading","text":"Overview"},{"type":"paragraph","inlineContent":[{"type":"text","text":"The Store Manager has two primary roles. Fetch the catalogue and save it locally on device and secondly keeping an updated count on product stock quantities."}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"All the views and other app components such as the Home Screen, Catalogue Screen and the Search Screen communicate with the Store Manager to get and show the required products on the screen."}]},{"anchor":"1-Fetch-Catalogue","level":4,"type":"heading","text":"1. Fetch Catalogue"},{"type":"paragraph","inlineContent":[{"type":"text","text":"The Store Manager fetches the catalogue from the server. It then keeps a copy of it locally on the device with a catalogue version number."}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"The catalogue is refreshed on app launch. Each time the store manager tries to fetch the catalogue from the server, it passes the catalogue version number to the server, if the version number is below the latest, the server returns the latest version of the catalogue and the store manager  stores it locally. If the version number is the latest, the server instead returns an upto date message response without the catalogue and the store manager loads the locally stored catalogue to the memory."}]},{"anchor":"2-Fetch-available-stock-quantities","level":4,"type":"heading","text":"2. Fetch available stock quantities"},{"type":"paragraph","inlineContent":[{"type":"text","text":"The Store Manager also fetches product stock quantities every 30 seconds from the server, to ensure that the inventory is up-to-date at all times."}]},{"anchor":"Implementation","level":2,"type":"heading","text":"Implementation"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Navigate to implementation class"}]},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"reference","isActive":true,"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ProductsDataStoreManager"}]}]}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/yababa\/storemanager"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/yababa\/storemanager"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/StoreManager","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Core component of the app, responsible for fetching the latest catalogue from server and maintaining it locally on the device."}],"kind":"article","metadata":{"roleHeading":"Article","title":"Store Manager","role":"article","modules":[{"name":"Yababa"}]},"hierarchy":{"paths":[["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa"]]},"seeAlsoSections":[{"title":"Shopping","identifiers":["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/-ShoppingOverview","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ShoppingCartManager"],"generated":true}],"references":{"doc://com.yababaGmbH.yababa/documentation/Yababa/ShoppingCartManager":{"role":"article","title":"Shopping Cart","abstract":[{"type":"text","text":"Core component of the app, responsible for managing products in the shopping cart."}],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ShoppingCartManager","kind":"article","type":"topic","url":"\/documentation\/yababa\/shoppingcartmanager"},"doc://com.yababaGmbH.yababa/documentation/Yababa/-ShoppingOverview":{"role":"article","title":"Shopping experience","abstract":[{"type":"text","text":"One Shopping"}],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/-ShoppingOverview","kind":"article","type":"topic","url":"\/documentation\/yababa\/-shoppingoverview"},"doc://com.yababaGmbH.yababa/documentation/Yababa":{"role":"collection","title":"Yababa","abstract":[{"type":"text","text":"Getting Started"}],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa","kind":"symbol","type":"topic","url":"\/documentation\/yababa"},"doc://com.yababaGmbH.yababa/documentation/Yababa/ProductsDataStoreManager":{"role":"symbol","title":"ProductsDataStoreManager","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ProductsDataStoreManager"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ProductsDataStoreManager","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ProductsDataStoreManager"}],"url":"\/documentation\/yababa\/productsdatastoremanager"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/topicSections","value":null},{"op":"replace","path":"\/seeAlsoSections","value":[{"title":"Shopping","identifiers":["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/-ShoppingOverview","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ShoppingCartManager"],"generated":true}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1ProductsDataStoreManager\/title","value":"ProductsDataStoreManager"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1ProductsDataStoreManager\/fragments","value":[{"kind":"identifier","text":"ProductsDataStoreManager"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}