{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TileProduct"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/yababa\/tileproduct"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/yababa\/tileproduct"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.yababaGmbH.yababa\/objc(cs)UIView"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.yababaGmbH.yababa\/objc(pl)NSCoding","doc:\/\/com.yababaGmbH.yababa\/objc(pl)NSObject","doc:\/\/com.yababaGmbH.yababa\/objc(pl)CALayerDelegate","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/Renderable","doc:\/\/com.yababaGmbH.yababa\/12SkeletonView17AssociatedObjectsP","doc:\/\/com.yababaGmbH.yababa\/12SkeletonView15IterableElementP","doc:\/\/com.yababaGmbH.yababa\/12SkeletonView11RecoverableP","doc:\/\/com.yababaGmbH.yababa\/6Stripe19SafeAreaLayoutGuideP","doc:\/\/com.yababaGmbH.yababa\/s7CVarArgP","doc:\/\/com.yababaGmbH.yababa\/s28CustomDebugStringConvertibleP","doc:\/\/com.yababaGmbH.yababa\/s23CustomStringConvertibleP","doc:\/\/com.yababaGmbH.yababa\/SQ","doc:\/\/com.yababaGmbH.yababa\/SH","doc:\/\/com.yababaGmbH.yababa\/s8SendableP","doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIAccessibilityIdentification","doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIActivityItemsConfigurationProviding","doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIAppearance","doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIAppearanceContainer","doc:\/\/com.yababaGmbH.yababa\/objc(pl)UICoordinateSpace","doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIDynamicItem","doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIFocusEnvironment","doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIFocusItem","doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIFocusItemContainer","doc:\/\/com.yababaGmbH.yababa\/objc(pl)UILargeContentViewerItem","doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIPasteConfigurationSupporting","doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIPopoverPresentationControllerSourceItem","doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIResponderStandardEditActions","doc:\/\/com.yababaGmbH.yababa\/objc(pl)UITraitEnvironment","doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIUserActivityRestoring"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/TileProduct","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"WARNING: Not finished. Example implementation for component with Renderable"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TileProduct"}],"title":"TileProduct","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@Yababa@objc(cs)TileProduct","modules":[{"name":"Yababa"}],"navigatorTitle":[{"kind":"identifier","text":"TileProduct"}]},"hierarchy":{"paths":[["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa"]]},"topicSections":[{"title":"Structures","identifiers":["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/TileProduct\/Data"]},{"title":"Instance Properties","identifiers":["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/TileProduct\/addButton","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/TileProduct\/imageView","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/TileProduct\/priceTitleLabel","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/TileProduct\/subtitleLabel","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/TileProduct\/titleLabel","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/TileProduct\/viewModel-swift.property"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/TileProduct\/onAddButtonTapped()","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/TileProduct\/render(vm:)"]},{"title":"Type Aliases","identifiers":["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/TileProduct\/ViewModel-swift.typealias"]}],"references":{"doc://com.yababaGmbH.yababa/documentation/Yababa/TileProduct/render(vm:)":{"role":"symbol","title":"render(vm:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"render"},{"kind":"text","text":"("},{"kind":"externalParam","text":"vm"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Data","preciseIdentifier":"s:6Yababa11TileProductC4DataV"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/TileProduct\/render(vm:)","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/tileproduct\/render(vm:)"},"doc://com.yababaGmbH.yababa/objc(pl)UIUserActivityRestoring":{"type":"unresolvable","title":"UIKit.UIUserActivityRestoring","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIUserActivityRestoring"},"doc://com.yababaGmbH.yababa/objc(pl)UIFocusItem":{"type":"unresolvable","title":"UIKit.UIFocusItem","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIFocusItem"},"doc://com.yababaGmbH.yababa/12SkeletonView17AssociatedObjectsP":{"type":"unresolvable","title":"SkeletonView.AssociatedObjects","identifier":"doc:\/\/com.yababaGmbH.yababa\/12SkeletonView17AssociatedObjectsP"},"doc://com.yababaGmbH.yababa/objc(pl)NSCoding":{"type":"unresolvable","title":"Foundation.NSCoding","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)NSCoding"},"doc://com.yababaGmbH.yababa/documentation/Yababa/TileProduct/imageView":{"role":"symbol","title":"imageView","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"imageView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIImageView","preciseIdentifier":"c:objc(cs)UIImageView"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/TileProduct\/imageView","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/tileproduct\/imageview"},"doc://com.yababaGmbH.yababa/objc(pl)UIPasteConfigurationSupporting":{"type":"unresolvable","title":"UIKit.UIPasteConfigurationSupporting","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIPasteConfigurationSupporting"},"doc://com.yababaGmbH.yababa/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.yababaGmbH.yababa\/SQ"},"doc://com.yababaGmbH.yababa/objc(pl)UIAppearanceContainer":{"type":"unresolvable","title":"UIKit.UIAppearanceContainer","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIAppearanceContainer"},"doc://com.yababaGmbH.yababa/objc(pl)UIFocusItemContainer":{"type":"unresolvable","title":"UIKit.UIFocusItemContainer","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIFocusItemContainer"},"doc://com.yababaGmbH.yababa/12SkeletonView11RecoverableP":{"type":"unresolvable","title":"SkeletonView.Recoverable","identifier":"doc:\/\/com.yababaGmbH.yababa\/12SkeletonView11RecoverableP"},"doc://com.yababaGmbH.yababa/12SkeletonView15IterableElementP":{"type":"unresolvable","title":"SkeletonView.IterableElement","identifier":"doc:\/\/com.yababaGmbH.yababa\/12SkeletonView15IterableElementP"},"doc://com.yababaGmbH.yababa/documentation/Yababa":{"role":"collection","title":"Yababa","abstract":[{"type":"text","text":"Getting Started"}],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa","kind":"symbol","type":"topic","url":"\/documentation\/yababa"},"doc://com.yababaGmbH.yababa/documentation/Yababa/TileProduct/titleLabel":{"role":"symbol","title":"titleLabel","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"titleLabel"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UILabel","preciseIdentifier":"c:objc(cs)UILabel"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/TileProduct\/titleLabel","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/tileproduct\/titlelabel"},"doc://com.yababaGmbH.yababa/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/com.yababaGmbH.yababa\/s8SendableP"},"doc://com.yababaGmbH.yababa/documentation/Yababa/TileProduct/viewModel-swift.property":{"role":"symbol","title":"viewModel","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"viewModel"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Data","preciseIdentifier":"s:6Yababa11TileProductC4DataV"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/TileProduct\/viewModel-swift.property","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/tileproduct\/viewmodel-swift.property"},"doc://com.yababaGmbH.yababa/objc(pl)UICoordinateSpace":{"type":"unresolvable","title":"UIKit.UICoordinateSpace","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)UICoordinateSpace"},"doc://com.yababaGmbH.yababa/objc(pl)UIAccessibilityIdentification":{"type":"unresolvable","title":"UIKit.UIAccessibilityIdentification","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIAccessibilityIdentification"},"doc://com.yababaGmbH.yababa/objc(pl)CALayerDelegate":{"type":"unresolvable","title":"QuartzCore.CALayerDelegate","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)CALayerDelegate"},"doc://com.yababaGmbH.yababa/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.yababaGmbH.yababa\/s23CustomStringConvertibleP"},"doc://com.yababaGmbH.yababa/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)NSObject"},"doc://com.yababaGmbH.yababa/objc(pl)UITraitEnvironment":{"type":"unresolvable","title":"UIKit.UITraitEnvironment","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)UITraitEnvironment"},"doc://com.yababaGmbH.yababa/documentation/Yababa/TileProduct/addButton":{"role":"symbol","title":"addButton","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"addButton"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIButton","preciseIdentifier":"c:objc(cs)UIButton"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/TileProduct\/addButton","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/tileproduct\/addbutton"},"doc://com.yababaGmbH.yababa/documentation/Yababa/TileProduct/ViewModel-swift.typealias":{"role":"symbol","title":"TileProduct.ViewModel","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"ViewModel"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/TileProduct\/ViewModel-swift.typealias","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ViewModel"}],"url":"\/documentation\/yababa\/tileproduct\/viewmodel-swift.typealias"},"doc://com.yababaGmbH.yababa/documentation/Yababa/TileProduct/initWithCoder:":{"role":"symbol","title":"initWithCoder:","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithCoder:"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/TileProduct\/initWithCoder:","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithCoder:"}],"url":"\/documentation\/yababa\/tileproduct\/initwithcoder:"},"doc://com.yababaGmbH.yababa/documentation/Yababa/TileProduct/initWithFrame:":{"role":"symbol","title":"initWithFrame:","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithFrame:"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/TileProduct\/initWithFrame:","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithFrame:"}],"url":"\/documentation\/yababa\/tileproduct\/initwithframe:"},"doc://com.yababaGmbH.yababa/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.yababaGmbH.yababa\/SH"},"doc://com.yababaGmbH.yababa/objc(pl)UIResponderStandardEditActions":{"type":"unresolvable","title":"UIKit.UIResponderStandardEditActions","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIResponderStandardEditActions"},"doc://com.yababaGmbH.yababa/objc(pl)UILargeContentViewerItem":{"type":"unresolvable","title":"UIKit.UILargeContentViewerItem","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)UILargeContentViewerItem"},"doc://com.yababaGmbH.yababa/objc(pl)UIPopoverPresentationControllerSourceItem":{"type":"unresolvable","title":"UIKit.UIPopoverPresentationControllerSourceItem","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIPopoverPresentationControllerSourceItem"},"doc://com.yababaGmbH.yababa/objc(pl)UIDynamicItem":{"type":"unresolvable","title":"UIKit.UIDynamicItem","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIDynamicItem"},"doc://com.yababaGmbH.yababa/objc(cs)UIView":{"type":"unresolvable","title":"UIView","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(cs)UIView"},"doc://com.yababaGmbH.yababa/documentation/Yababa/TileProduct/onAddButtonTapped()":{"role":"symbol","title":"onAddButtonTapped()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onAddButtonTapped"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/TileProduct\/onAddButtonTapped()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"onAddButtonTapped"}],"url":"\/documentation\/yababa\/tileproduct\/onaddbuttontapped()"},"doc://com.yababaGmbH.yababa/documentation/Yababa/TileProduct":{"role":"symbol","title":"TileProduct","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TileProduct"}],"abstract":[{"type":"text","text":"WARNING: Not finished. Example implementation for component with Renderable"}],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/TileProduct","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"TileProduct"}],"url":"\/documentation\/yababa\/tileproduct"},"doc://com.yababaGmbH.yababa/documentation/Yababa/Renderable":{"role":"symbol","title":"Renderable","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"Renderable"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/Renderable","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Renderable"}],"url":"\/documentation\/yababa\/renderable"},"doc://com.yababaGmbH.yababa/documentation/Yababa/TileProduct/Data":{"role":"symbol","title":"TileProduct.Data","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"Data"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/TileProduct\/Data","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Data"}],"url":"\/documentation\/yababa\/tileproduct\/data"},"doc://com.yababaGmbH.yababa/objc(pl)UIActivityItemsConfigurationProviding":{"type":"unresolvable","title":"UIKit.UIActivityItemsConfigurationProviding","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIActivityItemsConfigurationProviding"},"doc://com.yababaGmbH.yababa/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.yababaGmbH.yababa\/s28CustomDebugStringConvertibleP"},"doc://com.yababaGmbH.yababa/documentation/Yababa/TileProduct/priceTitleLabel":{"role":"symbol","title":"priceTitleLabel","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"priceTitleLabel"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UILabel","preciseIdentifier":"c:objc(cs)UILabel"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/TileProduct\/priceTitleLabel","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/tileproduct\/pricetitlelabel"},"doc://com.yababaGmbH.yababa/documentation/Yababa/TileProduct/subtitleLabel":{"role":"symbol","title":"subtitleLabel","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"subtitleLabel"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UILabel","preciseIdentifier":"c:objc(cs)UILabel"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/TileProduct\/subtitleLabel","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/tileproduct\/subtitlelabel"},"doc://com.yababaGmbH.yababa/6Stripe19SafeAreaLayoutGuideP":{"type":"unresolvable","title":"Stripe.SafeAreaLayoutGuide","identifier":"doc:\/\/com.yababaGmbH.yababa\/6Stripe19SafeAreaLayoutGuideP"},"doc://com.yababaGmbH.yababa/objc(pl)UIAppearance":{"type":"unresolvable","title":"UIKit.UIAppearance","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIAppearance"},"doc://com.yababaGmbH.yababa/objc(pl)UIFocusEnvironment":{"type":"unresolvable","title":"UIKit.UIFocusEnvironment","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIFocusEnvironment"},"doc://com.yababaGmbH.yababa/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.yababaGmbH.yababa\/s7CVarArgP"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"TileProduct"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"TileProduct"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"TileProduct"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/TileProduct\/initWithCoder:","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/TileProduct\/initWithFrame:","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/TileProduct\/onAddButtonTapped()"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.yababaGmbH.yababa\/objc(cs)UIView"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"TileProduct"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1TileProduct~1onAddButtonTapped()\/title","value":"onAddButtonTapped"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1TileProduct~1onAddButtonTapped()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onAddButtonTapped"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1TileProduct\/title","value":"TileProduct"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1TileProduct\/fragments","value":[{"kind":"identifier","text":"TileProduct"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}