{"primaryContentSections":[{"kind":"content","content":[{"anchor":"Overview","level":2,"type":"heading","text":"Overview"},{"type":"paragraph","inlineContent":[{"type":"text","text":"The app provides standard email login as well as social login option. If “Continue with Email” is chosen in the welcome screen, user is prompted to enter in their email address. If the email address exists in backend databse, user is prompted to enter the password, else user is taken to a signup form where they can create a new account."}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"Note: The code for Login view controller came from the in2 project and is written in Objective C while following the MVC pattern. The Welcome screen ("},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/WelcomeSceneViewController"},{"type":"text","text":"), Email input screen ("},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/JoinSceneViewController"},{"type":"text","text":") and Signup Screen ("},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/SignupSceneViewController"},{"type":"text","text":") are written in Swift."}]},{"anchor":"Social-Logins","level":2,"type":"heading","text":"Social Logins"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Currently, the app also provides users to login and signup using Apple, Facebook and Google. All of these have their respected SDKs included in the project. The code has seperate implementation classes for each method."}]},{"anchor":"Implementation-Classes","level":4,"type":"heading","text":"Implementation Classes"},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"reference","isActive":true,"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AppleLogin"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"reference","isActive":true,"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/FacebookLogin"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"reference","isActive":true,"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/GoogleLogin"}]}]}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"To standarize implementation and integration of different SDKs, all social login methods are required to implement the "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/SocialLogin"},{"type":"text","text":" protocol. It follows the SOLID principals and makes it scalable to add new social login options in the future if needed. The protocol also forces these login methods to request the Backend with required APIs. For example Apple Login will call the \/user\/signInWithApple API."}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"A small component situated between the Welcome screen and Social logins is the "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/SocialRouter"},{"type":"text","text":". Its usefulness lies in its ability to be reused in other places, making all the implemented social login methods easily accessible. For instance, the Home Screen can display and activate the social login methods while in browsing mode. To use this component, the calling classes must implement the "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/SocialLoginResponseDelegate"},{"type":"text","text":" protocol, which standardizes the behavior of successful and failed logins."}]},{"type":"paragraph","inlineContent":[{"type":"image","identifier":"SocialLoginOverview.jpg"}]},{"anchor":"Profile-completion","level":2,"type":"heading","text":"Profile completion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Social logins can sometimes fail to provide the user’s name or email address to the app. To ensure that the system has the necessary contact information for the user, a profile completion screen is implemented and triggered (if needed) before the checkout process. This screen prompts users to add any missing contact information that the system will need to contact them."}]},{"anchor":"Implementation","level":4,"type":"heading","text":"Implementation"},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"reference","isActive":true,"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CompleteProfileSceneViewController"}]}]}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/yababa\/user-login"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/yababa\/user-login"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/User-Login","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Covers user login and signup journey through Email and Social login methods"}],"kind":"article","metadata":{"roleHeading":"Article","title":"User Login","role":"article","modules":[{"name":"Yababa"}]},"hierarchy":{"paths":[["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa"]]},"seeAlsoSections":[{"title":"User Access","identifiers":["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AddressManagerDocumentation","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/UserStateManager","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/PushNotificationsDocumentation"],"generated":true}],"references":{"doc://com.yababaGmbH.yababa/documentation/Yababa/FacebookLogin":{"role":"symbol","title":"FacebookLogin","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FacebookLogin"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/FacebookLogin","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FacebookLogin"}],"url":"\/documentation\/yababa\/facebooklogin"},"doc://com.yababaGmbH.yababa/documentation/Yababa/SocialLoginResponseDelegate":{"role":"symbol","title":"SocialLoginResponseDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SocialLoginResponseDelegate"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/SocialLoginResponseDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SocialLoginResponseDelegate"}],"url":"\/documentation\/yababa\/socialloginresponsedelegate"},"doc://com.yababaGmbH.yababa/documentation/Yababa":{"role":"collection","title":"Yababa","abstract":[{"type":"text","text":"Getting Started"}],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa","kind":"symbol","type":"topic","url":"\/documentation\/yababa"},"doc://com.yababaGmbH.yababa/documentation/Yababa/JoinSceneViewController":{"role":"symbol","title":"JoinSceneViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"JoinSceneViewController"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/JoinSceneViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"JoinSceneViewController"}],"url":"\/documentation\/yababa\/joinsceneviewcontroller"},"doc://com.yababaGmbH.yababa/documentation/Yababa/GoogleLogin":{"role":"symbol","title":"GoogleLogin","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GoogleLogin"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/GoogleLogin","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GoogleLogin"}],"url":"\/documentation\/yababa\/googlelogin"},"doc://com.yababaGmbH.yababa/documentation/Yababa/SocialLogin":{"role":"symbol","title":"SocialLogin","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SocialLogin"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/SocialLogin","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SocialLogin"}],"url":"\/documentation\/yababa\/sociallogin"},"doc://com.yababaGmbH.yababa/documentation/Yababa/SignupSceneViewController":{"role":"symbol","title":"SignupSceneViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SignupSceneViewController"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/SignupSceneViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SignupSceneViewController"}],"url":"\/documentation\/yababa\/signupsceneviewcontroller"},"doc://com.yababaGmbH.yababa/documentation/Yababa/CompleteProfileSceneViewController":{"role":"symbol","title":"CompleteProfileSceneViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CompleteProfileSceneViewController"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CompleteProfileSceneViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CompleteProfileSceneViewController"}],"url":"\/documentation\/yababa\/completeprofilesceneviewcontroller"},"doc://com.yababaGmbH.yababa/documentation/Yababa/AddressManagerDocumentation":{"role":"article","title":"Address Managing Module","abstract":[{"type":"text","text":"Manages user delivery addresses. Allows user to add new address and validate existing ones"}],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AddressManagerDocumentation","kind":"article","type":"topic","url":"\/documentation\/yababa\/addressmanagerdocumentation"},"doc://com.yababaGmbH.yababa/documentation/Yababa/UserStateManager":{"role":"symbol","title":"UserStateManager","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"UserStateManager"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"LocalUserStateManager","preciseIdentifier":"c:@M@Yababa@objc(cs)LocalUserStateManager"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/UserStateManager","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/userstatemanager"},"SocialLoginOverview.jpg":{"alt":"Social login overview","type":"image","identifier":"SocialLoginOverview.jpg","variants":[{"url":"\/images\/SocialLoginOverview@2x.jpg","traits":["2x","light"]}]},"doc://com.yababaGmbH.yababa/documentation/Yababa/AppleLogin":{"role":"symbol","title":"AppleLogin","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AppleLogin"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AppleLogin","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AppleLogin"}],"url":"\/documentation\/yababa\/applelogin"},"doc://com.yababaGmbH.yababa/documentation/Yababa/WelcomeSceneViewController":{"role":"symbol","title":"WelcomeSceneViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"WelcomeSceneViewController"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/WelcomeSceneViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"WelcomeSceneViewController"}],"url":"\/documentation\/yababa\/welcomesceneviewcontroller"},"doc://com.yababaGmbH.yababa/documentation/Yababa/SocialRouter":{"role":"symbol","title":"SocialRouter","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SocialRouter"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/SocialRouter","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SocialRouter"}],"url":"\/documentation\/yababa\/socialrouter"},"doc://com.yababaGmbH.yababa/documentation/Yababa/PushNotificationsDocumentation":{"role":"collectionGroup","title":"Push Notifications Manager","abstract":[{"type":"text","text":"Requesting permission for Push Notifications and receiving them"}],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/PushNotificationsDocumentation","kind":"article","type":"topic","url":"\/documentation\/yababa\/pushnotificationsdocumentation"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/topicSections","value":null},{"op":"replace","path":"\/seeAlsoSections","value":[{"title":"User Access","identifiers":["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AddressManagerDocumentation","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/PushNotificationsDocumentation"],"generated":true}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1JoinSceneViewController\/title","value":"JoinSceneViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1JoinSceneViewController\/fragments","value":[{"kind":"identifier","text":"JoinSceneViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1SignupSceneViewController\/title","value":"SignupSceneViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1SignupSceneViewController\/fragments","value":[{"kind":"identifier","text":"SignupSceneViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1CompleteProfileSceneViewController\/title","value":"CompleteProfileSceneViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1CompleteProfileSceneViewController\/fragments","value":[{"kind":"identifier","text":"CompleteProfileSceneViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1AppleLogin\/title","value":"AppleLogin"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1AppleLogin\/fragments","value":[{"kind":"identifier","text":"AppleLogin"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1WelcomeSceneViewController\/title","value":"WelcomeSceneViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1WelcomeSceneViewController\/fragments","value":[{"kind":"identifier","text":"WelcomeSceneViewController"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}