{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"UserData"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/yababa\/userdata"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/yababa\/userdata"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.yababaGmbH.yababa\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.yababaGmbH.yababa\/objc(pl)NSCoding","doc:\/\/com.yababaGmbH.yababa\/objc(pl)NSObject","doc:\/\/com.yababaGmbH.yababa\/12SkeletonView17AssociatedObjectsP","doc:\/\/com.yababaGmbH.yababa\/s7CVarArgP","doc:\/\/com.yababaGmbH.yababa\/s28CustomDebugStringConvertibleP","doc:\/\/com.yababaGmbH.yababa\/s23CustomStringConvertibleP","doc:\/\/com.yababaGmbH.yababa\/SQ","doc:\/\/com.yababaGmbH.yababa\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/UserData","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/UserData\/advanceToken","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/UserData\/appleToken","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/UserData\/city","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/UserData\/country","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/UserData\/facebookToken","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/UserData\/facebookUserId","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/UserData\/imagesCache","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/UserData\/isAroundMe","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/UserData\/isFacebookLoggedIn","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/UserData\/isLoggedInWithGoogle","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/UserData\/isLoggedOut","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/UserData\/latitude","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/UserData\/longitude","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/UserData\/microsoftAzureToken","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/UserData\/myProfile","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/UserData\/pushToken","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/UserData\/radius","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/UserData\/referralCode","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/UserData\/referralValue","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/UserData\/token"]}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"UserData"}],"title":"UserData","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:objc(cs)UserData","modules":[{"name":"Yababa"}],"navigatorTitle":[{"kind":"identifier","text":"UserData"}]},"hierarchy":{"paths":[["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa"]]},"references":{"doc://com.yababaGmbH.yababa/documentation/Yababa/UserData/isFacebookLoggedIn":{"role":"symbol","title":"isFacebookLoggedIn","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isFacebookLoggedIn"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/UserData\/isFacebookLoggedIn","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"isFacebookLoggedIn"}],"url":"\/documentation\/yababa\/userdata\/isfacebookloggedin"},"doc://com.yababaGmbH.yababa/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.yababaGmbH.yababa\/s7CVarArgP"},"doc://com.yababaGmbH.yababa/documentation/Yababa/UserData/isLoggedInWithGoogle":{"role":"symbol","title":"isLoggedInWithGoogle","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isLoggedInWithGoogle"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/UserData\/isLoggedInWithGoogle","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"isLoggedInWithGoogle"}],"url":"\/documentation\/yababa\/userdata\/isloggedinwithgoogle"},"doc://com.yababaGmbH.yababa/objc(pl)NSCoding":{"type":"unresolvable","title":"NSCoding","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)NSCoding"},"doc://com.yababaGmbH.yababa/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.yababaGmbH.yababa\/s28CustomDebugStringConvertibleP"},"doc://com.yababaGmbH.yababa/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.yababaGmbH.yababa\/SH"},"doc://com.yababaGmbH.yababa/12SkeletonView17AssociatedObjectsP":{"type":"unresolvable","title":"SkeletonView.AssociatedObjects","identifier":"doc:\/\/com.yababaGmbH.yababa\/12SkeletonView17AssociatedObjectsP"},"doc://com.yababaGmbH.yababa/documentation/Yababa/UserData/imagesCache":{"role":"symbol","title":"imagesCache","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"imagesCache"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSMutableDictionary","preciseIdentifier":"c:objc(cs)NSMutableDictionary"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/UserData\/imagesCache","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ImagesCache"}],"url":"\/documentation\/yababa\/userdata\/imagescache"},"doc://com.yababaGmbH.yababa/documentation/Yababa/UserData/city":{"role":"symbol","title":"city","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"city"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/UserData\/city","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"city"}],"url":"\/documentation\/yababa\/userdata\/city"},"doc://com.yababaGmbH.yababa/documentation/Yababa/UserData/longitude":{"role":"symbol","title":"longitude","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"longitude"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/UserData\/longitude","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"longitude"}],"url":"\/documentation\/yababa\/userdata\/longitude"},"doc://com.yababaGmbH.yababa/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(cs)NSObject"},"doc://com.yababaGmbH.yababa/documentation/Yababa/UserData/microsoftAzureToken":{"role":"symbol","title":"microsoftAzureToken","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"microsoftAzureToken"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/UserData\/microsoftAzureToken","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"microsoftAzureToken"}],"url":"\/documentation\/yababa\/userdata\/microsoftazuretoken"},"doc://com.yababaGmbH.yababa/documentation/Yababa/UserData/facebookUserId":{"role":"symbol","title":"facebookUserId","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"facebookUserId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/UserData\/facebookUserId","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"facebookUserId"}],"url":"\/documentation\/yababa\/userdata\/facebookuserid"},"doc://com.yababaGmbH.yababa/documentation/Yababa/UserData/myProfile":{"role":"symbol","title":"myProfile","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"myProfile"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Profile","preciseIdentifier":"c:@M@Yababa@objc(cs)Profile"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/UserData\/myProfile","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"myProfile"}],"url":"\/documentation\/yababa\/userdata\/myprofile"},"doc://com.yababaGmbH.yababa/documentation/Yababa":{"role":"collection","title":"Yababa","abstract":[{"type":"text","text":"Getting Started"}],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa","kind":"symbol","type":"topic","url":"\/documentation\/yababa"},"doc://com.yababaGmbH.yababa/documentation/Yababa/UserData/referralValue":{"role":"symbol","title":"referralValue","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"referralValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/UserData\/referralValue","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"referralValue"}],"url":"\/documentation\/yababa\/userdata\/referralvalue"},"doc://com.yababaGmbH.yababa/documentation/Yababa/UserData/advanceToken":{"role":"symbol","title":"advanceToken","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"advanceToken"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/UserData\/advanceToken","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"advanceToken"}],"url":"\/documentation\/yababa\/userdata\/advancetoken"},"doc://com.yababaGmbH.yababa/documentation/Yababa/UserData/isLoggedOut":{"role":"symbol","title":"isLoggedOut","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isLoggedOut"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/UserData\/isLoggedOut","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"isLoggedOut"}],"url":"\/documentation\/yababa\/userdata\/isloggedout"},"doc://com.yababaGmbH.yababa/documentation/Yababa/UserData/radius":{"role":"symbol","title":"radius","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"radius"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/UserData\/radius","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"radius"}],"url":"\/documentation\/yababa\/userdata\/radius"},"doc://com.yababaGmbH.yababa/documentation/Yababa/UserData/pushToken":{"role":"symbol","title":"pushToken","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"pushToken"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/UserData\/pushToken","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"pushToken"}],"url":"\/documentation\/yababa\/userdata\/pushtoken"},"doc://com.yababaGmbH.yababa/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.yababaGmbH.yababa\/s23CustomStringConvertibleP"},"doc://com.yababaGmbH.yababa/documentation/Yababa/UserData/country":{"role":"symbol","title":"country","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"country"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/UserData\/country","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"country"}],"url":"\/documentation\/yababa\/userdata\/country"},"doc://com.yababaGmbH.yababa/documentation/Yababa/UserData":{"role":"symbol","title":"UserData","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"UserData"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/UserData","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"UserData"}],"url":"\/documentation\/yababa\/userdata"},"doc://com.yababaGmbH.yababa/documentation/Yababa/UserData/isAroundMe":{"role":"symbol","title":"isAroundMe","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isAroundMe"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/UserData\/isAroundMe","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"isAroundMe"}],"url":"\/documentation\/yababa\/userdata\/isaroundme"},"doc://com.yababaGmbH.yababa/documentation/Yababa/UserData/facebookToken":{"role":"symbol","title":"facebookToken","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"facebookToken"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/UserData\/facebookToken","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"facebookToken"}],"url":"\/documentation\/yababa\/userdata\/facebooktoken"},"doc://com.yababaGmbH.yababa/documentation/Yababa/UserData/latitude":{"role":"symbol","title":"latitude","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"latitude"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/UserData\/latitude","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"latitude"}],"url":"\/documentation\/yababa\/userdata\/latitude"},"doc://com.yababaGmbH.yababa/documentation/Yababa/UserData/referralCode":{"role":"symbol","title":"referralCode","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"referralCode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/UserData\/referralCode","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"referralCode"}],"url":"\/documentation\/yababa\/userdata\/referralcode"},"doc://com.yababaGmbH.yababa/documentation/Yababa/UserData/appleToken":{"role":"symbol","title":"appleToken","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"appleToken"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/UserData\/appleToken","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"appleToken"}],"url":"\/documentation\/yababa\/userdata\/appletoken"},"doc://com.yababaGmbH.yababa/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.yababaGmbH.yababa\/SQ"},"doc://com.yababaGmbH.yababa/documentation/Yababa/UserData/token":{"role":"symbol","title":"token","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"token"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/UserData\/token","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"token"}],"url":"\/documentation\/yababa\/userdata\/token"},"doc://com.yababaGmbH.yababa/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)NSObject"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"UserData"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"UserData"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"UserData"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/UserData\/advanceToken","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/UserData\/appleToken","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/UserData\/city","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/UserData\/country","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/UserData\/facebookToken","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/UserData\/facebookUserId","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/UserData\/imagesCache","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/UserData\/isAroundMe","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/UserData\/isFacebookLoggedIn","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/UserData\/isLoggedInWithGoogle","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/UserData\/isLoggedOut","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/UserData\/latitude","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/UserData\/longitude","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/UserData\/microsoftAzureToken","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/UserData\/myProfile","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/UserData\/pushToken","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/UserData\/radius","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/UserData\/referralCode","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/UserData\/referralValue","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/UserData\/token"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.yababaGmbH.yababa\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.yababaGmbH.yababa\/objc(pl)NSCoding"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"UserData"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1UserData~1isFacebookLoggedIn\/title","value":"isFacebookLoggedIn"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1UserData~1isFacebookLoggedIn\/fragments","value":[{"kind":"identifier","text":"isFacebookLoggedIn"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1UserData~1isLoggedInWithGoogle\/title","value":"isLoggedInWithGoogle"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1UserData~1isLoggedInWithGoogle\/fragments","value":[{"kind":"identifier","text":"isLoggedInWithGoogle"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1UserData~1imagesCache\/title","value":"ImagesCache"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1UserData~1imagesCache\/fragments","value":[{"kind":"identifier","text":"ImagesCache"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1UserData~1city\/title","value":"city"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1UserData~1city\/fragments","value":[{"kind":"identifier","text":"city"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1UserData~1longitude\/title","value":"longitude"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1UserData~1longitude\/fragments","value":[{"kind":"identifier","text":"longitude"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1UserData~1microsoftAzureToken\/title","value":"microsoftAzureToken"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1UserData~1microsoftAzureToken\/fragments","value":[{"kind":"identifier","text":"microsoftAzureToken"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1UserData~1facebookUserId\/title","value":"facebookUserId"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1UserData~1facebookUserId\/fragments","value":[{"kind":"identifier","text":"facebookUserId"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1UserData~1myProfile\/title","value":"myProfile"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1UserData~1myProfile\/fragments","value":[{"kind":"identifier","text":"myProfile"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1UserData~1referralValue\/title","value":"referralValue"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1UserData~1referralValue\/fragments","value":[{"kind":"identifier","text":"referralValue"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1UserData~1advanceToken\/title","value":"advanceToken"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1UserData~1advanceToken\/fragments","value":[{"kind":"identifier","text":"advanceToken"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1UserData~1isLoggedOut\/title","value":"isLoggedOut"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1UserData~1isLoggedOut\/fragments","value":[{"kind":"identifier","text":"isLoggedOut"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1UserData~1radius\/title","value":"radius"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1UserData~1radius\/fragments","value":[{"kind":"identifier","text":"radius"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1UserData~1pushToken\/title","value":"pushToken"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1UserData~1pushToken\/fragments","value":[{"kind":"identifier","text":"pushToken"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1UserData~1country\/title","value":"country"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1UserData~1country\/fragments","value":[{"kind":"identifier","text":"country"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1UserData\/title","value":"UserData"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1UserData\/fragments","value":[{"kind":"identifier","text":"UserData"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1UserData~1isAroundMe\/title","value":"isAroundMe"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1UserData~1isAroundMe\/fragments","value":[{"kind":"identifier","text":"isAroundMe"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1UserData~1facebookToken\/title","value":"facebookToken"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1UserData~1facebookToken\/fragments","value":[{"kind":"identifier","text":"facebookToken"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1UserData~1latitude\/title","value":"latitude"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1UserData~1latitude\/fragments","value":[{"kind":"identifier","text":"latitude"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1UserData~1referralCode\/title","value":"referralCode"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1UserData~1referralCode\/fragments","value":[{"kind":"identifier","text":"referralCode"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1UserData~1appleToken\/title","value":"appleToken"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1UserData~1appleToken\/fragments","value":[{"kind":"identifier","text":"appleToken"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1UserData~1token\/title","value":"token"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1UserData~1token\/fragments","value":[{"kind":"identifier","text":"token"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}