{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Utilities"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/yababa\/utilities"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/yababa\/utilities"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.yababaGmbH.yababa\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.yababaGmbH.yababa\/objc(pl)NSObject","doc:\/\/com.yababaGmbH.yababa\/12SkeletonView17AssociatedObjectsP","doc:\/\/com.yababaGmbH.yababa\/s7CVarArgP","doc:\/\/com.yababaGmbH.yababa\/s28CustomDebugStringConvertibleP","doc:\/\/com.yababaGmbH.yababa\/s23CustomStringConvertibleP","doc:\/\/com.yababaGmbH.yababa\/SQ","doc:\/\/com.yababaGmbH.yababa\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/Utilities","interfaceLanguage":"swift"},"topicSections":[{"title":"Type Properties","identifiers":["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/Utilities\/ISOAlternateDateFormatter","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/Utilities\/ISODateFormatter","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/Utilities\/ISOWith24HoursDateFormatter","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/Utilities\/defaultDateFormatter","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/Utilities\/justDayDateFormatter","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/Utilities\/shortDataAndTimeDateFormatter","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/Utilities\/standardDateFormatter","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/Utilities\/timeDateFormatter","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/Utilities\/weekdayDateFormatter","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/Utilities\/yearFirstDateFormatter"]},{"title":"Type Methods","identifiers":["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/Utilities\/isEmailValid(_:)","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/Utilities\/makeTransparentNavigationControllerWith(viewController:)","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/Utilities\/setupSearchBar(searchBar:)"]}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Utilities"}],"title":"Utilities","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@Yababa@objc(cs)Utilities","modules":[{"name":"Yababa"}],"navigatorTitle":[{"kind":"identifier","text":"Utilities"}]},"hierarchy":{"paths":[["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa"]]},"references":{"doc://com.yababaGmbH.yababa/documentation/Yababa/Utilities":{"role":"symbol","title":"Utilities","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Utilities"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/Utilities","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Utilities"}],"url":"\/documentation\/yababa\/utilities"},"doc://com.yababaGmbH.yababa/documentation/Yababa/Utilities/isEmailValid(_:)":{"role":"symbol","title":"isEmailValid(_:)","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"isEmailValid"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/Utilities\/isEmailValid(_:)","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/utilities\/isemailvalid(_:)"},"doc://com.yababaGmbH.yababa/documentation/Yababa/Utilities/yearFirstDateFormatter":{"role":"symbol","title":"yearFirstDateFormatter","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"yearFirstDateFormatter"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DateFormatter","preciseIdentifier":"c:objc(cs)NSDateFormatter"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/Utilities\/yearFirstDateFormatter","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/utilities\/yearfirstdateformatter"},"doc://com.yababaGmbH.yababa/documentation/Yababa/Utilities/timeDateFormatter":{"role":"symbol","title":"timeDateFormatter","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"timeDateFormatter"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DateFormatter","preciseIdentifier":"c:objc(cs)NSDateFormatter"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/Utilities\/timeDateFormatter","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/utilities\/timedateformatter"},"doc://com.yababaGmbH.yababa/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.yababaGmbH.yababa\/s23CustomStringConvertibleP"},"doc://com.yababaGmbH.yababa/documentation/Yababa/Utilities/ISODateFormatter":{"role":"symbol","title":"ISODateFormatter","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"ISODateFormatter"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DateFormatter","preciseIdentifier":"c:objc(cs)NSDateFormatter"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/Utilities\/ISODateFormatter","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/utilities\/isodateformatter"},"doc://com.yababaGmbH.yababa/documentation/Yababa/Utilities/defaultDateFormatter":{"role":"symbol","title":"defaultDateFormatter","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"defaultDateFormatter"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DateFormatter","preciseIdentifier":"c:objc(cs)NSDateFormatter"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/Utilities\/defaultDateFormatter","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/utilities\/defaultdateformatter"},"doc://com.yababaGmbH.yababa/12SkeletonView17AssociatedObjectsP":{"type":"unresolvable","title":"SkeletonView.AssociatedObjects","identifier":"doc:\/\/com.yababaGmbH.yababa\/12SkeletonView17AssociatedObjectsP"},"doc://com.yababaGmbH.yababa/documentation/Yababa/Utilities/justDayDateFormatter":{"role":"symbol","title":"justDayDateFormatter","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"justDayDateFormatter"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DateFormatter","preciseIdentifier":"c:objc(cs)NSDateFormatter"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/Utilities\/justDayDateFormatter","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/utilities\/justdaydateformatter"},"doc://com.yababaGmbH.yababa/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.yababaGmbH.yababa\/s7CVarArgP"},"doc://com.yababaGmbH.yababa/documentation/Yababa/Utilities/weekdayDateFormatter":{"role":"symbol","title":"weekdayDateFormatter","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"weekdayDateFormatter"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DateFormatter","preciseIdentifier":"c:objc(cs)NSDateFormatter"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/Utilities\/weekdayDateFormatter","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/utilities\/weekdaydateformatter"},"doc://com.yababaGmbH.yababa/documentation/Yababa/Utilities/setupSearchBar(searchBar:)":{"role":"symbol","title":"setupSearchBar(searchBar:)","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setupSearchBar"},{"kind":"text","text":"("},{"kind":"externalParam","text":"searchBar"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UISearchBar","preciseIdentifier":"c:objc(cs)UISearchBar"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/Utilities\/setupSearchBar(searchBar:)","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/utilities\/setupsearchbar(searchbar:)"},"doc://com.yababaGmbH.yababa/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.yababaGmbH.yababa\/SQ"},"doc://com.yababaGmbH.yababa/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.yababaGmbH.yababa\/s28CustomDebugStringConvertibleP"},"doc://com.yababaGmbH.yababa/documentation/Yababa/Utilities/makeTransparentNavigationControllerWith(viewController:)":{"role":"symbol","title":"makeTransparentNavigationControllerWith(viewController:)","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"makeTransparentNavigationControllerWith"},{"kind":"text","text":"("},{"kind":"externalParam","text":"viewController"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"UINavigationController","preciseIdentifier":"c:objc(cs)UINavigationController"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/Utilities\/makeTransparentNavigationControllerWith(viewController:)","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/utilities\/maketransparentnavigationcontrollerwith(viewcontroller:)"},"doc://com.yababaGmbH.yababa/documentation/Yababa/Utilities/ISOWith24HoursDateFormatter":{"role":"symbol","title":"ISOWith24HoursDateFormatter","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"ISOWith24HoursDateFormatter"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DateFormatter","preciseIdentifier":"c:objc(cs)NSDateFormatter"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/Utilities\/ISOWith24HoursDateFormatter","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/utilities\/isowith24hoursdateformatter"},"doc://com.yababaGmbH.yababa/documentation/Yababa/Utilities/init":{"role":"symbol","title":"init","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/Utilities\/init","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"init"}],"url":"\/documentation\/yababa\/utilities\/init"},"doc://com.yababaGmbH.yababa/documentation/Yababa/Utilities/standardDateFormatter":{"role":"symbol","title":"standardDateFormatter","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"standardDateFormatter"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DateFormatter","preciseIdentifier":"c:objc(cs)NSDateFormatter"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/Utilities\/standardDateFormatter","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/utilities\/standarddateformatter"},"doc://com.yababaGmbH.yababa/documentation/Yababa":{"role":"collection","title":"Yababa","abstract":[{"type":"text","text":"Getting Started"}],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa","kind":"symbol","type":"topic","url":"\/documentation\/yababa"},"doc://com.yababaGmbH.yababa/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(cs)NSObject"},"doc://com.yababaGmbH.yababa/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.yababaGmbH.yababa\/SH"},"doc://com.yababaGmbH.yababa/documentation/Yababa/Utilities/shortDataAndTimeDateFormatter":{"role":"symbol","title":"shortDataAndTimeDateFormatter","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"shortDataAndTimeDateFormatter"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DateFormatter","preciseIdentifier":"c:objc(cs)NSDateFormatter"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/Utilities\/shortDataAndTimeDateFormatter","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/utilities\/shortdataandtimedateformatter"},"doc://com.yababaGmbH.yababa/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)NSObject"},"doc://com.yababaGmbH.yababa/documentation/Yababa/Utilities/ISOAlternateDateFormatter":{"role":"symbol","title":"ISOAlternateDateFormatter","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"ISOAlternateDateFormatter"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DateFormatter","preciseIdentifier":"c:objc(cs)NSDateFormatter"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/Utilities\/ISOAlternateDateFormatter","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/utilities\/isoalternatedateformatter"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"Utilities"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"Utilities"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"Utilities"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/Utilities\/init"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.yababaGmbH.yababa\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"Utilities"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1Utilities\/title","value":"Utilities"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1Utilities\/fragments","value":[{"kind":"identifier","text":"Utilities"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}