{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ZendeskFAQInteractor"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/yababa\/zendeskfaqinteractor"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/yababa\/zendeskfaqinteractor"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.yababaGmbH.yababa\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.yababaGmbH.yababa\/objc(pl)NSObject","doc:\/\/com.yababaGmbH.yababa\/12SkeletonView17AssociatedObjectsP","doc:\/\/com.yababaGmbH.yababa\/s7CVarArgP","doc:\/\/com.yababaGmbH.yababa\/s28CustomDebugStringConvertibleP","doc:\/\/com.yababaGmbH.yababa\/s23CustomStringConvertibleP","doc:\/\/com.yababaGmbH.yababa\/SQ","doc:\/\/com.yababaGmbH.yababa\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ZendeskFAQInteractor","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ZendeskFAQInteractor\/fetchFAQs()"]}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ZendeskFAQInteractor"}],"title":"ZendeskFAQInteractor","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@Yababa@objc(cs)ZendeskFAQInteractor","modules":[{"name":"Yababa"}],"navigatorTitle":[{"kind":"identifier","text":"ZendeskFAQInteractor"}]},"hierarchy":{"paths":[["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa"]]},"references":{"doc://com.yababaGmbH.yababa/documentation/Yababa/ZendeskFAQInteractor/init":{"role":"symbol","title":"init","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ZendeskFAQInteractor\/init","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"init"}],"url":"\/documentation\/yababa\/zendeskfaqinteractor\/init"},"doc://com.yababaGmbH.yababa/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(cs)NSObject"},"doc://com.yababaGmbH.yababa/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.yababaGmbH.yababa\/s28CustomDebugStringConvertibleP"},"doc://com.yababaGmbH.yababa/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)NSObject"},"doc://com.yababaGmbH.yababa/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.yababaGmbH.yababa\/s23CustomStringConvertibleP"},"doc://com.yababaGmbH.yababa/documentation/Yababa":{"role":"collection","title":"Yababa","abstract":[{"type":"text","text":"Getting Started"}],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa","kind":"symbol","type":"topic","url":"\/documentation\/yababa"},"doc://com.yababaGmbH.yababa/documentation/Yababa/ZendeskFAQInteractor/fetchFAQs()":{"role":"symbol","title":"fetchFAQs()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"fetchFAQs"},{"kind":"text","text":"() "},{"kind":"keyword","text":"async"},{"kind":"text","text":" "},{"kind":"keyword","text":"throws"},{"kind":"text","text":" -> ["},{"kind":"typeIdentifier","text":"ZendeskSection","preciseIdentifier":"s:6Yababa14ZendeskSectionV"},{"kind":"text","text":"]?"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ZendeskFAQInteractor\/fetchFAQs()","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/zendeskfaqinteractor\/fetchfaqs()"},"doc://com.yababaGmbH.yababa/12SkeletonView17AssociatedObjectsP":{"type":"unresolvable","title":"SkeletonView.AssociatedObjects","identifier":"doc:\/\/com.yababaGmbH.yababa\/12SkeletonView17AssociatedObjectsP"},"doc://com.yababaGmbH.yababa/documentation/Yababa/ZendeskFAQInteractor":{"role":"symbol","title":"ZendeskFAQInteractor","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ZendeskFAQInteractor"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ZendeskFAQInteractor","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ZendeskFAQInteractor"}],"url":"\/documentation\/yababa\/zendeskfaqinteractor"},"doc://com.yababaGmbH.yababa/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.yababaGmbH.yababa\/SQ"},"doc://com.yababaGmbH.yababa/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.yababaGmbH.yababa\/SH"},"doc://com.yababaGmbH.yababa/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.yababaGmbH.yababa\/s7CVarArgP"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"ZendeskFAQInteractor"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"ZendeskFAQInteractor"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"ZendeskFAQInteractor"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ZendeskFAQInteractor\/init"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.yababaGmbH.yababa\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"ZendeskFAQInteractor"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1ZendeskFAQInteractor\/title","value":"ZendeskFAQInteractor"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1ZendeskFAQInteractor\/fragments","value":[{"kind":"identifier","text":"ZendeskFAQInteractor"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}