{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"collectionView"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"collectionView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UICollectionView","preciseIdentifier":"c:objc(cs)UICollectionView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"layout"},{"kind":"text","text":" "},{"kind":"internalParam","text":"collectionViewLayout"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UICollectionViewLayout","preciseIdentifier":"c:objc(cs)UICollectionViewLayout"},{"kind":"text","text":", "},{"kind":"externalParam","text":"referenceSizeForFooterInSection"},{"kind":"text","text":" "},{"kind":"internalParam","text":"section"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"CGSize","preciseIdentifier":"c:@S@CGSize"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/yababa\/productslistingdatasourcemanager\/collectionview(_:layout:referencesizeforfooterinsection:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/yababa\/productslistingdatasourcemanager\/collectionview(_:layout:referencesizeforfooterinsection:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ProductsListingDatasourceManager\/collectionView(_:layout:referenceSizeForFooterInSection:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"UICollectionViewDelegateFlowLayout.collectionView(_:layout:referenceSizeForFooterInSection:)"},{"type":"text","text":"."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"collectionView"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UICollectionView","preciseIdentifier":"c:objc(cs)UICollectionView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"layout"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UICollectionViewLayout","preciseIdentifier":"c:objc(cs)UICollectionViewLayout"},{"kind":"text","text":", "},{"kind":"externalParam","text":"referenceSizeForFooterInSection"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"CGSize","preciseIdentifier":"c:@S@CGSize"}],"title":"collectionView(_:layout:referenceSizeForFooterInSection:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@M@Yababa@objc(cs)ProductsListingDatasourceManager(im)collectionView:layout:referenceSizeForFooterInSection:","modules":[{"name":"Yababa"}],"navigatorTitle":[{"kind":"identifier","text":"collectionView:layout:referenceSizeForFooterInSection:"}]},"hierarchy":{"paths":[["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ProductsListingDatasourceManager"]]},"references":{"doc://com.yababaGmbH.yababa/documentation/Yababa":{"role":"collection","title":"Yababa","abstract":[{"type":"text","text":"Getting Started"}],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa","kind":"symbol","type":"topic","url":"\/documentation\/yababa"},"doc://com.yababaGmbH.yababa/documentation/Yababa/ProductsListingDatasourceManager":{"role":"symbol","title":"ProductsListingDatasourceManager","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ProductsListingDatasourceManager"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ProductsListingDatasourceManager","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ProductsListingDatasourceManager"}],"url":"\/documentation\/yababa\/productslistingdatasourcemanager"},"doc://com.yababaGmbH.yababa/documentation/Yababa/ProductsListingDatasourceManager/collectionView(_:layout:referenceSizeForFooterInSection:)":{"role":"symbol","title":"collectionView(_:layout:referenceSizeForFooterInSection:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"collectionView"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UICollectionView","preciseIdentifier":"c:objc(cs)UICollectionView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"layout"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UICollectionViewLayout","preciseIdentifier":"c:objc(cs)UICollectionViewLayout"},{"kind":"text","text":", "},{"kind":"externalParam","text":"referenceSizeForFooterInSection"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"CGSize","preciseIdentifier":"c:@S@CGSize"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ProductsListingDatasourceManager\/collectionView(_:layout:referenceSizeForFooterInSection:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"collectionView:layout:referenceSizeForFooterInSection:"}],"url":"\/documentation\/yababa\/productslistingdatasourcemanager\/collectionview(_:layout:referencesizeforfooterinsection:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"collectionView:layout:referenceSizeForFooterInSection:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"collectionView:layout:referenceSizeForFooterInSection:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"CGSize","preciseIdentifier":"c:@S@CGSize"},{"kind":"text","text":") "},{"kind":"identifier","text":"collectionView:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UICollectionView","preciseIdentifier":"c:objc(cs)UICollectionView"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"collectionView"},{"kind":"text","text":" "},{"kind":"identifier","text":"layout:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UICollectionViewLayout","preciseIdentifier":"c:objc(cs)UICollectionViewLayout"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"collectionViewLayout"},{"kind":"text","text":" "},{"kind":"identifier","text":"referenceSizeForFooterInSection:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"},{"kind":"text","text":")"},{"kind":"internalParam","text":"section"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1ProductsListingDatasourceManager\/title","value":"ProductsListingDatasourceManager"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1ProductsListingDatasourceManager\/fragments","value":[{"kind":"identifier","text":"ProductsListingDatasourceManager"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1ProductsListingDatasourceManager~1collectionView(_:layout:referenceSizeForFooterInSection:)\/title","value":"collectionView:layout:referenceSizeForFooterInSection:"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1ProductsListingDatasourceManager~1collectionView(_:layout:referenceSizeForFooterInSection:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"collectionView:layout:referenceSizeForFooterInSection:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}