{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"collectionView"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"collectionView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UICollectionView","preciseIdentifier":"c:objc(cs)UICollectionView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"viewForSupplementaryElementOfKind"},{"kind":"text","text":" "},{"kind":"internalParam","text":"kind"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"at"},{"kind":"text","text":" "},{"kind":"internalParam","text":"indexPath"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"IndexPath","preciseIdentifier":"s:10Foundation9IndexPathV"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"UICollectionReusableView","preciseIdentifier":"c:objc(cs)UICollectionReusableView"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/yababa\/productslistingdatasourcemanager\/collectionview(_:viewforsupplementaryelementofkind:at:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/yababa\/productslistingdatasourcemanager\/collectionview(_:viewforsupplementaryelementofkind:at:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ProductsListingDatasourceManager\/collectionView(_:viewForSupplementaryElementOfKind:at:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"UICollectionViewDataSource.collectionView(_:viewForSupplementaryElementOfKind:at:)"},{"type":"text","text":"."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"collectionView"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UICollectionView","preciseIdentifier":"c:objc(cs)UICollectionView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"viewForSupplementaryElementOfKind"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"at"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"IndexPath","preciseIdentifier":"s:10Foundation9IndexPathV"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"UICollectionReusableView","preciseIdentifier":"c:objc(cs)UICollectionReusableView"}],"title":"collectionView(_:viewForSupplementaryElementOfKind:at:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@M@Yababa@objc(cs)ProductsListingDatasourceManager(im)collectionView:viewForSupplementaryElementOfKind:atIndexPath:","modules":[{"name":"Yababa"}],"navigatorTitle":[{"kind":"identifier","text":"collectionView:viewForSupplementaryElementOfKind:atIndexPath:"}]},"hierarchy":{"paths":[["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ProductsListingDatasourceManager"]]},"references":{"doc://com.yababaGmbH.yababa/documentation/Yababa/ProductsListingDatasourceManager/collectionView(_:viewForSupplementaryElementOfKind:at:)":{"role":"symbol","title":"collectionView(_:viewForSupplementaryElementOfKind:at:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"collectionView"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UICollectionView","preciseIdentifier":"c:objc(cs)UICollectionView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"viewForSupplementaryElementOfKind"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"at"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"IndexPath","preciseIdentifier":"s:10Foundation9IndexPathV"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"UICollectionReusableView","preciseIdentifier":"c:objc(cs)UICollectionReusableView"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ProductsListingDatasourceManager\/collectionView(_:viewForSupplementaryElementOfKind:at:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"collectionView:viewForSupplementaryElementOfKind:atIndexPath:"}],"url":"\/documentation\/yababa\/productslistingdatasourcemanager\/collectionview(_:viewforsupplementaryelementofkind:at:)"},"doc://com.yababaGmbH.yababa/documentation/Yababa":{"role":"collection","title":"Yababa","abstract":[{"type":"text","text":"Getting Started"}],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa","kind":"symbol","type":"topic","url":"\/documentation\/yababa"},"doc://com.yababaGmbH.yababa/documentation/Yababa/ProductsListingDatasourceManager":{"role":"symbol","title":"ProductsListingDatasourceManager","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ProductsListingDatasourceManager"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ProductsListingDatasourceManager","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ProductsListingDatasourceManager"}],"url":"\/documentation\/yababa\/productslistingdatasourcemanager"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"collectionView:viewForSupplementaryElementOfKind:atIndexPath:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"collectionView:viewForSupplementaryElementOfKind:atIndexPath:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"UICollectionReusableView","preciseIdentifier":"c:objc(cs)UICollectionReusableView"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"collectionView:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UICollectionView","preciseIdentifier":"c:objc(cs)UICollectionView"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"collectionView"},{"kind":"text","text":" "},{"kind":"identifier","text":"viewForSupplementaryElementOfKind:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"kind"},{"kind":"text","text":" "},{"kind":"identifier","text":"atIndexPath:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSIndexPath","preciseIdentifier":"c:objc(cs)NSIndexPath"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"indexPath"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1ProductsListingDatasourceManager~1collectionView(_:viewForSupplementaryElementOfKind:at:)\/title","value":"collectionView:viewForSupplementaryElementOfKind:atIndexPath:"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1ProductsListingDatasourceManager~1collectionView(_:viewForSupplementaryElementOfKind:at:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"collectionView:viewForSupplementaryElementOfKind:atIndexPath:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1ProductsListingDatasourceManager\/title","value":"ProductsListingDatasourceManager"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1ProductsListingDatasourceManager\/fragments","value":[{"kind":"identifier","text":"ProductsListingDatasourceManager"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}