{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@IBAction"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onSubAction"},{"kind":"text","text":"()"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/yababa\/collectionviewitemcell\/onsubaction()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/yababa\/collectionviewitemcell\/onsubaction()"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CollectionViewItemCell\/onSubAction()","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onSubAction"},{"kind":"text","text":"()"}],"title":"onSubAction()","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@M@Yababa@objc(cs)CollectionViewItemCell(im)onSubAction","modules":[{"name":"Yababa"}],"navigatorTitle":[{"kind":"identifier","text":"onSubAction"}]},"hierarchy":{"paths":[["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CollectionViewItemCell"]]},"references":{"doc://com.yababaGmbH.yababa/documentation/Yababa/CollectionViewItemCell/onSubAction()":{"role":"symbol","title":"onSubAction()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onSubAction"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CollectionViewItemCell\/onSubAction()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"onSubAction"}],"url":"\/documentation\/yababa\/collectionviewitemcell\/onsubaction()"},"doc://com.yababaGmbH.yababa/documentation/Yababa/CollectionViewItemCell":{"role":"symbol","title":"CollectionViewItemCell","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CollectionViewItemCell"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CollectionViewItemCell","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CollectionViewItemCell"}],"url":"\/documentation\/yababa\/collectionviewitemcell"},"doc://com.yababaGmbH.yababa/documentation/Yababa":{"role":"collection","title":"Yababa","abstract":[{"type":"text","text":"Getting Started"}],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa","kind":"symbol","type":"topic","url":"\/documentation\/yababa"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"onSubAction"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onSubAction"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"onSubAction"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1CollectionViewItemCell~1onSubAction()\/title","value":"onSubAction"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1CollectionViewItemCell~1onSubAction()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onSubAction"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1CollectionViewItemCell\/title","value":"CollectionViewItemCell"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1CollectionViewItemCell\/fragments","value":[{"kind":"identifier","text":"CollectionViewItemCell"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}