{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setLaunchScreen"},{"kind":"text","text":"("},{"kind":"externalParam","text":"window"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIWindow","preciseIdentifier":"c:objc(cs)UIWindow"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/yababa\/launchscreenmanager\/setlaunchscreen(window:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/yababa\/launchscreenmanager\/setlaunchscreen(window:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/LaunchScreenManager\/setLaunchScreen(window:)","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setLaunchScreen"},{"kind":"text","text":"("},{"kind":"externalParam","text":"window"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIWindow","preciseIdentifier":"c:objc(cs)UIWindow"},{"kind":"text","text":")"}],"title":"setLaunchScreen(window:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@M@Yababa@objc(cs)LaunchScreenManager(im)setLaunchScreenWithWindow:","modules":[{"name":"Yababa"}],"navigatorTitle":[{"kind":"identifier","text":"setLaunchScreenWithWindow:"}]},"hierarchy":{"paths":[["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/LaunchScreenManager"]]},"references":{"doc://com.yababaGmbH.yababa/documentation/Yababa/LaunchScreenManager":{"role":"symbol","title":"LaunchScreenManager","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"LaunchScreenManager"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/LaunchScreenManager","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"LaunchScreenManager"}],"url":"\/documentation\/yababa\/launchscreenmanager"},"doc://com.yababaGmbH.yababa/documentation/Yababa/LaunchScreenManager/setLaunchScreen(window:)":{"role":"symbol","title":"setLaunchScreen(window:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setLaunchScreen"},{"kind":"text","text":"("},{"kind":"externalParam","text":"window"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIWindow","preciseIdentifier":"c:objc(cs)UIWindow"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/LaunchScreenManager\/setLaunchScreen(window:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"setLaunchScreenWithWindow:"}],"url":"\/documentation\/yababa\/launchscreenmanager\/setlaunchscreen(window:)"},"doc://com.yababaGmbH.yababa/documentation/Yababa":{"role":"collection","title":"Yababa","abstract":[{"type":"text","text":"Getting Started"}],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa","kind":"symbol","type":"topic","url":"\/documentation\/yababa"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"setLaunchScreenWithWindow:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setLaunchScreenWithWindow:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"setLaunchScreenWithWindow:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UIWindow","preciseIdentifier":"c:objc(cs)UIWindow"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"window"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1LaunchScreenManager\/title","value":"LaunchScreenManager"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1LaunchScreenManager\/fragments","value":[{"kind":"identifier","text":"LaunchScreenManager"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1LaunchScreenManager~1setLaunchScreen(window:)\/title","value":"setLaunchScreenWithWindow:"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1LaunchScreenManager~1setLaunchScreen(window:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setLaunchScreenWithWindow:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}