{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onAddButtonTapped"},{"kind":"text","text":"()"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/yababa\/tileproduct\/onaddbuttontapped()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/yababa\/tileproduct\/onaddbuttontapped()"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/TileProduct\/onAddButtonTapped()","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onAddButtonTapped"},{"kind":"text","text":"()"}],"title":"onAddButtonTapped()","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@M@Yababa@objc(cs)TileProduct(im)onAddButtonTapped","modules":[{"name":"Yababa"}],"navigatorTitle":[{"kind":"identifier","text":"onAddButtonTapped"}]},"hierarchy":{"paths":[["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/TileProduct"]]},"references":{"doc://com.yababaGmbH.yababa/documentation/Yababa/TileProduct":{"role":"symbol","title":"TileProduct","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TileProduct"}],"abstract":[{"type":"text","text":"WARNING: Not finished. Example implementation for component with Renderable"}],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/TileProduct","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"TileProduct"}],"url":"\/documentation\/yababa\/tileproduct"},"doc://com.yababaGmbH.yababa/documentation/Yababa":{"role":"collection","title":"Yababa","abstract":[{"type":"text","text":"Getting Started"}],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa","kind":"symbol","type":"topic","url":"\/documentation\/yababa"},"doc://com.yababaGmbH.yababa/documentation/Yababa/TileProduct/onAddButtonTapped()":{"role":"symbol","title":"onAddButtonTapped()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onAddButtonTapped"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/TileProduct\/onAddButtonTapped()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"onAddButtonTapped"}],"url":"\/documentation\/yababa\/tileproduct\/onaddbuttontapped()"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"onAddButtonTapped"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onAddButtonTapped"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"onAddButtonTapped"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1TileProduct\/title","value":"TileProduct"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1TileProduct\/fragments","value":[{"kind":"identifier","text":"TileProduct"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1TileProduct~1onAddButtonTapped()\/title","value":"onAddButtonTapped"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1TileProduct~1onAddButtonTapped()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onAddButtonTapped"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}