{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@IBAction"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onViewAreas"},{"kind":"text","text":"()"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/yababa\/invalidaddressviewcontroller\/onviewareas()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/yababa\/invalidaddressviewcontroller\/onviewareas()"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/InvalidAddressViewController\/onViewAreas()","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onViewAreas"},{"kind":"text","text":"()"}],"title":"onViewAreas()","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@M@Yababa@objc(cs)InvalidAddressViewController(im)onViewAreas","modules":[{"name":"Yababa"}],"navigatorTitle":[{"kind":"identifier","text":"onViewAreas"}]},"hierarchy":{"paths":[["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/InvalidAddressViewController"]]},"references":{"doc://com.yababaGmbH.yababa/documentation/Yababa/InvalidAddressViewController/onViewAreas()":{"role":"symbol","title":"onViewAreas()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onViewAreas"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/InvalidAddressViewController\/onViewAreas()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"onViewAreas"}],"url":"\/documentation\/yababa\/invalidaddressviewcontroller\/onviewareas()"},"doc://com.yababaGmbH.yababa/documentation/Yababa":{"role":"collection","title":"Yababa","abstract":[{"type":"text","text":"Getting Started"}],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa","kind":"symbol","type":"topic","url":"\/documentation\/yababa"},"doc://com.yababaGmbH.yababa/documentation/Yababa/InvalidAddressViewController":{"role":"symbol","title":"InvalidAddressViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"InvalidAddressViewController"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/InvalidAddressViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"InvalidAddressViewController"}],"url":"\/documentation\/yababa\/invalidaddressviewcontroller"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"onViewAreas"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onViewAreas"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"onViewAreas"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1InvalidAddressViewController~1onViewAreas()\/title","value":"onViewAreas"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1InvalidAddressViewController~1onViewAreas()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onViewAreas"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1InvalidAddressViewController\/title","value":"InvalidAddressViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1InvalidAddressViewController\/fragments","value":[{"kind":"identifier","text":"InvalidAddressViewController"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}