{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@IBAction"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onDone"},{"kind":"text","text":"()"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/yababa\/languageselectionviewcontroller\/ondone()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/yababa\/languageselectionviewcontroller\/ondone()"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/LanguageSelectionViewController\/onDone()","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onDone"},{"kind":"text","text":"()"}],"title":"onDone()","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@M@Yababa@objc(cs)LanguageSelectionViewController(im)onDone","modules":[{"name":"Yababa"}],"navigatorTitle":[{"kind":"identifier","text":"onDone"}]},"hierarchy":{"paths":[["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/LanguageSelectionViewController"]]},"references":{"doc://com.yababaGmbH.yababa/documentation/Yababa/LanguageSelectionViewController":{"role":"symbol","title":"LanguageSelectionViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"LanguageSelectionViewController"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/LanguageSelectionViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"LanguageSelectionViewController"}],"url":"\/documentation\/yababa\/languageselectionviewcontroller"},"doc://com.yababaGmbH.yababa/documentation/Yababa/LanguageSelectionViewController/onDone()":{"role":"symbol","title":"onDone()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onDone"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/LanguageSelectionViewController\/onDone()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"onDone"}],"url":"\/documentation\/yababa\/languageselectionviewcontroller\/ondone()"},"doc://com.yababaGmbH.yababa/documentation/Yababa":{"role":"collection","title":"Yababa","abstract":[{"type":"text","text":"Getting Started"}],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa","kind":"symbol","type":"topic","url":"\/documentation\/yababa"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"onDone"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onDone"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"onDone"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1LanguageSelectionViewController\/title","value":"LanguageSelectionViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1LanguageSelectionViewController\/fragments","value":[{"kind":"identifier","text":"LanguageSelectionViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1LanguageSelectionViewController~1onDone()\/title","value":"onDone"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1LanguageSelectionViewController~1onDone()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onDone"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}