{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"voucherView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/VoucherView","preciseIdentifier":"c:@M@Yababa@objc(cs)VoucherView","text":"VoucherView"},{"kind":"text","text":"!"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/yababa\/vouchercell\/voucherview"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/VoucherCell\/voucherView","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"voucherView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"VoucherView","preciseIdentifier":"c:@M@Yababa@objc(cs)VoucherView"},{"kind":"text","text":"!"}],"title":"voucherView","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"s:6Yababa11VoucherCellC11voucherViewAA0bE0CSgvp","modules":[{"name":"Yababa"}]},"hierarchy":{"paths":[["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/VoucherCell"]]},"references":{"doc://com.yababaGmbH.yababa/documentation/Yababa/VoucherView":{"role":"symbol","title":"VoucherView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"VoucherView"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/VoucherView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"VoucherView"}],"url":"\/documentation\/yababa\/voucherview"},"doc://com.yababaGmbH.yababa/documentation/Yababa/VoucherCell":{"role":"symbol","title":"VoucherCell","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"VoucherCell"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/VoucherCell","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"VoucherCell"}],"url":"\/documentation\/yababa\/vouchercell"},"doc://com.yababaGmbH.yababa/documentation/Yababa/VoucherCell/voucherView":{"role":"symbol","title":"voucherView","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"voucherView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"VoucherView","preciseIdentifier":"c:@M@Yababa@objc(cs)VoucherView"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/VoucherCell\/voucherView","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/vouchercell\/voucherview"},"doc://com.yababaGmbH.yababa/documentation/Yababa":{"role":"collection","title":"Yababa","abstract":[{"type":"text","text":"Getting Started"}],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa","kind":"symbol","type":"topic","url":"\/documentation\/yababa"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1VoucherView\/title","value":"VoucherView"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1VoucherView\/fragments","value":[{"kind":"identifier","text":"VoucherView"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1VoucherCell\/title","value":"VoucherCell"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1VoucherCell\/fragments","value":[{"kind":"identifier","text":"VoucherCell"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}