{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"didResolveDeepLink"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"result"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DeepLinkResult","preciseIdentifier":"c:objc(cs)AppsFlyerDeepLinkResult"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/yababa\/appsflyermanager\/didresolvedeeplink(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/yababa\/appsflyermanager\/didresolvedeeplink(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AppsFlyerManager\/didResolveDeepLink(_:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"DeepLinkDelegate.didResolveDeepLink(_:)"},{"type":"text","text":"."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"didResolveDeepLink"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"DeepLinkResult","preciseIdentifier":"c:objc(cs)AppsFlyerDeepLinkResult"},{"kind":"text","text":")"}],"title":"didResolveDeepLink(_:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@M@Yababa@objc(cs)AppsFlyerManager(im)didResolveDeepLink:","modules":[{"name":"Yababa"}],"navigatorTitle":[{"kind":"identifier","text":"didResolveDeepLink:"}]},"hierarchy":{"paths":[["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AppsFlyerManager"]]},"references":{"doc://com.yababaGmbH.yababa/documentation/Yababa/AppsFlyerManager":{"role":"symbol","title":"AppsFlyerManager","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AppsFlyerManager"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AppsFlyerManager","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AppsFlyerManager"}],"url":"\/documentation\/yababa\/appsflyermanager"},"doc://com.yababaGmbH.yababa/documentation/Yababa/AppsFlyerManager/didResolveDeepLink(_:)":{"role":"symbol","title":"didResolveDeepLink(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"didResolveDeepLink"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"DeepLinkResult","preciseIdentifier":"c:objc(cs)AppsFlyerDeepLinkResult"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AppsFlyerManager\/didResolveDeepLink(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"didResolveDeepLink:"}],"url":"\/documentation\/yababa\/appsflyermanager\/didresolvedeeplink(_:)"},"doc://com.yababaGmbH.yababa/documentation/Yababa":{"role":"collection","title":"Yababa","abstract":[{"type":"text","text":"Getting Started"}],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa","kind":"symbol","type":"topic","url":"\/documentation\/yababa"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"didResolveDeepLink:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"didResolveDeepLink:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"didResolveDeepLink:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AppsFlyerDeepLinkResult","preciseIdentifier":"c:objc(cs)AppsFlyerDeepLinkResult"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"result"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1AppsFlyerManager\/title","value":"AppsFlyerManager"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1AppsFlyerManager\/fragments","value":[{"kind":"identifier","text":"AppsFlyerManager"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1AppsFlyerManager~1didResolveDeepLink(_:)\/title","value":"didResolveDeepLink:"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1AppsFlyerManager~1didResolveDeepLink(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"didResolveDeepLink:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}