{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"voucher"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/VoucherView","preciseIdentifier":"c:@M@Yababa@objc(cs)VoucherView","text":"VoucherView"},{"kind":"text","text":"."},{"kind":"typeIdentifier","identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/VoucherView\/Data","preciseIdentifier":"s:6Yababa11VoucherViewC4DataV","text":"Data"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/yababa\/discountscollectionview\/item\/voucher(_:)"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/DiscountsCollectionView\/Item\/voucher(_:)","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"voucher"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"VoucherView","preciseIdentifier":"c:@M@Yababa@objc(cs)VoucherView"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"Data","preciseIdentifier":"s:6Yababa11VoucherViewC4DataV"},{"kind":"text","text":")"}],"title":"DiscountsCollectionView.Item.voucher(_:)","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"s:6Yababa23DiscountsCollectionViewC4ItemO7voucheryAeA07VoucherD0C4DataVcAEmF","modules":[{"name":"Yababa"}]},"hierarchy":{"paths":[["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/DiscountsCollectionView","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/DiscountsCollectionView\/Item"]]},"references":{"doc://com.yababaGmbH.yababa/documentation/Yababa/DiscountsCollectionView":{"role":"symbol","title":"DiscountsCollectionView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DiscountsCollectionView"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/DiscountsCollectionView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DiscountsCollectionView"}],"url":"\/documentation\/yababa\/discountscollectionview"},"doc://com.yababaGmbH.yababa/documentation/Yababa/DiscountsCollectionView/Item":{"role":"symbol","title":"DiscountsCollectionView.Item","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"Item"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/DiscountsCollectionView\/Item","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Item"}],"url":"\/documentation\/yababa\/discountscollectionview\/item"},"doc://com.yababaGmbH.yababa/documentation/Yababa":{"role":"collection","title":"Yababa","abstract":[{"type":"text","text":"Getting Started"}],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa","kind":"symbol","type":"topic","url":"\/documentation\/yababa"},"doc://com.yababaGmbH.yababa/documentation/Yababa/DiscountsCollectionView/Item/voucher(_:)":{"role":"symbol","title":"DiscountsCollectionView.Item.voucher(_:)","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"voucher"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"VoucherView","preciseIdentifier":"c:@M@Yababa@objc(cs)VoucherView"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"Data","preciseIdentifier":"s:6Yababa11VoucherViewC4DataV"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/DiscountsCollectionView\/Item\/voucher(_:)","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/discountscollectionview\/item\/voucher(_:)"},"doc://com.yababaGmbH.yababa/documentation/Yababa/VoucherView":{"role":"symbol","title":"VoucherView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"VoucherView"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/VoucherView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"VoucherView"}],"url":"\/documentation\/yababa\/voucherview"},"doc://com.yababaGmbH.yababa/documentation/Yababa/VoucherView/Data":{"role":"symbol","title":"VoucherView.Data","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"Data"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/VoucherView\/Data","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Data"}],"url":"\/documentation\/yababa\/voucherview\/data"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1DiscountsCollectionView\/title","value":"DiscountsCollectionView"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1DiscountsCollectionView\/fragments","value":[{"kind":"identifier","text":"DiscountsCollectionView"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1VoucherView\/title","value":"VoucherView"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1VoucherView\/fragments","value":[{"kind":"identifier","text":"VoucherView"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}