{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"promptEnablePushNotificationFromSettings"},{"kind":"text","text":"()"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/yababa\/pushnotificationinteractorprotocol\/promptenablepushnotificationfromsettings()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/yababa\/pushnotificationinteractorprotocol\/promptenablepushnotificationfromsettings()"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/PushNotificationInteractorProtocol\/promptEnablePushNotificationFromSettings()","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"promptEnablePushNotificationFromSettings"}],"role":"symbol","title":"promptEnablePushNotificationFromSettings()","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"promptEnablePushNotificationFromSettings"},{"kind":"text","text":"()"}],"symbolKind":"method","externalID":"c:@M@Yababa@objc(pl)PushNotificationInteractorProtocol(im)promptEnablePushNotificationFromSettings","required":true,"modules":[{"name":"Yababa"}]},"hierarchy":{"paths":[["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/PushNotificationInteractorProtocol"]]},"references":{"doc://com.yababaGmbH.yababa/documentation/Yababa/PushNotificationInteractorProtocol/promptEnablePushNotificationFromSettings()":{"navigatorTitle":[{"kind":"identifier","text":"promptEnablePushNotificationFromSettings"}],"role":"symbol","title":"promptEnablePushNotificationFromSettings()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"promptEnablePushNotificationFromSettings"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/PushNotificationInteractorProtocol\/promptEnablePushNotificationFromSettings()","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/yababa\/pushnotificationinteractorprotocol\/promptenablepushnotificationfromsettings()"},"doc://com.yababaGmbH.yababa/documentation/Yababa/PushNotificationInteractorProtocol":{"role":"symbol","title":"PushNotificationInteractorProtocol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"PushNotificationInteractorProtocol"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/PushNotificationInteractorProtocol","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PushNotificationInteractorProtocol"}],"url":"\/documentation\/yababa\/pushnotificationinteractorprotocol"},"doc://com.yababaGmbH.yababa/documentation/Yababa":{"role":"collection","title":"Yababa","abstract":[{"type":"text","text":"Getting Started"}],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa","kind":"symbol","type":"topic","url":"\/documentation\/yababa"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"promptEnablePushNotificationFromSettings"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"promptEnablePushNotificationFromSettings"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"promptEnablePushNotificationFromSettings"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1PushNotificationInteractorProtocol~1promptEnablePushNotificationFromSettings()\/title","value":"promptEnablePushNotificationFromSettings"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1PushNotificationInteractorProtocol~1promptEnablePushNotificationFromSettings()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"promptEnablePushNotificationFromSettings"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1PushNotificationInteractorProtocol\/title","value":"PushNotificationInteractorProtocol"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1PushNotificationInteractorProtocol\/fragments","value":[{"kind":"identifier","text":"PushNotificationInteractorProtocol"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}