{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"profile"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ProfileClass","preciseIdentifier":"c:objc(cs)ProfileClass","text":"ProfileClass"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/yababa\/editprofileviewcontroller\/profile"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/yababa\/editprofileviewcontroller\/profile"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/EditProfileViewController\/profile","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"profile"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ProfileClass","preciseIdentifier":"c:objc(cs)ProfileClass"}],"title":"profile","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:objc(cs)EditProfileViewController(py)profile","modules":[{"name":"Yababa"}],"navigatorTitle":[{"kind":"identifier","text":"profile"}]},"hierarchy":{"paths":[["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/EditProfileViewController"]]},"references":{"doc://com.yababaGmbH.yababa/documentation/Yababa/EditProfileViewController":{"role":"symbol","title":"EditProfileViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"EditProfileViewController"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/EditProfileViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"EditProfileViewController"}],"url":"\/documentation\/yababa\/editprofileviewcontroller"},"doc://com.yababaGmbH.yababa/documentation/Yababa/ProfileClass":{"role":"symbol","title":"ProfileClass","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ProfileClass"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ProfileClass","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ProfileClass"}],"url":"\/documentation\/yababa\/profileclass"},"doc://com.yababaGmbH.yababa/documentation/Yababa/EditProfileViewController/profile":{"role":"symbol","title":"profile","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"profile"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ProfileClass","preciseIdentifier":"c:objc(cs)ProfileClass"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/EditProfileViewController\/profile","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"profile"}],"url":"\/documentation\/yababa\/editprofileviewcontroller\/profile"},"doc://com.yababaGmbH.yababa/documentation/Yababa":{"role":"collection","title":"Yababa","abstract":[{"type":"text","text":"Getting Started"}],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa","kind":"symbol","type":"topic","url":"\/documentation\/yababa"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"profile"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"profile"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":", "},{"kind":"keyword","text":"nonnull"},{"kind":"text","text":") "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ProfileClass","preciseIdentifier":"c:objc(cs)ProfileClass","text":"ProfileClass"},{"kind":"text","text":" * "},{"kind":"identifier","text":"profile"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1EditProfileViewController\/title","value":"EditProfileViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1EditProfileViewController\/fragments","value":[{"kind":"identifier","text":"EditProfileViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1ProfileClass\/title","value":"ProfileClass"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1ProfileClass\/fragments","value":[{"kind":"identifier","text":"ProfileClass"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1EditProfileViewController~1profile\/title","value":"profile"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1EditProfileViewController~1profile\/fragments","value":[{"kind":"identifier","text":"profile"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}