{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"proceedToLoginScreen"},{"kind":"text","text":"("},{"kind":"externalParam","text":"profile"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/Profile","preciseIdentifier":"c:@M@Yababa@objc(cs)Profile","text":"Profile"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/yababa\/joinsceneviewcontroller\/proceedtologinscreen(profile:)"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/JoinSceneViewController\/proceedToLoginScreen(profile:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"JoinSceneViewControllerProtocol.proceedToLoginScreen(profile:)"},{"type":"text","text":"."}],"kind":"symbol","metadata":{"role":"symbol","title":"proceedToLoginScreen(profile:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"proceedToLoginScreen"},{"kind":"text","text":"("},{"kind":"externalParam","text":"profile"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Profile","preciseIdentifier":"c:@M@Yababa@objc(cs)Profile"},{"kind":"text","text":")"}],"symbolKind":"method","externalID":"s:6Yababa23JoinSceneViewControllerC20proceedToLoginScreen7profileyAA7ProfileC_tF","extendedModule":"Yababa","modules":[{"name":"Yababa"}]},"hierarchy":{"paths":[["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/JoinSceneViewController","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/JoinSceneViewController\/JoinSceneViewControllerProtocol-Implementations"]]},"references":{"doc://com.yababaGmbH.yababa/documentation/Yababa":{"role":"collection","title":"Yababa","abstract":[{"type":"text","text":"Getting Started"}],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa","kind":"symbol","type":"topic","url":"\/documentation\/yababa"},"doc://com.yababaGmbH.yababa/documentation/Yababa/JoinSceneViewController/proceedToLoginScreen(profile:)":{"role":"symbol","title":"proceedToLoginScreen(profile:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"proceedToLoginScreen"},{"kind":"text","text":"("},{"kind":"externalParam","text":"profile"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Profile","preciseIdentifier":"c:@M@Yababa@objc(cs)Profile"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/JoinSceneViewController\/proceedToLoginScreen(profile:)","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/joinsceneviewcontroller\/proceedtologinscreen(profile:)"},"doc://com.yababaGmbH.yababa/documentation/Yababa/JoinSceneViewController":{"role":"symbol","title":"JoinSceneViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"JoinSceneViewController"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/JoinSceneViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"JoinSceneViewController"}],"url":"\/documentation\/yababa\/joinsceneviewcontroller"},"doc://com.yababaGmbH.yababa/documentation/Yababa/Profile":{"role":"symbol","title":"Profile","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Profile"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/Profile","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Profile"}],"url":"\/documentation\/yababa\/profile"},"doc://com.yababaGmbH.yababa/documentation/Yababa/JoinSceneViewController/JoinSceneViewControllerProtocol-Implementations":{"role":"collectionGroup","title":"JoinSceneViewControllerProtocol Implementations","abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/JoinSceneViewController\/JoinSceneViewControllerProtocol-Implementations","kind":"article","type":"topic","url":"\/documentation\/yababa\/joinsceneviewcontroller\/joinsceneviewcontrollerprotocol-implementations"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1JoinSceneViewController\/title","value":"JoinSceneViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1JoinSceneViewController\/fragments","value":[{"kind":"identifier","text":"JoinSceneViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1Profile\/title","value":"Profile"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1Profile\/fragments","value":[{"kind":"identifier","text":"Profile"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}