{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@IBAction"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"openAppStore"},{"kind":"text","text":"()"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/yababa\/appupdateprompt\/openappstore()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/yababa\/appupdateprompt\/openappstore()"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AppUpdatePrompt\/openAppStore()","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"openAppStore"},{"kind":"text","text":"()"}],"title":"openAppStore()","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@M@Yababa@objc(cs)AppUpdatePrompt(im)openAppStore","modules":[{"name":"Yababa"}],"navigatorTitle":[{"kind":"identifier","text":"openAppStore"}]},"hierarchy":{"paths":[["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AppUpdatePrompt"]]},"references":{"doc://com.yababaGmbH.yababa/documentation/Yababa/AppUpdatePrompt":{"role":"symbol","title":"AppUpdatePrompt","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AppUpdatePrompt"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AppUpdatePrompt","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AppUpdatePrompt"}],"url":"\/documentation\/yababa\/appupdateprompt"},"doc://com.yababaGmbH.yababa/documentation/Yababa":{"role":"collection","title":"Yababa","abstract":[{"type":"text","text":"Getting Started"}],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa","kind":"symbol","type":"topic","url":"\/documentation\/yababa"},"doc://com.yababaGmbH.yababa/documentation/Yababa/AppUpdatePrompt/openAppStore()":{"role":"symbol","title":"openAppStore()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"openAppStore"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AppUpdatePrompt\/openAppStore()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"openAppStore"}],"url":"\/documentation\/yababa\/appupdateprompt\/openappstore()"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"openAppStore"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"openAppStore"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"openAppStore"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1AppUpdatePrompt\/title","value":"AppUpdatePrompt"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1AppUpdatePrompt\/fragments","value":[{"kind":"identifier","text":"AppUpdatePrompt"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1AppUpdatePrompt~1openAppStore()\/title","value":"openAppStore"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1AppUpdatePrompt~1openAppStore()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"openAppStore"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}