{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"subscribed"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/yababa\/subscriptionstatus\/subscribed"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/yababa\/subscriptionstatus\/subscribed"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/SubscriptionStatus\/subscribed","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"subscribed"}],"title":"SubscriptionStatus.subscribed","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@M@Yababa@E@SubscriptionStatus@SubscriptionStatusSubscribed","modules":[{"name":"Yababa"}],"navigatorTitle":[{"kind":"identifier","text":"SubscriptionStatusSubscribed"}]},"hierarchy":{"paths":[["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/SubscriptionStatus"]]},"references":{"doc://com.yababaGmbH.yababa/documentation/Yababa/SubscriptionStatus":{"role":"symbol","title":"SubscriptionStatus","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SubscriptionStatus"}],"abstract":[{"type":"text","text":"OPTED_IN: subscribed, and explicitly opted in."},{"type":"text","text":" "},{"type":"text","text":"SUBSCRIBED: subscribed, but not explicitly opted in."},{"type":"text","text":" "},{"type":"text","text":"UNSUBSCRIBED: unsubscribed and\/or explicitly opted out."}],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/SubscriptionStatus","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SubscriptionStatus"}],"url":"\/documentation\/yababa\/subscriptionstatus"},"doc://com.yababaGmbH.yababa/documentation/Yababa/SubscriptionStatus/subscribed":{"role":"symbol","title":"SubscriptionStatus.subscribed","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"subscribed"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/SubscriptionStatus\/subscribed","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SubscriptionStatusSubscribed"}],"url":"\/documentation\/yababa\/subscriptionstatus\/subscribed"},"doc://com.yababaGmbH.yababa/documentation/Yababa":{"role":"collection","title":"Yababa","abstract":[{"type":"text","text":"Getting Started"}],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa","kind":"symbol","type":"topic","url":"\/documentation\/yababa"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"SubscriptionStatusSubscribed"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SubscriptionStatusSubscribed"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"SubscriptionStatusSubscribed"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1SubscriptionStatus\/title","value":"SubscriptionStatus"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1SubscriptionStatus\/fragments","value":[{"kind":"identifier","text":"SubscriptionStatus"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1SubscriptionStatus~1subscribed\/title","value":"SubscriptionStatusSubscribed"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1SubscriptionStatus~1subscribed\/fragments","value":[{"kind":"identifier","text":"SubscriptionStatusSubscribed"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}