{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"optional"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"response"},{"kind":"text","text":"("},{"kind":"externalParam","text":"forContactUs"},{"kind":"text","text":" "},{"kind":"internalParam","text":"response"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ResponseClass","preciseIdentifier":"c:objc(cs)ResponseClass","text":"ResponseClass"},{"kind":"text","text":"!)"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/yababa\/indelegate\/response(forcontactus:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/yababa\/indelegate\/response(forcontactus:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/InDelegate\/response(forContactUs:)","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"response"},{"kind":"text","text":"("},{"kind":"externalParam","text":"forContactUs"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ResponseClass","preciseIdentifier":"c:objc(cs)ResponseClass"},{"kind":"text","text":"!)"}],"title":"response(forContactUs:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:objc(pl)InDelegate(im)ResponseForContactUs:","modules":[{"name":"Yababa"}],"navigatorTitle":[{"kind":"identifier","text":"ResponseForContactUs:"}]},"hierarchy":{"paths":[["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/InDelegate"]]},"references":{"doc://com.yababaGmbH.yababa/documentation/Yababa":{"role":"collection","title":"Yababa","abstract":[{"type":"text","text":"Getting Started"}],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa","kind":"symbol","type":"topic","url":"\/documentation\/yababa"},"doc://com.yababaGmbH.yababa/documentation/Yababa/InDelegate/response(forContactUs:)":{"role":"symbol","title":"response(forContactUs:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"response"},{"kind":"text","text":"("},{"kind":"externalParam","text":"forContactUs"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ResponseClass","preciseIdentifier":"c:objc(cs)ResponseClass"},{"kind":"text","text":"!)"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/InDelegate\/response(forContactUs:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ResponseForContactUs:"}],"url":"\/documentation\/yababa\/indelegate\/response(forcontactus:)"},"doc://com.yababaGmbH.yababa/documentation/Yababa/InDelegate":{"role":"symbol","title":"InDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"InDelegate"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/InDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"InDelegate"}],"url":"\/documentation\/yababa\/indelegate"},"doc://com.yababaGmbH.yababa/documentation/Yababa/ResponseClass":{"role":"symbol","title":"ResponseClass","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ResponseClass"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ResponseClass","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ResponseClass"}],"url":"\/documentation\/yababa\/responseclass"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"ResponseForContactUs:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"ResponseForContactUs:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"ResponseForContactUs:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ResponseClass","preciseIdentifier":"c:objc(cs)ResponseClass","text":"ResponseClass"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"response"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1InDelegate~1response(forContactUs:)\/title","value":"ResponseForContactUs:"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1InDelegate~1response(forContactUs:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"ResponseForContactUs:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1InDelegate\/title","value":"InDelegate"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1InDelegate\/fragments","value":[{"kind":"identifier","text":"InDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1ResponseClass\/title","value":"ResponseClass"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1ResponseClass\/fragments","value":[{"kind":"identifier","text":"ResponseClass"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}