{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"authenticationPresentingViewController"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/yababa\/stripegatewayviewcontroller\/authenticationpresentingviewcontroller()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/yababa\/stripegatewayviewcontroller\/authenticationpresentingviewcontroller()"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/StripeGatewayViewController\/authenticationPresentingViewController()","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"STPAuthenticationContext.authenticationPresentingViewController()"},{"type":"text","text":"."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"authenticationPresentingViewController"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"}],"title":"authenticationPresentingViewController()","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@M@Yababa@objc(cs)StripeGatewayViewController(im)authenticationPresentingViewController","modules":[{"name":"Yababa"}],"navigatorTitle":[{"kind":"identifier","text":"authenticationPresentingViewController"}]},"hierarchy":{"paths":[["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/StripeGatewayViewController"]]},"references":{"doc://com.yababaGmbH.yababa/documentation/Yababa":{"role":"collection","title":"Yababa","abstract":[{"type":"text","text":"Getting Started"}],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa","kind":"symbol","type":"topic","url":"\/documentation\/yababa"},"doc://com.yababaGmbH.yababa/documentation/Yababa/StripeGatewayViewController/authenticationPresentingViewController()":{"role":"symbol","title":"authenticationPresentingViewController()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"authenticationPresentingViewController"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/StripeGatewayViewController\/authenticationPresentingViewController()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"authenticationPresentingViewController"}],"url":"\/documentation\/yababa\/stripegatewayviewcontroller\/authenticationpresentingviewcontroller()"},"doc://com.yababaGmbH.yababa/documentation/Yababa/StripeGatewayViewController":{"role":"symbol","title":"StripeGatewayViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"StripeGatewayViewController"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/StripeGatewayViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"StripeGatewayViewController"}],"url":"\/documentation\/yababa\/stripegatewayviewcontroller"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"authenticationPresentingViewController"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"authenticationPresentingViewController"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"authenticationPresentingViewController"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1StripeGatewayViewController~1authenticationPresentingViewController()\/title","value":"authenticationPresentingViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1StripeGatewayViewController~1authenticationPresentingViewController()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"authenticationPresentingViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1StripeGatewayViewController\/title","value":"StripeGatewayViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1StripeGatewayViewController\/fragments","value":[{"kind":"identifier","text":"StripeGatewayViewController"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}