{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"configure"},{"kind":"text","text":"("},{"kind":"externalParam","text":"pushNotificationManagerInteractor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/PushNotificationInteractorProtocol","preciseIdentifier":"c:@M@Yababa@objc(pl)PushNotificationInteractorProtocol","text":"PushNotificationInteractorProtocol"},{"kind":"text","text":", "},{"kind":"externalParam","text":"pushNotificationMarketingManager"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/PushNotificationMarketingManager","preciseIdentifier":"s:6Yababa32PushNotificationMarketingManagerP","text":"PushNotificationMarketingManager"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/yababa\/pushnotificationsmanager\/configure(pushnotificationmanagerinteractor:pushnotificationmarketingmanager:)"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/PushNotificationsManager\/configure(pushNotificationManagerInteractor:pushNotificationMarketingManager:)","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"configure"},{"kind":"text","text":"("},{"kind":"externalParam","text":"pushNotificationManagerInteractor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"PushNotificationInteractorProtocol","preciseIdentifier":"c:@M@Yababa@objc(pl)PushNotificationInteractorProtocol"},{"kind":"text","text":", "},{"kind":"externalParam","text":"pushNotificationMarketingManager"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"PushNotificationMarketingManager","preciseIdentifier":"s:6Yababa32PushNotificationMarketingManagerP"},{"kind":"text","text":")"}],"title":"configure(pushNotificationManagerInteractor:pushNotificationMarketingManager:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"s:6Yababa24PushNotificationsManagerC9configure016pushNotificationD10Interactor0fg9MarketingD0yAA0bgH8Protocol_p_AA0bgiD0_ptF","modules":[{"name":"Yababa"}]},"hierarchy":{"paths":[["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/PushNotificationsManager"]]},"references":{"doc://com.yababaGmbH.yababa/documentation/Yababa/PushNotificationsManager/configure(pushNotificationManagerInteractor:pushNotificationMarketingManager:)":{"role":"symbol","title":"configure(pushNotificationManagerInteractor:pushNotificationMarketingManager:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"configure"},{"kind":"text","text":"("},{"kind":"externalParam","text":"pushNotificationManagerInteractor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"PushNotificationInteractorProtocol","preciseIdentifier":"c:@M@Yababa@objc(pl)PushNotificationInteractorProtocol"},{"kind":"text","text":", "},{"kind":"externalParam","text":"pushNotificationMarketingManager"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"PushNotificationMarketingManager","preciseIdentifier":"s:6Yababa32PushNotificationMarketingManagerP"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/PushNotificationsManager\/configure(pushNotificationManagerInteractor:pushNotificationMarketingManager:)","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/pushnotificationsmanager\/configure(pushnotificationmanagerinteractor:pushnotificationmarketingmanager:)"},"doc://com.yababaGmbH.yababa/documentation/Yababa":{"role":"collection","title":"Yababa","abstract":[{"type":"text","text":"Getting Started"}],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa","kind":"symbol","type":"topic","url":"\/documentation\/yababa"},"doc://com.yababaGmbH.yababa/documentation/Yababa/PushNotificationMarketingManager":{"role":"symbol","title":"PushNotificationMarketingManager","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"PushNotificationMarketingManager"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/PushNotificationMarketingManager","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PushNotificationMarketingManager"}],"url":"\/documentation\/yababa\/pushnotificationmarketingmanager"},"doc://com.yababaGmbH.yababa/documentation/Yababa/PushNotificationInteractorProtocol":{"role":"symbol","title":"PushNotificationInteractorProtocol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"PushNotificationInteractorProtocol"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/PushNotificationInteractorProtocol","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PushNotificationInteractorProtocol"}],"url":"\/documentation\/yababa\/pushnotificationinteractorprotocol"},"doc://com.yababaGmbH.yababa/documentation/Yababa/PushNotificationsManager":{"role":"symbol","title":"PushNotificationsManager","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PushNotificationsManager"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/PushNotificationsManager","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PushNotificationsManager"}],"url":"\/documentation\/yababa\/pushnotificationsmanager"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1PushNotificationInteractorProtocol\/title","value":"PushNotificationInteractorProtocol"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1PushNotificationInteractorProtocol\/fragments","value":[{"kind":"identifier","text":"PushNotificationInteractorProtocol"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1PushNotificationsManager\/title","value":"PushNotificationsManager"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1PushNotificationsManager\/fragments","value":[{"kind":"identifier","text":"PushNotificationsManager"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}