{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getUserPushSubscriptionStatus"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/SubscriptionStatus","preciseIdentifier":"c:@M@Yababa@E@SubscriptionStatus","text":"SubscriptionStatus"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/yababa\/pushnotificationsmanager\/getuserpushsubscriptionstatus()"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/PushNotificationsManager\/getUserPushSubscriptionStatus()","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"role":"symbol","title":"getUserPushSubscriptionStatus()","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getUserPushSubscriptionStatus"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"SubscriptionStatus","preciseIdentifier":"c:@M@Yababa@E@SubscriptionStatus"}],"symbolKind":"method","externalID":"s:6Yababa24PushNotificationsManagerC07getUserB18SubscriptionStatusAA0gH0OyF","extendedModule":"Yababa","modules":[{"name":"Yababa"}]},"hierarchy":{"paths":[["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/PushNotificationsManager"]]},"references":{"doc://com.yababaGmbH.yababa/documentation/Yababa/PushNotificationsManager":{"role":"symbol","title":"PushNotificationsManager","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PushNotificationsManager"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/PushNotificationsManager","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PushNotificationsManager"}],"url":"\/documentation\/yababa\/pushnotificationsmanager"},"doc://com.yababaGmbH.yababa/documentation/Yababa":{"role":"collection","title":"Yababa","abstract":[{"type":"text","text":"Getting Started"}],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa","kind":"symbol","type":"topic","url":"\/documentation\/yababa"},"doc://com.yababaGmbH.yababa/documentation/Yababa/SubscriptionStatus":{"role":"symbol","title":"SubscriptionStatus","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SubscriptionStatus"}],"abstract":[{"type":"text","text":"OPTED_IN: subscribed, and explicitly opted in."},{"type":"text","text":" "},{"type":"text","text":"SUBSCRIBED: subscribed, but not explicitly opted in."},{"type":"text","text":" "},{"type":"text","text":"UNSUBSCRIBED: unsubscribed and\/or explicitly opted out."}],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/SubscriptionStatus","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SubscriptionStatus"}],"url":"\/documentation\/yababa\/subscriptionstatus"},"doc://com.yababaGmbH.yababa/documentation/Yababa/PushNotificationsManager/getUserPushSubscriptionStatus()":{"role":"symbol","title":"getUserPushSubscriptionStatus()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getUserPushSubscriptionStatus"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"SubscriptionStatus","preciseIdentifier":"c:@M@Yababa@E@SubscriptionStatus"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/PushNotificationsManager\/getUserPushSubscriptionStatus()","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/pushnotificationsmanager\/getuserpushsubscriptionstatus()"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1PushNotificationsManager\/title","value":"PushNotificationsManager"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1PushNotificationsManager\/fragments","value":[{"kind":"identifier","text":"PushNotificationsManager"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1SubscriptionStatus\/title","value":"SubscriptionStatus"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1SubscriptionStatus\/fragments","value":[{"kind":"identifier","text":"SubscriptionStatus"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}