{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"didRequestAutocompletePredictions"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"viewController"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GMSAutocompleteViewController","preciseIdentifier":"c:objc(cs)GMSAutocompleteViewController"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/yababa\/mapsviewcontroller\/didrequestautocompletepredictions(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/yababa\/mapsviewcontroller\/didrequestautocompletepredictions(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/MapsViewController\/didRequestAutocompletePredictions(_:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"GMSAutocompleteViewControllerDelegate.didRequestAutocompletePredictions(_:)"},{"type":"text","text":"."}],"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"didRequestAutocompletePredictions:"}],"role":"symbol","title":"didRequestAutocompletePredictions(_:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"didRequestAutocompletePredictions"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"GMSAutocompleteViewController","preciseIdentifier":"c:objc(cs)GMSAutocompleteViewController"},{"kind":"text","text":")"}],"symbolKind":"method","externalID":"c:@CM@Yababa@objc(cs)MapsViewController(im)didRequestAutocompletePredictions:","extendedModule":"Yababa","modules":[{"name":"Yababa"}]},"hierarchy":{"paths":[["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/MapsViewController","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/MapsViewController\/GMSAutocompleteViewControllerDelegate-Implementations"]]},"references":{"doc://com.yababaGmbH.yababa/documentation/Yababa/MapsViewController":{"role":"symbol","title":"MapsViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MapsViewController"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/MapsViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MapsViewController"}],"url":"\/documentation\/yababa\/mapsviewcontroller"},"doc://com.yababaGmbH.yababa/documentation/Yababa/MapsViewController/didRequestAutocompletePredictions(_:)":{"role":"symbol","title":"didRequestAutocompletePredictions(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"didRequestAutocompletePredictions"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"GMSAutocompleteViewController","preciseIdentifier":"c:objc(cs)GMSAutocompleteViewController"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/MapsViewController\/didRequestAutocompletePredictions(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"didRequestAutocompletePredictions:"}],"url":"\/documentation\/yababa\/mapsviewcontroller\/didrequestautocompletepredictions(_:)"},"doc://com.yababaGmbH.yababa/documentation/Yababa":{"role":"collection","title":"Yababa","abstract":[{"type":"text","text":"Getting Started"}],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa","kind":"symbol","type":"topic","url":"\/documentation\/yababa"},"doc://com.yababaGmbH.yababa/documentation/Yababa/MapsViewController/GMSAutocompleteViewControllerDelegate-Implementations":{"role":"collectionGroup","title":"GMSAutocompleteViewControllerDelegate Implementations","abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/MapsViewController\/GMSAutocompleteViewControllerDelegate-Implementations","kind":"article","type":"topic","url":"\/documentation\/yababa\/mapsviewcontroller\/gmsautocompleteviewcontrollerdelegate-implementations"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"didRequestAutocompletePredictions:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"didRequestAutocompletePredictions:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"didRequestAutocompletePredictions:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"GMSAutocompleteViewController","preciseIdentifier":"c:objc(cs)GMSAutocompleteViewController"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"viewController"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1MapsViewController\/title","value":"MapsViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1MapsViewController\/fragments","value":[{"kind":"identifier","text":"MapsViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1MapsViewController~1didRequestAutocompletePredictions(_:)\/title","value":"didRequestAutocompletePredictions:"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1MapsViewController~1didRequestAutocompletePredictions(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"didRequestAutocompletePredictions:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}