{"variants":[{"paths":["\/documentation\/yababa\/mapsviewcontroller\/gmsautocompleteviewcontrollerdelegate-implementations"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/yababa\/mapsviewcontroller\/gmsautocompleteviewcontrollerdelegate-implementations"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"identifier":{"url":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/MapsViewController\/GMSAutocompleteViewControllerDelegate-Implementations","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/MapsViewController\/didRequestAutocompletePredictions(_:)","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/MapsViewController\/didUpdateAutocompletePredictions(_:)","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/MapsViewController\/viewController(_:didAutocompleteWith:)","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/MapsViewController\/viewController(_:didFailAutocompleteWithError:)","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/MapsViewController\/wasCancelled(_:)"],"generated":true}],"kind":"article","metadata":{"modules":[{"name":"Yababa"}],"role":"collectionGroup","title":"GMSAutocompleteViewControllerDelegate Implementations"},"hierarchy":{"paths":[["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/MapsViewController"]]},"references":{"doc://com.yababaGmbH.yababa/documentation/Yababa/MapsViewController/wasCancelled(_:)":{"role":"symbol","title":"wasCancelled(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"wasCancelled"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"GMSAutocompleteViewController","preciseIdentifier":"c:objc(cs)GMSAutocompleteViewController"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/MapsViewController\/wasCancelled(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"wasCancelled:"}],"url":"\/documentation\/yababa\/mapsviewcontroller\/wascancelled(_:)"},"doc://com.yababaGmbH.yababa/documentation/Yababa/MapsViewController/viewController(_:didFailAutocompleteWithError:)":{"role":"symbol","title":"viewController(_:didFailAutocompleteWithError:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"viewController"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"GMSAutocompleteViewController","preciseIdentifier":"c:objc(cs)GMSAutocompleteViewController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didFailAutocompleteWithError"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/MapsViewController\/viewController(_:didFailAutocompleteWithError:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"viewController:didFailAutocompleteWithError:"}],"url":"\/documentation\/yababa\/mapsviewcontroller\/viewcontroller(_:didfailautocompletewitherror:)"},"doc://com.yababaGmbH.yababa/documentation/Yababa/MapsViewController/didUpdateAutocompletePredictions(_:)":{"role":"symbol","title":"didUpdateAutocompletePredictions(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"didUpdateAutocompletePredictions"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"GMSAutocompleteViewController","preciseIdentifier":"c:objc(cs)GMSAutocompleteViewController"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/MapsViewController\/didUpdateAutocompletePredictions(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"didUpdateAutocompletePredictions:"}],"url":"\/documentation\/yababa\/mapsviewcontroller\/didupdateautocompletepredictions(_:)"},"doc://com.yababaGmbH.yababa/documentation/Yababa/MapsViewController":{"role":"symbol","title":"MapsViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MapsViewController"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/MapsViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MapsViewController"}],"url":"\/documentation\/yababa\/mapsviewcontroller"},"doc://com.yababaGmbH.yababa/documentation/Yababa":{"role":"collection","title":"Yababa","abstract":[{"type":"text","text":"Getting Started"}],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa","kind":"symbol","type":"topic","url":"\/documentation\/yababa"},"doc://com.yababaGmbH.yababa/documentation/Yababa/MapsViewController/didRequestAutocompletePredictions(_:)":{"role":"symbol","title":"didRequestAutocompletePredictions(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"didRequestAutocompletePredictions"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"GMSAutocompleteViewController","preciseIdentifier":"c:objc(cs)GMSAutocompleteViewController"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/MapsViewController\/didRequestAutocompletePredictions(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"didRequestAutocompletePredictions:"}],"url":"\/documentation\/yababa\/mapsviewcontroller\/didrequestautocompletepredictions(_:)"},"doc://com.yababaGmbH.yababa/documentation/Yababa/MapsViewController/viewController(_:didAutocompleteWith:)":{"role":"symbol","title":"viewController(_:didAutocompleteWith:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"viewController"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"GMSAutocompleteViewController","preciseIdentifier":"c:objc(cs)GMSAutocompleteViewController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didAutocompleteWith"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GMSPlace","preciseIdentifier":"c:objc(cs)GMSPlace"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/MapsViewController\/viewController(_:didAutocompleteWith:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"viewController:didAutocompleteWithPlace:"}],"url":"\/documentation\/yababa\/mapsviewcontroller\/viewcontroller(_:didautocompletewith:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/MapsViewController\/didRequestAutocompletePredictions(_:)","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/MapsViewController\/didUpdateAutocompletePredictions(_:)","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/MapsViewController\/viewController(_:didAutocompleteWith:)","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/MapsViewController\/viewController(_:didFailAutocompleteWithError:)","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/MapsViewController\/wasCancelled(_:)"],"generated":true}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1MapsViewController~1wasCancelled(_:)\/title","value":"wasCancelled:"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1MapsViewController~1wasCancelled(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"wasCancelled:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1MapsViewController~1viewController(_:didFailAutocompleteWithError:)\/title","value":"viewController:didFailAutocompleteWithError:"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1MapsViewController~1viewController(_:didFailAutocompleteWithError:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"viewController:didFailAutocompleteWithError:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1MapsViewController~1didUpdateAutocompletePredictions(_:)\/title","value":"didUpdateAutocompletePredictions:"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1MapsViewController~1didUpdateAutocompletePredictions(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"didUpdateAutocompletePredictions:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1MapsViewController\/title","value":"MapsViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1MapsViewController\/fragments","value":[{"kind":"identifier","text":"MapsViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1MapsViewController~1didRequestAutocompletePredictions(_:)\/title","value":"didRequestAutocompletePredictions:"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1MapsViewController~1didRequestAutocompletePredictions(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"didRequestAutocompletePredictions:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1MapsViewController~1viewController(_:didAutocompleteWith:)\/title","value":"viewController:didAutocompleteWithPlace:"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1MapsViewController~1viewController(_:didAutocompleteWith:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"viewController:didAutocompleteWithPlace:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}