{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@IBOutlet"},{"kind":"text","text":" "},{"kind":"keyword","text":"weak"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"searchLabel"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UILabel","preciseIdentifier":"c:objc(cs)UILabel"},{"kind":"text","text":"!"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/yababa\/mapsviewcontroller\/searchlabel"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/yababa\/mapsviewcontroller\/searchlabel"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/MapsViewController\/searchLabel","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"searchLabel"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UILabel","preciseIdentifier":"c:objc(cs)UILabel"},{"kind":"text","text":"!"}],"title":"searchLabel","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:@M@Yababa@objc(cs)MapsViewController(py)searchLabel","modules":[{"name":"Yababa"}],"navigatorTitle":[{"kind":"identifier","text":"searchLabel"}]},"hierarchy":{"paths":[["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/MapsViewController"]]},"references":{"doc://com.yababaGmbH.yababa/documentation/Yababa/MapsViewController":{"role":"symbol","title":"MapsViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MapsViewController"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/MapsViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MapsViewController"}],"url":"\/documentation\/yababa\/mapsviewcontroller"},"doc://com.yababaGmbH.yababa/documentation/Yababa/MapsViewController/searchLabel":{"role":"symbol","title":"searchLabel","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"searchLabel"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UILabel","preciseIdentifier":"c:objc(cs)UILabel"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/MapsViewController\/searchLabel","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"searchLabel"}],"url":"\/documentation\/yababa\/mapsviewcontroller\/searchlabel"},"doc://com.yababaGmbH.yababa/documentation/Yababa":{"role":"collection","title":"Yababa","abstract":[{"type":"text","text":"Getting Started"}],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa","kind":"symbol","type":"topic","url":"\/documentation\/yababa"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"searchLabel"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"searchLabel"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"weak"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"UILabel","preciseIdentifier":"c:objc(cs)UILabel"},{"kind":"text","text":" * "},{"kind":"identifier","text":"searchLabel"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1MapsViewController\/title","value":"MapsViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1MapsViewController\/fragments","value":[{"kind":"identifier","text":"MapsViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1MapsViewController~1searchLabel\/title","value":"searchLabel"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1MapsViewController~1searchLabel\/fragments","value":[{"kind":"identifier","text":"searchLabel"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}