{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@IBOutlet"},{"kind":"text","text":" "},{"kind":"keyword","text":"weak"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"cancelBtn"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIButton","preciseIdentifier":"c:objc(cs)UIButton"},{"kind":"text","text":"!"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/yababa\/addaddressdetailsviewcontroller\/cancelbtn"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/yababa\/addaddressdetailsviewcontroller\/cancelbtn"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AddAddressDetailsViewController\/cancelBtn","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"cancelBtn"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIButton","preciseIdentifier":"c:objc(cs)UIButton"},{"kind":"text","text":"!"}],"title":"cancelBtn","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:@M@Yababa@objc(cs)AddAddressDetailsViewController(py)cancelBtn","modules":[{"name":"Yababa"}],"navigatorTitle":[{"kind":"identifier","text":"cancelBtn"}]},"hierarchy":{"paths":[["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AddAddressDetailsViewController"]]},"references":{"doc://com.yababaGmbH.yababa/documentation/Yababa/AddAddressDetailsViewController":{"role":"symbol","title":"AddAddressDetailsViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AddAddressDetailsViewController"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AddAddressDetailsViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AddAddressDetailsViewController"}],"url":"\/documentation\/yababa\/addaddressdetailsviewcontroller"},"doc://com.yababaGmbH.yababa/documentation/Yababa":{"role":"collection","title":"Yababa","abstract":[{"type":"text","text":"Getting Started"}],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa","kind":"symbol","type":"topic","url":"\/documentation\/yababa"},"doc://com.yababaGmbH.yababa/documentation/Yababa/AddAddressDetailsViewController/cancelBtn":{"role":"symbol","title":"cancelBtn","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"cancelBtn"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIButton","preciseIdentifier":"c:objc(cs)UIButton"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AddAddressDetailsViewController\/cancelBtn","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"cancelBtn"}],"url":"\/documentation\/yababa\/addaddressdetailsviewcontroller\/cancelbtn"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"cancelBtn"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"cancelBtn"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"weak"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"UIButton","preciseIdentifier":"c:objc(cs)UIButton"},{"kind":"text","text":" * "},{"kind":"identifier","text":"cancelBtn"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1AddAddressDetailsViewController\/title","value":"AddAddressDetailsViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1AddAddressDetailsViewController\/fragments","value":[{"kind":"identifier","text":"AddAddressDetailsViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1AddAddressDetailsViewController~1cancelBtn\/title","value":"cancelBtn"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1AddAddressDetailsViewController~1cancelBtn\/fragments","value":[{"kind":"identifier","text":"cancelBtn"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}