{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"viewController"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"viewController"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GMSAutocompleteViewController","preciseIdentifier":"c:objc(cs)GMSAutocompleteViewController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didFailAutocompleteWithError"},{"kind":"text","text":" "},{"kind":"internalParam","text":"error"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/yababa\/mapsviewcontroller\/viewcontroller(_:didfailautocompletewitherror:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/yababa\/mapsviewcontroller\/viewcontroller(_:didfailautocompletewitherror:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/MapsViewController\/viewController(_:didFailAutocompleteWithError:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"GMSAutocompleteViewControllerDelegate.viewController(_:didFailAutocompleteWithError:)"},{"type":"text","text":"."}],"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"viewController:didFailAutocompleteWithError:"}],"role":"symbol","title":"viewController(_:didFailAutocompleteWithError:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"viewController"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"GMSAutocompleteViewController","preciseIdentifier":"c:objc(cs)GMSAutocompleteViewController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didFailAutocompleteWithError"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":")"}],"symbolKind":"method","externalID":"c:@CM@Yababa@objc(cs)MapsViewController(im)viewController:didFailAutocompleteWithError:","extendedModule":"Yababa","modules":[{"name":"Yababa"}]},"hierarchy":{"paths":[["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/MapsViewController","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/MapsViewController\/GMSAutocompleteViewControllerDelegate-Implementations"]]},"references":{"doc://com.yababaGmbH.yababa/documentation/Yababa/MapsViewController/GMSAutocompleteViewControllerDelegate-Implementations":{"role":"collectionGroup","title":"GMSAutocompleteViewControllerDelegate Implementations","abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/MapsViewController\/GMSAutocompleteViewControllerDelegate-Implementations","kind":"article","type":"topic","url":"\/documentation\/yababa\/mapsviewcontroller\/gmsautocompleteviewcontrollerdelegate-implementations"},"doc://com.yababaGmbH.yababa/documentation/Yababa/MapsViewController/viewController(_:didFailAutocompleteWithError:)":{"role":"symbol","title":"viewController(_:didFailAutocompleteWithError:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"viewController"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"GMSAutocompleteViewController","preciseIdentifier":"c:objc(cs)GMSAutocompleteViewController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didFailAutocompleteWithError"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/MapsViewController\/viewController(_:didFailAutocompleteWithError:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"viewController:didFailAutocompleteWithError:"}],"url":"\/documentation\/yababa\/mapsviewcontroller\/viewcontroller(_:didfailautocompletewitherror:)"},"doc://com.yababaGmbH.yababa/documentation/Yababa/MapsViewController":{"role":"symbol","title":"MapsViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MapsViewController"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/MapsViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MapsViewController"}],"url":"\/documentation\/yababa\/mapsviewcontroller"},"doc://com.yababaGmbH.yababa/documentation/Yababa":{"role":"collection","title":"Yababa","abstract":[{"type":"text","text":"Getting Started"}],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa","kind":"symbol","type":"topic","url":"\/documentation\/yababa"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"viewController:didFailAutocompleteWithError:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"viewController:didFailAutocompleteWithError:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"viewController:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"GMSAutocompleteViewController","preciseIdentifier":"c:objc(cs)GMSAutocompleteViewController"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"viewController"},{"kind":"text","text":" "},{"kind":"identifier","text":"didFailAutocompleteWithError:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSError","preciseIdentifier":"c:objc(cs)NSError"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"error"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1MapsViewController~1viewController(_:didFailAutocompleteWithError:)\/title","value":"viewController:didFailAutocompleteWithError:"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1MapsViewController~1viewController(_:didFailAutocompleteWithError:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"viewController:didFailAutocompleteWithError:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1MapsViewController\/title","value":"MapsViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1MapsViewController\/fragments","value":[{"kind":"identifier","text":"MapsViewController"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}