{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"authenticationPresentingViewController"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/yababa\/checkoutsceneinteractor\/authenticationpresentingviewcontroller()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/yababa\/checkoutsceneinteractor\/authenticationpresentingviewcontroller()"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CheckoutSceneInteractor\/authenticationPresentingViewController()","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"STPAuthenticationContext.authenticationPresentingViewController()"},{"type":"text","text":"."}],"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"authenticationPresentingViewController"}],"role":"symbol","title":"authenticationPresentingViewController()","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"authenticationPresentingViewController"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"}],"symbolKind":"method","externalID":"c:@CM@Yababa@objc(cs)CheckoutSceneInteractor(im)authenticationPresentingViewController","extendedModule":"Yababa","modules":[{"name":"Yababa"}]},"hierarchy":{"paths":[["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CheckoutSceneInteractor","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CheckoutSceneInteractor\/STPAuthenticationContext-Implementations"]]},"references":{"doc://com.yababaGmbH.yababa/documentation/Yababa":{"role":"collection","title":"Yababa","abstract":[{"type":"text","text":"Getting Started"}],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa","kind":"symbol","type":"topic","url":"\/documentation\/yababa"},"doc://com.yababaGmbH.yababa/documentation/Yababa/CheckoutSceneInteractor/STPAuthenticationContext-Implementations":{"role":"collectionGroup","title":"STPAuthenticationContext Implementations","abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CheckoutSceneInteractor\/STPAuthenticationContext-Implementations","kind":"article","type":"topic","url":"\/documentation\/yababa\/checkoutsceneinteractor\/stpauthenticationcontext-implementations"},"doc://com.yababaGmbH.yababa/documentation/Yababa/CheckoutSceneInteractor":{"role":"symbol","title":"CheckoutSceneInteractor","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CheckoutSceneInteractor"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CheckoutSceneInteractor","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CheckoutSceneInteractor"}],"url":"\/documentation\/yababa\/checkoutsceneinteractor"},"doc://com.yababaGmbH.yababa/documentation/Yababa/CheckoutSceneInteractor/authenticationPresentingViewController()":{"role":"symbol","title":"authenticationPresentingViewController()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"authenticationPresentingViewController"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CheckoutSceneInteractor\/authenticationPresentingViewController()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"authenticationPresentingViewController"}],"url":"\/documentation\/yababa\/checkoutsceneinteractor\/authenticationpresentingviewcontroller()"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"authenticationPresentingViewController"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"authenticationPresentingViewController"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"authenticationPresentingViewController"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1CheckoutSceneInteractor\/title","value":"CheckoutSceneInteractor"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1CheckoutSceneInteractor\/fragments","value":[{"kind":"identifier","text":"CheckoutSceneInteractor"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1CheckoutSceneInteractor~1authenticationPresentingViewController()\/title","value":"authenticationPresentingViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1CheckoutSceneInteractor~1authenticationPresentingViewController()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"authenticationPresentingViewController"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}