{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"unsubscribed"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/yababa\/subscriptionstatus\/unsubscribed"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/yababa\/subscriptionstatus\/unsubscribed"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/SubscriptionStatus\/unsubscribed","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"unsubscribed"}],"title":"SubscriptionStatus.unsubscribed","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@M@Yababa@E@SubscriptionStatus@SubscriptionStatusUnsubscribed","modules":[{"name":"Yababa"}],"navigatorTitle":[{"kind":"identifier","text":"SubscriptionStatusUnsubscribed"}]},"hierarchy":{"paths":[["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/SubscriptionStatus"]]},"references":{"doc://com.yababaGmbH.yababa/documentation/Yababa":{"role":"collection","title":"Yababa","abstract":[{"type":"text","text":"Getting Started"}],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa","kind":"symbol","type":"topic","url":"\/documentation\/yababa"},"doc://com.yababaGmbH.yababa/documentation/Yababa/SubscriptionStatus/unsubscribed":{"role":"symbol","title":"SubscriptionStatus.unsubscribed","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"unsubscribed"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/SubscriptionStatus\/unsubscribed","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SubscriptionStatusUnsubscribed"}],"url":"\/documentation\/yababa\/subscriptionstatus\/unsubscribed"},"doc://com.yababaGmbH.yababa/documentation/Yababa/SubscriptionStatus":{"role":"symbol","title":"SubscriptionStatus","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SubscriptionStatus"}],"abstract":[{"type":"text","text":"OPTED_IN: subscribed, and explicitly opted in."},{"type":"text","text":" "},{"type":"text","text":"SUBSCRIBED: subscribed, but not explicitly opted in."},{"type":"text","text":" "},{"type":"text","text":"UNSUBSCRIBED: unsubscribed and\/or explicitly opted out."}],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/SubscriptionStatus","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SubscriptionStatus"}],"url":"\/documentation\/yababa\/subscriptionstatus"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"SubscriptionStatusUnsubscribed"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SubscriptionStatusUnsubscribed"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"SubscriptionStatusUnsubscribed"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1SubscriptionStatus~1unsubscribed\/title","value":"SubscriptionStatusUnsubscribed"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1SubscriptionStatus~1unsubscribed\/fragments","value":[{"kind":"identifier","text":"SubscriptionStatusUnsubscribed"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1SubscriptionStatus\/title","value":"SubscriptionStatus"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1SubscriptionStatus\/fragments","value":[{"kind":"identifier","text":"SubscriptionStatus"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}