{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"customFlowLayout"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/DiscountsCollectionFlowLayout","preciseIdentifier":"c:@M@Yababa@objc(cs)DiscountsCollectionFlowLayout","text":"DiscountsCollectionFlowLayout"},{"kind":"text","text":"!"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/yababa\/discountscollectionview\/customflowlayout"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/DiscountsCollectionView\/customFlowLayout","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"customFlowLayout"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DiscountsCollectionFlowLayout","preciseIdentifier":"c:@M@Yababa@objc(cs)DiscountsCollectionFlowLayout"},{"kind":"text","text":"!"}],"title":"customFlowLayout","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"s:6Yababa23DiscountsCollectionViewC16customFlowLayoutAA0bcfG0CSgvp","modules":[{"name":"Yababa"}]},"hierarchy":{"paths":[["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/DiscountsCollectionView"]]},"references":{"doc://com.yababaGmbH.yababa/documentation/Yababa/DiscountsCollectionFlowLayout":{"role":"symbol","title":"DiscountsCollectionFlowLayout","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DiscountsCollectionFlowLayout"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/DiscountsCollectionFlowLayout","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DiscountsCollectionFlowLayout"}],"url":"\/documentation\/yababa\/discountscollectionflowlayout"},"doc://com.yababaGmbH.yababa/documentation/Yababa/DiscountsCollectionView/customFlowLayout":{"role":"symbol","title":"customFlowLayout","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"customFlowLayout"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DiscountsCollectionFlowLayout","preciseIdentifier":"c:@M@Yababa@objc(cs)DiscountsCollectionFlowLayout"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/DiscountsCollectionView\/customFlowLayout","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/discountscollectionview\/customflowlayout"},"doc://com.yababaGmbH.yababa/documentation/Yababa/DiscountsCollectionView":{"role":"symbol","title":"DiscountsCollectionView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DiscountsCollectionView"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/DiscountsCollectionView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DiscountsCollectionView"}],"url":"\/documentation\/yababa\/discountscollectionview"},"doc://com.yababaGmbH.yababa/documentation/Yababa":{"role":"collection","title":"Yababa","abstract":[{"type":"text","text":"Getting Started"}],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa","kind":"symbol","type":"topic","url":"\/documentation\/yababa"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1DiscountsCollectionFlowLayout\/title","value":"DiscountsCollectionFlowLayout"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1DiscountsCollectionFlowLayout\/fragments","value":[{"kind":"identifier","text":"DiscountsCollectionFlowLayout"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1DiscountsCollectionView\/title","value":"DiscountsCollectionView"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1DiscountsCollectionView\/fragments","value":[{"kind":"identifier","text":"DiscountsCollectionView"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}