{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"messaging"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"messaging"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Messaging","preciseIdentifier":"c:objc(cs)FIRMessaging"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didReceiveRegistrationToken"},{"kind":"text","text":" "},{"kind":"internalParam","text":"fcmToken"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?)"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/yababa\/firebasemanager\/messaging(_:didreceiveregistrationtoken:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/yababa\/firebasemanager\/messaging(_:didreceiveregistrationtoken:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/FirebaseManager\/messaging(_:didReceiveRegistrationToken:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Monitor Token refresh"},{"type":"text","text":" "},{"type":"text","text":"This callback is fired at each app startup and whenever a new token is generated."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"messaging"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Messaging","preciseIdentifier":"c:objc(cs)FIRMessaging"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didReceiveRegistrationToken"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?)"}],"title":"messaging(_:didReceiveRegistrationToken:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@M@Yababa@objc(cs)FirebaseManager(im)messaging:didReceiveRegistrationToken:","modules":[{"name":"Yababa"}],"navigatorTitle":[{"kind":"identifier","text":"messaging:didReceiveRegistrationToken:"}]},"hierarchy":{"paths":[["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/FirebaseManager"]]},"references":{"doc://com.yababaGmbH.yababa/documentation/Yababa":{"role":"collection","title":"Yababa","abstract":[{"type":"text","text":"Getting Started"}],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa","kind":"symbol","type":"topic","url":"\/documentation\/yababa"},"doc://com.yababaGmbH.yababa/documentation/Yababa/FirebaseManager/messaging(_:didReceiveRegistrationToken:)":{"role":"symbol","title":"messaging(_:didReceiveRegistrationToken:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"messaging"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Messaging","preciseIdentifier":"c:objc(cs)FIRMessaging"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didReceiveRegistrationToken"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?)"}],"abstract":[{"type":"text","text":"Monitor Token refresh"},{"type":"text","text":" "},{"type":"text","text":"This callback is fired at each app startup and whenever a new token is generated."}],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/FirebaseManager\/messaging(_:didReceiveRegistrationToken:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"messaging:didReceiveRegistrationToken:"}],"url":"\/documentation\/yababa\/firebasemanager\/messaging(_:didreceiveregistrationtoken:)"},"doc://com.yababaGmbH.yababa/documentation/Yababa/FirebaseManager":{"role":"symbol","title":"FirebaseManager","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FirebaseManager"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/FirebaseManager","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FirebaseManager"}],"url":"\/documentation\/yababa\/firebasemanager"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"messaging:didReceiveRegistrationToken:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"messaging:didReceiveRegistrationToken:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"messaging:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"FIRMessaging","preciseIdentifier":"c:objc(cs)FIRMessaging"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"messaging"},{"kind":"text","text":" "},{"kind":"identifier","text":"didReceiveRegistrationToken:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"fcmToken"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1FirebaseManager~1messaging(_:didReceiveRegistrationToken:)\/title","value":"messaging:didReceiveRegistrationToken:"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1FirebaseManager~1messaging(_:didReceiveRegistrationToken:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"messaging:didReceiveRegistrationToken:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1FirebaseManager\/title","value":"FirebaseManager"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1FirebaseManager\/fragments","value":[{"kind":"identifier","text":"FirebaseManager"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}