{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"collectionView"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"collectionView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UICollectionView","preciseIdentifier":"c:objc(cs)UICollectionView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didEndDisplaying"},{"kind":"text","text":" "},{"kind":"internalParam","text":"cell"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UICollectionViewCell","preciseIdentifier":"c:objc(cs)UICollectionViewCell"},{"kind":"text","text":", "},{"kind":"externalParam","text":"forItemAt"},{"kind":"text","text":" "},{"kind":"internalParam","text":"indexPath"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"IndexPath","preciseIdentifier":"s:10Foundation9IndexPathV"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/yababa\/deliveryareasviewcontroller\/collectionview(_:didenddisplaying:foritemat:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/yababa\/deliveryareasviewcontroller\/collectionview(_:didenddisplaying:foritemat:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/DeliveryAreasViewController\/collectionView(_:didEndDisplaying:forItemAt:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"UICollectionViewDelegate.collectionView(_:didEndDisplaying:forItemAt:)"},{"type":"text","text":"."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"collectionView"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UICollectionView","preciseIdentifier":"c:objc(cs)UICollectionView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didEndDisplaying"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UICollectionViewCell","preciseIdentifier":"c:objc(cs)UICollectionViewCell"},{"kind":"text","text":", "},{"kind":"externalParam","text":"forItemAt"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"IndexPath","preciseIdentifier":"s:10Foundation9IndexPathV"},{"kind":"text","text":")"}],"title":"collectionView(_:didEndDisplaying:forItemAt:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@CM@Yababa@objc(cs)DeliveryAreasViewController(im)collectionView:didEndDisplayingCell:forItemAtIndexPath:","modules":[{"name":"Yababa"}],"navigatorTitle":[{"kind":"identifier","text":"collectionView:didEndDisplayingCell:forItemAtIndexPath:"}]},"hierarchy":{"paths":[["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/DeliveryAreasViewController","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/DeliveryAreasViewController\/UICollectionViewDelegate-Implementations"]]},"references":{"doc://com.yababaGmbH.yababa/documentation/Yababa/DeliveryAreasViewController/collectionView(_:didEndDisplaying:forItemAt:)":{"role":"symbol","title":"collectionView(_:didEndDisplaying:forItemAt:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"collectionView"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UICollectionView","preciseIdentifier":"c:objc(cs)UICollectionView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didEndDisplaying"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UICollectionViewCell","preciseIdentifier":"c:objc(cs)UICollectionViewCell"},{"kind":"text","text":", "},{"kind":"externalParam","text":"forItemAt"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"IndexPath","preciseIdentifier":"s:10Foundation9IndexPathV"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/DeliveryAreasViewController\/collectionView(_:didEndDisplaying:forItemAt:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"collectionView:didEndDisplayingCell:forItemAtIndexPath:"}],"url":"\/documentation\/yababa\/deliveryareasviewcontroller\/collectionview(_:didenddisplaying:foritemat:)"},"doc://com.yababaGmbH.yababa/documentation/Yababa/DeliveryAreasViewController":{"role":"symbol","title":"DeliveryAreasViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DeliveryAreasViewController"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/DeliveryAreasViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DeliveryAreasViewController"}],"url":"\/documentation\/yababa\/deliveryareasviewcontroller"},"doc://com.yababaGmbH.yababa/documentation/Yababa":{"role":"collection","title":"Yababa","abstract":[{"type":"text","text":"Getting Started"}],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa","kind":"symbol","type":"topic","url":"\/documentation\/yababa"},"doc://com.yababaGmbH.yababa/documentation/Yababa/DeliveryAreasViewController/UICollectionViewDelegate-Implementations":{"role":"collectionGroup","title":"UICollectionViewDelegate Implementations","abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/DeliveryAreasViewController\/UICollectionViewDelegate-Implementations","kind":"article","type":"topic","url":"\/documentation\/yababa\/deliveryareasviewcontroller\/uicollectionviewdelegate-implementations"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"collectionView:didEndDisplayingCell:forItemAtIndexPath:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"collectionView:didEndDisplayingCell:forItemAtIndexPath:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"collectionView:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UICollectionView","preciseIdentifier":"c:objc(cs)UICollectionView"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"collectionView"},{"kind":"text","text":" "},{"kind":"identifier","text":"didEndDisplayingCell:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UICollectionViewCell","preciseIdentifier":"c:objc(cs)UICollectionViewCell"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"cell"},{"kind":"text","text":" "},{"kind":"identifier","text":"forItemAtIndexPath:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSIndexPath","preciseIdentifier":"c:objc(cs)NSIndexPath"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"indexPath"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1DeliveryAreasViewController~1collectionView(_:didEndDisplaying:forItemAt:)\/title","value":"collectionView:didEndDisplayingCell:forItemAtIndexPath:"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1DeliveryAreasViewController~1collectionView(_:didEndDisplaying:forItemAt:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"collectionView:didEndDisplayingCell:forItemAtIndexPath:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1DeliveryAreasViewController\/title","value":"DeliveryAreasViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1DeliveryAreasViewController\/fragments","value":[{"kind":"identifier","text":"DeliveryAreasViewController"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}