{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"applePayContext"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"context"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"STPApplePayContext","preciseIdentifier":"c:@M@StripeApplePay@objc(cs)_stpinternal_APContextSwift"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didCreatePaymentMethod"},{"kind":"text","text":" "},{"kind":"internalParam","text":"paymentMethod"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"STPPaymentMethod","preciseIdentifier":"c:@M@Stripe@objc(cs)STPPaymentMethod"},{"kind":"text","text":", "},{"kind":"externalParam","text":"paymentInformation"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"PKPayment","preciseIdentifier":"c:objc(cs)PKPayment"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": "},{"kind":"attribute","text":"@escaping"},{"kind":"text","text":" "},{"kind":"typeIdentifier","text":"STPIntentClientSecretCompletionBlock","preciseIdentifier":"s:14StripeApplePay36STPIntentClientSecretCompletionBlocka"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/yababa\/stripeapplepay\/applepaycontext(_:didcreatepaymentmethod:paymentinformation:completion:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/yababa\/stripeapplepay\/applepaycontext(_:didcreatepaymentmethod:paymentinformation:completion:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/StripeApplePay\/applePayContext(_:didCreatePaymentMethod:paymentInformation:completion:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"STPApplePayContextDelegate.applePayContext(_:didCreatePaymentMethod:paymentInformation:completion:)"},{"type":"text","text":"."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"applePayContext"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"STPApplePayContext","preciseIdentifier":"c:@M@StripeApplePay@objc(cs)_stpinternal_APContextSwift"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didCreatePaymentMethod"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"STPPaymentMethod","preciseIdentifier":"c:@M@Stripe@objc(cs)STPPaymentMethod"},{"kind":"text","text":", "},{"kind":"externalParam","text":"paymentInformation"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"PKPayment","preciseIdentifier":"c:objc(cs)PKPayment"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"STPIntentClientSecretCompletionBlock","preciseIdentifier":"s:14StripeApplePay36STPIntentClientSecretCompletionBlocka"},{"kind":"text","text":")"}],"title":"applePayContext(_:didCreatePaymentMethod:paymentInformation:completion:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@CM@Yababa@objc(cs)StripeApplePay(im)applePayContext:didCreatePaymentMethod:paymentInformation:completion:","modules":[{"name":"Yababa"}],"navigatorTitle":[{"kind":"identifier","text":"applePayContext:didCreatePaymentMethod:paymentInformation:completion:"}]},"hierarchy":{"paths":[["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/StripeApplePay","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/StripeApplePay\/STPApplePayContextDelegate-Implementations"]]},"references":{"doc://com.yababaGmbH.yababa/documentation/Yababa/StripeApplePay/applePayContext(_:didCreatePaymentMethod:paymentInformation:completion:)":{"role":"symbol","title":"applePayContext(_:didCreatePaymentMethod:paymentInformation:completion:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"applePayContext"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"STPApplePayContext","preciseIdentifier":"c:@M@StripeApplePay@objc(cs)_stpinternal_APContextSwift"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didCreatePaymentMethod"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"STPPaymentMethod","preciseIdentifier":"c:@M@Stripe@objc(cs)STPPaymentMethod"},{"kind":"text","text":", "},{"kind":"externalParam","text":"paymentInformation"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"PKPayment","preciseIdentifier":"c:objc(cs)PKPayment"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"STPIntentClientSecretCompletionBlock","preciseIdentifier":"s:14StripeApplePay36STPIntentClientSecretCompletionBlocka"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/StripeApplePay\/applePayContext(_:didCreatePaymentMethod:paymentInformation:completion:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"applePayContext:didCreatePaymentMethod:paymentInformation:completion:"}],"url":"\/documentation\/yababa\/stripeapplepay\/applepaycontext(_:didcreatepaymentmethod:paymentinformation:completion:)"},"doc://com.yababaGmbH.yababa/documentation/Yababa/StripeApplePay":{"role":"symbol","title":"StripeApplePay","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"StripeApplePay"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/StripeApplePay","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"StripeApplePay"}],"url":"\/documentation\/yababa\/stripeapplepay"},"doc://com.yababaGmbH.yababa/documentation/Yababa/StripeApplePay/STPApplePayContextDelegate-Implementations":{"role":"collectionGroup","title":"STPApplePayContextDelegate Implementations","abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/StripeApplePay\/STPApplePayContextDelegate-Implementations","kind":"article","type":"topic","url":"\/documentation\/yababa\/stripeapplepay\/stpapplepaycontextdelegate-implementations"},"doc://com.yababaGmbH.yababa/documentation/Yababa":{"role":"collection","title":"Yababa","abstract":[{"type":"text","text":"Getting Started"}],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa","kind":"symbol","type":"topic","url":"\/documentation\/yababa"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"applePayContext:didCreatePaymentMethod:paymentInformation:completion:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"applePayContext:didCreatePaymentMethod:paymentInformation:completion:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"applePayContext:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"_stpinternal_APContextSwift","preciseIdentifier":"c:@M@StripeApplePay@objc(cs)_stpinternal_APContextSwift"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"context"},{"kind":"text","text":" "},{"kind":"identifier","text":"didCreatePaymentMethod:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"STPPaymentMethod","preciseIdentifier":"c:@M@Stripe@objc(cs)STPPaymentMethod"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"paymentMethod"},{"kind":"text","text":" "},{"kind":"identifier","text":"paymentInformation:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"PKPayment","preciseIdentifier":"c:objc(cs)PKPayment"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"paymentInformation"},{"kind":"text","text":" "},{"kind":"identifier","text":"completion:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"void (^)(NSString *, NSError *)","preciseIdentifier":"c:BFv(#*$objc(cs)NSString#*$objc(cs)NSError)"},{"kind":"text","text":")"},{"kind":"internalParam","text":"completion"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1StripeApplePay~1applePayContext(_:didCreatePaymentMethod:paymentInformation:completion:)\/title","value":"applePayContext:didCreatePaymentMethod:paymentInformation:completion:"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1StripeApplePay~1applePayContext(_:didCreatePaymentMethod:paymentInformation:completion:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"applePayContext:didCreatePaymentMethod:paymentInformation:completion:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1StripeApplePay\/title","value":"StripeApplePay"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1StripeApplePay\/fragments","value":[{"kind":"identifier","text":"StripeApplePay"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}