{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"application"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"application"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIApplication","preciseIdentifier":"c:objc(cs)UIApplication"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didReceiveRemoteNotification"},{"kind":"text","text":" "},{"kind":"internalParam","text":"userInfo"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"AnyHashable","preciseIdentifier":"s:s11AnyHashableV"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"fetchCompletionHandler"},{"kind":"text","text":" "},{"kind":"internalParam","text":"completionHandler"},{"kind":"text","text":": "},{"kind":"attribute","text":"@escaping"},{"kind":"text","text":" ("},{"kind":"typeIdentifier","text":"UIBackgroundFetchResult","preciseIdentifier":"c:@E@UIBackgroundFetchResult"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/yababa\/pushnotificationsmanager\/application(_:didreceiveremotenotification:fetchcompletionhandler:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/yababa\/pushnotificationsmanager\/application(_:didreceiveremotenotification:fetchcompletionhandler:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/PushNotificationsManager\/application(_:didReceiveRemoteNotification:fetchCompletionHandler:)","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"application:didReceiveRemoteNotification:fetchCompletionHandler:"}],"role":"symbol","title":"application(_:didReceiveRemoteNotification:fetchCompletionHandler:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"application"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UIApplication","preciseIdentifier":"c:objc(cs)UIApplication"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didReceiveRemoteNotification"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"AnyHashable","preciseIdentifier":"s:s11AnyHashableV"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"fetchCompletionHandler"},{"kind":"text","text":": ("},{"kind":"typeIdentifier","text":"UIBackgroundFetchResult","preciseIdentifier":"c:@E@UIBackgroundFetchResult"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"symbolKind":"method","externalID":"c:@CM@Yababa@objc(cs)PushNotificationsManager(im)application:didReceiveRemoteNotification:fetchCompletionHandler:","extendedModule":"Yababa","modules":[{"name":"Yababa"}]},"hierarchy":{"paths":[["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/PushNotificationsManager"]]},"references":{"doc://com.yababaGmbH.yababa/documentation/Yababa/PushNotificationsManager/application(_:didReceiveRemoteNotification:fetchCompletionHandler:)":{"role":"symbol","title":"application(_:didReceiveRemoteNotification:fetchCompletionHandler:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"application"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UIApplication","preciseIdentifier":"c:objc(cs)UIApplication"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didReceiveRemoteNotification"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"AnyHashable","preciseIdentifier":"s:s11AnyHashableV"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"fetchCompletionHandler"},{"kind":"text","text":": ("},{"kind":"typeIdentifier","text":"UIBackgroundFetchResult","preciseIdentifier":"c:@E@UIBackgroundFetchResult"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/PushNotificationsManager\/application(_:didReceiveRemoteNotification:fetchCompletionHandler:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"application:didReceiveRemoteNotification:fetchCompletionHandler:"}],"url":"\/documentation\/yababa\/pushnotificationsmanager\/application(_:didreceiveremotenotification:fetchcompletionhandler:)"},"doc://com.yababaGmbH.yababa/documentation/Yababa/PushNotificationsManager":{"role":"symbol","title":"PushNotificationsManager","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PushNotificationsManager"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/PushNotificationsManager","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PushNotificationsManager"}],"url":"\/documentation\/yababa\/pushnotificationsmanager"},"doc://com.yababaGmbH.yababa/documentation/Yababa":{"role":"collection","title":"Yababa","abstract":[{"type":"text","text":"Getting Started"}],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa","kind":"symbol","type":"topic","url":"\/documentation\/yababa"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"application:didReceiveRemoteNotification:fetchCompletionHandler:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"application:didReceiveRemoteNotification:fetchCompletionHandler:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"application:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UIApplication","preciseIdentifier":"c:objc(cs)UIApplication"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"application"},{"kind":"text","text":" "},{"kind":"identifier","text":"didReceiveRemoteNotification:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSDictionary","preciseIdentifier":"c:objc(cs)NSDictionary"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"userInfo"},{"kind":"text","text":" "},{"kind":"identifier","text":"fetchCompletionHandler:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"void (^)(enum UIBackgroundFetchResult)","preciseIdentifier":"c:BFv(#$@E@UIBackgroundFetchResult)"},{"kind":"text","text":")"},{"kind":"internalParam","text":"completionHandler"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1PushNotificationsManager~1application(_:didReceiveRemoteNotification:fetchCompletionHandler:)\/title","value":"application:didReceiveRemoteNotification:fetchCompletionHandler:"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1PushNotificationsManager~1application(_:didReceiveRemoteNotification:fetchCompletionHandler:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"application:didReceiveRemoteNotification:fetchCompletionHandler:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1PushNotificationsManager\/title","value":"PushNotificationsManager"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1PushNotificationsManager\/fragments","value":[{"kind":"identifier","text":"PushNotificationsManager"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}