{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"didRegisterForRemoteNotifications"},{"kind":"text","text":"("},{"kind":"externalParam","text":"deviceToken"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Data","preciseIdentifier":"s:10Foundation4DataV"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/yababa\/pushnotificationsmanager\/didregisterforremotenotifications(devicetoken:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/yababa\/pushnotificationsmanager\/didregisterforremotenotifications(devicetoken:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/PushNotificationsManager\/didRegisterForRemoteNotifications(deviceToken:)","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"didRegisterForRemoteNotificationsWithDeviceToken:"}],"role":"symbol","title":"didRegisterForRemoteNotifications(deviceToken:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"didRegisterForRemoteNotifications"},{"kind":"text","text":"("},{"kind":"externalParam","text":"deviceToken"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Data","preciseIdentifier":"s:10Foundation4DataV"},{"kind":"text","text":")"}],"symbolKind":"method","externalID":"c:@CM@Yababa@objc(cs)PushNotificationsManager(im)didRegisterForRemoteNotificationsWithDeviceToken:","extendedModule":"Yababa","modules":[{"name":"Yababa"}]},"hierarchy":{"paths":[["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/PushNotificationsManager"]]},"references":{"doc://com.yababaGmbH.yababa/documentation/Yababa/PushNotificationsManager/didRegisterForRemoteNotifications(deviceToken:)":{"role":"symbol","title":"didRegisterForRemoteNotifications(deviceToken:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"didRegisterForRemoteNotifications"},{"kind":"text","text":"("},{"kind":"externalParam","text":"deviceToken"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Data","preciseIdentifier":"s:10Foundation4DataV"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/PushNotificationsManager\/didRegisterForRemoteNotifications(deviceToken:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"didRegisterForRemoteNotificationsWithDeviceToken:"}],"url":"\/documentation\/yababa\/pushnotificationsmanager\/didregisterforremotenotifications(devicetoken:)"},"doc://com.yababaGmbH.yababa/documentation/Yababa/PushNotificationsManager":{"role":"symbol","title":"PushNotificationsManager","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PushNotificationsManager"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/PushNotificationsManager","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PushNotificationsManager"}],"url":"\/documentation\/yababa\/pushnotificationsmanager"},"doc://com.yababaGmbH.yababa/documentation/Yababa":{"role":"collection","title":"Yababa","abstract":[{"type":"text","text":"Getting Started"}],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa","kind":"symbol","type":"topic","url":"\/documentation\/yababa"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"didRegisterForRemoteNotificationsWithDeviceToken:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"didRegisterForRemoteNotificationsWithDeviceToken:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"didRegisterForRemoteNotificationsWithDeviceToken:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSData","preciseIdentifier":"c:objc(cs)NSData"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"deviceToken"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1PushNotificationsManager~1didRegisterForRemoteNotifications(deviceToken:)\/title","value":"didRegisterForRemoteNotificationsWithDeviceToken:"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1PushNotificationsManager~1didRegisterForRemoteNotifications(deviceToken:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"didRegisterForRemoteNotificationsWithDeviceToken:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1PushNotificationsManager\/title","value":"PushNotificationsManager"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1PushNotificationsManager\/fragments","value":[{"kind":"identifier","text":"PushNotificationsManager"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}