{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"typeIdentifier","identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/SharedData","preciseIdentifier":"c:objc(cs)SharedData","text":"SharedData"},{"kind":"text","text":" * "},{"kind":"identifier","text":"Manager"}],"languages":["occ"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/yababa\/internetalertview\/manager"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/InternetAlertView\/Manager","interfaceLanguage":"occ"},"kind":"symbol","metadata":{"fragments":[{"kind":"identifier","text":"Manager"}],"title":"Manager","roleHeading":"Instance Variable","role":"symbol","symbolKind":"ivar","externalID":"c:objc(cs)InternetAlertView@Manager","modules":[{"name":"Yababa"}],"navigatorTitle":[{"kind":"identifier","text":"Manager"}]},"hierarchy":{"paths":[["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/InternetAlertView"]]},"references":{"doc://com.yababaGmbH.yababa/documentation/Yababa/SharedData":{"role":"symbol","title":"SharedData","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SharedData"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/SharedData","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SharedData"}],"url":"\/documentation\/yababa\/shareddata"},"doc://com.yababaGmbH.yababa/documentation/Yababa/InternetAlertView":{"role":"symbol","title":"InternetAlertView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"InternetAlertView"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/InternetAlertView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"InternetAlertView"}],"url":"\/documentation\/yababa\/internetalertview"},"doc://com.yababaGmbH.yababa/documentation/Yababa":{"role":"collection","title":"Yababa","abstract":[{"type":"text","text":"Getting Started"}],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa","kind":"symbol","type":"topic","url":"\/documentation\/yababa"},"doc://com.yababaGmbH.yababa/documentation/Yababa/InternetAlertView/Manager":{"role":"symbol","title":"Manager","fragments":[{"kind":"identifier","text":"Manager"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/InternetAlertView\/Manager","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/internetalertview\/manager"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1SharedData\/title","value":"SharedData"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1SharedData\/fragments","value":[{"kind":"identifier","text":"SharedData"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1InternetAlertView\/title","value":"InternetAlertView"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1InternetAlertView\/fragments","value":[{"kind":"identifier","text":"InternetAlertView"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}