{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"appHasBeenLoggedInStateAtleastOnce"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/yababa\/appmanager\/apphasbeenloggedinstateatleastonce()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/yababa\/appmanager\/apphasbeenloggedinstateatleastonce()"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AppManager\/appHasBeenLoggedInStateAtleastOnce()","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"appHasBeenLoggedInStateAtleastOnce"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"title":"appHasBeenLoggedInStateAtleastOnce()","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@M@Yababa@objc(cs)AppManager(im)appHasBeenLoggedInStateAtleastOnce","modules":[{"name":"Yababa"}],"navigatorTitle":[{"kind":"identifier","text":"appHasBeenLoggedInStateAtleastOnce"}]},"hierarchy":{"paths":[["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AppManager"]]},"references":{"doc://com.yababaGmbH.yababa/documentation/Yababa/AppManager":{"role":"symbol","title":"AppManager","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AppManager"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AppManager","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AppManager"}],"url":"\/documentation\/yababa\/appmanager"},"doc://com.yababaGmbH.yababa/documentation/Yababa":{"role":"collection","title":"Yababa","abstract":[{"type":"text","text":"Getting Started"}],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa","kind":"symbol","type":"topic","url":"\/documentation\/yababa"},"doc://com.yababaGmbH.yababa/documentation/Yababa/AppManager/appHasBeenLoggedInStateAtleastOnce()":{"role":"symbol","title":"appHasBeenLoggedInStateAtleastOnce()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"appHasBeenLoggedInStateAtleastOnce"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AppManager\/appHasBeenLoggedInStateAtleastOnce()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"appHasBeenLoggedInStateAtleastOnce"}],"url":"\/documentation\/yababa\/appmanager\/apphasbeenloggedinstateatleastonce()"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"appHasBeenLoggedInStateAtleastOnce"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"appHasBeenLoggedInStateAtleastOnce"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":") "},{"kind":"identifier","text":"appHasBeenLoggedInStateAtleastOnce"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1AppManager\/title","value":"AppManager"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1AppManager\/fragments","value":[{"kind":"identifier","text":"AppManager"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1AppManager~1appHasBeenLoggedInStateAtleastOnce()\/title","value":"appHasBeenLoggedInStateAtleastOnce"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1AppManager~1appHasBeenLoggedInStateAtleastOnce()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"appHasBeenLoggedInStateAtleastOnce"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}