{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"currentTabBarController"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/TabBarController","preciseIdentifier":"c:@M@Yababa@objc(cs)TabBarController","text":"TabBarController"},{"kind":"text","text":"!"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/yababa\/appmanager\/currenttabbarcontroller"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/yababa\/appmanager\/currenttabbarcontroller"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AppManager\/currentTabBarController","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"currentTabBarController"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TabBarController","preciseIdentifier":"c:@M@Yababa@objc(cs)TabBarController"},{"kind":"text","text":"!"}],"title":"currentTabBarController","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:@M@Yababa@objc(cs)AppManager(py)currentTabBarController","modules":[{"name":"Yababa"}],"navigatorTitle":[{"kind":"identifier","text":"currentTabBarController"}]},"hierarchy":{"paths":[["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AppManager"]]},"references":{"doc://com.yababaGmbH.yababa/documentation/Yababa/AppManager":{"role":"symbol","title":"AppManager","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AppManager"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AppManager","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AppManager"}],"url":"\/documentation\/yababa\/appmanager"},"doc://com.yababaGmbH.yababa/documentation/Yababa":{"role":"collection","title":"Yababa","abstract":[{"type":"text","text":"Getting Started"}],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa","kind":"symbol","type":"topic","url":"\/documentation\/yababa"},"doc://com.yababaGmbH.yababa/documentation/Yababa/TabBarController":{"role":"symbol","title":"TabBarController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TabBarController"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/TabBarController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"TabBarController"}],"url":"\/documentation\/yababa\/tabbarcontroller"},"doc://com.yababaGmbH.yababa/documentation/Yababa/AppManager/currentTabBarController":{"role":"symbol","title":"currentTabBarController","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"currentTabBarController"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TabBarController","preciseIdentifier":"c:@M@Yababa@objc(cs)TabBarController"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AppManager\/currentTabBarController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"currentTabBarController"}],"url":"\/documentation\/yababa\/appmanager\/currenttabbarcontroller"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"currentTabBarController"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"currentTabBarController"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/TabBarController","preciseIdentifier":"c:@M@Yababa@objc(cs)TabBarController","text":"TabBarController"},{"kind":"text","text":" * "},{"kind":"identifier","text":"currentTabBarController"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1AppManager\/title","value":"AppManager"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1AppManager\/fragments","value":[{"kind":"identifier","text":"AppManager"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1TabBarController\/title","value":"TabBarController"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1TabBarController\/fragments","value":[{"kind":"identifier","text":"TabBarController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1AppManager~1currentTabBarController\/title","value":"currentTabBarController"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1AppManager~1currentTabBarController\/fragments","value":[{"kind":"identifier","text":"currentTabBarController"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}