{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@IBOutlet"},{"kind":"text","text":" "},{"kind":"keyword","text":"weak"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"phoneTextField"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/MyPhoneNumberTextField","preciseIdentifier":"c:@M@Yababa@objc(cs)MyPhoneNumberTextField","text":"MyPhoneNumberTextField"},{"kind":"text","text":"!"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/yababa\/completeprofilesceneviewcontroller\/phonetextfield"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/yababa\/completeprofilesceneviewcontroller\/phonetextfield"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CompleteProfileSceneViewController\/phoneTextField","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"phoneTextField"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MyPhoneNumberTextField","preciseIdentifier":"c:@M@Yababa@objc(cs)MyPhoneNumberTextField"},{"kind":"text","text":"!"}],"title":"phoneTextField","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:@M@Yababa@objc(cs)CompleteProfileSceneViewController(py)phoneTextField","modules":[{"name":"Yababa"}],"navigatorTitle":[{"kind":"identifier","text":"phoneTextField"}]},"hierarchy":{"paths":[["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CompleteProfileSceneViewController"]]},"references":{"doc://com.yababaGmbH.yababa/documentation/Yababa":{"role":"collection","title":"Yababa","abstract":[{"type":"text","text":"Getting Started"}],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa","kind":"symbol","type":"topic","url":"\/documentation\/yababa"},"doc://com.yababaGmbH.yababa/documentation/Yababa/MyPhoneNumberTextField":{"role":"symbol","title":"MyPhoneNumberTextField","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MyPhoneNumberTextField"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/MyPhoneNumberTextField","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MyPhoneNumberTextField"}],"url":"\/documentation\/yababa\/myphonenumbertextfield"},"doc://com.yababaGmbH.yababa/documentation/Yababa/CompleteProfileSceneViewController/phoneTextField":{"role":"symbol","title":"phoneTextField","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"phoneTextField"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MyPhoneNumberTextField","preciseIdentifier":"c:@M@Yababa@objc(cs)MyPhoneNumberTextField"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CompleteProfileSceneViewController\/phoneTextField","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"phoneTextField"}],"url":"\/documentation\/yababa\/completeprofilesceneviewcontroller\/phonetextfield"},"doc://com.yababaGmbH.yababa/documentation/Yababa/CompleteProfileSceneViewController":{"role":"symbol","title":"CompleteProfileSceneViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CompleteProfileSceneViewController"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CompleteProfileSceneViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CompleteProfileSceneViewController"}],"url":"\/documentation\/yababa\/completeprofilesceneviewcontroller"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"phoneTextField"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"phoneTextField"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"weak"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/MyPhoneNumberTextField","preciseIdentifier":"c:@M@Yababa@objc(cs)MyPhoneNumberTextField","text":"MyPhoneNumberTextField"},{"kind":"text","text":" * "},{"kind":"identifier","text":"phoneTextField"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1MyPhoneNumberTextField\/title","value":"MyPhoneNumberTextField"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1MyPhoneNumberTextField\/fragments","value":[{"kind":"identifier","text":"MyPhoneNumberTextField"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1CompleteProfileSceneViewController~1phoneTextField\/title","value":"phoneTextField"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1CompleteProfileSceneViewController~1phoneTextField\/fragments","value":[{"kind":"identifier","text":"phoneTextField"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1CompleteProfileSceneViewController\/title","value":"CompleteProfileSceneViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1CompleteProfileSceneViewController\/fragments","value":[{"kind":"identifier","text":"CompleteProfileSceneViewController"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}