{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@IBOutlet"},{"kind":"text","text":" "},{"kind":"keyword","text":"weak"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"subTitleLabel"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UILabel","preciseIdentifier":"c:objc(cs)UILabel"},{"kind":"text","text":"!"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/yababa\/completeprofilesceneviewcontroller\/subtitlelabel"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/yababa\/completeprofilesceneviewcontroller\/subtitlelabel"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CompleteProfileSceneViewController\/subTitleLabel","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"subTitleLabel"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UILabel","preciseIdentifier":"c:objc(cs)UILabel"},{"kind":"text","text":"!"}],"title":"subTitleLabel","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:@M@Yababa@objc(cs)CompleteProfileSceneViewController(py)subTitleLabel","modules":[{"name":"Yababa"}],"navigatorTitle":[{"kind":"identifier","text":"subTitleLabel"}]},"hierarchy":{"paths":[["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CompleteProfileSceneViewController"]]},"references":{"doc://com.yababaGmbH.yababa/documentation/Yababa":{"role":"collection","title":"Yababa","abstract":[{"type":"text","text":"Getting Started"}],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa","kind":"symbol","type":"topic","url":"\/documentation\/yababa"},"doc://com.yababaGmbH.yababa/documentation/Yababa/CompleteProfileSceneViewController":{"role":"symbol","title":"CompleteProfileSceneViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CompleteProfileSceneViewController"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CompleteProfileSceneViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CompleteProfileSceneViewController"}],"url":"\/documentation\/yababa\/completeprofilesceneviewcontroller"},"doc://com.yababaGmbH.yababa/documentation/Yababa/CompleteProfileSceneViewController/subTitleLabel":{"role":"symbol","title":"subTitleLabel","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"subTitleLabel"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UILabel","preciseIdentifier":"c:objc(cs)UILabel"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CompleteProfileSceneViewController\/subTitleLabel","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"subTitleLabel"}],"url":"\/documentation\/yababa\/completeprofilesceneviewcontroller\/subtitlelabel"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"subTitleLabel"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"subTitleLabel"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"weak"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"UILabel","preciseIdentifier":"c:objc(cs)UILabel"},{"kind":"text","text":" * "},{"kind":"identifier","text":"subTitleLabel"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1CompleteProfileSceneViewController\/title","value":"CompleteProfileSceneViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1CompleteProfileSceneViewController\/fragments","value":[{"kind":"identifier","text":"CompleteProfileSceneViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1CompleteProfileSceneViewController~1subTitleLabel\/title","value":"subTitleLabel"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1CompleteProfileSceneViewController~1subTitleLabel\/fragments","value":[{"kind":"identifier","text":"subTitleLabel"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}