{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"homeScreen"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/HomeScreen","preciseIdentifier":"c:@M@Yababa@objc(cs)HomeScreen","text":"HomeScreen"},{"kind":"text","text":"?"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/yababa\/homenavigationcontroller\/homescreen"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/HomeNavigationController\/homeScreen","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"homeScreen"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"HomeScreen","preciseIdentifier":"c:@M@Yababa@objc(cs)HomeScreen"},{"kind":"text","text":"?"}],"title":"homeScreen","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"s:6Yababa24HomeNavigationControllerC10homeScreenAA0bF0CSgvp","modules":[{"name":"Yababa"}]},"hierarchy":{"paths":[["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/HomeNavigationController"]]},"references":{"doc://com.yababaGmbH.yababa/documentation/Yababa/HomeNavigationController/homeScreen":{"role":"symbol","title":"homeScreen","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"homeScreen"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"HomeScreen","preciseIdentifier":"c:@M@Yababa@objc(cs)HomeScreen"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/HomeNavigationController\/homeScreen","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/homenavigationcontroller\/homescreen"},"doc://com.yababaGmbH.yababa/documentation/Yababa/HomeNavigationController":{"role":"symbol","title":"HomeNavigationController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HomeNavigationController"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/HomeNavigationController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HomeNavigationController"}],"url":"\/documentation\/yababa\/homenavigationcontroller"},"doc://com.yababaGmbH.yababa/documentation/Yababa":{"role":"collection","title":"Yababa","abstract":[{"type":"text","text":"Getting Started"}],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa","kind":"symbol","type":"topic","url":"\/documentation\/yababa"},"doc://com.yababaGmbH.yababa/documentation/Yababa/HomeScreen":{"role":"symbol","title":"HomeScreen","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HomeScreen"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/HomeScreen","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HomeScreen"}],"url":"\/documentation\/yababa\/homescreen"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1HomeNavigationController\/title","value":"HomeNavigationController"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1HomeNavigationController\/fragments","value":[{"kind":"identifier","text":"HomeNavigationController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1HomeScreen\/title","value":"HomeScreen"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1HomeScreen\/fragments","value":[{"kind":"identifier","text":"HomeScreen"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}