{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"ConfigFetchTimeout"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/yababa\/remoteconfigmanager\/configfetchtimeout"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/yababa\/remoteconfigmanager\/configfetchtimeout"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/RemoteConfigManager\/ConfigFetchTimeout","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"ConfigFetchTimeout"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"title":"ConfigFetchTimeout","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:@M@Yababa@objc(cs)RemoteConfigManager(py)ConfigFetchTimeout","modules":[{"name":"Yababa"}],"navigatorTitle":[{"kind":"identifier","text":"ConfigFetchTimeout"}]},"hierarchy":{"paths":[["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/RemoteConfigManager"]]},"references":{"doc://com.yababaGmbH.yababa/documentation/Yababa/RemoteConfigManager/ConfigFetchTimeout":{"role":"symbol","title":"ConfigFetchTimeout","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"ConfigFetchTimeout"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/RemoteConfigManager\/ConfigFetchTimeout","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ConfigFetchTimeout"}],"url":"\/documentation\/yababa\/remoteconfigmanager\/configfetchtimeout"},"doc://com.yababaGmbH.yababa/documentation/Yababa":{"role":"collection","title":"Yababa","abstract":[{"type":"text","text":"Getting Started"}],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa","kind":"symbol","type":"topic","url":"\/documentation\/yababa"},"doc://com.yababaGmbH.yababa/documentation/Yababa/RemoteConfigManager":{"role":"symbol","title":"RemoteConfigManager","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"RemoteConfigManager"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/RemoteConfigManager","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"RemoteConfigManager"}],"url":"\/documentation\/yababa\/remoteconfigmanager"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"ConfigFetchTimeout"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"ConfigFetchTimeout"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"},{"kind":"text","text":" "},{"kind":"identifier","text":"ConfigFetchTimeout"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1RemoteConfigManager~1ConfigFetchTimeout\/title","value":"ConfigFetchTimeout"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1RemoteConfigManager~1ConfigFetchTimeout\/fragments","value":[{"kind":"identifier","text":"ConfigFetchTimeout"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1RemoteConfigManager\/title","value":"RemoteConfigManager"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1RemoteConfigManager\/fragments","value":[{"kind":"identifier","text":"RemoteConfigManager"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}