{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"fetchAndActivate"},{"kind":"text","text":"("},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": "},{"kind":"attribute","text":"@escaping"},{"kind":"text","text":" ("},{"kind":"typeIdentifier","text":"RemoteConfigFetchAndActivateStatus","preciseIdentifier":"c:@E@FIRRemoteConfigFetchAndActivateStatus"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/yababa\/remoteconfigmanager\/fetchandactivate(completion:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/yababa\/remoteconfigmanager\/fetchandactivate(completion:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/RemoteConfigManager\/fetchAndActivate(completion:)","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"fetchAndActivate"},{"kind":"text","text":"("},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": ("},{"kind":"typeIdentifier","text":"RemoteConfigFetchAndActivateStatus","preciseIdentifier":"c:@E@FIRRemoteConfigFetchAndActivateStatus"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"title":"fetchAndActivate(completion:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@M@Yababa@objc(cs)RemoteConfigManager(im)fetchAndActivateWithCompletion:","modules":[{"name":"Yababa"}],"navigatorTitle":[{"kind":"identifier","text":"fetchAndActivateWithCompletion:"}]},"hierarchy":{"paths":[["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/RemoteConfigManager"]]},"references":{"doc://com.yababaGmbH.yababa/documentation/Yababa":{"role":"collection","title":"Yababa","abstract":[{"type":"text","text":"Getting Started"}],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa","kind":"symbol","type":"topic","url":"\/documentation\/yababa"},"doc://com.yababaGmbH.yababa/documentation/Yababa/RemoteConfigManager/fetchAndActivate(completion:)":{"role":"symbol","title":"fetchAndActivate(completion:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"fetchAndActivate"},{"kind":"text","text":"("},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": ("},{"kind":"typeIdentifier","text":"RemoteConfigFetchAndActivateStatus","preciseIdentifier":"c:@E@FIRRemoteConfigFetchAndActivateStatus"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/RemoteConfigManager\/fetchAndActivate(completion:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"fetchAndActivateWithCompletion:"}],"url":"\/documentation\/yababa\/remoteconfigmanager\/fetchandactivate(completion:)"},"doc://com.yababaGmbH.yababa/documentation/Yababa/RemoteConfigManager":{"role":"symbol","title":"RemoteConfigManager","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"RemoteConfigManager"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/RemoteConfigManager","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"RemoteConfigManager"}],"url":"\/documentation\/yababa\/remoteconfigmanager"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"fetchAndActivateWithCompletion:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"fetchAndActivateWithCompletion:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"fetchAndActivateWithCompletion:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"void (^)(enum FIRRemoteConfigFetchAndActivateStatus)","preciseIdentifier":"c:BFv(#$@E@FIRRemoteConfigFetchAndActivateStatus)"},{"kind":"text","text":")"},{"kind":"internalParam","text":"completion"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1RemoteConfigManager~1fetchAndActivate(completion:)\/title","value":"fetchAndActivateWithCompletion:"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1RemoteConfigManager~1fetchAndActivate(completion:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"fetchAndActivateWithCompletion:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1RemoteConfigManager\/title","value":"RemoteConfigManager"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1RemoteConfigManager\/fragments","value":[{"kind":"identifier","text":"RemoteConfigManager"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}