{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@IBAction"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onDismissCompleteProcess"},{"kind":"text","text":"()"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/yababa\/fragmentdrawerviewcontroller\/ondismisscompleteprocess()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/yababa\/fragmentdrawerviewcontroller\/ondismisscompleteprocess()"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/FragmentDrawerViewController\/onDismissCompleteProcess()","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onDismissCompleteProcess"},{"kind":"text","text":"()"}],"title":"onDismissCompleteProcess()","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@M@Yababa@objc(cs)FragmentDrawerViewController(im)onDismissCompleteProcess","modules":[{"name":"Yababa"}],"navigatorTitle":[{"kind":"identifier","text":"onDismissCompleteProcess"}]},"hierarchy":{"paths":[["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/FragmentDrawerViewController"]]},"references":{"doc://com.yababaGmbH.yababa/documentation/Yababa/FragmentDrawerViewController/onDismissCompleteProcess()":{"role":"symbol","title":"onDismissCompleteProcess()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onDismissCompleteProcess"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/FragmentDrawerViewController\/onDismissCompleteProcess()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"onDismissCompleteProcess"}],"url":"\/documentation\/yababa\/fragmentdrawerviewcontroller\/ondismisscompleteprocess()"},"doc://com.yababaGmbH.yababa/documentation/Yababa/FragmentDrawerViewController":{"role":"symbol","title":"FragmentDrawerViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FragmentDrawerViewController"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/FragmentDrawerViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FragmentDrawerViewController"}],"url":"\/documentation\/yababa\/fragmentdrawerviewcontroller"},"doc://com.yababaGmbH.yababa/documentation/Yababa":{"role":"collection","title":"Yababa","abstract":[{"type":"text","text":"Getting Started"}],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa","kind":"symbol","type":"topic","url":"\/documentation\/yababa"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"onDismissCompleteProcess"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onDismissCompleteProcess"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"onDismissCompleteProcess"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1FragmentDrawerViewController~1onDismissCompleteProcess()\/title","value":"onDismissCompleteProcess"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1FragmentDrawerViewController~1onDismissCompleteProcess()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onDismissCompleteProcess"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1FragmentDrawerViewController\/title","value":"FragmentDrawerViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1FragmentDrawerViewController\/fragments","value":[{"kind":"identifier","text":"FragmentDrawerViewController"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}