{"variants":[{"paths":["\/documentation\/yababa\/deliveryareasviewcontroller\/uicollectionviewdelegate-implementations"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/yababa\/deliveryareasviewcontroller\/uicollectionviewdelegate-implementations"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"identifier":{"url":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/DeliveryAreasViewController\/UICollectionViewDelegate-Implementations","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/DeliveryAreasViewController\/collectionView(_:didEndDisplaying:forItemAt:)"],"generated":true}],"kind":"article","metadata":{"modules":[{"name":"Yababa"}],"role":"collectionGroup","title":"UICollectionViewDelegate Implementations"},"hierarchy":{"paths":[["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/DeliveryAreasViewController"]]},"references":{"doc://com.yababaGmbH.yababa/documentation/Yababa/DeliveryAreasViewController":{"role":"symbol","title":"DeliveryAreasViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DeliveryAreasViewController"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/DeliveryAreasViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DeliveryAreasViewController"}],"url":"\/documentation\/yababa\/deliveryareasviewcontroller"},"doc://com.yababaGmbH.yababa/documentation/Yababa/DeliveryAreasViewController/collectionView(_:didEndDisplaying:forItemAt:)":{"role":"symbol","title":"collectionView(_:didEndDisplaying:forItemAt:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"collectionView"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UICollectionView","preciseIdentifier":"c:objc(cs)UICollectionView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didEndDisplaying"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UICollectionViewCell","preciseIdentifier":"c:objc(cs)UICollectionViewCell"},{"kind":"text","text":", "},{"kind":"externalParam","text":"forItemAt"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"IndexPath","preciseIdentifier":"s:10Foundation9IndexPathV"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/DeliveryAreasViewController\/collectionView(_:didEndDisplaying:forItemAt:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"collectionView:didEndDisplayingCell:forItemAtIndexPath:"}],"url":"\/documentation\/yababa\/deliveryareasviewcontroller\/collectionview(_:didenddisplaying:foritemat:)"},"doc://com.yababaGmbH.yababa/documentation/Yababa":{"role":"collection","title":"Yababa","abstract":[{"type":"text","text":"Getting Started"}],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa","kind":"symbol","type":"topic","url":"\/documentation\/yababa"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/DeliveryAreasViewController\/collectionView(_:didEndDisplaying:forItemAt:)"],"generated":true}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1DeliveryAreasViewController\/title","value":"DeliveryAreasViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1DeliveryAreasViewController\/fragments","value":[{"kind":"identifier","text":"DeliveryAreasViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1DeliveryAreasViewController~1collectionView(_:didEndDisplaying:forItemAt:)\/title","value":"collectionView:didEndDisplayingCell:forItemAtIndexPath:"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1DeliveryAreasViewController~1collectionView(_:didEndDisplaying:forItemAt:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"collectionView:didEndDisplayingCell:forItemAtIndexPath:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}