{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"searchBar"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"searchBar"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UISearchBar","preciseIdentifier":"c:objc(cs)UISearchBar"},{"kind":"text","text":", "},{"kind":"externalParam","text":"textDidChange"},{"kind":"text","text":" "},{"kind":"internalParam","text":"searchText"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/yababa\/searchviewcontroller\/searchbar(_:textdidchange:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/yababa\/searchviewcontroller\/searchbar(_:textdidchange:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/SearchViewController\/searchBar(_:textDidChange:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"UISearchBarDelegate.searchBar(_:textDidChange:)"},{"type":"text","text":"."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"searchBar"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UISearchBar","preciseIdentifier":"c:objc(cs)UISearchBar"},{"kind":"text","text":", "},{"kind":"externalParam","text":"textDidChange"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"title":"searchBar(_:textDidChange:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@CM@Yababa@objc(cs)SearchViewController(im)searchBar:textDidChange:","modules":[{"name":"Yababa"}],"navigatorTitle":[{"kind":"identifier","text":"searchBar:textDidChange:"}]},"hierarchy":{"paths":[["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/SearchViewController","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/SearchViewController\/UISearchBarDelegate-Implementations"]]},"references":{"doc://com.yababaGmbH.yababa/documentation/Yababa/SearchViewController/UISearchBarDelegate-Implementations":{"role":"collectionGroup","title":"UISearchBarDelegate Implementations","abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/SearchViewController\/UISearchBarDelegate-Implementations","kind":"article","type":"topic","url":"\/documentation\/yababa\/searchviewcontroller\/uisearchbardelegate-implementations"},"doc://com.yababaGmbH.yababa/documentation/Yababa":{"role":"collection","title":"Yababa","abstract":[{"type":"text","text":"Getting Started"}],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa","kind":"symbol","type":"topic","url":"\/documentation\/yababa"},"doc://com.yababaGmbH.yababa/documentation/Yababa/SearchViewController":{"role":"symbol","title":"SearchViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SearchViewController"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/SearchViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SearchViewController"}],"url":"\/documentation\/yababa\/searchviewcontroller"},"doc://com.yababaGmbH.yababa/documentation/Yababa/SearchViewController/searchBar(_:textDidChange:)":{"role":"symbol","title":"searchBar(_:textDidChange:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"searchBar"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UISearchBar","preciseIdentifier":"c:objc(cs)UISearchBar"},{"kind":"text","text":", "},{"kind":"externalParam","text":"textDidChange"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/SearchViewController\/searchBar(_:textDidChange:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"searchBar:textDidChange:"}],"url":"\/documentation\/yababa\/searchviewcontroller\/searchbar(_:textdidchange:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"searchBar:textDidChange:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"searchBar:textDidChange:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"searchBar:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UISearchBar","preciseIdentifier":"c:objc(cs)UISearchBar"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"searchBar"},{"kind":"text","text":" "},{"kind":"identifier","text":"textDidChange:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"searchText"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1SearchViewController\/title","value":"SearchViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1SearchViewController\/fragments","value":[{"kind":"identifier","text":"SearchViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1SearchViewController~1searchBar(_:textDidChange:)\/title","value":"searchBar:textDidChange:"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1SearchViewController~1searchBar(_:textDidChange:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"searchBar:textDidChange:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}