{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"searchResultsViewController"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/SearchResultsViewController","preciseIdentifier":"c:@M@Yababa@objc(cs)SearchResultsViewController","text":"SearchResultsViewController"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/yababa\/searchviewcontroller\/searchresultsviewcontroller"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/SearchViewController\/searchResultsViewController","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"searchResultsViewController"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SearchResultsViewController","preciseIdentifier":"c:@M@Yababa@objc(cs)SearchResultsViewController"}],"title":"searchResultsViewController","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"s:6Yababa20SearchViewControllerC013searchResultscD0AA0bfcD0Cvp","modules":[{"name":"Yababa"}]},"hierarchy":{"paths":[["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/SearchViewController"]]},"references":{"doc://com.yababaGmbH.yababa/documentation/Yababa/SearchViewController/searchResultsViewController":{"role":"symbol","title":"searchResultsViewController","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"searchResultsViewController"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SearchResultsViewController","preciseIdentifier":"c:@M@Yababa@objc(cs)SearchResultsViewController"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/SearchViewController\/searchResultsViewController","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/searchviewcontroller\/searchresultsviewcontroller"},"doc://com.yababaGmbH.yababa/documentation/Yababa/SearchViewController":{"role":"symbol","title":"SearchViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SearchViewController"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/SearchViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SearchViewController"}],"url":"\/documentation\/yababa\/searchviewcontroller"},"doc://com.yababaGmbH.yababa/documentation/Yababa/SearchResultsViewController":{"role":"symbol","title":"SearchResultsViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SearchResultsViewController"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/SearchResultsViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SearchResultsViewController"}],"url":"\/documentation\/yababa\/searchresultsviewcontroller"},"doc://com.yababaGmbH.yababa/documentation/Yababa":{"role":"collection","title":"Yababa","abstract":[{"type":"text","text":"Getting Started"}],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa","kind":"symbol","type":"topic","url":"\/documentation\/yababa"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1SearchViewController\/title","value":"SearchViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1SearchViewController\/fragments","value":[{"kind":"identifier","text":"SearchViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1SearchResultsViewController\/title","value":"SearchResultsViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1SearchResultsViewController\/fragments","value":[{"kind":"identifier","text":"SearchResultsViewController"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}