{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getUserPushSubscriptionStatus"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/SubscriptionStatus","preciseIdentifier":"c:@M@Yababa@E@SubscriptionStatus","text":"SubscriptionStatus"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/yababa\/pushnotificationinteractor\/getuserpushsubscriptionstatus()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/yababa\/pushnotificationinteractor\/getuserpushsubscriptionstatus()"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/PushNotificationInteractor\/getUserPushSubscriptionStatus()","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"PushNotificationInteractorProtocol.getUserPushSubscriptionStatus()"},{"type":"text","text":"."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getUserPushSubscriptionStatus"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"SubscriptionStatus","preciseIdentifier":"c:@M@Yababa@E@SubscriptionStatus"}],"title":"getUserPushSubscriptionStatus()","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@M@Yababa@objc(cs)PushNotificationInteractor(im)getUserPushSubscriptionStatus","modules":[{"name":"Yababa"}],"navigatorTitle":[{"kind":"identifier","text":"getUserPushSubscriptionStatus"}]},"hierarchy":{"paths":[["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/PushNotificationInteractor"]]},"references":{"doc://com.yababaGmbH.yababa/documentation/Yababa/SubscriptionStatus":{"role":"symbol","title":"SubscriptionStatus","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SubscriptionStatus"}],"abstract":[{"type":"text","text":"OPTED_IN: subscribed, and explicitly opted in."},{"type":"text","text":" "},{"type":"text","text":"SUBSCRIBED: subscribed, but not explicitly opted in."},{"type":"text","text":" "},{"type":"text","text":"UNSUBSCRIBED: unsubscribed and\/or explicitly opted out."}],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/SubscriptionStatus","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SubscriptionStatus"}],"url":"\/documentation\/yababa\/subscriptionstatus"},"doc://com.yababaGmbH.yababa/documentation/Yababa/PushNotificationInteractor":{"role":"symbol","title":"PushNotificationInteractor","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PushNotificationInteractor"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/PushNotificationInteractor","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PushNotificationInteractor"}],"url":"\/documentation\/yababa\/pushnotificationinteractor"},"doc://com.yababaGmbH.yababa/documentation/Yababa":{"role":"collection","title":"Yababa","abstract":[{"type":"text","text":"Getting Started"}],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa","kind":"symbol","type":"topic","url":"\/documentation\/yababa"},"doc://com.yababaGmbH.yababa/documentation/Yababa/PushNotificationInteractor/getUserPushSubscriptionStatus()":{"role":"symbol","title":"getUserPushSubscriptionStatus()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getUserPushSubscriptionStatus"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"SubscriptionStatus","preciseIdentifier":"c:@M@Yababa@E@SubscriptionStatus"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/PushNotificationInteractor\/getUserPushSubscriptionStatus()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"getUserPushSubscriptionStatus"}],"url":"\/documentation\/yababa\/pushnotificationinteractor\/getuserpushsubscriptionstatus()"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"getUserPushSubscriptionStatus"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"getUserPushSubscriptionStatus"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/SubscriptionStatus","preciseIdentifier":"c:@M@Yababa@E@SubscriptionStatus","text":"SubscriptionStatus"},{"kind":"text","text":") "},{"kind":"identifier","text":"getUserPushSubscriptionStatus"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1SubscriptionStatus\/title","value":"SubscriptionStatus"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1SubscriptionStatus\/fragments","value":[{"kind":"identifier","text":"SubscriptionStatus"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1PushNotificationInteractor\/title","value":"PushNotificationInteractor"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1PushNotificationInteractor\/fragments","value":[{"kind":"identifier","text":"PushNotificationInteractor"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1PushNotificationInteractor~1getUserPushSubscriptionStatus()\/title","value":"getUserPushSubscriptionStatus"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1PushNotificationInteractor~1getUserPushSubscriptionStatus()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"getUserPushSubscriptionStatus"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}