{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"currentUser"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/UserData","preciseIdentifier":"c:objc(cs)UserData","text":"UserData"},{"kind":"text","text":"! { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/yababa\/shareddata\/currentuser"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/yababa\/shareddata\/currentuser"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/SharedData\/currentUser","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"currentUser"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UserData","preciseIdentifier":"c:objc(cs)UserData"},{"kind":"text","text":"!"}],"title":"currentUser","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:objc(cs)SharedData(py)currentUser","modules":[{"name":"Yababa"}],"navigatorTitle":[{"kind":"identifier","text":"currentUser"}]},"hierarchy":{"paths":[["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/SharedData"]]},"references":{"doc://com.yababaGmbH.yababa/documentation/Yababa/UserData":{"role":"symbol","title":"UserData","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"UserData"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/UserData","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"UserData"}],"url":"\/documentation\/yababa\/userdata"},"doc://com.yababaGmbH.yababa/documentation/Yababa/SharedData":{"role":"symbol","title":"SharedData","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SharedData"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/SharedData","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SharedData"}],"url":"\/documentation\/yababa\/shareddata"},"doc://com.yababaGmbH.yababa/documentation/Yababa/SharedData/currentUser":{"role":"symbol","title":"currentUser","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"currentUser"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UserData","preciseIdentifier":"c:objc(cs)UserData"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/SharedData\/currentUser","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"currentUser"}],"url":"\/documentation\/yababa\/shareddata\/currentuser"},"doc://com.yababaGmbH.yababa/documentation/Yababa":{"role":"collection","title":"Yababa","abstract":[{"type":"text","text":"Getting Started"}],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa","kind":"symbol","type":"topic","url":"\/documentation\/yababa"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"currentUser"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"currentUser"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"retain"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/UserData","preciseIdentifier":"c:objc(cs)UserData","text":"UserData"},{"kind":"text","text":" * "},{"kind":"identifier","text":"currentUser"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1UserData\/title","value":"UserData"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1UserData\/fragments","value":[{"kind":"identifier","text":"UserData"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1SharedData\/title","value":"SharedData"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1SharedData\/fragments","value":[{"kind":"identifier","text":"SharedData"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1SharedData~1currentUser\/title","value":"currentUser"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1SharedData~1currentUser\/fragments","value":[{"kind":"identifier","text":"currentUser"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}