{"variants":[{"paths":["\/documentation\/yababa\/brazemanager\/abkinappmessageuidelegate-implementations"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/yababa\/brazemanager\/abkinappmessageuidelegate-implementations"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"identifier":{"url":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/BrazeManager\/ABKInAppMessageUIDelegate-Implementations","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/BrazeManager\/on(inAppMessageButtonClicked:button:)","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/BrazeManager\/on(inAppMessageClicked:)"],"generated":true}],"kind":"article","metadata":{"modules":[{"name":"Yababa"}],"role":"collectionGroup","title":"ABKInAppMessageUIDelegate Implementations"},"hierarchy":{"paths":[["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/BrazeManager"]]},"references":{"doc://com.yababaGmbH.yababa/documentation/Yababa/BrazeManager/on(inAppMessageClicked:)":{"role":"symbol","title":"on(inAppMessageClicked:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"on"},{"kind":"text","text":"("},{"kind":"externalParam","text":"inAppMessageClicked"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ABKInAppMessage","preciseIdentifier":"c:objc(cs)ABKInAppMessage"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/BrazeManager\/on(inAppMessageClicked:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"onInAppMessageClicked:"}],"url":"\/documentation\/yababa\/brazemanager\/on(inappmessageclicked:)"},"doc://com.yababaGmbH.yababa/documentation/Yababa/BrazeManager/on(inAppMessageButtonClicked:button:)":{"role":"symbol","title":"on(inAppMessageButtonClicked:button:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"on"},{"kind":"text","text":"("},{"kind":"externalParam","text":"inAppMessageButtonClicked"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ABKInAppMessageImmersive","preciseIdentifier":"c:objc(cs)ABKInAppMessageImmersive"},{"kind":"text","text":", "},{"kind":"externalParam","text":"button"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ABKInAppMessageButton","preciseIdentifier":"c:objc(cs)ABKInAppMessageButton"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/BrazeManager\/on(inAppMessageButtonClicked:button:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"onInAppMessageButtonClicked:button:"}],"url":"\/documentation\/yababa\/brazemanager\/on(inappmessagebuttonclicked:button:)"},"doc://com.yababaGmbH.yababa/documentation/Yababa":{"role":"collection","title":"Yababa","abstract":[{"type":"text","text":"Getting Started"}],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa","kind":"symbol","type":"topic","url":"\/documentation\/yababa"},"doc://com.yababaGmbH.yababa/documentation/Yababa/BrazeManager":{"role":"symbol","title":"BrazeManager","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"BrazeManager"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/BrazeManager","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"BrazeManager"}],"url":"\/documentation\/yababa\/brazemanager"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/BrazeManager\/on(inAppMessageButtonClicked:button:)","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/BrazeManager\/on(inAppMessageClicked:)"],"generated":true}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1BrazeManager~1on(inAppMessageClicked:)\/title","value":"onInAppMessageClicked:"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1BrazeManager~1on(inAppMessageClicked:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onInAppMessageClicked:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1BrazeManager~1on(inAppMessageButtonClicked:button:)\/title","value":"onInAppMessageButtonClicked:button:"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1BrazeManager~1on(inAppMessageButtonClicked:button:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onInAppMessageButtonClicked:button:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1BrazeManager\/title","value":"BrazeManager"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1BrazeManager\/fragments","value":[{"kind":"identifier","text":"BrazeManager"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}