{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"on"},{"kind":"text","text":"("},{"kind":"externalParam","text":"inAppMessageClicked"},{"kind":"text","text":" "},{"kind":"internalParam","text":"inAppMessage"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ABKInAppMessage","preciseIdentifier":"c:objc(cs)ABKInAppMessage"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/yababa\/brazemanager\/on(inappmessageclicked:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/yababa\/brazemanager\/on(inappmessageclicked:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/BrazeManager\/on(inAppMessageClicked:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"ABKInAppMessageUIDelegate.on(inAppMessageClicked:)"},{"type":"text","text":"."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"on"},{"kind":"text","text":"("},{"kind":"externalParam","text":"inAppMessageClicked"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ABKInAppMessage","preciseIdentifier":"c:objc(cs)ABKInAppMessage"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"title":"on(inAppMessageClicked:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@CM@Yababa@objc(cs)BrazeManager(im)onInAppMessageClicked:","modules":[{"name":"Yababa"}],"navigatorTitle":[{"kind":"identifier","text":"onInAppMessageClicked:"}]},"hierarchy":{"paths":[["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/BrazeManager","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/BrazeManager\/ABKInAppMessageUIDelegate-Implementations"]]},"references":{"doc://com.yababaGmbH.yababa/documentation/Yababa/BrazeManager/on(inAppMessageClicked:)":{"role":"symbol","title":"on(inAppMessageClicked:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"on"},{"kind":"text","text":"("},{"kind":"externalParam","text":"inAppMessageClicked"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ABKInAppMessage","preciseIdentifier":"c:objc(cs)ABKInAppMessage"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/BrazeManager\/on(inAppMessageClicked:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"onInAppMessageClicked:"}],"url":"\/documentation\/yababa\/brazemanager\/on(inappmessageclicked:)"},"doc://com.yababaGmbH.yababa/documentation/Yababa":{"role":"collection","title":"Yababa","abstract":[{"type":"text","text":"Getting Started"}],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa","kind":"symbol","type":"topic","url":"\/documentation\/yababa"},"doc://com.yababaGmbH.yababa/documentation/Yababa/BrazeManager":{"role":"symbol","title":"BrazeManager","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"BrazeManager"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/BrazeManager","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"BrazeManager"}],"url":"\/documentation\/yababa\/brazemanager"},"doc://com.yababaGmbH.yababa/documentation/Yababa/BrazeManager/ABKInAppMessageUIDelegate-Implementations":{"role":"collectionGroup","title":"ABKInAppMessageUIDelegate Implementations","abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/BrazeManager\/ABKInAppMessageUIDelegate-Implementations","kind":"article","type":"topic","url":"\/documentation\/yababa\/brazemanager\/abkinappmessageuidelegate-implementations"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"onInAppMessageClicked:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onInAppMessageClicked:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":") "},{"kind":"identifier","text":"onInAppMessageClicked:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"ABKInAppMessage","preciseIdentifier":"c:objc(cs)ABKInAppMessage"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"inAppMessage"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1BrazeManager~1on(inAppMessageClicked:)\/title","value":"onInAppMessageClicked:"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1BrazeManager~1on(inAppMessageClicked:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onInAppMessageClicked:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1BrazeManager\/title","value":"BrazeManager"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1BrazeManager\/fragments","value":[{"kind":"identifier","text":"BrazeManager"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}