{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"isPhoneNumberValid"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/yababa\/myphonenumbertextfield\/isphonenumbervalid()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/yababa\/myphonenumbertextfield\/isphonenumbervalid()"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/MyPhoneNumberTextField\/isPhoneNumberValid()","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"isPhoneNumberValid"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"title":"isPhoneNumberValid()","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@M@Yababa@objc(cs)MyPhoneNumberTextField(im)isPhoneNumberValid","modules":[{"name":"Yababa"}],"navigatorTitle":[{"kind":"identifier","text":"isPhoneNumberValid"}]},"hierarchy":{"paths":[["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/MyPhoneNumberTextField"]]},"references":{"doc://com.yababaGmbH.yababa/documentation/Yababa":{"role":"collection","title":"Yababa","abstract":[{"type":"text","text":"Getting Started"}],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa","kind":"symbol","type":"topic","url":"\/documentation\/yababa"},"doc://com.yababaGmbH.yababa/documentation/Yababa/MyPhoneNumberTextField":{"role":"symbol","title":"MyPhoneNumberTextField","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MyPhoneNumberTextField"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/MyPhoneNumberTextField","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MyPhoneNumberTextField"}],"url":"\/documentation\/yababa\/myphonenumbertextfield"},"doc://com.yababaGmbH.yababa/documentation/Yababa/MyPhoneNumberTextField/isPhoneNumberValid()":{"role":"symbol","title":"isPhoneNumberValid()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"isPhoneNumberValid"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/MyPhoneNumberTextField\/isPhoneNumberValid()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"isPhoneNumberValid"}],"url":"\/documentation\/yababa\/myphonenumbertextfield\/isphonenumbervalid()"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"isPhoneNumberValid"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"isPhoneNumberValid"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":") "},{"kind":"identifier","text":"isPhoneNumberValid"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1MyPhoneNumberTextField\/title","value":"MyPhoneNumberTextField"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1MyPhoneNumberTextField\/fragments","value":[{"kind":"identifier","text":"MyPhoneNumberTextField"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1MyPhoneNumberTextField~1isPhoneNumberValid()\/title","value":"isPhoneNumberValid"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1MyPhoneNumberTextField~1isPhoneNumberValid()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"isPhoneNumberValid"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}