{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"navigateToDeviceSettings"},{"kind":"text","text":"()"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/yababa\/pushnotificationinteractor\/navigatetodevicesettings()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/yababa\/pushnotificationinteractor\/navigatetodevicesettings()"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/PushNotificationInteractor\/navigateToDeviceSettings()","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Open App in device settings for user to enable push notifications for Yababa"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"navigateToDeviceSettings"},{"kind":"text","text":"()"}],"title":"navigateToDeviceSettings()","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@M@Yababa@objc(cs)PushNotificationInteractor(im)navigateToDeviceSettings","modules":[{"name":"Yababa"}],"navigatorTitle":[{"kind":"identifier","text":"navigateToDeviceSettings"}]},"hierarchy":{"paths":[["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/PushNotificationInteractor"]]},"references":{"doc://com.yababaGmbH.yababa/documentation/Yababa/PushNotificationInteractor":{"role":"symbol","title":"PushNotificationInteractor","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PushNotificationInteractor"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/PushNotificationInteractor","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PushNotificationInteractor"}],"url":"\/documentation\/yababa\/pushnotificationinteractor"},"doc://com.yababaGmbH.yababa/documentation/Yababa":{"role":"collection","title":"Yababa","abstract":[{"type":"text","text":"Getting Started"}],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa","kind":"symbol","type":"topic","url":"\/documentation\/yababa"},"doc://com.yababaGmbH.yababa/documentation/Yababa/PushNotificationInteractor/navigateToDeviceSettings()":{"role":"symbol","title":"navigateToDeviceSettings()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"navigateToDeviceSettings"},{"kind":"text","text":"()"}],"abstract":[{"type":"text","text":"Open App in device settings for user to enable push notifications for Yababa"}],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/PushNotificationInteractor\/navigateToDeviceSettings()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"navigateToDeviceSettings"}],"url":"\/documentation\/yababa\/pushnotificationinteractor\/navigatetodevicesettings()"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"navigateToDeviceSettings"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"navigateToDeviceSettings"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"navigateToDeviceSettings"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1PushNotificationInteractor\/title","value":"PushNotificationInteractor"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1PushNotificationInteractor\/fragments","value":[{"kind":"identifier","text":"PushNotificationInteractor"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1PushNotificationInteractor~1navigateToDeviceSettings()\/title","value":"navigateToDeviceSettings"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1PushNotificationInteractor~1navigateToDeviceSettings()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"navigateToDeviceSettings"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}