{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"requestTrackingAuthorization"},{"kind":"text","text":"()"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/yababa\/permissionsmanager\/requesttrackingauthorization()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/yababa\/permissionsmanager\/requesttrackingauthorization()"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/PermissionsManager\/requestTrackingAuthorization()","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"requestTrackingAuthorization"},{"kind":"text","text":"()"}],"title":"requestTrackingAuthorization()","roleHeading":"Type Method","role":"symbol","symbolKind":"method","externalID":"c:@M@Yababa@objc(cs)PermissionsManager(cm)requestTrackingAuthorization","modules":[{"name":"Yababa"}],"navigatorTitle":[{"kind":"identifier","text":"requestTrackingAuthorization"}]},"hierarchy":{"paths":[["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/PermissionsManager"]]},"references":{"doc://com.yababaGmbH.yababa/documentation/Yababa":{"role":"collection","title":"Yababa","abstract":[{"type":"text","text":"Getting Started"}],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa","kind":"symbol","type":"topic","url":"\/documentation\/yababa"},"doc://com.yababaGmbH.yababa/documentation/Yababa/PermissionsManager/requestTrackingAuthorization()":{"role":"symbol","title":"requestTrackingAuthorization()","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"requestTrackingAuthorization"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/PermissionsManager\/requestTrackingAuthorization()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"requestTrackingAuthorization"}],"url":"\/documentation\/yababa\/permissionsmanager\/requesttrackingauthorization()"},"doc://com.yababaGmbH.yababa/documentation/Yababa/PermissionsManager":{"role":"symbol","title":"PermissionsManager","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PermissionsManager"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/PermissionsManager","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PermissionsManager"}],"url":"\/documentation\/yababa\/permissionsmanager"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Method"},{"op":"replace","path":"\/metadata\/title","value":"requestTrackingAuthorization"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"requestTrackingAuthorization"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"+ ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"requestTrackingAuthorization"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1PermissionsManager~1requestTrackingAuthorization()\/title","value":"requestTrackingAuthorization"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1PermissionsManager~1requestTrackingAuthorization()\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"requestTrackingAuthorization"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1PermissionsManager\/title","value":"PermissionsManager"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1PermissionsManager\/fragments","value":[{"kind":"identifier","text":"PermissionsManager"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}