{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"requestForTimeZone"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withLong"},{"kind":"text","text":" "},{"kind":"internalParam","text":"lng"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"},{"kind":"text","text":", "},{"kind":"externalParam","text":"andLat"},{"kind":"text","text":" "},{"kind":"internalParam","text":"lat"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/yababa\/inrepository\/requestfortimezone(withlong:andlat:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/yababa\/inrepository\/requestfortimezone(withlong:andlat:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/InRepository\/requestForTimeZone(withLong:andLat:)","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"requestForTimeZone"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withLong"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"},{"kind":"text","text":", "},{"kind":"externalParam","text":"andLat"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"},{"kind":"text","text":")"}],"title":"requestForTimeZone(withLong:andLat:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:objc(cs)InRepository(im)RequestForTimeZoneWithLong:andLat:","modules":[{"name":"Yababa"}],"navigatorTitle":[{"kind":"identifier","text":"RequestForTimeZoneWithLong:andLat:"}]},"hierarchy":{"paths":[["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/InRepository"]]},"references":{"doc://com.yababaGmbH.yababa/documentation/Yababa/InRepository":{"role":"symbol","title":"InRepository","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"InRepository"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/InRepository","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"InRepository"}],"url":"\/documentation\/yababa\/inrepository"},"doc://com.yababaGmbH.yababa/documentation/Yababa/InRepository/requestForTimeZone(withLong:andLat:)":{"role":"symbol","title":"requestForTimeZone(withLong:andLat:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"requestForTimeZone"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withLong"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"},{"kind":"text","text":", "},{"kind":"externalParam","text":"andLat"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/InRepository\/requestForTimeZone(withLong:andLat:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"RequestForTimeZoneWithLong:andLat:"}],"url":"\/documentation\/yababa\/inrepository\/requestfortimezone(withlong:andlat:)"},"doc://com.yababaGmbH.yababa/documentation/Yababa":{"role":"collection","title":"Yababa","abstract":[{"type":"text","text":"Getting Started"}],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa","kind":"symbol","type":"topic","url":"\/documentation\/yababa"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"RequestForTimeZoneWithLong:andLat:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"RequestForTimeZoneWithLong:andLat:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"RequestForTimeZoneWithLong:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"double","preciseIdentifier":"c:d"},{"kind":"text","text":")"},{"kind":"internalParam","text":"lng"},{"kind":"text","text":" "},{"kind":"identifier","text":"andLat:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"double","preciseIdentifier":"c:d"},{"kind":"text","text":")"},{"kind":"internalParam","text":"lat"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1InRepository\/title","value":"InRepository"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1InRepository\/fragments","value":[{"kind":"identifier","text":"InRepository"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1InRepository~1requestForTimeZone(withLong:andLat:)\/title","value":"RequestForTimeZoneWithLong:andLat:"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1InRepository~1requestForTimeZone(withLong:andLat:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"RequestForTimeZoneWithLong:andLat:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}