{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getAlertStyle"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"UIAlertController","preciseIdentifier":"c:objc(cs)UIAlertController"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"Style","preciseIdentifier":"c:@E@UIAlertControllerStyle"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/yababa\/appmanager\/getalertstyle()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/yababa\/appmanager\/getalertstyle()"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AppManager\/getAlertStyle()","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getAlertStyle"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"UIAlertController","preciseIdentifier":"c:objc(cs)UIAlertController"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"Style","preciseIdentifier":"c:@E@UIAlertControllerStyle"}],"title":"getAlertStyle()","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@M@Yababa@objc(cs)AppManager(im)getAlertStyle","modules":[{"name":"Yababa"}],"navigatorTitle":[{"kind":"identifier","text":"getAlertStyle"}]},"hierarchy":{"paths":[["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AppManager"]]},"references":{"doc://com.yababaGmbH.yababa/documentation/Yababa":{"role":"collection","title":"Yababa","abstract":[{"type":"text","text":"Getting Started"}],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa","kind":"symbol","type":"topic","url":"\/documentation\/yababa"},"doc://com.yababaGmbH.yababa/documentation/Yababa/AppManager":{"role":"symbol","title":"AppManager","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AppManager"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AppManager","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AppManager"}],"url":"\/documentation\/yababa\/appmanager"},"doc://com.yababaGmbH.yababa/documentation/Yababa/AppManager/getAlertStyle()":{"role":"symbol","title":"getAlertStyle()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getAlertStyle"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"UIAlertController","preciseIdentifier":"c:objc(cs)UIAlertController"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"Style","preciseIdentifier":"c:@E@UIAlertControllerStyle"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AppManager\/getAlertStyle()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"getAlertStyle"}],"url":"\/documentation\/yababa\/appmanager\/getalertstyle()"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"getAlertStyle"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"getAlertStyle"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"typeIdentifier","text":"UIAlertControllerStyle","preciseIdentifier":"c:@E@UIAlertControllerStyle"},{"kind":"text","text":") "},{"kind":"identifier","text":"getAlertStyle"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1AppManager\/title","value":"AppManager"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1AppManager\/fragments","value":[{"kind":"identifier","text":"AppManager"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1AppManager~1getAlertStyle()\/title","value":"getAlertStyle"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1AppManager~1getAlertStyle()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"getAlertStyle"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}