{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"synchronizeUserData"},{"kind":"text","text":"()"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/yababa\/homescreeninteractor\/synchronizeuserdata()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/yababa\/homescreeninteractor\/synchronizeuserdata()"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/HomeScreenInteractor\/synchronizeUserData()","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"HomeScreenInteractorProtocol.synchronizeUserData()"},{"type":"text","text":"."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"synchronizeUserData"},{"kind":"text","text":"()"}],"title":"synchronizeUserData()","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@M@Yababa@objc(cs)HomeScreenInteractor(im)synchronizeUserData","modules":[{"name":"Yababa"}],"navigatorTitle":[{"kind":"identifier","text":"synchronizeUserData"}]},"hierarchy":{"paths":[["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/HomeScreenInteractor"]]},"references":{"doc://com.yababaGmbH.yababa/documentation/Yababa/HomeScreenInteractor":{"role":"symbol","title":"HomeScreenInteractor","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HomeScreenInteractor"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/HomeScreenInteractor","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HomeScreenInteractor"}],"url":"\/documentation\/yababa\/homescreeninteractor"},"doc://com.yababaGmbH.yababa/documentation/Yababa/HomeScreenInteractor/synchronizeUserData()":{"role":"symbol","title":"synchronizeUserData()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"synchronizeUserData"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/HomeScreenInteractor\/synchronizeUserData()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"synchronizeUserData"}],"url":"\/documentation\/yababa\/homescreeninteractor\/synchronizeuserdata()"},"doc://com.yababaGmbH.yababa/documentation/Yababa":{"role":"collection","title":"Yababa","abstract":[{"type":"text","text":"Getting Started"}],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa","kind":"symbol","type":"topic","url":"\/documentation\/yababa"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"synchronizeUserData"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"synchronizeUserData"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"synchronizeUserData"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1HomeScreenInteractor\/title","value":"HomeScreenInteractor"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1HomeScreenInteractor\/fragments","value":[{"kind":"identifier","text":"HomeScreenInteractor"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1HomeScreenInteractor~1synchronizeUserData()\/title","value":"synchronizeUserData"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1HomeScreenInteractor~1synchronizeUserData()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"synchronizeUserData"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}