{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"remoteConfigManager"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/RemoteConfigManager","preciseIdentifier":"c:@M@Yababa@objc(cs)RemoteConfigManager","text":"RemoteConfigManager"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/yababa\/launchscreenmanager\/remoteconfigmanager"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/LaunchScreenManager\/remoteConfigManager","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"remoteConfigManager"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"RemoteConfigManager","preciseIdentifier":"c:@M@Yababa@objc(cs)RemoteConfigManager"}],"title":"remoteConfigManager","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"s:6Yababa19LaunchScreenManagerC012remoteConfigD0AA06RemotefD0Cvp","modules":[{"name":"Yababa"}]},"hierarchy":{"paths":[["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/LaunchScreenManager"]]},"references":{"doc://com.yababaGmbH.yababa/documentation/Yababa/LaunchScreenManager/remoteConfigManager":{"role":"symbol","title":"remoteConfigManager","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"remoteConfigManager"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"RemoteConfigManager","preciseIdentifier":"c:@M@Yababa@objc(cs)RemoteConfigManager"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/LaunchScreenManager\/remoteConfigManager","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/launchscreenmanager\/remoteconfigmanager"},"doc://com.yababaGmbH.yababa/documentation/Yababa":{"role":"collection","title":"Yababa","abstract":[{"type":"text","text":"Getting Started"}],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa","kind":"symbol","type":"topic","url":"\/documentation\/yababa"},"doc://com.yababaGmbH.yababa/documentation/Yababa/LaunchScreenManager":{"role":"symbol","title":"LaunchScreenManager","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"LaunchScreenManager"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/LaunchScreenManager","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"LaunchScreenManager"}],"url":"\/documentation\/yababa\/launchscreenmanager"},"doc://com.yababaGmbH.yababa/documentation/Yababa/RemoteConfigManager":{"role":"symbol","title":"RemoteConfigManager","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"RemoteConfigManager"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/RemoteConfigManager","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"RemoteConfigManager"}],"url":"\/documentation\/yababa\/remoteconfigmanager"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1LaunchScreenManager\/title","value":"LaunchScreenManager"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1LaunchScreenManager\/fragments","value":[{"kind":"identifier","text":"LaunchScreenManager"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1RemoteConfigManager\/title","value":"RemoteConfigManager"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1RemoteConfigManager\/fragments","value":[{"kind":"identifier","text":"RemoteConfigManager"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}