{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@IBAction"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onShowServerSelectionList"},{"kind":"text","text":"()"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/yababa\/welcomesceneviewcontroller\/onshowserverselectionlist()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/yababa\/welcomesceneviewcontroller\/onshowserverselectionlist()"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/WelcomeSceneViewController\/onShowServerSelectionList()","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onShowServerSelectionList"},{"kind":"text","text":"()"}],"title":"onShowServerSelectionList()","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@M@Yababa@objc(cs)WelcomeSceneViewController(im)onShowServerSelectionList","modules":[{"name":"Yababa"}],"navigatorTitle":[{"kind":"identifier","text":"onShowServerSelectionList"}]},"hierarchy":{"paths":[["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/WelcomeSceneViewController"]]},"references":{"doc://com.yababaGmbH.yababa/documentation/Yababa":{"role":"collection","title":"Yababa","abstract":[{"type":"text","text":"Getting Started"}],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa","kind":"symbol","type":"topic","url":"\/documentation\/yababa"},"doc://com.yababaGmbH.yababa/documentation/Yababa/WelcomeSceneViewController":{"role":"symbol","title":"WelcomeSceneViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"WelcomeSceneViewController"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/WelcomeSceneViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"WelcomeSceneViewController"}],"url":"\/documentation\/yababa\/welcomesceneviewcontroller"},"doc://com.yababaGmbH.yababa/documentation/Yababa/WelcomeSceneViewController/onShowServerSelectionList()":{"role":"symbol","title":"onShowServerSelectionList()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onShowServerSelectionList"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/WelcomeSceneViewController\/onShowServerSelectionList()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"onShowServerSelectionList"}],"url":"\/documentation\/yababa\/welcomesceneviewcontroller\/onshowserverselectionlist()"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"onShowServerSelectionList"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onShowServerSelectionList"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"onShowServerSelectionList"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1WelcomeSceneViewController\/title","value":"WelcomeSceneViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1WelcomeSceneViewController\/fragments","value":[{"kind":"identifier","text":"WelcomeSceneViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1WelcomeSceneViewController~1onShowServerSelectionList()\/title","value":"onShowServerSelectionList"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1WelcomeSceneViewController~1onShowServerSelectionList()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onShowServerSelectionList"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}