{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"waitingView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/WaitingView","preciseIdentifier":"c:objc(cs)WaitingView","text":"WaitingView"},{"kind":"text","text":"! { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/yababa\/shareddata\/waitingview"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/yababa\/shareddata\/waitingview"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/SharedData\/waitingView","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"waitingView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"WaitingView","preciseIdentifier":"c:objc(cs)WaitingView"},{"kind":"text","text":"!"}],"title":"waitingView","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:objc(cs)SharedData(py)waitingView","modules":[{"name":"Yababa"}],"navigatorTitle":[{"kind":"identifier","text":"waitingView"}]},"hierarchy":{"paths":[["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/SharedData"]]},"references":{"doc://com.yababaGmbH.yababa/documentation/Yababa/SharedData/waitingView":{"role":"symbol","title":"waitingView","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"waitingView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"WaitingView","preciseIdentifier":"c:objc(cs)WaitingView"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/SharedData\/waitingView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"waitingView"}],"url":"\/documentation\/yababa\/shareddata\/waitingview"},"doc://com.yababaGmbH.yababa/documentation/Yababa/WaitingView":{"role":"symbol","title":"WaitingView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"WaitingView"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/WaitingView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"WaitingView"}],"url":"\/documentation\/yababa\/waitingview"},"doc://com.yababaGmbH.yababa/documentation/Yababa/SharedData":{"role":"symbol","title":"SharedData","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SharedData"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/SharedData","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SharedData"}],"url":"\/documentation\/yababa\/shareddata"},"doc://com.yababaGmbH.yababa/documentation/Yababa":{"role":"collection","title":"Yababa","abstract":[{"type":"text","text":"Getting Started"}],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa","kind":"symbol","type":"topic","url":"\/documentation\/yababa"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"waitingView"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"waitingView"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"retain"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/WaitingView","preciseIdentifier":"c:objc(cs)WaitingView","text":"WaitingView"},{"kind":"text","text":" * "},{"kind":"identifier","text":"waitingView"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1SharedData~1waitingView\/title","value":"waitingView"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1SharedData~1waitingView\/fragments","value":[{"kind":"identifier","text":"waitingView"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1WaitingView\/title","value":"WaitingView"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1WaitingView\/fragments","value":[{"kind":"identifier","text":"WaitingView"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1SharedData\/title","value":"SharedData"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1SharedData\/fragments","value":[{"kind":"identifier","text":"SharedData"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}