{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"weak"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"viewController"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CheckoutSceneViewController","preciseIdentifier":"c:@M@Yababa@objc(cs)CheckoutSceneViewController","text":"CheckoutSceneViewController"},{"kind":"text","text":"?"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/yababa\/checkoutscenerouter\/viewcontroller"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CheckoutSceneRouter\/viewController","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"CheckoutSceneRouterProtocol.viewController"},{"type":"text","text":"."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"viewController"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CheckoutSceneViewController","preciseIdentifier":"c:@M@Yababa@objc(cs)CheckoutSceneViewController"},{"kind":"text","text":"?"}],"title":"viewController","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"s:6Yababa19CheckoutSceneRouterC14viewControllerAA0bc4ViewF0CSgvp","modules":[{"name":"Yababa"}]},"hierarchy":{"paths":[["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CheckoutSceneRouter"]]},"references":{"doc://com.yababaGmbH.yababa/documentation/Yababa":{"role":"collection","title":"Yababa","abstract":[{"type":"text","text":"Getting Started"}],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa","kind":"symbol","type":"topic","url":"\/documentation\/yababa"},"doc://com.yababaGmbH.yababa/documentation/Yababa/CheckoutSceneViewController":{"role":"symbol","title":"CheckoutSceneViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CheckoutSceneViewController"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CheckoutSceneViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CheckoutSceneViewController"}],"url":"\/documentation\/yababa\/checkoutsceneviewcontroller"},"doc://com.yababaGmbH.yababa/documentation/Yababa/CheckoutSceneRouter":{"role":"symbol","title":"CheckoutSceneRouter","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CheckoutSceneRouter"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CheckoutSceneRouter","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CheckoutSceneRouter"}],"url":"\/documentation\/yababa\/checkoutscenerouter"},"doc://com.yababaGmbH.yababa/documentation/Yababa/CheckoutSceneRouter/viewController":{"role":"symbol","title":"viewController","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"viewController"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CheckoutSceneViewController","preciseIdentifier":"c:@M@Yababa@objc(cs)CheckoutSceneViewController"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CheckoutSceneRouter\/viewController","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/checkoutscenerouter\/viewcontroller"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1CheckoutSceneViewController\/title","value":"CheckoutSceneViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1CheckoutSceneViewController\/fragments","value":[{"kind":"identifier","text":"CheckoutSceneViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1CheckoutSceneRouter\/title","value":"CheckoutSceneRouter"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1CheckoutSceneRouter\/fragments","value":[{"kind":"identifier","text":"CheckoutSceneRouter"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}