{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@IBAction"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onPlaceOrder"},{"kind":"text","text":"()"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/yababa\/checkoutsceneviewcontroller\/onplaceorder()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/yababa\/checkoutsceneviewcontroller\/onplaceorder()"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CheckoutSceneViewController\/onPlaceOrder()","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onPlaceOrder"},{"kind":"text","text":"()"}],"title":"onPlaceOrder()","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@M@Yababa@objc(cs)CheckoutSceneViewController(im)onPlaceOrder","modules":[{"name":"Yababa"}],"navigatorTitle":[{"kind":"identifier","text":"onPlaceOrder"}]},"hierarchy":{"paths":[["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CheckoutSceneViewController"]]},"references":{"doc://com.yababaGmbH.yababa/documentation/Yababa":{"role":"collection","title":"Yababa","abstract":[{"type":"text","text":"Getting Started"}],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa","kind":"symbol","type":"topic","url":"\/documentation\/yababa"},"doc://com.yababaGmbH.yababa/documentation/Yababa/CheckoutSceneViewController/onPlaceOrder()":{"role":"symbol","title":"onPlaceOrder()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onPlaceOrder"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CheckoutSceneViewController\/onPlaceOrder()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"onPlaceOrder"}],"url":"\/documentation\/yababa\/checkoutsceneviewcontroller\/onplaceorder()"},"doc://com.yababaGmbH.yababa/documentation/Yababa/CheckoutSceneViewController":{"role":"symbol","title":"CheckoutSceneViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CheckoutSceneViewController"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CheckoutSceneViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CheckoutSceneViewController"}],"url":"\/documentation\/yababa\/checkoutsceneviewcontroller"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"onPlaceOrder"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onPlaceOrder"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"onPlaceOrder"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1CheckoutSceneViewController~1onPlaceOrder()\/title","value":"onPlaceOrder"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1CheckoutSceneViewController~1onPlaceOrder()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onPlaceOrder"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1CheckoutSceneViewController\/title","value":"CheckoutSceneViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1CheckoutSceneViewController\/fragments","value":[{"kind":"identifier","text":"CheckoutSceneViewController"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}