{"variants":[{"paths":["\/documentation\/yababa\/checkoutsceneviewcontroller\/uiviewcontrollertransitioningdelegate-implementations"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/yababa\/checkoutsceneviewcontroller\/uiviewcontrollertransitioningdelegate-implementations"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"identifier":{"url":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CheckoutSceneViewController\/UIViewControllerTransitioningDelegate-Implementations","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CheckoutSceneViewController\/presentationController(forPresented:presenting:source:)"],"generated":true}],"kind":"article","metadata":{"modules":[{"name":"Yababa"}],"role":"collectionGroup","title":"UIViewControllerTransitioningDelegate Implementations"},"hierarchy":{"paths":[["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CheckoutSceneViewController"]]},"references":{"doc://com.yababaGmbH.yababa/documentation/Yababa":{"role":"collection","title":"Yababa","abstract":[{"type":"text","text":"Getting Started"}],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa","kind":"symbol","type":"topic","url":"\/documentation\/yababa"},"doc://com.yababaGmbH.yababa/documentation/Yababa/CheckoutSceneViewController/presentationController(forPresented:presenting:source:)":{"role":"symbol","title":"presentationController(forPresented:presenting:source:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"presentationController"},{"kind":"text","text":"("},{"kind":"externalParam","text":"forPresented"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"presenting"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"source"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"UIPresentationController","preciseIdentifier":"c:objc(cs)UIPresentationController"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CheckoutSceneViewController\/presentationController(forPresented:presenting:source:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"presentationControllerForPresentedViewController:presentingViewController:sourceViewController:"}],"url":"\/documentation\/yababa\/checkoutsceneviewcontroller\/presentationcontroller(forpresented:presenting:source:)"},"doc://com.yababaGmbH.yababa/documentation/Yababa/CheckoutSceneViewController":{"role":"symbol","title":"CheckoutSceneViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CheckoutSceneViewController"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CheckoutSceneViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CheckoutSceneViewController"}],"url":"\/documentation\/yababa\/checkoutsceneviewcontroller"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CheckoutSceneViewController\/presentationController(forPresented:presenting:source:)"],"generated":true}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1CheckoutSceneViewController~1presentationController(forPresented:presenting:source:)\/title","value":"presentationControllerForPresentedViewController:presentingViewController:sourceViewController:"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1CheckoutSceneViewController~1presentationController(forPresented:presenting:source:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"presentationControllerForPresentedViewController:presentingViewController:sourceViewController:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1CheckoutSceneViewController\/title","value":"CheckoutSceneViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1CheckoutSceneViewController\/fragments","value":[{"kind":"identifier","text":"CheckoutSceneViewController"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}