{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@IBOutlet"},{"kind":"text","text":" "},{"kind":"keyword","text":"weak"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"vouchersCollectionView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/DiscountsCollectionView","preciseIdentifier":"c:@M@Yababa@objc(cs)DiscountsCollectionView","text":"DiscountsCollectionView"},{"kind":"text","text":"!"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/yababa\/checkoutsceneviewcontroller\/voucherscollectionview"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/yababa\/checkoutsceneviewcontroller\/voucherscollectionview"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CheckoutSceneViewController\/vouchersCollectionView","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"vouchersCollectionView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DiscountsCollectionView","preciseIdentifier":"c:@M@Yababa@objc(cs)DiscountsCollectionView"},{"kind":"text","text":"!"}],"title":"vouchersCollectionView","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:@M@Yababa@objc(cs)CheckoutSceneViewController(py)vouchersCollectionView","modules":[{"name":"Yababa"}],"navigatorTitle":[{"kind":"identifier","text":"vouchersCollectionView"}]},"hierarchy":{"paths":[["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CheckoutSceneViewController"]]},"references":{"doc://com.yababaGmbH.yababa/documentation/Yababa/DiscountsCollectionView":{"role":"symbol","title":"DiscountsCollectionView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DiscountsCollectionView"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/DiscountsCollectionView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DiscountsCollectionView"}],"url":"\/documentation\/yababa\/discountscollectionview"},"doc://com.yababaGmbH.yababa/documentation/Yababa/CheckoutSceneViewController":{"role":"symbol","title":"CheckoutSceneViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CheckoutSceneViewController"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CheckoutSceneViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CheckoutSceneViewController"}],"url":"\/documentation\/yababa\/checkoutsceneviewcontroller"},"doc://com.yababaGmbH.yababa/documentation/Yababa/CheckoutSceneViewController/vouchersCollectionView":{"role":"symbol","title":"vouchersCollectionView","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"vouchersCollectionView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DiscountsCollectionView","preciseIdentifier":"c:@M@Yababa@objc(cs)DiscountsCollectionView"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CheckoutSceneViewController\/vouchersCollectionView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"vouchersCollectionView"}],"url":"\/documentation\/yababa\/checkoutsceneviewcontroller\/voucherscollectionview"},"doc://com.yababaGmbH.yababa/documentation/Yababa":{"role":"collection","title":"Yababa","abstract":[{"type":"text","text":"Getting Started"}],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa","kind":"symbol","type":"topic","url":"\/documentation\/yababa"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"vouchersCollectionView"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"vouchersCollectionView"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"weak"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/DiscountsCollectionView","preciseIdentifier":"c:@M@Yababa@objc(cs)DiscountsCollectionView","text":"DiscountsCollectionView"},{"kind":"text","text":" * "},{"kind":"identifier","text":"vouchersCollectionView"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1DiscountsCollectionView\/title","value":"DiscountsCollectionView"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1DiscountsCollectionView\/fragments","value":[{"kind":"identifier","text":"DiscountsCollectionView"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1CheckoutSceneViewController\/title","value":"CheckoutSceneViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1CheckoutSceneViewController\/fragments","value":[{"kind":"identifier","text":"CheckoutSceneViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1CheckoutSceneViewController~1vouchersCollectionView\/title","value":"vouchersCollectionView"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1CheckoutSceneViewController~1vouchersCollectionView\/fragments","value":[{"kind":"identifier","text":"vouchersCollectionView"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}