{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"override"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"tabBar"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"tabBar"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UITabBar","preciseIdentifier":"c:objc(cs)UITabBar"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didSelect"},{"kind":"text","text":" "},{"kind":"internalParam","text":"item"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UITabBarItem","preciseIdentifier":"c:objc(cs)UITabBarItem"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/yababa\/tabbarcontroller\/tabbar(_:didselect:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/yababa\/tabbarcontroller\/tabbar(_:didselect:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/TabBarController\/tabBar(_:didSelect:)","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"tabBar"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UITabBar","preciseIdentifier":"c:objc(cs)UITabBar"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didSelect"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UITabBarItem","preciseIdentifier":"c:objc(cs)UITabBarItem"},{"kind":"text","text":")"}],"title":"tabBar(_:didSelect:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@M@Yababa@objc(cs)TabBarController(im)tabBar:didSelectItem:","modules":[{"name":"Yababa"}],"navigatorTitle":[{"kind":"identifier","text":"tabBar:didSelectItem:"}]},"hierarchy":{"paths":[["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/TabBarController"]]},"references":{"doc://com.yababaGmbH.yababa/documentation/Yababa/TabBarController/tabBar(_:didSelect:)":{"role":"symbol","title":"tabBar(_:didSelect:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"tabBar"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UITabBar","preciseIdentifier":"c:objc(cs)UITabBar"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didSelect"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UITabBarItem","preciseIdentifier":"c:objc(cs)UITabBarItem"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/TabBarController\/tabBar(_:didSelect:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"tabBar:didSelectItem:"}],"url":"\/documentation\/yababa\/tabbarcontroller\/tabbar(_:didselect:)"},"doc://com.yababaGmbH.yababa/documentation/Yababa":{"role":"collection","title":"Yababa","abstract":[{"type":"text","text":"Getting Started"}],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa","kind":"symbol","type":"topic","url":"\/documentation\/yababa"},"doc://com.yababaGmbH.yababa/documentation/Yababa/TabBarController":{"role":"symbol","title":"TabBarController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TabBarController"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/TabBarController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"TabBarController"}],"url":"\/documentation\/yababa\/tabbarcontroller"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"tabBar:didSelectItem:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"tabBar:didSelectItem:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"tabBar:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UITabBar","preciseIdentifier":"c:objc(cs)UITabBar"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"tabBar"},{"kind":"text","text":" "},{"kind":"identifier","text":"didSelectItem:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UITabBarItem","preciseIdentifier":"c:objc(cs)UITabBarItem"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"item"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1TabBarController~1tabBar(_:didSelect:)\/title","value":"tabBar:didSelectItem:"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1TabBarController~1tabBar(_:didSelect:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"tabBar:didSelectItem:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1TabBarController\/title","value":"TabBarController"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1TabBarController\/fragments","value":[{"kind":"identifier","text":"TabBarController"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}