{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"configure"},{"kind":"text","text":"("},{"kind":"externalParam","text":"prefilledEmail"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/yababa\/forgotpasswordscenebuilder\/configure(prefilledemail:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/yababa\/forgotpasswordscenebuilder\/configure(prefilledemail:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ForgotPasswordSceneBuilder\/configure(prefilledEmail:)","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"configure"},{"kind":"text","text":"("},{"kind":"externalParam","text":"prefilledEmail"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"}],"title":"configure(prefilledEmail:)","roleHeading":"Type Method","role":"symbol","symbolKind":"method","externalID":"c:@M@Yababa@objc(cs)ForgotPasswordSceneBuilder(cm)configureWithPrefilledEmail:","modules":[{"name":"Yababa"}],"navigatorTitle":[{"kind":"identifier","text":"configureWithPrefilledEmail:"}]},"hierarchy":{"paths":[["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ForgotPasswordSceneBuilder"]]},"references":{"doc://com.yababaGmbH.yababa/documentation/Yababa/ForgotPasswordSceneBuilder":{"role":"symbol","title":"ForgotPasswordSceneBuilder","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ForgotPasswordSceneBuilder"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ForgotPasswordSceneBuilder","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ForgotPasswordSceneBuilder"}],"url":"\/documentation\/yababa\/forgotpasswordscenebuilder"},"doc://com.yababaGmbH.yababa/documentation/Yababa/ForgotPasswordSceneBuilder/configure(prefilledEmail:)":{"role":"symbol","title":"configure(prefilledEmail:)","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"configure"},{"kind":"text","text":"("},{"kind":"externalParam","text":"prefilledEmail"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ForgotPasswordSceneBuilder\/configure(prefilledEmail:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"configureWithPrefilledEmail:"}],"url":"\/documentation\/yababa\/forgotpasswordscenebuilder\/configure(prefilledemail:)"},"doc://com.yababaGmbH.yababa/documentation/Yababa":{"role":"collection","title":"Yababa","abstract":[{"type":"text","text":"Getting Started"}],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa","kind":"symbol","type":"topic","url":"\/documentation\/yababa"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Method"},{"op":"replace","path":"\/metadata\/title","value":"configureWithPrefilledEmail:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"configureWithPrefilledEmail:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"+ ("},{"kind":"typeIdentifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"configureWithPrefilledEmail:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"prefilledEmail"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1ForgotPasswordSceneBuilder\/title","value":"ForgotPasswordSceneBuilder"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1ForgotPasswordSceneBuilder\/fragments","value":[{"kind":"identifier","text":"ForgotPasswordSceneBuilder"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1ForgotPasswordSceneBuilder~1configure(prefilledEmail:)\/title","value":"configureWithPrefilledEmail:"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1ForgotPasswordSceneBuilder~1configure(prefilledEmail:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"configureWithPrefilledEmail:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}