{"primaryContentSections":[{"kind":"content","content":[{"anchor":"Overview","level":2,"type":"heading","text":"Overview"},{"type":"paragraph","inlineContent":[{"type":"text","text":"asjdhasjkdhjas jsad"}]},{"anchor":"Core-Components","level":2,"type":"heading","text":"Core Components"},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"reference","isActive":true,"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/StoreManager"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"reference","isActive":true,"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ShoppingCartManager"}]}]}]},{"anchor":"Views","level":2,"type":"heading","text":"Views"},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"reference","isActive":true,"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/HomeView"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"reference","isActive":true,"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/Catalogue"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"doc:Search"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"doc:ProductDetails"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"doc:ShoppingCartView"}]}]}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/yababa\/-shoppingoverview"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/yababa\/-shoppingoverview"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/-ShoppingOverview","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"One Shopping"}],"kind":"article","metadata":{"roleHeading":"Article","title":"Shopping experience","role":"article","modules":[{"name":"Yababa"}]},"hierarchy":{"paths":[["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa"]]},"seeAlsoSections":[{"title":"Shopping","identifiers":["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/StoreManager","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ShoppingCartManager"],"generated":true}],"references":{"doc://com.yababaGmbH.yababa/documentation/Yababa/HomeView":{"role":"collectionGroup","title":"Home Screen","abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/HomeView","kind":"article","type":"topic","url":"\/documentation\/yababa\/homeview"},"doc://com.yababaGmbH.yababa/documentation/Yababa/Catalogue":{"role":"symbol","title":"Catalogue","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"Catalogue"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/Catalogue","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Catalogue"}],"url":"\/documentation\/yababa\/catalogue"},"doc://com.yababaGmbH.yababa/documentation/Yababa":{"role":"collection","title":"Yababa","abstract":[{"type":"text","text":"Getting Started"}],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa","kind":"symbol","type":"topic","url":"\/documentation\/yababa"},"doc://com.yababaGmbH.yababa/documentation/Yababa/StoreManager":{"role":"article","title":"Store Manager","abstract":[{"type":"text","text":"Core component of the app, responsible for fetching the latest catalogue from server and maintaining it locally on the device."}],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/StoreManager","kind":"article","type":"topic","url":"\/documentation\/yababa\/storemanager"},"doc://com.yababaGmbH.yababa/documentation/Yababa/ShoppingCartManager":{"role":"article","title":"Shopping Cart","abstract":[{"type":"text","text":"Core component of the app, responsible for managing products in the shopping cart."}],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ShoppingCartManager","kind":"article","type":"topic","url":"\/documentation\/yababa\/shoppingcartmanager"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/topicSections","value":null},{"op":"replace","path":"\/seeAlsoSections","value":[{"title":"Shopping","identifiers":["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/StoreManager","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ShoppingCartManager"],"generated":true}]}],"traits":[{"interfaceLanguage":"occ"}]}]}