{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AddAddressDetailsViewController"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/yababa\/addaddressdetailsviewcontroller"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/yababa\/addaddressdetailsviewcontroller"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.yababaGmbH.yababa\/objc(cs)UIViewController"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.yababaGmbH.yababa\/objc(pl)NSCoding","doc:\/\/com.yababaGmbH.yababa\/objc(pl)NSExtensionRequestHandling","doc:\/\/com.yababaGmbH.yababa\/objc(pl)NSObject","doc:\/\/com.yababaGmbH.yababa\/12SkeletonView17AssociatedObjectsP","doc:\/\/com.yababaGmbH.yababa\/s7CVarArgP","doc:\/\/com.yababaGmbH.yababa\/s28CustomDebugStringConvertibleP","doc:\/\/com.yababaGmbH.yababa\/s23CustomStringConvertibleP","doc:\/\/com.yababaGmbH.yababa\/SQ","doc:\/\/com.yababaGmbH.yababa\/SH","doc:\/\/com.yababaGmbH.yababa\/s8SendableP","doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIActivityItemsConfigurationProviding","doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIAppearanceContainer","doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIContentContainer","doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIFocusEnvironment","doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIPasteConfigurationSupporting","doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIResponderStandardEditActions","doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIStateRestoring","doc:\/\/com.yababaGmbH.yababa\/objc(pl)UITraitEnvironment","doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIUserActivityRestoring"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AddAddressDetailsViewController","interfaceLanguage":"swift"},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AddAddressDetailsViewController\/init(address:delegate:)","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AddAddressDetailsViewController\/init(coder:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AddAddressDetailsViewController\/additionalInfoLabel","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AddAddressDetailsViewController\/additionalInfoTextField","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AddAddressDetailsViewController\/addressLabel","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AddAddressDetailsViewController\/addressTextField","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AddAddressDetailsViewController\/cancelBtn","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AddAddressDetailsViewController\/postalCodeLabel","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AddAddressDetailsViewController\/postalCodeTextField","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AddAddressDetailsViewController\/submitBtn"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AddAddressDetailsViewController\/onCancel()","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AddAddressDetailsViewController\/onSubmit()","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AddAddressDetailsViewController\/setIdentifiers()","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AddAddressDetailsViewController\/setLocalizationStrings()","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AddAddressDetailsViewController\/setupUI()","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AddAddressDetailsViewController\/viewDidLoad()"]}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AddAddressDetailsViewController"}],"title":"AddAddressDetailsViewController","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@Yababa@objc(cs)AddAddressDetailsViewController","modules":[{"name":"Yababa"}],"navigatorTitle":[{"kind":"identifier","text":"AddAddressDetailsViewController"}]},"hierarchy":{"paths":[["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa"]]},"references":{"doc://com.yababaGmbH.yababa/documentation/Yababa/AddAddressDetailsViewController/init(address:delegate:)":{"role":"symbol","title":"init(address:delegate:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"address"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Address","preciseIdentifier":"s:6Yababa7AddressC"},{"kind":"text","text":", "},{"kind":"externalParam","text":"delegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AddAddressDetailsDelegate","preciseIdentifier":"s:6Yababa25AddAddressDetailsDelegateP"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AddAddressDetailsViewController\/init(address:delegate:)","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/addaddressdetailsviewcontroller\/init(address:delegate:)"},"doc://com.yababaGmbH.yababa/documentation/Yababa/AddAddressDetailsViewController/onSubmit()":{"role":"symbol","title":"onSubmit()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onSubmit"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AddAddressDetailsViewController\/onSubmit()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"onSubmit"}],"url":"\/documentation\/yababa\/addaddressdetailsviewcontroller\/onsubmit()"},"doc://com.yababaGmbH.yababa/objc(cs)UIViewController":{"type":"unresolvable","title":"UIViewController","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(cs)UIViewController"},"doc://com.yababaGmbH.yababa/objc(pl)NSCoding":{"type":"unresolvable","title":"Foundation.NSCoding","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)NSCoding"},"doc://com.yababaGmbH.yababa/documentation/Yababa/AddAddressDetailsViewController/setIdentifiers()":{"role":"symbol","title":"setIdentifiers()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setIdentifiers"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AddAddressDetailsViewController\/setIdentifiers()","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/addaddressdetailsviewcontroller\/setidentifiers()"},"doc://com.yababaGmbH.yababa/documentation/Yababa/AddAddressDetailsViewController/cancelBtn":{"role":"symbol","title":"cancelBtn","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"cancelBtn"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIButton","preciseIdentifier":"c:objc(cs)UIButton"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AddAddressDetailsViewController\/cancelBtn","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"cancelBtn"}],"url":"\/documentation\/yababa\/addaddressdetailsviewcontroller\/cancelbtn"},"doc://com.yababaGmbH.yababa/12SkeletonView17AssociatedObjectsP":{"type":"unresolvable","title":"SkeletonView.AssociatedObjects","identifier":"doc:\/\/com.yababaGmbH.yababa\/12SkeletonView17AssociatedObjectsP"},"doc://com.yababaGmbH.yababa/documentation/Yababa/AddAddressDetailsViewController/additionalInfoLabel":{"role":"symbol","title":"additionalInfoLabel","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"additionalInfoLabel"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UILabel","preciseIdentifier":"c:objc(cs)UILabel"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AddAddressDetailsViewController\/additionalInfoLabel","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"additionalInfoLabel"}],"url":"\/documentation\/yababa\/addaddressdetailsviewcontroller\/additionalinfolabel"},"doc://com.yababaGmbH.yababa/documentation/Yababa/AddAddressDetailsViewController/postalCodeTextField":{"role":"symbol","title":"postalCodeTextField","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"postalCodeTextField"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UITextField","preciseIdentifier":"c:objc(cs)UITextField"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AddAddressDetailsViewController\/postalCodeTextField","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"postalCodeTextField"}],"url":"\/documentation\/yababa\/addaddressdetailsviewcontroller\/postalcodetextfield"},"doc://com.yababaGmbH.yababa/documentation/Yababa/AddAddressDetailsViewController/viewDidLoad()":{"role":"symbol","title":"viewDidLoad()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"viewDidLoad"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AddAddressDetailsViewController\/viewDidLoad()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"viewDidLoad"}],"url":"\/documentation\/yababa\/addaddressdetailsviewcontroller\/viewdidload()"},"doc://com.yababaGmbH.yababa/objc(pl)UIStateRestoring":{"type":"unresolvable","title":"UIKit.UIStateRestoring","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIStateRestoring"},"doc://com.yababaGmbH.yababa/objc(pl)UIAppearanceContainer":{"type":"unresolvable","title":"UIKit.UIAppearanceContainer","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIAppearanceContainer"},"doc://com.yababaGmbH.yababa/objc(pl)UIResponderStandardEditActions":{"type":"unresolvable","title":"UIKit.UIResponderStandardEditActions","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIResponderStandardEditActions"},"doc://com.yababaGmbH.yababa/objc(pl)UIUserActivityRestoring":{"type":"unresolvable","title":"UIKit.UIUserActivityRestoring","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIUserActivityRestoring"},"doc://com.yababaGmbH.yababa/documentation/Yababa/AddAddressDetailsViewController/addressLabel":{"role":"symbol","title":"addressLabel","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"addressLabel"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UILabel","preciseIdentifier":"c:objc(cs)UILabel"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AddAddressDetailsViewController\/addressLabel","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"addressLabel"}],"url":"\/documentation\/yababa\/addaddressdetailsviewcontroller\/addresslabel"},"doc://com.yababaGmbH.yababa/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.yababaGmbH.yababa\/SH"},"doc://com.yababaGmbH.yababa/objc(pl)UIContentContainer":{"type":"unresolvable","title":"UIKit.UIContentContainer","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIContentContainer"},"doc://com.yababaGmbH.yababa/documentation/Yababa/AddAddressDetailsViewController/postalCodeLabel":{"role":"symbol","title":"postalCodeLabel","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"postalCodeLabel"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UILabel","preciseIdentifier":"c:objc(cs)UILabel"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AddAddressDetailsViewController\/postalCodeLabel","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"postalCodeLabel"}],"url":"\/documentation\/yababa\/addaddressdetailsviewcontroller\/postalcodelabel"},"doc://com.yababaGmbH.yababa/objc(pl)UIFocusEnvironment":{"type":"unresolvable","title":"UIKit.UIFocusEnvironment","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIFocusEnvironment"},"doc://com.yababaGmbH.yababa/documentation/Yababa/AddAddressDetailsViewController":{"role":"symbol","title":"AddAddressDetailsViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AddAddressDetailsViewController"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AddAddressDetailsViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AddAddressDetailsViewController"}],"url":"\/documentation\/yababa\/addaddressdetailsviewcontroller"},"doc://com.yababaGmbH.yababa/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.yababaGmbH.yababa\/SQ"},"doc://com.yababaGmbH.yababa/documentation/Yababa/AddAddressDetailsViewController/setupUI()":{"role":"symbol","title":"setupUI()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setupUI"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AddAddressDetailsViewController\/setupUI()","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/addaddressdetailsviewcontroller\/setupui()"},"doc://com.yababaGmbH.yababa/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.yababaGmbH.yababa\/s28CustomDebugStringConvertibleP"},"doc://com.yababaGmbH.yababa/documentation/Yababa/AddAddressDetailsViewController/onCancel()":{"role":"symbol","title":"onCancel()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onCancel"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AddAddressDetailsViewController\/onCancel()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"onCancel"}],"url":"\/documentation\/yababa\/addaddressdetailsviewcontroller\/oncancel()"},"doc://com.yababaGmbH.yababa/documentation/Yababa/AddAddressDetailsViewController/init(coder:)":{"role":"symbol","title":"init(coder:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"coder"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSCoder","preciseIdentifier":"c:objc(cs)NSCoder"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AddAddressDetailsViewController\/init(coder:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithCoder:"}],"url":"\/documentation\/yababa\/addaddressdetailsviewcontroller\/init(coder:)"},"doc://com.yababaGmbH.yababa/objc(pl)UITraitEnvironment":{"type":"unresolvable","title":"UIKit.UITraitEnvironment","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)UITraitEnvironment"},"doc://com.yababaGmbH.yababa/objc(pl)NSExtensionRequestHandling":{"type":"unresolvable","title":"Foundation.NSExtensionRequestHandling","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)NSExtensionRequestHandling"},"doc://com.yababaGmbH.yababa/documentation/Yababa/AddAddressDetailsViewController/additionalInfoTextField":{"role":"symbol","title":"additionalInfoTextField","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"additionalInfoTextField"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UITextField","preciseIdentifier":"c:objc(cs)UITextField"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AddAddressDetailsViewController\/additionalInfoTextField","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"additionalInfoTextField"}],"url":"\/documentation\/yababa\/addaddressdetailsviewcontroller\/additionalinfotextfield"},"doc://com.yababaGmbH.yababa/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/com.yababaGmbH.yababa\/s8SendableP"},"doc://com.yababaGmbH.yababa/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.yababaGmbH.yababa\/s23CustomStringConvertibleP"},"doc://com.yababaGmbH.yababa/documentation/Yababa/AddAddressDetailsViewController/addressTextField":{"role":"symbol","title":"addressTextField","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"addressTextField"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UITextField","preciseIdentifier":"c:objc(cs)UITextField"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AddAddressDetailsViewController\/addressTextField","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"addressTextField"}],"url":"\/documentation\/yababa\/addaddressdetailsviewcontroller\/addresstextfield"},"doc://com.yababaGmbH.yababa/documentation/Yababa/AddAddressDetailsViewController/submitBtn":{"role":"symbol","title":"submitBtn","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"submitBtn"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIButton","preciseIdentifier":"c:objc(cs)UIButton"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AddAddressDetailsViewController\/submitBtn","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"submitBtn"}],"url":"\/documentation\/yababa\/addaddressdetailsviewcontroller\/submitbtn"},"doc://com.yababaGmbH.yababa/objc(pl)UIActivityItemsConfigurationProviding":{"type":"unresolvable","title":"UIKit.UIActivityItemsConfigurationProviding","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIActivityItemsConfigurationProviding"},"doc://com.yababaGmbH.yababa/objc(pl)UIPasteConfigurationSupporting":{"type":"unresolvable","title":"UIKit.UIPasteConfigurationSupporting","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIPasteConfigurationSupporting"},"doc://com.yababaGmbH.yababa/documentation/Yababa":{"role":"collection","title":"Yababa","abstract":[{"type":"text","text":"Getting Started"}],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa","kind":"symbol","type":"topic","url":"\/documentation\/yababa"},"doc://com.yababaGmbH.yababa/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.yababaGmbH.yababa\/s7CVarArgP"},"doc://com.yababaGmbH.yababa/documentation/Yababa/AddAddressDetailsViewController/setLocalizationStrings()":{"role":"symbol","title":"setLocalizationStrings()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setLocalizationStrings"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AddAddressDetailsViewController\/setLocalizationStrings()","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/addaddressdetailsviewcontroller\/setlocalizationstrings()"},"doc://com.yababaGmbH.yababa/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)NSObject"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"AddAddressDetailsViewController"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AddAddressDetailsViewController"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"AddAddressDetailsViewController"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AddAddressDetailsViewController\/additionalInfoLabel","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AddAddressDetailsViewController\/additionalInfoTextField","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AddAddressDetailsViewController\/addressLabel","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AddAddressDetailsViewController\/addressTextField","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AddAddressDetailsViewController\/cancelBtn","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AddAddressDetailsViewController\/postalCodeLabel","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AddAddressDetailsViewController\/postalCodeTextField","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AddAddressDetailsViewController\/submitBtn"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AddAddressDetailsViewController\/init(coder:)","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AddAddressDetailsViewController\/onCancel()","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AddAddressDetailsViewController\/onSubmit()","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AddAddressDetailsViewController\/viewDidLoad()"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.yababaGmbH.yababa\/objc(cs)UIViewController"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"AddAddressDetailsViewController"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1AddAddressDetailsViewController~1onSubmit()\/title","value":"onSubmit"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1AddAddressDetailsViewController~1onSubmit()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onSubmit"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1AddAddressDetailsViewController~1cancelBtn\/title","value":"cancelBtn"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1AddAddressDetailsViewController~1cancelBtn\/fragments","value":[{"kind":"identifier","text":"cancelBtn"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1AddAddressDetailsViewController~1additionalInfoLabel\/title","value":"additionalInfoLabel"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1AddAddressDetailsViewController~1additionalInfoLabel\/fragments","value":[{"kind":"identifier","text":"additionalInfoLabel"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1AddAddressDetailsViewController~1postalCodeTextField\/title","value":"postalCodeTextField"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1AddAddressDetailsViewController~1postalCodeTextField\/fragments","value":[{"kind":"identifier","text":"postalCodeTextField"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1AddAddressDetailsViewController~1viewDidLoad()\/title","value":"viewDidLoad"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1AddAddressDetailsViewController~1viewDidLoad()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"viewDidLoad"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1AddAddressDetailsViewController~1addressLabel\/title","value":"addressLabel"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1AddAddressDetailsViewController~1addressLabel\/fragments","value":[{"kind":"identifier","text":"addressLabel"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1AddAddressDetailsViewController~1postalCodeLabel\/title","value":"postalCodeLabel"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1AddAddressDetailsViewController~1postalCodeLabel\/fragments","value":[{"kind":"identifier","text":"postalCodeLabel"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1AddAddressDetailsViewController\/title","value":"AddAddressDetailsViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1AddAddressDetailsViewController\/fragments","value":[{"kind":"identifier","text":"AddAddressDetailsViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1AddAddressDetailsViewController~1onCancel()\/title","value":"onCancel"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1AddAddressDetailsViewController~1onCancel()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onCancel"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1AddAddressDetailsViewController~1init(coder:)\/title","value":"initWithCoder:"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1AddAddressDetailsViewController~1init(coder:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithCoder:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1AddAddressDetailsViewController~1additionalInfoTextField\/title","value":"additionalInfoTextField"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1AddAddressDetailsViewController~1additionalInfoTextField\/fragments","value":[{"kind":"identifier","text":"additionalInfoTextField"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1AddAddressDetailsViewController~1addressTextField\/title","value":"addressTextField"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1AddAddressDetailsViewController~1addressTextField\/fragments","value":[{"kind":"identifier","text":"addressTextField"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1AddAddressDetailsViewController~1submitBtn\/title","value":"submitBtn"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1AddAddressDetailsViewController~1submitBtn\/fragments","value":[{"kind":"identifier","text":"submitBtn"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}