{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AddCouponPopup"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/yababa\/addcouponpopup"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/yababa\/addcouponpopup"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.yababaGmbH.yababa\/objc(cs)UIViewController"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.yababaGmbH.yababa\/objc(pl)NSCoding","doc:\/\/com.yababaGmbH.yababa\/objc(pl)NSExtensionRequestHandling","doc:\/\/com.yababaGmbH.yababa\/objc(pl)NSObject","doc:\/\/com.yababaGmbH.yababa\/12SkeletonView17AssociatedObjectsP","doc:\/\/com.yababaGmbH.yababa\/s7CVarArgP","doc:\/\/com.yababaGmbH.yababa\/s28CustomDebugStringConvertibleP","doc:\/\/com.yababaGmbH.yababa\/s23CustomStringConvertibleP","doc:\/\/com.yababaGmbH.yababa\/SQ","doc:\/\/com.yababaGmbH.yababa\/SH","doc:\/\/com.yababaGmbH.yababa\/s8SendableP","doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIActivityItemsConfigurationProviding","doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIAppearanceContainer","doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIContentContainer","doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIFocusEnvironment","doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIPasteConfigurationSupporting","doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIResponderStandardEditActions","doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIStateRestoring","doc:\/\/com.yababaGmbH.yababa\/objc(pl)UITraitEnvironment","doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIUserActivityRestoring"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AddCouponPopup","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AddCouponPopup\/closeButton","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AddCouponPopup\/codeTextField","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AddCouponPopup\/onDismiss","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AddCouponPopup\/origin","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AddCouponPopup\/popupView","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AddCouponPopup\/popupViewBottomConstraint","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AddCouponPopup\/popupViewCenterConstraint","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AddCouponPopup\/submitButton","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AddCouponPopup\/titleLabel"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AddCouponPopup\/dismissSelf()","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AddCouponPopup\/keyboardWillHide(_:)","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AddCouponPopup\/keyboardWillShow(_:)","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AddCouponPopup\/popupViewTapped()","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AddCouponPopup\/setIdentifiers()","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AddCouponPopup\/setup(origin:onDismiss:)","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AddCouponPopup\/showError(_:)","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AddCouponPopup\/submit(_:)","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AddCouponPopup\/viewDidLoad()","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AddCouponPopup\/viewWillAppear(_:)"]}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AddCouponPopup"}],"title":"AddCouponPopup","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@Yababa@objc(cs)AddCouponPopup","modules":[{"name":"Yababa"}],"navigatorTitle":[{"kind":"identifier","text":"AddCouponPopup"}]},"hierarchy":{"paths":[["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa"]]},"references":{"doc://com.yababaGmbH.yababa/objc(pl)UITraitEnvironment":{"type":"unresolvable","title":"UIKit.UITraitEnvironment","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)UITraitEnvironment"},"doc://com.yababaGmbH.yababa/12SkeletonView17AssociatedObjectsP":{"type":"unresolvable","title":"SkeletonView.AssociatedObjects","identifier":"doc:\/\/com.yababaGmbH.yababa\/12SkeletonView17AssociatedObjectsP"},"doc://com.yababaGmbH.yababa/objc(pl)UIPasteConfigurationSupporting":{"type":"unresolvable","title":"UIKit.UIPasteConfigurationSupporting","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIPasteConfigurationSupporting"},"doc://com.yababaGmbH.yababa/documentation/Yababa/AddCouponPopup/titleLabel":{"role":"symbol","title":"titleLabel","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"titleLabel"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UILabel","preciseIdentifier":"c:objc(cs)UILabel"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AddCouponPopup\/titleLabel","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"titleLabel"}],"url":"\/documentation\/yababa\/addcouponpopup\/titlelabel"},"doc://com.yababaGmbH.yababa/documentation/Yababa/AddCouponPopup/closeButton":{"role":"symbol","title":"closeButton","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"closeButton"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIButton","preciseIdentifier":"c:objc(cs)UIButton"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AddCouponPopup\/closeButton","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"closeButton"}],"url":"\/documentation\/yababa\/addcouponpopup\/closebutton"},"doc://com.yababaGmbH.yababa/documentation/Yababa/AddCouponPopup/onDismiss":{"role":"symbol","title":"onDismiss","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"onDismiss"},{"kind":"text","text":": (() -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")?"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AddCouponPopup\/onDismiss","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/addcouponpopup\/ondismiss"},"doc://com.yababaGmbH.yababa/documentation/Yababa":{"role":"collection","title":"Yababa","abstract":[{"type":"text","text":"Getting Started"}],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa","kind":"symbol","type":"topic","url":"\/documentation\/yababa"},"doc://com.yababaGmbH.yababa/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.yababaGmbH.yababa\/SQ"},"doc://com.yababaGmbH.yababa/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.yababaGmbH.yababa\/s23CustomStringConvertibleP"},"doc://com.yababaGmbH.yababa/documentation/Yababa/AddCouponPopup/submit(_:)":{"role":"symbol","title":"submit(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"submit"},{"kind":"text","text":"("},{"kind":"keyword","text":"Any"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AddCouponPopup\/submit(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"submit:"}],"url":"\/documentation\/yababa\/addcouponpopup\/submit(_:)"},"doc://com.yababaGmbH.yababa/objc(pl)UIResponderStandardEditActions":{"type":"unresolvable","title":"UIKit.UIResponderStandardEditActions","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIResponderStandardEditActions"},"doc://com.yababaGmbH.yababa/objc(pl)UIAppearanceContainer":{"type":"unresolvable","title":"UIKit.UIAppearanceContainer","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIAppearanceContainer"},"doc://com.yababaGmbH.yababa/documentation/Yababa/AddCouponPopup/origin":{"role":"symbol","title":"origin","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"origin"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TrackingOrigin","preciseIdentifier":"s:6Yababa14TrackingOriginO"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AddCouponPopup\/origin","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/addcouponpopup\/origin"},"doc://com.yababaGmbH.yababa/documentation/Yababa/AddCouponPopup/submitButton":{"role":"symbol","title":"submitButton","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"submitButton"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIButton","preciseIdentifier":"c:objc(cs)UIButton"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AddCouponPopup\/submitButton","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"submitButton"}],"url":"\/documentation\/yababa\/addcouponpopup\/submitbutton"},"doc://com.yababaGmbH.yababa/documentation/Yababa/AddCouponPopup/viewWillAppear(_:)":{"role":"symbol","title":"viewWillAppear(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"viewWillAppear"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AddCouponPopup\/viewWillAppear(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"viewWillAppear:"}],"url":"\/documentation\/yababa\/addcouponpopup\/viewwillappear(_:)"},"doc://com.yababaGmbH.yababa/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.yababaGmbH.yababa\/s28CustomDebugStringConvertibleP"},"doc://com.yababaGmbH.yababa/documentation/Yababa/AddCouponPopup/viewDidLoad()":{"role":"symbol","title":"viewDidLoad()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"viewDidLoad"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AddCouponPopup\/viewDidLoad()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"viewDidLoad"}],"url":"\/documentation\/yababa\/addcouponpopup\/viewdidload()"},"doc://com.yababaGmbH.yababa/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.yababaGmbH.yababa\/SH"},"doc://com.yababaGmbH.yababa/documentation/Yababa/AddCouponPopup":{"role":"symbol","title":"AddCouponPopup","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AddCouponPopup"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AddCouponPopup","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AddCouponPopup"}],"url":"\/documentation\/yababa\/addcouponpopup"},"doc://com.yababaGmbH.yababa/documentation/Yababa/AddCouponPopup/initWithCoder:":{"role":"symbol","title":"initWithCoder:","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithCoder:"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AddCouponPopup\/initWithCoder:","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithCoder:"}],"url":"\/documentation\/yababa\/addcouponpopup\/initwithcoder:"},"doc://com.yababaGmbH.yababa/objc(cs)UIViewController":{"type":"unresolvable","title":"UIViewController","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(cs)UIViewController"},"doc://com.yababaGmbH.yababa/documentation/Yababa/AddCouponPopup/codeTextField":{"role":"symbol","title":"codeTextField","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"codeTextField"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UITextField","preciseIdentifier":"c:objc(cs)UITextField"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AddCouponPopup\/codeTextField","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"codeTextField"}],"url":"\/documentation\/yababa\/addcouponpopup\/codetextfield"},"doc://com.yababaGmbH.yababa/documentation/Yababa/AddCouponPopup/popupView":{"role":"symbol","title":"popupView","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"popupView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AddCouponPopup\/popupView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"popupView"}],"url":"\/documentation\/yababa\/addcouponpopup\/popupview"},"doc://com.yababaGmbH.yababa/documentation/Yababa/AddCouponPopup/popupViewCenterConstraint":{"role":"symbol","title":"popupViewCenterConstraint","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"popupViewCenterConstraint"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSLayoutConstraint","preciseIdentifier":"c:objc(cs)NSLayoutConstraint"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AddCouponPopup\/popupViewCenterConstraint","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"popupViewCenterConstraint"}],"url":"\/documentation\/yababa\/addcouponpopup\/popupviewcenterconstraint"},"doc://com.yababaGmbH.yababa/objc(pl)UIContentContainer":{"type":"unresolvable","title":"UIKit.UIContentContainer","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIContentContainer"},"doc://com.yababaGmbH.yababa/documentation/Yababa/AddCouponPopup/showError(_:)":{"role":"symbol","title":"showError(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"showError"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AddCouponPopup\/showError(_:)","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/addcouponpopup\/showerror(_:)"},"doc://com.yababaGmbH.yababa/documentation/Yababa/AddCouponPopup/dismissSelf()":{"role":"symbol","title":"dismissSelf()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"dismissSelf"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AddCouponPopup\/dismissSelf()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"dismissSelf"}],"url":"\/documentation\/yababa\/addcouponpopup\/dismissself()"},"doc://com.yababaGmbH.yababa/documentation/Yababa/AddCouponPopup/keyboardWillShow(_:)":{"role":"symbol","title":"keyboardWillShow(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"keyboardWillShow"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Notification","preciseIdentifier":"s:10Foundation12NotificationV"},{"kind":"text","text":"!)"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AddCouponPopup\/keyboardWillShow(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"keyboardWillShow:"}],"url":"\/documentation\/yababa\/addcouponpopup\/keyboardwillshow(_:)"},"doc://com.yababaGmbH.yababa/documentation/Yababa/AddCouponPopup/popupViewTapped()":{"role":"symbol","title":"popupViewTapped()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"popupViewTapped"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AddCouponPopup\/popupViewTapped()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"popupViewTapped"}],"url":"\/documentation\/yababa\/addcouponpopup\/popupviewtapped()"},"doc://com.yababaGmbH.yababa/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)NSObject"},"doc://com.yababaGmbH.yababa/objc(pl)UIActivityItemsConfigurationProviding":{"type":"unresolvable","title":"UIKit.UIActivityItemsConfigurationProviding","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIActivityItemsConfigurationProviding"},"doc://com.yababaGmbH.yababa/objc(pl)NSExtensionRequestHandling":{"type":"unresolvable","title":"Foundation.NSExtensionRequestHandling","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)NSExtensionRequestHandling"},"doc://com.yababaGmbH.yababa/documentation/Yababa/AddCouponPopup/setup(origin:onDismiss:)":{"role":"symbol","title":"setup(origin:onDismiss:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setup"},{"kind":"text","text":"("},{"kind":"externalParam","text":"origin"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TrackingOrigin","preciseIdentifier":"s:6Yababa14TrackingOriginO"},{"kind":"text","text":", "},{"kind":"externalParam","text":"onDismiss"},{"kind":"text","text":": () -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AddCouponPopup\/setup(origin:onDismiss:)","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/addcouponpopup\/setup(origin:ondismiss:)"},"doc://com.yababaGmbH.yababa/documentation/Yababa/AddCouponPopup/keyboardWillHide(_:)":{"role":"symbol","title":"keyboardWillHide(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"keyboardWillHide"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Notification","preciseIdentifier":"s:10Foundation12NotificationV"},{"kind":"text","text":"!)"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AddCouponPopup\/keyboardWillHide(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"keyboardWillHide:"}],"url":"\/documentation\/yababa\/addcouponpopup\/keyboardwillhide(_:)"},"doc://com.yababaGmbH.yababa/objc(pl)UIFocusEnvironment":{"type":"unresolvable","title":"UIKit.UIFocusEnvironment","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIFocusEnvironment"},"doc://com.yababaGmbH.yababa/objc(pl)NSCoding":{"type":"unresolvable","title":"Foundation.NSCoding","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)NSCoding"},"doc://com.yababaGmbH.yababa/documentation/Yababa/AddCouponPopup/popupViewBottomConstraint":{"role":"symbol","title":"popupViewBottomConstraint","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"popupViewBottomConstraint"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSLayoutConstraint","preciseIdentifier":"c:objc(cs)NSLayoutConstraint"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AddCouponPopup\/popupViewBottomConstraint","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"popupViewBottomConstraint"}],"url":"\/documentation\/yababa\/addcouponpopup\/popupviewbottomconstraint"},"doc://com.yababaGmbH.yababa/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.yababaGmbH.yababa\/s7CVarArgP"},"doc://com.yababaGmbH.yababa/documentation/Yababa/AddCouponPopup/initWithNibName:bundle:":{"role":"symbol","title":"initWithNibName:bundle:","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithNibName:bundle:"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AddCouponPopup\/initWithNibName:bundle:","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithNibName:bundle:"}],"url":"\/documentation\/yababa\/addcouponpopup\/initwithnibname:bundle:"},"doc://com.yababaGmbH.yababa/objc(pl)UIStateRestoring":{"type":"unresolvable","title":"UIKit.UIStateRestoring","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIStateRestoring"},"doc://com.yababaGmbH.yababa/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/com.yababaGmbH.yababa\/s8SendableP"},"doc://com.yababaGmbH.yababa/documentation/Yababa/AddCouponPopup/setIdentifiers()":{"role":"symbol","title":"setIdentifiers()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setIdentifiers"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AddCouponPopup\/setIdentifiers()","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/addcouponpopup\/setidentifiers()"},"doc://com.yababaGmbH.yababa/objc(pl)UIUserActivityRestoring":{"type":"unresolvable","title":"UIKit.UIUserActivityRestoring","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIUserActivityRestoring"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"AddCouponPopup"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AddCouponPopup"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"AddCouponPopup"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AddCouponPopup\/closeButton","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AddCouponPopup\/codeTextField","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AddCouponPopup\/popupView","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AddCouponPopup\/popupViewBottomConstraint","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AddCouponPopup\/popupViewCenterConstraint","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AddCouponPopup\/submitButton","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AddCouponPopup\/titleLabel"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AddCouponPopup\/dismissSelf()","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AddCouponPopup\/initWithCoder:","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AddCouponPopup\/initWithNibName:bundle:","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AddCouponPopup\/keyboardWillHide(_:)","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AddCouponPopup\/keyboardWillShow(_:)","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AddCouponPopup\/popupViewTapped()","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AddCouponPopup\/submit(_:)","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AddCouponPopup\/viewDidLoad()","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AddCouponPopup\/viewWillAppear(_:)"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.yababaGmbH.yababa\/objc(cs)UIViewController"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"AddCouponPopup"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1AddCouponPopup~1titleLabel\/title","value":"titleLabel"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1AddCouponPopup~1titleLabel\/fragments","value":[{"kind":"identifier","text":"titleLabel"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1AddCouponPopup~1closeButton\/title","value":"closeButton"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1AddCouponPopup~1closeButton\/fragments","value":[{"kind":"identifier","text":"closeButton"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1AddCouponPopup~1submit(_:)\/title","value":"submit:"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1AddCouponPopup~1submit(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"submit:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1AddCouponPopup~1submitButton\/title","value":"submitButton"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1AddCouponPopup~1submitButton\/fragments","value":[{"kind":"identifier","text":"submitButton"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1AddCouponPopup~1viewWillAppear(_:)\/title","value":"viewWillAppear:"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1AddCouponPopup~1viewWillAppear(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"viewWillAppear:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1AddCouponPopup~1viewDidLoad()\/title","value":"viewDidLoad"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1AddCouponPopup~1viewDidLoad()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"viewDidLoad"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1AddCouponPopup\/title","value":"AddCouponPopup"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1AddCouponPopup\/fragments","value":[{"kind":"identifier","text":"AddCouponPopup"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1AddCouponPopup~1codeTextField\/title","value":"codeTextField"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1AddCouponPopup~1codeTextField\/fragments","value":[{"kind":"identifier","text":"codeTextField"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1AddCouponPopup~1popupView\/title","value":"popupView"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1AddCouponPopup~1popupView\/fragments","value":[{"kind":"identifier","text":"popupView"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1AddCouponPopup~1popupViewCenterConstraint\/title","value":"popupViewCenterConstraint"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1AddCouponPopup~1popupViewCenterConstraint\/fragments","value":[{"kind":"identifier","text":"popupViewCenterConstraint"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1AddCouponPopup~1dismissSelf()\/title","value":"dismissSelf"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1AddCouponPopup~1dismissSelf()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"dismissSelf"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1AddCouponPopup~1keyboardWillShow(_:)\/title","value":"keyboardWillShow:"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1AddCouponPopup~1keyboardWillShow(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"keyboardWillShow:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1AddCouponPopup~1popupViewTapped()\/title","value":"popupViewTapped"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1AddCouponPopup~1popupViewTapped()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"popupViewTapped"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1AddCouponPopup~1keyboardWillHide(_:)\/title","value":"keyboardWillHide:"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1AddCouponPopup~1keyboardWillHide(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"keyboardWillHide:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1AddCouponPopup~1popupViewBottomConstraint\/title","value":"popupViewBottomConstraint"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1AddCouponPopup~1popupViewBottomConstraint\/fragments","value":[{"kind":"identifier","text":"popupViewBottomConstraint"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}