{"primaryContentSections":[{"kind":"content","content":[{"anchor":"Overview","level":2,"type":"heading","text":"Overview"},{"type":"paragraph","inlineContent":[{"type":"text","text":"The purpose of this module is to manage user’s delivery addresses, allow user to add new address and view existing ones."},{"type":"text","text":" "},{"type":"text","text":"The module is made up of three primary classes. The "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AddressManager"},{"type":"text","text":", "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AddressManagerInteractor"},{"type":"text","text":" and "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AddressManagerViewNavigator"},{"type":"text","text":"."}]},{"type":"paragraph","inlineContent":[{"type":"image","identifier":"AddressMangement.png"}]},{"anchor":"AddressManager","level":4,"type":"heading","text":"AddressManager"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Serves as the core component, acting as a mediator between the other two classes. It is the front-facing component that allows other classes and views to communicate with it to retrieve and save addresses. AddressManager holds a strong reference to both AddressManagerInteractor and AddressManagerViewNavigator."}]},{"anchor":"AddressManagerInteractor","level":4,"type":"heading","text":"AddressManagerInteractor"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Communicates with the backend to retrieve and save addresses. It holds weak reference to the AddressManager."}]},{"anchor":"AddressManagerViewNavigator","level":4,"type":"heading","text":"AddressManagerViewNavigator"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Requires a parent view (a view conforming to AddressManagerOwner protocol e.g. Home Screen) to be initiated. It creates address-related screens and gives it to parent view controller to launch them, such as "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/MapsViewController"},{"type":"text","text":" and "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AddressSelectionListSceneViewController"},{"type":"text","text":". It holds a weak reference to these classes, so it is notified when MapsViewController is done with selecting coordinates and when AddressSelectionListSceneViewController is done with selecting an address. Additionally, AddressManagerViewNavigator communicates with "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/INLocationManager"},{"type":"text","text":" to fetch the reverse geocoded information from coordinates."}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"It also holds a weak reference to the parent view so it can launch the screens for it."},{"type":"text","text":" "},{"type":"text","text":"Also holds weak reference to the AddressManager"}]},{"anchor":"Understanding-Warehouses-and-Storefronts","level":2,"type":"heading","text":"Understanding Warehouses and Storefronts"},{"anchor":"Warehouse","level":4,"type":"heading","text":"Warehouse"},{"type":"paragraph","inlineContent":[{"type":"text","text":"A warehouse is a physical location where inventory is stored and distributed from. For Yababa, the primary warehouse is located in Berlin."}]},{"anchor":"Storefront","level":4,"type":"heading","text":"Storefront"},{"type":"paragraph","inlineContent":[{"type":"text","text":"At Yababa, a storefront is a virtual area defined by a set of postal codes. Each storefront is linked to a parent warehouse, which means that a warehouse can have multiple storefronts."}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"For instance, the “Cologne” warehouse could have two storefronts: “Cologne East” with postal codes 100, 101, and 102, and “Cologne West” with postal codes 200, 201, and 202."}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"The purpose of having storefronts is to apply different rules to different areas even though they are served from the same warehouse. Each storefront can have:"}]},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Different time slots and cut-off times"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Different minimum order values (MOV) and delivery fees"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Different stock items served. For instance, meat may be served in Berlin central city storefronts, but not for storefronts in Berlin outskirts."}]}]}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"By having storefronts, Yababa can tailor its services to the needs of various areas while optimizing its inventory management and distribution processes."}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/yababa\/addressmanagerdocumentation"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/yababa\/addressmanagerdocumentation"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AddressManagerDocumentation","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Manages user delivery addresses. Allows user to add new address and validate existing ones"}],"kind":"article","metadata":{"roleHeading":"Article","title":"Address Managing Module","role":"article","modules":[{"name":"Yababa"}]},"hierarchy":{"paths":[["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa"]]},"seeAlsoSections":[{"title":"User Access","identifiers":["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/User-Login","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/UserStateManager","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/PushNotificationsDocumentation"],"generated":true}],"references":{"doc://com.yababaGmbH.yababa/documentation/Yababa/INLocationManager":{"role":"symbol","title":"INLocationManager","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"INLocationManager"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/INLocationManager","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"INLocationManager"}],"url":"\/documentation\/yababa\/inlocationmanager"},"doc://com.yababaGmbH.yababa/documentation/Yababa/MapsViewController":{"role":"symbol","title":"MapsViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MapsViewController"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/MapsViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MapsViewController"}],"url":"\/documentation\/yababa\/mapsviewcontroller"},"doc://com.yababaGmbH.yababa/documentation/Yababa/AddressManager":{"role":"symbol","title":"AddressManager","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AddressManager"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AddressManager","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AddressManager"}],"url":"\/documentation\/yababa\/addressmanager"},"doc://com.yababaGmbH.yababa/documentation/Yababa":{"role":"collection","title":"Yababa","abstract":[{"type":"text","text":"Getting Started"}],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa","kind":"symbol","type":"topic","url":"\/documentation\/yababa"},"doc://com.yababaGmbH.yababa/documentation/Yababa/UserStateManager":{"role":"symbol","title":"UserStateManager","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"UserStateManager"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"LocalUserStateManager","preciseIdentifier":"c:@M@Yababa@objc(cs)LocalUserStateManager"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/UserStateManager","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/userstatemanager"},"AddressMangement.png":{"alt":"AddressMangement","type":"image","identifier":"AddressMangement.png","variants":[{"url":"\/images\/AddressMangement@2x.png","traits":["2x","light"]}]},"doc://com.yababaGmbH.yababa/documentation/Yababa/AddressManagerViewNavigator":{"role":"symbol","title":"AddressManagerViewNavigator","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AddressManagerViewNavigator"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AddressManagerViewNavigator","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AddressManagerViewNavigator"}],"url":"\/documentation\/yababa\/addressmanagerviewnavigator"},"doc://com.yababaGmbH.yababa/documentation/Yababa/AddressManagerInteractor":{"role":"symbol","title":"AddressManagerInteractor","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AddressManagerInteractor"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AddressManagerInteractor","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AddressManagerInteractor"}],"url":"\/documentation\/yababa\/addressmanagerinteractor"},"doc://com.yababaGmbH.yababa/documentation/Yababa/PushNotificationsDocumentation":{"role":"collectionGroup","title":"Push Notifications Manager","abstract":[{"type":"text","text":"Requesting permission for Push Notifications and receiving them"}],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/PushNotificationsDocumentation","kind":"article","type":"topic","url":"\/documentation\/yababa\/pushnotificationsdocumentation"},"doc://com.yababaGmbH.yababa/documentation/Yababa/AddressSelectionListSceneViewController":{"role":"symbol","title":"AddressSelectionListSceneViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AddressSelectionListSceneViewController"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AddressSelectionListSceneViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AddressSelectionListSceneViewController"}],"url":"\/documentation\/yababa\/addressselectionlistsceneviewcontroller"},"doc://com.yababaGmbH.yababa/documentation/Yababa/User-Login":{"role":"article","title":"User Login","abstract":[{"type":"text","text":"Covers user login and signup journey through Email and Social login methods"}],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/User-Login","kind":"article","type":"topic","url":"\/documentation\/yababa\/user-login"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/topicSections","value":null},{"op":"replace","path":"\/seeAlsoSections","value":[{"title":"User Access","identifiers":["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/User-Login","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/PushNotificationsDocumentation"],"generated":true}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1INLocationManager\/title","value":"INLocationManager"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1INLocationManager\/fragments","value":[{"kind":"identifier","text":"INLocationManager"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1MapsViewController\/title","value":"MapsViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1MapsViewController\/fragments","value":[{"kind":"identifier","text":"MapsViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1AddressManager\/title","value":"AddressManager"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1AddressManager\/fragments","value":[{"kind":"identifier","text":"AddressManager"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1AddressManagerViewNavigator\/title","value":"AddressManagerViewNavigator"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1AddressManagerViewNavigator\/fragments","value":[{"kind":"identifier","text":"AddressManagerViewNavigator"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1AddressSelectionListSceneViewController\/title","value":"AddressSelectionListSceneViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1AddressSelectionListSceneViewController\/fragments","value":[{"kind":"identifier","text":"AddressSelectionListSceneViewController"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}