{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AddressManager"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/yababa\/addressmanager"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/yababa\/addressmanager"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.yababaGmbH.yababa\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AddressManagerDelegate","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AddressSelectionDelegate","doc:\/\/com.yababaGmbH.yababa\/objc(pl)NSObject","doc:\/\/com.yababaGmbH.yababa\/12SkeletonView17AssociatedObjectsP","doc:\/\/com.yababaGmbH.yababa\/s7CVarArgP","doc:\/\/com.yababaGmbH.yababa\/s28CustomDebugStringConvertibleP","doc:\/\/com.yababaGmbH.yababa\/s23CustomStringConvertibleP","doc:\/\/com.yababaGmbH.yababa\/SQ","doc:\/\/com.yababaGmbH.yababa\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AddressManager","interfaceLanguage":"swift"},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AddressManager\/init(interactor:addressSelectionDelegate:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AddressManager\/addressSelectionNavigator","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AddressManager\/forViewingList","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AddressManager\/interactor"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AddressManager\/checkUserAddresses(_:)","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AddressManager\/initiate()","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AddressManager\/initiateAndShowUserAddresses()","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AddressManager\/processAddressValidationResponse(_:)","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AddressManager\/refreshAddresses()","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AddressManager\/saveAddress(_:)","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AddressManager\/showInvalidAddress(addressValidationResponse:)","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AddressManager\/showUserAddresses(_:)"]},{"title":"Default Implementations","identifiers":["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AddressManager\/AddressSelectionDelegate-Implementations"],"generated":true}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AddressManager"}],"title":"AddressManager","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@Yababa@objc(cs)AddressManager","modules":[{"name":"Yababa"}],"navigatorTitle":[{"kind":"identifier","text":"AddressManager"}]},"hierarchy":{"paths":[["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa"]]},"references":{"doc://com.yababaGmbH.yababa/12SkeletonView17AssociatedObjectsP":{"type":"unresolvable","title":"SkeletonView.AssociatedObjects","identifier":"doc:\/\/com.yababaGmbH.yababa\/12SkeletonView17AssociatedObjectsP"},"doc://com.yababaGmbH.yababa/documentation/Yababa/AddressManager/refreshAddresses()":{"role":"symbol","title":"refreshAddresses()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"refreshAddresses"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AddressManager\/refreshAddresses()","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/addressmanager\/refreshaddresses()"},"doc://com.yababaGmbH.yababa/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.yababaGmbH.yababa\/s28CustomDebugStringConvertibleP"},"doc://com.yababaGmbH.yababa/documentation/Yababa/AddressSelectionDelegate":{"role":"symbol","title":"AddressSelectionDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"AddressSelectionDelegate"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AddressSelectionDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AddressSelectionDelegate"}],"url":"\/documentation\/yababa\/addressselectiondelegate"},"doc://com.yababaGmbH.yababa/documentation/Yababa":{"role":"collection","title":"Yababa","abstract":[{"type":"text","text":"Getting Started"}],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa","kind":"symbol","type":"topic","url":"\/documentation\/yababa"},"doc://com.yababaGmbH.yababa/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.yababaGmbH.yababa\/s23CustomStringConvertibleP"},"doc://com.yababaGmbH.yababa/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.yababaGmbH.yababa\/SH"},"doc://com.yababaGmbH.yababa/documentation/Yababa/AddressManager/initiate()":{"role":"symbol","title":"initiate()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"initiate"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AddressManager\/initiate()","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/addressmanager\/initiate()"},"doc://com.yababaGmbH.yababa/documentation/Yababa/AddressManager/forViewingList":{"role":"symbol","title":"forViewingList","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"forViewingList"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AddressManager\/forViewingList","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/addressmanager\/forviewinglist"},"doc://com.yababaGmbH.yababa/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.yababaGmbH.yababa\/SQ"},"doc://com.yababaGmbH.yababa/documentation/Yababa/AddressManagerDelegate":{"role":"symbol","title":"AddressManagerDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"AddressManagerDelegate"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AddressManagerDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AddressManagerDelegate"}],"url":"\/documentation\/yababa\/addressmanagerdelegate"},"doc://com.yababaGmbH.yababa/documentation/Yababa/AddressManager/interactor":{"role":"symbol","title":"interactor","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"interactor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AddressManagerInteractorProtocol","preciseIdentifier":"s:6Yababa32AddressManagerInteractorProtocolP"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AddressManager\/interactor","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/addressmanager\/interactor"},"doc://com.yababaGmbH.yababa/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(cs)NSObject"},"doc://com.yababaGmbH.yababa/documentation/Yababa/AddressManager/showUserAddresses(_:)":{"role":"symbol","title":"showUserAddresses(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"showUserAddresses"},{"kind":"text","text":"(["},{"kind":"typeIdentifier","text":"Address","preciseIdentifier":"s:6Yababa7AddressC"},{"kind":"text","text":"])"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AddressManager\/showUserAddresses(_:)","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/addressmanager\/showuseraddresses(_:)"},"doc://com.yababaGmbH.yababa/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.yababaGmbH.yababa\/s7CVarArgP"},"doc://com.yababaGmbH.yababa/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)NSObject"},"doc://com.yababaGmbH.yababa/documentation/Yababa/AddressManager/addressSelectionNavigator":{"role":"symbol","title":"addressSelectionNavigator","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"addressSelectionNavigator"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AddressSelectionManager","preciseIdentifier":"s:6Yababa23AddressSelectionManagerP"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AddressManager\/addressSelectionNavigator","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/addressmanager\/addressselectionnavigator"},"doc://com.yababaGmbH.yababa/documentation/Yababa/AddressManager/checkUserAddresses(_:)":{"role":"symbol","title":"checkUserAddresses(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"checkUserAddresses"},{"kind":"text","text":"(["},{"kind":"typeIdentifier","text":"Address","preciseIdentifier":"s:6Yababa7AddressC"},{"kind":"text","text":"])"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AddressManager\/checkUserAddresses(_:)","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/addressmanager\/checkuseraddresses(_:)"},"doc://com.yababaGmbH.yababa/documentation/Yababa/AddressManager/initiateAndShowUserAddresses()":{"role":"symbol","title":"initiateAndShowUserAddresses()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"initiateAndShowUserAddresses"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AddressManager\/initiateAndShowUserAddresses()","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/addressmanager\/initiateandshowuseraddresses()"},"doc://com.yababaGmbH.yababa/documentation/Yababa/AddressManager/AddressSelectionDelegate-Implementations":{"role":"collectionGroup","title":"AddressSelectionDelegate Implementations","abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AddressManager\/AddressSelectionDelegate-Implementations","kind":"article","type":"topic","url":"\/documentation\/yababa\/addressmanager\/addressselectiondelegate-implementations"},"doc://com.yababaGmbH.yababa/documentation/Yababa/AddressManager/init(interactor:addressSelectionDelegate:)":{"role":"symbol","title":"init(interactor:addressSelectionDelegate:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"interactor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AddressManagerInteractorProtocol","preciseIdentifier":"s:6Yababa32AddressManagerInteractorProtocolP"},{"kind":"text","text":", "},{"kind":"externalParam","text":"addressSelectionDelegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AddressSelectionManager","preciseIdentifier":"s:6Yababa23AddressSelectionManagerP"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AddressManager\/init(interactor:addressSelectionDelegate:)","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/addressmanager\/init(interactor:addressselectiondelegate:)"},"doc://com.yababaGmbH.yababa/documentation/Yababa/AddressManager/showInvalidAddress(addressValidationResponse:)":{"role":"symbol","title":"showInvalidAddress(addressValidationResponse:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"showInvalidAddress"},{"kind":"text","text":"("},{"kind":"externalParam","text":"addressValidationResponse"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AddressValidationResponse","preciseIdentifier":"s:6Yababa25AddressValidationResponseC"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AddressManager\/showInvalidAddress(addressValidationResponse:)","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/addressmanager\/showinvalidaddress(addressvalidationresponse:)"},"doc://com.yababaGmbH.yababa/documentation/Yababa/AddressManager/saveAddress(_:)":{"role":"symbol","title":"saveAddress(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"saveAddress"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Address","preciseIdentifier":"s:6Yababa7AddressC"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AddressManager\/saveAddress(_:)","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/addressmanager\/saveaddress(_:)"},"doc://com.yababaGmbH.yababa/documentation/Yababa/AddressManager/processAddressValidationResponse(_:)":{"role":"symbol","title":"processAddressValidationResponse(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"processAddressValidationResponse"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Result","preciseIdentifier":"s:s6ResultO"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"AddressValidationResponse","preciseIdentifier":"s:6Yababa25AddressValidationResponseC"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":">)"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AddressManager\/processAddressValidationResponse(_:)","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/addressmanager\/processaddressvalidationresponse(_:)"},"doc://com.yababaGmbH.yababa/documentation/Yababa/AddressManager":{"role":"symbol","title":"AddressManager","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AddressManager"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AddressManager","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AddressManager"}],"url":"\/documentation\/yababa\/addressmanager"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"AddressManager"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AddressManager"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"AddressManager"}]},{"op":"replace","path":"\/topicSections","value":null},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.yababaGmbH.yababa\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"AddressManager"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1AddressManager\/title","value":"AddressManager"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1AddressManager\/fragments","value":[{"kind":"identifier","text":"AddressManager"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}