{"primaryContentSections":[{"kind":"content","content":[{"anchor":"Overview","level":2,"type":"heading","text":"Overview"},{"type":"paragraph","inlineContent":[{"type":"reference","isActive":true,"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AnalyticsTracker"},{"type":"text","text":" is a managing class responsible to forwarding events to other third party analytics platforms such as Segment, Mixpanel, Firebase Analytics, Appsflyer and Braze for further analysis."}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"Note:"}]},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"A refactor of AnalyticsTracker was done where the tracking events were split into several small classes. But the task for replacing the method calls for the newer classes was parked aside."}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Segment was the primary tool which AnalyticsTracker sent events to. It forwarded the events to Mixpanel and Firebase. Later it was removed with AnalyticsTracker sending events directly to Mixpanel."}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Production app sends events to the Production environment of Mixpanel. While testing app sends to the Sandbox environment of Mixpanel, regardless whatever server was chosen to run the app with. (Testflght app with Live server will send events to Mixpanel Sandbox). See "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AppSchemes"}]}]}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"There are few more tools used, but these arent managed by AnalyticsTracker. These are mentioned below."}]},{"anchor":"Screen-Capture","level":3,"type":"heading","text":"Screen Capture"},{"type":"paragraph","inlineContent":[{"type":"reference","isActive":true,"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/UXCamUtils"}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"UXCam - Captures screens, behavioral events, issues and gestures"}]},{"anchor":"Error-Tracking","level":3,"type":"heading","text":"Error Tracking"},{"type":"paragraph","inlineContent":[{"type":"reference","isActive":true,"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ErrorTracker"},{"type":"text","text":" - Main class for tracking errors and forwarding to other third party tools"}]},{"type":"paragraph","inlineContent":[{"type":"reference","isActive":true,"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/SentryManager"},{"type":"text","text":" - The primary error tracking tool used for Yababa"}]},{"anchor":"References","level":3,"type":"heading","text":"References"},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"reference","isActive":true,"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/SegmentAnalytics"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"reference","isActive":true,"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/MixpanelAnalytics"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"reference","isActive":true,"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/BrazeManager"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"reference","isActive":true,"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AppsFlyerManager"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"reference","isActive":true,"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/FirebaseManager"}]}]}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/yababa\/analyticsdocumentation"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/yababa\/analyticsdocumentation"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AnalyticsDocumentation","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Responsible for collecting events about user behavior and forwarding to third party analytics platforms."}],"kind":"article","metadata":{"roleHeading":"Article","title":"Analytics Manager","role":"article","modules":[{"name":"Yababa"}]},"hierarchy":{"paths":[["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa"]]},"seeAlsoSections":[{"title":"Others","identifiers":["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/NetworkLayer","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/InAppMessages"],"generated":true}],"references":{"doc://com.yababaGmbH.yababa/documentation/Yababa/ErrorTracker":{"role":"symbol","title":"ErrorTracker","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ErrorTracker"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ErrorTracker","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ErrorTracker"}],"url":"\/documentation\/yababa\/errortracker"},"doc://com.yababaGmbH.yababa/documentation/Yababa/MixpanelAnalytics":{"role":"symbol","title":"MixpanelAnalytics","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MixpanelAnalytics"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/MixpanelAnalytics","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MixpanelAnalytics"}],"url":"\/documentation\/yababa\/mixpanelanalytics"},"doc://com.yababaGmbH.yababa/documentation/Yababa/UXCamUtils":{"role":"symbol","title":"UXCamUtils","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"UXCamUtils"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/UXCamUtils","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"UXCamUtils"}],"url":"\/documentation\/yababa\/uxcamutils"},"doc://com.yababaGmbH.yababa/documentation/Yababa/InAppMessages":{"role":"article","title":"InApp Messages","abstract":[{"type":"text","text":"Pop-up messages that appear within the app to provide users with information, promotions, and other relevant content."}],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/InAppMessages","kind":"article","type":"topic","url":"\/documentation\/yababa\/inappmessages"},"doc://com.yababaGmbH.yababa/documentation/Yababa/BrazeManager":{"role":"symbol","title":"BrazeManager","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"BrazeManager"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/BrazeManager","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"BrazeManager"}],"url":"\/documentation\/yababa\/brazemanager"},"doc://com.yababaGmbH.yababa/documentation/Yababa/SentryManager":{"role":"symbol","title":"SentryManager","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SentryManager"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/SentryManager","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SentryManager"}],"url":"\/documentation\/yababa\/sentrymanager"},"doc://com.yababaGmbH.yababa/documentation/Yababa/AppSchemes":{"role":"article","title":"App Schemes","abstract":[{"type":"text","text":"Compile builds for different environments (Development \/ Testflight \/ AppStore)"}],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AppSchemes","kind":"article","type":"topic","url":"\/documentation\/yababa\/appschemes"},"doc://com.yababaGmbH.yababa/documentation/Yababa/NetworkLayer":{"role":"article","title":"Network Layer","abstract":[{"type":"text","text":"Responsible for managing the communication between the app and backend server"}],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/NetworkLayer","kind":"article","type":"topic","url":"\/documentation\/yababa\/networklayer"},"doc://com.yababaGmbH.yababa/documentation/Yababa/AppsFlyerManager":{"role":"symbol","title":"AppsFlyerManager","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AppsFlyerManager"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AppsFlyerManager","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AppsFlyerManager"}],"url":"\/documentation\/yababa\/appsflyermanager"},"doc://com.yababaGmbH.yababa/documentation/Yababa/FirebaseManager":{"role":"symbol","title":"FirebaseManager","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FirebaseManager"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/FirebaseManager","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FirebaseManager"}],"url":"\/documentation\/yababa\/firebasemanager"},"doc://com.yababaGmbH.yababa/documentation/Yababa/AnalyticsTracker":{"role":"symbol","title":"AnalyticsTracker","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AnalyticsTracker"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AnalyticsTracker","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AnalyticsTracker"}],"url":"\/documentation\/yababa\/analyticstracker"},"doc://com.yababaGmbH.yababa/documentation/Yababa/SegmentAnalytics":{"role":"symbol","title":"SegmentAnalytics","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SegmentAnalytics"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/SegmentAnalytics","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SegmentAnalytics"}],"url":"\/documentation\/yababa\/segmentanalytics"},"doc://com.yababaGmbH.yababa/documentation/Yababa":{"role":"collection","title":"Yababa","abstract":[{"type":"text","text":"Getting Started"}],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa","kind":"symbol","type":"topic","url":"\/documentation\/yababa"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/topicSections","value":null},{"op":"replace","path":"\/seeAlsoSections","value":[{"title":"Others","identifiers":["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/NetworkLayer","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/InAppMessages"],"generated":true}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1ErrorTracker\/title","value":"ErrorTracker"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1ErrorTracker\/fragments","value":[{"kind":"identifier","text":"ErrorTracker"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1UXCamUtils\/title","value":"UXCamUtils"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1UXCamUtils\/fragments","value":[{"kind":"identifier","text":"UXCamUtils"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1BrazeManager\/title","value":"BrazeManager"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1BrazeManager\/fragments","value":[{"kind":"identifier","text":"BrazeManager"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1AppsFlyerManager\/title","value":"AppsFlyerManager"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1AppsFlyerManager\/fragments","value":[{"kind":"identifier","text":"AppsFlyerManager"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1FirebaseManager\/title","value":"FirebaseManager"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1FirebaseManager\/fragments","value":[{"kind":"identifier","text":"FirebaseManager"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1AnalyticsTracker\/title","value":"AnalyticsTracker"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1AnalyticsTracker\/fragments","value":[{"kind":"identifier","text":"AnalyticsTracker"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}