{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AppleLogin"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/yababa\/applelogin"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/yababa\/applelogin"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.yababaGmbH.yababa\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.yababaGmbH.yababa\/objc(pl)ASAuthorizationControllerDelegate","doc:\/\/com.yababaGmbH.yababa\/objc(pl)ASAuthorizationControllerPresentationContextProviding","doc:\/\/com.yababaGmbH.yababa\/objc(pl)NSObject","doc:\/\/com.yababaGmbH.yababa\/12SkeletonView17AssociatedObjectsP","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/SocialLogin","doc:\/\/com.yababaGmbH.yababa\/s7CVarArgP","doc:\/\/com.yababaGmbH.yababa\/s28CustomDebugStringConvertibleP","doc:\/\/com.yababaGmbH.yababa\/s23CustomStringConvertibleP","doc:\/\/com.yababaGmbH.yababa\/SQ","doc:\/\/com.yababaGmbH.yababa\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AppleLogin","interfaceLanguage":"swift"},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AppleLogin\/init(delegate:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AppleLogin\/delegate"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AppleLogin\/loginToIN2Server(fullName:token:userId:)","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AppleLogin\/onSocialLogin()","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AppleLogin\/trackAnalytics()"]},{"title":"Default Implementations","identifiers":["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AppleLogin\/ASAuthorizationControllerDelegate-Implementations","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AppleLogin\/ASAuthorizationControllerPresentationContextProviding-Implementations"],"generated":true}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AppleLogin"}],"title":"AppleLogin","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@Yababa@objc(cs)AppleLogin","modules":[{"name":"Yababa"}],"navigatorTitle":[{"kind":"identifier","text":"AppleLogin"}]},"hierarchy":{"paths":[["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa"]]},"references":{"doc://com.yababaGmbH.yababa/documentation/Yababa/AppleLogin/delegate":{"role":"symbol","title":"delegate","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"delegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SocialLoginResponseDelegate","preciseIdentifier":"s:6Yababa27SocialLoginResponseDelegateP"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AppleLogin\/delegate","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/applelogin\/delegate"},"doc://com.yababaGmbH.yababa/objc(pl)ASAuthorizationControllerDelegate":{"type":"unresolvable","title":"AuthenticationServices.ASAuthorizationControllerDelegate","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)ASAuthorizationControllerDelegate"},"doc://com.yababaGmbH.yababa/documentation/Yababa":{"role":"collection","title":"Yababa","abstract":[{"type":"text","text":"Getting Started"}],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa","kind":"symbol","type":"topic","url":"\/documentation\/yababa"},"doc://com.yababaGmbH.yababa/objc(pl)ASAuthorizationControllerPresentationContextProviding":{"type":"unresolvable","title":"AuthenticationServices.ASAuthorizationControllerPresentationContextProviding","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)ASAuthorizationControllerPresentationContextProviding"},"doc://com.yababaGmbH.yababa/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(cs)NSObject"},"doc://com.yababaGmbH.yababa/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.yababaGmbH.yababa\/s23CustomStringConvertibleP"},"doc://com.yababaGmbH.yababa/documentation/Yababa/AppleLogin":{"role":"symbol","title":"AppleLogin","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AppleLogin"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AppleLogin","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AppleLogin"}],"url":"\/documentation\/yababa\/applelogin"},"doc://com.yababaGmbH.yababa/12SkeletonView17AssociatedObjectsP":{"type":"unresolvable","title":"SkeletonView.AssociatedObjects","identifier":"doc:\/\/com.yababaGmbH.yababa\/12SkeletonView17AssociatedObjectsP"},"doc://com.yababaGmbH.yababa/documentation/Yababa/AppleLogin/ASAuthorizationControllerPresentationContextProviding-Implementations":{"role":"collectionGroup","title":"ASAuthorizationControllerPresentationContextProviding Implementations","abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AppleLogin\/ASAuthorizationControllerPresentationContextProviding-Implementations","kind":"article","type":"topic","url":"\/documentation\/yababa\/applelogin\/asauthorizationcontrollerpresentationcontextproviding-implementations"},"doc://com.yababaGmbH.yababa/documentation/Yababa/AppleLogin/onSocialLogin()":{"role":"symbol","title":"onSocialLogin()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onSocialLogin"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AppleLogin\/onSocialLogin()","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/applelogin\/onsociallogin()"},"doc://com.yababaGmbH.yababa/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)NSObject"},"doc://com.yababaGmbH.yababa/documentation/Yababa/AppleLogin/init(delegate:)":{"role":"symbol","title":"init(delegate:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"delegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SocialLoginResponseDelegate","preciseIdentifier":"s:6Yababa27SocialLoginResponseDelegateP"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AppleLogin\/init(delegate:)","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/applelogin\/init(delegate:)"},"doc://com.yababaGmbH.yababa/documentation/Yababa/AppleLogin/trackAnalytics()":{"role":"symbol","title":"trackAnalytics()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"trackAnalytics"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AppleLogin\/trackAnalytics()","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/applelogin\/trackanalytics()"},"doc://com.yababaGmbH.yababa/documentation/Yababa/SocialLogin":{"role":"symbol","title":"SocialLogin","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SocialLogin"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/SocialLogin","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SocialLogin"}],"url":"\/documentation\/yababa\/sociallogin"},"doc://com.yababaGmbH.yababa/documentation/Yababa/AppleLogin/loginToIN2Server(fullName:token:userId:)":{"role":"symbol","title":"loginToIN2Server(fullName:token:userId:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"loginToIN2Server"},{"kind":"text","text":"("},{"kind":"externalParam","text":"fullName"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"token"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"userId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?)"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AppleLogin\/loginToIN2Server(fullName:token:userId:)","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/applelogin\/logintoin2server(fullname:token:userid:)"},"doc://com.yababaGmbH.yababa/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.yababaGmbH.yababa\/SH"},"doc://com.yababaGmbH.yababa/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.yababaGmbH.yababa\/s7CVarArgP"},"doc://com.yababaGmbH.yababa/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.yababaGmbH.yababa\/SQ"},"doc://com.yababaGmbH.yababa/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.yababaGmbH.yababa\/s28CustomDebugStringConvertibleP"},"doc://com.yababaGmbH.yababa/documentation/Yababa/AppleLogin/ASAuthorizationControllerDelegate-Implementations":{"role":"collectionGroup","title":"ASAuthorizationControllerDelegate Implementations","abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AppleLogin\/ASAuthorizationControllerDelegate-Implementations","kind":"article","type":"topic","url":"\/documentation\/yababa\/applelogin\/asauthorizationcontrollerdelegate-implementations"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"AppleLogin"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AppleLogin"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"AppleLogin"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Default Implementations","identifiers":["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AppleLogin\/ASAuthorizationControllerDelegate-Implementations","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AppleLogin\/ASAuthorizationControllerPresentationContextProviding-Implementations"],"generated":true}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.yababaGmbH.yababa\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"AppleLogin"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1AppleLogin\/title","value":"AppleLogin"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1AppleLogin\/fragments","value":[{"kind":"identifier","text":"AppleLogin"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}