{"primaryContentSections":[{"kind":"content","content":[{"anchor":"Overview","level":2,"type":"heading","text":"Overview"},{"type":"paragraph","inlineContent":[{"type":"text","text":"The configuration properties for the app are stored in the Info.plist. It contains:"}]},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"URLs for server selection"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"API version of Backend to request to"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"API keys of third party frameworks and libraries"},{"type":"text","text":" "},{"type":"text","text":"(example Facebook, Mixpanel, Braze, Sentry etc)"}]}]}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"To access the properties of Info.plist from the code, the class "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AppInfo"},{"type":"text","text":" has been written. It helps by providing a wrapper  to access required properties of given frameworks. Example Mixpanel properties can be access via the subclass "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AppInfo\/Mixpanel"},{"type":"text","text":"."}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/yababa\/appproperties"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/yababa\/appproperties"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AppProperties","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Configuring properties for the app and third party frameworks"}],"kind":"article","metadata":{"roleHeading":"Article","title":"App Properties","role":"article","modules":[{"name":"Yababa"}]},"hierarchy":{"paths":[["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa"]]},"seeAlsoSections":[{"title":"App Configuration","identifiers":["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AppSchemes"],"generated":true}],"references":{"doc://com.yababaGmbH.yababa/documentation/Yababa":{"role":"collection","title":"Yababa","abstract":[{"type":"text","text":"Getting Started"}],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa","kind":"symbol","type":"topic","url":"\/documentation\/yababa"},"doc://com.yababaGmbH.yababa/documentation/Yababa/AppInfo/Mixpanel":{"role":"symbol","title":"AppInfo.Mixpanel","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Mixpanel"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AppInfo\/Mixpanel","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Mixpanel"}],"url":"\/documentation\/yababa\/appinfo\/mixpanel"},"doc://com.yababaGmbH.yababa/documentation/Yababa/AppSchemes":{"role":"article","title":"App Schemes","abstract":[{"type":"text","text":"Compile builds for different environments (Development \/ Testflight \/ AppStore)"}],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AppSchemes","kind":"article","type":"topic","url":"\/documentation\/yababa\/appschemes"},"doc://com.yababaGmbH.yababa/documentation/Yababa/AppInfo":{"role":"symbol","title":"AppInfo","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AppInfo"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AppInfo","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AppInfo"}],"url":"\/documentation\/yababa\/appinfo"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/topicSections","value":null},{"op":"replace","path":"\/seeAlsoSections","value":[{"title":"App Configuration","identifiers":["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AppSchemes"],"generated":true}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1AppInfo\/title","value":"AppInfo"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1AppInfo\/fragments","value":[{"kind":"identifier","text":"AppInfo"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}