{"primaryContentSections":[{"kind":"content","content":[{"anchor":"Overview","level":2,"type":"heading","text":"Overview"},{"type":"paragraph","inlineContent":[{"type":"text","text":"The app has only one Target. But has two different schemes available, each serving a specific purpose. The Schemes are configured through build configurations (Development\/Release) which use flags defined in the User-Defined settings of the app (Settings -> Target -> Build Settings -> “User-Defined” -> “IS_TEST_BUILD” flag)."}]},{"type":"paragraph","inlineContent":[{"type":"image","identifier":"AppConfig.png"}]},{"anchor":"Yababa-Scheme","level":4,"type":"heading","text":"Yababa Scheme"},{"type":"paragraph","inlineContent":[{"type":"text","text":"The “Yababa” scheme is used to compile the app for production purposes, which is intended for release on app stores. It does not allow the option for server selection."}]},{"anchor":"YababaTest-Scheme","level":4,"type":"heading","text":"YababaTest Scheme"},{"type":"paragraph","inlineContent":[{"type":"text","text":"The “YababaTest” scheme is for testing purposes. It enables users to select the server they wish to connect to, such as the Sandbox environment. The server selection option is presented on the welcome screen. The advantage of this implementation is that one build can be compiled for development\/Testflight. We can choose desired server and compare the feature on different environments."}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"For compiling Testflight builds or testing on devices, the “YababaTest” scheme is particularly useful. For production releases,  only the “Yababa” scheme should be used."}]},{"style":"note","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Bitrise, our CI\/CD tool, is already configured with these options."}]}],"type":"aside","name":"Note"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/yababa\/appschemes"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/yababa\/appschemes"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AppSchemes","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Compile builds for different environments (Development \/ Testflight \/ AppStore)"}],"kind":"article","metadata":{"roleHeading":"Article","title":"App Schemes","role":"article","modules":[{"name":"Yababa"}]},"hierarchy":{"paths":[["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa"]]},"seeAlsoSections":[{"title":"App Configuration","identifiers":["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AppProperties"],"generated":true}],"references":{"AppConfig.png":{"alt":"Configs","type":"image","identifier":"AppConfig.png","variants":[{"url":"\/images\/AppConfig@2x.png","traits":["2x","light"]}]},"doc://com.yababaGmbH.yababa/documentation/Yababa/AppProperties":{"role":"article","title":"App Properties","abstract":[{"type":"text","text":"Configuring properties for the app and third party frameworks"}],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AppProperties","kind":"article","type":"topic","url":"\/documentation\/yababa\/appproperties"},"doc://com.yababaGmbH.yababa/documentation/Yababa":{"role":"collection","title":"Yababa","abstract":[{"type":"text","text":"Getting Started"}],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa","kind":"symbol","type":"topic","url":"\/documentation\/yababa"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/topicSections","value":null},{"op":"replace","path":"\/seeAlsoSections","value":[{"title":"App Configuration","identifiers":["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AppProperties"],"generated":true}]}],"traits":[{"interfaceLanguage":"occ"}]}]}