{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"BrazeManager"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/yababa\/brazemanager"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/yababa\/brazemanager"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.yababaGmbH.yababa\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.yababaGmbH.yababa\/objc(pl)ABKInAppMessageControllerDelegate","doc:\/\/com.yababaGmbH.yababa\/objc(pl)ABKInAppMessageUIDelegate","doc:\/\/com.yababaGmbH.yababa\/objc(pl)NSObject","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/PushNotificationMarketingManager","doc:\/\/com.yababaGmbH.yababa\/12SkeletonView17AssociatedObjectsP","doc:\/\/com.yababaGmbH.yababa\/s7CVarArgP","doc:\/\/com.yababaGmbH.yababa\/s28CustomDebugStringConvertibleP","doc:\/\/com.yababaGmbH.yababa\/s23CustomStringConvertibleP","doc:\/\/com.yababaGmbH.yababa\/SQ","doc:\/\/com.yababaGmbH.yababa\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/BrazeManager","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/BrazeManager\/configure(_:didFinishLaunchingWithOptions:)","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/BrazeManager\/configureInAppMessaging()","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/BrazeManager\/displayNextInAppMessage()","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/BrazeManager\/registerDeviceToken(_:)","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/BrazeManager\/setLoggedInUser(changeUser:)","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/BrazeManager\/setUserEmailSubscription(status:)","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/BrazeManager\/setUserPushStatus(_:)","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/BrazeManager\/updateAddress()"]},{"title":"Type Properties","identifiers":["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/BrazeManager\/sharedInstance"]},{"title":"Default Implementations","identifiers":["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/BrazeManager\/ABKInAppMessageUIDelegate-Implementations","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/BrazeManager\/PushNotificationMarketingManager-Implementations"],"generated":true}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"BrazeManager"}],"title":"BrazeManager","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@Yababa@objc(cs)BrazeManager","modules":[{"name":"Yababa"}],"navigatorTitle":[{"kind":"identifier","text":"BrazeManager"}]},"hierarchy":{"paths":[["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa"]]},"references":{"doc://com.yababaGmbH.yababa/documentation/Yababa/BrazeManager/displayNextInAppMessage()":{"role":"symbol","title":"displayNextInAppMessage()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"displayNextInAppMessage"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/BrazeManager\/displayNextInAppMessage()","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/brazemanager\/displaynextinappmessage()"},"doc://com.yababaGmbH.yababa/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.yababaGmbH.yababa\/SH"},"doc://com.yababaGmbH.yababa/documentation/Yababa/BrazeManager/PushNotificationMarketingManager-Implementations":{"role":"collectionGroup","title":"PushNotificationMarketingManager Implementations","abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/BrazeManager\/PushNotificationMarketingManager-Implementations","kind":"article","type":"topic","url":"\/documentation\/yababa\/brazemanager\/pushnotificationmarketingmanager-implementations"},"doc://com.yababaGmbH.yababa/documentation/Yababa/BrazeManager/setUserEmailSubscription(status:)":{"role":"symbol","title":"setUserEmailSubscription(status:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setUserEmailSubscription"},{"kind":"text","text":"("},{"kind":"externalParam","text":"status"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ABKNotificationSubscriptionType","preciseIdentifier":"c:@E@ABKNotificationSubscriptionType"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"You can set the email subscription state for an email address that is not yet associated with any users within Braze."},{"type":"text","text":" "},{"type":"text","text":"When that email address is subsequently associated with a user, the email subscription state that you uploaded will be automatically set."}],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/BrazeManager\/setUserEmailSubscription(status:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"setUserEmailSubscriptionWithStatus:"}],"url":"\/documentation\/yababa\/brazemanager\/setuseremailsubscription(status:)"},"doc://com.yababaGmbH.yababa/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.yababaGmbH.yababa\/s7CVarArgP"},"doc://com.yababaGmbH.yababa/documentation/Yababa/BrazeManager/init":{"role":"symbol","title":"init","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/BrazeManager\/init","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"init"}],"url":"\/documentation\/yababa\/brazemanager\/init"},"doc://com.yababaGmbH.yababa/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(cs)NSObject"},"doc://com.yababaGmbH.yababa/documentation/Yababa/BrazeManager/ABKInAppMessageUIDelegate-Implementations":{"role":"collectionGroup","title":"ABKInAppMessageUIDelegate Implementations","abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/BrazeManager\/ABKInAppMessageUIDelegate-Implementations","kind":"article","type":"topic","url":"\/documentation\/yababa\/brazemanager\/abkinappmessageuidelegate-implementations"},"doc://com.yababaGmbH.yababa/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.yababaGmbH.yababa\/SQ"},"doc://com.yababaGmbH.yababa/documentation/Yababa/BrazeManager/configure(_:didFinishLaunchingWithOptions:)":{"role":"symbol","title":"configure(_:didFinishLaunchingWithOptions:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"configure"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UIApplication","preciseIdentifier":"c:objc(cs)UIApplication"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didFinishLaunchingWithOptions"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"UIApplication","preciseIdentifier":"c:objc(cs)UIApplication"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"LaunchOptionsKey","preciseIdentifier":"c:@T@UIApplicationLaunchOptionsKey"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]?)"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/BrazeManager\/configure(_:didFinishLaunchingWithOptions:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"configure:didFinishLaunchingWithOptions:"}],"url":"\/documentation\/yababa\/brazemanager\/configure(_:didfinishlaunchingwithoptions:)"},"doc://com.yababaGmbH.yababa/documentation/Yababa/BrazeManager/registerDeviceToken(_:)":{"role":"symbol","title":"registerDeviceToken(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"registerDeviceToken"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Data","preciseIdentifier":"s:10Foundation4DataV"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/BrazeManager\/registerDeviceToken(_:)","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/brazemanager\/registerdevicetoken(_:)"},"doc://com.yababaGmbH.yababa/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)NSObject"},"doc://com.yababaGmbH.yababa/documentation/Yababa/BrazeManager/updateAddress()":{"role":"symbol","title":"updateAddress()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"updateAddress"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/BrazeManager\/updateAddress()","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/brazemanager\/updateaddress()"},"doc://com.yababaGmbH.yababa/documentation/Yababa/PushNotificationMarketingManager":{"role":"symbol","title":"PushNotificationMarketingManager","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"PushNotificationMarketingManager"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/PushNotificationMarketingManager","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PushNotificationMarketingManager"}],"url":"\/documentation\/yababa\/pushnotificationmarketingmanager"},"doc://com.yababaGmbH.yababa/documentation/Yababa/BrazeManager/setUserPushStatus(_:)":{"role":"symbol","title":"setUserPushStatus(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setUserPushStatus"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/BrazeManager\/setUserPushStatus(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"setUserPushStatus:"}],"url":"\/documentation\/yababa\/brazemanager\/setuserpushstatus(_:)"},"doc://com.yababaGmbH.yababa/documentation/Yababa/BrazeManager":{"role":"symbol","title":"BrazeManager","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"BrazeManager"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/BrazeManager","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"BrazeManager"}],"url":"\/documentation\/yababa\/brazemanager"},"doc://com.yababaGmbH.yababa/documentation/Yababa/BrazeManager/sharedInstance":{"role":"symbol","title":"sharedInstance","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"sharedInstance"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"BrazeManager","preciseIdentifier":"c:@M@Yababa@objc(cs)BrazeManager"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/BrazeManager\/sharedInstance","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"sharedInstance"}],"url":"\/documentation\/yababa\/brazemanager\/sharedinstance"},"doc://com.yababaGmbH.yababa/objc(pl)ABKInAppMessageUIDelegate":{"type":"unresolvable","title":"Appboy_iOS_SDK.ABKInAppMessageUIDelegate","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)ABKInAppMessageUIDelegate"},"doc://com.yababaGmbH.yababa/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.yababaGmbH.yababa\/s28CustomDebugStringConvertibleP"},"doc://com.yababaGmbH.yababa/documentation/Yababa":{"role":"collection","title":"Yababa","abstract":[{"type":"text","text":"Getting Started"}],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa","kind":"symbol","type":"topic","url":"\/documentation\/yababa"},"doc://com.yababaGmbH.yababa/documentation/Yababa/BrazeManager/setLoggedInUser(changeUser:)":{"role":"symbol","title":"setLoggedInUser(changeUser:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setLoggedInUser"},{"kind":"text","text":"("},{"kind":"externalParam","text":"changeUser"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/BrazeManager\/setLoggedInUser(changeUser:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"setLoggedInUserWithChangeUser:"}],"url":"\/documentation\/yababa\/brazemanager\/setloggedinuser(changeuser:)"},"doc://com.yababaGmbH.yababa/documentation/Yababa/BrazeManager/configureInAppMessaging()":{"role":"symbol","title":"configureInAppMessaging()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"configureInAppMessaging"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/BrazeManager\/configureInAppMessaging()","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/brazemanager\/configureinappmessaging()"},"doc://com.yababaGmbH.yababa/objc(pl)ABKInAppMessageControllerDelegate":{"type":"unresolvable","title":"Appboy_iOS_SDK.ABKInAppMessageControllerDelegate","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)ABKInAppMessageControllerDelegate"},"doc://com.yababaGmbH.yababa/12SkeletonView17AssociatedObjectsP":{"type":"unresolvable","title":"SkeletonView.AssociatedObjects","identifier":"doc:\/\/com.yababaGmbH.yababa\/12SkeletonView17AssociatedObjectsP"},"doc://com.yababaGmbH.yababa/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.yababaGmbH.yababa\/s23CustomStringConvertibleP"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"BrazeManager"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"BrazeManager"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"BrazeManager"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/BrazeManager\/configure(_:didFinishLaunchingWithOptions:)","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/BrazeManager\/init","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/BrazeManager\/setLoggedInUser(changeUser:)","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/BrazeManager\/setUserEmailSubscription(status:)","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/BrazeManager\/setUserPushStatus(_:)"]},{"title":"Type Properties","identifiers":["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/BrazeManager\/sharedInstance"]},{"title":"Default Implementations","identifiers":["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/BrazeManager\/ABKInAppMessageUIDelegate-Implementations"],"generated":true}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.yababaGmbH.yababa\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"BrazeManager"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1BrazeManager~1setUserEmailSubscription(status:)\/title","value":"setUserEmailSubscriptionWithStatus:"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1BrazeManager~1setUserEmailSubscription(status:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setUserEmailSubscriptionWithStatus:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1BrazeManager~1configure(_:didFinishLaunchingWithOptions:)\/title","value":"configure:didFinishLaunchingWithOptions:"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1BrazeManager~1configure(_:didFinishLaunchingWithOptions:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"configure:didFinishLaunchingWithOptions:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1BrazeManager~1setUserPushStatus(_:)\/title","value":"setUserPushStatus:"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1BrazeManager~1setUserPushStatus(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setUserPushStatus:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1BrazeManager\/title","value":"BrazeManager"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1BrazeManager\/fragments","value":[{"kind":"identifier","text":"BrazeManager"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1BrazeManager~1sharedInstance\/title","value":"sharedInstance"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1BrazeManager~1sharedInstance\/fragments","value":[{"kind":"identifier","text":"sharedInstance"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1BrazeManager~1setLoggedInUser(changeUser:)\/title","value":"setLoggedInUserWithChangeUser:"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1BrazeManager~1setLoggedInUser(changeUser:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setLoggedInUserWithChangeUser:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}