{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CheckoutSceneInteractor"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/yababa\/checkoutsceneinteractor"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/yababa\/checkoutsceneinteractor"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.yababaGmbH.yababa\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CardSelectionDelegate","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CheckoutSceneInteractorProtocol","doc:\/\/com.yababaGmbH.yababa\/objc(pl)NSObject","doc:\/\/com.yababaGmbH.yababa\/12SkeletonView17AssociatedObjectsP","doc:\/\/com.yababaGmbH.yababa\/@M@Stripe@objc(pl)STPAuthenticationContext","doc:\/\/com.yababaGmbH.yababa\/s7CVarArgP","doc:\/\/com.yababaGmbH.yababa\/s28CustomDebugStringConvertibleP","doc:\/\/com.yababaGmbH.yababa\/s23CustomStringConvertibleP","doc:\/\/com.yababaGmbH.yababa\/SQ","doc:\/\/com.yababaGmbH.yababa\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CheckoutSceneInteractor","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CheckoutSceneInteractor\/presenter","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CheckoutSceneInteractor\/userStateManager"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CheckoutSceneInteractor\/completeCheckout(orderId:)","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CheckoutSceneInteractor\/confirmCheckout()","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CheckoutSceneInteractor\/confirmWithCheckoutNow(paymentType:idPaymentMethod:idAddress:deliveryTimeWindow:secureCheckoutBeanString:currentCheckoutResponse:)","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CheckoutSceneInteractor\/getCreditCards()","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CheckoutSceneInteractor\/getDeliveryAddressAndTimeSlot()","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CheckoutSceneInteractor\/getPaymentType()","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CheckoutSceneInteractor\/getSelectedCard()","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CheckoutSceneInteractor\/postPaymentSuccessToServer(sessionId:)","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CheckoutSceneInteractor\/prepareCartCheckout()","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CheckoutSceneInteractor\/setCouponName(couponName:)","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CheckoutSceneInteractor\/setStripeAccount(gatewayInfo:)","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CheckoutSceneInteractor\/startPaymentRecoveryFlow(clientSecret:referenceMethodId:sessionId:)"]},{"title":"Default Implementations","identifiers":["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CheckoutSceneInteractor\/CardSelectionDelegate-Implementations","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CheckoutSceneInteractor\/CheckoutSceneInteractorProtocol-Implementations","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CheckoutSceneInteractor\/STPAuthenticationContext-Implementations"],"generated":true}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CheckoutSceneInteractor"}],"title":"CheckoutSceneInteractor","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@Yababa@objc(cs)CheckoutSceneInteractor","modules":[{"name":"Yababa"}],"navigatorTitle":[{"kind":"identifier","text":"CheckoutSceneInteractor"}]},"hierarchy":{"paths":[["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa"]]},"references":{"doc://com.yababaGmbH.yababa/documentation/Yababa/CheckoutSceneInteractor/setStripeAccount(gatewayInfo:)":{"role":"symbol","title":"setStripeAccount(gatewayInfo:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setStripeAccount"},{"kind":"text","text":"("},{"kind":"externalParam","text":"gatewayInfo"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GatewayInfo","preciseIdentifier":"s:6Yababa11GatewayInfoC"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CheckoutSceneInteractor\/setStripeAccount(gatewayInfo:)","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/checkoutsceneinteractor\/setstripeaccount(gatewayinfo:)"},"doc://com.yababaGmbH.yababa/documentation/Yababa/CheckoutSceneInteractor/setCouponName(couponName:)":{"role":"symbol","title":"setCouponName(couponName:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setCouponName"},{"kind":"text","text":"("},{"kind":"externalParam","text":"couponName"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?)"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CheckoutSceneInteractor\/setCouponName(couponName:)","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/checkoutsceneinteractor\/setcouponname(couponname:)"},"doc://com.yababaGmbH.yababa/documentation/Yababa/CheckoutSceneInteractor/confirmWithCheckoutNow(paymentType:idPaymentMethod:idAddress:deliveryTimeWindow:secureCheckoutBeanString:currentCheckoutResponse:)":{"role":"symbol","title":"confirmWithCheckoutNow(paymentType:idPaymentMethod:idAddress:deliveryTimeWindow:secureCheckoutBeanString:currentCheckoutResponse:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"confirmWithCheckoutNow"},{"kind":"text","text":"("},{"kind":"externalParam","text":"paymentType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"idPaymentMethod"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"kind":"externalParam","text":"idAddress"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"kind":"externalParam","text":"deliveryTimeWindow"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"secureCheckoutBeanString"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"currentCheckoutResponse"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CheckoutResponseBean","preciseIdentifier":"s:6Yababa20CheckoutResponseBeanC"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CheckoutSceneInteractor\/confirmWithCheckoutNow(paymentType:idPaymentMethod:idAddress:deliveryTimeWindow:secureCheckoutBeanString:currentCheckoutResponse:)","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/checkoutsceneinteractor\/confirmwithcheckoutnow(paymenttype:idpaymentmethod:idaddress:deliverytimewindow:securecheckoutbeanstring:currentcheckoutresponse:)"},"doc://com.yababaGmbH.yababa/12SkeletonView17AssociatedObjectsP":{"type":"unresolvable","title":"SkeletonView.AssociatedObjects","identifier":"doc:\/\/com.yababaGmbH.yababa\/12SkeletonView17AssociatedObjectsP"},"doc://com.yababaGmbH.yababa/documentation/Yababa/CheckoutSceneInteractor/confirmCheckout()":{"role":"symbol","title":"confirmCheckout()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"confirmCheckout"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CheckoutSceneInteractor\/confirmCheckout()","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/checkoutsceneinteractor\/confirmcheckout()"},"doc://com.yababaGmbH.yababa/documentation/Yababa/CardSelectionDelegate":{"role":"symbol","title":"CardSelectionDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"CardSelectionDelegate"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CardSelectionDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CardSelectionDelegate"}],"url":"\/documentation\/yababa\/cardselectiondelegate"},"doc://com.yababaGmbH.yababa/documentation/Yababa/CheckoutSceneInteractor":{"role":"symbol","title":"CheckoutSceneInteractor","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CheckoutSceneInteractor"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CheckoutSceneInteractor","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CheckoutSceneInteractor"}],"url":"\/documentation\/yababa\/checkoutsceneinteractor"},"doc://com.yababaGmbH.yababa/documentation/Yababa/CheckoutSceneInteractor/prepareCartCheckout()":{"role":"symbol","title":"prepareCartCheckout()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"prepareCartCheckout"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CheckoutSceneInteractor\/prepareCartCheckout()","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/checkoutsceneinteractor\/preparecartcheckout()"},"doc://com.yababaGmbH.yababa/documentation/Yababa/CheckoutSceneInteractor/getPaymentType()":{"role":"symbol","title":"getPaymentType()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getPaymentType"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CheckoutSceneInteractor\/getPaymentType()","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/checkoutsceneinteractor\/getpaymenttype()"},"doc://com.yababaGmbH.yababa/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.yababaGmbH.yababa\/SQ"},"doc://com.yababaGmbH.yababa/documentation/Yababa/CheckoutSceneInteractor/presenter":{"role":"symbol","title":"presenter","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"presenter"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CheckoutScenePresenterProtocol","preciseIdentifier":"s:6Yababa30CheckoutScenePresenterProtocolP"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CheckoutSceneInteractor\/presenter","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/checkoutsceneinteractor\/presenter"},"doc://com.yababaGmbH.yababa/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.yababaGmbH.yababa\/SH"},"doc://com.yababaGmbH.yababa/documentation/Yababa/CheckoutSceneInteractorProtocol":{"role":"symbol","title":"CheckoutSceneInteractorProtocol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"CheckoutSceneInteractorProtocol"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CheckoutSceneInteractorProtocol","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CheckoutSceneInteractorProtocol"}],"url":"\/documentation\/yababa\/checkoutsceneinteractorprotocol"},"doc://com.yababaGmbH.yababa/documentation/Yababa/CheckoutSceneInteractor/completeCheckout(orderId:)":{"role":"symbol","title":"completeCheckout(orderId:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"completeCheckout"},{"kind":"text","text":"("},{"kind":"externalParam","text":"orderId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":"?)"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CheckoutSceneInteractor\/completeCheckout(orderId:)","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/checkoutsceneinteractor\/completecheckout(orderid:)"},"doc://com.yababaGmbH.yababa/documentation/Yababa/CheckoutSceneInteractor/init":{"role":"symbol","title":"init","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CheckoutSceneInteractor\/init","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"init"}],"url":"\/documentation\/yababa\/checkoutsceneinteractor\/init"},"doc://com.yababaGmbH.yababa/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.yababaGmbH.yababa\/s28CustomDebugStringConvertibleP"},"doc://com.yababaGmbH.yababa/documentation/Yababa/CheckoutSceneInteractor/userStateManager":{"role":"symbol","title":"userStateManager","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"userStateManager"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UserStateManagerProtocol","preciseIdentifier":"s:6Yababa24UserStateManagerProtocolP"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CheckoutSceneInteractor\/userStateManager","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/checkoutsceneinteractor\/userstatemanager"},"doc://com.yababaGmbH.yababa/documentation/Yababa/CheckoutSceneInteractor/postPaymentSuccessToServer(sessionId:)":{"role":"symbol","title":"postPaymentSuccessToServer(sessionId:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"postPaymentSuccessToServer"},{"kind":"text","text":"("},{"kind":"externalParam","text":"sessionId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CheckoutSceneInteractor\/postPaymentSuccessToServer(sessionId:)","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/checkoutsceneinteractor\/postpaymentsuccesstoserver(sessionid:)"},"doc://com.yababaGmbH.yababa/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.yababaGmbH.yababa\/s23CustomStringConvertibleP"},"doc://com.yababaGmbH.yababa/@M@Stripe@objc(pl)STPAuthenticationContext":{"type":"unresolvable","title":"Stripe.STPAuthenticationContext","identifier":"doc:\/\/com.yababaGmbH.yababa\/@M@Stripe@objc(pl)STPAuthenticationContext"},"doc://com.yababaGmbH.yababa/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.yababaGmbH.yababa\/s7CVarArgP"},"doc://com.yababaGmbH.yababa/documentation/Yababa/CheckoutSceneInteractor/CheckoutSceneInteractorProtocol-Implementations":{"role":"collectionGroup","title":"CheckoutSceneInteractorProtocol Implementations","abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CheckoutSceneInteractor\/CheckoutSceneInteractorProtocol-Implementations","kind":"article","type":"topic","url":"\/documentation\/yababa\/checkoutsceneinteractor\/checkoutsceneinteractorprotocol-implementations"},"doc://com.yababaGmbH.yababa/documentation/Yababa/CheckoutSceneInteractor/getDeliveryAddressAndTimeSlot()":{"role":"symbol","title":"getDeliveryAddressAndTimeSlot()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getDeliveryAddressAndTimeSlot"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CheckoutSceneInteractor\/getDeliveryAddressAndTimeSlot()","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/checkoutsceneinteractor\/getdeliveryaddressandtimeslot()"},"doc://com.yababaGmbH.yababa/documentation/Yababa/CheckoutSceneInteractor/getCreditCards()":{"role":"symbol","title":"getCreditCards()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getCreditCards"},{"kind":"text","text":"() -> (cards"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"CreditCard","preciseIdentifier":"s:6Yababa10CreditCardC"},{"kind":"text","text":"]?, otherPaymentMethods"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"CreditCard","preciseIdentifier":"s:6Yababa10CreditCardC"},{"kind":"text","text":"]?)"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CheckoutSceneInteractor\/getCreditCards()","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/checkoutsceneinteractor\/getcreditcards()"},"doc://com.yababaGmbH.yababa/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)NSObject"},"doc://com.yababaGmbH.yababa/documentation/Yababa/CheckoutSceneInteractor/startPaymentRecoveryFlow(clientSecret:referenceMethodId:sessionId:)":{"role":"symbol","title":"startPaymentRecoveryFlow(clientSecret:referenceMethodId:sessionId:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"startPaymentRecoveryFlow"},{"kind":"text","text":"("},{"kind":"externalParam","text":"clientSecret"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"referenceMethodId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"sessionId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CheckoutSceneInteractor\/startPaymentRecoveryFlow(clientSecret:referenceMethodId:sessionId:)","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/checkoutsceneinteractor\/startpaymentrecoveryflow(clientsecret:referencemethodid:sessionid:)"},"doc://com.yababaGmbH.yababa/documentation/Yababa/CheckoutSceneInteractor/STPAuthenticationContext-Implementations":{"role":"collectionGroup","title":"STPAuthenticationContext Implementations","abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CheckoutSceneInteractor\/STPAuthenticationContext-Implementations","kind":"article","type":"topic","url":"\/documentation\/yababa\/checkoutsceneinteractor\/stpauthenticationcontext-implementations"},"doc://com.yababaGmbH.yababa/documentation/Yababa/CheckoutSceneInteractor/getSelectedCard()":{"role":"symbol","title":"getSelectedCard()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getSelectedCard"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"CreditCard","preciseIdentifier":"s:6Yababa10CreditCardC"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CheckoutSceneInteractor\/getSelectedCard()","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/checkoutsceneinteractor\/getselectedcard()"},"doc://com.yababaGmbH.yababa/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(cs)NSObject"},"doc://com.yababaGmbH.yababa/documentation/Yababa":{"role":"collection","title":"Yababa","abstract":[{"type":"text","text":"Getting Started"}],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa","kind":"symbol","type":"topic","url":"\/documentation\/yababa"},"doc://com.yababaGmbH.yababa/documentation/Yababa/CheckoutSceneInteractor/CardSelectionDelegate-Implementations":{"role":"collectionGroup","title":"CardSelectionDelegate Implementations","abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CheckoutSceneInteractor\/CardSelectionDelegate-Implementations","kind":"article","type":"topic","url":"\/documentation\/yababa\/checkoutsceneinteractor\/cardselectiondelegate-implementations"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"CheckoutSceneInteractor"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"CheckoutSceneInteractor"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"CheckoutSceneInteractor"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CheckoutSceneInteractor\/init"]},{"title":"Default Implementations","identifiers":["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CheckoutSceneInteractor\/STPAuthenticationContext-Implementations"],"generated":true}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.yababaGmbH.yababa\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"CheckoutSceneInteractor"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1CheckoutSceneInteractor\/title","value":"CheckoutSceneInteractor"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1CheckoutSceneInteractor\/fragments","value":[{"kind":"identifier","text":"CheckoutSceneInteractor"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}