{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CollectionViewDynamicFlowLayout"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/yababa\/collectionviewdynamicflowlayout"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/yababa\/collectionviewdynamicflowlayout"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.yababaGmbH.yababa\/objc(cs)UICollectionViewFlowLayout"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/BannerCollectionFlowLayout","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/BlockFlowLayout","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/BlocksSliderFlowLayout","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/Columns3FlowLayout","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/DiscountsCollectionFlowLayout","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/DropdownFlowLayout","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/InfoCardFlowLayout","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/InfoTextFlowLayout","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/OrdersCollectionFlowLayout","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ProductCollectionFlowLayout","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ReferralCollectionFlowLayout","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/StaticBlocksFlowLayout"],"kind":"relationships","title":"Inherited By","type":"inheritedBy"},{"identifiers":["doc:\/\/com.yababaGmbH.yababa\/objc(pl)NSCoding","doc:\/\/com.yababaGmbH.yababa\/objc(pl)NSObject","doc:\/\/com.yababaGmbH.yababa\/12SkeletonView17AssociatedObjectsP","doc:\/\/com.yababaGmbH.yababa\/s7CVarArgP","doc:\/\/com.yababaGmbH.yababa\/s28CustomDebugStringConvertibleP","doc:\/\/com.yababaGmbH.yababa\/s23CustomStringConvertibleP","doc:\/\/com.yababaGmbH.yababa\/SQ","doc:\/\/com.yababaGmbH.yababa\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CollectionViewDynamicFlowLayout","interfaceLanguage":"swift"},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CollectionViewDynamicFlowLayout\/init()","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CollectionViewDynamicFlowLayout\/init(coder:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CollectionViewDynamicFlowLayout\/bottomPadding","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CollectionViewDynamicFlowLayout\/defaultPadding","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CollectionViewDynamicFlowLayout\/fullAvailableWidth","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CollectionViewDynamicFlowLayout\/topPadding"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CollectionViewDynamicFlowLayout\/setup()"]}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CollectionViewDynamicFlowLayout"}],"title":"CollectionViewDynamicFlowLayout","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@Yababa@objc(cs)CollectionViewDynamicFlowLayout","modules":[{"name":"Yababa"}],"navigatorTitle":[{"kind":"identifier","text":"CollectionViewDynamicFlowLayout"}]},"hierarchy":{"paths":[["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa"]]},"references":{"doc://com.yababaGmbH.yababa/documentation/Yababa/Columns3FlowLayout":{"role":"symbol","title":"Columns3FlowLayout","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Columns3FlowLayout"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/Columns3FlowLayout","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Columns3FlowLayout"}],"url":"\/documentation\/yababa\/columns3flowlayout"},"doc://com.yababaGmbH.yababa/documentation/Yababa/CollectionViewDynamicFlowLayout/init()":{"role":"symbol","title":"init()","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CollectionViewDynamicFlowLayout\/init()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"init"}],"url":"\/documentation\/yababa\/collectionviewdynamicflowlayout\/init()"},"doc://com.yababaGmbH.yababa/documentation/Yababa/BlockFlowLayout":{"role":"symbol","title":"BlockFlowLayout","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"BlockFlowLayout"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/BlockFlowLayout","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"BlockFlowLayout"}],"url":"\/documentation\/yababa\/blockflowlayout"},"doc://com.yababaGmbH.yababa/documentation/Yababa/CollectionViewDynamicFlowLayout/defaultPadding":{"role":"symbol","title":"defaultPadding","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"defaultPadding"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CollectionViewDynamicFlowLayout\/defaultPadding","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/collectionviewdynamicflowlayout\/defaultpadding"},"doc://com.yababaGmbH.yababa/documentation/Yababa/StaticBlocksFlowLayout":{"role":"symbol","title":"StaticBlocksFlowLayout","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"StaticBlocksFlowLayout"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/StaticBlocksFlowLayout","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"StaticBlocksFlowLayout"}],"url":"\/documentation\/yababa\/staticblocksflowlayout"},"doc://com.yababaGmbH.yababa/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.yababaGmbH.yababa\/s7CVarArgP"},"doc://com.yababaGmbH.yababa/documentation/Yababa/CollectionViewDynamicFlowLayout/bottomPadding":{"role":"symbol","title":"bottomPadding","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"bottomPadding"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CollectionViewDynamicFlowLayout\/bottomPadding","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/collectionviewdynamicflowlayout\/bottompadding"},"doc://com.yababaGmbH.yababa/12SkeletonView17AssociatedObjectsP":{"type":"unresolvable","title":"SkeletonView.AssociatedObjects","identifier":"doc:\/\/com.yababaGmbH.yababa\/12SkeletonView17AssociatedObjectsP"},"doc://com.yababaGmbH.yababa/documentation/Yababa/CollectionViewDynamicFlowLayout/topPadding":{"role":"symbol","title":"topPadding","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"topPadding"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CollectionViewDynamicFlowLayout\/topPadding","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/collectionviewdynamicflowlayout\/toppadding"},"doc://com.yababaGmbH.yababa/documentation/Yababa/ProductCollectionFlowLayout":{"role":"symbol","title":"ProductCollectionFlowLayout","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ProductCollectionFlowLayout"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ProductCollectionFlowLayout","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ProductCollectionFlowLayout"}],"url":"\/documentation\/yababa\/productcollectionflowlayout"},"doc://com.yababaGmbH.yababa/documentation/Yababa/InfoCardFlowLayout":{"role":"symbol","title":"InfoCardFlowLayout","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"InfoCardFlowLayout"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/InfoCardFlowLayout","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"InfoCardFlowLayout"}],"url":"\/documentation\/yababa\/infocardflowlayout"},"doc://com.yababaGmbH.yababa/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.yababaGmbH.yababa\/s23CustomStringConvertibleP"},"doc://com.yababaGmbH.yababa/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.yababaGmbH.yababa\/SQ"},"doc://com.yababaGmbH.yababa/documentation/Yababa":{"role":"collection","title":"Yababa","abstract":[{"type":"text","text":"Getting Started"}],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa","kind":"symbol","type":"topic","url":"\/documentation\/yababa"},"doc://com.yababaGmbH.yababa/objc(cs)UICollectionViewFlowLayout":{"type":"unresolvable","title":"UICollectionViewFlowLayout","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(cs)UICollectionViewFlowLayout"},"doc://com.yababaGmbH.yababa/documentation/Yababa/ReferralCollectionFlowLayout":{"role":"symbol","title":"ReferralCollectionFlowLayout","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ReferralCollectionFlowLayout"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ReferralCollectionFlowLayout","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ReferralCollectionFlowLayout"}],"url":"\/documentation\/yababa\/referralcollectionflowlayout"},"doc://com.yababaGmbH.yababa/documentation/Yababa/OrdersCollectionFlowLayout":{"role":"symbol","title":"OrdersCollectionFlowLayout","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"OrdersCollectionFlowLayout"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/OrdersCollectionFlowLayout","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"OrdersCollectionFlowLayout"}],"url":"\/documentation\/yababa\/orderscollectionflowlayout"},"doc://com.yababaGmbH.yababa/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)NSObject"},"doc://com.yababaGmbH.yababa/documentation/Yababa/InfoTextFlowLayout":{"role":"symbol","title":"InfoTextFlowLayout","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"InfoTextFlowLayout"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/InfoTextFlowLayout","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"InfoTextFlowLayout"}],"url":"\/documentation\/yababa\/infotextflowlayout"},"doc://com.yababaGmbH.yababa/documentation/Yababa/CollectionViewDynamicFlowLayout/init(coder:)":{"role":"symbol","title":"init(coder:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"coder"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSCoder","preciseIdentifier":"c:objc(cs)NSCoder"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CollectionViewDynamicFlowLayout\/init(coder:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithCoder:"}],"url":"\/documentation\/yababa\/collectionviewdynamicflowlayout\/init(coder:)"},"doc://com.yababaGmbH.yababa/documentation/Yababa/CollectionViewDynamicFlowLayout":{"role":"symbol","title":"CollectionViewDynamicFlowLayout","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CollectionViewDynamicFlowLayout"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CollectionViewDynamicFlowLayout","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CollectionViewDynamicFlowLayout"}],"url":"\/documentation\/yababa\/collectionviewdynamicflowlayout"},"doc://com.yababaGmbH.yababa/documentation/Yababa/CollectionViewDynamicFlowLayout/fullAvailableWidth":{"role":"symbol","title":"fullAvailableWidth","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"fullAvailableWidth"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CollectionViewDynamicFlowLayout\/fullAvailableWidth","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/collectionviewdynamicflowlayout\/fullavailablewidth"},"doc://com.yababaGmbH.yababa/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.yababaGmbH.yababa\/SH"},"doc://com.yababaGmbH.yababa/documentation/Yababa/DropdownFlowLayout":{"role":"symbol","title":"DropdownFlowLayout","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DropdownFlowLayout"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/DropdownFlowLayout","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DropdownFlowLayout"}],"url":"\/documentation\/yababa\/dropdownflowlayout"},"doc://com.yababaGmbH.yababa/documentation/Yababa/DiscountsCollectionFlowLayout":{"role":"symbol","title":"DiscountsCollectionFlowLayout","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DiscountsCollectionFlowLayout"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/DiscountsCollectionFlowLayout","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DiscountsCollectionFlowLayout"}],"url":"\/documentation\/yababa\/discountscollectionflowlayout"},"doc://com.yababaGmbH.yababa/objc(pl)NSCoding":{"type":"unresolvable","title":"Foundation.NSCoding","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)NSCoding"},"doc://com.yababaGmbH.yababa/documentation/Yababa/BannerCollectionFlowLayout":{"role":"symbol","title":"BannerCollectionFlowLayout","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"BannerCollectionFlowLayout"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/BannerCollectionFlowLayout","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"BannerCollectionFlowLayout"}],"url":"\/documentation\/yababa\/bannercollectionflowlayout"},"doc://com.yababaGmbH.yababa/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.yababaGmbH.yababa\/s28CustomDebugStringConvertibleP"},"doc://com.yababaGmbH.yababa/documentation/Yababa/CollectionViewDynamicFlowLayout/setup()":{"role":"symbol","title":"setup()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setup"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CollectionViewDynamicFlowLayout\/setup()","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/collectionviewdynamicflowlayout\/setup()"},"doc://com.yababaGmbH.yababa/documentation/Yababa/BlocksSliderFlowLayout":{"role":"symbol","title":"BlocksSliderFlowLayout","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"BlocksSliderFlowLayout"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/BlocksSliderFlowLayout","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"BlocksSliderFlowLayout"}],"url":"\/documentation\/yababa\/blockssliderflowlayout"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"CollectionViewDynamicFlowLayout"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"CollectionViewDynamicFlowLayout"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"CollectionViewDynamicFlowLayout"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CollectionViewDynamicFlowLayout\/init()","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CollectionViewDynamicFlowLayout\/init(coder:)"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.yababaGmbH.yababa\/objc(cs)UICollectionViewFlowLayout"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/BannerCollectionFlowLayout","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/BlockFlowLayout","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/BlocksSliderFlowLayout","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/Columns3FlowLayout","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/DiscountsCollectionFlowLayout","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/DropdownFlowLayout","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/InfoCardFlowLayout","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/InfoTextFlowLayout","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/OrdersCollectionFlowLayout","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ProductCollectionFlowLayout","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ReferralCollectionFlowLayout","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/StaticBlocksFlowLayout"],"kind":"relationships","title":"Inherited By","type":"inheritedBy"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"CollectionViewDynamicFlowLayout"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"UICollectionViewFlowLayout","preciseIdentifier":"c:objc(cs)UICollectionViewFlowLayout"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1Columns3FlowLayout\/title","value":"Columns3FlowLayout"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1Columns3FlowLayout\/fragments","value":[{"kind":"identifier","text":"Columns3FlowLayout"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1CollectionViewDynamicFlowLayout~1init()\/title","value":"init"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1CollectionViewDynamicFlowLayout~1init()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1BlockFlowLayout\/title","value":"BlockFlowLayout"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1BlockFlowLayout\/fragments","value":[{"kind":"identifier","text":"BlockFlowLayout"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1StaticBlocksFlowLayout\/title","value":"StaticBlocksFlowLayout"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1StaticBlocksFlowLayout\/fragments","value":[{"kind":"identifier","text":"StaticBlocksFlowLayout"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1ProductCollectionFlowLayout\/title","value":"ProductCollectionFlowLayout"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1ProductCollectionFlowLayout\/fragments","value":[{"kind":"identifier","text":"ProductCollectionFlowLayout"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1InfoCardFlowLayout\/title","value":"InfoCardFlowLayout"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1InfoCardFlowLayout\/fragments","value":[{"kind":"identifier","text":"InfoCardFlowLayout"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1ReferralCollectionFlowLayout\/title","value":"ReferralCollectionFlowLayout"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1ReferralCollectionFlowLayout\/fragments","value":[{"kind":"identifier","text":"ReferralCollectionFlowLayout"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1OrdersCollectionFlowLayout\/title","value":"OrdersCollectionFlowLayout"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1OrdersCollectionFlowLayout\/fragments","value":[{"kind":"identifier","text":"OrdersCollectionFlowLayout"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1InfoTextFlowLayout\/title","value":"InfoTextFlowLayout"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1InfoTextFlowLayout\/fragments","value":[{"kind":"identifier","text":"InfoTextFlowLayout"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1CollectionViewDynamicFlowLayout~1init(coder:)\/title","value":"initWithCoder:"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1CollectionViewDynamicFlowLayout~1init(coder:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithCoder:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1CollectionViewDynamicFlowLayout\/title","value":"CollectionViewDynamicFlowLayout"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1CollectionViewDynamicFlowLayout\/fragments","value":[{"kind":"identifier","text":"CollectionViewDynamicFlowLayout"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1DropdownFlowLayout\/title","value":"DropdownFlowLayout"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1DropdownFlowLayout\/fragments","value":[{"kind":"identifier","text":"DropdownFlowLayout"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1DiscountsCollectionFlowLayout\/title","value":"DiscountsCollectionFlowLayout"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1DiscountsCollectionFlowLayout\/fragments","value":[{"kind":"identifier","text":"DiscountsCollectionFlowLayout"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1BannerCollectionFlowLayout\/title","value":"BannerCollectionFlowLayout"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1BannerCollectionFlowLayout\/fragments","value":[{"kind":"identifier","text":"BannerCollectionFlowLayout"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1BlocksSliderFlowLayout\/title","value":"BlocksSliderFlowLayout"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1BlocksSliderFlowLayout\/fragments","value":[{"kind":"identifier","text":"BlocksSliderFlowLayout"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}