{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DeliveryAreasViewController"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/yababa\/deliveryareasviewcontroller"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/yababa\/deliveryareasviewcontroller"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/MasterViewController"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.yababaGmbH.yababa\/objc(pl)NSCoding","doc:\/\/com.yababaGmbH.yababa\/objc(pl)NSExtensionRequestHandling","doc:\/\/com.yababaGmbH.yababa\/objc(pl)NSObject","doc:\/\/com.yababaGmbH.yababa\/12SkeletonView17AssociatedObjectsP","doc:\/\/com.yababaGmbH.yababa\/s7CVarArgP","doc:\/\/com.yababaGmbH.yababa\/s28CustomDebugStringConvertibleP","doc:\/\/com.yababaGmbH.yababa\/s23CustomStringConvertibleP","doc:\/\/com.yababaGmbH.yababa\/SQ","doc:\/\/com.yababaGmbH.yababa\/SH","doc:\/\/com.yababaGmbH.yababa\/s8SendableP","doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIActivityItemsConfigurationProviding","doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIAppearanceContainer","doc:\/\/com.yababaGmbH.yababa\/objc(pl)UICollectionViewDataSource","doc:\/\/com.yababaGmbH.yababa\/objc(pl)UICollectionViewDelegate","doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIContentContainer","doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIFocusEnvironment","doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIPasteConfigurationSupporting","doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIResponderStandardEditActions","doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIScrollViewDelegate","doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIStateRestoring","doc:\/\/com.yababaGmbH.yababa\/objc(pl)UITraitEnvironment","doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIUserActivityRestoring"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/DeliveryAreasViewController","interfaceLanguage":"swift"},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/DeliveryAreasViewController\/init(areasWeDeliverInPlaces:delegate:)","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/DeliveryAreasViewController\/init(coder:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/DeliveryAreasViewController\/collectionView","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/DeliveryAreasViewController\/getNotifiedBtn","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/DeliveryAreasViewController\/pageControl","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/DeliveryAreasViewController\/reEnterBtn","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/DeliveryAreasViewController\/titleLabel"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/DeliveryAreasViewController\/onBack()","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/DeliveryAreasViewController\/onGetNotified()","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/DeliveryAreasViewController\/onReEnter()","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/DeliveryAreasViewController\/setupUI()","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/DeliveryAreasViewController\/viewDidLoad()"]},{"title":"Default Implementations","identifiers":["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/DeliveryAreasViewController\/UICollectionViewDataSource-Implementations","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/DeliveryAreasViewController\/UICollectionViewDelegate-Implementations"],"generated":true}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DeliveryAreasViewController"}],"title":"DeliveryAreasViewController","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@Yababa@objc(cs)DeliveryAreasViewController","modules":[{"name":"Yababa"}],"navigatorTitle":[{"kind":"identifier","text":"DeliveryAreasViewController"}]},"hierarchy":{"paths":[["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa"]]},"references":{"doc://com.yababaGmbH.yababa/documentation/Yababa/DeliveryAreasViewController/init(coder:)":{"role":"symbol","title":"init(coder:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"coder"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSCoder","preciseIdentifier":"c:objc(cs)NSCoder"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/DeliveryAreasViewController\/init(coder:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithCoder:"}],"url":"\/documentation\/yababa\/deliveryareasviewcontroller\/init(coder:)"},"doc://com.yababaGmbH.yababa/documentation/Yababa/DeliveryAreasViewController/reEnterBtn":{"role":"symbol","title":"reEnterBtn","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"reEnterBtn"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIButton","preciseIdentifier":"c:objc(cs)UIButton"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/DeliveryAreasViewController\/reEnterBtn","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"reEnterBtn"}],"url":"\/documentation\/yababa\/deliveryareasviewcontroller\/reenterbtn"},"doc://com.yababaGmbH.yababa/documentation/Yababa":{"role":"collection","title":"Yababa","abstract":[{"type":"text","text":"Getting Started"}],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa","kind":"symbol","type":"topic","url":"\/documentation\/yababa"},"doc://com.yababaGmbH.yababa/objc(pl)UIScrollViewDelegate":{"type":"unresolvable","title":"UIKit.UIScrollViewDelegate","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIScrollViewDelegate"},"doc://com.yababaGmbH.yababa/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)NSObject"},"doc://com.yababaGmbH.yababa/objc(pl)UIActivityItemsConfigurationProviding":{"type":"unresolvable","title":"UIKit.UIActivityItemsConfigurationProviding","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIActivityItemsConfigurationProviding"},"doc://com.yababaGmbH.yababa/documentation/Yababa/DeliveryAreasViewController/titleLabel":{"role":"symbol","title":"titleLabel","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"titleLabel"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UILabel","preciseIdentifier":"c:objc(cs)UILabel"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/DeliveryAreasViewController\/titleLabel","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"titleLabel"}],"url":"\/documentation\/yababa\/deliveryareasviewcontroller\/titlelabel"},"doc://com.yababaGmbH.yababa/objc(pl)UIContentContainer":{"type":"unresolvable","title":"UIKit.UIContentContainer","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIContentContainer"},"doc://com.yababaGmbH.yababa/objc(pl)UIResponderStandardEditActions":{"type":"unresolvable","title":"UIKit.UIResponderStandardEditActions","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIResponderStandardEditActions"},"doc://com.yababaGmbH.yababa/objc(pl)UIAppearanceContainer":{"type":"unresolvable","title":"UIKit.UIAppearanceContainer","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIAppearanceContainer"},"doc://com.yababaGmbH.yababa/documentation/Yababa/DeliveryAreasViewController/setupUI()":{"role":"symbol","title":"setupUI()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setupUI"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/DeliveryAreasViewController\/setupUI()","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/deliveryareasviewcontroller\/setupui()"},"doc://com.yababaGmbH.yababa/documentation/Yababa/DeliveryAreasViewController/getNotifiedBtn":{"role":"symbol","title":"getNotifiedBtn","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"getNotifiedBtn"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIButton","preciseIdentifier":"c:objc(cs)UIButton"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/DeliveryAreasViewController\/getNotifiedBtn","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"getNotifiedBtn"}],"url":"\/documentation\/yababa\/deliveryareasviewcontroller\/getnotifiedbtn"},"doc://com.yababaGmbH.yababa/objc(pl)NSCoding":{"type":"unresolvable","title":"Foundation.NSCoding","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)NSCoding"},"doc://com.yababaGmbH.yababa/documentation/Yababa/DeliveryAreasViewController":{"role":"symbol","title":"DeliveryAreasViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DeliveryAreasViewController"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/DeliveryAreasViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DeliveryAreasViewController"}],"url":"\/documentation\/yababa\/deliveryareasviewcontroller"},"doc://com.yababaGmbH.yababa/documentation/Yababa/DeliveryAreasViewController/UICollectionViewDataSource-Implementations":{"role":"collectionGroup","title":"UICollectionViewDataSource Implementations","abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/DeliveryAreasViewController\/UICollectionViewDataSource-Implementations","kind":"article","type":"topic","url":"\/documentation\/yababa\/deliveryareasviewcontroller\/uicollectionviewdatasource-implementations"},"doc://com.yababaGmbH.yababa/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.yababaGmbH.yababa\/SH"},"doc://com.yababaGmbH.yababa/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.yababaGmbH.yababa\/s7CVarArgP"},"doc://com.yababaGmbH.yababa/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.yababaGmbH.yababa\/SQ"},"doc://com.yababaGmbH.yababa/documentation/Yababa/MasterViewController":{"role":"symbol","title":"MasterViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MasterViewController"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/MasterViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MasterViewController"}],"url":"\/documentation\/yababa\/masterviewcontroller"},"doc://com.yababaGmbH.yababa/12SkeletonView17AssociatedObjectsP":{"type":"unresolvable","title":"SkeletonView.AssociatedObjects","identifier":"doc:\/\/com.yababaGmbH.yababa\/12SkeletonView17AssociatedObjectsP"},"doc://com.yababaGmbH.yababa/documentation/Yababa/DeliveryAreasViewController/onReEnter()":{"role":"symbol","title":"onReEnter()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onReEnter"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/DeliveryAreasViewController\/onReEnter()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"onReEnter"}],"url":"\/documentation\/yababa\/deliveryareasviewcontroller\/onreenter()"},"doc://com.yababaGmbH.yababa/objc(pl)UICollectionViewDataSource":{"type":"unresolvable","title":"UIKit.UICollectionViewDataSource","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)UICollectionViewDataSource"},"doc://com.yababaGmbH.yababa/objc(pl)UIFocusEnvironment":{"type":"unresolvable","title":"UIKit.UIFocusEnvironment","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIFocusEnvironment"},"doc://com.yababaGmbH.yababa/documentation/Yababa/DeliveryAreasViewController/init(areasWeDeliverInPlaces:delegate:)":{"role":"symbol","title":"init(areasWeDeliverInPlaces:delegate:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"areasWeDeliverInPlaces"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"AreasWeDeliverInPlace","preciseIdentifier":"s:6Yababa21AreasWeDeliverInPlaceC"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"delegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DeliveryAreasSceneDelegate","preciseIdentifier":"s:6Yababa26DeliveryAreasSceneDelegateP"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/DeliveryAreasViewController\/init(areasWeDeliverInPlaces:delegate:)","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/deliveryareasviewcontroller\/init(areaswedeliverinplaces:delegate:)"},"doc://com.yababaGmbH.yababa/documentation/Yababa/DeliveryAreasViewController/viewDidLoad()":{"role":"symbol","title":"viewDidLoad()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"viewDidLoad"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/DeliveryAreasViewController\/viewDidLoad()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"viewDidLoad"}],"url":"\/documentation\/yababa\/deliveryareasviewcontroller\/viewdidload()"},"doc://com.yababaGmbH.yababa/documentation/Yababa/DeliveryAreasViewController/pageControl":{"role":"symbol","title":"pageControl","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"pageControl"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIPageControl","preciseIdentifier":"c:objc(cs)UIPageControl"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/DeliveryAreasViewController\/pageControl","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"pageControl"}],"url":"\/documentation\/yababa\/deliveryareasviewcontroller\/pagecontrol"},"doc://com.yababaGmbH.yababa/documentation/Yababa/DeliveryAreasViewController/UICollectionViewDelegate-Implementations":{"role":"collectionGroup","title":"UICollectionViewDelegate Implementations","abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/DeliveryAreasViewController\/UICollectionViewDelegate-Implementations","kind":"article","type":"topic","url":"\/documentation\/yababa\/deliveryareasviewcontroller\/uicollectionviewdelegate-implementations"},"doc://com.yababaGmbH.yababa/documentation/Yababa/DeliveryAreasViewController/onGetNotified()":{"role":"symbol","title":"onGetNotified()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onGetNotified"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/DeliveryAreasViewController\/onGetNotified()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"onGetNotified"}],"url":"\/documentation\/yababa\/deliveryareasviewcontroller\/ongetnotified()"},"doc://com.yababaGmbH.yababa/objc(pl)UITraitEnvironment":{"type":"unresolvable","title":"UIKit.UITraitEnvironment","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)UITraitEnvironment"},"doc://com.yababaGmbH.yababa/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.yababaGmbH.yababa\/s28CustomDebugStringConvertibleP"},"doc://com.yababaGmbH.yababa/objc(pl)UIStateRestoring":{"type":"unresolvable","title":"UIKit.UIStateRestoring","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIStateRestoring"},"doc://com.yababaGmbH.yababa/documentation/Yababa/DeliveryAreasViewController/collectionView":{"role":"symbol","title":"collectionView","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"collectionView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UICollectionView","preciseIdentifier":"c:objc(cs)UICollectionView"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/DeliveryAreasViewController\/collectionView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"collectionView"}],"url":"\/documentation\/yababa\/deliveryareasviewcontroller\/collectionview"},"doc://com.yababaGmbH.yababa/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.yababaGmbH.yababa\/s23CustomStringConvertibleP"},"doc://com.yababaGmbH.yababa/objc(pl)UICollectionViewDelegate":{"type":"unresolvable","title":"UIKit.UICollectionViewDelegate","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)UICollectionViewDelegate"},"doc://com.yababaGmbH.yababa/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/com.yababaGmbH.yababa\/s8SendableP"},"doc://com.yababaGmbH.yababa/objc(pl)NSExtensionRequestHandling":{"type":"unresolvable","title":"Foundation.NSExtensionRequestHandling","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)NSExtensionRequestHandling"},"doc://com.yababaGmbH.yababa/objc(pl)UIPasteConfigurationSupporting":{"type":"unresolvable","title":"UIKit.UIPasteConfigurationSupporting","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIPasteConfigurationSupporting"},"doc://com.yababaGmbH.yababa/documentation/Yababa/DeliveryAreasViewController/onBack()":{"role":"symbol","title":"onBack()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onBack"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/DeliveryAreasViewController\/onBack()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"onBack"}],"url":"\/documentation\/yababa\/deliveryareasviewcontroller\/onback()"},"doc://com.yababaGmbH.yababa/objc(pl)UIUserActivityRestoring":{"type":"unresolvable","title":"UIKit.UIUserActivityRestoring","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIUserActivityRestoring"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"DeliveryAreasViewController"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"DeliveryAreasViewController"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"DeliveryAreasViewController"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/DeliveryAreasViewController\/collectionView","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/DeliveryAreasViewController\/getNotifiedBtn","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/DeliveryAreasViewController\/pageControl","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/DeliveryAreasViewController\/reEnterBtn","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/DeliveryAreasViewController\/titleLabel"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/DeliveryAreasViewController\/init(coder:)","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/DeliveryAreasViewController\/onBack()","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/DeliveryAreasViewController\/onGetNotified()","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/DeliveryAreasViewController\/onReEnter()","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/DeliveryAreasViewController\/viewDidLoad()"]},{"title":"Default Implementations","identifiers":["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/DeliveryAreasViewController\/UICollectionViewDataSource-Implementations","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/DeliveryAreasViewController\/UICollectionViewDelegate-Implementations"],"generated":true}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/MasterViewController"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"DeliveryAreasViewController"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/MasterViewController","preciseIdentifier":"c:@M@Yababa@objc(cs)MasterViewController","text":"MasterViewController"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1DeliveryAreasViewController~1init(coder:)\/title","value":"initWithCoder:"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1DeliveryAreasViewController~1init(coder:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithCoder:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1DeliveryAreasViewController~1reEnterBtn\/title","value":"reEnterBtn"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1DeliveryAreasViewController~1reEnterBtn\/fragments","value":[{"kind":"identifier","text":"reEnterBtn"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1DeliveryAreasViewController~1titleLabel\/title","value":"titleLabel"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1DeliveryAreasViewController~1titleLabel\/fragments","value":[{"kind":"identifier","text":"titleLabel"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1DeliveryAreasViewController~1getNotifiedBtn\/title","value":"getNotifiedBtn"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1DeliveryAreasViewController~1getNotifiedBtn\/fragments","value":[{"kind":"identifier","text":"getNotifiedBtn"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1DeliveryAreasViewController\/title","value":"DeliveryAreasViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1DeliveryAreasViewController\/fragments","value":[{"kind":"identifier","text":"DeliveryAreasViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1MasterViewController\/title","value":"MasterViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1MasterViewController\/fragments","value":[{"kind":"identifier","text":"MasterViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1DeliveryAreasViewController~1onReEnter()\/title","value":"onReEnter"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1DeliveryAreasViewController~1onReEnter()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onReEnter"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1DeliveryAreasViewController~1viewDidLoad()\/title","value":"viewDidLoad"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1DeliveryAreasViewController~1viewDidLoad()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"viewDidLoad"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1DeliveryAreasViewController~1pageControl\/title","value":"pageControl"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1DeliveryAreasViewController~1pageControl\/fragments","value":[{"kind":"identifier","text":"pageControl"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1DeliveryAreasViewController~1onGetNotified()\/title","value":"onGetNotified"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1DeliveryAreasViewController~1onGetNotified()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onGetNotified"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1DeliveryAreasViewController~1collectionView\/title","value":"collectionView"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1DeliveryAreasViewController~1collectionView\/fragments","value":[{"kind":"identifier","text":"collectionView"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1DeliveryAreasViewController~1onBack()\/title","value":"onBack"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1DeliveryAreasViewController~1onBack()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onBack"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}