{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HomeScreenInteractor"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/yababa\/homescreeninteractor"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/yababa\/homescreeninteractor"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.yababaGmbH.yababa\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/HomeScreenInteractorProtocol","doc:\/\/com.yababaGmbH.yababa\/objc(pl)NSObject","doc:\/\/com.yababaGmbH.yababa\/12SkeletonView17AssociatedObjectsP","doc:\/\/com.yababaGmbH.yababa\/s7CVarArgP","doc:\/\/com.yababaGmbH.yababa\/s28CustomDebugStringConvertibleP","doc:\/\/com.yababaGmbH.yababa\/s23CustomStringConvertibleP","doc:\/\/com.yababaGmbH.yababa\/SQ","doc:\/\/com.yababaGmbH.yababa\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/HomeScreenInteractor","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/HomeScreenInteractor\/viewController"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/HomeScreenInteractor\/fetchHomeScreenItems(completion:)","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/HomeScreenInteractor\/getGoogleSigninVisibility(completion:)","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/HomeScreenInteractor\/hasWalletCollectionInResponse()","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/HomeScreenInteractor\/synchronizeUserData()"]},{"title":"Default Implementations","identifiers":["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/HomeScreenInteractor\/HomeScreenInteractorProtocol-Implementations"],"generated":true}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HomeScreenInteractor"}],"title":"HomeScreenInteractor","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@Yababa@objc(cs)HomeScreenInteractor","modules":[{"name":"Yababa"}],"navigatorTitle":[{"kind":"identifier","text":"HomeScreenInteractor"}]},"hierarchy":{"paths":[["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa"]]},"references":{"doc://com.yababaGmbH.yababa/documentation/Yababa/HomeScreenInteractor/HomeScreenInteractorProtocol-Implementations":{"role":"collectionGroup","title":"HomeScreenInteractorProtocol Implementations","abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/HomeScreenInteractor\/HomeScreenInteractorProtocol-Implementations","kind":"article","type":"topic","url":"\/documentation\/yababa\/homescreeninteractor\/homescreeninteractorprotocol-implementations"},"doc://com.yababaGmbH.yababa/documentation/Yababa/HomeScreenInteractor/synchronizeUserData()":{"role":"symbol","title":"synchronizeUserData()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"synchronizeUserData"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/HomeScreenInteractor\/synchronizeUserData()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"synchronizeUserData"}],"url":"\/documentation\/yababa\/homescreeninteractor\/synchronizeuserdata()"},"doc://com.yababaGmbH.yababa/documentation/Yababa/HomeScreenInteractor/fetchHomeScreenItems(completion:)":{"role":"symbol","title":"fetchHomeScreenItems(completion:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"fetchHomeScreenItems"},{"kind":"text","text":"("},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": ("},{"kind":"typeIdentifier","text":"Result","preciseIdentifier":"s:s6ResultO"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"HomeScreenResponseBean","preciseIdentifier":"s:6Yababa22HomeScreenResponseBeanC"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":">) -> ())"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/HomeScreenInteractor\/fetchHomeScreenItems(completion:)","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/homescreeninteractor\/fetchhomescreenitems(completion:)"},"doc://com.yababaGmbH.yababa/documentation/Yababa/HomeScreenInteractor":{"role":"symbol","title":"HomeScreenInteractor","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HomeScreenInteractor"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/HomeScreenInteractor","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HomeScreenInteractor"}],"url":"\/documentation\/yababa\/homescreeninteractor"},"doc://com.yababaGmbH.yababa/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.yababaGmbH.yababa\/s7CVarArgP"},"doc://com.yababaGmbH.yababa/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.yababaGmbH.yababa\/SH"},"doc://com.yababaGmbH.yababa/documentation/Yababa/HomeScreenInteractorProtocol":{"role":"symbol","title":"HomeScreenInteractorProtocol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"HomeScreenInteractorProtocol"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/HomeScreenInteractorProtocol","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HomeScreenInteractorProtocol"}],"url":"\/documentation\/yababa\/homescreeninteractorprotocol"},"doc://com.yababaGmbH.yababa/documentation/Yababa/HomeScreenInteractor/init":{"role":"symbol","title":"init","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/HomeScreenInteractor\/init","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"init"}],"url":"\/documentation\/yababa\/homescreeninteractor\/init"},"doc://com.yababaGmbH.yababa/documentation/Yababa":{"role":"collection","title":"Yababa","abstract":[{"type":"text","text":"Getting Started"}],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa","kind":"symbol","type":"topic","url":"\/documentation\/yababa"},"doc://com.yababaGmbH.yababa/12SkeletonView17AssociatedObjectsP":{"type":"unresolvable","title":"SkeletonView.AssociatedObjects","identifier":"doc:\/\/com.yababaGmbH.yababa\/12SkeletonView17AssociatedObjectsP"},"doc://com.yababaGmbH.yababa/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.yababaGmbH.yababa\/SQ"},"doc://com.yababaGmbH.yababa/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.yababaGmbH.yababa\/s28CustomDebugStringConvertibleP"},"doc://com.yababaGmbH.yababa/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)NSObject"},"doc://com.yababaGmbH.yababa/documentation/Yababa/HomeScreenInteractor/viewController":{"role":"symbol","title":"viewController","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"viewController"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/HomeScreenInteractor\/viewController","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/homescreeninteractor\/viewcontroller"},"doc://com.yababaGmbH.yababa/documentation/Yababa/HomeScreenInteractor/getGoogleSigninVisibility(completion:)":{"role":"symbol","title":"getGoogleSigninVisibility(completion:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getGoogleSigninVisibility"},{"kind":"text","text":"("},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": ("},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/HomeScreenInteractor\/getGoogleSigninVisibility(completion:)","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/homescreeninteractor\/getgooglesigninvisibility(completion:)"},"doc://com.yababaGmbH.yababa/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.yababaGmbH.yababa\/s23CustomStringConvertibleP"},"doc://com.yababaGmbH.yababa/documentation/Yababa/HomeScreenInteractor/hasWalletCollectionInResponse()":{"role":"symbol","title":"hasWalletCollectionInResponse()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"hasWalletCollectionInResponse"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/HomeScreenInteractor\/hasWalletCollectionInResponse()","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/homescreeninteractor\/haswalletcollectioninresponse()"},"doc://com.yababaGmbH.yababa/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(cs)NSObject"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"HomeScreenInteractor"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"HomeScreenInteractor"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"HomeScreenInteractor"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/HomeScreenInteractor\/init","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/HomeScreenInteractor\/synchronizeUserData()"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.yababaGmbH.yababa\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"HomeScreenInteractor"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1HomeScreenInteractor~1synchronizeUserData()\/title","value":"synchronizeUserData"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1HomeScreenInteractor~1synchronizeUserData()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"synchronizeUserData"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1HomeScreenInteractor\/title","value":"HomeScreenInteractor"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1HomeScreenInteractor\/fragments","value":[{"kind":"identifier","text":"HomeScreenInteractor"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}