{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"InvalidAddressViewController"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/yababa\/invalidaddressviewcontroller"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/yababa\/invalidaddressviewcontroller"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.yababaGmbH.yababa\/objc(cs)UIViewController"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.yababaGmbH.yababa\/objc(pl)NSCoding","doc:\/\/com.yababaGmbH.yababa\/objc(pl)NSExtensionRequestHandling","doc:\/\/com.yababaGmbH.yababa\/objc(pl)NSObject","doc:\/\/com.yababaGmbH.yababa\/12SkeletonView17AssociatedObjectsP","doc:\/\/com.yababaGmbH.yababa\/s7CVarArgP","doc:\/\/com.yababaGmbH.yababa\/s28CustomDebugStringConvertibleP","doc:\/\/com.yababaGmbH.yababa\/s23CustomStringConvertibleP","doc:\/\/com.yababaGmbH.yababa\/SQ","doc:\/\/com.yababaGmbH.yababa\/SH","doc:\/\/com.yababaGmbH.yababa\/s8SendableP","doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIActivityItemsConfigurationProviding","doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIAppearanceContainer","doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIContentContainer","doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIFocusEnvironment","doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIPasteConfigurationSupporting","doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIResponderStandardEditActions","doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIStateRestoring","doc:\/\/com.yababaGmbH.yababa\/objc(pl)UITraitEnvironment","doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIUserActivityRestoring"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/InvalidAddressViewController","interfaceLanguage":"swift"},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/InvalidAddressViewController\/init(addressValidationResponse:)","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/InvalidAddressViewController\/init(coder:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/InvalidAddressViewController\/cancelBtn","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/InvalidAddressViewController\/delegate","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/InvalidAddressViewController\/getNotifiedBtn","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/InvalidAddressViewController\/subTitleLabel","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/InvalidAddressViewController\/titleLabel","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/InvalidAddressViewController\/viewAreasBtn","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/InvalidAddressViewController\/viewAreasBtnContainer"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/InvalidAddressViewController\/onCancel()","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/InvalidAddressViewController\/onNotifyForAddress()","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/InvalidAddressViewController\/onViewAreas()","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/InvalidAddressViewController\/refresh()","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/InvalidAddressViewController\/setLocalizationStrings()","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/InvalidAddressViewController\/viewDidLoad()"]}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"InvalidAddressViewController"}],"title":"InvalidAddressViewController","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@Yababa@objc(cs)InvalidAddressViewController","modules":[{"name":"Yababa"}],"navigatorTitle":[{"kind":"identifier","text":"InvalidAddressViewController"}]},"hierarchy":{"paths":[["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa"]]},"references":{"doc://com.yababaGmbH.yababa/objc(cs)UIViewController":{"type":"unresolvable","title":"UIViewController","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(cs)UIViewController"},"doc://com.yababaGmbH.yababa/objc(pl)UIActivityItemsConfigurationProviding":{"type":"unresolvable","title":"UIKit.UIActivityItemsConfigurationProviding","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIActivityItemsConfigurationProviding"},"doc://com.yababaGmbH.yababa/documentation/Yababa/InvalidAddressViewController/init(addressValidationResponse:)":{"role":"symbol","title":"init(addressValidationResponse:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"addressValidationResponse"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AddressValidationResponse","preciseIdentifier":"s:6Yababa25AddressValidationResponseC"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/InvalidAddressViewController\/init(addressValidationResponse:)","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/invalidaddressviewcontroller\/init(addressvalidationresponse:)"},"doc://com.yababaGmbH.yababa/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.yababaGmbH.yababa\/SH"},"doc://com.yababaGmbH.yababa/objc(pl)UIFocusEnvironment":{"type":"unresolvable","title":"UIKit.UIFocusEnvironment","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIFocusEnvironment"},"doc://com.yababaGmbH.yababa/12SkeletonView17AssociatedObjectsP":{"type":"unresolvable","title":"SkeletonView.AssociatedObjects","identifier":"doc:\/\/com.yababaGmbH.yababa\/12SkeletonView17AssociatedObjectsP"},"doc://com.yababaGmbH.yababa/documentation/Yababa/InvalidAddressViewController/titleLabel":{"role":"symbol","title":"titleLabel","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"titleLabel"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UILabel","preciseIdentifier":"c:objc(cs)UILabel"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/InvalidAddressViewController\/titleLabel","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"titleLabel"}],"url":"\/documentation\/yababa\/invalidaddressviewcontroller\/titlelabel"},"doc://com.yababaGmbH.yababa/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.yababaGmbH.yababa\/SQ"},"doc://com.yababaGmbH.yababa/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)NSObject"},"doc://com.yababaGmbH.yababa/documentation/Yababa/InvalidAddressViewController/refresh()":{"role":"symbol","title":"refresh()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"refresh"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/InvalidAddressViewController\/refresh()","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/invalidaddressviewcontroller\/refresh()"},"doc://com.yababaGmbH.yababa/objc(pl)UIContentContainer":{"type":"unresolvable","title":"UIKit.UIContentContainer","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIContentContainer"},"doc://com.yababaGmbH.yababa/documentation/Yababa/InvalidAddressViewController/cancelBtn":{"role":"symbol","title":"cancelBtn","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"cancelBtn"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIButton","preciseIdentifier":"c:objc(cs)UIButton"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/InvalidAddressViewController\/cancelBtn","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"cancelBtn"}],"url":"\/documentation\/yababa\/invalidaddressviewcontroller\/cancelbtn"},"doc://com.yababaGmbH.yababa/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.yababaGmbH.yababa\/s23CustomStringConvertibleP"},"doc://com.yababaGmbH.yababa/objc(pl)UIStateRestoring":{"type":"unresolvable","title":"UIKit.UIStateRestoring","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIStateRestoring"},"doc://com.yababaGmbH.yababa/objc(pl)UIPasteConfigurationSupporting":{"type":"unresolvable","title":"UIKit.UIPasteConfigurationSupporting","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIPasteConfigurationSupporting"},"doc://com.yababaGmbH.yababa/objc(pl)UIAppearanceContainer":{"type":"unresolvable","title":"UIKit.UIAppearanceContainer","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIAppearanceContainer"},"doc://com.yababaGmbH.yababa/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.yababaGmbH.yababa\/s28CustomDebugStringConvertibleP"},"doc://com.yababaGmbH.yababa/documentation/Yababa/InvalidAddressViewController/subTitleLabel":{"role":"symbol","title":"subTitleLabel","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"subTitleLabel"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UILabel","preciseIdentifier":"c:objc(cs)UILabel"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/InvalidAddressViewController\/subTitleLabel","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"subTitleLabel"}],"url":"\/documentation\/yababa\/invalidaddressviewcontroller\/subtitlelabel"},"doc://com.yababaGmbH.yababa/documentation/Yababa/InvalidAddressViewController/viewAreasBtnContainer":{"role":"symbol","title":"viewAreasBtnContainer","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"viewAreasBtnContainer"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/InvalidAddressViewController\/viewAreasBtnContainer","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"viewAreasBtnContainer"}],"url":"\/documentation\/yababa\/invalidaddressviewcontroller\/viewareasbtncontainer"},"doc://com.yababaGmbH.yababa/documentation/Yababa/InvalidAddressViewController/viewDidLoad()":{"role":"symbol","title":"viewDidLoad()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"viewDidLoad"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/InvalidAddressViewController\/viewDidLoad()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"viewDidLoad"}],"url":"\/documentation\/yababa\/invalidaddressviewcontroller\/viewdidload()"},"doc://com.yababaGmbH.yababa/documentation/Yababa/InvalidAddressViewController/getNotifiedBtn":{"role":"symbol","title":"getNotifiedBtn","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"getNotifiedBtn"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIButton","preciseIdentifier":"c:objc(cs)UIButton"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/InvalidAddressViewController\/getNotifiedBtn","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"getNotifiedBtn"}],"url":"\/documentation\/yababa\/invalidaddressviewcontroller\/getnotifiedbtn"},"doc://com.yababaGmbH.yababa/documentation/Yababa/InvalidAddressViewController/setLocalizationStrings()":{"role":"symbol","title":"setLocalizationStrings()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setLocalizationStrings"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/InvalidAddressViewController\/setLocalizationStrings()","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/invalidaddressviewcontroller\/setlocalizationstrings()"},"doc://com.yababaGmbH.yababa/objc(pl)UITraitEnvironment":{"type":"unresolvable","title":"UIKit.UITraitEnvironment","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)UITraitEnvironment"},"doc://com.yababaGmbH.yababa/documentation/Yababa/InvalidAddressViewController/delegate":{"role":"symbol","title":"delegate","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"delegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"InvalidAddressSelectionDelegate","preciseIdentifier":"s:6Yababa31InvalidAddressSelectionDelegateP"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/InvalidAddressViewController\/delegate","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/invalidaddressviewcontroller\/delegate"},"doc://com.yababaGmbH.yababa/documentation/Yababa/InvalidAddressViewController/onViewAreas()":{"role":"symbol","title":"onViewAreas()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onViewAreas"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/InvalidAddressViewController\/onViewAreas()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"onViewAreas"}],"url":"\/documentation\/yababa\/invalidaddressviewcontroller\/onviewareas()"},"doc://com.yababaGmbH.yababa/objc(pl)UIResponderStandardEditActions":{"type":"unresolvable","title":"UIKit.UIResponderStandardEditActions","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIResponderStandardEditActions"},"doc://com.yababaGmbH.yababa/documentation/Yababa/InvalidAddressViewController/init(coder:)":{"role":"symbol","title":"init(coder:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"coder"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSCoder","preciseIdentifier":"c:objc(cs)NSCoder"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/InvalidAddressViewController\/init(coder:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithCoder:"}],"url":"\/documentation\/yababa\/invalidaddressviewcontroller\/init(coder:)"},"doc://com.yababaGmbH.yababa/objc(pl)NSCoding":{"type":"unresolvable","title":"Foundation.NSCoding","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)NSCoding"},"doc://com.yababaGmbH.yababa/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.yababaGmbH.yababa\/s7CVarArgP"},"doc://com.yababaGmbH.yababa/objc(pl)UIUserActivityRestoring":{"type":"unresolvable","title":"UIKit.UIUserActivityRestoring","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIUserActivityRestoring"},"doc://com.yababaGmbH.yababa/documentation/Yababa/InvalidAddressViewController/onCancel()":{"role":"symbol","title":"onCancel()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onCancel"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/InvalidAddressViewController\/onCancel()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"onCancel"}],"url":"\/documentation\/yababa\/invalidaddressviewcontroller\/oncancel()"},"doc://com.yababaGmbH.yababa/documentation/Yababa/InvalidAddressViewController/onNotifyForAddress()":{"role":"symbol","title":"onNotifyForAddress()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onNotifyForAddress"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/InvalidAddressViewController\/onNotifyForAddress()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"onNotifyForAddress"}],"url":"\/documentation\/yababa\/invalidaddressviewcontroller\/onnotifyforaddress()"},"doc://com.yababaGmbH.yababa/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/com.yababaGmbH.yababa\/s8SendableP"},"doc://com.yababaGmbH.yababa/objc(pl)NSExtensionRequestHandling":{"type":"unresolvable","title":"Foundation.NSExtensionRequestHandling","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)NSExtensionRequestHandling"},"doc://com.yababaGmbH.yababa/documentation/Yababa/InvalidAddressViewController/viewAreasBtn":{"role":"symbol","title":"viewAreasBtn","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"viewAreasBtn"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIButton","preciseIdentifier":"c:objc(cs)UIButton"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/InvalidAddressViewController\/viewAreasBtn","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"viewAreasBtn"}],"url":"\/documentation\/yababa\/invalidaddressviewcontroller\/viewareasbtn"},"doc://com.yababaGmbH.yababa/documentation/Yababa":{"role":"collection","title":"Yababa","abstract":[{"type":"text","text":"Getting Started"}],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa","kind":"symbol","type":"topic","url":"\/documentation\/yababa"},"doc://com.yababaGmbH.yababa/documentation/Yababa/InvalidAddressViewController":{"role":"symbol","title":"InvalidAddressViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"InvalidAddressViewController"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/InvalidAddressViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"InvalidAddressViewController"}],"url":"\/documentation\/yababa\/invalidaddressviewcontroller"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"InvalidAddressViewController"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"InvalidAddressViewController"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"InvalidAddressViewController"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/InvalidAddressViewController\/cancelBtn","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/InvalidAddressViewController\/getNotifiedBtn","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/InvalidAddressViewController\/subTitleLabel","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/InvalidAddressViewController\/titleLabel","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/InvalidAddressViewController\/viewAreasBtn","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/InvalidAddressViewController\/viewAreasBtnContainer"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/InvalidAddressViewController\/init(coder:)","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/InvalidAddressViewController\/onCancel()","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/InvalidAddressViewController\/onNotifyForAddress()","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/InvalidAddressViewController\/onViewAreas()","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/InvalidAddressViewController\/viewDidLoad()"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.yababaGmbH.yababa\/objc(cs)UIViewController"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"InvalidAddressViewController"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1InvalidAddressViewController~1titleLabel\/title","value":"titleLabel"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1InvalidAddressViewController~1titleLabel\/fragments","value":[{"kind":"identifier","text":"titleLabel"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1InvalidAddressViewController~1cancelBtn\/title","value":"cancelBtn"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1InvalidAddressViewController~1cancelBtn\/fragments","value":[{"kind":"identifier","text":"cancelBtn"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1InvalidAddressViewController~1subTitleLabel\/title","value":"subTitleLabel"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1InvalidAddressViewController~1subTitleLabel\/fragments","value":[{"kind":"identifier","text":"subTitleLabel"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1InvalidAddressViewController~1viewAreasBtnContainer\/title","value":"viewAreasBtnContainer"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1InvalidAddressViewController~1viewAreasBtnContainer\/fragments","value":[{"kind":"identifier","text":"viewAreasBtnContainer"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1InvalidAddressViewController~1viewDidLoad()\/title","value":"viewDidLoad"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1InvalidAddressViewController~1viewDidLoad()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"viewDidLoad"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1InvalidAddressViewController~1getNotifiedBtn\/title","value":"getNotifiedBtn"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1InvalidAddressViewController~1getNotifiedBtn\/fragments","value":[{"kind":"identifier","text":"getNotifiedBtn"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1InvalidAddressViewController~1onViewAreas()\/title","value":"onViewAreas"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1InvalidAddressViewController~1onViewAreas()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onViewAreas"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1InvalidAddressViewController~1init(coder:)\/title","value":"initWithCoder:"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1InvalidAddressViewController~1init(coder:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithCoder:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1InvalidAddressViewController~1onCancel()\/title","value":"onCancel"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1InvalidAddressViewController~1onCancel()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onCancel"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1InvalidAddressViewController~1onNotifyForAddress()\/title","value":"onNotifyForAddress"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1InvalidAddressViewController~1onNotifyForAddress()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onNotifyForAddress"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1InvalidAddressViewController~1viewAreasBtn\/title","value":"viewAreasBtn"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1InvalidAddressViewController~1viewAreasBtn\/fragments","value":[{"kind":"identifier","text":"viewAreasBtn"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1InvalidAddressViewController\/title","value":"InvalidAddressViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1InvalidAddressViewController\/fragments","value":[{"kind":"identifier","text":"InvalidAddressViewController"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}