{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"kOpenUDIDErrorCompromised"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/yababa\/kopenudiderrorcompromised"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/yababa\/kopenudiderrorcompromised"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/kOpenUDIDErrorCompromised","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"kOpenUDIDErrorCompromised"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"title":"kOpenUDIDErrorCompromised","roleHeading":"Global Variable","role":"symbol","symbolKind":"var","externalID":"c:OpenUDID.h@1619@macro@kOpenUDIDErrorCompromised","modules":[{"name":"Yababa"}],"navigatorTitle":[{"kind":"identifier","text":"kOpenUDIDErrorCompromised"}]},"hierarchy":{"paths":[["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa"]]},"references":{"doc://com.yababaGmbH.yababa/documentation/Yababa":{"role":"collection","title":"Yababa","abstract":[{"type":"text","text":"Getting Started"}],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa","kind":"symbol","type":"topic","url":"\/documentation\/yababa"},"doc://com.yababaGmbH.yababa/documentation/Yababa/kOpenUDIDErrorCompromised":{"role":"symbol","title":"kOpenUDIDErrorCompromised","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"kOpenUDIDErrorCompromised"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/kOpenUDIDErrorCompromised","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"kOpenUDIDErrorCompromised"}],"url":"\/documentation\/yababa\/kopenudiderrorcompromised"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Macro"},{"op":"replace","path":"\/metadata\/title","value":"kOpenUDIDErrorCompromised"},{"op":"replace","path":"\/metadata\/symbolKind","value":"macro"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"#define"},{"kind":"text","text":" "},{"kind":"identifier","text":"kOpenUDIDErrorCompromised"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1kOpenUDIDErrorCompromised\/title","value":"kOpenUDIDErrorCompromised"}],"traits":[{"interfaceLanguage":"occ"}]}]}