{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"LocalFileDataStore"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/yababa\/localfiledatastore"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/yababa\/localfiledatastore"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.yababaGmbH.yababa\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/LocalDataStore","doc:\/\/com.yababaGmbH.yababa\/objc(pl)NSObject","doc:\/\/com.yababaGmbH.yababa\/12SkeletonView17AssociatedObjectsP","doc:\/\/com.yababaGmbH.yababa\/s7CVarArgP","doc:\/\/com.yababaGmbH.yababa\/s28CustomDebugStringConvertibleP","doc:\/\/com.yababaGmbH.yababa\/s23CustomStringConvertibleP","doc:\/\/com.yababaGmbH.yababa\/SQ","doc:\/\/com.yababaGmbH.yababa\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/LocalFileDataStore","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/LocalFileDataStore\/cartFile","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/LocalFileDataStore\/catalogueFile"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/LocalFileDataStore\/clearCart()","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/LocalFileDataStore\/clearCatalogue()","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/LocalFileDataStore\/getCart()","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/LocalFileDataStore\/getCatalogue()","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/LocalFileDataStore\/printDocumentLocation()","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/LocalFileDataStore\/saveCatalogue(_:)","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/LocalFileDataStore\/updateCart(_:)"]}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"LocalFileDataStore"}],"title":"LocalFileDataStore","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@Yababa@objc(cs)LocalFileDataStore","modules":[{"name":"Yababa"}],"navigatorTitle":[{"kind":"identifier","text":"LocalFileDataStore"}]},"hierarchy":{"paths":[["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa"]]},"references":{"doc://com.yababaGmbH.yababa/documentation/Yababa/LocalFileDataStore/getCatalogue()":{"role":"symbol","title":"getCatalogue()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getCatalogue"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"Catalogue","preciseIdentifier":"s:6Yababa9Cataloguea"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/LocalFileDataStore\/getCatalogue()","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/localfiledatastore\/getcatalogue()"},"doc://com.yababaGmbH.yababa/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.yababaGmbH.yababa\/SH"},"doc://com.yababaGmbH.yababa/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.yababaGmbH.yababa\/s28CustomDebugStringConvertibleP"},"doc://com.yababaGmbH.yababa/documentation/Yababa/LocalFileDataStore":{"role":"symbol","title":"LocalFileDataStore","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"LocalFileDataStore"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/LocalFileDataStore","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"LocalFileDataStore"}],"url":"\/documentation\/yababa\/localfiledatastore"},"doc://com.yababaGmbH.yababa/documentation/Yababa/LocalFileDataStore/updateCart(_:)":{"role":"symbol","title":"updateCart(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"updateCart"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Cart","preciseIdentifier":"s:6Yababa4Carta"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/LocalFileDataStore\/updateCart(_:)","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/localfiledatastore\/updatecart(_:)"},"doc://com.yababaGmbH.yababa/documentation/Yababa":{"role":"collection","title":"Yababa","abstract":[{"type":"text","text":"Getting Started"}],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa","kind":"symbol","type":"topic","url":"\/documentation\/yababa"},"doc://com.yababaGmbH.yababa/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(cs)NSObject"},"doc://com.yababaGmbH.yababa/documentation/Yababa/LocalDataStore":{"role":"symbol","title":"LocalDataStore","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"LocalDataStore"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/LocalDataStore","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"LocalDataStore"}],"url":"\/documentation\/yababa\/localdatastore"},"doc://com.yababaGmbH.yababa/documentation/Yababa/LocalFileDataStore/clearCatalogue()":{"role":"symbol","title":"clearCatalogue()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"clearCatalogue"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/LocalFileDataStore\/clearCatalogue()","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/localfiledatastore\/clearcatalogue()"},"doc://com.yababaGmbH.yababa/documentation/Yababa/LocalFileDataStore/printDocumentLocation()":{"role":"symbol","title":"printDocumentLocation()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"printDocumentLocation"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/LocalFileDataStore\/printDocumentLocation()","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/localfiledatastore\/printdocumentlocation()"},"doc://com.yababaGmbH.yababa/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.yababaGmbH.yababa\/s7CVarArgP"},"doc://com.yababaGmbH.yababa/12SkeletonView17AssociatedObjectsP":{"type":"unresolvable","title":"SkeletonView.AssociatedObjects","identifier":"doc:\/\/com.yababaGmbH.yababa\/12SkeletonView17AssociatedObjectsP"},"doc://com.yababaGmbH.yababa/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.yababaGmbH.yababa\/s23CustomStringConvertibleP"},"doc://com.yababaGmbH.yababa/documentation/Yababa/LocalFileDataStore/cartFile":{"role":"symbol","title":"cartFile","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"cartFile"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/LocalFileDataStore\/cartFile","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/localfiledatastore\/cartfile"},"doc://com.yababaGmbH.yababa/documentation/Yababa/LocalFileDataStore/init":{"role":"symbol","title":"init","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/LocalFileDataStore\/init","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"init"}],"url":"\/documentation\/yababa\/localfiledatastore\/init"},"doc://com.yababaGmbH.yababa/documentation/Yababa/LocalFileDataStore/getCart()":{"role":"symbol","title":"getCart()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getCart"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"Cart","preciseIdentifier":"s:6Yababa4Carta"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/LocalFileDataStore\/getCart()","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/localfiledatastore\/getcart()"},"doc://com.yababaGmbH.yababa/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.yababaGmbH.yababa\/SQ"},"doc://com.yababaGmbH.yababa/documentation/Yababa/LocalFileDataStore/catalogueFile":{"role":"symbol","title":"catalogueFile","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"catalogueFile"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/LocalFileDataStore\/catalogueFile","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/localfiledatastore\/cataloguefile"},"doc://com.yababaGmbH.yababa/documentation/Yababa/LocalFileDataStore/clearCart()":{"role":"symbol","title":"clearCart()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"clearCart"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/LocalFileDataStore\/clearCart()","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/localfiledatastore\/clearcart()"},"doc://com.yababaGmbH.yababa/documentation/Yababa/LocalFileDataStore/saveCatalogue(_:)":{"role":"symbol","title":"saveCatalogue(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"saveCatalogue"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Catalogue","preciseIdentifier":"s:6Yababa9Cataloguea"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/LocalFileDataStore\/saveCatalogue(_:)","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/localfiledatastore\/savecatalogue(_:)"},"doc://com.yababaGmbH.yababa/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)NSObject"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"LocalFileDataStore"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"LocalFileDataStore"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"LocalFileDataStore"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/LocalFileDataStore\/init"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.yababaGmbH.yababa\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"LocalFileDataStore"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1LocalFileDataStore\/title","value":"LocalFileDataStore"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1LocalFileDataStore\/fragments","value":[{"kind":"identifier","text":"LocalFileDataStore"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}