{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"LoginResponseClass"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/yababa\/loginresponseclass"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/yababa\/loginresponseclass"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ResponseClass"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.yababaGmbH.yababa\/objc(pl)NSCoding","doc:\/\/com.yababaGmbH.yababa\/objc(pl)NSObject","doc:\/\/com.yababaGmbH.yababa\/12SkeletonView17AssociatedObjectsP","doc:\/\/com.yababaGmbH.yababa\/s7CVarArgP","doc:\/\/com.yababaGmbH.yababa\/s28CustomDebugStringConvertibleP","doc:\/\/com.yababaGmbH.yababa\/s23CustomStringConvertibleP","doc:\/\/com.yababaGmbH.yababa\/SQ","doc:\/\/com.yababaGmbH.yababa\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/LoginResponseClass","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/LoginResponseClass\/messageToDisplay","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/LoginResponseClass\/profile","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/LoginResponseClass\/token"]}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"LoginResponseClass"}],"title":"LoginResponseClass","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:objc(cs)LoginResponseClass","modules":[{"name":"Yababa"}],"navigatorTitle":[{"kind":"identifier","text":"LoginResponseClass"}]},"hierarchy":{"paths":[["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa"]]},"references":{"doc://com.yababaGmbH.yababa/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.yababaGmbH.yababa\/s28CustomDebugStringConvertibleP"},"doc://com.yababaGmbH.yababa/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.yababaGmbH.yababa\/SH"},"doc://com.yababaGmbH.yababa/documentation/Yababa/ResponseClass":{"role":"symbol","title":"ResponseClass","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ResponseClass"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ResponseClass","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ResponseClass"}],"url":"\/documentation\/yababa\/responseclass"},"doc://com.yababaGmbH.yababa/documentation/Yababa":{"role":"collection","title":"Yababa","abstract":[{"type":"text","text":"Getting Started"}],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa","kind":"symbol","type":"topic","url":"\/documentation\/yababa"},"doc://com.yababaGmbH.yababa/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.yababaGmbH.yababa\/s23CustomStringConvertibleP"},"doc://com.yababaGmbH.yababa/objc(pl)NSCoding":{"type":"unresolvable","title":"Foundation.NSCoding","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)NSCoding"},"doc://com.yababaGmbH.yababa/12SkeletonView17AssociatedObjectsP":{"type":"unresolvable","title":"SkeletonView.AssociatedObjects","identifier":"doc:\/\/com.yababaGmbH.yababa\/12SkeletonView17AssociatedObjectsP"},"doc://com.yababaGmbH.yababa/documentation/Yababa/LoginResponseClass":{"role":"symbol","title":"LoginResponseClass","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"LoginResponseClass"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/LoginResponseClass","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"LoginResponseClass"}],"url":"\/documentation\/yababa\/loginresponseclass"},"doc://com.yababaGmbH.yababa/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)NSObject"},"doc://com.yababaGmbH.yababa/documentation/Yababa/LoginResponseClass/messageToDisplay":{"role":"symbol","title":"messageToDisplay","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"messageToDisplay"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/LoginResponseClass\/messageToDisplay","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"messageToDisplay"}],"url":"\/documentation\/yababa\/loginresponseclass\/messagetodisplay"},"doc://com.yababaGmbH.yababa/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.yababaGmbH.yababa\/s7CVarArgP"},"doc://com.yababaGmbH.yababa/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.yababaGmbH.yababa\/SQ"},"doc://com.yababaGmbH.yababa/documentation/Yababa/LoginResponseClass/profile":{"role":"symbol","title":"profile","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"profile"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ProfileClass","preciseIdentifier":"c:objc(cs)ProfileClass"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/LoginResponseClass\/profile","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"profile"}],"url":"\/documentation\/yababa\/loginresponseclass\/profile"},"doc://com.yababaGmbH.yababa/documentation/Yababa/LoginResponseClass/token":{"role":"symbol","title":"token","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"token"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/LoginResponseClass\/token","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"token"}],"url":"\/documentation\/yababa\/loginresponseclass\/token"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"LoginResponseClass"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"LoginResponseClass"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"LoginResponseClass"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/LoginResponseClass\/messageToDisplay","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/LoginResponseClass\/profile","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/LoginResponseClass\/token"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ResponseClass"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"LoginResponseClass"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ResponseClass","preciseIdentifier":"c:objc(cs)ResponseClass","text":"ResponseClass"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1ResponseClass\/title","value":"ResponseClass"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1ResponseClass\/fragments","value":[{"kind":"identifier","text":"ResponseClass"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1LoginResponseClass\/title","value":"LoginResponseClass"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1LoginResponseClass\/fragments","value":[{"kind":"identifier","text":"LoginResponseClass"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1LoginResponseClass~1messageToDisplay\/title","value":"messageToDisplay"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1LoginResponseClass~1messageToDisplay\/fragments","value":[{"kind":"identifier","text":"messageToDisplay"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1LoginResponseClass~1profile\/title","value":"profile"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1LoginResponseClass~1profile\/fragments","value":[{"kind":"identifier","text":"profile"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1LoginResponseClass~1token\/title","value":"token"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1LoginResponseClass~1token\/fragments","value":[{"kind":"identifier","text":"token"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}