{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"OrderDetailsSceneViewController"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/yababa\/orderdetailssceneviewcontroller"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/yababa\/orderdetailssceneviewcontroller"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/MasterViewController"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.yababaGmbH.yababa\/objc(pl)NSCoding","doc:\/\/com.yababaGmbH.yababa\/objc(pl)NSExtensionRequestHandling","doc:\/\/com.yababaGmbH.yababa\/objc(pl)NSObject","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/OrderDetailsSceneViewControllerProtocol","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/OrderProductsDatasourceSelection","doc:\/\/com.yababaGmbH.yababa\/12SkeletonView17AssociatedObjectsP","doc:\/\/com.yababaGmbH.yababa\/s7CVarArgP","doc:\/\/com.yababaGmbH.yababa\/s28CustomDebugStringConvertibleP","doc:\/\/com.yababaGmbH.yababa\/s23CustomStringConvertibleP","doc:\/\/com.yababaGmbH.yababa\/SQ","doc:\/\/com.yababaGmbH.yababa\/SH","doc:\/\/com.yababaGmbH.yababa\/s8SendableP","doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIActivityItemsConfigurationProviding","doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIAppearanceContainer","doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIContentContainer","doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIFocusEnvironment","doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIPasteConfigurationSupporting","doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIResponderStandardEditActions","doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIStateRestoring","doc:\/\/com.yababaGmbH.yababa\/objc(pl)UITraitEnvironment","doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIUserActivityRestoring"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/OrderDetailsSceneViewController","interfaceLanguage":"swift"},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/OrderDetailsSceneViewController\/init(coder:)","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/OrderDetailsSceneViewController\/init(idOrder:showCustomBackBtn:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/OrderDetailsSceneViewController\/addressLabel","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/OrderDetailsSceneViewController\/backupTitleLabel","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/OrderDetailsSceneViewController\/customNavbar","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/OrderDetailsSceneViewController\/deliveryAddressLabel","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/OrderDetailsSceneViewController\/deliveryETAContainer","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/OrderDetailsSceneViewController\/deliveryETALabel","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/OrderDetailsSceneViewController\/deliveryFeeLabel","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/OrderDetailsSceneViewController\/deliveryFeeTextLabel","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/OrderDetailsSceneViewController\/deliveryWindowDateLabel","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/OrderDetailsSceneViewController\/deliveryWindowTimeLabel","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/OrderDetailsSceneViewController\/discountLabel","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/OrderDetailsSceneViewController\/discountStackView","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/OrderDetailsSceneViewController\/discountTextLabel","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/OrderDetailsSceneViewController\/interactor","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/OrderDetailsSceneViewController\/mapView","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/OrderDetailsSceneViewController\/orderDetailsImage","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/OrderDetailsSceneViewController\/orderDetailsSubTitle","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/OrderDetailsSceneViewController\/orderDetailsTrackOrderBtn","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/OrderDetailsSceneViewController\/orderDetailsTrackOrderContainer","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/OrderDetailsSceneViewController\/orderInfoDetailsView","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/OrderDetailsSceneViewController\/orderNumberLabel","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/OrderDetailsSceneViewController\/orderNumberRefLabel","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/OrderDetailsSceneViewController\/orderOverViewContainerView","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/OrderDetailsSceneViewController\/orderOverviewTextLabel","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/OrderDetailsSceneViewController\/orderPriceInfoView","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/OrderDetailsSceneViewController\/orderProductsCountLabel","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/OrderDetailsSceneViewController\/orderProductsTableView","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/OrderDetailsSceneViewController\/orderProductsTableViewHeightConstraint","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/OrderDetailsSceneViewController\/orderStatusContainerView","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/OrderDetailsSceneViewController\/orderStatusTableView","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/OrderDetailsSceneViewController\/orderStatusTableViewHeightConstraint","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/OrderDetailsSceneViewController\/reorderButton","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/OrderDetailsSceneViewController\/router","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/OrderDetailsSceneViewController\/subTotalLabel","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/OrderDetailsSceneViewController\/subTotalTextLabel","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/OrderDetailsSceneViewController\/totalLabel","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/OrderDetailsSceneViewController\/totalTextLabel"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/OrderDetailsSceneViewController\/addSameProductsToCart(_:)","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/OrderDetailsSceneViewController\/setupUI()","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/OrderDetailsSceneViewController\/showLocalizedStrings()","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/OrderDetailsSceneViewController\/trackUserOrder(_:)","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/OrderDetailsSceneViewController\/viewDidLoad()","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/OrderDetailsSceneViewController\/viewWillAppear(_:)","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/OrderDetailsSceneViewController\/viewWillDisappear(_:)"]},{"title":"Default Implementations","identifiers":["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/OrderDetailsSceneViewController\/OrderDetailsSceneViewControllerProtocol-Implementations","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/OrderDetailsSceneViewController\/OrderProductsDatasourceSelection-Implementations"],"generated":true}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"OrderDetailsSceneViewController"}],"title":"OrderDetailsSceneViewController","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@Yababa@objc(cs)OrderDetailsSceneViewController","modules":[{"name":"Yababa"}],"navigatorTitle":[{"kind":"identifier","text":"OrderDetailsSceneViewController"}]},"hierarchy":{"paths":[["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa"]]},"references":{"doc://com.yababaGmbH.yababa/documentation/Yababa/OrderDetailsSceneViewController/viewDidLoad()":{"role":"symbol","title":"viewDidLoad()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"viewDidLoad"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/OrderDetailsSceneViewController\/viewDidLoad()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"viewDidLoad"}],"url":"\/documentation\/yababa\/orderdetailssceneviewcontroller\/viewdidload()"},"doc://com.yababaGmbH.yababa/documentation/Yababa/OrderDetailsSceneViewController/orderProductsTableView":{"role":"symbol","title":"orderProductsTableView","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"orderProductsTableView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UITableView","preciseIdentifier":"c:objc(cs)UITableView"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/OrderDetailsSceneViewController\/orderProductsTableView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"orderProductsTableView"}],"url":"\/documentation\/yababa\/orderdetailssceneviewcontroller\/orderproductstableview"},"doc://com.yababaGmbH.yababa/documentation/Yababa/OrderDetailsSceneViewController/deliveryFeeTextLabel":{"role":"symbol","title":"deliveryFeeTextLabel","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"deliveryFeeTextLabel"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UILabel","preciseIdentifier":"c:objc(cs)UILabel"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/OrderDetailsSceneViewController\/deliveryFeeTextLabel","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"deliveryFeeTextLabel"}],"url":"\/documentation\/yababa\/orderdetailssceneviewcontroller\/deliveryfeetextlabel"},"doc://com.yababaGmbH.yababa/documentation/Yababa/OrderDetailsSceneViewController/orderProductsCountLabel":{"role":"symbol","title":"orderProductsCountLabel","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"orderProductsCountLabel"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UILabel","preciseIdentifier":"c:objc(cs)UILabel"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/OrderDetailsSceneViewController\/orderProductsCountLabel","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"orderProductsCountLabel"}],"url":"\/documentation\/yababa\/orderdetailssceneviewcontroller\/orderproductscountlabel"},"doc://com.yababaGmbH.yababa/documentation/Yababa/OrderDetailsSceneViewController/orderOverviewTextLabel":{"role":"symbol","title":"orderOverviewTextLabel","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"orderOverviewTextLabel"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UILabel","preciseIdentifier":"c:objc(cs)UILabel"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/OrderDetailsSceneViewController\/orderOverviewTextLabel","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"orderOverviewTextLabel"}],"url":"\/documentation\/yababa\/orderdetailssceneviewcontroller\/orderoverviewtextlabel"},"doc://com.yababaGmbH.yababa/documentation/Yababa":{"role":"collection","title":"Yababa","abstract":[{"type":"text","text":"Getting Started"}],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa","kind":"symbol","type":"topic","url":"\/documentation\/yababa"},"doc://com.yababaGmbH.yababa/documentation/Yababa/OrderDetailsSceneViewController/setupUI()":{"role":"symbol","title":"setupUI()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setupUI"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/OrderDetailsSceneViewController\/setupUI()","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/orderdetailssceneviewcontroller\/setupui()"},"doc://com.yababaGmbH.yababa/documentation/Yababa/MasterViewController":{"role":"symbol","title":"MasterViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MasterViewController"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/MasterViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MasterViewController"}],"url":"\/documentation\/yababa\/masterviewcontroller"},"doc://com.yababaGmbH.yababa/documentation/Yababa/OrderDetailsSceneViewController/orderDetailsTrackOrderContainer":{"role":"symbol","title":"orderDetailsTrackOrderContainer","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"orderDetailsTrackOrderContainer"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/OrderDetailsSceneViewController\/orderDetailsTrackOrderContainer","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"orderDetailsTrackOrderContainer"}],"url":"\/documentation\/yababa\/orderdetailssceneviewcontroller\/orderdetailstrackordercontainer"},"doc://com.yababaGmbH.yababa/documentation/Yababa/OrderDetailsSceneViewController/viewWillAppear(_:)":{"role":"symbol","title":"viewWillAppear(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"viewWillAppear"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/OrderDetailsSceneViewController\/viewWillAppear(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"viewWillAppear:"}],"url":"\/documentation\/yababa\/orderdetailssceneviewcontroller\/viewwillappear(_:)"},"doc://com.yababaGmbH.yababa/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.yababaGmbH.yababa\/SQ"},"doc://com.yababaGmbH.yababa/documentation/Yababa/OrderDetailsSceneViewController/deliveryWindowTimeLabel":{"role":"symbol","title":"deliveryWindowTimeLabel","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"deliveryWindowTimeLabel"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UILabel","preciseIdentifier":"c:objc(cs)UILabel"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/OrderDetailsSceneViewController\/deliveryWindowTimeLabel","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"deliveryWindowTimeLabel"}],"url":"\/documentation\/yababa\/orderdetailssceneviewcontroller\/deliverywindowtimelabel"},"doc://com.yababaGmbH.yababa/documentation/Yababa/OrderDetailsSceneViewController/deliveryFeeLabel":{"role":"symbol","title":"deliveryFeeLabel","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"deliveryFeeLabel"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UILabel","preciseIdentifier":"c:objc(cs)UILabel"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/OrderDetailsSceneViewController\/deliveryFeeLabel","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"deliveryFeeLabel"}],"url":"\/documentation\/yababa\/orderdetailssceneviewcontroller\/deliveryfeelabel"},"doc://com.yababaGmbH.yababa/documentation/Yababa/OrderDetailsSceneViewController":{"role":"symbol","title":"OrderDetailsSceneViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"OrderDetailsSceneViewController"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/OrderDetailsSceneViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"OrderDetailsSceneViewController"}],"url":"\/documentation\/yababa\/orderdetailssceneviewcontroller"},"doc://com.yababaGmbH.yababa/documentation/Yababa/OrderDetailsSceneViewController/orderPriceInfoView":{"role":"symbol","title":"orderPriceInfoView","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"orderPriceInfoView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/OrderDetailsSceneViewController\/orderPriceInfoView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"orderPriceInfoView"}],"url":"\/documentation\/yababa\/orderdetailssceneviewcontroller\/orderpriceinfoview"},"doc://com.yababaGmbH.yababa/documentation/Yababa/OrderDetailsSceneViewController/deliveryAddressLabel":{"role":"symbol","title":"deliveryAddressLabel","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"deliveryAddressLabel"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UILabel","preciseIdentifier":"c:objc(cs)UILabel"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/OrderDetailsSceneViewController\/deliveryAddressLabel","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"deliveryAddressLabel"}],"url":"\/documentation\/yababa\/orderdetailssceneviewcontroller\/deliveryaddresslabel"},"doc://com.yababaGmbH.yababa/documentation/Yababa/OrderDetailsSceneViewController/router":{"role":"symbol","title":"router","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"router"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"OrderDetailsSceneRouterProtocol","preciseIdentifier":"s:6Yababa31OrderDetailsSceneRouterProtocolP"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/OrderDetailsSceneViewController\/router","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/orderdetailssceneviewcontroller\/router"},"doc://com.yababaGmbH.yababa/documentation/Yababa/OrderDetailsSceneViewController/orderDetailsImage":{"role":"symbol","title":"orderDetailsImage","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"orderDetailsImage"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIImageView","preciseIdentifier":"c:objc(cs)UIImageView"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/OrderDetailsSceneViewController\/orderDetailsImage","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"orderDetailsImage"}],"url":"\/documentation\/yababa\/orderdetailssceneviewcontroller\/orderdetailsimage"},"doc://com.yababaGmbH.yababa/documentation/Yababa/OrderDetailsSceneViewController/reorderButton":{"role":"symbol","title":"reorderButton","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"reorderButton"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIButton","preciseIdentifier":"c:objc(cs)UIButton"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/OrderDetailsSceneViewController\/reorderButton","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"reorderButton"}],"url":"\/documentation\/yababa\/orderdetailssceneviewcontroller\/reorderbutton"},"doc://com.yababaGmbH.yababa/objc(pl)UIFocusEnvironment":{"type":"unresolvable","title":"UIKit.UIFocusEnvironment","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIFocusEnvironment"},"doc://com.yababaGmbH.yababa/objc(pl)UIUserActivityRestoring":{"type":"unresolvable","title":"UIKit.UIUserActivityRestoring","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIUserActivityRestoring"},"doc://com.yababaGmbH.yababa/objc(pl)NSCoding":{"type":"unresolvable","title":"Foundation.NSCoding","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)NSCoding"},"doc://com.yababaGmbH.yababa/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.yababaGmbH.yababa\/SH"},"doc://com.yababaGmbH.yababa/documentation/Yababa/OrderDetailsSceneViewController/OrderDetailsSceneViewControllerProtocol-Implementations":{"role":"collectionGroup","title":"OrderDetailsSceneViewControllerProtocol Implementations","abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/OrderDetailsSceneViewController\/OrderDetailsSceneViewControllerProtocol-Implementations","kind":"article","type":"topic","url":"\/documentation\/yababa\/orderdetailssceneviewcontroller\/orderdetailssceneviewcontrollerprotocol-implementations"},"doc://com.yababaGmbH.yababa/objc(pl)NSExtensionRequestHandling":{"type":"unresolvable","title":"Foundation.NSExtensionRequestHandling","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)NSExtensionRequestHandling"},"doc://com.yababaGmbH.yababa/objc(pl)UITraitEnvironment":{"type":"unresolvable","title":"UIKit.UITraitEnvironment","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)UITraitEnvironment"},"doc://com.yababaGmbH.yababa/objc(pl)UIPasteConfigurationSupporting":{"type":"unresolvable","title":"UIKit.UIPasteConfigurationSupporting","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIPasteConfigurationSupporting"},"doc://com.yababaGmbH.yababa/documentation/Yababa/OrderDetailsSceneViewController/showLocalizedStrings()":{"role":"symbol","title":"showLocalizedStrings()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"showLocalizedStrings"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/OrderDetailsSceneViewController\/showLocalizedStrings()","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/orderdetailssceneviewcontroller\/showlocalizedstrings()"},"doc://com.yababaGmbH.yababa/documentation/Yababa/OrderDetailsSceneViewController/backupTitleLabel":{"role":"symbol","title":"backupTitleLabel","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"backupTitleLabel"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UILabel","preciseIdentifier":"c:objc(cs)UILabel"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/OrderDetailsSceneViewController\/backupTitleLabel","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"backupTitleLabel"}],"url":"\/documentation\/yababa\/orderdetailssceneviewcontroller\/backuptitlelabel"},"doc://com.yababaGmbH.yababa/documentation/Yababa/OrderDetailsSceneViewController/orderOverViewContainerView":{"role":"symbol","title":"orderOverViewContainerView","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"orderOverViewContainerView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/OrderDetailsSceneViewController\/orderOverViewContainerView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"orderOverViewContainerView"}],"url":"\/documentation\/yababa\/orderdetailssceneviewcontroller\/orderoverviewcontainerview"},"doc://com.yababaGmbH.yababa/documentation/Yababa/OrderDetailsSceneViewController/addSameProductsToCart(_:)":{"role":"symbol","title":"addSameProductsToCart(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"addSameProductsToCart"},{"kind":"text","text":"("},{"kind":"keyword","text":"Any"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/OrderDetailsSceneViewController\/addSameProductsToCart(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"addSameProductsToCart:"}],"url":"\/documentation\/yababa\/orderdetailssceneviewcontroller\/addsameproductstocart(_:)"},"doc://com.yababaGmbH.yababa/documentation/Yababa/OrderDetailsSceneViewController/subTotalLabel":{"role":"symbol","title":"subTotalLabel","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"subTotalLabel"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UILabel","preciseIdentifier":"c:objc(cs)UILabel"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/OrderDetailsSceneViewController\/subTotalLabel","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"subTotalLabel"}],"url":"\/documentation\/yababa\/orderdetailssceneviewcontroller\/subtotallabel"},"doc://com.yababaGmbH.yababa/objc(pl)UIStateRestoring":{"type":"unresolvable","title":"UIKit.UIStateRestoring","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIStateRestoring"},"doc://com.yababaGmbH.yababa/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)NSObject"},"doc://com.yababaGmbH.yababa/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.yababaGmbH.yababa\/s7CVarArgP"},"doc://com.yababaGmbH.yababa/documentation/Yababa/OrderDetailsSceneViewController/totalLabel":{"role":"symbol","title":"totalLabel","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"totalLabel"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UILabel","preciseIdentifier":"c:objc(cs)UILabel"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/OrderDetailsSceneViewController\/totalLabel","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"totalLabel"}],"url":"\/documentation\/yababa\/orderdetailssceneviewcontroller\/totallabel"},"doc://com.yababaGmbH.yababa/objc(pl)UIActivityItemsConfigurationProviding":{"type":"unresolvable","title":"UIKit.UIActivityItemsConfigurationProviding","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIActivityItemsConfigurationProviding"},"doc://com.yababaGmbH.yababa/documentation/Yababa/OrderDetailsSceneViewController/deliveryWindowDateLabel":{"role":"symbol","title":"deliveryWindowDateLabel","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"deliveryWindowDateLabel"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UILabel","preciseIdentifier":"c:objc(cs)UILabel"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/OrderDetailsSceneViewController\/deliveryWindowDateLabel","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"deliveryWindowDateLabel"}],"url":"\/documentation\/yababa\/orderdetailssceneviewcontroller\/deliverywindowdatelabel"},"doc://com.yababaGmbH.yababa/documentation/Yababa/OrderDetailsSceneViewController/orderNumberRefLabel":{"role":"symbol","title":"orderNumberRefLabel","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"orderNumberRefLabel"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UILabel","preciseIdentifier":"c:objc(cs)UILabel"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/OrderDetailsSceneViewController\/orderNumberRefLabel","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"orderNumberRefLabel"}],"url":"\/documentation\/yababa\/orderdetailssceneviewcontroller\/ordernumberreflabel"},"doc://com.yababaGmbH.yababa/objc(pl)UIResponderStandardEditActions":{"type":"unresolvable","title":"UIKit.UIResponderStandardEditActions","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIResponderStandardEditActions"},"doc://com.yababaGmbH.yababa/documentation/Yababa/OrderDetailsSceneViewControllerProtocol":{"role":"symbol","title":"OrderDetailsSceneViewControllerProtocol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"OrderDetailsSceneViewControllerProtocol"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/OrderDetailsSceneViewControllerProtocol","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"OrderDetailsSceneViewControllerProtocol"}],"url":"\/documentation\/yababa\/orderdetailssceneviewcontrollerprotocol"},"doc://com.yababaGmbH.yababa/documentation/Yababa/OrderDetailsSceneViewController/totalTextLabel":{"role":"symbol","title":"totalTextLabel","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"totalTextLabel"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UILabel","preciseIdentifier":"c:objc(cs)UILabel"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/OrderDetailsSceneViewController\/totalTextLabel","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"totalTextLabel"}],"url":"\/documentation\/yababa\/orderdetailssceneviewcontroller\/totaltextlabel"},"doc://com.yababaGmbH.yababa/documentation/Yababa/OrderDetailsSceneViewController/orderStatusContainerView":{"role":"symbol","title":"orderStatusContainerView","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"orderStatusContainerView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/OrderDetailsSceneViewController\/orderStatusContainerView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"orderStatusContainerView"}],"url":"\/documentation\/yababa\/orderdetailssceneviewcontroller\/orderstatuscontainerview"},"doc://com.yababaGmbH.yababa/documentation/Yababa/OrderDetailsSceneViewController/deliveryETALabel":{"role":"symbol","title":"deliveryETALabel","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"deliveryETALabel"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UILabel","preciseIdentifier":"c:objc(cs)UILabel"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/OrderDetailsSceneViewController\/deliveryETALabel","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"deliveryETALabel"}],"url":"\/documentation\/yababa\/orderdetailssceneviewcontroller\/deliveryetalabel"},"doc://com.yababaGmbH.yababa/documentation/Yababa/OrderDetailsSceneViewController/orderInfoDetailsView":{"role":"symbol","title":"orderInfoDetailsView","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"orderInfoDetailsView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/OrderDetailsSceneViewController\/orderInfoDetailsView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"orderInfoDetailsView"}],"url":"\/documentation\/yababa\/orderdetailssceneviewcontroller\/orderinfodetailsview"},"doc://com.yababaGmbH.yababa/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/com.yababaGmbH.yababa\/s8SendableP"},"doc://com.yababaGmbH.yababa/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.yababaGmbH.yababa\/s23CustomStringConvertibleP"},"doc://com.yababaGmbH.yababa/documentation/Yababa/OrderDetailsSceneViewController/discountTextLabel":{"role":"symbol","title":"discountTextLabel","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"discountTextLabel"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UILabel","preciseIdentifier":"c:objc(cs)UILabel"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/OrderDetailsSceneViewController\/discountTextLabel","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"discountTextLabel"}],"url":"\/documentation\/yababa\/orderdetailssceneviewcontroller\/discounttextlabel"},"doc://com.yababaGmbH.yababa/documentation/Yababa/OrderDetailsSceneViewController/discountLabel":{"role":"symbol","title":"discountLabel","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"discountLabel"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UILabel","preciseIdentifier":"c:objc(cs)UILabel"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/OrderDetailsSceneViewController\/discountLabel","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"discountLabel"}],"url":"\/documentation\/yababa\/orderdetailssceneviewcontroller\/discountlabel"},"doc://com.yababaGmbH.yababa/documentation/Yababa/OrderDetailsSceneViewController/addressLabel":{"role":"symbol","title":"addressLabel","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"addressLabel"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UILabel","preciseIdentifier":"c:objc(cs)UILabel"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/OrderDetailsSceneViewController\/addressLabel","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"addressLabel"}],"url":"\/documentation\/yababa\/orderdetailssceneviewcontroller\/addresslabel"},"doc://com.yababaGmbH.yababa/objc(pl)UIContentContainer":{"type":"unresolvable","title":"UIKit.UIContentContainer","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIContentContainer"},"doc://com.yababaGmbH.yababa/documentation/Yababa/OrderDetailsSceneViewController/orderProductsTableViewHeightConstraint":{"role":"symbol","title":"orderProductsTableViewHeightConstraint","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"orderProductsTableViewHeightConstraint"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSLayoutConstraint","preciseIdentifier":"c:objc(cs)NSLayoutConstraint"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/OrderDetailsSceneViewController\/orderProductsTableViewHeightConstraint","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"orderProductsTableViewHeightConstraint"}],"url":"\/documentation\/yababa\/orderdetailssceneviewcontroller\/orderproductstableviewheightconstraint"},"doc://com.yababaGmbH.yababa/objc(pl)UIAppearanceContainer":{"type":"unresolvable","title":"UIKit.UIAppearanceContainer","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIAppearanceContainer"},"doc://com.yababaGmbH.yababa/documentation/Yababa/OrderDetailsSceneViewController/discountStackView":{"role":"symbol","title":"discountStackView","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"discountStackView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIStackView","preciseIdentifier":"c:objc(cs)UIStackView"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/OrderDetailsSceneViewController\/discountStackView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"discountStackView"}],"url":"\/documentation\/yababa\/orderdetailssceneviewcontroller\/discountstackview"},"doc://com.yababaGmbH.yababa/documentation/Yababa/OrderDetailsSceneViewController/subTotalTextLabel":{"role":"symbol","title":"subTotalTextLabel","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"subTotalTextLabel"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UILabel","preciseIdentifier":"c:objc(cs)UILabel"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/OrderDetailsSceneViewController\/subTotalTextLabel","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"subTotalTextLabel"}],"url":"\/documentation\/yababa\/orderdetailssceneviewcontroller\/subtotaltextlabel"},"doc://com.yababaGmbH.yababa/documentation/Yababa/OrderDetailsSceneViewController/mapView":{"role":"symbol","title":"mapView","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"mapView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GMSMapView","preciseIdentifier":"c:objc(cs)GMSMapView"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/OrderDetailsSceneViewController\/mapView","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/orderdetailssceneviewcontroller\/mapview"},"doc://com.yababaGmbH.yababa/documentation/Yababa/OrderDetailsSceneViewController/orderNumberLabel":{"role":"symbol","title":"orderNumberLabel","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"orderNumberLabel"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UILabel","preciseIdentifier":"c:objc(cs)UILabel"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/OrderDetailsSceneViewController\/orderNumberLabel","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"orderNumberLabel"}],"url":"\/documentation\/yababa\/orderdetailssceneviewcontroller\/ordernumberlabel"},"doc://com.yababaGmbH.yababa/documentation/Yababa/OrderDetailsSceneViewController/init(idOrder:showCustomBackBtn:)":{"role":"symbol","title":"init(idOrder:showCustomBackBtn:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"idOrder"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"kind":"externalParam","text":"showCustomBackBtn"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/OrderDetailsSceneViewController\/init(idOrder:showCustomBackBtn:)","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/orderdetailssceneviewcontroller\/init(idorder:showcustombackbtn:)"},"doc://com.yababaGmbH.yababa/documentation/Yababa/OrderDetailsSceneViewController/interactor":{"role":"symbol","title":"interactor","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"interactor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"OrderDetailsSceneInteractorProtocol","preciseIdentifier":"s:6Yababa35OrderDetailsSceneInteractorProtocolP"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/OrderDetailsSceneViewController\/interactor","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/orderdetailssceneviewcontroller\/interactor"},"doc://com.yababaGmbH.yababa/documentation/Yababa/OrderDetailsSceneViewController/init(coder:)":{"role":"symbol","title":"init(coder:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"coder"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSCoder","preciseIdentifier":"c:objc(cs)NSCoder"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/OrderDetailsSceneViewController\/init(coder:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithCoder:"}],"url":"\/documentation\/yababa\/orderdetailssceneviewcontroller\/init(coder:)"},"doc://com.yababaGmbH.yababa/documentation/Yababa/OrderDetailsSceneViewController/OrderProductsDatasourceSelection-Implementations":{"role":"collectionGroup","title":"OrderProductsDatasourceSelection Implementations","abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/OrderDetailsSceneViewController\/OrderProductsDatasourceSelection-Implementations","kind":"article","type":"topic","url":"\/documentation\/yababa\/orderdetailssceneviewcontroller\/orderproductsdatasourceselection-implementations"},"doc://com.yababaGmbH.yababa/documentation/Yababa/OrderProductsDatasourceSelection":{"role":"symbol","title":"OrderProductsDatasourceSelection","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"OrderProductsDatasourceSelection"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/OrderProductsDatasourceSelection","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"OrderProductsDatasourceSelection"}],"url":"\/documentation\/yababa\/orderproductsdatasourceselection"},"doc://com.yababaGmbH.yababa/documentation/Yababa/OrderDetailsSceneViewController/orderDetailsTrackOrderBtn":{"role":"symbol","title":"orderDetailsTrackOrderBtn","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"orderDetailsTrackOrderBtn"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIButton","preciseIdentifier":"c:objc(cs)UIButton"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/OrderDetailsSceneViewController\/orderDetailsTrackOrderBtn","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"orderDetailsTrackOrderBtn"}],"url":"\/documentation\/yababa\/orderdetailssceneviewcontroller\/orderdetailstrackorderbtn"},"doc://com.yababaGmbH.yababa/documentation/Yababa/OrderDetailsSceneViewController/orderStatusTableViewHeightConstraint":{"role":"symbol","title":"orderStatusTableViewHeightConstraint","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"orderStatusTableViewHeightConstraint"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSLayoutConstraint","preciseIdentifier":"c:objc(cs)NSLayoutConstraint"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/OrderDetailsSceneViewController\/orderStatusTableViewHeightConstraint","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"orderStatusTableViewHeightConstraint"}],"url":"\/documentation\/yababa\/orderdetailssceneviewcontroller\/orderstatustableviewheightconstraint"},"doc://com.yababaGmbH.yababa/12SkeletonView17AssociatedObjectsP":{"type":"unresolvable","title":"SkeletonView.AssociatedObjects","identifier":"doc:\/\/com.yababaGmbH.yababa\/12SkeletonView17AssociatedObjectsP"},"doc://com.yababaGmbH.yababa/documentation/Yababa/OrderDetailsSceneViewController/viewWillDisappear(_:)":{"role":"symbol","title":"viewWillDisappear(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"viewWillDisappear"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/OrderDetailsSceneViewController\/viewWillDisappear(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"viewWillDisappear:"}],"url":"\/documentation\/yababa\/orderdetailssceneviewcontroller\/viewwilldisappear(_:)"},"doc://com.yababaGmbH.yababa/documentation/Yababa/OrderDetailsSceneViewController/customNavbar":{"role":"symbol","title":"customNavbar","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"customNavbar"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/OrderDetailsSceneViewController\/customNavbar","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"customNavbar"}],"url":"\/documentation\/yababa\/orderdetailssceneviewcontroller\/customnavbar"},"doc://com.yababaGmbH.yababa/documentation/Yababa/OrderDetailsSceneViewController/deliveryETAContainer":{"role":"symbol","title":"deliveryETAContainer","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"deliveryETAContainer"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/OrderDetailsSceneViewController\/deliveryETAContainer","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"deliveryETAContainer"}],"url":"\/documentation\/yababa\/orderdetailssceneviewcontroller\/deliveryetacontainer"},"doc://com.yababaGmbH.yababa/documentation/Yababa/OrderDetailsSceneViewController/orderDetailsSubTitle":{"role":"symbol","title":"orderDetailsSubTitle","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"orderDetailsSubTitle"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UILabel","preciseIdentifier":"c:objc(cs)UILabel"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/OrderDetailsSceneViewController\/orderDetailsSubTitle","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"orderDetailsSubTitle"}],"url":"\/documentation\/yababa\/orderdetailssceneviewcontroller\/orderdetailssubtitle"},"doc://com.yababaGmbH.yababa/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.yababaGmbH.yababa\/s28CustomDebugStringConvertibleP"},"doc://com.yababaGmbH.yababa/documentation/Yababa/OrderDetailsSceneViewController/trackUserOrder(_:)":{"role":"symbol","title":"trackUserOrder(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"trackUserOrder"},{"kind":"text","text":"("},{"kind":"keyword","text":"Any"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/OrderDetailsSceneViewController\/trackUserOrder(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"trackUserOrder:"}],"url":"\/documentation\/yababa\/orderdetailssceneviewcontroller\/trackuserorder(_:)"},"doc://com.yababaGmbH.yababa/documentation/Yababa/OrderDetailsSceneViewController/orderStatusTableView":{"role":"symbol","title":"orderStatusTableView","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"orderStatusTableView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UITableView","preciseIdentifier":"c:objc(cs)UITableView"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/OrderDetailsSceneViewController\/orderStatusTableView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"orderStatusTableView"}],"url":"\/documentation\/yababa\/orderdetailssceneviewcontroller\/orderstatustableview"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"OrderDetailsSceneViewController"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"OrderDetailsSceneViewController"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"OrderDetailsSceneViewController"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/OrderDetailsSceneViewController\/addressLabel","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/OrderDetailsSceneViewController\/backupTitleLabel","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/OrderDetailsSceneViewController\/customNavbar","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/OrderDetailsSceneViewController\/deliveryAddressLabel","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/OrderDetailsSceneViewController\/deliveryETAContainer","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/OrderDetailsSceneViewController\/deliveryETALabel","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/OrderDetailsSceneViewController\/deliveryFeeLabel","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/OrderDetailsSceneViewController\/deliveryFeeTextLabel","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/OrderDetailsSceneViewController\/deliveryWindowDateLabel","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/OrderDetailsSceneViewController\/deliveryWindowTimeLabel","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/OrderDetailsSceneViewController\/discountLabel","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/OrderDetailsSceneViewController\/discountStackView","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/OrderDetailsSceneViewController\/discountTextLabel","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/OrderDetailsSceneViewController\/orderDetailsImage","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/OrderDetailsSceneViewController\/orderDetailsSubTitle","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/OrderDetailsSceneViewController\/orderDetailsTrackOrderBtn","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/OrderDetailsSceneViewController\/orderDetailsTrackOrderContainer","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/OrderDetailsSceneViewController\/orderInfoDetailsView","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/OrderDetailsSceneViewController\/orderNumberLabel","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/OrderDetailsSceneViewController\/orderNumberRefLabel","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/OrderDetailsSceneViewController\/orderOverViewContainerView","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/OrderDetailsSceneViewController\/orderOverviewTextLabel","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/OrderDetailsSceneViewController\/orderPriceInfoView","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/OrderDetailsSceneViewController\/orderProductsCountLabel","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/OrderDetailsSceneViewController\/orderProductsTableView","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/OrderDetailsSceneViewController\/orderProductsTableViewHeightConstraint","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/OrderDetailsSceneViewController\/orderStatusContainerView","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/OrderDetailsSceneViewController\/orderStatusTableView","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/OrderDetailsSceneViewController\/orderStatusTableViewHeightConstraint","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/OrderDetailsSceneViewController\/reorderButton","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/OrderDetailsSceneViewController\/subTotalLabel","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/OrderDetailsSceneViewController\/subTotalTextLabel","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/OrderDetailsSceneViewController\/totalLabel","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/OrderDetailsSceneViewController\/totalTextLabel"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/OrderDetailsSceneViewController\/addSameProductsToCart(_:)","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/OrderDetailsSceneViewController\/init(coder:)","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/OrderDetailsSceneViewController\/trackUserOrder(_:)","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/OrderDetailsSceneViewController\/viewDidLoad()","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/OrderDetailsSceneViewController\/viewWillAppear(_:)","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/OrderDetailsSceneViewController\/viewWillDisappear(_:)"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/MasterViewController"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"OrderDetailsSceneViewController"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/MasterViewController","preciseIdentifier":"c:@M@Yababa@objc(cs)MasterViewController","text":"MasterViewController"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1OrderDetailsSceneViewController~1viewDidLoad()\/title","value":"viewDidLoad"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1OrderDetailsSceneViewController~1viewDidLoad()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"viewDidLoad"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1OrderDetailsSceneViewController~1orderProductsTableView\/title","value":"orderProductsTableView"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1OrderDetailsSceneViewController~1orderProductsTableView\/fragments","value":[{"kind":"identifier","text":"orderProductsTableView"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1OrderDetailsSceneViewController~1deliveryFeeTextLabel\/title","value":"deliveryFeeTextLabel"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1OrderDetailsSceneViewController~1deliveryFeeTextLabel\/fragments","value":[{"kind":"identifier","text":"deliveryFeeTextLabel"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1OrderDetailsSceneViewController~1orderProductsCountLabel\/title","value":"orderProductsCountLabel"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1OrderDetailsSceneViewController~1orderProductsCountLabel\/fragments","value":[{"kind":"identifier","text":"orderProductsCountLabel"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1OrderDetailsSceneViewController~1orderOverviewTextLabel\/title","value":"orderOverviewTextLabel"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1OrderDetailsSceneViewController~1orderOverviewTextLabel\/fragments","value":[{"kind":"identifier","text":"orderOverviewTextLabel"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1MasterViewController\/title","value":"MasterViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1MasterViewController\/fragments","value":[{"kind":"identifier","text":"MasterViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1OrderDetailsSceneViewController~1orderDetailsTrackOrderContainer\/title","value":"orderDetailsTrackOrderContainer"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1OrderDetailsSceneViewController~1orderDetailsTrackOrderContainer\/fragments","value":[{"kind":"identifier","text":"orderDetailsTrackOrderContainer"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1OrderDetailsSceneViewController~1viewWillAppear(_:)\/title","value":"viewWillAppear:"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1OrderDetailsSceneViewController~1viewWillAppear(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"viewWillAppear:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1OrderDetailsSceneViewController~1deliveryWindowTimeLabel\/title","value":"deliveryWindowTimeLabel"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1OrderDetailsSceneViewController~1deliveryWindowTimeLabel\/fragments","value":[{"kind":"identifier","text":"deliveryWindowTimeLabel"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1OrderDetailsSceneViewController~1deliveryFeeLabel\/title","value":"deliveryFeeLabel"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1OrderDetailsSceneViewController~1deliveryFeeLabel\/fragments","value":[{"kind":"identifier","text":"deliveryFeeLabel"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1OrderDetailsSceneViewController\/title","value":"OrderDetailsSceneViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1OrderDetailsSceneViewController\/fragments","value":[{"kind":"identifier","text":"OrderDetailsSceneViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1OrderDetailsSceneViewController~1orderPriceInfoView\/title","value":"orderPriceInfoView"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1OrderDetailsSceneViewController~1orderPriceInfoView\/fragments","value":[{"kind":"identifier","text":"orderPriceInfoView"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1OrderDetailsSceneViewController~1deliveryAddressLabel\/title","value":"deliveryAddressLabel"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1OrderDetailsSceneViewController~1deliveryAddressLabel\/fragments","value":[{"kind":"identifier","text":"deliveryAddressLabel"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1OrderDetailsSceneViewController~1orderDetailsImage\/title","value":"orderDetailsImage"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1OrderDetailsSceneViewController~1orderDetailsImage\/fragments","value":[{"kind":"identifier","text":"orderDetailsImage"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1OrderDetailsSceneViewController~1reorderButton\/title","value":"reorderButton"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1OrderDetailsSceneViewController~1reorderButton\/fragments","value":[{"kind":"identifier","text":"reorderButton"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1OrderDetailsSceneViewController~1backupTitleLabel\/title","value":"backupTitleLabel"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1OrderDetailsSceneViewController~1backupTitleLabel\/fragments","value":[{"kind":"identifier","text":"backupTitleLabel"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1OrderDetailsSceneViewController~1orderOverViewContainerView\/title","value":"orderOverViewContainerView"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1OrderDetailsSceneViewController~1orderOverViewContainerView\/fragments","value":[{"kind":"identifier","text":"orderOverViewContainerView"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1OrderDetailsSceneViewController~1addSameProductsToCart(_:)\/title","value":"addSameProductsToCart:"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1OrderDetailsSceneViewController~1addSameProductsToCart(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"addSameProductsToCart:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1OrderDetailsSceneViewController~1subTotalLabel\/title","value":"subTotalLabel"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1OrderDetailsSceneViewController~1subTotalLabel\/fragments","value":[{"kind":"identifier","text":"subTotalLabel"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1OrderDetailsSceneViewController~1totalLabel\/title","value":"totalLabel"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1OrderDetailsSceneViewController~1totalLabel\/fragments","value":[{"kind":"identifier","text":"totalLabel"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1OrderDetailsSceneViewController~1deliveryWindowDateLabel\/title","value":"deliveryWindowDateLabel"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1OrderDetailsSceneViewController~1deliveryWindowDateLabel\/fragments","value":[{"kind":"identifier","text":"deliveryWindowDateLabel"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1OrderDetailsSceneViewController~1orderNumberRefLabel\/title","value":"orderNumberRefLabel"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1OrderDetailsSceneViewController~1orderNumberRefLabel\/fragments","value":[{"kind":"identifier","text":"orderNumberRefLabel"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1OrderDetailsSceneViewController~1totalTextLabel\/title","value":"totalTextLabel"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1OrderDetailsSceneViewController~1totalTextLabel\/fragments","value":[{"kind":"identifier","text":"totalTextLabel"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1OrderDetailsSceneViewController~1orderStatusContainerView\/title","value":"orderStatusContainerView"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1OrderDetailsSceneViewController~1orderStatusContainerView\/fragments","value":[{"kind":"identifier","text":"orderStatusContainerView"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1OrderDetailsSceneViewController~1deliveryETALabel\/title","value":"deliveryETALabel"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1OrderDetailsSceneViewController~1deliveryETALabel\/fragments","value":[{"kind":"identifier","text":"deliveryETALabel"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1OrderDetailsSceneViewController~1orderInfoDetailsView\/title","value":"orderInfoDetailsView"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1OrderDetailsSceneViewController~1orderInfoDetailsView\/fragments","value":[{"kind":"identifier","text":"orderInfoDetailsView"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1OrderDetailsSceneViewController~1discountTextLabel\/title","value":"discountTextLabel"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1OrderDetailsSceneViewController~1discountTextLabel\/fragments","value":[{"kind":"identifier","text":"discountTextLabel"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1OrderDetailsSceneViewController~1discountLabel\/title","value":"discountLabel"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1OrderDetailsSceneViewController~1discountLabel\/fragments","value":[{"kind":"identifier","text":"discountLabel"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1OrderDetailsSceneViewController~1addressLabel\/title","value":"addressLabel"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1OrderDetailsSceneViewController~1addressLabel\/fragments","value":[{"kind":"identifier","text":"addressLabel"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1OrderDetailsSceneViewController~1orderProductsTableViewHeightConstraint\/title","value":"orderProductsTableViewHeightConstraint"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1OrderDetailsSceneViewController~1orderProductsTableViewHeightConstraint\/fragments","value":[{"kind":"identifier","text":"orderProductsTableViewHeightConstraint"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1OrderDetailsSceneViewController~1discountStackView\/title","value":"discountStackView"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1OrderDetailsSceneViewController~1discountStackView\/fragments","value":[{"kind":"identifier","text":"discountStackView"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1OrderDetailsSceneViewController~1subTotalTextLabel\/title","value":"subTotalTextLabel"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1OrderDetailsSceneViewController~1subTotalTextLabel\/fragments","value":[{"kind":"identifier","text":"subTotalTextLabel"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1OrderDetailsSceneViewController~1orderNumberLabel\/title","value":"orderNumberLabel"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1OrderDetailsSceneViewController~1orderNumberLabel\/fragments","value":[{"kind":"identifier","text":"orderNumberLabel"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1OrderDetailsSceneViewController~1init(coder:)\/title","value":"initWithCoder:"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1OrderDetailsSceneViewController~1init(coder:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithCoder:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1OrderDetailsSceneViewController~1orderDetailsTrackOrderBtn\/title","value":"orderDetailsTrackOrderBtn"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1OrderDetailsSceneViewController~1orderDetailsTrackOrderBtn\/fragments","value":[{"kind":"identifier","text":"orderDetailsTrackOrderBtn"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1OrderDetailsSceneViewController~1orderStatusTableViewHeightConstraint\/title","value":"orderStatusTableViewHeightConstraint"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1OrderDetailsSceneViewController~1orderStatusTableViewHeightConstraint\/fragments","value":[{"kind":"identifier","text":"orderStatusTableViewHeightConstraint"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1OrderDetailsSceneViewController~1viewWillDisappear(_:)\/title","value":"viewWillDisappear:"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1OrderDetailsSceneViewController~1viewWillDisappear(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"viewWillDisappear:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1OrderDetailsSceneViewController~1customNavbar\/title","value":"customNavbar"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1OrderDetailsSceneViewController~1customNavbar\/fragments","value":[{"kind":"identifier","text":"customNavbar"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1OrderDetailsSceneViewController~1deliveryETAContainer\/title","value":"deliveryETAContainer"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1OrderDetailsSceneViewController~1deliveryETAContainer\/fragments","value":[{"kind":"identifier","text":"deliveryETAContainer"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1OrderDetailsSceneViewController~1orderDetailsSubTitle\/title","value":"orderDetailsSubTitle"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1OrderDetailsSceneViewController~1orderDetailsSubTitle\/fragments","value":[{"kind":"identifier","text":"orderDetailsSubTitle"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1OrderDetailsSceneViewController~1trackUserOrder(_:)\/title","value":"trackUserOrder:"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1OrderDetailsSceneViewController~1trackUserOrder(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"trackUserOrder:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1OrderDetailsSceneViewController~1orderStatusTableView\/title","value":"orderStatusTableView"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1OrderDetailsSceneViewController~1orderStatusTableView\/fragments","value":[{"kind":"identifier","text":"orderStatusTableView"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}