{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"PaymentProcessManager"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/yababa\/paymentprocessmanager"],"traits":[{"interfaceLanguage":"swift"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CashPaymentProcessManager","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/PaypalPaymentProcessManager","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/StripePaymentProcessManager"],"kind":"relationships","title":"Conforming Types","type":"conformingTypes"}],"identifier":{"url":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/PaymentProcessManager","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/PaymentProcessManager\/initiate(_:selectedSubGateway:flowProcessor:)"]}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"PaymentProcessManager"}],"title":"PaymentProcessManager","roleHeading":"Protocol","role":"symbol","symbolKind":"protocol","externalID":"s:6Yababa21PaymentProcessManagerP","modules":[{"name":"Yababa"}],"navigatorTitle":[{"kind":"identifier","text":"PaymentProcessManager"}]},"hierarchy":{"paths":[["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa"]]},"references":{"doc://com.yababaGmbH.yababa/documentation/Yababa/PaypalPaymentProcessManager":{"role":"symbol","title":"PaypalPaymentProcessManager","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PaypalPaymentProcessManager"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/PaypalPaymentProcessManager","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PaypalPaymentProcessManager"}],"url":"\/documentation\/yababa\/paypalpaymentprocessmanager"},"doc://com.yababaGmbH.yababa/documentation/Yababa/StripePaymentProcessManager":{"role":"symbol","title":"StripePaymentProcessManager","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"StripePaymentProcessManager"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/StripePaymentProcessManager","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"StripePaymentProcessManager"}],"url":"\/documentation\/yababa\/stripepaymentprocessmanager"},"doc://com.yababaGmbH.yababa/documentation/Yababa/PaymentProcessManager/initiate(_:selectedSubGateway:flowProcessor:)":{"role":"symbol","title":"initiate(_:selectedSubGateway:flowProcessor:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"initiate"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"CheckoutInformation","preciseIdentifier":"s:6Yababa19CheckoutInformationa"},{"kind":"text","text":", "},{"kind":"externalParam","text":"selectedSubGateway"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SubGatewayType","preciseIdentifier":"s:6Yababa14SubGatewayTypeO"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"flowProcessor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"FlowProcessor","preciseIdentifier":"s:6Yababa13FlowProcessorP"},{"kind":"text","text":") -> (viewController"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"},{"kind":"text","text":"?, paymentSubMethod"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"PaymentSubMethod","preciseIdentifier":"s:6Yababa16PaymentSubMethodP"},{"kind":"text","text":"?)"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/PaymentProcessManager\/initiate(_:selectedSubGateway:flowProcessor:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/yababa\/paymentprocessmanager\/initiate(_:selectedsubgateway:flowprocessor:)"},"doc://com.yababaGmbH.yababa/documentation/Yababa":{"role":"collection","title":"Yababa","abstract":[{"type":"text","text":"Getting Started"}],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa","kind":"symbol","type":"topic","url":"\/documentation\/yababa"},"doc://com.yababaGmbH.yababa/documentation/Yababa/CashPaymentProcessManager":{"role":"symbol","title":"CashPaymentProcessManager","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CashPaymentProcessManager"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CashPaymentProcessManager","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CashPaymentProcessManager"}],"url":"\/documentation\/yababa\/cashpaymentprocessmanager"},"doc://com.yababaGmbH.yababa/documentation/Yababa/PaymentProcessManager":{"role":"symbol","title":"PaymentProcessManager","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"PaymentProcessManager"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/PaymentProcessManager","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PaymentProcessManager"}],"url":"\/documentation\/yababa\/paymentprocessmanager"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1PaypalPaymentProcessManager\/title","value":"PaypalPaymentProcessManager"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1PaypalPaymentProcessManager\/fragments","value":[{"kind":"identifier","text":"PaypalPaymentProcessManager"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1StripePaymentProcessManager\/title","value":"StripePaymentProcessManager"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1StripePaymentProcessManager\/fragments","value":[{"kind":"identifier","text":"StripePaymentProcessManager"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1CashPaymentProcessManager\/title","value":"CashPaymentProcessManager"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1CashPaymentProcessManager\/fragments","value":[{"kind":"identifier","text":"CashPaymentProcessManager"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}