{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"PaymentSubMethod"},{"kind":"text","text":" : AnyObject"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/yababa\/paymentsubmethod"],"traits":[{"interfaceLanguage":"swift"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/StripeApplePay","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/StripeCreditCardPay","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/StripeGiroPay"],"kind":"relationships","title":"Conforming Types","type":"conformingTypes"}],"identifier":{"url":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/PaymentSubMethod","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/PaymentSubMethod\/iconName","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/PaymentSubMethod\/name"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/PaymentSubMethod\/initiate()"]}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"PaymentSubMethod"}],"title":"PaymentSubMethod","roleHeading":"Protocol","role":"symbol","symbolKind":"protocol","externalID":"s:6Yababa16PaymentSubMethodP","modules":[{"name":"Yababa"}],"navigatorTitle":[{"kind":"identifier","text":"PaymentSubMethod"}]},"hierarchy":{"paths":[["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa"]]},"references":{"doc://com.yababaGmbH.yababa/documentation/Yababa/StripeApplePay":{"role":"symbol","title":"StripeApplePay","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"StripeApplePay"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/StripeApplePay","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"StripeApplePay"}],"url":"\/documentation\/yababa\/stripeapplepay"},"doc://com.yababaGmbH.yababa/documentation/Yababa":{"role":"collection","title":"Yababa","abstract":[{"type":"text","text":"Getting Started"}],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa","kind":"symbol","type":"topic","url":"\/documentation\/yababa"},"doc://com.yababaGmbH.yababa/documentation/Yababa/PaymentSubMethod":{"role":"symbol","title":"PaymentSubMethod","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"PaymentSubMethod"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/PaymentSubMethod","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PaymentSubMethod"}],"url":"\/documentation\/yababa\/paymentsubmethod"},"doc://com.yababaGmbH.yababa/documentation/Yababa/PaymentSubMethod/iconName":{"role":"symbol","title":"iconName","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"iconName"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/PaymentSubMethod\/iconName","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/yababa\/paymentsubmethod\/iconname"},"doc://com.yababaGmbH.yababa/documentation/Yababa/PaymentSubMethod/initiate()":{"role":"symbol","title":"initiate()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"initiate"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/PaymentSubMethod\/initiate()","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/yababa\/paymentsubmethod\/initiate()"},"doc://com.yababaGmbH.yababa/documentation/Yababa/StripeCreditCardPay":{"role":"symbol","title":"StripeCreditCardPay","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"StripeCreditCardPay"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/StripeCreditCardPay","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"StripeCreditCardPay"}],"url":"\/documentation\/yababa\/stripecreditcardpay"},"doc://com.yababaGmbH.yababa/documentation/Yababa/PaymentSubMethod/name":{"role":"symbol","title":"name","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"name"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/PaymentSubMethod\/name","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/yababa\/paymentsubmethod\/name"},"doc://com.yababaGmbH.yababa/documentation/Yababa/StripeGiroPay":{"role":"symbol","title":"StripeGiroPay","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"StripeGiroPay"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/StripeGiroPay","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"StripeGiroPay"}],"url":"\/documentation\/yababa\/stripegiropay"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1StripeApplePay\/title","value":"StripeApplePay"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1StripeApplePay\/fragments","value":[{"kind":"identifier","text":"StripeApplePay"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1StripeCreditCardPay\/title","value":"StripeCreditCardPay"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1StripeCreditCardPay\/fragments","value":[{"kind":"identifier","text":"StripeCreditCardPay"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1StripeGiroPay\/title","value":"StripeGiroPay"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1StripeGiroPay\/fragments","value":[{"kind":"identifier","text":"StripeGiroPay"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}