{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PresentationViewController"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/yababa\/presentationviewcontroller"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/yababa\/presentationviewcontroller"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.yababaGmbH.yababa\/objc(cs)UIPresentationController"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.yababaGmbH.yababa\/objc(pl)NSObject","doc:\/\/com.yababaGmbH.yababa\/12SkeletonView17AssociatedObjectsP","doc:\/\/com.yababaGmbH.yababa\/s7CVarArgP","doc:\/\/com.yababaGmbH.yababa\/s28CustomDebugStringConvertibleP","doc:\/\/com.yababaGmbH.yababa\/s23CustomStringConvertibleP","doc:\/\/com.yababaGmbH.yababa\/SQ","doc:\/\/com.yababaGmbH.yababa\/SH","doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIAppearanceContainer","doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIContentContainer","doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIFocusEnvironment","doc:\/\/com.yababaGmbH.yababa\/objc(pl)UITraitEnvironment"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/PresentationViewController","interfaceLanguage":"swift"},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/PresentationViewController\/init(presentedViewController:presenting:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/PresentationViewController\/blurEffectView","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/PresentationViewController\/frameOfPresentedViewInContainerView","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/PresentationViewController\/tapGestureRecognizer"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/PresentationViewController\/containerViewDidLayoutSubviews()","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/PresentationViewController\/containerViewWillLayoutSubviews()","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/PresentationViewController\/dismiss()","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/PresentationViewController\/dismissalTransitionWillBegin()","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/PresentationViewController\/presentationTransitionWillBegin()"]}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PresentationViewController"}],"title":"PresentationViewController","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@Yababa@objc(cs)PresentationViewController","modules":[{"name":"Yababa"}],"navigatorTitle":[{"kind":"identifier","text":"PresentationViewController"}]},"hierarchy":{"paths":[["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa"]]},"references":{"doc://com.yababaGmbH.yababa/documentation/Yababa/PresentationViewController/blurEffectView":{"role":"symbol","title":"blurEffectView","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"blurEffectView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIVisualEffectView","preciseIdentifier":"c:objc(cs)UIVisualEffectView"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/PresentationViewController\/blurEffectView","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/presentationviewcontroller\/blureffectview"},"doc://com.yababaGmbH.yababa/documentation/Yababa/PresentationViewController/tapGestureRecognizer":{"role":"symbol","title":"tapGestureRecognizer","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"tapGestureRecognizer"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UITapGestureRecognizer","preciseIdentifier":"c:objc(cs)UITapGestureRecognizer"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/PresentationViewController\/tapGestureRecognizer","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/presentationviewcontroller\/tapgesturerecognizer"},"doc://com.yababaGmbH.yababa/objc(pl)UITraitEnvironment":{"type":"unresolvable","title":"UIKit.UITraitEnvironment","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)UITraitEnvironment"},"doc://com.yababaGmbH.yababa/documentation/Yababa":{"role":"collection","title":"Yababa","abstract":[{"type":"text","text":"Getting Started"}],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa","kind":"symbol","type":"topic","url":"\/documentation\/yababa"},"doc://com.yababaGmbH.yababa/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.yababaGmbH.yababa\/s28CustomDebugStringConvertibleP"},"doc://com.yababaGmbH.yababa/objc(pl)UIAppearanceContainer":{"type":"unresolvable","title":"UIKit.UIAppearanceContainer","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIAppearanceContainer"},"doc://com.yababaGmbH.yababa/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.yababaGmbH.yababa\/s23CustomStringConvertibleP"},"doc://com.yababaGmbH.yababa/documentation/Yababa/PresentationViewController/frameOfPresentedViewInContainerView":{"role":"symbol","title":"frameOfPresentedViewInContainerView","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"frameOfPresentedViewInContainerView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGRect","preciseIdentifier":"c:@S@CGRect"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/PresentationViewController\/frameOfPresentedViewInContainerView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"frameOfPresentedViewInContainerView"}],"url":"\/documentation\/yababa\/presentationviewcontroller\/frameofpresentedviewincontainerview"},"doc://com.yababaGmbH.yababa/documentation/Yababa/PresentationViewController/dismissalTransitionWillBegin()":{"role":"symbol","title":"dismissalTransitionWillBegin()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"dismissalTransitionWillBegin"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/PresentationViewController\/dismissalTransitionWillBegin()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"dismissalTransitionWillBegin"}],"url":"\/documentation\/yababa\/presentationviewcontroller\/dismissaltransitionwillbegin()"},"doc://com.yababaGmbH.yababa/documentation/Yababa/PresentationViewController/dismiss()":{"role":"symbol","title":"dismiss()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"dismiss"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/PresentationViewController\/dismiss()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"dismiss"}],"url":"\/documentation\/yababa\/presentationviewcontroller\/dismiss()"},"doc://com.yababaGmbH.yababa/documentation/Yababa/PresentationViewController/init(presentedViewController:presenting:)":{"role":"symbol","title":"init(presentedViewController:presenting:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"presentedViewController"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"presenting"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"},{"kind":"text","text":"?)"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/PresentationViewController\/init(presentedViewController:presenting:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithPresentedViewController:presentingViewController:"}],"url":"\/documentation\/yababa\/presentationviewcontroller\/init(presentedviewcontroller:presenting:)"},"doc://com.yababaGmbH.yababa/12SkeletonView17AssociatedObjectsP":{"type":"unresolvable","title":"SkeletonView.AssociatedObjects","identifier":"doc:\/\/com.yababaGmbH.yababa\/12SkeletonView17AssociatedObjectsP"},"doc://com.yababaGmbH.yababa/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)NSObject"},"doc://com.yababaGmbH.yababa/documentation/Yababa/PresentationViewController/presentationTransitionWillBegin()":{"role":"symbol","title":"presentationTransitionWillBegin()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"presentationTransitionWillBegin"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/PresentationViewController\/presentationTransitionWillBegin()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"presentationTransitionWillBegin"}],"url":"\/documentation\/yababa\/presentationviewcontroller\/presentationtransitionwillbegin()"},"doc://com.yababaGmbH.yababa/objc(pl)UIFocusEnvironment":{"type":"unresolvable","title":"UIKit.UIFocusEnvironment","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIFocusEnvironment"},"doc://com.yababaGmbH.yababa/documentation/Yababa/PresentationViewController/containerViewWillLayoutSubviews()":{"role":"symbol","title":"containerViewWillLayoutSubviews()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"containerViewWillLayoutSubviews"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/PresentationViewController\/containerViewWillLayoutSubviews()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"containerViewWillLayoutSubviews"}],"url":"\/documentation\/yababa\/presentationviewcontroller\/containerviewwilllayoutsubviews()"},"doc://com.yababaGmbH.yababa/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.yababaGmbH.yababa\/SQ"},"doc://com.yababaGmbH.yababa/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.yababaGmbH.yababa\/SH"},"doc://com.yababaGmbH.yababa/objc(cs)UIPresentationController":{"type":"unresolvable","title":"UIPresentationController","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(cs)UIPresentationController"},"doc://com.yababaGmbH.yababa/documentation/Yababa/PresentationViewController/containerViewDidLayoutSubviews()":{"role":"symbol","title":"containerViewDidLayoutSubviews()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"containerViewDidLayoutSubviews"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/PresentationViewController\/containerViewDidLayoutSubviews()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"containerViewDidLayoutSubviews"}],"url":"\/documentation\/yababa\/presentationviewcontroller\/containerviewdidlayoutsubviews()"},"doc://com.yababaGmbH.yababa/documentation/Yababa/PresentationViewController":{"role":"symbol","title":"PresentationViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PresentationViewController"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/PresentationViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PresentationViewController"}],"url":"\/documentation\/yababa\/presentationviewcontroller"},"doc://com.yababaGmbH.yababa/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.yababaGmbH.yababa\/s7CVarArgP"},"doc://com.yababaGmbH.yababa/objc(pl)UIContentContainer":{"type":"unresolvable","title":"UIKit.UIContentContainer","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIContentContainer"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"PresentationViewController"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"PresentationViewController"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"PresentationViewController"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/PresentationViewController\/frameOfPresentedViewInContainerView"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/PresentationViewController\/containerViewDidLayoutSubviews()","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/PresentationViewController\/containerViewWillLayoutSubviews()","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/PresentationViewController\/dismiss()","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/PresentationViewController\/dismissalTransitionWillBegin()","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/PresentationViewController\/init(presentedViewController:presenting:)","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/PresentationViewController\/presentationTransitionWillBegin()"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.yababaGmbH.yababa\/objc(cs)UIPresentationController"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"PresentationViewController"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"UIPresentationController","preciseIdentifier":"c:objc(cs)UIPresentationController"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1PresentationViewController~1frameOfPresentedViewInContainerView\/title","value":"frameOfPresentedViewInContainerView"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1PresentationViewController~1frameOfPresentedViewInContainerView\/fragments","value":[{"kind":"identifier","text":"frameOfPresentedViewInContainerView"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1PresentationViewController~1dismissalTransitionWillBegin()\/title","value":"dismissalTransitionWillBegin"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1PresentationViewController~1dismissalTransitionWillBegin()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"dismissalTransitionWillBegin"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1PresentationViewController~1dismiss()\/title","value":"dismiss"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1PresentationViewController~1dismiss()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"dismiss"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1PresentationViewController~1init(presentedViewController:presenting:)\/title","value":"initWithPresentedViewController:presentingViewController:"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1PresentationViewController~1init(presentedViewController:presenting:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithPresentedViewController:presentingViewController:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1PresentationViewController~1presentationTransitionWillBegin()\/title","value":"presentationTransitionWillBegin"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1PresentationViewController~1presentationTransitionWillBegin()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"presentationTransitionWillBegin"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1PresentationViewController~1containerViewWillLayoutSubviews()\/title","value":"containerViewWillLayoutSubviews"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1PresentationViewController~1containerViewWillLayoutSubviews()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"containerViewWillLayoutSubviews"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1PresentationViewController~1containerViewDidLayoutSubviews()\/title","value":"containerViewDidLayoutSubviews"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1PresentationViewController~1containerViewDidLayoutSubviews()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"containerViewDidLayoutSubviews"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1PresentationViewController\/title","value":"PresentationViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1PresentationViewController\/fragments","value":[{"kind":"identifier","text":"PresentationViewController"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}