{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ProductsAdjustmentPopupView"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/yababa\/productsadjustmentpopupview"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/yababa\/productsadjustmentpopupview"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.yababaGmbH.yababa\/objc(cs)UIViewController"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.yababaGmbH.yababa\/objc(pl)NSCoding","doc:\/\/com.yababaGmbH.yababa\/objc(pl)NSExtensionRequestHandling","doc:\/\/com.yababaGmbH.yababa\/objc(pl)NSObject","doc:\/\/com.yababaGmbH.yababa\/12SkeletonView17AssociatedObjectsP","doc:\/\/com.yababaGmbH.yababa\/s7CVarArgP","doc:\/\/com.yababaGmbH.yababa\/s28CustomDebugStringConvertibleP","doc:\/\/com.yababaGmbH.yababa\/s23CustomStringConvertibleP","doc:\/\/com.yababaGmbH.yababa\/SQ","doc:\/\/com.yababaGmbH.yababa\/SH","doc:\/\/com.yababaGmbH.yababa\/s8SendableP","doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIActivityItemsConfigurationProviding","doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIAppearanceContainer","doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIContentContainer","doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIFocusEnvironment","doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIPasteConfigurationSupporting","doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIResponderStandardEditActions","doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIScrollViewDelegate","doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIStateRestoring","doc:\/\/com.yababaGmbH.yababa\/objc(pl)UITableViewDataSource","doc:\/\/com.yababaGmbH.yababa\/objc(pl)UITableViewDelegate","doc:\/\/com.yababaGmbH.yababa\/objc(pl)UITraitEnvironment","doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIUserActivityRestoring"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ProductsAdjustmentPopupView","interfaceLanguage":"swift"},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ProductsAdjustmentPopupView\/init(coder:)","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ProductsAdjustmentPopupView\/init(productsAjusted:)"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ProductsAdjustmentPopupView\/onClose(_:)","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ProductsAdjustmentPopupView\/viewDidLoad()"]},{"title":"Default Implementations","identifiers":["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ProductsAdjustmentPopupView\/UITableViewDataSource-Implementations","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ProductsAdjustmentPopupView\/UITableViewDelegate-Implementations"],"generated":true}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ProductsAdjustmentPopupView"}],"title":"ProductsAdjustmentPopupView","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@Yababa@objc(cs)ProductsAdjustmentPopupView","modules":[{"name":"Yababa"}],"navigatorTitle":[{"kind":"identifier","text":"ProductsAdjustmentPopupView"}]},"hierarchy":{"paths":[["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa"]]},"references":{"doc://com.yababaGmbH.yababa/documentation/Yababa/ProductsAdjustmentPopupView/onClose(_:)":{"role":"symbol","title":"onClose(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onClose"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UIButton","preciseIdentifier":"c:objc(cs)UIButton"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ProductsAdjustmentPopupView\/onClose(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"onClose:"}],"url":"\/documentation\/yababa\/productsadjustmentpopupview\/onclose(_:)"},"doc://com.yababaGmbH.yababa/documentation/Yababa/ProductsAdjustmentPopupView":{"role":"symbol","title":"ProductsAdjustmentPopupView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ProductsAdjustmentPopupView"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ProductsAdjustmentPopupView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ProductsAdjustmentPopupView"}],"url":"\/documentation\/yababa\/productsadjustmentpopupview"},"doc://com.yababaGmbH.yababa/objc(pl)UITableViewDataSource":{"type":"unresolvable","title":"UIKit.UITableViewDataSource","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)UITableViewDataSource"},"doc://com.yababaGmbH.yababa/objc(pl)UITraitEnvironment":{"type":"unresolvable","title":"UIKit.UITraitEnvironment","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)UITraitEnvironment"},"doc://com.yababaGmbH.yababa/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)NSObject"},"doc://com.yababaGmbH.yababa/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.yababaGmbH.yababa\/SQ"},"doc://com.yababaGmbH.yababa/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.yababaGmbH.yababa\/s7CVarArgP"},"doc://com.yababaGmbH.yababa/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.yababaGmbH.yababa\/s23CustomStringConvertibleP"},"doc://com.yababaGmbH.yababa/documentation/Yababa/ProductsAdjustmentPopupView/init(coder:)":{"role":"symbol","title":"init(coder:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"coder"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSCoder","preciseIdentifier":"c:objc(cs)NSCoder"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ProductsAdjustmentPopupView\/init(coder:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithCoder:"}],"url":"\/documentation\/yababa\/productsadjustmentpopupview\/init(coder:)"},"doc://com.yababaGmbH.yababa/objc(pl)UIActivityItemsConfigurationProviding":{"type":"unresolvable","title":"UIKit.UIActivityItemsConfigurationProviding","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIActivityItemsConfigurationProviding"},"doc://com.yababaGmbH.yababa/documentation/Yababa":{"role":"collection","title":"Yababa","abstract":[{"type":"text","text":"Getting Started"}],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa","kind":"symbol","type":"topic","url":"\/documentation\/yababa"},"doc://com.yababaGmbH.yababa/documentation/Yababa/ProductsAdjustmentPopupView/UITableViewDelegate-Implementations":{"role":"collectionGroup","title":"UITableViewDelegate Implementations","abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ProductsAdjustmentPopupView\/UITableViewDelegate-Implementations","kind":"article","type":"topic","url":"\/documentation\/yababa\/productsadjustmentpopupview\/uitableviewdelegate-implementations"},"doc://com.yababaGmbH.yababa/objc(pl)NSCoding":{"type":"unresolvable","title":"Foundation.NSCoding","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)NSCoding"},"doc://com.yababaGmbH.yababa/objc(pl)UIAppearanceContainer":{"type":"unresolvable","title":"UIKit.UIAppearanceContainer","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIAppearanceContainer"},"doc://com.yababaGmbH.yababa/objc(pl)UIScrollViewDelegate":{"type":"unresolvable","title":"UIKit.UIScrollViewDelegate","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIScrollViewDelegate"},"doc://com.yababaGmbH.yababa/objc(pl)UIContentContainer":{"type":"unresolvable","title":"UIKit.UIContentContainer","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIContentContainer"},"doc://com.yababaGmbH.yababa/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/com.yababaGmbH.yababa\/s8SendableP"},"doc://com.yababaGmbH.yababa/objc(pl)NSExtensionRequestHandling":{"type":"unresolvable","title":"Foundation.NSExtensionRequestHandling","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)NSExtensionRequestHandling"},"doc://com.yababaGmbH.yababa/documentation/Yababa/ProductsAdjustmentPopupView/UITableViewDataSource-Implementations":{"role":"collectionGroup","title":"UITableViewDataSource Implementations","abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ProductsAdjustmentPopupView\/UITableViewDataSource-Implementations","kind":"article","type":"topic","url":"\/documentation\/yababa\/productsadjustmentpopupview\/uitableviewdatasource-implementations"},"doc://com.yababaGmbH.yababa/documentation/Yababa/ProductsAdjustmentPopupView/viewDidLoad()":{"role":"symbol","title":"viewDidLoad()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"viewDidLoad"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ProductsAdjustmentPopupView\/viewDidLoad()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"viewDidLoad"}],"url":"\/documentation\/yababa\/productsadjustmentpopupview\/viewdidload()"},"doc://com.yababaGmbH.yababa/objc(cs)UIViewController":{"type":"unresolvable","title":"UIViewController","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(cs)UIViewController"},"doc://com.yababaGmbH.yababa/objc(pl)UIUserActivityRestoring":{"type":"unresolvable","title":"UIKit.UIUserActivityRestoring","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIUserActivityRestoring"},"doc://com.yababaGmbH.yababa/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.yababaGmbH.yababa\/s28CustomDebugStringConvertibleP"},"doc://com.yababaGmbH.yababa/documentation/Yababa/ProductsAdjustmentPopupView/init(productsAjusted:)":{"role":"symbol","title":"init(productsAjusted:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"productsAjusted"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"ShoppingCartItem","preciseIdentifier":"s:6Yababa16ShoppingCartItemC"},{"kind":"text","text":"])"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ProductsAdjustmentPopupView\/init(productsAjusted:)","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/productsadjustmentpopupview\/init(productsajusted:)"},"doc://com.yababaGmbH.yababa/12SkeletonView17AssociatedObjectsP":{"type":"unresolvable","title":"SkeletonView.AssociatedObjects","identifier":"doc:\/\/com.yababaGmbH.yababa\/12SkeletonView17AssociatedObjectsP"},"doc://com.yababaGmbH.yababa/objc(pl)UIStateRestoring":{"type":"unresolvable","title":"UIKit.UIStateRestoring","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIStateRestoring"},"doc://com.yababaGmbH.yababa/objc(pl)UITableViewDelegate":{"type":"unresolvable","title":"UIKit.UITableViewDelegate","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)UITableViewDelegate"},"doc://com.yababaGmbH.yababa/objc(pl)UIFocusEnvironment":{"type":"unresolvable","title":"UIKit.UIFocusEnvironment","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIFocusEnvironment"},"doc://com.yababaGmbH.yababa/objc(pl)UIResponderStandardEditActions":{"type":"unresolvable","title":"UIKit.UIResponderStandardEditActions","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIResponderStandardEditActions"},"doc://com.yababaGmbH.yababa/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.yababaGmbH.yababa\/SH"},"doc://com.yababaGmbH.yababa/objc(pl)UIPasteConfigurationSupporting":{"type":"unresolvable","title":"UIKit.UIPasteConfigurationSupporting","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIPasteConfigurationSupporting"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"ProductsAdjustmentPopupView"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"ProductsAdjustmentPopupView"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"ProductsAdjustmentPopupView"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ProductsAdjustmentPopupView\/init(coder:)","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ProductsAdjustmentPopupView\/onClose(_:)","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ProductsAdjustmentPopupView\/viewDidLoad()"]},{"title":"Default Implementations","identifiers":["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ProductsAdjustmentPopupView\/UITableViewDataSource-Implementations","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ProductsAdjustmentPopupView\/UITableViewDelegate-Implementations"],"generated":true}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.yababaGmbH.yababa\/objc(cs)UIViewController"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"ProductsAdjustmentPopupView"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1ProductsAdjustmentPopupView~1onClose(_:)\/title","value":"onClose:"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1ProductsAdjustmentPopupView~1onClose(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onClose:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1ProductsAdjustmentPopupView\/title","value":"ProductsAdjustmentPopupView"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1ProductsAdjustmentPopupView\/fragments","value":[{"kind":"identifier","text":"ProductsAdjustmentPopupView"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1ProductsAdjustmentPopupView~1init(coder:)\/title","value":"initWithCoder:"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1ProductsAdjustmentPopupView~1init(coder:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithCoder:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1ProductsAdjustmentPopupView~1viewDidLoad()\/title","value":"viewDidLoad"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1ProductsAdjustmentPopupView~1viewDidLoad()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"viewDidLoad"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}