{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ProductsDataStoreManager"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/yababa\/productsdatastoremanager"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/yababa\/productsdatastoremanager"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.yababaGmbH.yababa\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.yababaGmbH.yababa\/objc(pl)NSObject","doc:\/\/com.yababaGmbH.yababa\/12SkeletonView17AssociatedObjectsP","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/StoreManagerProtocol","doc:\/\/com.yababaGmbH.yababa\/s7CVarArgP","doc:\/\/com.yababaGmbH.yababa\/s28CustomDebugStringConvertibleP","doc:\/\/com.yababaGmbH.yababa\/s23CustomStringConvertibleP","doc:\/\/com.yababaGmbH.yababa\/SQ","doc:\/\/com.yababaGmbH.yababa\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ProductsDataStoreManager","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ProductsDataStoreManager\/catalogue","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ProductsDataStoreManager\/currentCatalogueVersion","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ProductsDataStoreManager\/defaultStorefrontId","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ProductsDataStoreManager\/defaultWarehouseId","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ProductsDataStoreManager\/productsMap","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ProductsDataStoreManager\/stockQuantities"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ProductsDataStoreManager\/buildProductsMap()","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ProductsDataStoreManager\/clearCatalogue()","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ProductsDataStoreManager\/fetchCatalogue()","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ProductsDataStoreManager\/fetchCatalogue(completion:)","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ProductsDataStoreManager\/fetchInventoryQuantities(completion:)","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ProductsDataStoreManager\/fetchRemoteCatalogue(withLoader:completion:)","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ProductsDataStoreManager\/forceRefetchCatalogue(completion:)","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ProductsDataStoreManager\/getProduct(idProduct:)","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ProductsDataStoreManager\/getProductParentSubcategoryAndCategory(idProduct:)","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ProductsDataStoreManager\/initiate()","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ProductsDataStoreManager\/isProductInStock(_:)","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ProductsDataStoreManager\/quantityOfProductInStoreInventory(_:)","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ProductsDataStoreManager\/similarProductsTo(_:)"]},{"title":"Type Properties","identifiers":["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ProductsDataStoreManager\/defaultInstance"]}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ProductsDataStoreManager"}],"title":"ProductsDataStoreManager","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@Yababa@objc(cs)ProductsDataStoreManager","modules":[{"name":"Yababa"}],"navigatorTitle":[{"kind":"identifier","text":"ProductsDataStoreManager"}]},"hierarchy":{"paths":[["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa"]]},"references":{"doc://com.yababaGmbH.yababa/documentation/Yababa/ProductsDataStoreManager/defaultStorefrontId":{"role":"symbol","title":"defaultStorefrontId","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"defaultStorefrontId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"If user has not entered in an address. We use the default storefront id. In this case - Berlin"}],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ProductsDataStoreManager\/defaultStorefrontId","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/productsdatastoremanager\/defaultstorefrontid"},"doc://com.yababaGmbH.yababa/documentation/Yababa/ProductsDataStoreManager/clearCatalogue()":{"role":"symbol","title":"clearCatalogue()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"clearCatalogue"},{"kind":"text","text":"()"}],"abstract":[{"type":"text","text":"Clears locally stored catalogue"}],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ProductsDataStoreManager\/clearCatalogue()","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/productsdatastoremanager\/clearcatalogue()"},"doc://com.yababaGmbH.yababa/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.yababaGmbH.yababa\/s7CVarArgP"},"doc://com.yababaGmbH.yababa/documentation/Yababa/ProductsDataStoreManager":{"role":"symbol","title":"ProductsDataStoreManager","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ProductsDataStoreManager"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ProductsDataStoreManager","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ProductsDataStoreManager"}],"url":"\/documentation\/yababa\/productsdatastoremanager"},"doc://com.yababaGmbH.yababa/12SkeletonView17AssociatedObjectsP":{"type":"unresolvable","title":"SkeletonView.AssociatedObjects","identifier":"doc:\/\/com.yababaGmbH.yababa\/12SkeletonView17AssociatedObjectsP"},"doc://com.yababaGmbH.yababa/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.yababaGmbH.yababa\/SH"},"doc://com.yababaGmbH.yababa/documentation/Yababa/ProductsDataStoreManager/currentCatalogueVersion":{"role":"symbol","title":"currentCatalogueVersion","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"currentCatalogueVersion"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"}],"abstract":[{"type":"text","text":"The Catalogue has a version number so we can be compare the local and remote version values"}],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ProductsDataStoreManager\/currentCatalogueVersion","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/productsdatastoremanager\/currentcatalogueversion"},"doc://com.yababaGmbH.yababa/documentation/Yababa/ProductsDataStoreManager/isProductInStock(_:)":{"role":"symbol","title":"isProductInStock(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"isProductInStock"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Product","preciseIdentifier":"s:6Yababa7ProductC"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Checks if product is in stock. Takes considetation if the product is virtual stock item"}],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ProductsDataStoreManager\/isProductInStock(_:)","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/productsdatastoremanager\/isproductinstock(_:)"},"doc://com.yababaGmbH.yababa/documentation/Yababa/ProductsDataStoreManager/stockQuantities":{"role":"symbol","title":"stockQuantities","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"stockQuantities"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":"]?"}],"abstract":[{"type":"text","text":"A Map\/Dictionary of product id’s to their quantity available at store warehouse."},{"type":"text","text":" "},{"type":"text","text":"Fast O(1) access, to see if product is in stock and compare on how many items are available to add to cart"}],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ProductsDataStoreManager\/stockQuantities","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/productsdatastoremanager\/stockquantities"},"doc://com.yababaGmbH.yababa/documentation/Yababa/ProductsDataStoreManager/init":{"role":"symbol","title":"init","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ProductsDataStoreManager\/init","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"init"}],"url":"\/documentation\/yababa\/productsdatastoremanager\/init"},"doc://com.yababaGmbH.yababa/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.yababaGmbH.yababa\/s28CustomDebugStringConvertibleP"},"doc://com.yababaGmbH.yababa/documentation/Yababa/ProductsDataStoreManager/getProductParentSubcategoryAndCategory(idProduct:)":{"role":"symbol","title":"getProductParentSubcategoryAndCategory(idProduct:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getProductParentSubcategoryAndCategory"},{"kind":"text","text":"("},{"kind":"externalParam","text":"idProduct"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":") -> (subCategory"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SubCategory","preciseIdentifier":"s:6Yababa11SubCategoryC"},{"kind":"text","text":"?, category"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CollectionCategory","preciseIdentifier":"s:6Yababa18CollectionCategoryC"},{"kind":"text","text":"?)"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ProductsDataStoreManager\/getProductParentSubcategoryAndCategory(idProduct:)","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/productsdatastoremanager\/getproductparentsubcategoryandcategory(idproduct:)"},"doc://com.yababaGmbH.yababa/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(cs)NSObject"},"doc://com.yababaGmbH.yababa/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.yababaGmbH.yababa\/SQ"},"doc://com.yababaGmbH.yababa/documentation/Yababa/ProductsDataStoreManager/getProduct(idProduct:)":{"role":"symbol","title":"getProduct(idProduct:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getProduct"},{"kind":"text","text":"("},{"kind":"externalParam","text":"idProduct"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Product","preciseIdentifier":"s:6Yababa7ProductC"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Get Product by id"}],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ProductsDataStoreManager\/getProduct(idProduct:)","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/productsdatastoremanager\/getproduct(idproduct:)"},"doc://com.yababaGmbH.yababa/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.yababaGmbH.yababa\/s23CustomStringConvertibleP"},"doc://com.yababaGmbH.yababa/documentation/Yababa/ProductsDataStoreManager/forceRefetchCatalogue(completion:)":{"role":"symbol","title":"forceRefetchCatalogue(completion:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"forceRefetchCatalogue"},{"kind":"text","text":"("},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": () -> ())"}],"abstract":[{"type":"text","text":"Forces remote fetch of the catalogue. Regardless the locally stored version is upto date"},{"type":"text","text":" "},{"type":"text","text":"Useful when new app version is deployed to store and we want to update the local copy."}],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ProductsDataStoreManager\/forceRefetchCatalogue(completion:)","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/productsdatastoremanager\/forcerefetchcatalogue(completion:)"},"doc://com.yababaGmbH.yababa/documentation/Yababa/ProductsDataStoreManager/initiate()":{"role":"symbol","title":"initiate()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"initiate"},{"kind":"text","text":"()"}],"abstract":[{"type":"text","text":"Initializes the class by fetching the catalogue and setting up a timer to refresh the stock quantities every 30 seconds."}],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ProductsDataStoreManager\/initiate()","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/productsdatastoremanager\/initiate()"},"doc://com.yababaGmbH.yababa/documentation/Yababa/StoreManagerProtocol":{"role":"symbol","title":"StoreManagerProtocol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"StoreManagerProtocol"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/StoreManagerProtocol","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"StoreManagerProtocol"}],"url":"\/documentation\/yababa\/storemanagerprotocol"},"doc://com.yababaGmbH.yababa/documentation/Yababa/ProductsDataStoreManager/fetchCatalogue()":{"role":"symbol","title":"fetchCatalogue()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"fetchCatalogue"},{"kind":"text","text":"()"}],"abstract":[{"type":"text","text":"Non closure call to fetch the catalogue"}],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ProductsDataStoreManager\/fetchCatalogue()","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/productsdatastoremanager\/fetchcatalogue()"},"doc://com.yababaGmbH.yababa/documentation/Yababa/ProductsDataStoreManager/similarProductsTo(_:)":{"role":"symbol","title":"similarProductsTo(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"similarProductsTo"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Product","preciseIdentifier":"s:6Yababa7ProductC"},{"kind":"text","text":") -> ["},{"kind":"typeIdentifier","text":"Product","preciseIdentifier":"s:6Yababa7ProductC"},{"kind":"text","text":"]?"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ProductsDataStoreManager\/similarProductsTo(_:)","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/productsdatastoremanager\/similarproductsto(_:)"},"doc://com.yababaGmbH.yababa/documentation/Yababa":{"role":"collection","title":"Yababa","abstract":[{"type":"text","text":"Getting Started"}],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa","kind":"symbol","type":"topic","url":"\/documentation\/yababa"},"doc://com.yababaGmbH.yababa/documentation/Yababa/ProductsDataStoreManager/defaultInstance":{"role":"symbol","title":"defaultInstance","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"defaultInstance"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ProductsDataStoreManager","preciseIdentifier":"c:@M@Yababa@objc(cs)ProductsDataStoreManager"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ProductsDataStoreManager\/defaultInstance","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/productsdatastoremanager\/defaultinstance"},"doc://com.yababaGmbH.yababa/documentation/Yababa/ProductsDataStoreManager/fetchRemoteCatalogue(withLoader:completion:)":{"role":"symbol","title":"fetchRemoteCatalogue(withLoader:completion:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"fetchRemoteCatalogue"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withLoader"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": () -> ())"}],"abstract":[{"type":"text","text":"Fetches the remote version of the catalogue. Upon successful retrieval, updates the local version if the remote version is newer."},{"type":"text","text":" "},{"type":"text","text":"In case of failure, this method automatically retries 5 times"},{"type":"text","text":" "},{"type":"text","text":"If the remote version retrieval fails entirely, the method reverts to the local version and logs the error."}],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ProductsDataStoreManager\/fetchRemoteCatalogue(withLoader:completion:)","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/productsdatastoremanager\/fetchremotecatalogue(withloader:completion:)"},"doc://com.yababaGmbH.yababa/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)NSObject"},"doc://com.yababaGmbH.yababa/documentation/Yababa/ProductsDataStoreManager/productsMap":{"role":"symbol","title":"productsMap","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"productsMap"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"ProductPosition","preciseIdentifier":"s:6Yababa15ProductPositionV"},{"kind":"text","text":"]"}],"abstract":[{"type":"text","text":"A shortcut map of a given product’s location in the catalogue"},{"type":"text","text":" "},{"type":"text","text":"Given a product id, get product’s position in holding sub category and category"},{"type":"text","text":" "},{"type":"text","text":"Instead of nested looping in catalogue to find a particular product, use the result indices to access the desired product in catalogue array directly in O(1)"}],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ProductsDataStoreManager\/productsMap","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/productsdatastoremanager\/productsmap"},"doc://com.yababaGmbH.yababa/documentation/Yababa/ProductsDataStoreManager/quantityOfProductInStoreInventory(_:)":{"role":"symbol","title":"quantityOfProductInStoreInventory(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"quantityOfProductInStoreInventory"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"abstract":[{"type":"text","text":"Actual quantity of product in Store inventory"}],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ProductsDataStoreManager\/quantityOfProductInStoreInventory(_:)","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/productsdatastoremanager\/quantityofproductinstoreinventory(_:)"},"doc://com.yababaGmbH.yababa/documentation/Yababa/ProductsDataStoreManager/fetchCatalogue(completion:)":{"role":"symbol","title":"fetchCatalogue(completion:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"fetchCatalogue"},{"kind":"text","text":"("},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": () -> ())"}],"abstract":[{"type":"text","text":"Loads local copy of the catalogue into memory."},{"type":"text","text":" "},{"type":"text","text":"It then checks against the remote version, if a new version is available, it fetches and stores it"}],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ProductsDataStoreManager\/fetchCatalogue(completion:)","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/productsdatastoremanager\/fetchcatalogue(completion:)"},"doc://com.yababaGmbH.yababa/documentation/Yababa/ProductsDataStoreManager/defaultWarehouseId":{"role":"symbol","title":"defaultWarehouseId","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"defaultWarehouseId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"If user has not entered in an address. We use the default warehouse id"}],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ProductsDataStoreManager\/defaultWarehouseId","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/productsdatastoremanager\/defaultwarehouseid"},"doc://com.yababaGmbH.yababa/documentation/Yababa/ProductsDataStoreManager/buildProductsMap()":{"role":"symbol","title":"buildProductsMap()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"buildProductsMap"},{"kind":"text","text":"()"}],"abstract":[{"type":"text","text":"Builds a mapping of products to their precise location in catalogue"},{"type":"text","text":" "},{"type":"text","text":"This is helpful in accessing a specific product in catalogue directly (without lopping catalogue)"}],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ProductsDataStoreManager\/buildProductsMap()","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/productsdatastoremanager\/buildproductsmap()"},"doc://com.yababaGmbH.yababa/documentation/Yababa/ProductsDataStoreManager/fetchInventoryQuantities(completion:)":{"role":"symbol","title":"fetchInventoryQuantities(completion:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"fetchInventoryQuantities"},{"kind":"text","text":"("},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": () -> ())"}],"abstract":[{"type":"text","text":"Fetches product stock quantities from the server based on user’s location warehouse"},{"type":"text","text":" "},{"type":"text","text":"In case of failure, this method automatically retries 5 times"},{"type":"text","text":" "},{"type":"text","text":"If it fails after mutiple events, it logs the error."}],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ProductsDataStoreManager\/fetchInventoryQuantities(completion:)","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/productsdatastoremanager\/fetchinventoryquantities(completion:)"},"doc://com.yababaGmbH.yababa/documentation/Yababa/ProductsDataStoreManager/catalogue":{"role":"symbol","title":"catalogue","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"catalogue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Catalogue","preciseIdentifier":"s:6Yababa9Cataloguea"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"The actual catalogue object. Contains categories, with each category containing several sub categories."},{"type":"text","text":" "},{"type":"text","text":"Each  sub category contains a list of products"}],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ProductsDataStoreManager\/catalogue","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/productsdatastoremanager\/catalogue"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"ProductsDataStoreManager"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"ProductsDataStoreManager"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"ProductsDataStoreManager"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ProductsDataStoreManager\/init"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.yababaGmbH.yababa\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"ProductsDataStoreManager"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1ProductsDataStoreManager\/title","value":"ProductsDataStoreManager"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1ProductsDataStoreManager\/fragments","value":[{"kind":"identifier","text":"ProductsDataStoreManager"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}