{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"ProfileMenuItem"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/yababa\/profilemenuitem"],"traits":[{"interfaceLanguage":"swift"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AccountSettingsMenuItem","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ChatWithUsMenuItem","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ContactUsMenuItem","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/FAQMenuItem","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/InviteFriendsMenuItem","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/LanguageSelectionItem","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/LanguageSelectionMenuItem","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/MyFavouritesMenuItem","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/MyOrdersMenuItem","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/PrivacyPolicyMenuItem","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/TermsAndConditionsMenuItem"],"kind":"relationships","title":"Conforming Types","type":"conformingTypes"}],"identifier":{"url":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ProfileMenuItem","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ProfileMenuItem\/destinationController","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ProfileMenuItem\/icon","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ProfileMenuItem\/title","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ProfileMenuItem\/transitionStyle"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ProfileMenuItem\/launchIndependently(sender:)-18aun"]}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"ProfileMenuItem"}],"title":"ProfileMenuItem","roleHeading":"Protocol","role":"symbol","symbolKind":"protocol","externalID":"s:6Yababa15ProfileMenuItemP","modules":[{"name":"Yababa"}],"navigatorTitle":[{"kind":"identifier","text":"ProfileMenuItem"}]},"hierarchy":{"paths":[["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa"]]},"references":{"doc://com.yababaGmbH.yababa/documentation/Yababa/ProfileMenuItem/launchIndependently(sender:)-18aun":{"defaultImplementations":1,"role":"symbol","title":"launchIndependently(sender:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"launchIndependently"},{"kind":"text","text":"("},{"kind":"externalParam","text":"sender"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ProfileMenuItem\/launchIndependently(sender:)-18aun","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/yababa\/profilemenuitem\/launchindependently(sender:)-18aun"},"doc://com.yababaGmbH.yababa/documentation/Yababa/MyFavouritesMenuItem":{"role":"symbol","title":"MyFavouritesMenuItem","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"MyFavouritesMenuItem"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/MyFavouritesMenuItem","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MyFavouritesMenuItem"}],"url":"\/documentation\/yababa\/myfavouritesmenuitem"},"doc://com.yababaGmbH.yababa/documentation/Yababa/ProfileMenuItem":{"role":"symbol","title":"ProfileMenuItem","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"ProfileMenuItem"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ProfileMenuItem","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ProfileMenuItem"}],"url":"\/documentation\/yababa\/profilemenuitem"},"doc://com.yababaGmbH.yababa/documentation/Yababa/ChatWithUsMenuItem":{"role":"symbol","title":"ChatWithUsMenuItem","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChatWithUsMenuItem"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ChatWithUsMenuItem","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ChatWithUsMenuItem"}],"url":"\/documentation\/yababa\/chatwithusmenuitem"},"doc://com.yababaGmbH.yababa/documentation/Yababa/TermsAndConditionsMenuItem":{"role":"symbol","title":"TermsAndConditionsMenuItem","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"TermsAndConditionsMenuItem"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/TermsAndConditionsMenuItem","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"TermsAndConditionsMenuItem"}],"url":"\/documentation\/yababa\/termsandconditionsmenuitem"},"doc://com.yababaGmbH.yababa/documentation/Yababa/ProfileMenuItem/transitionStyle":{"role":"symbol","title":"transitionStyle","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"transitionStyle"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ShowTransitionStyle","preciseIdentifier":"s:6Yababa19ShowTransitionStyleO"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ProfileMenuItem\/transitionStyle","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/yababa\/profilemenuitem\/transitionstyle"},"doc://com.yababaGmbH.yababa/documentation/Yababa":{"role":"collection","title":"Yababa","abstract":[{"type":"text","text":"Getting Started"}],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa","kind":"symbol","type":"topic","url":"\/documentation\/yababa"},"doc://com.yababaGmbH.yababa/documentation/Yababa/ContactUsMenuItem":{"role":"symbol","title":"ContactUsMenuItem","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ContactUsMenuItem"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ContactUsMenuItem","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ContactUsMenuItem"}],"url":"\/documentation\/yababa\/contactusmenuitem"},"doc://com.yababaGmbH.yababa/documentation/Yababa/FAQMenuItem":{"role":"symbol","title":"FAQMenuItem","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"FAQMenuItem"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/FAQMenuItem","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FAQMenuItem"}],"url":"\/documentation\/yababa\/faqmenuitem"},"doc://com.yababaGmbH.yababa/documentation/Yababa/PrivacyPolicyMenuItem":{"role":"symbol","title":"PrivacyPolicyMenuItem","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"PrivacyPolicyMenuItem"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/PrivacyPolicyMenuItem","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PrivacyPolicyMenuItem"}],"url":"\/documentation\/yababa\/privacypolicymenuitem"},"doc://com.yababaGmbH.yababa/documentation/Yababa/LanguageSelectionMenuItem":{"role":"symbol","title":"LanguageSelectionMenuItem","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"LanguageSelectionMenuItem"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/LanguageSelectionMenuItem","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"LanguageSelectionMenuItem"}],"url":"\/documentation\/yababa\/languageselectionmenuitem"},"doc://com.yababaGmbH.yababa/documentation/Yababa/AccountSettingsMenuItem":{"role":"symbol","title":"AccountSettingsMenuItem","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"AccountSettingsMenuItem"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AccountSettingsMenuItem","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AccountSettingsMenuItem"}],"url":"\/documentation\/yababa\/accountsettingsmenuitem"},"doc://com.yababaGmbH.yababa/documentation/Yababa/ProfileMenuItem/title":{"role":"symbol","title":"title","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"title"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ProfileMenuItem\/title","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/yababa\/profilemenuitem\/title"},"doc://com.yababaGmbH.yababa/documentation/Yababa/MyOrdersMenuItem":{"role":"symbol","title":"MyOrdersMenuItem","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"MyOrdersMenuItem"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/MyOrdersMenuItem","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MyOrdersMenuItem"}],"url":"\/documentation\/yababa\/myordersmenuitem"},"doc://com.yababaGmbH.yababa/documentation/Yababa/ProfileMenuItem/destinationController":{"role":"symbol","title":"destinationController","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"destinationController"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ProfileMenuItem\/destinationController","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/yababa\/profilemenuitem\/destinationcontroller"},"doc://com.yababaGmbH.yababa/documentation/Yababa/InviteFriendsMenuItem":{"role":"symbol","title":"InviteFriendsMenuItem","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"InviteFriendsMenuItem"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/InviteFriendsMenuItem","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"InviteFriendsMenuItem"}],"url":"\/documentation\/yababa\/invitefriendsmenuitem"},"doc://com.yababaGmbH.yababa/documentation/Yababa/LanguageSelectionItem":{"role":"symbol","title":"LanguageSelectionItem","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"LanguageSelectionItem"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/LanguageSelectionItem","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"LanguageSelectionItem"}],"url":"\/documentation\/yababa\/languageselectionitem"},"doc://com.yababaGmbH.yababa/documentation/Yababa/ProfileMenuItem/icon":{"role":"symbol","title":"icon","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"icon"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ProfileMenuItem\/icon","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/yababa\/profilemenuitem\/icon"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1ChatWithUsMenuItem\/title","value":"ChatWithUsMenuItem"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1ChatWithUsMenuItem\/fragments","value":[{"kind":"identifier","text":"ChatWithUsMenuItem"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1ContactUsMenuItem\/title","value":"ContactUsMenuItem"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1ContactUsMenuItem\/fragments","value":[{"kind":"identifier","text":"ContactUsMenuItem"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}