{"primaryContentSections":[{"kind":"content","content":[{"anchor":"Overview","level":2,"type":"heading","text":"Overview"},{"type":"paragraph","inlineContent":[{"type":"text","text":"This documentation provides an overview of the process for requesting permission and receiving push notifications in the iOS app. The main class responsible for managing push notifications is the "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/PushNotificationsManager"},{"type":"text","text":", which coordinates all aspects of push notifications. Additionally, Braze plays a crucial role in the process by sending updates on promotions, while the backend uses notifications to provide information about order status."}]},{"anchor":"Requesting-Permission","level":2,"type":"heading","text":"Requesting Permission"},{"type":"paragraph","inlineContent":[{"type":"image","identifier":"PushNotificationFlow.png"}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"The process for requesting permission for push notifications involves two steps. Firstly, the app displays an In-App Message to the user, explaining the benefits of enabling push notifications. This is known as the Soft-Opt-In. The Braze platform is used to design and configure the display of this popup message, which can be triggered based on certain criteria. For instance, the Soft-Opt-In can be triggered when a user successfully completes a checkout. The app sends analytic events to Braze, which enables it to track the user’s journey (see "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AnalyticsDocumentation"},{"type":"text","text":")."}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"Once the user taps “Yes” on the Soft-Opt-In, the PushNotification Manager requests the "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/PushNotificationInteractor"},{"type":"text","text":" to prompt the Hard-Opt-In. This is the native permissions popup that appears on the device, asking the user if they would like to receive push notifications from the app. If the user agrees, the app registers with Apple Push Notification service (APNs) to receive notifications. "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/PushNotificationsManager"},{"type":"text","text":" then communicates with "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/BrazeManager"},{"type":"text","text":" to update the permission status in Braze, which keeps track of users who have granted permission for push notifications."}]},{"style":"note","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Follow the dark pink outline to see the flow of requesting permission in the diagram above."}]}],"type":"aside","name":"Info"},{"style":"note","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"If the user declines to Hard-Opt-In, he\/she can give permissions through the"},{"type":"text","text":" "},{"type":"text","text":"Profile -> Account Settings -> Notifications Toggle"}]}],"type":"aside","name":"Note"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/yababa\/pushnotificationsdocumentation"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/yababa\/pushnotificationsdocumentation"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/PushNotificationsDocumentation","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Requesting permission for Push Notifications and receiving them"}],"kind":"article","metadata":{"roleHeading":"Article","title":"Push Notifications Manager","role":"collectionGroup","modules":[{"name":"Yababa"}]},"hierarchy":{"paths":[["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa"]]},"seeAlsoSections":[{"title":"User Access","identifiers":["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/User-Login","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AddressManagerDocumentation","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/UserStateManager"],"generated":true}],"references":{"doc://com.yababaGmbH.yababa/documentation/Yababa/PushNotificationsManager":{"role":"symbol","title":"PushNotificationsManager","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PushNotificationsManager"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/PushNotificationsManager","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PushNotificationsManager"}],"url":"\/documentation\/yababa\/pushnotificationsmanager"},"PushNotificationFlow.png":{"alt":"PushNotificationsFlow","type":"image","identifier":"PushNotificationFlow.png","variants":[{"url":"\/images\/PushNotificationFlow@2x.png","traits":["2x","light"]}]},"doc://com.yababaGmbH.yababa/documentation/Yababa/AnalyticsDocumentation":{"role":"article","title":"Analytics Manager","abstract":[{"type":"text","text":"Responsible for collecting events about user behavior and forwarding to third party analytics platforms."}],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AnalyticsDocumentation","kind":"article","type":"topic","url":"\/documentation\/yababa\/analyticsdocumentation"},"doc://com.yababaGmbH.yababa/documentation/Yababa/PushNotificationInteractor":{"role":"symbol","title":"PushNotificationInteractor","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PushNotificationInteractor"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/PushNotificationInteractor","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PushNotificationInteractor"}],"url":"\/documentation\/yababa\/pushnotificationinteractor"},"doc://com.yababaGmbH.yababa/documentation/Yababa/AddressManagerDocumentation":{"role":"article","title":"Address Managing Module","abstract":[{"type":"text","text":"Manages user delivery addresses. Allows user to add new address and validate existing ones"}],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AddressManagerDocumentation","kind":"article","type":"topic","url":"\/documentation\/yababa\/addressmanagerdocumentation"},"doc://com.yababaGmbH.yababa/documentation/Yababa/User-Login":{"role":"article","title":"User Login","abstract":[{"type":"text","text":"Covers user login and signup journey through Email and Social login methods"}],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/User-Login","kind":"article","type":"topic","url":"\/documentation\/yababa\/user-login"},"doc://com.yababaGmbH.yababa/documentation/Yababa/UserStateManager":{"role":"symbol","title":"UserStateManager","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"UserStateManager"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"LocalUserStateManager","preciseIdentifier":"c:@M@Yababa@objc(cs)LocalUserStateManager"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/UserStateManager","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/userstatemanager"},"doc://com.yababaGmbH.yababa/documentation/Yababa":{"role":"collection","title":"Yababa","abstract":[{"type":"text","text":"Getting Started"}],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa","kind":"symbol","type":"topic","url":"\/documentation\/yababa"},"doc://com.yababaGmbH.yababa/documentation/Yababa/BrazeManager":{"role":"symbol","title":"BrazeManager","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"BrazeManager"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/BrazeManager","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"BrazeManager"}],"url":"\/documentation\/yababa\/brazemanager"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/topicSections","value":null},{"op":"replace","path":"\/seeAlsoSections","value":[{"title":"User Access","identifiers":["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/User-Login","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AddressManagerDocumentation"],"generated":true}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1PushNotificationsManager\/title","value":"PushNotificationsManager"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1PushNotificationsManager\/fragments","value":[{"kind":"identifier","text":"PushNotificationsManager"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1PushNotificationInteractor\/title","value":"PushNotificationInteractor"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1PushNotificationInteractor\/fragments","value":[{"kind":"identifier","text":"PushNotificationInteractor"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1BrazeManager\/title","value":"BrazeManager"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1BrazeManager\/fragments","value":[{"kind":"identifier","text":"BrazeManager"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}