{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objcMembers"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"RemoteConfigManager"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/yababa\/remoteconfigmanager"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/yababa\/remoteconfigmanager"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.yababaGmbH.yababa\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.yababaGmbH.yababa\/objc(pl)NSObject","doc:\/\/com.yababaGmbH.yababa\/12SkeletonView17AssociatedObjectsP","doc:\/\/com.yababaGmbH.yababa\/s7CVarArgP","doc:\/\/com.yababaGmbH.yababa\/s28CustomDebugStringConvertibleP","doc:\/\/com.yababaGmbH.yababa\/s23CustomStringConvertibleP","doc:\/\/com.yababaGmbH.yababa\/SQ","doc:\/\/com.yababaGmbH.yababa\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/RemoteConfigManager","interfaceLanguage":"swift"},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/RemoteConfigManager\/init()"]},{"title":"Instance Properties","identifiers":["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/RemoteConfigManager\/ConfigFetchTimeout","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/RemoteConfigManager\/configFetched","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/RemoteConfigManager\/configStore"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/RemoteConfigManager\/fetchAndActivate(completion:)","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/RemoteConfigManager\/getCartGamification()","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/RemoteConfigManager\/getCashPayment()","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/RemoteConfigManager\/getFirstPage()","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/RemoteConfigManager\/getStartPage()"]},{"title":"Type Properties","identifiers":["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/RemoteConfigManager\/shared"]}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"RemoteConfigManager"}],"title":"RemoteConfigManager","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@Yababa@objc(cs)RemoteConfigManager","modules":[{"name":"Yababa"}],"navigatorTitle":[{"kind":"identifier","text":"RemoteConfigManager"}]},"hierarchy":{"paths":[["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa"]]},"references":{"doc://com.yababaGmbH.yababa/documentation/Yababa/RemoteConfigManager/getCashPayment()":{"role":"symbol","title":"getCashPayment()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getCashPayment"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"FeatureFlag","preciseIdentifier":"s:6Yababa11FeatureFlagO"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"CashPayment","preciseIdentifier":"s:6Yababa11FeatureFlagO11CashPaymentO"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/RemoteConfigManager\/getCashPayment()","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/remoteconfigmanager\/getcashpayment()"},"doc://com.yababaGmbH.yababa/documentation/Yababa/RemoteConfigManager/fetchAndActivate(completion:)":{"role":"symbol","title":"fetchAndActivate(completion:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"fetchAndActivate"},{"kind":"text","text":"("},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": ("},{"kind":"typeIdentifier","text":"RemoteConfigFetchAndActivateStatus","preciseIdentifier":"c:@E@FIRRemoteConfigFetchAndActivateStatus"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/RemoteConfigManager\/fetchAndActivate(completion:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"fetchAndActivateWithCompletion:"}],"url":"\/documentation\/yababa\/remoteconfigmanager\/fetchandactivate(completion:)"},"doc://com.yababaGmbH.yababa/documentation/Yababa/RemoteConfigManager/getStartPage()":{"role":"symbol","title":"getStartPage()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getStartPage"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"FeatureFlag","preciseIdentifier":"s:6Yababa11FeatureFlagO"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"StartPage","preciseIdentifier":"s:6Yababa11FeatureFlagO9StartPageO"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/RemoteConfigManager\/getStartPage()","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/remoteconfigmanager\/getstartpage()"},"doc://com.yababaGmbH.yababa/documentation/Yababa/RemoteConfigManager/getCartGamification()":{"role":"symbol","title":"getCartGamification()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getCartGamification"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"FeatureFlag","preciseIdentifier":"s:6Yababa11FeatureFlagO"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"CartGamification","preciseIdentifier":"s:6Yababa11FeatureFlagO16CartGamificationO"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/RemoteConfigManager\/getCartGamification()","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/remoteconfigmanager\/getcartgamification()"},"doc://com.yababaGmbH.yababa/12SkeletonView17AssociatedObjectsP":{"type":"unresolvable","title":"SkeletonView.AssociatedObjects","identifier":"doc:\/\/com.yababaGmbH.yababa\/12SkeletonView17AssociatedObjectsP"},"doc://com.yababaGmbH.yababa/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.yababaGmbH.yababa\/s28CustomDebugStringConvertibleP"},"doc://com.yababaGmbH.yababa/documentation/Yababa/RemoteConfigManager/init()":{"role":"symbol","title":"init()","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/RemoteConfigManager\/init()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"init"}],"url":"\/documentation\/yababa\/remoteconfigmanager\/init()"},"doc://com.yababaGmbH.yababa/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)NSObject"},"doc://com.yababaGmbH.yababa/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(cs)NSObject"},"doc://com.yababaGmbH.yababa/documentation/Yababa/RemoteConfigManager/configStore":{"role":"symbol","title":"configStore","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"configStore"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ConfigStore","preciseIdentifier":"s:6Yababa11ConfigStoreP"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/RemoteConfigManager\/configStore","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/remoteconfigmanager\/configstore"},"doc://com.yababaGmbH.yababa/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.yababaGmbH.yababa\/s7CVarArgP"},"doc://com.yababaGmbH.yababa/documentation/Yababa/RemoteConfigManager/ConfigFetchTimeout":{"role":"symbol","title":"ConfigFetchTimeout","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"ConfigFetchTimeout"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/RemoteConfigManager\/ConfigFetchTimeout","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ConfigFetchTimeout"}],"url":"\/documentation\/yababa\/remoteconfigmanager\/configfetchtimeout"},"doc://com.yababaGmbH.yababa/documentation/Yababa/RemoteConfigManager":{"role":"symbol","title":"RemoteConfigManager","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"RemoteConfigManager"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/RemoteConfigManager","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"RemoteConfigManager"}],"url":"\/documentation\/yababa\/remoteconfigmanager"},"doc://com.yababaGmbH.yababa/documentation/Yababa":{"role":"collection","title":"Yababa","abstract":[{"type":"text","text":"Getting Started"}],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa","kind":"symbol","type":"topic","url":"\/documentation\/yababa"},"doc://com.yababaGmbH.yababa/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.yababaGmbH.yababa\/SH"},"doc://com.yababaGmbH.yababa/documentation/Yababa/RemoteConfigManager/shared":{"role":"symbol","title":"shared","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"shared"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"RemoteConfigManager","preciseIdentifier":"c:@M@Yababa@objc(cs)RemoteConfigManager"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/RemoteConfigManager\/shared","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"shared"}],"url":"\/documentation\/yababa\/remoteconfigmanager\/shared"},"doc://com.yababaGmbH.yababa/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.yababaGmbH.yababa\/SQ"},"doc://com.yababaGmbH.yababa/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.yababaGmbH.yababa\/s23CustomStringConvertibleP"},"doc://com.yababaGmbH.yababa/documentation/Yababa/RemoteConfigManager/getFirstPage()":{"role":"symbol","title":"getFirstPage()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getFirstPage"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"FeatureFlag","preciseIdentifier":"s:6Yababa11FeatureFlagO"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"FirstPage","preciseIdentifier":"s:6Yababa11FeatureFlagO9FirstPageO"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/RemoteConfigManager\/getFirstPage()","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/remoteconfigmanager\/getfirstpage()"},"doc://com.yababaGmbH.yababa/documentation/Yababa/RemoteConfigManager/configFetched":{"role":"symbol","title":"configFetched","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"configFetched"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/RemoteConfigManager\/configFetched","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"configFetched"}],"url":"\/documentation\/yababa\/remoteconfigmanager\/configfetched"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"RemoteConfigManager"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"RemoteConfigManager"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"RemoteConfigManager"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/RemoteConfigManager\/ConfigFetchTimeout","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/RemoteConfigManager\/configFetched"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/RemoteConfigManager\/fetchAndActivate(completion:)","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/RemoteConfigManager\/init()"]},{"title":"Type Properties","identifiers":["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/RemoteConfigManager\/shared"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.yababaGmbH.yababa\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"RemoteConfigManager"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1RemoteConfigManager~1fetchAndActivate(completion:)\/title","value":"fetchAndActivateWithCompletion:"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1RemoteConfigManager~1fetchAndActivate(completion:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"fetchAndActivateWithCompletion:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1RemoteConfigManager~1init()\/title","value":"init"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1RemoteConfigManager~1init()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1RemoteConfigManager~1ConfigFetchTimeout\/title","value":"ConfigFetchTimeout"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1RemoteConfigManager~1ConfigFetchTimeout\/fragments","value":[{"kind":"identifier","text":"ConfigFetchTimeout"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1RemoteConfigManager\/title","value":"RemoteConfigManager"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1RemoteConfigManager\/fragments","value":[{"kind":"identifier","text":"RemoteConfigManager"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1RemoteConfigManager~1shared\/title","value":"shared"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1RemoteConfigManager~1shared\/fragments","value":[{"kind":"identifier","text":"shared"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1RemoteConfigManager~1configFetched\/title","value":"configFetched"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1RemoteConfigManager~1configFetched\/fragments","value":[{"kind":"identifier","text":"configFetched"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}