{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ShoppingCartSceneViewController"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/yababa\/shoppingcartsceneviewcontroller"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/yababa\/shoppingcartsceneviewcontroller"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/MasterViewController"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CompleteProfileVCDelegate","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/DynamicLayoutItemSelectionDelegate","doc:\/\/com.yababaGmbH.yababa\/objc(pl)NSCoding","doc:\/\/com.yababaGmbH.yababa\/objc(pl)NSExtensionRequestHandling","doc:\/\/com.yababaGmbH.yababa\/objc(pl)NSObject","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/PresenterToViewCartProtocol","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ShoppingCartObserver","doc:\/\/com.yababaGmbH.yababa\/12SkeletonView17AssociatedObjectsP","doc:\/\/com.yababaGmbH.yababa\/s7CVarArgP","doc:\/\/com.yababaGmbH.yababa\/s28CustomDebugStringConvertibleP","doc:\/\/com.yababaGmbH.yababa\/s23CustomStringConvertibleP","doc:\/\/com.yababaGmbH.yababa\/SQ","doc:\/\/com.yababaGmbH.yababa\/SH","doc:\/\/com.yababaGmbH.yababa\/s8SendableP","doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIActivityItemsConfigurationProviding","doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIAppearanceContainer","doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIContentContainer","doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIFocusEnvironment","doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIPasteConfigurationSupporting","doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIResponderStandardEditActions","doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIScrollViewDelegate","doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIStateRestoring","doc:\/\/com.yababaGmbH.yababa\/objc(pl)UITableViewDataSource","doc:\/\/com.yababaGmbH.yababa\/objc(pl)UITableViewDelegate","doc:\/\/com.yababaGmbH.yababa\/objc(pl)UITraitEnvironment","doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIUserActivityRestoring"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ShoppingCartSceneViewController","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ShoppingCartSceneViewController\/clearBtn","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ShoppingCartSceneViewController\/interactor","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ShoppingCartSceneViewController\/router"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ShoppingCartSceneViewController\/heightForHeaderInSection(_:)","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ShoppingCartSceneViewController\/heightForRowAtIndexPath(_:)","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ShoppingCartSceneViewController\/numberOfRowsInSection(_:)","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ShoppingCartSceneViewController\/onBack()","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ShoppingCartSceneViewController\/onCheckout()","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ShoppingCartSceneViewController\/onClearCart()","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ShoppingCartSceneViewController\/onStartShopping()","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ShoppingCartSceneViewController\/refreshUI()","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ShoppingCartSceneViewController\/setEmptyCartMessages()","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ShoppingCartSceneViewController\/setIdentifiers()","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ShoppingCartSceneViewController\/setupNavigationBarItems()","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ShoppingCartSceneViewController\/unSubscribeFromShoppingCart()","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ShoppingCartSceneViewController\/updateCartProgress()","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ShoppingCartSceneViewController\/viewDidAppear(_:)","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ShoppingCartSceneViewController\/viewDidLayoutSubviews()","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ShoppingCartSceneViewController\/viewDidLoad()","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ShoppingCartSceneViewController\/viewWillAppear(_:)"]},{"title":"Default Implementations","identifiers":["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ShoppingCartSceneViewController\/CompleteProfileVCDelegate-Implementations","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ShoppingCartSceneViewController\/ShoppingCartObserver-Implementations","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ShoppingCartSceneViewController\/UITableViewDataSource-Implementations","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ShoppingCartSceneViewController\/UITableViewDelegate-Implementations"],"generated":true}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ShoppingCartSceneViewController"}],"title":"ShoppingCartSceneViewController","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@Yababa@objc(cs)ShoppingCartSceneViewController","modules":[{"name":"Yababa"}],"navigatorTitle":[{"kind":"identifier","text":"ShoppingCartSceneViewController"}]},"hierarchy":{"paths":[["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa"]]},"references":{"doc://com.yababaGmbH.yababa/documentation/Yababa/ShoppingCartSceneViewController/UITableViewDataSource-Implementations":{"role":"collectionGroup","title":"UITableViewDataSource Implementations","abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ShoppingCartSceneViewController\/UITableViewDataSource-Implementations","kind":"article","type":"topic","url":"\/documentation\/yababa\/shoppingcartsceneviewcontroller\/uitableviewdatasource-implementations"},"doc://com.yababaGmbH.yababa/documentation/Yababa/ShoppingCartSceneViewController/viewDidLayoutSubviews()":{"role":"symbol","title":"viewDidLayoutSubviews()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"viewDidLayoutSubviews"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ShoppingCartSceneViewController\/viewDidLayoutSubviews()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"viewDidLayoutSubviews"}],"url":"\/documentation\/yababa\/shoppingcartsceneviewcontroller\/viewdidlayoutsubviews()"},"doc://com.yababaGmbH.yababa/documentation/Yababa/ShoppingCartSceneViewController/viewWillAppear(_:)":{"role":"symbol","title":"viewWillAppear(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"viewWillAppear"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ShoppingCartSceneViewController\/viewWillAppear(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"viewWillAppear:"}],"url":"\/documentation\/yababa\/shoppingcartsceneviewcontroller\/viewwillappear(_:)"},"doc://com.yababaGmbH.yababa/objc(pl)UIContentContainer":{"type":"unresolvable","title":"UIKit.UIContentContainer","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIContentContainer"},"doc://com.yababaGmbH.yababa/documentation/Yababa/ShoppingCartSceneViewController/numberOfRowsInSection(_:)":{"role":"symbol","title":"numberOfRowsInSection(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"numberOfRowsInSection"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ShoppingCartSceneViewController\/numberOfRowsInSection(_:)","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/shoppingcartsceneviewcontroller\/numberofrowsinsection(_:)"},"doc://com.yababaGmbH.yababa/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.yababaGmbH.yababa\/s23CustomStringConvertibleP"},"doc://com.yababaGmbH.yababa/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.yababaGmbH.yababa\/s28CustomDebugStringConvertibleP"},"doc://com.yababaGmbH.yababa/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)NSObject"},"doc://com.yababaGmbH.yababa/documentation/Yababa/ShoppingCartObserver":{"role":"symbol","title":"ShoppingCartObserver","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"ShoppingCartObserver"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ShoppingCartObserver","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ShoppingCartObserver"}],"url":"\/documentation\/yababa\/shoppingcartobserver"},"doc://com.yababaGmbH.yababa/objc(pl)UIScrollViewDelegate":{"type":"unresolvable","title":"UIKit.UIScrollViewDelegate","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIScrollViewDelegate"},"doc://com.yababaGmbH.yababa/objc(pl)NSCoding":{"type":"unresolvable","title":"Foundation.NSCoding","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)NSCoding"},"doc://com.yababaGmbH.yababa/12SkeletonView17AssociatedObjectsP":{"type":"unresolvable","title":"SkeletonView.AssociatedObjects","identifier":"doc:\/\/com.yababaGmbH.yababa\/12SkeletonView17AssociatedObjectsP"},"doc://com.yababaGmbH.yababa/documentation/Yababa/ShoppingCartSceneViewController/updateCartProgress()":{"role":"symbol","title":"updateCartProgress()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"updateCartProgress"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ShoppingCartSceneViewController\/updateCartProgress()","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/shoppingcartsceneviewcontroller\/updatecartprogress()"},"doc://com.yababaGmbH.yababa/documentation/Yababa/ShoppingCartSceneViewController/heightForHeaderInSection(_:)":{"role":"symbol","title":"heightForHeaderInSection(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"heightForHeaderInSection"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ShoppingCartSceneViewController\/heightForHeaderInSection(_:)","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/shoppingcartsceneviewcontroller\/heightforheaderinsection(_:)"},"doc://com.yababaGmbH.yababa/objc(pl)UIPasteConfigurationSupporting":{"type":"unresolvable","title":"UIKit.UIPasteConfigurationSupporting","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIPasteConfigurationSupporting"},"doc://com.yababaGmbH.yababa/documentation/Yababa/CompleteProfileVCDelegate":{"role":"symbol","title":"CompleteProfileVCDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"CompleteProfileVCDelegate"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CompleteProfileVCDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CompleteProfileVCDelegate"}],"url":"\/documentation\/yababa\/completeprofilevcdelegate"},"doc://com.yababaGmbH.yababa/objc(pl)UITraitEnvironment":{"type":"unresolvable","title":"UIKit.UITraitEnvironment","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)UITraitEnvironment"},"doc://com.yababaGmbH.yababa/documentation/Yababa/ShoppingCartSceneViewController":{"role":"symbol","title":"ShoppingCartSceneViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ShoppingCartSceneViewController"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ShoppingCartSceneViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ShoppingCartSceneViewController"}],"url":"\/documentation\/yababa\/shoppingcartsceneviewcontroller"},"doc://com.yababaGmbH.yababa/documentation/Yababa/ShoppingCartSceneViewController/interactor":{"role":"symbol","title":"interactor","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"interactor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ViewControllerToInteractorCartProtocol","preciseIdentifier":"s:6Yababa38ViewControllerToInteractorCartProtocolP"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ShoppingCartSceneViewController\/interactor","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/shoppingcartsceneviewcontroller\/interactor"},"doc://com.yababaGmbH.yababa/objc(pl)UITableViewDelegate":{"type":"unresolvable","title":"UIKit.UITableViewDelegate","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)UITableViewDelegate"},"doc://com.yababaGmbH.yababa/documentation/Yababa/ShoppingCartSceneViewController/viewDidAppear(_:)":{"role":"symbol","title":"viewDidAppear(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"viewDidAppear"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ShoppingCartSceneViewController\/viewDidAppear(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"viewDidAppear:"}],"url":"\/documentation\/yababa\/shoppingcartsceneviewcontroller\/viewdidappear(_:)"},"doc://com.yababaGmbH.yababa/documentation/Yababa/DynamicLayoutItemSelectionDelegate":{"role":"symbol","title":"DynamicLayoutItemSelectionDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"DynamicLayoutItemSelectionDelegate"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/DynamicLayoutItemSelectionDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DynamicLayoutItemSelectionDelegate"}],"url":"\/documentation\/yababa\/dynamiclayoutitemselectiondelegate"},"doc://com.yababaGmbH.yababa/objc(pl)UIUserActivityRestoring":{"type":"unresolvable","title":"UIKit.UIUserActivityRestoring","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIUserActivityRestoring"},"doc://com.yababaGmbH.yababa/objc(pl)NSExtensionRequestHandling":{"type":"unresolvable","title":"Foundation.NSExtensionRequestHandling","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)NSExtensionRequestHandling"},"doc://com.yababaGmbH.yababa/documentation/Yababa/ShoppingCartSceneViewController/onStartShopping()":{"role":"symbol","title":"onStartShopping()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onStartShopping"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ShoppingCartSceneViewController\/onStartShopping()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"onStartShopping"}],"url":"\/documentation\/yababa\/shoppingcartsceneviewcontroller\/onstartshopping()"},"doc://com.yababaGmbH.yababa/documentation/Yababa/ShoppingCartSceneViewController/onClearCart()":{"role":"symbol","title":"onClearCart()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onClearCart"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ShoppingCartSceneViewController\/onClearCart()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"onClearCart"}],"url":"\/documentation\/yababa\/shoppingcartsceneviewcontroller\/onclearcart()"},"doc://com.yababaGmbH.yababa/objc(pl)UITableViewDataSource":{"type":"unresolvable","title":"UIKit.UITableViewDataSource","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)UITableViewDataSource"},"doc://com.yababaGmbH.yababa/documentation/Yababa/ShoppingCartSceneViewController/router":{"role":"symbol","title":"router","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"router"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ViewControllerToRouterCartProtocol","preciseIdentifier":"s:6Yababa34ViewControllerToRouterCartProtocolP"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ShoppingCartSceneViewController\/router","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/shoppingcartsceneviewcontroller\/router"},"doc://com.yababaGmbH.yababa/documentation/Yababa/PresenterToViewCartProtocol":{"role":"symbol","title":"PresenterToViewCartProtocol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"PresenterToViewCartProtocol"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/PresenterToViewCartProtocol","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PresenterToViewCartProtocol"}],"url":"\/documentation\/yababa\/presentertoviewcartprotocol"},"doc://com.yababaGmbH.yababa/documentation/Yababa/ShoppingCartSceneViewController/viewDidLoad()":{"role":"symbol","title":"viewDidLoad()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"viewDidLoad"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ShoppingCartSceneViewController\/viewDidLoad()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"viewDidLoad"}],"url":"\/documentation\/yababa\/shoppingcartsceneviewcontroller\/viewdidload()"},"doc://com.yababaGmbH.yababa/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.yababaGmbH.yababa\/s7CVarArgP"},"doc://com.yababaGmbH.yababa/documentation/Yababa/ShoppingCartSceneViewController/setupNavigationBarItems()":{"role":"symbol","title":"setupNavigationBarItems()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setupNavigationBarItems"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ShoppingCartSceneViewController\/setupNavigationBarItems()","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/shoppingcartsceneviewcontroller\/setupnavigationbaritems()"},"doc://com.yababaGmbH.yababa/documentation/Yababa/ShoppingCartSceneViewController/refreshUI()":{"role":"symbol","title":"refreshUI()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"refreshUI"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ShoppingCartSceneViewController\/refreshUI()","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/shoppingcartsceneviewcontroller\/refreshui()"},"doc://com.yababaGmbH.yababa/documentation/Yababa":{"role":"collection","title":"Yababa","abstract":[{"type":"text","text":"Getting Started"}],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa","kind":"symbol","type":"topic","url":"\/documentation\/yababa"},"doc://com.yababaGmbH.yababa/documentation/Yababa/ShoppingCartSceneViewController/initWithCoder:":{"role":"symbol","title":"initWithCoder:","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithCoder:"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ShoppingCartSceneViewController\/initWithCoder:","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithCoder:"}],"url":"\/documentation\/yababa\/shoppingcartsceneviewcontroller\/initwithcoder:"},"doc://com.yababaGmbH.yababa/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.yababaGmbH.yababa\/SH"},"doc://com.yababaGmbH.yababa/objc(pl)UIResponderStandardEditActions":{"type":"unresolvable","title":"UIKit.UIResponderStandardEditActions","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIResponderStandardEditActions"},"doc://com.yababaGmbH.yababa/documentation/Yababa/ShoppingCartSceneViewController/ShoppingCartObserver-Implementations":{"role":"collectionGroup","title":"ShoppingCartObserver Implementations","abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ShoppingCartSceneViewController\/ShoppingCartObserver-Implementations","kind":"article","type":"topic","url":"\/documentation\/yababa\/shoppingcartsceneviewcontroller\/shoppingcartobserver-implementations"},"doc://com.yababaGmbH.yababa/documentation/Yababa/ShoppingCartSceneViewController/initWithNibName:bundle:":{"role":"symbol","title":"initWithNibName:bundle:","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithNibName:bundle:"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ShoppingCartSceneViewController\/initWithNibName:bundle:","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithNibName:bundle:"}],"url":"\/documentation\/yababa\/shoppingcartsceneviewcontroller\/initwithnibname:bundle:"},"doc://com.yababaGmbH.yababa/documentation/Yababa/ShoppingCartSceneViewController/heightForRowAtIndexPath(_:)":{"role":"symbol","title":"heightForRowAtIndexPath(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"heightForRowAtIndexPath"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"IndexPath","preciseIdentifier":"s:10Foundation9IndexPathV"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ShoppingCartSceneViewController\/heightForRowAtIndexPath(_:)","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/shoppingcartsceneviewcontroller\/heightforrowatindexpath(_:)"},"doc://com.yababaGmbH.yababa/documentation/Yababa/ShoppingCartSceneViewController/onCheckout()":{"role":"symbol","title":"onCheckout()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onCheckout"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ShoppingCartSceneViewController\/onCheckout()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"onCheckout"}],"url":"\/documentation\/yababa\/shoppingcartsceneviewcontroller\/oncheckout()"},"doc://com.yababaGmbH.yababa/objc(pl)UIActivityItemsConfigurationProviding":{"type":"unresolvable","title":"UIKit.UIActivityItemsConfigurationProviding","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIActivityItemsConfigurationProviding"},"doc://com.yababaGmbH.yababa/documentation/Yababa/ShoppingCartSceneViewController/CompleteProfileVCDelegate-Implementations":{"role":"collectionGroup","title":"CompleteProfileVCDelegate Implementations","abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ShoppingCartSceneViewController\/CompleteProfileVCDelegate-Implementations","kind":"article","type":"topic","url":"\/documentation\/yababa\/shoppingcartsceneviewcontroller\/completeprofilevcdelegate-implementations"},"doc://com.yababaGmbH.yababa/objc(pl)UIAppearanceContainer":{"type":"unresolvable","title":"UIKit.UIAppearanceContainer","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIAppearanceContainer"},"doc://com.yababaGmbH.yababa/documentation/Yababa/ShoppingCartSceneViewController/UITableViewDelegate-Implementations":{"role":"collectionGroup","title":"UITableViewDelegate Implementations","abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ShoppingCartSceneViewController\/UITableViewDelegate-Implementations","kind":"article","type":"topic","url":"\/documentation\/yababa\/shoppingcartsceneviewcontroller\/uitableviewdelegate-implementations"},"doc://com.yababaGmbH.yababa/documentation/Yababa/ShoppingCartSceneViewController/setIdentifiers()":{"role":"symbol","title":"setIdentifiers()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setIdentifiers"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ShoppingCartSceneViewController\/setIdentifiers()","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/shoppingcartsceneviewcontroller\/setidentifiers()"},"doc://com.yababaGmbH.yababa/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.yababaGmbH.yababa\/SQ"},"doc://com.yababaGmbH.yababa/objc(pl)UIFocusEnvironment":{"type":"unresolvable","title":"UIKit.UIFocusEnvironment","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIFocusEnvironment"},"doc://com.yababaGmbH.yababa/documentation/Yababa/ShoppingCartSceneViewController/unSubscribeFromShoppingCart()":{"role":"symbol","title":"unSubscribeFromShoppingCart()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"unSubscribeFromShoppingCart"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ShoppingCartSceneViewController\/unSubscribeFromShoppingCart()","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/shoppingcartsceneviewcontroller\/unsubscribefromshoppingcart()"},"doc://com.yababaGmbH.yababa/documentation/Yababa/ShoppingCartSceneViewController/setEmptyCartMessages()":{"role":"symbol","title":"setEmptyCartMessages()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setEmptyCartMessages"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ShoppingCartSceneViewController\/setEmptyCartMessages()","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/shoppingcartsceneviewcontroller\/setemptycartmessages()"},"doc://com.yababaGmbH.yababa/objc(pl)UIStateRestoring":{"type":"unresolvable","title":"UIKit.UIStateRestoring","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIStateRestoring"},"doc://com.yababaGmbH.yababa/documentation/Yababa/MasterViewController":{"role":"symbol","title":"MasterViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MasterViewController"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/MasterViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MasterViewController"}],"url":"\/documentation\/yababa\/masterviewcontroller"},"doc://com.yababaGmbH.yababa/documentation/Yababa/ShoppingCartSceneViewController/onBack()":{"role":"symbol","title":"onBack()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onBack"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ShoppingCartSceneViewController\/onBack()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"onBack"}],"url":"\/documentation\/yababa\/shoppingcartsceneviewcontroller\/onback()"},"doc://com.yababaGmbH.yababa/documentation/Yababa/ShoppingCartSceneViewController/clearBtn":{"role":"symbol","title":"clearBtn","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"clearBtn"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIBarButtonItem","preciseIdentifier":"c:objc(cs)UIBarButtonItem"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ShoppingCartSceneViewController\/clearBtn","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/shoppingcartsceneviewcontroller\/clearbtn"},"doc://com.yababaGmbH.yababa/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/com.yababaGmbH.yababa\/s8SendableP"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"ShoppingCartSceneViewController"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"ShoppingCartSceneViewController"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"ShoppingCartSceneViewController"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ShoppingCartSceneViewController\/initWithCoder:","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ShoppingCartSceneViewController\/initWithNibName:bundle:","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ShoppingCartSceneViewController\/onBack()","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ShoppingCartSceneViewController\/onCheckout()","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ShoppingCartSceneViewController\/onClearCart()","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ShoppingCartSceneViewController\/onStartShopping()","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ShoppingCartSceneViewController\/viewDidAppear(_:)","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ShoppingCartSceneViewController\/viewDidLayoutSubviews()","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ShoppingCartSceneViewController\/viewDidLoad()","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ShoppingCartSceneViewController\/viewWillAppear(_:)"]},{"title":"Default Implementations","identifiers":["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ShoppingCartSceneViewController\/UITableViewDataSource-Implementations","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ShoppingCartSceneViewController\/UITableViewDelegate-Implementations"],"generated":true}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/MasterViewController"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"ShoppingCartSceneViewController"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/MasterViewController","preciseIdentifier":"c:@M@Yababa@objc(cs)MasterViewController","text":"MasterViewController"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1ShoppingCartSceneViewController~1viewDidLayoutSubviews()\/title","value":"viewDidLayoutSubviews"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1ShoppingCartSceneViewController~1viewDidLayoutSubviews()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"viewDidLayoutSubviews"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1ShoppingCartSceneViewController~1viewWillAppear(_:)\/title","value":"viewWillAppear:"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1ShoppingCartSceneViewController~1viewWillAppear(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"viewWillAppear:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1ShoppingCartSceneViewController\/title","value":"ShoppingCartSceneViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1ShoppingCartSceneViewController\/fragments","value":[{"kind":"identifier","text":"ShoppingCartSceneViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1ShoppingCartSceneViewController~1viewDidAppear(_:)\/title","value":"viewDidAppear:"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1ShoppingCartSceneViewController~1viewDidAppear(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"viewDidAppear:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1ShoppingCartSceneViewController~1onStartShopping()\/title","value":"onStartShopping"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1ShoppingCartSceneViewController~1onStartShopping()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onStartShopping"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1ShoppingCartSceneViewController~1onClearCart()\/title","value":"onClearCart"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1ShoppingCartSceneViewController~1onClearCart()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onClearCart"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1ShoppingCartSceneViewController~1viewDidLoad()\/title","value":"viewDidLoad"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1ShoppingCartSceneViewController~1viewDidLoad()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"viewDidLoad"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1ShoppingCartSceneViewController~1onCheckout()\/title","value":"onCheckout"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1ShoppingCartSceneViewController~1onCheckout()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onCheckout"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1MasterViewController\/title","value":"MasterViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1MasterViewController\/fragments","value":[{"kind":"identifier","text":"MasterViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1ShoppingCartSceneViewController~1onBack()\/title","value":"onBack"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1ShoppingCartSceneViewController~1onBack()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onBack"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}