{"primaryContentSections":[{"kind":"content","content":[{"anchor":"Overview","level":2,"type":"heading","text":"Overview"},{"type":"paragraph","inlineContent":[{"type":"text","text":"The component works on a Singleton class for shopping cart class that conforms to a protocol called CartProtocol."}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"From a bird’s eye view, it includes methods to add, remove, and clear products from the cart. The cart is maintained locally on device"}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"On the core, it also manages to:"}]},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Check the availability of the products before adding them to the cart."}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Check against the server to see if required product quantities are availble in stock"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Load and Save cart to disk"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Allow subscribing for updates so observers can be notified about changes and perform UI updates or other actions accordingly."}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Track events to analytics when open addition and removals."}]}]}]},{"anchor":"Implementation","level":2,"type":"heading","text":"Implementation"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Navigate to implementation class"}]},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"reference","isActive":true,"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/LocalShoppingCart"}]}]}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/yababa\/shoppingcartmanager"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/yababa\/shoppingcartmanager"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ShoppingCartManager","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Core component of the app, responsible for managing products in the shopping cart."}],"kind":"article","metadata":{"roleHeading":"Article","title":"Shopping Cart","role":"article","modules":[{"name":"Yababa"}]},"hierarchy":{"paths":[["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa"]]},"seeAlsoSections":[{"title":"Shopping","identifiers":["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/-ShoppingOverview","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/StoreManager"],"generated":true}],"references":{"doc://com.yababaGmbH.yababa/documentation/Yababa/LocalShoppingCart":{"role":"symbol","title":"LocalShoppingCart","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"LocalShoppingCart"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/LocalShoppingCart","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"LocalShoppingCart"}],"url":"\/documentation\/yababa\/localshoppingcart"},"doc://com.yababaGmbH.yababa/documentation/Yababa/-ShoppingOverview":{"role":"article","title":"Shopping experience","abstract":[{"type":"text","text":"One Shopping"}],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/-ShoppingOverview","kind":"article","type":"topic","url":"\/documentation\/yababa\/-shoppingoverview"},"doc://com.yababaGmbH.yababa/documentation/Yababa":{"role":"collection","title":"Yababa","abstract":[{"type":"text","text":"Getting Started"}],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa","kind":"symbol","type":"topic","url":"\/documentation\/yababa"},"doc://com.yababaGmbH.yababa/documentation/Yababa/StoreManager":{"role":"article","title":"Store Manager","abstract":[{"type":"text","text":"Core component of the app, responsible for fetching the latest catalogue from server and maintaining it locally on the device."}],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/StoreManager","kind":"article","type":"topic","url":"\/documentation\/yababa\/storemanager"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/topicSections","value":null},{"op":"replace","path":"\/seeAlsoSections","value":[{"title":"Shopping","identifiers":["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/-ShoppingOverview","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/StoreManager"],"generated":true}]}],"traits":[{"interfaceLanguage":"occ"}]}]}