{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SignupSceneViewController"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/yababa\/signupsceneviewcontroller"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/yababa\/signupsceneviewcontroller"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/MasterViewController"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.yababaGmbH.yababa\/objc(pl)NSCoding","doc:\/\/com.yababaGmbH.yababa\/objc(pl)NSExtensionRequestHandling","doc:\/\/com.yababaGmbH.yababa\/6Nantes0A13LabelDelegateP","doc:\/\/com.yababaGmbH.yababa\/objc(pl)NSObject","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/SignupSceneViewControllerProtocol","doc:\/\/com.yababaGmbH.yababa\/12SkeletonView17AssociatedObjectsP","doc:\/\/com.yababaGmbH.yababa\/s7CVarArgP","doc:\/\/com.yababaGmbH.yababa\/s28CustomDebugStringConvertibleP","doc:\/\/com.yababaGmbH.yababa\/s23CustomStringConvertibleP","doc:\/\/com.yababaGmbH.yababa\/SQ","doc:\/\/com.yababaGmbH.yababa\/SH","doc:\/\/com.yababaGmbH.yababa\/s8SendableP","doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIActivityItemsConfigurationProviding","doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIAppearanceContainer","doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIContentContainer","doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIFocusEnvironment","doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIPasteConfigurationSupporting","doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIResponderStandardEditActions","doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIStateRestoring","doc:\/\/com.yababaGmbH.yababa\/objc(pl)UITraitEnvironment","doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIUserActivityRestoring"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/SignupSceneViewController","interfaceLanguage":"swift"},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/SignupSceneViewController\/init(coder:)","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/SignupSceneViewController\/init(prefilledEmailAddress:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/SignupSceneViewController\/completeTextLabel","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/SignupSceneViewController\/continueBtn","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/SignupSceneViewController\/emailLabel","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/SignupSceneViewController\/firstNameTextField","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/SignupSceneViewController\/interactor","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/SignupSceneViewController\/lastNameTextField","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/SignupSceneViewController\/marketingConsentCheckBoxBtn","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/SignupSceneViewController\/marketingConsentLabel","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/SignupSceneViewController\/passwordTextField","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/SignupSceneViewController\/router","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/SignupSceneViewController\/showPasswordBtn","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/SignupSceneViewController\/signupTitleLabel","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/SignupSceneViewController\/smallSpinner","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/SignupSceneViewController\/termsCheckBoxBtn","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/SignupSceneViewController\/yababaTermsLabel"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/SignupSceneViewController\/hideSpinner()","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/SignupSceneViewController\/onContinue()","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/SignupSceneViewController\/onTapMarketingConsentCheckbox()","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/SignupSceneViewController\/onTapTermsCheckbox()","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/SignupSceneViewController\/onToggleSecureText(_:)","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/SignupSceneViewController\/processSignup()","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/SignupSceneViewController\/showSpinner()","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/SignupSceneViewController\/viewDidLoad()"]},{"title":"Default Implementations","identifiers":["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/SignupSceneViewController\/NantesLabelDelegate-Implementations","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/SignupSceneViewController\/SignupSceneViewControllerProtocol-Implementations"],"generated":true}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SignupSceneViewController"}],"title":"SignupSceneViewController","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@Yababa@objc(cs)SignupSceneViewController","modules":[{"name":"Yababa"}],"navigatorTitle":[{"kind":"identifier","text":"SignupSceneViewController"}]},"hierarchy":{"paths":[["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa"]]},"references":{"doc://com.yababaGmbH.yababa/documentation/Yababa/SignupSceneViewController/yababaTermsLabel":{"role":"symbol","title":"yababaTermsLabel","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"yababaTermsLabel"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NantesLabel","preciseIdentifier":"c:@M@Nantes@objc(cs)NantesLabel"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/SignupSceneViewController\/yababaTermsLabel","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"yababaTermsLabel"}],"url":"\/documentation\/yababa\/signupsceneviewcontroller\/yababatermslabel"},"doc://com.yababaGmbH.yababa/documentation/Yababa/SignupSceneViewController/marketingConsentCheckBoxBtn":{"role":"symbol","title":"marketingConsentCheckBoxBtn","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"marketingConsentCheckBoxBtn"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIButton","preciseIdentifier":"c:objc(cs)UIButton"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/SignupSceneViewController\/marketingConsentCheckBoxBtn","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"marketingConsentCheckBoxBtn"}],"url":"\/documentation\/yababa\/signupsceneviewcontroller\/marketingconsentcheckboxbtn"},"doc://com.yababaGmbH.yababa/12SkeletonView17AssociatedObjectsP":{"type":"unresolvable","title":"SkeletonView.AssociatedObjects","identifier":"doc:\/\/com.yababaGmbH.yababa\/12SkeletonView17AssociatedObjectsP"},"doc://com.yababaGmbH.yababa/objc(pl)UIStateRestoring":{"type":"unresolvable","title":"UIKit.UIStateRestoring","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIStateRestoring"},"doc://com.yababaGmbH.yababa/documentation/Yababa/SignupSceneViewController/completeTextLabel":{"role":"symbol","title":"completeTextLabel","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"completeTextLabel"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UILabel","preciseIdentifier":"c:objc(cs)UILabel"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/SignupSceneViewController\/completeTextLabel","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"completeTextLabel"}],"url":"\/documentation\/yababa\/signupsceneviewcontroller\/completetextlabel"},"doc://com.yababaGmbH.yababa/objc(pl)UIUserActivityRestoring":{"type":"unresolvable","title":"UIKit.UIUserActivityRestoring","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIUserActivityRestoring"},"doc://com.yababaGmbH.yababa/documentation/Yababa/SignupSceneViewController/router":{"role":"symbol","title":"router","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"router"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SignupSceneRouterProtocol","preciseIdentifier":"s:6Yababa25SignupSceneRouterProtocolP"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/SignupSceneViewController\/router","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/signupsceneviewcontroller\/router"},"doc://com.yababaGmbH.yababa/documentation/Yababa/SignupSceneViewController/onTapTermsCheckbox()":{"role":"symbol","title":"onTapTermsCheckbox()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onTapTermsCheckbox"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/SignupSceneViewController\/onTapTermsCheckbox()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"onTapTermsCheckbox"}],"url":"\/documentation\/yababa\/signupsceneviewcontroller\/ontaptermscheckbox()"},"doc://com.yababaGmbH.yababa/documentation/Yababa/SignupSceneViewController/interactor":{"role":"symbol","title":"interactor","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"interactor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SignupSceneInteractorProtocol","preciseIdentifier":"s:6Yababa29SignupSceneInteractorProtocolP"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/SignupSceneViewController\/interactor","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/signupsceneviewcontroller\/interactor"},"doc://com.yababaGmbH.yababa/documentation/Yababa/SignupSceneViewController/processSignup()":{"role":"symbol","title":"processSignup()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"processSignup"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/SignupSceneViewController\/processSignup()","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/signupsceneviewcontroller\/processsignup()"},"doc://com.yababaGmbH.yababa/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.yababaGmbH.yababa\/s23CustomStringConvertibleP"},"doc://com.yababaGmbH.yababa/documentation/Yababa/SignupSceneViewController/init(prefilledEmailAddress:)":{"role":"symbol","title":"init(prefilledEmailAddress:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"prefilledEmailAddress"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/SignupSceneViewController\/init(prefilledEmailAddress:)","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/signupsceneviewcontroller\/init(prefilledemailaddress:)"},"doc://com.yababaGmbH.yababa/documentation/Yababa/SignupSceneViewController/marketingConsentLabel":{"role":"symbol","title":"marketingConsentLabel","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"marketingConsentLabel"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UILabel","preciseIdentifier":"c:objc(cs)UILabel"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/SignupSceneViewController\/marketingConsentLabel","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"marketingConsentLabel"}],"url":"\/documentation\/yababa\/signupsceneviewcontroller\/marketingconsentlabel"},"doc://com.yababaGmbH.yababa/documentation/Yababa/SignupSceneViewController/continueBtn":{"role":"symbol","title":"continueBtn","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"continueBtn"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIButton","preciseIdentifier":"c:objc(cs)UIButton"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/SignupSceneViewController\/continueBtn","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"continueBtn"}],"url":"\/documentation\/yababa\/signupsceneviewcontroller\/continuebtn"},"doc://com.yababaGmbH.yababa/objc(pl)NSCoding":{"type":"unresolvable","title":"Foundation.NSCoding","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)NSCoding"},"doc://com.yababaGmbH.yababa/objc(pl)UIFocusEnvironment":{"type":"unresolvable","title":"UIKit.UIFocusEnvironment","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIFocusEnvironment"},"doc://com.yababaGmbH.yababa/documentation/Yababa/SignupSceneViewController/termsCheckBoxBtn":{"role":"symbol","title":"termsCheckBoxBtn","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"termsCheckBoxBtn"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIButton","preciseIdentifier":"c:objc(cs)UIButton"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/SignupSceneViewController\/termsCheckBoxBtn","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"termsCheckBoxBtn"}],"url":"\/documentation\/yababa\/signupsceneviewcontroller\/termscheckboxbtn"},"doc://com.yababaGmbH.yababa/objc(pl)NSExtensionRequestHandling":{"type":"unresolvable","title":"Foundation.NSExtensionRequestHandling","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)NSExtensionRequestHandling"},"doc://com.yababaGmbH.yababa/documentation/Yababa/SignupSceneViewController/showPasswordBtn":{"role":"symbol","title":"showPasswordBtn","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"showPasswordBtn"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIButton","preciseIdentifier":"c:objc(cs)UIButton"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/SignupSceneViewController\/showPasswordBtn","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"showPasswordBtn"}],"url":"\/documentation\/yababa\/signupsceneviewcontroller\/showpasswordbtn"},"doc://com.yababaGmbH.yababa/documentation/Yababa/SignupSceneViewController/SignupSceneViewControllerProtocol-Implementations":{"role":"collectionGroup","title":"SignupSceneViewControllerProtocol Implementations","abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/SignupSceneViewController\/SignupSceneViewControllerProtocol-Implementations","kind":"article","type":"topic","url":"\/documentation\/yababa\/signupsceneviewcontroller\/signupsceneviewcontrollerprotocol-implementations"},"doc://com.yababaGmbH.yababa/6Nantes0A13LabelDelegateP":{"type":"unresolvable","title":"Nantes.NantesLabelDelegate","identifier":"doc:\/\/com.yababaGmbH.yababa\/6Nantes0A13LabelDelegateP"},"doc://com.yababaGmbH.yababa/objc(pl)UIPasteConfigurationSupporting":{"type":"unresolvable","title":"UIKit.UIPasteConfigurationSupporting","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIPasteConfigurationSupporting"},"doc://com.yababaGmbH.yababa/documentation/Yababa/SignupSceneViewController/firstNameTextField":{"role":"symbol","title":"firstNameTextField","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"firstNameTextField"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UITextField","preciseIdentifier":"c:objc(cs)UITextField"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/SignupSceneViewController\/firstNameTextField","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"firstNameTextField"}],"url":"\/documentation\/yababa\/signupsceneviewcontroller\/firstnametextfield"},"doc://com.yababaGmbH.yababa/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.yababaGmbH.yababa\/SQ"},"doc://com.yababaGmbH.yababa/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.yababaGmbH.yababa\/s7CVarArgP"},"doc://com.yababaGmbH.yababa/documentation/Yababa/SignupSceneViewController/emailLabel":{"role":"symbol","title":"emailLabel","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"emailLabel"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UILabel","preciseIdentifier":"c:objc(cs)UILabel"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/SignupSceneViewController\/emailLabel","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"emailLabel"}],"url":"\/documentation\/yababa\/signupsceneviewcontroller\/emaillabel"},"doc://com.yababaGmbH.yababa/documentation/Yababa/SignupSceneViewController/hideSpinner()":{"role":"symbol","title":"hideSpinner()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"hideSpinner"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/SignupSceneViewController\/hideSpinner()","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/signupsceneviewcontroller\/hidespinner()"},"doc://com.yababaGmbH.yababa/documentation/Yababa/SignupSceneViewController/showSpinner()":{"role":"symbol","title":"showSpinner()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"showSpinner"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/SignupSceneViewController\/showSpinner()","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/signupsceneviewcontroller\/showspinner()"},"doc://com.yababaGmbH.yababa/documentation/Yababa":{"role":"collection","title":"Yababa","abstract":[{"type":"text","text":"Getting Started"}],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa","kind":"symbol","type":"topic","url":"\/documentation\/yababa"},"doc://com.yababaGmbH.yababa/documentation/Yababa/SignupSceneViewController/NantesLabelDelegate-Implementations":{"role":"collectionGroup","title":"NantesLabelDelegate Implementations","abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/SignupSceneViewController\/NantesLabelDelegate-Implementations","kind":"article","type":"topic","url":"\/documentation\/yababa\/signupsceneviewcontroller\/nanteslabeldelegate-implementations"},"doc://com.yababaGmbH.yababa/documentation/Yababa/SignupSceneViewController":{"role":"symbol","title":"SignupSceneViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SignupSceneViewController"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/SignupSceneViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SignupSceneViewController"}],"url":"\/documentation\/yababa\/signupsceneviewcontroller"},"doc://com.yababaGmbH.yababa/documentation/Yababa/SignupSceneViewController/passwordTextField":{"role":"symbol","title":"passwordTextField","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"passwordTextField"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UITextField","preciseIdentifier":"c:objc(cs)UITextField"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/SignupSceneViewController\/passwordTextField","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"passwordTextField"}],"url":"\/documentation\/yababa\/signupsceneviewcontroller\/passwordtextfield"},"doc://com.yababaGmbH.yababa/objc(pl)UIActivityItemsConfigurationProviding":{"type":"unresolvable","title":"UIKit.UIActivityItemsConfigurationProviding","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIActivityItemsConfigurationProviding"},"doc://com.yababaGmbH.yababa/documentation/Yababa/SignupSceneViewControllerProtocol":{"role":"symbol","title":"SignupSceneViewControllerProtocol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SignupSceneViewControllerProtocol"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/SignupSceneViewControllerProtocol","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SignupSceneViewControllerProtocol"}],"url":"\/documentation\/yababa\/signupsceneviewcontrollerprotocol"},"doc://com.yababaGmbH.yababa/documentation/Yababa/SignupSceneViewController/lastNameTextField":{"role":"symbol","title":"lastNameTextField","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"lastNameTextField"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UITextField","preciseIdentifier":"c:objc(cs)UITextField"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/SignupSceneViewController\/lastNameTextField","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"lastNameTextField"}],"url":"\/documentation\/yababa\/signupsceneviewcontroller\/lastnametextfield"},"doc://com.yababaGmbH.yababa/objc(pl)UIAppearanceContainer":{"type":"unresolvable","title":"UIKit.UIAppearanceContainer","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIAppearanceContainer"},"doc://com.yababaGmbH.yababa/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/com.yababaGmbH.yababa\/s8SendableP"},"doc://com.yababaGmbH.yababa/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)NSObject"},"doc://com.yababaGmbH.yababa/objc(pl)UITraitEnvironment":{"type":"unresolvable","title":"UIKit.UITraitEnvironment","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)UITraitEnvironment"},"doc://com.yababaGmbH.yababa/documentation/Yababa/SignupSceneViewController/onTapMarketingConsentCheckbox()":{"role":"symbol","title":"onTapMarketingConsentCheckbox()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onTapMarketingConsentCheckbox"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/SignupSceneViewController\/onTapMarketingConsentCheckbox()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"onTapMarketingConsentCheckbox"}],"url":"\/documentation\/yababa\/signupsceneviewcontroller\/ontapmarketingconsentcheckbox()"},"doc://com.yababaGmbH.yababa/objc(pl)UIResponderStandardEditActions":{"type":"unresolvable","title":"UIKit.UIResponderStandardEditActions","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIResponderStandardEditActions"},"doc://com.yababaGmbH.yababa/documentation/Yababa/SignupSceneViewController/onContinue()":{"role":"symbol","title":"onContinue()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onContinue"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/SignupSceneViewController\/onContinue()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"onContinue"}],"url":"\/documentation\/yababa\/signupsceneviewcontroller\/oncontinue()"},"doc://com.yababaGmbH.yababa/objc(pl)UIContentContainer":{"type":"unresolvable","title":"UIKit.UIContentContainer","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIContentContainer"},"doc://com.yababaGmbH.yababa/documentation/Yababa/SignupSceneViewController/onToggleSecureText(_:)":{"role":"symbol","title":"onToggleSecureText(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onToggleSecureText"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UIButton","preciseIdentifier":"c:objc(cs)UIButton"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/SignupSceneViewController\/onToggleSecureText(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"onToggleSecureText:"}],"url":"\/documentation\/yababa\/signupsceneviewcontroller\/ontogglesecuretext(_:)"},"doc://com.yababaGmbH.yababa/documentation/Yababa/MasterViewController":{"role":"symbol","title":"MasterViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MasterViewController"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/MasterViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MasterViewController"}],"url":"\/documentation\/yababa\/masterviewcontroller"},"doc://com.yababaGmbH.yababa/documentation/Yababa/SignupSceneViewController/init(coder:)":{"role":"symbol","title":"init(coder:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"coder"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSCoder","preciseIdentifier":"c:objc(cs)NSCoder"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/SignupSceneViewController\/init(coder:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithCoder:"}],"url":"\/documentation\/yababa\/signupsceneviewcontroller\/init(coder:)"},"doc://com.yababaGmbH.yababa/documentation/Yababa/SignupSceneViewController/smallSpinner":{"role":"symbol","title":"smallSpinner","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"smallSpinner"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIActivityIndicatorView","preciseIdentifier":"c:objc(cs)UIActivityIndicatorView"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/SignupSceneViewController\/smallSpinner","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"smallSpinner"}],"url":"\/documentation\/yababa\/signupsceneviewcontroller\/smallspinner"},"doc://com.yababaGmbH.yababa/documentation/Yababa/SignupSceneViewController/viewDidLoad()":{"role":"symbol","title":"viewDidLoad()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"viewDidLoad"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/SignupSceneViewController\/viewDidLoad()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"viewDidLoad"}],"url":"\/documentation\/yababa\/signupsceneviewcontroller\/viewdidload()"},"doc://com.yababaGmbH.yababa/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.yababaGmbH.yababa\/s28CustomDebugStringConvertibleP"},"doc://com.yababaGmbH.yababa/documentation/Yababa/SignupSceneViewController/signupTitleLabel":{"role":"symbol","title":"signupTitleLabel","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"signupTitleLabel"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UILabel","preciseIdentifier":"c:objc(cs)UILabel"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/SignupSceneViewController\/signupTitleLabel","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"signupTitleLabel"}],"url":"\/documentation\/yababa\/signupsceneviewcontroller\/signuptitlelabel"},"doc://com.yababaGmbH.yababa/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.yababaGmbH.yababa\/SH"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"SignupSceneViewController"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SignupSceneViewController"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"SignupSceneViewController"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/SignupSceneViewController\/completeTextLabel","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/SignupSceneViewController\/continueBtn","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/SignupSceneViewController\/emailLabel","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/SignupSceneViewController\/firstNameTextField","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/SignupSceneViewController\/lastNameTextField","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/SignupSceneViewController\/marketingConsentCheckBoxBtn","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/SignupSceneViewController\/marketingConsentLabel","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/SignupSceneViewController\/passwordTextField","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/SignupSceneViewController\/showPasswordBtn","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/SignupSceneViewController\/signupTitleLabel","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/SignupSceneViewController\/smallSpinner","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/SignupSceneViewController\/termsCheckBoxBtn","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/SignupSceneViewController\/yababaTermsLabel"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/SignupSceneViewController\/init(coder:)","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/SignupSceneViewController\/onContinue()","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/SignupSceneViewController\/onTapMarketingConsentCheckbox()","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/SignupSceneViewController\/onTapTermsCheckbox()","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/SignupSceneViewController\/onToggleSecureText(_:)","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/SignupSceneViewController\/viewDidLoad()"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/MasterViewController"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"SignupSceneViewController"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/MasterViewController","preciseIdentifier":"c:@M@Yababa@objc(cs)MasterViewController","text":"MasterViewController"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1SignupSceneViewController~1yababaTermsLabel\/title","value":"yababaTermsLabel"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1SignupSceneViewController~1yababaTermsLabel\/fragments","value":[{"kind":"identifier","text":"yababaTermsLabel"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1SignupSceneViewController~1marketingConsentCheckBoxBtn\/title","value":"marketingConsentCheckBoxBtn"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1SignupSceneViewController~1marketingConsentCheckBoxBtn\/fragments","value":[{"kind":"identifier","text":"marketingConsentCheckBoxBtn"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1SignupSceneViewController~1completeTextLabel\/title","value":"completeTextLabel"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1SignupSceneViewController~1completeTextLabel\/fragments","value":[{"kind":"identifier","text":"completeTextLabel"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1SignupSceneViewController~1onTapTermsCheckbox()\/title","value":"onTapTermsCheckbox"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1SignupSceneViewController~1onTapTermsCheckbox()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onTapTermsCheckbox"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1SignupSceneViewController~1marketingConsentLabel\/title","value":"marketingConsentLabel"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1SignupSceneViewController~1marketingConsentLabel\/fragments","value":[{"kind":"identifier","text":"marketingConsentLabel"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1SignupSceneViewController~1continueBtn\/title","value":"continueBtn"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1SignupSceneViewController~1continueBtn\/fragments","value":[{"kind":"identifier","text":"continueBtn"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1SignupSceneViewController~1termsCheckBoxBtn\/title","value":"termsCheckBoxBtn"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1SignupSceneViewController~1termsCheckBoxBtn\/fragments","value":[{"kind":"identifier","text":"termsCheckBoxBtn"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1SignupSceneViewController~1showPasswordBtn\/title","value":"showPasswordBtn"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1SignupSceneViewController~1showPasswordBtn\/fragments","value":[{"kind":"identifier","text":"showPasswordBtn"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1SignupSceneViewController~1firstNameTextField\/title","value":"firstNameTextField"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1SignupSceneViewController~1firstNameTextField\/fragments","value":[{"kind":"identifier","text":"firstNameTextField"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1SignupSceneViewController~1emailLabel\/title","value":"emailLabel"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1SignupSceneViewController~1emailLabel\/fragments","value":[{"kind":"identifier","text":"emailLabel"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1SignupSceneViewController\/title","value":"SignupSceneViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1SignupSceneViewController\/fragments","value":[{"kind":"identifier","text":"SignupSceneViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1SignupSceneViewController~1passwordTextField\/title","value":"passwordTextField"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1SignupSceneViewController~1passwordTextField\/fragments","value":[{"kind":"identifier","text":"passwordTextField"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1SignupSceneViewController~1lastNameTextField\/title","value":"lastNameTextField"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1SignupSceneViewController~1lastNameTextField\/fragments","value":[{"kind":"identifier","text":"lastNameTextField"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1SignupSceneViewController~1onTapMarketingConsentCheckbox()\/title","value":"onTapMarketingConsentCheckbox"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1SignupSceneViewController~1onTapMarketingConsentCheckbox()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onTapMarketingConsentCheckbox"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1SignupSceneViewController~1onContinue()\/title","value":"onContinue"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1SignupSceneViewController~1onContinue()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onContinue"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1SignupSceneViewController~1onToggleSecureText(_:)\/title","value":"onToggleSecureText:"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1SignupSceneViewController~1onToggleSecureText(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onToggleSecureText:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1MasterViewController\/title","value":"MasterViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1MasterViewController\/fragments","value":[{"kind":"identifier","text":"MasterViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1SignupSceneViewController~1init(coder:)\/title","value":"initWithCoder:"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1SignupSceneViewController~1init(coder:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithCoder:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1SignupSceneViewController~1smallSpinner\/title","value":"smallSpinner"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1SignupSceneViewController~1smallSpinner\/fragments","value":[{"kind":"identifier","text":"smallSpinner"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1SignupSceneViewController~1viewDidLoad()\/title","value":"viewDidLoad"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1SignupSceneViewController~1viewDidLoad()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"viewDidLoad"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1SignupSceneViewController~1signupTitleLabel\/title","value":"signupTitleLabel"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1SignupSceneViewController~1signupTitleLabel\/fragments","value":[{"kind":"identifier","text":"signupTitleLabel"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}