{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SocialLoginResponseDelegate"},{"kind":"text","text":" : AnyObject"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/yababa\/socialloginresponsedelegate"],"traits":[{"interfaceLanguage":"swift"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/HomeScreen","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/WelcomeSceneViewController"],"kind":"relationships","title":"Conforming Types","type":"conformingTypes"}],"identifier":{"url":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/SocialLoginResponseDelegate","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/SocialLoginResponseDelegate\/onSocialLoginFail(errorTitle:errorMessage:)","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/SocialLoginResponseDelegate\/onSocialLoginSuccess(profile:fullName:token:providerTokenAssignAction:)-3vlar","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/SocialLoginResponseDelegate\/showMessage(_:)","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/SocialLoginResponseDelegate\/socialLoginSuccessCompleted()"]}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SocialLoginResponseDelegate"}],"title":"SocialLoginResponseDelegate","roleHeading":"Protocol","role":"symbol","symbolKind":"protocol","externalID":"s:6Yababa27SocialLoginResponseDelegateP","modules":[{"name":"Yababa"}],"navigatorTitle":[{"kind":"identifier","text":"SocialLoginResponseDelegate"}]},"hierarchy":{"paths":[["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa"]]},"references":{"doc://com.yababaGmbH.yababa/documentation/Yababa/WelcomeSceneViewController":{"role":"symbol","title":"WelcomeSceneViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"WelcomeSceneViewController"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/WelcomeSceneViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"WelcomeSceneViewController"}],"url":"\/documentation\/yababa\/welcomesceneviewcontroller"},"doc://com.yababaGmbH.yababa/documentation/Yababa/SocialLoginResponseDelegate":{"role":"symbol","title":"SocialLoginResponseDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SocialLoginResponseDelegate"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/SocialLoginResponseDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SocialLoginResponseDelegate"}],"url":"\/documentation\/yababa\/socialloginresponsedelegate"},"doc://com.yababaGmbH.yababa/documentation/Yababa/SocialLoginResponseDelegate/onSocialLoginFail(errorTitle:errorMessage:)":{"role":"symbol","title":"onSocialLoginFail(errorTitle:errorMessage:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onSocialLoginFail"},{"kind":"text","text":"("},{"kind":"externalParam","text":"errorTitle"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"errorMessage"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/SocialLoginResponseDelegate\/onSocialLoginFail(errorTitle:errorMessage:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/yababa\/socialloginresponsedelegate\/onsocialloginfail(errortitle:errormessage:)"},"doc://com.yababaGmbH.yababa/documentation/Yababa":{"role":"collection","title":"Yababa","abstract":[{"type":"text","text":"Getting Started"}],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa","kind":"symbol","type":"topic","url":"\/documentation\/yababa"},"doc://com.yababaGmbH.yababa/documentation/Yababa/SocialLoginResponseDelegate/onSocialLoginSuccess(profile:fullName:token:providerTokenAssignAction:)-3vlar":{"defaultImplementations":1,"role":"symbol","title":"onSocialLoginSuccess(profile:fullName:token:providerTokenAssignAction:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onSocialLoginSuccess"},{"kind":"text","text":"("},{"kind":"externalParam","text":"profile"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Profile","preciseIdentifier":"c:@M@Yababa@objc(cs)Profile"},{"kind":"text","text":", "},{"kind":"externalParam","text":"fullName"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"token"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"providerTokenAssignAction"},{"kind":"text","text":": () -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/SocialLoginResponseDelegate\/onSocialLoginSuccess(profile:fullName:token:providerTokenAssignAction:)-3vlar","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/yababa\/socialloginresponsedelegate\/onsocialloginsuccess(profile:fullname:token:providertokenassignaction:)-3vlar"},"doc://com.yababaGmbH.yababa/documentation/Yababa/HomeScreen":{"role":"symbol","title":"HomeScreen","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HomeScreen"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/HomeScreen","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HomeScreen"}],"url":"\/documentation\/yababa\/homescreen"},"doc://com.yababaGmbH.yababa/documentation/Yababa/SocialLoginResponseDelegate/socialLoginSuccessCompleted()":{"role":"symbol","title":"socialLoginSuccessCompleted()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"socialLoginSuccessCompleted"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/SocialLoginResponseDelegate\/socialLoginSuccessCompleted()","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/yababa\/socialloginresponsedelegate\/socialloginsuccesscompleted()"},"doc://com.yababaGmbH.yababa/documentation/Yababa/SocialLoginResponseDelegate/showMessage(_:)":{"role":"symbol","title":"showMessage(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"showMessage"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/SocialLoginResponseDelegate\/showMessage(_:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/yababa\/socialloginresponsedelegate\/showmessage(_:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1WelcomeSceneViewController\/title","value":"WelcomeSceneViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1WelcomeSceneViewController\/fragments","value":[{"kind":"identifier","text":"WelcomeSceneViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1HomeScreen\/title","value":"HomeScreen"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1HomeScreen\/fragments","value":[{"kind":"identifier","text":"HomeScreen"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}