{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"StripeGatewayViewController"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/yababa\/stripegatewayviewcontroller"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/yababa\/stripegatewayviewcontroller"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/MasterViewController"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.yababaGmbH.yababa\/objc(pl)NSCoding","doc:\/\/com.yababaGmbH.yababa\/objc(pl)NSExtensionRequestHandling","doc:\/\/com.yababaGmbH.yababa\/objc(pl)NSObject","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/PaymentProcessViewExtension","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/PaymentTimerDelegate","doc:\/\/com.yababaGmbH.yababa\/12SkeletonView17AssociatedObjectsP","doc:\/\/com.yababaGmbH.yababa\/@M@Stripe@objc(pl)STPAuthenticationContext","doc:\/\/com.yababaGmbH.yababa\/s7CVarArgP","doc:\/\/com.yababaGmbH.yababa\/s28CustomDebugStringConvertibleP","doc:\/\/com.yababaGmbH.yababa\/s23CustomStringConvertibleP","doc:\/\/com.yababaGmbH.yababa\/SQ","doc:\/\/com.yababaGmbH.yababa\/SH","doc:\/\/com.yababaGmbH.yababa\/s8SendableP","doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIActivityItemsConfigurationProviding","doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIAppearanceContainer","doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIContentContainer","doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIFocusEnvironment","doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIPasteConfigurationSupporting","doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIResponderStandardEditActions","doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIStateRestoring","doc:\/\/com.yababaGmbH.yababa\/objc(pl)UITraitEnvironment","doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIUserActivityRestoring"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/StripeGatewayViewController","interfaceLanguage":"swift"},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/StripeGatewayViewController\/init(amount:currency:delegate:)","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/StripeGatewayViewController\/init(coder:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/StripeGatewayViewController\/cardTextField","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/StripeGatewayViewController\/payBtn","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/StripeGatewayViewController\/paymentInformationTextLabel","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/StripeGatewayViewController\/timeoutLabel","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/StripeGatewayViewController\/titleTextLabel","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/StripeGatewayViewController\/totalLabel","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/StripeGatewayViewController\/totalTextLabel"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/StripeGatewayViewController\/authenticationPresentingViewController()","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/StripeGatewayViewController\/onBack()","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/StripeGatewayViewController\/onDismissKeyboard()","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/StripeGatewayViewController\/onPay()","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/StripeGatewayViewController\/setIdentifiers()","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/StripeGatewayViewController\/setupLocalizedStrings()","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/StripeGatewayViewController\/showInformation()","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/StripeGatewayViewController\/viewDidDisappear(_:)","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/StripeGatewayViewController\/viewDidLoad()"]},{"title":"Default Implementations","identifiers":["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/StripeGatewayViewController\/PaymentTimerDelegate-Implementations"],"generated":true}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"StripeGatewayViewController"}],"title":"StripeGatewayViewController","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@Yababa@objc(cs)StripeGatewayViewController","modules":[{"name":"Yababa"}],"navigatorTitle":[{"kind":"identifier","text":"StripeGatewayViewController"}]},"hierarchy":{"paths":[["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa"]]},"references":{"doc://com.yababaGmbH.yababa/objc(pl)UIActivityItemsConfigurationProviding":{"type":"unresolvable","title":"UIKit.UIActivityItemsConfigurationProviding","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIActivityItemsConfigurationProviding"},"doc://com.yababaGmbH.yababa/documentation/Yababa/StripeGatewayViewController/cardTextField":{"role":"symbol","title":"cardTextField","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"cardTextField"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"STPPaymentCardTextField","preciseIdentifier":"c:@M@Stripe@objc(cs)STPPaymentCardTextField"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/StripeGatewayViewController\/cardTextField","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"cardTextField"}],"url":"\/documentation\/yababa\/stripegatewayviewcontroller\/cardtextfield"},"doc://com.yababaGmbH.yababa/documentation/Yababa/StripeGatewayViewController/viewDidLoad()":{"role":"symbol","title":"viewDidLoad()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"viewDidLoad"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/StripeGatewayViewController\/viewDidLoad()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"viewDidLoad"}],"url":"\/documentation\/yababa\/stripegatewayviewcontroller\/viewdidload()"},"doc://com.yababaGmbH.yababa/objc(pl)UIUserActivityRestoring":{"type":"unresolvable","title":"UIKit.UIUserActivityRestoring","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIUserActivityRestoring"},"doc://com.yababaGmbH.yababa/documentation/Yababa/PaymentTimerDelegate":{"role":"symbol","title":"PaymentTimerDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"PaymentTimerDelegate"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/PaymentTimerDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PaymentTimerDelegate"}],"url":"\/documentation\/yababa\/paymenttimerdelegate"},"doc://com.yababaGmbH.yababa/documentation/Yababa/StripeGatewayViewController/setupLocalizedStrings()":{"role":"symbol","title":"setupLocalizedStrings()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setupLocalizedStrings"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/StripeGatewayViewController\/setupLocalizedStrings()","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/stripegatewayviewcontroller\/setuplocalizedstrings()"},"doc://com.yababaGmbH.yababa/objc(pl)UITraitEnvironment":{"type":"unresolvable","title":"UIKit.UITraitEnvironment","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)UITraitEnvironment"},"doc://com.yababaGmbH.yababa/objc(pl)UIContentContainer":{"type":"unresolvable","title":"UIKit.UIContentContainer","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIContentContainer"},"doc://com.yababaGmbH.yababa/documentation/Yababa/MasterViewController":{"role":"symbol","title":"MasterViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MasterViewController"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/MasterViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MasterViewController"}],"url":"\/documentation\/yababa\/masterviewcontroller"},"doc://com.yababaGmbH.yababa/documentation/Yababa/StripeGatewayViewController/showInformation()":{"role":"symbol","title":"showInformation()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"showInformation"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/StripeGatewayViewController\/showInformation()","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/stripegatewayviewcontroller\/showinformation()"},"doc://com.yababaGmbH.yababa/documentation/Yababa/StripeGatewayViewController/totalTextLabel":{"role":"symbol","title":"totalTextLabel","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"totalTextLabel"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UILabel","preciseIdentifier":"c:objc(cs)UILabel"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/StripeGatewayViewController\/totalTextLabel","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"totalTextLabel"}],"url":"\/documentation\/yababa\/stripegatewayviewcontroller\/totaltextlabel"},"doc://com.yababaGmbH.yababa/objc(pl)NSExtensionRequestHandling":{"type":"unresolvable","title":"Foundation.NSExtensionRequestHandling","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)NSExtensionRequestHandling"},"doc://com.yababaGmbH.yababa/documentation/Yababa/StripeGatewayViewController/paymentInformationTextLabel":{"role":"symbol","title":"paymentInformationTextLabel","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"paymentInformationTextLabel"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UILabel","preciseIdentifier":"c:objc(cs)UILabel"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/StripeGatewayViewController\/paymentInformationTextLabel","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"paymentInformationTextLabel"}],"url":"\/documentation\/yababa\/stripegatewayviewcontroller\/paymentinformationtextlabel"},"doc://com.yababaGmbH.yababa/12SkeletonView17AssociatedObjectsP":{"type":"unresolvable","title":"SkeletonView.AssociatedObjects","identifier":"doc:\/\/com.yababaGmbH.yababa\/12SkeletonView17AssociatedObjectsP"},"doc://com.yababaGmbH.yababa/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.yababaGmbH.yababa\/SH"},"doc://com.yababaGmbH.yababa/documentation/Yababa/PaymentProcessViewExtension":{"role":"symbol","title":"PaymentProcessViewExtension","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"PaymentProcessViewExtension"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/PaymentProcessViewExtension","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PaymentProcessViewExtension"}],"url":"\/documentation\/yababa\/paymentprocessviewextension"},"doc://com.yababaGmbH.yababa/objc(pl)UIResponderStandardEditActions":{"type":"unresolvable","title":"UIKit.UIResponderStandardEditActions","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIResponderStandardEditActions"},"doc://com.yababaGmbH.yababa/documentation/Yababa/StripeGatewayViewController/authenticationPresentingViewController()":{"role":"symbol","title":"authenticationPresentingViewController()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"authenticationPresentingViewController"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/StripeGatewayViewController\/authenticationPresentingViewController()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"authenticationPresentingViewController"}],"url":"\/documentation\/yababa\/stripegatewayviewcontroller\/authenticationpresentingviewcontroller()"},"doc://com.yababaGmbH.yababa/documentation/Yababa/StripeGatewayViewController/viewDidDisappear(_:)":{"role":"symbol","title":"viewDidDisappear(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"viewDidDisappear"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/StripeGatewayViewController\/viewDidDisappear(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"viewDidDisappear:"}],"url":"\/documentation\/yababa\/stripegatewayviewcontroller\/viewdiddisappear(_:)"},"doc://com.yababaGmbH.yababa/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.yababaGmbH.yababa\/s28CustomDebugStringConvertibleP"},"doc://com.yababaGmbH.yababa/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.yababaGmbH.yababa\/SQ"},"doc://com.yababaGmbH.yababa/objc(pl)UIStateRestoring":{"type":"unresolvable","title":"UIKit.UIStateRestoring","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIStateRestoring"},"doc://com.yababaGmbH.yababa/objc(pl)UIFocusEnvironment":{"type":"unresolvable","title":"UIKit.UIFocusEnvironment","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIFocusEnvironment"},"doc://com.yababaGmbH.yababa/documentation/Yababa/StripeGatewayViewController/init(coder:)":{"role":"symbol","title":"init(coder:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"coder"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSCoder","preciseIdentifier":"c:objc(cs)NSCoder"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/StripeGatewayViewController\/init(coder:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithCoder:"}],"url":"\/documentation\/yababa\/stripegatewayviewcontroller\/init(coder:)"},"doc://com.yababaGmbH.yababa/documentation/Yababa/StripeGatewayViewController/timeoutLabel":{"role":"symbol","title":"timeoutLabel","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"timeoutLabel"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UILabel","preciseIdentifier":"c:objc(cs)UILabel"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/StripeGatewayViewController\/timeoutLabel","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"timeoutLabel"}],"url":"\/documentation\/yababa\/stripegatewayviewcontroller\/timeoutlabel"},"doc://com.yababaGmbH.yababa/@M@Stripe@objc(pl)STPAuthenticationContext":{"type":"unresolvable","title":"STPAuthenticationContext","identifier":"doc:\/\/com.yababaGmbH.yababa\/@M@Stripe@objc(pl)STPAuthenticationContext"},"doc://com.yababaGmbH.yababa/documentation/Yababa/StripeGatewayViewController/onPay()":{"role":"symbol","title":"onPay()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onPay"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/StripeGatewayViewController\/onPay()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"onPay"}],"url":"\/documentation\/yababa\/stripegatewayviewcontroller\/onpay()"},"doc://com.yababaGmbH.yababa/objc(pl)UIAppearanceContainer":{"type":"unresolvable","title":"UIKit.UIAppearanceContainer","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIAppearanceContainer"},"doc://com.yababaGmbH.yababa/documentation/Yababa/StripeGatewayViewController/titleTextLabel":{"role":"symbol","title":"titleTextLabel","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"titleTextLabel"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UILabel","preciseIdentifier":"c:objc(cs)UILabel"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/StripeGatewayViewController\/titleTextLabel","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"titleTextLabel"}],"url":"\/documentation\/yababa\/stripegatewayviewcontroller\/titletextlabel"},"doc://com.yababaGmbH.yababa/documentation/Yababa/StripeGatewayViewController/onBack()":{"role":"symbol","title":"onBack()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onBack"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/StripeGatewayViewController\/onBack()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"onBack"}],"url":"\/documentation\/yababa\/stripegatewayviewcontroller\/onback()"},"doc://com.yababaGmbH.yababa/documentation/Yababa/StripeGatewayViewController/init(amount:currency:delegate:)":{"role":"symbol","title":"init(amount:currency:delegate:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"amount"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"},{"kind":"text","text":", "},{"kind":"externalParam","text":"currency"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"delegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"StripeCreditCardPayDelegate","preciseIdentifier":"s:6Yababa27StripeCreditCardPayDelegateP"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/StripeGatewayViewController\/init(amount:currency:delegate:)","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/stripegatewayviewcontroller\/init(amount:currency:delegate:)"},"doc://com.yababaGmbH.yababa/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.yababaGmbH.yababa\/s7CVarArgP"},"doc://com.yababaGmbH.yababa/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)NSObject"},"doc://com.yababaGmbH.yababa/objc(pl)UIPasteConfigurationSupporting":{"type":"unresolvable","title":"UIKit.UIPasteConfigurationSupporting","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIPasteConfigurationSupporting"},"doc://com.yababaGmbH.yababa/documentation/Yababa/StripeGatewayViewController/PaymentTimerDelegate-Implementations":{"role":"collectionGroup","title":"PaymentTimerDelegate Implementations","abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/StripeGatewayViewController\/PaymentTimerDelegate-Implementations","kind":"article","type":"topic","url":"\/documentation\/yababa\/stripegatewayviewcontroller\/paymenttimerdelegate-implementations"},"doc://com.yababaGmbH.yababa/documentation/Yababa/StripeGatewayViewController/setIdentifiers()":{"role":"symbol","title":"setIdentifiers()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setIdentifiers"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/StripeGatewayViewController\/setIdentifiers()","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/stripegatewayviewcontroller\/setidentifiers()"},"doc://com.yababaGmbH.yababa/documentation/Yababa/StripeGatewayViewController/payBtn":{"role":"symbol","title":"payBtn","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"payBtn"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIButton","preciseIdentifier":"c:objc(cs)UIButton"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/StripeGatewayViewController\/payBtn","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"payBtn"}],"url":"\/documentation\/yababa\/stripegatewayviewcontroller\/paybtn"},"doc://com.yababaGmbH.yababa/documentation/Yababa/StripeGatewayViewController":{"role":"symbol","title":"StripeGatewayViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"StripeGatewayViewController"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/StripeGatewayViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"StripeGatewayViewController"}],"url":"\/documentation\/yababa\/stripegatewayviewcontroller"},"doc://com.yababaGmbH.yababa/documentation/Yababa/StripeGatewayViewController/onDismissKeyboard()":{"role":"symbol","title":"onDismissKeyboard()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onDismissKeyboard"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/StripeGatewayViewController\/onDismissKeyboard()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"onDismissKeyboard"}],"url":"\/documentation\/yababa\/stripegatewayviewcontroller\/ondismisskeyboard()"},"doc://com.yababaGmbH.yababa/objc(pl)NSCoding":{"type":"unresolvable","title":"Foundation.NSCoding","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)NSCoding"},"doc://com.yababaGmbH.yababa/documentation/Yababa/StripeGatewayViewController/totalLabel":{"role":"symbol","title":"totalLabel","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"totalLabel"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UILabel","preciseIdentifier":"c:objc(cs)UILabel"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/StripeGatewayViewController\/totalLabel","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"totalLabel"}],"url":"\/documentation\/yababa\/stripegatewayviewcontroller\/totallabel"},"doc://com.yababaGmbH.yababa/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/com.yababaGmbH.yababa\/s8SendableP"},"doc://com.yababaGmbH.yababa/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.yababaGmbH.yababa\/s23CustomStringConvertibleP"},"doc://com.yababaGmbH.yababa/documentation/Yababa":{"role":"collection","title":"Yababa","abstract":[{"type":"text","text":"Getting Started"}],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa","kind":"symbol","type":"topic","url":"\/documentation\/yababa"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"StripeGatewayViewController"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"StripeGatewayViewController"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"StripeGatewayViewController"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/StripeGatewayViewController\/cardTextField","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/StripeGatewayViewController\/payBtn","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/StripeGatewayViewController\/paymentInformationTextLabel","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/StripeGatewayViewController\/timeoutLabel","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/StripeGatewayViewController\/titleTextLabel","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/StripeGatewayViewController\/totalLabel","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/StripeGatewayViewController\/totalTextLabel"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/StripeGatewayViewController\/authenticationPresentingViewController()","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/StripeGatewayViewController\/init(coder:)","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/StripeGatewayViewController\/onBack()","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/StripeGatewayViewController\/onDismissKeyboard()","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/StripeGatewayViewController\/onPay()","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/StripeGatewayViewController\/viewDidDisappear(_:)","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/StripeGatewayViewController\/viewDidLoad()"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/MasterViewController"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.yababaGmbH.yababa\/@M@Stripe@objc(pl)STPAuthenticationContext"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"StripeGatewayViewController"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/MasterViewController","preciseIdentifier":"c:@M@Yababa@objc(cs)MasterViewController","text":"MasterViewController"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1StripeGatewayViewController~1cardTextField\/title","value":"cardTextField"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1StripeGatewayViewController~1cardTextField\/fragments","value":[{"kind":"identifier","text":"cardTextField"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1StripeGatewayViewController~1viewDidLoad()\/title","value":"viewDidLoad"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1StripeGatewayViewController~1viewDidLoad()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"viewDidLoad"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1MasterViewController\/title","value":"MasterViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1MasterViewController\/fragments","value":[{"kind":"identifier","text":"MasterViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1StripeGatewayViewController~1totalTextLabel\/title","value":"totalTextLabel"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1StripeGatewayViewController~1totalTextLabel\/fragments","value":[{"kind":"identifier","text":"totalTextLabel"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1StripeGatewayViewController~1paymentInformationTextLabel\/title","value":"paymentInformationTextLabel"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1StripeGatewayViewController~1paymentInformationTextLabel\/fragments","value":[{"kind":"identifier","text":"paymentInformationTextLabel"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1StripeGatewayViewController~1authenticationPresentingViewController()\/title","value":"authenticationPresentingViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1StripeGatewayViewController~1authenticationPresentingViewController()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"authenticationPresentingViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1StripeGatewayViewController~1viewDidDisappear(_:)\/title","value":"viewDidDisappear:"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1StripeGatewayViewController~1viewDidDisappear(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"viewDidDisappear:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1StripeGatewayViewController~1init(coder:)\/title","value":"initWithCoder:"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1StripeGatewayViewController~1init(coder:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithCoder:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1StripeGatewayViewController~1timeoutLabel\/title","value":"timeoutLabel"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1StripeGatewayViewController~1timeoutLabel\/fragments","value":[{"kind":"identifier","text":"timeoutLabel"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1StripeGatewayViewController~1onPay()\/title","value":"onPay"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1StripeGatewayViewController~1onPay()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onPay"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1StripeGatewayViewController~1titleTextLabel\/title","value":"titleTextLabel"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1StripeGatewayViewController~1titleTextLabel\/fragments","value":[{"kind":"identifier","text":"titleTextLabel"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1StripeGatewayViewController~1onBack()\/title","value":"onBack"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1StripeGatewayViewController~1onBack()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onBack"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1StripeGatewayViewController~1payBtn\/title","value":"payBtn"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1StripeGatewayViewController~1payBtn\/fragments","value":[{"kind":"identifier","text":"payBtn"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1StripeGatewayViewController\/title","value":"StripeGatewayViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1StripeGatewayViewController\/fragments","value":[{"kind":"identifier","text":"StripeGatewayViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1StripeGatewayViewController~1onDismissKeyboard()\/title","value":"onDismissKeyboard"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1StripeGatewayViewController~1onDismissKeyboard()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onDismissKeyboard"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1StripeGatewayViewController~1totalLabel\/title","value":"totalLabel"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1StripeGatewayViewController~1totalLabel\/fragments","value":[{"kind":"identifier","text":"totalLabel"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}