{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SubscriptionStatus"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/yababa\/subscriptionstatus"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/yababa\/subscriptionstatus"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.yababaGmbH.yababa\/SQ","doc:\/\/com.yababaGmbH.yababa\/SH","doc:\/\/com.yababaGmbH.yababa\/SY","doc:\/\/com.yababaGmbH.yababa\/s8SendableP"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/SubscriptionStatus","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"OPTED_IN: subscribed, and explicitly opted in."},{"type":"text","text":" "},{"type":"text","text":"SUBSCRIBED: subscribed, but not explicitly opted in."},{"type":"text","text":" "},{"type":"text","text":"UNSUBSCRIBED: unsubscribed and\/or explicitly opted out."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SubscriptionStatus"}],"title":"SubscriptionStatus","roleHeading":"Enumeration","role":"symbol","symbolKind":"enum","externalID":"c:@M@Yababa@E@SubscriptionStatus","modules":[{"name":"Yababa"}],"navigatorTitle":[{"kind":"identifier","text":"SubscriptionStatus"}]},"hierarchy":{"paths":[["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa"]]},"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/SubscriptionStatus\/optedIn","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/SubscriptionStatus\/subscribed","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/SubscriptionStatus\/unsubscribed"]},{"title":"Initializers","identifiers":["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/SubscriptionStatus\/init(rawValue:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/SubscriptionStatus\/description"]},{"title":"Default Implementations","identifiers":["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/SubscriptionStatus\/Equatable-Implementations","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/SubscriptionStatus\/RawRepresentable-Implementations"],"generated":true}],"references":{"doc://com.yababaGmbH.yababa/documentation/Yababa/SubscriptionStatus/unsubscribed":{"role":"symbol","title":"SubscriptionStatus.unsubscribed","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"unsubscribed"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/SubscriptionStatus\/unsubscribed","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SubscriptionStatusUnsubscribed"}],"url":"\/documentation\/yababa\/subscriptionstatus\/unsubscribed"},"doc://com.yababaGmbH.yababa/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/com.yababaGmbH.yababa\/s8SendableP"},"doc://com.yababaGmbH.yababa/documentation/Yababa":{"role":"collection","title":"Yababa","abstract":[{"type":"text","text":"Getting Started"}],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa","kind":"symbol","type":"topic","url":"\/documentation\/yababa"},"doc://com.yababaGmbH.yababa/documentation/Yababa/SubscriptionStatus/init(rawValue:)":{"role":"symbol","title":"init(rawValue:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/SubscriptionStatus\/init(rawValue:)","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/subscriptionstatus\/init(rawvalue:)"},"doc://com.yababaGmbH.yababa/documentation/Yababa/SubscriptionStatus/Equatable-Implementations":{"role":"collectionGroup","title":"Equatable Implementations","abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/SubscriptionStatus\/Equatable-Implementations","kind":"article","type":"topic","url":"\/documentation\/yababa\/subscriptionstatus\/equatable-implementations"},"doc://com.yababaGmbH.yababa/documentation/Yababa/SubscriptionStatus/description":{"role":"symbol","title":"description","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"description"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/SubscriptionStatus\/description","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/subscriptionstatus\/description"},"doc://com.yababaGmbH.yababa/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.yababaGmbH.yababa\/SH"},"doc://com.yababaGmbH.yababa/SY":{"type":"unresolvable","title":"Swift.RawRepresentable","identifier":"doc:\/\/com.yababaGmbH.yababa\/SY"},"doc://com.yababaGmbH.yababa/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.yababaGmbH.yababa\/SQ"},"doc://com.yababaGmbH.yababa/documentation/Yababa/SubscriptionStatus/subscribed":{"role":"symbol","title":"SubscriptionStatus.subscribed","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"subscribed"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/SubscriptionStatus\/subscribed","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SubscriptionStatusSubscribed"}],"url":"\/documentation\/yababa\/subscriptionstatus\/subscribed"},"doc://com.yababaGmbH.yababa/documentation/Yababa/SubscriptionStatus/optedIn":{"role":"symbol","title":"SubscriptionStatus.optedIn","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"optedIn"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/SubscriptionStatus\/optedIn","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SubscriptionStatusOptedIn"}],"url":"\/documentation\/yababa\/subscriptionstatus\/optedin"},"doc://com.yababaGmbH.yababa/documentation/Yababa/SubscriptionStatus":{"role":"symbol","title":"SubscriptionStatus","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SubscriptionStatus"}],"abstract":[{"type":"text","text":"OPTED_IN: subscribed, and explicitly opted in."},{"type":"text","text":" "},{"type":"text","text":"SUBSCRIBED: subscribed, but not explicitly opted in."},{"type":"text","text":" "},{"type":"text","text":"UNSUBSCRIBED: unsubscribed and\/or explicitly opted out."}],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/SubscriptionStatus","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SubscriptionStatus"}],"url":"\/documentation\/yababa\/subscriptionstatus"},"doc://com.yababaGmbH.yababa/documentation/Yababa/SubscriptionStatus/RawRepresentable-Implementations":{"role":"collectionGroup","title":"RawRepresentable Implementations","abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/SubscriptionStatus\/RawRepresentable-Implementations","kind":"article","type":"topic","url":"\/documentation\/yababa\/subscriptionstatus\/rawrepresentable-implementations"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration"},{"op":"replace","path":"\/metadata\/title","value":"SubscriptionStatus"},{"op":"replace","path":"\/metadata\/symbolKind","value":"enum"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SubscriptionStatus"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"SubscriptionStatus"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/SubscriptionStatus\/optedIn","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/SubscriptionStatus\/subscribed","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/SubscriptionStatus\/unsubscribed"]}]},{"op":"replace","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SubscriptionStatus"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1SubscriptionStatus~1unsubscribed\/title","value":"SubscriptionStatusUnsubscribed"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1SubscriptionStatus~1unsubscribed\/fragments","value":[{"kind":"identifier","text":"SubscriptionStatusUnsubscribed"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1SubscriptionStatus~1subscribed\/title","value":"SubscriptionStatusSubscribed"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1SubscriptionStatus~1subscribed\/fragments","value":[{"kind":"identifier","text":"SubscriptionStatusSubscribed"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1SubscriptionStatus~1optedIn\/title","value":"SubscriptionStatusOptedIn"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1SubscriptionStatus~1optedIn\/fragments","value":[{"kind":"identifier","text":"SubscriptionStatusOptedIn"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1SubscriptionStatus\/title","value":"SubscriptionStatus"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1SubscriptionStatus\/fragments","value":[{"kind":"identifier","text":"SubscriptionStatus"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}