{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TabBarController"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/yababa\/tabbarcontroller"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/yababa\/tabbarcontroller"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.yababaGmbH.yababa\/objc(cs)UITabBarController"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CustomBannerViewDelegate","doc:\/\/com.yababaGmbH.yababa\/objc(pl)NSCoding","doc:\/\/com.yababaGmbH.yababa\/objc(pl)NSExtensionRequestHandling","doc:\/\/com.yababaGmbH.yababa\/objc(pl)NSObject","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ShoppingCartObserver","doc:\/\/com.yababaGmbH.yababa\/12SkeletonView17AssociatedObjectsP","doc:\/\/com.yababaGmbH.yababa\/s7CVarArgP","doc:\/\/com.yababaGmbH.yababa\/s28CustomDebugStringConvertibleP","doc:\/\/com.yababaGmbH.yababa\/s23CustomStringConvertibleP","doc:\/\/com.yababaGmbH.yababa\/SQ","doc:\/\/com.yababaGmbH.yababa\/SH","doc:\/\/com.yababaGmbH.yababa\/s8SendableP","doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIActivityItemsConfigurationProviding","doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIAppearanceContainer","doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIContentContainer","doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIFocusEnvironment","doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIPasteConfigurationSupporting","doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIResponderStandardEditActions","doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIStateRestoring","doc:\/\/com.yababaGmbH.yababa\/objc(pl)UITabBarControllerDelegate","doc:\/\/com.yababaGmbH.yababa\/objc(pl)UITabBarDelegate","doc:\/\/com.yababaGmbH.yababa\/objc(pl)UITraitEnvironment","doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIUserActivityRestoring"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/TabBarController","interfaceLanguage":"swift"},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/TabBarController\/init()","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/TabBarController\/init(coder:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/TabBarController\/observation"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/TabBarController\/getIsBannerHidden()","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/TabBarController\/motionEnded(_:with:)","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/TabBarController\/onDismissBannerClicked()","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/TabBarController\/openCreateActivity(_:)","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/TabBarController\/populateTabControllers()","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/TabBarController\/selectPreviousScreen()","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/TabBarController\/setIdentifiers()","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/TabBarController\/setIsBannerHidden(_:withAnimation:)","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/TabBarController\/setupBannerView()","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/TabBarController\/showBadgeOnDiscountsIfNeeded()","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/TabBarController\/showBanner()","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/TabBarController\/showLanguageBanner()","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/TabBarController\/showReferralBanner(referralCode:referralValue:)","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/TabBarController\/tabBar(_:didSelect:)","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/TabBarController\/updateTabBarImages()","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/TabBarController\/viewDidLayoutSubviews()","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/TabBarController\/viewDidLoad()"]},{"title":"Default Implementations","identifiers":["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/TabBarController\/ShoppingCartObserver-Implementations"],"generated":true}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TabBarController"}],"title":"TabBarController","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@Yababa@objc(cs)TabBarController","modules":[{"name":"Yababa"}],"navigatorTitle":[{"kind":"identifier","text":"TabBarController"}]},"hierarchy":{"paths":[["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa"]]},"references":{"doc://com.yababaGmbH.yababa/documentation/Yababa/TabBarController/setIdentifiers()":{"role":"symbol","title":"setIdentifiers()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setIdentifiers"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/TabBarController\/setIdentifiers()","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/tabbarcontroller\/setidentifiers()"},"doc://com.yababaGmbH.yababa/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/com.yababaGmbH.yababa\/s8SendableP"},"doc://com.yababaGmbH.yababa/documentation/Yababa/TabBarController/observation":{"role":"symbol","title":"observation","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"observation"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSKeyValueObservation","preciseIdentifier":"c:@M@Foundation@objc(cs)_NSKeyValueObservation"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/TabBarController\/observation","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/tabbarcontroller\/observation"},"doc://com.yababaGmbH.yababa/documentation/Yababa/TabBarController/showReferralBanner(referralCode:referralValue:)":{"role":"symbol","title":"showReferralBanner(referralCode:referralValue:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"showReferralBanner"},{"kind":"text","text":"("},{"kind":"externalParam","text":"referralCode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"referralValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/TabBarController\/showReferralBanner(referralCode:referralValue:)","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/tabbarcontroller\/showreferralbanner(referralcode:referralvalue:)"},"doc://com.yababaGmbH.yababa/objc(pl)UITabBarControllerDelegate":{"type":"unresolvable","title":"UITabBarControllerDelegate","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)UITabBarControllerDelegate"},"doc://com.yababaGmbH.yababa/objc(pl)UIResponderStandardEditActions":{"type":"unresolvable","title":"UIKit.UIResponderStandardEditActions","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIResponderStandardEditActions"},"doc://com.yababaGmbH.yababa/objc(pl)UIContentContainer":{"type":"unresolvable","title":"UIKit.UIContentContainer","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIContentContainer"},"doc://com.yababaGmbH.yababa/documentation/Yababa/TabBarController/tabBar(_:didSelect:)":{"role":"symbol","title":"tabBar(_:didSelect:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"tabBar"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UITabBar","preciseIdentifier":"c:objc(cs)UITabBar"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didSelect"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UITabBarItem","preciseIdentifier":"c:objc(cs)UITabBarItem"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/TabBarController\/tabBar(_:didSelect:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"tabBar:didSelectItem:"}],"url":"\/documentation\/yababa\/tabbarcontroller\/tabbar(_:didselect:)"},"doc://com.yababaGmbH.yababa/objc(pl)UIPasteConfigurationSupporting":{"type":"unresolvable","title":"UIKit.UIPasteConfigurationSupporting","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIPasteConfigurationSupporting"},"doc://com.yababaGmbH.yababa/documentation/Yababa/TabBarController/getIsBannerHidden()":{"role":"symbol","title":"getIsBannerHidden()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getIsBannerHidden"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/TabBarController\/getIsBannerHidden()","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/tabbarcontroller\/getisbannerhidden()"},"doc://com.yababaGmbH.yababa/objc(pl)UITraitEnvironment":{"type":"unresolvable","title":"UIKit.UITraitEnvironment","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)UITraitEnvironment"},"doc://com.yababaGmbH.yababa/documentation/Yababa/TabBarController/updateTabBarImages()":{"role":"symbol","title":"updateTabBarImages()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"updateTabBarImages"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/TabBarController\/updateTabBarImages()","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/tabbarcontroller\/updatetabbarimages()"},"doc://com.yababaGmbH.yababa/documentation/Yababa/TabBarController/viewDidLoad()":{"role":"symbol","title":"viewDidLoad()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"viewDidLoad"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/TabBarController\/viewDidLoad()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"viewDidLoad"}],"url":"\/documentation\/yababa\/tabbarcontroller\/viewdidload()"},"doc://com.yababaGmbH.yababa/documentation/Yababa/TabBarController/populateTabControllers()":{"role":"symbol","title":"populateTabControllers()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"populateTabControllers"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/TabBarController\/populateTabControllers()","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/tabbarcontroller\/populatetabcontrollers()"},"doc://com.yababaGmbH.yababa/objc(pl)UIActivityItemsConfigurationProviding":{"type":"unresolvable","title":"UIKit.UIActivityItemsConfigurationProviding","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIActivityItemsConfigurationProviding"},"doc://com.yababaGmbH.yababa/documentation/Yababa/TabBarController/viewDidLayoutSubviews()":{"role":"symbol","title":"viewDidLayoutSubviews()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"viewDidLayoutSubviews"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/TabBarController\/viewDidLayoutSubviews()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"viewDidLayoutSubviews"}],"url":"\/documentation\/yababa\/tabbarcontroller\/viewdidlayoutsubviews()"},"doc://com.yababaGmbH.yababa/12SkeletonView17AssociatedObjectsP":{"type":"unresolvable","title":"SkeletonView.AssociatedObjects","identifier":"doc:\/\/com.yababaGmbH.yababa\/12SkeletonView17AssociatedObjectsP"},"doc://com.yababaGmbH.yababa/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.yababaGmbH.yababa\/SH"},"doc://com.yababaGmbH.yababa/documentation/Yababa/TabBarController/showLanguageBanner()":{"role":"symbol","title":"showLanguageBanner()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"showLanguageBanner"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/TabBarController\/showLanguageBanner()","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/tabbarcontroller\/showlanguagebanner()"},"doc://com.yababaGmbH.yababa/objc(pl)NSCoding":{"type":"unresolvable","title":"Foundation.NSCoding","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)NSCoding"},"doc://com.yababaGmbH.yababa/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.yababaGmbH.yababa\/SQ"},"doc://com.yababaGmbH.yababa/documentation/Yababa/CustomBannerViewDelegate":{"role":"symbol","title":"CustomBannerViewDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"CustomBannerViewDelegate"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CustomBannerViewDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CustomBannerViewDelegate"}],"url":"\/documentation\/yababa\/custombannerviewdelegate"},"doc://com.yababaGmbH.yababa/documentation/Yababa/TabBarController/showBanner()":{"role":"symbol","title":"showBanner()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"showBanner"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/TabBarController\/showBanner()","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/tabbarcontroller\/showbanner()"},"doc://com.yababaGmbH.yababa/documentation/Yababa/ShoppingCartObserver":{"role":"symbol","title":"ShoppingCartObserver","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"ShoppingCartObserver"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/ShoppingCartObserver","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ShoppingCartObserver"}],"url":"\/documentation\/yababa\/shoppingcartobserver"},"doc://com.yababaGmbH.yababa/documentation/Yababa/TabBarController/onDismissBannerClicked()":{"role":"symbol","title":"onDismissBannerClicked()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onDismissBannerClicked"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/TabBarController\/onDismissBannerClicked()","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/tabbarcontroller\/ondismissbannerclicked()"},"doc://com.yababaGmbH.yababa/documentation/Yababa/TabBarController/openCreateActivity(_:)":{"role":"symbol","title":"openCreateActivity(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"openCreateActivity"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UIStoryboardSegue","preciseIdentifier":"c:objc(cs)UIStoryboardSegue"},{"kind":"text","text":"?)"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/TabBarController\/openCreateActivity(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"openCreateActivity:"}],"url":"\/documentation\/yababa\/tabbarcontroller\/opencreateactivity(_:)"},"doc://com.yababaGmbH.yababa/documentation/Yababa/TabBarController/motionEnded(_:with:)":{"role":"symbol","title":"motionEnded(_:with:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"motionEnded"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UIEvent","preciseIdentifier":"c:objc(cs)UIEvent"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"EventSubtype","preciseIdentifier":"c:@E@UIEventSubtype"},{"kind":"text","text":", "},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIEvent","preciseIdentifier":"c:objc(cs)UIEvent"},{"kind":"text","text":"?)"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/TabBarController\/motionEnded(_:with:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"motionEnded:withEvent:"}],"url":"\/documentation\/yababa\/tabbarcontroller\/motionended(_:with:)"},"doc://com.yababaGmbH.yababa/objc(pl)UIAppearanceContainer":{"type":"unresolvable","title":"UIKit.UIAppearanceContainer","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIAppearanceContainer"},"doc://com.yababaGmbH.yababa/objc(pl)UIFocusEnvironment":{"type":"unresolvable","title":"UIKit.UIFocusEnvironment","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIFocusEnvironment"},"doc://com.yababaGmbH.yababa/objc(pl)UIUserActivityRestoring":{"type":"unresolvable","title":"UIKit.UIUserActivityRestoring","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIUserActivityRestoring"},"doc://com.yababaGmbH.yababa/documentation/Yababa/TabBarController":{"role":"symbol","title":"TabBarController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TabBarController"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/TabBarController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"TabBarController"}],"url":"\/documentation\/yababa\/tabbarcontroller"},"doc://com.yababaGmbH.yababa/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.yababaGmbH.yababa\/s7CVarArgP"},"doc://com.yababaGmbH.yababa/documentation/Yababa/TabBarController/selectPreviousScreen()":{"role":"symbol","title":"selectPreviousScreen()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"selectPreviousScreen"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/TabBarController\/selectPreviousScreen()","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/tabbarcontroller\/selectpreviousscreen()"},"doc://com.yababaGmbH.yababa/documentation/Yababa/TabBarController/showBadgeOnDiscountsIfNeeded()":{"role":"symbol","title":"showBadgeOnDiscountsIfNeeded()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"showBadgeOnDiscountsIfNeeded"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/TabBarController\/showBadgeOnDiscountsIfNeeded()","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/tabbarcontroller\/showbadgeondiscountsifneeded()"},"doc://com.yababaGmbH.yababa/objc(pl)NSExtensionRequestHandling":{"type":"unresolvable","title":"Foundation.NSExtensionRequestHandling","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)NSExtensionRequestHandling"},"doc://com.yababaGmbH.yababa/documentation/Yababa/TabBarController/init()":{"role":"symbol","title":"init()","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/TabBarController\/init()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"init"}],"url":"\/documentation\/yababa\/tabbarcontroller\/init()"},"doc://com.yababaGmbH.yababa/objc(cs)UITabBarController":{"type":"unresolvable","title":"UITabBarController","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(cs)UITabBarController"},"doc://com.yababaGmbH.yababa/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)NSObject"},"doc://com.yababaGmbH.yababa/documentation/Yababa/TabBarController/ShoppingCartObserver-Implementations":{"role":"collectionGroup","title":"ShoppingCartObserver Implementations","abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/TabBarController\/ShoppingCartObserver-Implementations","kind":"article","type":"topic","url":"\/documentation\/yababa\/tabbarcontroller\/shoppingcartobserver-implementations"},"doc://com.yababaGmbH.yababa/documentation/Yababa/TabBarController/setIsBannerHidden(_:withAnimation:)":{"role":"symbol","title":"setIsBannerHidden(_:withAnimation:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setIsBannerHidden"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"withAnimation"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/TabBarController\/setIsBannerHidden(_:withAnimation:)","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/tabbarcontroller\/setisbannerhidden(_:withanimation:)"},"doc://com.yababaGmbH.yababa/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.yababaGmbH.yababa\/s28CustomDebugStringConvertibleP"},"doc://com.yababaGmbH.yababa/documentation/Yababa/TabBarController/setupBannerView()":{"role":"symbol","title":"setupBannerView()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setupBannerView"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/TabBarController\/setupBannerView()","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/tabbarcontroller\/setupbannerview()"},"doc://com.yababaGmbH.yababa/documentation/Yababa/TabBarController/init(coder:)":{"role":"symbol","title":"init(coder:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"coder"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSCoder","preciseIdentifier":"c:objc(cs)NSCoder"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/TabBarController\/init(coder:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithCoder:"}],"url":"\/documentation\/yababa\/tabbarcontroller\/init(coder:)"},"doc://com.yababaGmbH.yababa/documentation/Yababa":{"role":"collection","title":"Yababa","abstract":[{"type":"text","text":"Getting Started"}],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa","kind":"symbol","type":"topic","url":"\/documentation\/yababa"},"doc://com.yababaGmbH.yababa/objc(pl)UITabBarDelegate":{"type":"unresolvable","title":"UIKit.UITabBarDelegate","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)UITabBarDelegate"},"doc://com.yababaGmbH.yababa/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.yababaGmbH.yababa\/s23CustomStringConvertibleP"},"doc://com.yababaGmbH.yababa/objc(pl)UIStateRestoring":{"type":"unresolvable","title":"UIKit.UIStateRestoring","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIStateRestoring"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"TabBarController"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"TabBarController"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"TabBarController"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/TabBarController\/init()","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/TabBarController\/init(coder:)","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/TabBarController\/motionEnded(_:with:)","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/TabBarController\/openCreateActivity(_:)","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/TabBarController\/tabBar(_:didSelect:)","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/TabBarController\/viewDidLayoutSubviews()","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/TabBarController\/viewDidLoad()"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.yababaGmbH.yababa\/objc(cs)UITabBarController"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.yababaGmbH.yababa\/objc(pl)UITabBarControllerDelegate"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"TabBarController"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"UITabBarController","preciseIdentifier":"c:objc(cs)UITabBarController"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1TabBarController~1tabBar(_:didSelect:)\/title","value":"tabBar:didSelectItem:"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1TabBarController~1tabBar(_:didSelect:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"tabBar:didSelectItem:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1TabBarController~1viewDidLoad()\/title","value":"viewDidLoad"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1TabBarController~1viewDidLoad()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"viewDidLoad"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1TabBarController~1viewDidLayoutSubviews()\/title","value":"viewDidLayoutSubviews"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1TabBarController~1viewDidLayoutSubviews()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"viewDidLayoutSubviews"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1TabBarController~1openCreateActivity(_:)\/title","value":"openCreateActivity:"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1TabBarController~1openCreateActivity(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"openCreateActivity:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1TabBarController~1motionEnded(_:with:)\/title","value":"motionEnded:withEvent:"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1TabBarController~1motionEnded(_:with:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"motionEnded:withEvent:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1TabBarController\/title","value":"TabBarController"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1TabBarController\/fragments","value":[{"kind":"identifier","text":"TabBarController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1TabBarController~1init()\/title","value":"init"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1TabBarController~1init()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1TabBarController~1init(coder:)\/title","value":"initWithCoder:"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1TabBarController~1init(coder:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithCoder:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}