{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"VoucherCollectionViewCell"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/yababa\/vouchercollectionviewcell"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/yababa\/vouchercollectionviewcell"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CollectionViewItemCell"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.yababaGmbH.yababa\/objc(pl)NSCoding","doc:\/\/com.yababaGmbH.yababa\/objc(pl)NSObject","doc:\/\/com.yababaGmbH.yababa\/objc(pl)CALayerDelegate","doc:\/\/com.yababaGmbH.yababa\/12SkeletonView17AssociatedObjectsP","doc:\/\/com.yababaGmbH.yababa\/12SkeletonView15IterableElementP","doc:\/\/com.yababaGmbH.yababa\/12SkeletonView11RecoverableP","doc:\/\/com.yababaGmbH.yababa\/12SkeletonView0A12ReusableCellP","doc:\/\/com.yababaGmbH.yababa\/6Stripe19SafeAreaLayoutGuideP","doc:\/\/com.yababaGmbH.yababa\/s7CVarArgP","doc:\/\/com.yababaGmbH.yababa\/s28CustomDebugStringConvertibleP","doc:\/\/com.yababaGmbH.yababa\/s23CustomStringConvertibleP","doc:\/\/com.yababaGmbH.yababa\/SQ","doc:\/\/com.yababaGmbH.yababa\/SH","doc:\/\/com.yababaGmbH.yababa\/s8SendableP","doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIAccessibilityIdentification","doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIActivityItemsConfigurationProviding","doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIAppearance","doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIAppearanceContainer","doc:\/\/com.yababaGmbH.yababa\/objc(pl)UICoordinateSpace","doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIDynamicItem","doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIFocusEnvironment","doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIFocusItem","doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIFocusItemContainer","doc:\/\/com.yababaGmbH.yababa\/objc(pl)UILargeContentViewerItem","doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIPasteConfigurationSupporting","doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIPopoverPresentationControllerSourceItem","doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIResponderStandardEditActions","doc:\/\/com.yababaGmbH.yababa\/objc(pl)UITraitEnvironment","doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIUserActivityRestoring","doc:\/\/com.yababaGmbH.yababa\/22ZendeskSDKUIComponents28UICollectionReusableViewTypeP"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/VoucherCollectionViewCell","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/VoucherCollectionViewCell\/voucherView"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/VoucherCollectionViewCell\/awakeFromNib()","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/VoucherCollectionViewCell\/setItem(_:)","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/VoucherCollectionViewCell\/setup(voucher:userSelectedVoucherCode:)"]}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"VoucherCollectionViewCell"}],"title":"VoucherCollectionViewCell","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@Yababa@objc(cs)VoucherCollectionViewCell","modules":[{"name":"Yababa"}],"navigatorTitle":[{"kind":"identifier","text":"VoucherCollectionViewCell"}]},"hierarchy":{"paths":[["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa"]]},"references":{"doc://com.yababaGmbH.yababa/documentation/Yababa/VoucherCollectionViewCell":{"role":"symbol","title":"VoucherCollectionViewCell","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"VoucherCollectionViewCell"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/VoucherCollectionViewCell","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"VoucherCollectionViewCell"}],"url":"\/documentation\/yababa\/vouchercollectionviewcell"},"doc://com.yababaGmbH.yababa/objc(pl)UIFocusEnvironment":{"type":"unresolvable","title":"UIKit.UIFocusEnvironment","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIFocusEnvironment"},"doc://com.yababaGmbH.yababa/objc(pl)UITraitEnvironment":{"type":"unresolvable","title":"UIKit.UITraitEnvironment","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)UITraitEnvironment"},"doc://com.yababaGmbH.yababa/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/com.yababaGmbH.yababa\/s8SendableP"},"doc://com.yababaGmbH.yababa/objc(pl)NSCoding":{"type":"unresolvable","title":"Foundation.NSCoding","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)NSCoding"},"doc://com.yababaGmbH.yababa/documentation/Yababa/VoucherCollectionViewCell/setItem(_:)":{"role":"symbol","title":"setItem(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setItem"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"ScreenItem","preciseIdentifier":"s:6Yababa10ScreenItemC"},{"kind":"text","text":"?)"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/VoucherCollectionViewCell\/setItem(_:)","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/vouchercollectionviewcell\/setitem(_:)"},"doc://com.yababaGmbH.yababa/6Stripe19SafeAreaLayoutGuideP":{"type":"unresolvable","title":"Stripe.SafeAreaLayoutGuide","identifier":"doc:\/\/com.yababaGmbH.yababa\/6Stripe19SafeAreaLayoutGuideP"},"doc://com.yababaGmbH.yababa/objc(pl)UIUserActivityRestoring":{"type":"unresolvable","title":"UIKit.UIUserActivityRestoring","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIUserActivityRestoring"},"doc://com.yababaGmbH.yababa/objc(pl)UIAppearanceContainer":{"type":"unresolvable","title":"UIKit.UIAppearanceContainer","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIAppearanceContainer"},"doc://com.yababaGmbH.yababa/documentation/Yababa/VoucherCollectionViewCell/initWithCoder:":{"role":"symbol","title":"initWithCoder:","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithCoder:"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/VoucherCollectionViewCell\/initWithCoder:","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithCoder:"}],"url":"\/documentation\/yababa\/vouchercollectionviewcell\/initwithcoder:"},"doc://com.yababaGmbH.yababa/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.yababaGmbH.yababa\/s28CustomDebugStringConvertibleP"},"doc://com.yababaGmbH.yababa/12SkeletonView15IterableElementP":{"type":"unresolvable","title":"SkeletonView.IterableElement","identifier":"doc:\/\/com.yababaGmbH.yababa\/12SkeletonView15IterableElementP"},"doc://com.yababaGmbH.yababa/objc(pl)UIAppearance":{"type":"unresolvable","title":"UIKit.UIAppearance","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIAppearance"},"doc://com.yababaGmbH.yababa/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)NSObject"},"doc://com.yababaGmbH.yababa/12SkeletonView11RecoverableP":{"type":"unresolvable","title":"SkeletonView.Recoverable","identifier":"doc:\/\/com.yababaGmbH.yababa\/12SkeletonView11RecoverableP"},"doc://com.yababaGmbH.yababa/documentation/Yababa":{"role":"collection","title":"Yababa","abstract":[{"type":"text","text":"Getting Started"}],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa","kind":"symbol","type":"topic","url":"\/documentation\/yababa"},"doc://com.yababaGmbH.yababa/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.yababaGmbH.yababa\/s23CustomStringConvertibleP"},"doc://com.yababaGmbH.yababa/objc(pl)UIFocusItem":{"type":"unresolvable","title":"UIKit.UIFocusItem","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIFocusItem"},"doc://com.yababaGmbH.yababa/objc(pl)UIActivityItemsConfigurationProviding":{"type":"unresolvable","title":"UIKit.UIActivityItemsConfigurationProviding","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIActivityItemsConfigurationProviding"},"doc://com.yababaGmbH.yababa/22ZendeskSDKUIComponents28UICollectionReusableViewTypeP":{"type":"unresolvable","title":"ZendeskSDKUIComponents.UICollectionReusableViewType","identifier":"doc:\/\/com.yababaGmbH.yababa\/22ZendeskSDKUIComponents28UICollectionReusableViewTypeP"},"doc://com.yababaGmbH.yababa/objc(pl)UIFocusItemContainer":{"type":"unresolvable","title":"UIKit.UIFocusItemContainer","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIFocusItemContainer"},"doc://com.yababaGmbH.yababa/objc(pl)UICoordinateSpace":{"type":"unresolvable","title":"UIKit.UICoordinateSpace","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)UICoordinateSpace"},"doc://com.yababaGmbH.yababa/objc(pl)CALayerDelegate":{"type":"unresolvable","title":"QuartzCore.CALayerDelegate","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)CALayerDelegate"},"doc://com.yababaGmbH.yababa/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.yababaGmbH.yababa\/SQ"},"doc://com.yababaGmbH.yababa/objc(pl)UIPopoverPresentationControllerSourceItem":{"type":"unresolvable","title":"UIKit.UIPopoverPresentationControllerSourceItem","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIPopoverPresentationControllerSourceItem"},"doc://com.yababaGmbH.yababa/objc(pl)UIDynamicItem":{"type":"unresolvable","title":"UIKit.UIDynamicItem","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIDynamicItem"},"doc://com.yababaGmbH.yababa/objc(pl)UIResponderStandardEditActions":{"type":"unresolvable","title":"UIKit.UIResponderStandardEditActions","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIResponderStandardEditActions"},"doc://com.yababaGmbH.yababa/12SkeletonView0A12ReusableCellP":{"type":"unresolvable","title":"SkeletonView.SkeletonReusableCell","identifier":"doc:\/\/com.yababaGmbH.yababa\/12SkeletonView0A12ReusableCellP"},"doc://com.yababaGmbH.yababa/documentation/Yababa/VoucherCollectionViewCell/setup(voucher:userSelectedVoucherCode:)":{"role":"symbol","title":"setup(voucher:userSelectedVoucherCode:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setup"},{"kind":"text","text":"("},{"kind":"externalParam","text":"voucher"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"VoucherView","preciseIdentifier":"c:@M@Yababa@objc(cs)VoucherView"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"Data","preciseIdentifier":"s:6Yababa11VoucherViewC4DataV"},{"kind":"text","text":", "},{"kind":"externalParam","text":"userSelectedVoucherCode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?)"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/VoucherCollectionViewCell\/setup(voucher:userSelectedVoucherCode:)","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/vouchercollectionviewcell\/setup(voucher:userselectedvouchercode:)"},"doc://com.yababaGmbH.yababa/objc(pl)UIPasteConfigurationSupporting":{"type":"unresolvable","title":"UIKit.UIPasteConfigurationSupporting","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIPasteConfigurationSupporting"},"doc://com.yababaGmbH.yababa/documentation/Yababa/VoucherCollectionViewCell/voucherView":{"role":"symbol","title":"voucherView","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"voucherView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"VoucherView","preciseIdentifier":"c:@M@Yababa@objc(cs)VoucherView"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/VoucherCollectionViewCell\/voucherView","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/vouchercollectionviewcell\/voucherview"},"doc://com.yababaGmbH.yababa/documentation/Yababa/VoucherCollectionViewCell/awakeFromNib()":{"role":"symbol","title":"awakeFromNib()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"awakeFromNib"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/VoucherCollectionViewCell\/awakeFromNib()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"awakeFromNib"}],"url":"\/documentation\/yababa\/vouchercollectionviewcell\/awakefromnib()"},"doc://com.yababaGmbH.yababa/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.yababaGmbH.yababa\/s7CVarArgP"},"doc://com.yababaGmbH.yababa/objc(pl)UIAccessibilityIdentification":{"type":"unresolvable","title":"UIKit.UIAccessibilityIdentification","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)UIAccessibilityIdentification"},"doc://com.yababaGmbH.yababa/documentation/Yababa/VoucherCollectionViewCell/initWithFrame:":{"role":"symbol","title":"initWithFrame:","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithFrame:"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/VoucherCollectionViewCell\/initWithFrame:","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithFrame:"}],"url":"\/documentation\/yababa\/vouchercollectionviewcell\/initwithframe:"},"doc://com.yababaGmbH.yababa/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.yababaGmbH.yababa\/SH"},"doc://com.yababaGmbH.yababa/documentation/Yababa/CollectionViewItemCell":{"role":"symbol","title":"CollectionViewItemCell","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CollectionViewItemCell"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CollectionViewItemCell","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CollectionViewItemCell"}],"url":"\/documentation\/yababa\/collectionviewitemcell"},"doc://com.yababaGmbH.yababa/12SkeletonView17AssociatedObjectsP":{"type":"unresolvable","title":"SkeletonView.AssociatedObjects","identifier":"doc:\/\/com.yababaGmbH.yababa\/12SkeletonView17AssociatedObjectsP"},"doc://com.yababaGmbH.yababa/objc(pl)UILargeContentViewerItem":{"type":"unresolvable","title":"UIKit.UILargeContentViewerItem","identifier":"doc:\/\/com.yababaGmbH.yababa\/objc(pl)UILargeContentViewerItem"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"VoucherCollectionViewCell"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"VoucherCollectionViewCell"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"VoucherCollectionViewCell"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/VoucherCollectionViewCell\/awakeFromNib()","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/VoucherCollectionViewCell\/initWithCoder:","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/VoucherCollectionViewCell\/initWithFrame:"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CollectionViewItemCell"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"VoucherCollectionViewCell"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CollectionViewItemCell","preciseIdentifier":"c:@M@Yababa@objc(cs)CollectionViewItemCell","text":"CollectionViewItemCell"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1VoucherCollectionViewCell\/title","value":"VoucherCollectionViewCell"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1VoucherCollectionViewCell\/fragments","value":[{"kind":"identifier","text":"VoucherCollectionViewCell"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1VoucherCollectionViewCell~1awakeFromNib()\/title","value":"awakeFromNib"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1VoucherCollectionViewCell~1awakeFromNib()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"awakeFromNib"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1CollectionViewItemCell\/title","value":"CollectionViewItemCell"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1CollectionViewItemCell\/fragments","value":[{"kind":"identifier","text":"CollectionViewItemCell"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}