{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"applePayContext"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"context"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"STPApplePayContext","preciseIdentifier":"c:@M@StripeApplePay@objc(cs)_stpinternal_APContextSwift"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didCompleteWith"},{"kind":"text","text":" "},{"kind":"internalParam","text":"status"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"STPPaymentStatus","preciseIdentifier":"c:@M@Stripe@E@STPPaymentStatus"},{"kind":"text","text":", "},{"kind":"externalParam","text":"error"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?)"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/yababa\/stripeapplepay\/applepaycontext(_:didcompletewith:error:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/yababa\/stripeapplepay\/applepaycontext(_:didcompletewith:error:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/StripeApplePay\/applePayContext(_:didCompleteWith:error:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"STPApplePayContextDelegate.applePayContext(_:didCompleteWith:error:)"},{"type":"text","text":"."}],"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"applePayContext:didCompleteWithStatus:error:"}],"role":"symbol","title":"applePayContext(_:didCompleteWith:error:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"applePayContext"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"STPApplePayContext","preciseIdentifier":"c:@M@StripeApplePay@objc(cs)_stpinternal_APContextSwift"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didCompleteWith"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"STPPaymentStatus","preciseIdentifier":"c:@M@Stripe@E@STPPaymentStatus"},{"kind":"text","text":", "},{"kind":"externalParam","text":"error"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?)"}],"symbolKind":"method","externalID":"c:@CM@Yababa@objc(cs)StripeApplePay(im)applePayContext:didCompleteWithStatus:error:","extendedModule":"Yababa","modules":[{"name":"Yababa"}]},"hierarchy":{"paths":[["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/StripeApplePay","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/StripeApplePay\/STPApplePayContextDelegate-Implementations"]]},"references":{"doc://com.yababaGmbH.yababa/documentation/Yababa":{"role":"collection","title":"Yababa","abstract":[{"type":"text","text":"Getting Started"}],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa","kind":"symbol","type":"topic","url":"\/documentation\/yababa"},"doc://com.yababaGmbH.yababa/documentation/Yababa/StripeApplePay":{"role":"symbol","title":"StripeApplePay","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"StripeApplePay"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/StripeApplePay","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"StripeApplePay"}],"url":"\/documentation\/yababa\/stripeapplepay"},"doc://com.yababaGmbH.yababa/documentation/Yababa/StripeApplePay/STPApplePayContextDelegate-Implementations":{"role":"collectionGroup","title":"STPApplePayContextDelegate Implementations","abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/StripeApplePay\/STPApplePayContextDelegate-Implementations","kind":"article","type":"topic","url":"\/documentation\/yababa\/stripeapplepay\/stpapplepaycontextdelegate-implementations"},"doc://com.yababaGmbH.yababa/documentation/Yababa/StripeApplePay/applePayContext(_:didCompleteWith:error:)":{"role":"symbol","title":"applePayContext(_:didCompleteWith:error:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"applePayContext"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"STPApplePayContext","preciseIdentifier":"c:@M@StripeApplePay@objc(cs)_stpinternal_APContextSwift"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didCompleteWith"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"STPPaymentStatus","preciseIdentifier":"c:@M@Stripe@E@STPPaymentStatus"},{"kind":"text","text":", "},{"kind":"externalParam","text":"error"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?)"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/StripeApplePay\/applePayContext(_:didCompleteWith:error:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"applePayContext:didCompleteWithStatus:error:"}],"url":"\/documentation\/yababa\/stripeapplepay\/applepaycontext(_:didcompletewith:error:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"applePayContext:didCompleteWithStatus:error:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"applePayContext:didCompleteWithStatus:error:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"applePayContext:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"_stpinternal_APContextSwift","preciseIdentifier":"c:@M@StripeApplePay@objc(cs)_stpinternal_APContextSwift"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"context"},{"kind":"text","text":" "},{"kind":"identifier","text":"didCompleteWithStatus:"},{"kind":"text","text":"("},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"typeIdentifier","text":"STPPaymentStatus","preciseIdentifier":"c:@M@Stripe@E@STPPaymentStatus"},{"kind":"text","text":")"},{"kind":"internalParam","text":"status"},{"kind":"text","text":" "},{"kind":"identifier","text":"error:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSError","preciseIdentifier":"c:objc(cs)NSError"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"error"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1StripeApplePay\/title","value":"StripeApplePay"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1StripeApplePay\/fragments","value":[{"kind":"identifier","text":"StripeApplePay"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1StripeApplePay~1applePayContext(_:didCompleteWith:error:)\/title","value":"applePayContext:didCompleteWithStatus:error:"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1StripeApplePay~1applePayContext(_:didCompleteWith:error:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"applePayContext:didCompleteWithStatus:error:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}