{"variants":[{"paths":["\/documentation\/yababa\/stripeapplepay\/stpapplepaycontextdelegate-implementations"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/yababa\/stripeapplepay\/stpapplepaycontextdelegate-implementations"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"identifier":{"url":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/StripeApplePay\/STPApplePayContextDelegate-Implementations","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/StripeApplePay\/applePayContext(_:didCompleteWith:error:)","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/StripeApplePay\/applePayContext(_:didCreatePaymentMethod:paymentInformation:completion:)"],"generated":true}],"kind":"article","metadata":{"modules":[{"name":"Yababa"}],"role":"collectionGroup","title":"STPApplePayContextDelegate Implementations"},"hierarchy":{"paths":[["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/StripeApplePay"]]},"references":{"doc://com.yababaGmbH.yababa/documentation/Yababa/StripeApplePay":{"role":"symbol","title":"StripeApplePay","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"StripeApplePay"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/StripeApplePay","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"StripeApplePay"}],"url":"\/documentation\/yababa\/stripeapplepay"},"doc://com.yababaGmbH.yababa/documentation/Yababa":{"role":"collection","title":"Yababa","abstract":[{"type":"text","text":"Getting Started"}],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa","kind":"symbol","type":"topic","url":"\/documentation\/yababa"},"doc://com.yababaGmbH.yababa/documentation/Yababa/StripeApplePay/applePayContext(_:didCreatePaymentMethod:paymentInformation:completion:)":{"role":"symbol","title":"applePayContext(_:didCreatePaymentMethod:paymentInformation:completion:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"applePayContext"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"STPApplePayContext","preciseIdentifier":"c:@M@StripeApplePay@objc(cs)_stpinternal_APContextSwift"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didCreatePaymentMethod"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"STPPaymentMethod","preciseIdentifier":"c:@M@Stripe@objc(cs)STPPaymentMethod"},{"kind":"text","text":", "},{"kind":"externalParam","text":"paymentInformation"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"PKPayment","preciseIdentifier":"c:objc(cs)PKPayment"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"STPIntentClientSecretCompletionBlock","preciseIdentifier":"s:14StripeApplePay36STPIntentClientSecretCompletionBlocka"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/StripeApplePay\/applePayContext(_:didCreatePaymentMethod:paymentInformation:completion:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"applePayContext:didCreatePaymentMethod:paymentInformation:completion:"}],"url":"\/documentation\/yababa\/stripeapplepay\/applepaycontext(_:didcreatepaymentmethod:paymentinformation:completion:)"},"doc://com.yababaGmbH.yababa/documentation/Yababa/StripeApplePay/applePayContext(_:didCompleteWith:error:)":{"role":"symbol","title":"applePayContext(_:didCompleteWith:error:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"applePayContext"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"STPApplePayContext","preciseIdentifier":"c:@M@StripeApplePay@objc(cs)_stpinternal_APContextSwift"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didCompleteWith"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"STPPaymentStatus","preciseIdentifier":"c:@M@Stripe@E@STPPaymentStatus"},{"kind":"text","text":", "},{"kind":"externalParam","text":"error"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?)"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/StripeApplePay\/applePayContext(_:didCompleteWith:error:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"applePayContext:didCompleteWithStatus:error:"}],"url":"\/documentation\/yababa\/stripeapplepay\/applepaycontext(_:didcompletewith:error:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/StripeApplePay\/applePayContext(_:didCompleteWith:error:)","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/StripeApplePay\/applePayContext(_:didCreatePaymentMethod:paymentInformation:completion:)"],"generated":true}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1StripeApplePay\/title","value":"StripeApplePay"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1StripeApplePay\/fragments","value":[{"kind":"identifier","text":"StripeApplePay"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1StripeApplePay~1applePayContext(_:didCreatePaymentMethod:paymentInformation:completion:)\/title","value":"applePayContext:didCreatePaymentMethod:paymentInformation:completion:"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1StripeApplePay~1applePayContext(_:didCreatePaymentMethod:paymentInformation:completion:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"applePayContext:didCreatePaymentMethod:paymentInformation:completion:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1StripeApplePay~1applePayContext(_:didCompleteWith:error:)\/title","value":"applePayContext:didCompleteWithStatus:error:"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1StripeApplePay~1applePayContext(_:didCompleteWith:error:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"applePayContext:didCompleteWithStatus:error:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}