{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@IBAction"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onKeepItemsInCart"},{"kind":"text","text":"()"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/yababa\/pricesupdatedpopup\/onkeepitemsincart()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/yababa\/pricesupdatedpopup\/onkeepitemsincart()"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/PricesUpdatedPopup\/onKeepItemsInCart()","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onKeepItemsInCart"},{"kind":"text","text":"()"}],"title":"onKeepItemsInCart()","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@M@Yababa@objc(cs)PricesUpdatedPopup(im)onKeepItemsInCart","modules":[{"name":"Yababa"}],"navigatorTitle":[{"kind":"identifier","text":"onKeepItemsInCart"}]},"hierarchy":{"paths":[["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/PricesUpdatedPopup"]]},"references":{"doc://com.yababaGmbH.yababa/documentation/Yababa/PricesUpdatedPopup":{"role":"symbol","title":"PricesUpdatedPopup","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PricesUpdatedPopup"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/PricesUpdatedPopup","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PricesUpdatedPopup"}],"url":"\/documentation\/yababa\/pricesupdatedpopup"},"doc://com.yababaGmbH.yababa/documentation/Yababa":{"role":"collection","title":"Yababa","abstract":[{"type":"text","text":"Getting Started"}],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa","kind":"symbol","type":"topic","url":"\/documentation\/yababa"},"doc://com.yababaGmbH.yababa/documentation/Yababa/PricesUpdatedPopup/onKeepItemsInCart()":{"role":"symbol","title":"onKeepItemsInCart()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onKeepItemsInCart"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/PricesUpdatedPopup\/onKeepItemsInCart()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"onKeepItemsInCart"}],"url":"\/documentation\/yababa\/pricesupdatedpopup\/onkeepitemsincart()"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"onKeepItemsInCart"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onKeepItemsInCart"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"onKeepItemsInCart"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1PricesUpdatedPopup\/title","value":"PricesUpdatedPopup"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1PricesUpdatedPopup\/fragments","value":[{"kind":"identifier","text":"PricesUpdatedPopup"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1PricesUpdatedPopup~1onKeepItemsInCart()\/title","value":"onKeepItemsInCart"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1PricesUpdatedPopup~1onKeepItemsInCart()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onKeepItemsInCart"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}