{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"categoryAndProductsViews"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CategoryAndProductsViewController","preciseIdentifier":"c:@M@Yababa@objc(cs)CategoryAndProductsViewController","text":"CategoryAndProductsViewController"},{"kind":"text","text":"]"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/yababa\/catalogueviewcontroller\/categoryandproductsviews"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CatalogueViewController\/categoryAndProductsViews","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"categoryAndProductsViews"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"CategoryAndProductsViewController","preciseIdentifier":"c:@M@Yababa@objc(cs)CategoryAndProductsViewController"},{"kind":"text","text":"]"}],"title":"categoryAndProductsViews","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"s:6Yababa23CatalogueViewControllerC24categoryAndProductsViewsSayAA08CategoryfgcD0CGvp","modules":[{"name":"Yababa"}]},"hierarchy":{"paths":[["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CatalogueViewController"]]},"references":{"doc://com.yababaGmbH.yababa/documentation/Yababa/CategoryAndProductsViewController":{"role":"symbol","title":"CategoryAndProductsViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CategoryAndProductsViewController"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CategoryAndProductsViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CategoryAndProductsViewController"}],"url":"\/documentation\/yababa\/categoryandproductsviewcontroller"},"doc://com.yababaGmbH.yababa/documentation/Yababa/CatalogueViewController/categoryAndProductsViews":{"role":"symbol","title":"categoryAndProductsViews","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"categoryAndProductsViews"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"CategoryAndProductsViewController","preciseIdentifier":"c:@M@Yababa@objc(cs)CategoryAndProductsViewController"},{"kind":"text","text":"]"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CatalogueViewController\/categoryAndProductsViews","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/catalogueviewcontroller\/categoryandproductsviews"},"doc://com.yababaGmbH.yababa/documentation/Yababa":{"role":"collection","title":"Yababa","abstract":[{"type":"text","text":"Getting Started"}],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa","kind":"symbol","type":"topic","url":"\/documentation\/yababa"},"doc://com.yababaGmbH.yababa/documentation/Yababa/CatalogueViewController":{"role":"symbol","title":"CatalogueViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CatalogueViewController"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CatalogueViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CatalogueViewController"}],"url":"\/documentation\/yababa\/catalogueviewcontroller"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1CategoryAndProductsViewController\/title","value":"CategoryAndProductsViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1CategoryAndProductsViewController\/fragments","value":[{"kind":"identifier","text":"CategoryAndProductsViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1CatalogueViewController\/title","value":"CatalogueViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1CatalogueViewController\/fragments","value":[{"kind":"identifier","text":"CatalogueViewController"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}