{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isCurrentEnvironmentLive"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/yababa\/appinfo\/iscurrentenvironmentlive"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/yababa\/appinfo\/iscurrentenvironmentlive"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AppInfo\/isCurrentEnvironmentLive","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isCurrentEnvironmentLive"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"title":"isCurrentEnvironmentLive","roleHeading":"Type Property","role":"symbol","symbolKind":"property","externalID":"c:@M@Yababa@objc(cs)AppInfo(cpy)isCurrentEnvironmentLive","modules":[{"name":"Yababa"}],"navigatorTitle":[{"kind":"identifier","text":"isCurrentEnvironmentLive"}]},"hierarchy":{"paths":[["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AppInfo"]]},"references":{"doc://com.yababaGmbH.yababa/documentation/Yababa/AppInfo":{"role":"symbol","title":"AppInfo","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AppInfo"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AppInfo","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AppInfo"}],"url":"\/documentation\/yababa\/appinfo"},"doc://com.yababaGmbH.yababa/documentation/Yababa/AppInfo/isCurrentEnvironmentLive":{"role":"symbol","title":"isCurrentEnvironmentLive","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isCurrentEnvironmentLive"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AppInfo\/isCurrentEnvironmentLive","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"isCurrentEnvironmentLive"}],"url":"\/documentation\/yababa\/appinfo\/iscurrentenvironmentlive"},"doc://com.yababaGmbH.yababa/documentation/Yababa":{"role":"collection","title":"Yababa","abstract":[{"type":"text","text":"Getting Started"}],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa","kind":"symbol","type":"topic","url":"\/documentation\/yababa"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Property"},{"op":"replace","path":"\/metadata\/title","value":"isCurrentEnvironmentLive"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"isCurrentEnvironmentLive"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"class"},{"kind":"text","text":", "},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":" "},{"kind":"identifier","text":"isCurrentEnvironmentLive"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1AppInfo\/title","value":"AppInfo"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1AppInfo\/fragments","value":[{"kind":"identifier","text":"AppInfo"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1AppInfo~1isCurrentEnvironmentLive\/title","value":"isCurrentEnvironmentLive"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1AppInfo~1isCurrentEnvironmentLive\/fragments","value":[{"kind":"identifier","text":"isCurrentEnvironmentLive"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}