{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getFormattedPhoneNumber"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/yababa\/myphonenumbertextfield\/getformattedphonenumber()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/yababa\/myphonenumbertextfield\/getformattedphonenumber()"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/MyPhoneNumberTextField\/getFormattedPhoneNumber()","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getFormattedPhoneNumber"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"title":"getFormattedPhoneNumber()","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@M@Yababa@objc(cs)MyPhoneNumberTextField(im)getFormattedPhoneNumber","modules":[{"name":"Yababa"}],"navigatorTitle":[{"kind":"identifier","text":"getFormattedPhoneNumber"}]},"hierarchy":{"paths":[["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/MyPhoneNumberTextField"]]},"references":{"doc://com.yababaGmbH.yababa/documentation/Yababa/MyPhoneNumberTextField/getFormattedPhoneNumber()":{"role":"symbol","title":"getFormattedPhoneNumber()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getFormattedPhoneNumber"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/MyPhoneNumberTextField\/getFormattedPhoneNumber()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"getFormattedPhoneNumber"}],"url":"\/documentation\/yababa\/myphonenumbertextfield\/getformattedphonenumber()"},"doc://com.yababaGmbH.yababa/documentation/Yababa/MyPhoneNumberTextField":{"role":"symbol","title":"MyPhoneNumberTextField","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MyPhoneNumberTextField"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/MyPhoneNumberTextField","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MyPhoneNumberTextField"}],"url":"\/documentation\/yababa\/myphonenumbertextfield"},"doc://com.yababaGmbH.yababa/documentation/Yababa":{"role":"collection","title":"Yababa","abstract":[{"type":"text","text":"Getting Started"}],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa","kind":"symbol","type":"topic","url":"\/documentation\/yababa"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"getFormattedPhoneNumber"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"getFormattedPhoneNumber"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"getFormattedPhoneNumber"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1MyPhoneNumberTextField~1getFormattedPhoneNumber()\/title","value":"getFormattedPhoneNumber"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1MyPhoneNumberTextField~1getFormattedPhoneNumber()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"getFormattedPhoneNumber"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1MyPhoneNumberTextField\/title","value":"MyPhoneNumberTextField"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1MyPhoneNumberTextField\/fragments","value":[{"kind":"identifier","text":"MyPhoneNumberTextField"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}