{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setUserEmailSubscription"},{"kind":"text","text":"("},{"kind":"externalParam","text":"status"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ABKNotificationSubscriptionType","preciseIdentifier":"c:@E@ABKNotificationSubscriptionType"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/yababa\/brazemanager\/setuseremailsubscription(status:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/yababa\/brazemanager\/setuseremailsubscription(status:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/BrazeManager\/setUserEmailSubscription(status:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"You can set the email subscription state for an email address that is not yet associated with any users within Braze."},{"type":"text","text":" "},{"type":"text","text":"When that email address is subsequently associated with a user, the email subscription state that you uploaded will be automatically set."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setUserEmailSubscription"},{"kind":"text","text":"("},{"kind":"externalParam","text":"status"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ABKNotificationSubscriptionType","preciseIdentifier":"c:@E@ABKNotificationSubscriptionType"},{"kind":"text","text":")"}],"title":"setUserEmailSubscription(status:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@M@Yababa@objc(cs)BrazeManager(im)setUserEmailSubscriptionWithStatus:","modules":[{"name":"Yababa"}],"navigatorTitle":[{"kind":"identifier","text":"setUserEmailSubscriptionWithStatus:"}]},"hierarchy":{"paths":[["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/BrazeManager"]]},"references":{"doc://com.yababaGmbH.yababa/documentation/Yababa/BrazeManager":{"role":"symbol","title":"BrazeManager","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"BrazeManager"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/BrazeManager","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"BrazeManager"}],"url":"\/documentation\/yababa\/brazemanager"},"doc://com.yababaGmbH.yababa/documentation/Yababa/BrazeManager/setUserEmailSubscription(status:)":{"role":"symbol","title":"setUserEmailSubscription(status:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setUserEmailSubscription"},{"kind":"text","text":"("},{"kind":"externalParam","text":"status"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ABKNotificationSubscriptionType","preciseIdentifier":"c:@E@ABKNotificationSubscriptionType"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"You can set the email subscription state for an email address that is not yet associated with any users within Braze."},{"type":"text","text":" "},{"type":"text","text":"When that email address is subsequently associated with a user, the email subscription state that you uploaded will be automatically set."}],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/BrazeManager\/setUserEmailSubscription(status:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"setUserEmailSubscriptionWithStatus:"}],"url":"\/documentation\/yababa\/brazemanager\/setuseremailsubscription(status:)"},"doc://com.yababaGmbH.yababa/documentation/Yababa":{"role":"collection","title":"Yababa","abstract":[{"type":"text","text":"Getting Started"}],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa","kind":"symbol","type":"topic","url":"\/documentation\/yababa"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"setUserEmailSubscriptionWithStatus:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setUserEmailSubscriptionWithStatus:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"setUserEmailSubscriptionWithStatus:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"ABKNotificationSubscriptionType","preciseIdentifier":"c:@E@ABKNotificationSubscriptionType"},{"kind":"text","text":")"},{"kind":"internalParam","text":"status"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1BrazeManager\/title","value":"BrazeManager"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1BrazeManager\/fragments","value":[{"kind":"identifier","text":"BrazeManager"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1BrazeManager~1setUserEmailSubscription(status:)\/title","value":"setUserEmailSubscriptionWithStatus:"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1BrazeManager~1setUserEmailSubscription(status:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setUserEmailSubscriptionWithStatus:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}