{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"requestForCity"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withLong"},{"kind":"text","text":" "},{"kind":"internalParam","text":"lng"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"},{"kind":"text","text":", "},{"kind":"externalParam","text":"andLat"},{"kind":"text","text":" "},{"kind":"internalParam","text":"lat"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/yababa\/inlocationmanager\/requestforcity(withlong:andlat:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/yababa\/inlocationmanager\/requestforcity(withlong:andlat:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/INLocationManager\/requestForCity(withLong:andLat:)","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"requestForCity"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withLong"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"},{"kind":"text","text":", "},{"kind":"externalParam","text":"andLat"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"},{"kind":"text","text":")"}],"title":"requestForCity(withLong:andLat:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:objc(cs)INLocationManager(im)RequestForCityWithLong:andLat:","modules":[{"name":"Yababa"}],"navigatorTitle":[{"kind":"identifier","text":"RequestForCityWithLong:andLat:"}]},"hierarchy":{"paths":[["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/INLocationManager"]]},"references":{"doc://com.yababaGmbH.yababa/documentation/Yababa":{"role":"collection","title":"Yababa","abstract":[{"type":"text","text":"Getting Started"}],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa","kind":"symbol","type":"topic","url":"\/documentation\/yababa"},"doc://com.yababaGmbH.yababa/documentation/Yababa/INLocationManager":{"role":"symbol","title":"INLocationManager","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"INLocationManager"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/INLocationManager","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"INLocationManager"}],"url":"\/documentation\/yababa\/inlocationmanager"},"doc://com.yababaGmbH.yababa/documentation/Yababa/INLocationManager/requestForCity(withLong:andLat:)":{"role":"symbol","title":"requestForCity(withLong:andLat:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"requestForCity"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withLong"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"},{"kind":"text","text":", "},{"kind":"externalParam","text":"andLat"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/INLocationManager\/requestForCity(withLong:andLat:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"RequestForCityWithLong:andLat:"}],"url":"\/documentation\/yababa\/inlocationmanager\/requestforcity(withlong:andlat:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"RequestForCityWithLong:andLat:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"RequestForCityWithLong:andLat:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"RequestForCityWithLong:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"double","preciseIdentifier":"c:d"},{"kind":"text","text":")"},{"kind":"internalParam","text":"lng"},{"kind":"text","text":" "},{"kind":"identifier","text":"andLat:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"double","preciseIdentifier":"c:d"},{"kind":"text","text":")"},{"kind":"internalParam","text":"lat"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1INLocationManager\/title","value":"INLocationManager"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1INLocationManager\/fragments","value":[{"kind":"identifier","text":"INLocationManager"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1INLocationManager~1requestForCity(withLong:andLat:)\/title","value":"RequestForCityWithLong:andLat:"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1INLocationManager~1requestForCity(withLong:andLat:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"RequestForCityWithLong:andLat:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}