{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@IBAction"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onDismissKeyboard"},{"kind":"text","text":"()"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/yababa\/stripegatewayviewcontroller\/ondismisskeyboard()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/yababa\/stripegatewayviewcontroller\/ondismisskeyboard()"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/StripeGatewayViewController\/onDismissKeyboard()","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onDismissKeyboard"},{"kind":"text","text":"()"}],"title":"onDismissKeyboard()","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@M@Yababa@objc(cs)StripeGatewayViewController(im)onDismissKeyboard","modules":[{"name":"Yababa"}],"navigatorTitle":[{"kind":"identifier","text":"onDismissKeyboard"}]},"hierarchy":{"paths":[["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/StripeGatewayViewController"]]},"references":{"doc://com.yababaGmbH.yababa/documentation/Yababa/StripeGatewayViewController":{"role":"symbol","title":"StripeGatewayViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"StripeGatewayViewController"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/StripeGatewayViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"StripeGatewayViewController"}],"url":"\/documentation\/yababa\/stripegatewayviewcontroller"},"doc://com.yababaGmbH.yababa/documentation/Yababa":{"role":"collection","title":"Yababa","abstract":[{"type":"text","text":"Getting Started"}],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa","kind":"symbol","type":"topic","url":"\/documentation\/yababa"},"doc://com.yababaGmbH.yababa/documentation/Yababa/StripeGatewayViewController/onDismissKeyboard()":{"role":"symbol","title":"onDismissKeyboard()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onDismissKeyboard"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/StripeGatewayViewController\/onDismissKeyboard()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"onDismissKeyboard"}],"url":"\/documentation\/yababa\/stripegatewayviewcontroller\/ondismisskeyboard()"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"onDismissKeyboard"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onDismissKeyboard"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"onDismissKeyboard"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1StripeGatewayViewController\/title","value":"StripeGatewayViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1StripeGatewayViewController\/fragments","value":[{"kind":"identifier","text":"StripeGatewayViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1StripeGatewayViewController~1onDismissKeyboard()\/title","value":"onDismissKeyboard"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1StripeGatewayViewController~1onDismissKeyboard()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onDismissKeyboard"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}