{"variants":[{"paths":["\/documentation\/yababa\/applelogin\/asauthorizationcontrollerpresentationcontextproviding-implementations"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/yababa\/applelogin\/asauthorizationcontrollerpresentationcontextproviding-implementations"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"identifier":{"url":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AppleLogin\/ASAuthorizationControllerPresentationContextProviding-Implementations","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AppleLogin\/presentationAnchor(for:)"],"generated":true}],"kind":"article","metadata":{"modules":[{"name":"Yababa"}],"role":"collectionGroup","title":"ASAuthorizationControllerPresentationContextProviding Implementations"},"hierarchy":{"paths":[["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AppleLogin"]]},"references":{"doc://com.yababaGmbH.yababa/documentation/Yababa":{"role":"collection","title":"Yababa","abstract":[{"type":"text","text":"Getting Started"}],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa","kind":"symbol","type":"topic","url":"\/documentation\/yababa"},"doc://com.yababaGmbH.yababa/documentation/Yababa/AppleLogin/presentationAnchor(for:)":{"role":"symbol","title":"presentationAnchor(for:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"presentationAnchor"},{"kind":"text","text":"("},{"kind":"externalParam","text":"for"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ASAuthorizationController","preciseIdentifier":"c:objc(cs)ASAuthorizationController"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"ASPresentationAnchor","preciseIdentifier":"c:@T@ASPresentationAnchor"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AppleLogin\/presentationAnchor(for:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"presentationAnchorForAuthorizationController:"}],"url":"\/documentation\/yababa\/applelogin\/presentationanchor(for:)"},"doc://com.yababaGmbH.yababa/documentation/Yababa/AppleLogin":{"role":"symbol","title":"AppleLogin","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AppleLogin"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AppleLogin","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AppleLogin"}],"url":"\/documentation\/yababa\/applelogin"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AppleLogin\/presentationAnchor(for:)"],"generated":true}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1AppleLogin~1presentationAnchor(for:)\/title","value":"presentationAnchorForAuthorizationController:"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1AppleLogin~1presentationAnchor(for:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"presentationAnchorForAuthorizationController:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1AppleLogin\/title","value":"AppleLogin"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1AppleLogin\/fragments","value":[{"kind":"identifier","text":"AppleLogin"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}