{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"authorizationController"},{"kind":"text","text":"("},{"kind":"externalParam","text":"controller"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ASAuthorizationController","preciseIdentifier":"c:objc(cs)ASAuthorizationController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didCompleteWithAuthorization"},{"kind":"text","text":" "},{"kind":"internalParam","text":"authorization"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ASAuthorization","preciseIdentifier":"c:objc(cs)ASAuthorization"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/yababa\/applelogin\/authorizationcontroller(controller:didcompletewithauthorization:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/yababa\/applelogin\/authorizationcontroller(controller:didcompletewithauthorization:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AppleLogin\/authorizationController(controller:didCompleteWithAuthorization:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"ASAuthorizationControllerDelegate.authorizationController(controller:didCompleteWithAuthorization:)"},{"type":"text","text":"."}],"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"authorizationController:didCompleteWithAuthorization:"}],"role":"symbol","title":"authorizationController(controller:didCompleteWithAuthorization:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"authorizationController"},{"kind":"text","text":"("},{"kind":"externalParam","text":"controller"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ASAuthorizationController","preciseIdentifier":"c:objc(cs)ASAuthorizationController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didCompleteWithAuthorization"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ASAuthorization","preciseIdentifier":"c:objc(cs)ASAuthorization"},{"kind":"text","text":")"}],"symbolKind":"method","externalID":"c:@CM@Yababa@objc(cs)AppleLogin(im)authorizationController:didCompleteWithAuthorization:","modules":[{"name":"Yababa"}],"platforms":[{"beta":false,"unavailable":false,"name":"iOS","introducedAt":"13.0","deprecated":false}]},"hierarchy":{"paths":[["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AppleLogin","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AppleLogin\/ASAuthorizationControllerDelegate-Implementations"]]},"references":{"doc://com.yababaGmbH.yababa/documentation/Yababa/AppleLogin/authorizationController(controller:didCompleteWithAuthorization:)":{"role":"symbol","title":"authorizationController(controller:didCompleteWithAuthorization:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"authorizationController"},{"kind":"text","text":"("},{"kind":"externalParam","text":"controller"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ASAuthorizationController","preciseIdentifier":"c:objc(cs)ASAuthorizationController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didCompleteWithAuthorization"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ASAuthorization","preciseIdentifier":"c:objc(cs)ASAuthorization"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AppleLogin\/authorizationController(controller:didCompleteWithAuthorization:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"authorizationController:didCompleteWithAuthorization:"}],"url":"\/documentation\/yababa\/applelogin\/authorizationcontroller(controller:didcompletewithauthorization:)"},"doc://com.yababaGmbH.yababa/documentation/Yababa/AppleLogin/ASAuthorizationControllerDelegate-Implementations":{"role":"collectionGroup","title":"ASAuthorizationControllerDelegate Implementations","abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AppleLogin\/ASAuthorizationControllerDelegate-Implementations","kind":"article","type":"topic","url":"\/documentation\/yababa\/applelogin\/asauthorizationcontrollerdelegate-implementations"},"doc://com.yababaGmbH.yababa/documentation/Yababa":{"role":"collection","title":"Yababa","abstract":[{"type":"text","text":"Getting Started"}],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa","kind":"symbol","type":"topic","url":"\/documentation\/yababa"},"doc://com.yababaGmbH.yababa/documentation/Yababa/AppleLogin":{"role":"symbol","title":"AppleLogin","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AppleLogin"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AppleLogin","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AppleLogin"}],"url":"\/documentation\/yababa\/applelogin"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/platforms","value":[{"beta":false,"unavailable":false,"name":"iOS","introducedAt":"13.0","deprecated":false}]},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"authorizationController:didCompleteWithAuthorization:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"authorizationController:didCompleteWithAuthorization:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"authorizationController:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"ASAuthorizationController","preciseIdentifier":"c:objc(cs)ASAuthorizationController"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"controller"},{"kind":"text","text":" "},{"kind":"identifier","text":"didCompleteWithAuthorization:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"ASAuthorization","preciseIdentifier":"c:objc(cs)ASAuthorization"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"authorization"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1AppleLogin~1authorizationController(controller:didCompleteWithAuthorization:)\/title","value":"authorizationController:didCompleteWithAuthorization:"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1AppleLogin~1authorizationController(controller:didCompleteWithAuthorization:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"authorizationController:didCompleteWithAuthorization:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1AppleLogin\/title","value":"AppleLogin"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1AppleLogin\/fragments","value":[{"kind":"identifier","text":"AppleLogin"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}