{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"presentationAnchor"},{"kind":"text","text":"("},{"kind":"externalParam","text":"for"},{"kind":"text","text":" "},{"kind":"internalParam","text":"controller"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ASAuthorizationController","preciseIdentifier":"c:objc(cs)ASAuthorizationController"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"ASPresentationAnchor","preciseIdentifier":"c:@T@ASPresentationAnchor"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/yababa\/applelogin\/presentationanchor(for:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/yababa\/applelogin\/presentationanchor(for:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AppleLogin\/presentationAnchor(for:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"ASAuthorizationControllerPresentationContextProviding.presentationAnchor(for:)"},{"type":"text","text":"."}],"kind":"symbol","metadata":{"modules":[{"name":"Yababa"}],"navigatorTitle":[{"kind":"identifier","text":"presentationAnchorForAuthorizationController:"}],"role":"symbol","title":"presentationAnchor(for:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"presentationAnchor"},{"kind":"text","text":"("},{"kind":"externalParam","text":"for"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ASAuthorizationController","preciseIdentifier":"c:objc(cs)ASAuthorizationController"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"ASPresentationAnchor","preciseIdentifier":"c:@T@ASPresentationAnchor"}],"symbolKind":"method","externalID":"c:@CM@Yababa@objc(cs)AppleLogin(im)presentationAnchorForAuthorizationController:","extendedModule":"Yababa","platforms":[{"beta":false,"unavailable":false,"name":"iOS","introducedAt":"13.0","deprecated":false}]},"hierarchy":{"paths":[["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AppleLogin","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AppleLogin\/ASAuthorizationControllerPresentationContextProviding-Implementations"]]},"references":{"doc://com.yababaGmbH.yababa/documentation/Yababa/AppleLogin/presentationAnchor(for:)":{"role":"symbol","title":"presentationAnchor(for:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"presentationAnchor"},{"kind":"text","text":"("},{"kind":"externalParam","text":"for"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ASAuthorizationController","preciseIdentifier":"c:objc(cs)ASAuthorizationController"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"ASPresentationAnchor","preciseIdentifier":"c:@T@ASPresentationAnchor"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AppleLogin\/presentationAnchor(for:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"presentationAnchorForAuthorizationController:"}],"url":"\/documentation\/yababa\/applelogin\/presentationanchor(for:)"},"doc://com.yababaGmbH.yababa/documentation/Yababa/AppleLogin":{"role":"symbol","title":"AppleLogin","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AppleLogin"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AppleLogin","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AppleLogin"}],"url":"\/documentation\/yababa\/applelogin"},"doc://com.yababaGmbH.yababa/documentation/Yababa":{"role":"collection","title":"Yababa","abstract":[{"type":"text","text":"Getting Started"}],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa","kind":"symbol","type":"topic","url":"\/documentation\/yababa"},"doc://com.yababaGmbH.yababa/documentation/Yababa/AppleLogin/ASAuthorizationControllerPresentationContextProviding-Implementations":{"role":"collectionGroup","title":"ASAuthorizationControllerPresentationContextProviding Implementations","abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AppleLogin\/ASAuthorizationControllerPresentationContextProviding-Implementations","kind":"article","type":"topic","url":"\/documentation\/yababa\/applelogin\/asauthorizationcontrollerpresentationcontextproviding-implementations"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/platforms","value":[{"beta":false,"unavailable":false,"name":"iOS","introducedAt":"13.0","deprecated":false}]},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"presentationAnchorForAuthorizationController:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"presentationAnchorForAuthorizationController:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"UIWindow","preciseIdentifier":"c:objc(cs)UIWindow"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"presentationAnchorForAuthorizationController:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"ASAuthorizationController","preciseIdentifier":"c:objc(cs)ASAuthorizationController"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"controller"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1AppleLogin~1presentationAnchor(for:)\/title","value":"presentationAnchorForAuthorizationController:"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1AppleLogin~1presentationAnchor(for:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"presentationAnchorForAuthorizationController:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1AppleLogin\/title","value":"AppleLogin"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1AppleLogin\/fragments","value":[{"kind":"identifier","text":"AppleLogin"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}