{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"scrollViewDidScroll"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"scrollView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIScrollView","preciseIdentifier":"c:objc(cs)UIScrollView"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/yababa\/dynamiclayoutscreen\/scrollviewdidscroll(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/yababa\/dynamiclayoutscreen\/scrollviewdidscroll(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/DynamicLayoutScreen\/scrollViewDidScroll(_:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"UIScrollViewDelegate.scrollViewDidScroll(_:)"},{"type":"text","text":"."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"scrollViewDidScroll"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UIScrollView","preciseIdentifier":"c:objc(cs)UIScrollView"},{"kind":"text","text":")"}],"title":"scrollViewDidScroll(_:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@CM@Yababa@objc(cs)DynamicLayoutScreen(im)scrollViewDidScroll:","modules":[{"name":"Yababa"}],"navigatorTitle":[{"kind":"identifier","text":"scrollViewDidScroll:"}]},"hierarchy":{"paths":[["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/DynamicLayoutScreen","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/DynamicLayoutScreen\/UIScrollViewDelegate-Implementations"]]},"references":{"doc://com.yababaGmbH.yababa/documentation/Yababa/DynamicLayoutScreen/UIScrollViewDelegate-Implementations":{"role":"collectionGroup","title":"UIScrollViewDelegate Implementations","abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/DynamicLayoutScreen\/UIScrollViewDelegate-Implementations","kind":"article","type":"topic","url":"\/documentation\/yababa\/dynamiclayoutscreen\/uiscrollviewdelegate-implementations"},"doc://com.yababaGmbH.yababa/documentation/Yababa/DynamicLayoutScreen/scrollViewDidScroll(_:)":{"role":"symbol","title":"scrollViewDidScroll(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"scrollViewDidScroll"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UIScrollView","preciseIdentifier":"c:objc(cs)UIScrollView"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/DynamicLayoutScreen\/scrollViewDidScroll(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"scrollViewDidScroll:"}],"url":"\/documentation\/yababa\/dynamiclayoutscreen\/scrollviewdidscroll(_:)"},"doc://com.yababaGmbH.yababa/documentation/Yababa/DynamicLayoutScreen":{"role":"symbol","title":"DynamicLayoutScreen","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DynamicLayoutScreen"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/DynamicLayoutScreen","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DynamicLayoutScreen"}],"url":"\/documentation\/yababa\/dynamiclayoutscreen"},"doc://com.yababaGmbH.yababa/documentation/Yababa":{"role":"collection","title":"Yababa","abstract":[{"type":"text","text":"Getting Started"}],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa","kind":"symbol","type":"topic","url":"\/documentation\/yababa"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"scrollViewDidScroll:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"scrollViewDidScroll:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"scrollViewDidScroll:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UIScrollView","preciseIdentifier":"c:objc(cs)UIScrollView"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"scrollView"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1DynamicLayoutScreen~1scrollViewDidScroll(_:)\/title","value":"scrollViewDidScroll:"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1DynamicLayoutScreen~1scrollViewDidScroll(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"scrollViewDidScroll:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1DynamicLayoutScreen\/title","value":"DynamicLayoutScreen"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1DynamicLayoutScreen\/fragments","value":[{"kind":"identifier","text":"DynamicLayoutScreen"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}