{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@IBOutlet"},{"kind":"text","text":" "},{"kind":"keyword","text":"weak"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"searchBar"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UISearchBar","preciseIdentifier":"c:objc(cs)UISearchBar"},{"kind":"text","text":"!"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/yababa\/catalogueviewcontroller\/searchbar"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/yababa\/catalogueviewcontroller\/searchbar"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CatalogueViewController\/searchBar","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"searchBar"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UISearchBar","preciseIdentifier":"c:objc(cs)UISearchBar"},{"kind":"text","text":"!"}],"title":"searchBar","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:@M@Yababa@objc(cs)CatalogueViewController(py)searchBar","modules":[{"name":"Yababa"}],"navigatorTitle":[{"kind":"identifier","text":"searchBar"}]},"hierarchy":{"paths":[["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CatalogueViewController"]]},"references":{"doc://com.yababaGmbH.yababa/documentation/Yababa/CatalogueViewController/searchBar":{"role":"symbol","title":"searchBar","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"searchBar"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UISearchBar","preciseIdentifier":"c:objc(cs)UISearchBar"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CatalogueViewController\/searchBar","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"searchBar"}],"url":"\/documentation\/yababa\/catalogueviewcontroller\/searchbar"},"doc://com.yababaGmbH.yababa/documentation/Yababa/CatalogueViewController":{"role":"symbol","title":"CatalogueViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CatalogueViewController"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CatalogueViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CatalogueViewController"}],"url":"\/documentation\/yababa\/catalogueviewcontroller"},"doc://com.yababaGmbH.yababa/documentation/Yababa":{"role":"collection","title":"Yababa","abstract":[{"type":"text","text":"Getting Started"}],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa","kind":"symbol","type":"topic","url":"\/documentation\/yababa"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"searchBar"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"searchBar"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"weak"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"UISearchBar","preciseIdentifier":"c:objc(cs)UISearchBar"},{"kind":"text","text":" * "},{"kind":"identifier","text":"searchBar"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1CatalogueViewController~1searchBar\/title","value":"searchBar"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1CatalogueViewController~1searchBar\/fragments","value":[{"kind":"identifier","text":"searchBar"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1CatalogueViewController\/title","value":"CatalogueViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1CatalogueViewController\/fragments","value":[{"kind":"identifier","text":"CatalogueViewController"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}