{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setup"},{"kind":"text","text":"("},{"kind":"externalParam","text":"voucher"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/VoucherView","preciseIdentifier":"c:@M@Yababa@objc(cs)VoucherView","text":"VoucherView"},{"kind":"text","text":"."},{"kind":"typeIdentifier","identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/VoucherView\/Data","preciseIdentifier":"s:6Yababa11VoucherViewC4DataV","text":"Data"},{"kind":"text","text":", "},{"kind":"externalParam","text":"userSelectedVoucherCode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?)"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/yababa\/vouchercollectionviewcell\/setup(voucher:userselectedvouchercode:)"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/VoucherCollectionViewCell\/setup(voucher:userSelectedVoucherCode:)","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setup"},{"kind":"text","text":"("},{"kind":"externalParam","text":"voucher"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"VoucherView","preciseIdentifier":"c:@M@Yababa@objc(cs)VoucherView"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"Data","preciseIdentifier":"s:6Yababa11VoucherViewC4DataV"},{"kind":"text","text":", "},{"kind":"externalParam","text":"userSelectedVoucherCode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?)"}],"title":"setup(voucher:userSelectedVoucherCode:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"s:6Yababa25VoucherCollectionViewCellC5setup7voucher012userSelectedB4CodeyAA0bD0C4DataV_SSSgtF","modules":[{"name":"Yababa"}]},"hierarchy":{"paths":[["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/VoucherCollectionViewCell"]]},"references":{"doc://com.yababaGmbH.yababa/documentation/Yababa/VoucherCollectionViewCell":{"role":"symbol","title":"VoucherCollectionViewCell","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"VoucherCollectionViewCell"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/VoucherCollectionViewCell","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"VoucherCollectionViewCell"}],"url":"\/documentation\/yababa\/vouchercollectionviewcell"},"doc://com.yababaGmbH.yababa/documentation/Yababa/VoucherCollectionViewCell/setup(voucher:userSelectedVoucherCode:)":{"role":"symbol","title":"setup(voucher:userSelectedVoucherCode:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setup"},{"kind":"text","text":"("},{"kind":"externalParam","text":"voucher"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"VoucherView","preciseIdentifier":"c:@M@Yababa@objc(cs)VoucherView"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"Data","preciseIdentifier":"s:6Yababa11VoucherViewC4DataV"},{"kind":"text","text":", "},{"kind":"externalParam","text":"userSelectedVoucherCode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?)"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/VoucherCollectionViewCell\/setup(voucher:userSelectedVoucherCode:)","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/vouchercollectionviewcell\/setup(voucher:userselectedvouchercode:)"},"doc://com.yababaGmbH.yababa/documentation/Yababa/VoucherView/Data":{"role":"symbol","title":"VoucherView.Data","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"Data"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/VoucherView\/Data","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Data"}],"url":"\/documentation\/yababa\/voucherview\/data"},"doc://com.yababaGmbH.yababa/documentation/Yababa":{"role":"collection","title":"Yababa","abstract":[{"type":"text","text":"Getting Started"}],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa","kind":"symbol","type":"topic","url":"\/documentation\/yababa"},"doc://com.yababaGmbH.yababa/documentation/Yababa/VoucherView":{"role":"symbol","title":"VoucherView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"VoucherView"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/VoucherView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"VoucherView"}],"url":"\/documentation\/yababa\/voucherview"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1VoucherCollectionViewCell\/title","value":"VoucherCollectionViewCell"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1VoucherCollectionViewCell\/fragments","value":[{"kind":"identifier","text":"VoucherCollectionViewCell"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1VoucherView\/title","value":"VoucherView"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1VoucherView\/fragments","value":[{"kind":"identifier","text":"VoucherView"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}