{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"voucherView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/VoucherView","preciseIdentifier":"c:@M@Yababa@objc(cs)VoucherView","text":"VoucherView"},{"kind":"text","text":"!"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/yababa\/vouchercollectionviewcell\/voucherview"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/VoucherCollectionViewCell\/voucherView","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"voucherView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"VoucherView","preciseIdentifier":"c:@M@Yababa@objc(cs)VoucherView"},{"kind":"text","text":"!"}],"title":"voucherView","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"s:6Yababa25VoucherCollectionViewCellC07voucherD0AA0bD0CSgvp","modules":[{"name":"Yababa"}]},"hierarchy":{"paths":[["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/VoucherCollectionViewCell"]]},"references":{"doc://com.yababaGmbH.yababa/documentation/Yababa":{"role":"collection","title":"Yababa","abstract":[{"type":"text","text":"Getting Started"}],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa","kind":"symbol","type":"topic","url":"\/documentation\/yababa"},"doc://com.yababaGmbH.yababa/documentation/Yababa/VoucherView":{"role":"symbol","title":"VoucherView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"VoucherView"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/VoucherView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"VoucherView"}],"url":"\/documentation\/yababa\/voucherview"},"doc://com.yababaGmbH.yababa/documentation/Yababa/VoucherCollectionViewCell/voucherView":{"role":"symbol","title":"voucherView","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"voucherView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"VoucherView","preciseIdentifier":"c:@M@Yababa@objc(cs)VoucherView"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/VoucherCollectionViewCell\/voucherView","kind":"symbol","type":"topic","url":"\/documentation\/yababa\/vouchercollectionviewcell\/voucherview"},"doc://com.yababaGmbH.yababa/documentation/Yababa/VoucherCollectionViewCell":{"role":"symbol","title":"VoucherCollectionViewCell","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"VoucherCollectionViewCell"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/VoucherCollectionViewCell","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"VoucherCollectionViewCell"}],"url":"\/documentation\/yababa\/vouchercollectionviewcell"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1VoucherView\/title","value":"VoucherView"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1VoucherView\/fragments","value":[{"kind":"identifier","text":"VoucherView"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1VoucherCollectionViewCell\/title","value":"VoucherCollectionViewCell"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1VoucherCollectionViewCell\/fragments","value":[{"kind":"identifier","text":"VoucherCollectionViewCell"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}