{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@IBAction"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"openCreateActivity"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"segue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIStoryboardSegue","preciseIdentifier":"c:objc(cs)UIStoryboardSegue"},{"kind":"text","text":"? = nil)"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/yababa\/tabbarcontroller\/opencreateactivity(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/yababa\/tabbarcontroller\/opencreateactivity(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/TabBarController\/openCreateActivity(_:)","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"openCreateActivity"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UIStoryboardSegue","preciseIdentifier":"c:objc(cs)UIStoryboardSegue"},{"kind":"text","text":"?)"}],"title":"openCreateActivity(_:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@M@Yababa@objc(cs)TabBarController(im)openCreateActivity:","modules":[{"name":"Yababa"}],"navigatorTitle":[{"kind":"identifier","text":"openCreateActivity:"}]},"hierarchy":{"paths":[["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/TabBarController"]]},"references":{"doc://com.yababaGmbH.yababa/documentation/Yababa/TabBarController/openCreateActivity(_:)":{"role":"symbol","title":"openCreateActivity(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"openCreateActivity"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UIStoryboardSegue","preciseIdentifier":"c:objc(cs)UIStoryboardSegue"},{"kind":"text","text":"?)"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/TabBarController\/openCreateActivity(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"openCreateActivity:"}],"url":"\/documentation\/yababa\/tabbarcontroller\/opencreateactivity(_:)"},"doc://com.yababaGmbH.yababa/documentation/Yababa":{"role":"collection","title":"Yababa","abstract":[{"type":"text","text":"Getting Started"}],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa","kind":"symbol","type":"topic","url":"\/documentation\/yababa"},"doc://com.yababaGmbH.yababa/documentation/Yababa/TabBarController":{"role":"symbol","title":"TabBarController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TabBarController"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/TabBarController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"TabBarController"}],"url":"\/documentation\/yababa\/tabbarcontroller"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"openCreateActivity:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"openCreateActivity:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"openCreateActivity:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UIStoryboardSegue","preciseIdentifier":"c:objc(cs)UIStoryboardSegue"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"segue"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1TabBarController~1openCreateActivity(_:)\/title","value":"openCreateActivity:"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1TabBarController~1openCreateActivity(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"openCreateActivity:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1TabBarController\/title","value":"TabBarController"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1TabBarController\/fragments","value":[{"kind":"identifier","text":"TabBarController"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}