{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@IBAction"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onNext"},{"kind":"text","text":"()"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/yababa\/completeprofilesceneviewcontroller\/onnext()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/yababa\/completeprofilesceneviewcontroller\/onnext()"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CompleteProfileSceneViewController\/onNext()","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onNext"},{"kind":"text","text":"()"}],"title":"onNext()","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@M@Yababa@objc(cs)CompleteProfileSceneViewController(im)onNext","modules":[{"name":"Yababa"}],"navigatorTitle":[{"kind":"identifier","text":"onNext"}]},"hierarchy":{"paths":[["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CompleteProfileSceneViewController"]]},"references":{"doc://com.yababaGmbH.yababa/documentation/Yababa/CompleteProfileSceneViewController":{"role":"symbol","title":"CompleteProfileSceneViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CompleteProfileSceneViewController"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CompleteProfileSceneViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CompleteProfileSceneViewController"}],"url":"\/documentation\/yababa\/completeprofilesceneviewcontroller"},"doc://com.yababaGmbH.yababa/documentation/Yababa":{"role":"collection","title":"Yababa","abstract":[{"type":"text","text":"Getting Started"}],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa","kind":"symbol","type":"topic","url":"\/documentation\/yababa"},"doc://com.yababaGmbH.yababa/documentation/Yababa/CompleteProfileSceneViewController/onNext()":{"role":"symbol","title":"onNext()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onNext"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CompleteProfileSceneViewController\/onNext()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"onNext"}],"url":"\/documentation\/yababa\/completeprofilesceneviewcontroller\/onnext()"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"onNext"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onNext"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"onNext"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1CompleteProfileSceneViewController\/title","value":"CompleteProfileSceneViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1CompleteProfileSceneViewController\/fragments","value":[{"kind":"identifier","text":"CompleteProfileSceneViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1CompleteProfileSceneViewController~1onNext()\/title","value":"onNext"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1CompleteProfileSceneViewController~1onNext()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onNext"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}