{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"popupViewTapped"},{"kind":"text","text":"()"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/yababa\/addcouponpopup\/popupviewtapped()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/yababa\/addcouponpopup\/popupviewtapped()"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AddCouponPopup\/popupViewTapped()","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"popupViewTapped"},{"kind":"text","text":"()"}],"title":"popupViewTapped()","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@M@Yababa@objc(cs)AddCouponPopup(im)popupViewTapped","modules":[{"name":"Yababa"}],"navigatorTitle":[{"kind":"identifier","text":"popupViewTapped"}]},"hierarchy":{"paths":[["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AddCouponPopup"]]},"references":{"doc://com.yababaGmbH.yababa/documentation/Yababa":{"role":"collection","title":"Yababa","abstract":[{"type":"text","text":"Getting Started"}],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa","kind":"symbol","type":"topic","url":"\/documentation\/yababa"},"doc://com.yababaGmbH.yababa/documentation/Yababa/AddCouponPopup/popupViewTapped()":{"role":"symbol","title":"popupViewTapped()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"popupViewTapped"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AddCouponPopup\/popupViewTapped()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"popupViewTapped"}],"url":"\/documentation\/yababa\/addcouponpopup\/popupviewtapped()"},"doc://com.yababaGmbH.yababa/documentation/Yababa/AddCouponPopup":{"role":"symbol","title":"AddCouponPopup","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AddCouponPopup"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/AddCouponPopup","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AddCouponPopup"}],"url":"\/documentation\/yababa\/addcouponpopup"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"popupViewTapped"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"popupViewTapped"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"popupViewTapped"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1AddCouponPopup~1popupViewTapped()\/title","value":"popupViewTapped"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1AddCouponPopup~1popupViewTapped()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"popupViewTapped"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1AddCouponPopup\/title","value":"AddCouponPopup"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1AddCouponPopup\/fragments","value":[{"kind":"identifier","text":"AddCouponPopup"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}