{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@IBOutlet"},{"kind":"text","text":" "},{"kind":"keyword","text":"weak"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"selectedCardIcon"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIImageView","preciseIdentifier":"c:objc(cs)UIImageView"},{"kind":"text","text":"!"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/yababa\/cardselectioncontroller\/selectedcardicon"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/yababa\/cardselectioncontroller\/selectedcardicon"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CardSelectionController\/selectedCardIcon","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"selectedCardIcon"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIImageView","preciseIdentifier":"c:objc(cs)UIImageView"},{"kind":"text","text":"!"}],"title":"selectedCardIcon","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:@M@Yababa@objc(cs)CardSelectionController(py)selectedCardIcon","modules":[{"name":"Yababa"}],"navigatorTitle":[{"kind":"identifier","text":"selectedCardIcon"}]},"hierarchy":{"paths":[["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CardSelectionController"]]},"references":{"doc://com.yababaGmbH.yababa/documentation/Yababa/CardSelectionController/selectedCardIcon":{"role":"symbol","title":"selectedCardIcon","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"selectedCardIcon"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIImageView","preciseIdentifier":"c:objc(cs)UIImageView"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CardSelectionController\/selectedCardIcon","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"selectedCardIcon"}],"url":"\/documentation\/yababa\/cardselectioncontroller\/selectedcardicon"},"doc://com.yababaGmbH.yababa/documentation/Yababa/CardSelectionController":{"role":"symbol","title":"CardSelectionController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CardSelectionController"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/CardSelectionController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CardSelectionController"}],"url":"\/documentation\/yababa\/cardselectioncontroller"},"doc://com.yababaGmbH.yababa/documentation/Yababa":{"role":"collection","title":"Yababa","abstract":[{"type":"text","text":"Getting Started"}],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa","kind":"symbol","type":"topic","url":"\/documentation\/yababa"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"selectedCardIcon"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"selectedCardIcon"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"weak"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"UIImageView","preciseIdentifier":"c:objc(cs)UIImageView"},{"kind":"text","text":" * "},{"kind":"identifier","text":"selectedCardIcon"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1CardSelectionController~1selectedCardIcon\/title","value":"selectedCardIcon"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1CardSelectionController~1selectedCardIcon\/fragments","value":[{"kind":"identifier","text":"selectedCardIcon"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1CardSelectionController\/title","value":"CardSelectionController"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1CardSelectionController\/fragments","value":[{"kind":"identifier","text":"CardSelectionController"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}