{"variants":[{"paths":["\/documentation\/yababa\/myorderssceneviewcontroller\/uitableviewdatasource-implementations"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/yababa\/myorderssceneviewcontroller\/uitableviewdatasource-implementations"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"identifier":{"url":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/MyOrdersSceneViewController\/UITableViewDataSource-Implementations","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/MyOrdersSceneViewController\/tableView(_:cellForRowAt:)","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/MyOrdersSceneViewController\/tableView(_:numberOfRowsInSection:)"],"generated":true}],"kind":"article","metadata":{"modules":[{"name":"Yababa"}],"role":"collectionGroup","title":"UITableViewDataSource Implementations"},"hierarchy":{"paths":[["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/MyOrdersSceneViewController"]]},"references":{"doc://com.yababaGmbH.yababa/documentation/Yababa/MyOrdersSceneViewController/tableView(_:cellForRowAt:)":{"role":"symbol","title":"tableView(_:cellForRowAt:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"tableView"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UITableView","preciseIdentifier":"c:objc(cs)UITableView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"cellForRowAt"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"IndexPath","preciseIdentifier":"s:10Foundation9IndexPathV"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"UITableViewCell","preciseIdentifier":"c:objc(cs)UITableViewCell"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/MyOrdersSceneViewController\/tableView(_:cellForRowAt:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"tableView:cellForRowAtIndexPath:"}],"url":"\/documentation\/yababa\/myorderssceneviewcontroller\/tableview(_:cellforrowat:)"},"doc://com.yababaGmbH.yababa/documentation/Yababa":{"role":"collection","title":"Yababa","abstract":[{"type":"text","text":"Getting Started"}],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa","kind":"symbol","type":"topic","url":"\/documentation\/yababa"},"doc://com.yababaGmbH.yababa/documentation/Yababa/MyOrdersSceneViewController":{"role":"symbol","title":"MyOrdersSceneViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MyOrdersSceneViewController"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/MyOrdersSceneViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MyOrdersSceneViewController"}],"url":"\/documentation\/yababa\/myorderssceneviewcontroller"},"doc://com.yababaGmbH.yababa/documentation/Yababa/MyOrdersSceneViewController/tableView(_:numberOfRowsInSection:)":{"role":"symbol","title":"tableView(_:numberOfRowsInSection:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"tableView"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UITableView","preciseIdentifier":"c:objc(cs)UITableView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"numberOfRowsInSection"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/MyOrdersSceneViewController\/tableView(_:numberOfRowsInSection:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"tableView:numberOfRowsInSection:"}],"url":"\/documentation\/yababa\/myorderssceneviewcontroller\/tableview(_:numberofrowsinsection:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/MyOrdersSceneViewController\/tableView(_:cellForRowAt:)","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/MyOrdersSceneViewController\/tableView(_:numberOfRowsInSection:)"],"generated":true}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1MyOrdersSceneViewController~1tableView(_:cellForRowAt:)\/title","value":"tableView:cellForRowAtIndexPath:"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1MyOrdersSceneViewController~1tableView(_:cellForRowAt:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"tableView:cellForRowAtIndexPath:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1MyOrdersSceneViewController\/title","value":"MyOrdersSceneViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1MyOrdersSceneViewController\/fragments","value":[{"kind":"identifier","text":"MyOrdersSceneViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1MyOrdersSceneViewController~1tableView(_:numberOfRowsInSection:)\/title","value":"tableView:numberOfRowsInSection:"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1MyOrdersSceneViewController~1tableView(_:numberOfRowsInSection:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"tableView:numberOfRowsInSection:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}