{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setUserPushSubscriptionStatus"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"status"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/SubscriptionStatus","preciseIdentifier":"c:@M@Yababa@E@SubscriptionStatus","text":"SubscriptionStatus"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/yababa\/localuserstatemanager\/setuserpushsubscriptionstatus(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/yababa\/localuserstatemanager\/setuserpushsubscriptionstatus(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/LocalUserStateManager\/setUserPushSubscriptionStatus(_:)","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setUserPushSubscriptionStatus"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"SubscriptionStatus","preciseIdentifier":"c:@M@Yababa@E@SubscriptionStatus"},{"kind":"text","text":")"}],"title":"setUserPushSubscriptionStatus(_:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@M@Yababa@objc(cs)LocalUserStateManager(im)setUserPushSubscriptionStatus:","modules":[{"name":"Yababa"}],"navigatorTitle":[{"kind":"identifier","text":"setUserPushSubscriptionStatus:"}]},"hierarchy":{"paths":[["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/LocalUserStateManager"]]},"references":{"doc://com.yababaGmbH.yababa/documentation/Yababa":{"role":"collection","title":"Yababa","abstract":[{"type":"text","text":"Getting Started"}],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa","kind":"symbol","type":"topic","url":"\/documentation\/yababa"},"doc://com.yababaGmbH.yababa/documentation/Yababa/LocalUserStateManager/setUserPushSubscriptionStatus(_:)":{"role":"symbol","title":"setUserPushSubscriptionStatus(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setUserPushSubscriptionStatus"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"SubscriptionStatus","preciseIdentifier":"c:@M@Yababa@E@SubscriptionStatus"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/LocalUserStateManager\/setUserPushSubscriptionStatus(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"setUserPushSubscriptionStatus:"}],"url":"\/documentation\/yababa\/localuserstatemanager\/setuserpushsubscriptionstatus(_:)"},"doc://com.yababaGmbH.yababa/documentation/Yababa/SubscriptionStatus":{"role":"symbol","title":"SubscriptionStatus","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SubscriptionStatus"}],"abstract":[{"type":"text","text":"OPTED_IN: subscribed, and explicitly opted in."},{"type":"text","text":" "},{"type":"text","text":"SUBSCRIBED: subscribed, but not explicitly opted in."},{"type":"text","text":" "},{"type":"text","text":"UNSUBSCRIBED: unsubscribed and\/or explicitly opted out."}],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/SubscriptionStatus","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SubscriptionStatus"}],"url":"\/documentation\/yababa\/subscriptionstatus"},"doc://com.yababaGmbH.yababa/documentation/Yababa/LocalUserStateManager":{"role":"symbol","title":"LocalUserStateManager","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"LocalUserStateManager"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/LocalUserStateManager","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"LocalUserStateManager"}],"url":"\/documentation\/yababa\/localuserstatemanager"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"setUserPushSubscriptionStatus:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setUserPushSubscriptionStatus:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"setUserPushSubscriptionStatus:"},{"kind":"text","text":"("},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/SubscriptionStatus","preciseIdentifier":"c:@M@Yababa@E@SubscriptionStatus","text":"SubscriptionStatus"},{"kind":"text","text":")"},{"kind":"internalParam","text":"status"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1LocalUserStateManager~1setUserPushSubscriptionStatus(_:)\/title","value":"setUserPushSubscriptionStatus:"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1LocalUserStateManager~1setUserPushSubscriptionStatus(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setUserPushSubscriptionStatus:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1SubscriptionStatus\/title","value":"SubscriptionStatus"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1SubscriptionStatus\/fragments","value":[{"kind":"identifier","text":"SubscriptionStatus"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1LocalUserStateManager\/title","value":"LocalUserStateManager"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1LocalUserStateManager\/fragments","value":[{"kind":"identifier","text":"LocalUserStateManager"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}