{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setUserUnreadFreshChatMessage"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"status"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/yababa\/localuserstatemanager\/setuserunreadfreshchatmessage(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/yababa\/localuserstatemanager\/setuserunreadfreshchatmessage(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/LocalUserStateManager\/setUserUnreadFreshChatMessage(_:)","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setUserUnreadFreshChatMessage"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"title":"setUserUnreadFreshChatMessage(_:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@M@Yababa@objc(cs)LocalUserStateManager(im)setUserUnreadFreshChatMessage:","modules":[{"name":"Yababa"}],"navigatorTitle":[{"kind":"identifier","text":"setUserUnreadFreshChatMessage:"}]},"hierarchy":{"paths":[["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/LocalUserStateManager"]]},"references":{"doc://com.yababaGmbH.yababa/documentation/Yababa":{"role":"collection","title":"Yababa","abstract":[{"type":"text","text":"Getting Started"}],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa","kind":"symbol","type":"topic","url":"\/documentation\/yababa"},"doc://com.yababaGmbH.yababa/documentation/Yababa/LocalUserStateManager":{"role":"symbol","title":"LocalUserStateManager","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"LocalUserStateManager"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/LocalUserStateManager","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"LocalUserStateManager"}],"url":"\/documentation\/yababa\/localuserstatemanager"},"doc://com.yababaGmbH.yababa/documentation/Yababa/LocalUserStateManager/setUserUnreadFreshChatMessage(_:)":{"role":"symbol","title":"setUserUnreadFreshChatMessage(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setUserUnreadFreshChatMessage"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/LocalUserStateManager\/setUserUnreadFreshChatMessage(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"setUserUnreadFreshChatMessage:"}],"url":"\/documentation\/yababa\/localuserstatemanager\/setuserunreadfreshchatmessage(_:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"setUserUnreadFreshChatMessage:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setUserUnreadFreshChatMessage:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"setUserUnreadFreshChatMessage:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":")"},{"kind":"internalParam","text":"status"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1LocalUserStateManager\/title","value":"LocalUserStateManager"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1LocalUserStateManager\/fragments","value":[{"kind":"identifier","text":"LocalUserStateManager"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1LocalUserStateManager~1setUserUnreadFreshChatMessage(_:)\/title","value":"setUserUnreadFreshChatMessage:"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1LocalUserStateManager~1setUserUnreadFreshChatMessage(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setUserUnreadFreshChatMessage:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}