{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"hideSensitiveDataView"},{"kind":"text","text":"("},{"kind":"externalParam","text":"sensitiveView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/yababa\/uxcamutils\/hidesensitivedataview(sensitiveview:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/yababa\/uxcamutils\/hidesensitivedataview(sensitiveview:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/UXCamUtils\/hideSensitiveDataView(sensitiveView:)","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"hideSensitiveDataView"},{"kind":"text","text":"("},{"kind":"externalParam","text":"sensitiveView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"},{"kind":"text","text":")"}],"title":"hideSensitiveDataView(sensitiveView:)","roleHeading":"Type Method","role":"symbol","symbolKind":"method","externalID":"c:@M@Yababa@objc(cs)UXCamUtils(cm)hideSensitiveDataViewWithSensitiveView:","modules":[{"name":"Yababa"}],"navigatorTitle":[{"kind":"identifier","text":"hideSensitiveDataViewWithSensitiveView:"}]},"hierarchy":{"paths":[["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/UXCamUtils"]]},"references":{"doc://com.yababaGmbH.yababa/documentation/Yababa/UXCamUtils/hideSensitiveDataView(sensitiveView:)":{"role":"symbol","title":"hideSensitiveDataView(sensitiveView:)","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"hideSensitiveDataView"},{"kind":"text","text":"("},{"kind":"externalParam","text":"sensitiveView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/UXCamUtils\/hideSensitiveDataView(sensitiveView:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"hideSensitiveDataViewWithSensitiveView:"}],"url":"\/documentation\/yababa\/uxcamutils\/hidesensitivedataview(sensitiveview:)"},"doc://com.yababaGmbH.yababa/documentation/Yababa/UXCamUtils":{"role":"symbol","title":"UXCamUtils","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"UXCamUtils"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/UXCamUtils","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"UXCamUtils"}],"url":"\/documentation\/yababa\/uxcamutils"},"doc://com.yababaGmbH.yababa/documentation/Yababa":{"role":"collection","title":"Yababa","abstract":[{"type":"text","text":"Getting Started"}],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa","kind":"symbol","type":"topic","url":"\/documentation\/yababa"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Method"},{"op":"replace","path":"\/metadata\/title","value":"hideSensitiveDataViewWithSensitiveView:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"hideSensitiveDataViewWithSensitiveView:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"+ ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"hideSensitiveDataViewWithSensitiveView:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"sensitiveView"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1UXCamUtils~1hideSensitiveDataView(sensitiveView:)\/title","value":"hideSensitiveDataViewWithSensitiveView:"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1UXCamUtils~1hideSensitiveDataView(sensitiveView:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"hideSensitiveDataViewWithSensitiveView:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1UXCamUtils\/title","value":"UXCamUtils"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1UXCamUtils\/fragments","value":[{"kind":"identifier","text":"UXCamUtils"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}