{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"optional"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"response"},{"kind":"text","text":"("},{"kind":"externalParam","text":"forSignin"},{"kind":"text","text":" "},{"kind":"internalParam","text":"loginResponse"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/LoginResponseClass","preciseIdentifier":"c:objc(cs)LoginResponseClass","text":"LoginResponseClass"},{"kind":"text","text":"!)"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/yababa\/indelegate\/response(forsignin:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/yababa\/indelegate\/response(forsignin:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/InDelegate\/response(forSignin:)","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"ResponseForSignin:"}],"role":"symbol","title":"response(forSignin:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"response"},{"kind":"text","text":"("},{"kind":"externalParam","text":"forSignin"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"LoginResponseClass","preciseIdentifier":"c:objc(cs)LoginResponseClass"},{"kind":"text","text":"!)"}],"symbolKind":"method","externalID":"c:objc(pl)InDelegate(im)ResponseForSignin:","required":true,"modules":[{"name":"Yababa"}]},"hierarchy":{"paths":[["doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa","doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/InDelegate"]]},"references":{"doc://com.yababaGmbH.yababa/documentation/Yababa/LoginResponseClass":{"role":"symbol","title":"LoginResponseClass","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"LoginResponseClass"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/LoginResponseClass","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"LoginResponseClass"}],"url":"\/documentation\/yababa\/loginresponseclass"},"doc://com.yababaGmbH.yababa/documentation/Yababa":{"role":"collection","title":"Yababa","abstract":[{"type":"text","text":"Getting Started"}],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa","kind":"symbol","type":"topic","url":"\/documentation\/yababa"},"doc://com.yababaGmbH.yababa/documentation/Yababa/InDelegate":{"role":"symbol","title":"InDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"InDelegate"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/InDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"InDelegate"}],"url":"\/documentation\/yababa\/indelegate"},"doc://com.yababaGmbH.yababa/documentation/Yababa/InDelegate/response(forSignin:)":{"navigatorTitle":[{"kind":"identifier","text":"ResponseForSignin:"}],"role":"symbol","title":"response(forSignin:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"response"},{"kind":"text","text":"("},{"kind":"externalParam","text":"forSignin"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"LoginResponseClass","preciseIdentifier":"c:objc(cs)LoginResponseClass"},{"kind":"text","text":"!)"}],"abstract":[],"identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/InDelegate\/response(forSignin:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/yababa\/indelegate\/response(forsignin:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"ResponseForSignin:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"ResponseForSignin:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"ResponseForSignin:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.yababaGmbH.yababa\/documentation\/Yababa\/LoginResponseClass","preciseIdentifier":"c:objc(cs)LoginResponseClass","text":"LoginResponseClass"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"loginResponse"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1LoginResponseClass\/title","value":"LoginResponseClass"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1LoginResponseClass\/fragments","value":[{"kind":"identifier","text":"LoginResponseClass"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1InDelegate\/title","value":"InDelegate"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1InDelegate\/fragments","value":[{"kind":"identifier","text":"InDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1InDelegate~1response(forSignin:)\/title","value":"ResponseForSignin:"},{"op":"replace","path":"\/references\/doc:~1~1com.yababaGmbH.yababa~1documentation~1Yababa~1InDelegate~1response(forSignin:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"ResponseForSignin:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}